package cn.ibizlab.plm.insight.logic.insight_viewlogic.use_cur_template;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.insight.domain.insight_view insight_viewuse_cur_templatedefault;
                global cn.ibizlab.plm.core.base.domain.dyna_dashboard insight_viewuse_cur_templateboard_filter;
                global cn.ibizlab.plm.core.base.domain.dyna_dashboard insight_viewuse_cur_templateboard_page;
                global cn.ibizlab.plm.core.base.domain.dyna_dashboard insight_viewuse_cur_templatedynadashboard;
                global cn.ibizlab.plm.core.base.domain.dyna_dashboard insight_viewuse_cur_templatenew_board;
                    global cn.ibizlab.plm.core.base.service.Idyna_dashboardService dyna_dashboardservice;
        global cn.ibizlab.plm.core.insight.service.Iinsight_viewService iBzSysInsight_viewDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "insight_viewuse_cur_templatebegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "insight_viewuse_cur_templateend1"
            when
            then
                        update(insight_viewuse_cur_templatedefault);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_filter);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_page);//更新fact中变量值
                        update(insight_viewuse_cur_templatedynadashboard);//更新fact中变量值
                        update(insight_viewuse_cur_templatenew_board);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "insight_viewuse_cur_templatedebugparam1"
            when
            then
                        update(insight_viewuse_cur_templatedefault);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_filter);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_page);//更新fact中变量值
                        update(insight_viewuse_cur_templatedynadashboard);//更新fact中变量值
                        update(insight_viewuse_cur_templatenew_board);//更新fact中变量值
            end

            //逻辑处理节点[设置过滤参数]
            rule "prepareparam3"
            ruleflow-group "insight_viewuse_cur_templateprepareparam3"
            when
            then
                            insight_viewuse_cur_templateboard_filter.set("n_owner_id_eq",insight_viewuse_cur_templatedefault.get("owner_id"));
                        update(insight_viewuse_cur_templatedefault);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_filter);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_page);//更新fact中变量值
                        update(insight_viewuse_cur_templatedynadashboard);//更新fact中变量值
                        update(insight_viewuse_cur_templatenew_board);//更新fact中变量值
            end

            //逻辑处理节点[查询当前视图下的看板]
            rule "dedataset1"
            ruleflow-group "insight_viewuse_cur_templatededataset1"
            when
            then
                        update(insight_viewuse_cur_templatedefault);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_filter);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_page);//更新fact中变量值
                        update(insight_viewuse_cur_templatedynadashboard);//更新fact中变量值
                        update(insight_viewuse_cur_templatenew_board);//更新fact中变量值
            end

            //逻辑处理节点[获取选中看板id]
            rule "prepareparam1"
            ruleflow-group "insight_viewuse_cur_templateprepareparam1"
            when
            then
                            insight_viewuse_cur_templatedynadashboard.set("dynadashboardid",insight_viewuse_cur_templatedefault.get("dyna_dashboard_id"));
                        update(insight_viewuse_cur_templatedefault);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_filter);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_page);//更新fact中变量值
                        update(insight_viewuse_cur_templatedynadashboard);//更新fact中变量值
                        update(insight_viewuse_cur_templatenew_board);//更新fact中变量值
            end

            //逻辑处理节点[获取选中看板数据]
            rule "deaction1"
            ruleflow-group "insight_viewuse_cur_templatedeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(dyna_dashboardservice.get(insight_viewuse_cur_templatedynadashboard.getDynadashboardid()),insight_viewuse_cur_templatedynadashboard);
                        update(insight_viewuse_cur_templatedefault);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_filter);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_page);//更新fact中变量值
                        update(insight_viewuse_cur_templatedynadashboard);//更新fact中变量值
                        update(insight_viewuse_cur_templatenew_board);//更新fact中变量值
            end

            //逻辑处理节点[准备新看板参数]
            rule "prepareparam2"
            ruleflow-group "insight_viewuse_cur_templateprepareparam2"
            when
            then
                            insight_viewuse_cur_templatenew_board.set("dynadashboardname",insight_viewuse_cur_templatedynadashboard.get("dynadashboardname"));
                            insight_viewuse_cur_templatenew_board.set("modelid",insight_viewuse_cur_templatedynadashboard.get("modelid"));
                            insight_viewuse_cur_templatenew_board.set("ownertype","insight_view");
                            insight_viewuse_cur_templatenew_board.set("type","data");
                            insight_viewuse_cur_templatenew_board.set("model",insight_viewuse_cur_templatedynadashboard.get("model"));
                            insight_viewuse_cur_templatenew_board.set("appid",insight_viewuse_cur_templatedynadashboard.get("appid"));
                            insight_viewuse_cur_templatenew_board.set("ownerid",insight_viewuse_cur_templatedefault.get("id"));
                        update(insight_viewuse_cur_templatedefault);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_filter);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_page);//更新fact中变量值
                        update(insight_viewuse_cur_templatedynadashboard);//更新fact中变量值
                        update(insight_viewuse_cur_templatenew_board);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam2"
            ruleflow-group "insight_viewuse_cur_templatedebugparam2"
            when
            then
                        update(insight_viewuse_cur_templatedefault);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_filter);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_page);//更新fact中变量值
                        update(insight_viewuse_cur_templatedynadashboard);//更新fact中变量值
                        update(insight_viewuse_cur_templatenew_board);//更新fact中变量值
            end

            //逻辑处理节点[准备新看板参数]
            rule "prepareparam4"
            ruleflow-group "insight_viewuse_cur_templateprepareparam4"
            when
            then
                            insight_viewuse_cur_templatenew_board.set("dynadashboardid",insight_viewuse_cur_templatedefault.get("owner_id"));
                        update(insight_viewuse_cur_templatedefault);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_filter);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_page);//更新fact中变量值
                        update(insight_viewuse_cur_templatedynadashboard);//更新fact中变量值
                        update(insight_viewuse_cur_templatenew_board);//更新fact中变量值
            end

            //逻辑处理节点[生成报表]
            rule "rawsfcode1"
            ruleflow-group "insight_viewuse_cur_templaterawsfcode1"
            when
            then
                        update(insight_viewuse_cur_templatedefault);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_filter);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_page);//更新fact中变量值
                        update(insight_viewuse_cur_templatedynadashboard);//更新fact中变量值
                        update(insight_viewuse_cur_templatenew_board);//更新fact中变量值
            end

            //逻辑处理节点[创建看板]
            rule "deaction2"
            ruleflow-group "insight_viewuse_cur_templatedeaction2"
            when
            then
                        dyna_dashboardservice.create(insight_viewuse_cur_templatenew_board);
                        update(insight_viewuse_cur_templatedefault);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_filter);//更新fact中变量值
                        update(insight_viewuse_cur_templateboard_page);//更新fact中变量值
                        update(insight_viewuse_cur_templatedynadashboard);//更新fact中变量值
                        update(insight_viewuse_cur_templatenew_board);//更新fact中变量值
            end