package cn.ibizlab.plm.prodmgmt.logic.productlogic.activate;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productactivatedefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productactivateupdate_obj;
                    global cn.ibizlab.plm.core.prodmgmt.service.IproductService productservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IproductService iBzSysProductDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "productactivatebegin"
            when
            then
            end

            //逻辑处理节点[设置归档状态]
            rule "prepareparam1"
            ruleflow-group "productactivateprepareparam1"
            when
            then
                            productactivateupdate_obj.set("isarchived","0");
                            productactivateupdate_obj.set("id",productactivatedefault.get("id"));
                        update(productactivatedefault);//更新fact中变量值
                        update(productactivateupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[激活]
            rule "deaction1"
            ruleflow-group "productactivatedeaction1"
            when
            then
                        productservice.update(productactivateupdate_obj);
                        update(productactivatedefault);//更新fact中变量值
                        update(productactivateupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "productactivateend1"
            when
            then
                        update(productactivatedefault);//更新fact中变量值
                        update(productactivateupdate_obj);//更新fact中变量值
            end