package cn.ibizlab.plm.prodmgmt.logic.productlogic.archive;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productarchivedefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productarchiveupdate_obj;
                    global cn.ibizlab.plm.core.prodmgmt.service.IproductService productservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IproductService iBzSysProductDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "productarchivebegin"
            when
            then
            end

            //逻辑处理节点[设置已归档状态]
            rule "prepareparam1"
            ruleflow-group "productarchiveprepareparam1"
            when
            then
                            productarchiveupdate_obj.set("isarchived","1");
                            productarchiveupdate_obj.set("id",productarchivedefault.get("id"));
                        update(productarchivedefault);//更新fact中变量值
                        update(productarchiveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[归档]
            rule "deaction1"
            ruleflow-group "productarchivedeaction1"
            when
            then
                        productservice.update(productarchiveupdate_obj);
                        update(productarchivedefault);//更新fact中变量值
                        update(productarchiveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "productarchiveend1"
            when
            then
                        update(productarchivedefault);//更新fact中变量值
                        update(productarchiveupdate_obj);//更新fact中变量值
            end