package cn.ibizlab.plm.prodmgmt.logic.productlogic.auto_create_members;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productauto_create_membersdefault;
                global cn.ibizlab.plm.core.base.domain.member productauto_create_membersmember;
                global cn.ibizlab.plm.core.base.domain.member productauto_create_membersmember_obj;
                global cn.ibizlab.plm.core.base.domain.member productauto_create_membersmember_page;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_member productauto_create_membersproduct_member;
                    global cn.ibizlab.plm.core.base.service.ImemberService memberservice;
                    global cn.ibizlab.plm.core.prodmgmt.service.Iproduct_memberService product_memberservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IproductService iBzSysProductDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "productauto_create_membersbegin"
            when
            then
            end

            //逻辑处理节点[准备查询参数]
            rule "prepareparam2"
            ruleflow-group "productauto_create_membersprepareparam2"
            when
            then
                            productauto_create_membersmember.set("n_owner_id_eq",productauto_create_membersdefault.get("scopeid"));
                            productauto_create_membersmember.set("n_owner_type_eq","GROUP");
                        update(productauto_create_membersdefault);//更新fact中变量值
                        update(productauto_create_membersmember);//更新fact中变量值
                        update(productauto_create_membersmember_obj);//更新fact中变量值
                        update(productauto_create_membersmember_page);//更新fact中变量值
                        update(productauto_create_membersproduct_member);//更新fact中变量值
            end

            //逻辑处理节点[查询用户数据]
            rule "dedataset1"
            ruleflow-group "productauto_create_membersdedataset1"
            when
            then
                        update(productauto_create_membersdefault);//更新fact中变量值
                        update(productauto_create_membersmember);//更新fact中变量值
                        update(productauto_create_membersmember_obj);//更新fact中变量值
                        update(productauto_create_membersmember_page);//更新fact中变量值
                        update(productauto_create_membersproduct_member);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "productauto_create_membersloopsubcall1"
            when
            then
                        update(productauto_create_membersdefault);//更新fact中变量值
                        update(productauto_create_membersmember);//更新fact中变量值
                        update(productauto_create_membersmember_obj);//更新fact中变量值
                        update(productauto_create_membersmember_page);//更新fact中变量值
                        update(productauto_create_membersproduct_member);//更新fact中变量值
            end

            //逻辑处理节点[重置参数]
            rule "resetparam1"
            ruleflow-group "productauto_create_membersresetparam1"
            when
            then
                        update(productauto_create_membersdefault);//更新fact中变量值
                        update(productauto_create_membersmember);//更新fact中变量值
                        update(productauto_create_membersmember_obj);//更新fact中变量值
                        update(productauto_create_membersmember_page);//更新fact中变量值
                        update(productauto_create_membersproduct_member);//更新fact中变量值
            end

            //逻辑处理节点[设置产品成员]
            rule "prepareparam4"
            ruleflow-group "productauto_create_membersprepareparam4"
            when
            then
                            productauto_create_membersproduct_member.set("productid",productauto_create_membersdefault.get("id"));
                            productauto_create_membersproduct_member.set("name",productauto_create_membersmember_obj.get("name"));
                            productauto_create_membersproduct_member.set("userid",productauto_create_membersmember_obj.get("userid"));
                            productauto_create_membersproduct_member.set("roleid",productauto_create_membersmember_obj.get("roleid"));
                        update(productauto_create_membersdefault);//更新fact中变量值
                        update(productauto_create_membersmember);//更新fact中变量值
                        update(productauto_create_membersmember_obj);//更新fact中变量值
                        update(productauto_create_membersmember_page);//更新fact中变量值
                        update(productauto_create_membersproduct_member);//更新fact中变量值
            end

            //逻辑处理节点[生成用户数据]
            rule "deaction3"
            ruleflow-group "productauto_create_membersdeaction3"
            when
            then
                        product_memberservice.create(productauto_create_membersproduct_member);
                        update(productauto_create_membersdefault);//更新fact中变量值
                        update(productauto_create_membersmember);//更新fact中变量值
                        update(productauto_create_membersmember_obj);//更新fact中变量值
                        update(productauto_create_membersmember_page);//更新fact中变量值
                        update(productauto_create_membersproduct_member);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "productauto_create_membersend1"
            when
            then
                        update(productauto_create_membersdefault);//更新fact中变量值
                        update(productauto_create_membersmember);//更新fact中变量值
                        update(productauto_create_membersmember_obj);//更新fact中变量值
                        update(productauto_create_membersmember_page);//更新fact中变量值
                        update(productauto_create_membersproduct_member);//更新fact中变量值
            end