package cn.ibizlab.plm.prodmgmt.logic.productlogic.create_recent;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productcreate_recentdefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_ticket_type productcreate_recentproduct_ticket_param;
                global cn.ibizlab.plm.core.base.domain.recent productcreate_recentrecent;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket_type productcreate_recentticket_type_filter;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket_type productcreate_recentticket_type_obj;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket_type productcreate_recentticket_type_page;
                    global cn.ibizlab.plm.core.base.service.IrecentService recentservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IproductService iBzSysProductDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "productcreate_recentbegin"
            when
            then
            end

            //逻辑处理节点[准备最近访问参数]
            rule "prepareparam1"
            ruleflow-group "productcreate_recentprepareparam1"
            when
            then
                            productcreate_recentrecent.set("ownerid",productcreate_recentdefault.get("id"));
                            productcreate_recentrecent.set("recentparentidentifier",productcreate_recentdefault.get("identifier"));
                            productcreate_recentrecent.set("recentparentname",productcreate_recentdefault.get("name"));
                            productcreate_recentrecent.set("recentparent",productcreate_recentdefault.get("id"));
                                productcreate_recentrecent.set("createman",curuser.getSessionParams().get("srfpersonid"));
                            productcreate_recentrecent.set("type","1");
                            productcreate_recentrecent.set("name",productcreate_recentdefault.get("name"));
                            productcreate_recentrecent.set("ownertype","product");
                            productcreate_recentrecent.set("ownersubtype","product");
                        update(productcreate_recentdefault);//更新fact中变量值
                        update(productcreate_recentproduct_ticket_param);//更新fact中变量值
                        update(productcreate_recentrecent);//更新fact中变量值
                        update(productcreate_recentticket_type_filter);//更新fact中变量值
                        update(productcreate_recentticket_type_obj);//更新fact中变量值
                        update(productcreate_recentticket_type_page);//更新fact中变量值
            end

            //逻辑处理节点[保存最近访问]
            rule "deaction1"
            ruleflow-group "productcreate_recentdeaction1"
            when
            then
                        recentservice.save(productcreate_recentrecent);
                        update(productcreate_recentdefault);//更新fact中变量值
                        update(productcreate_recentproduct_ticket_param);//更新fact中变量值
                        update(productcreate_recentrecent);//更新fact中变量值
                        update(productcreate_recentticket_type_filter);//更新fact中变量值
                        update(productcreate_recentticket_type_obj);//更新fact中变量值
                        update(productcreate_recentticket_type_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "productcreate_recentend1"
            when
            then
                        update(productcreate_recentdefault);//更新fact中变量值
                        update(productcreate_recentproduct_ticket_param);//更新fact中变量值
                        update(productcreate_recentrecent);//更新fact中变量值
                        update(productcreate_recentticket_type_filter);//更新fact中变量值
                        update(productcreate_recentticket_type_obj);//更新fact中变量值
                        update(productcreate_recentticket_type_page);//更新fact中变量值
            end