package cn.ibizlab.plm.prodmgmt.logic.productlogic.delete;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productdeletedefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productdeleteupdate_obj;
                    global cn.ibizlab.plm.core.prodmgmt.service.IproductService productservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IproductService iBzSysProductDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "productdeletebegin"
            when
            then
            end

            //逻辑处理节点[设置删除状态]
            rule "prepareparam1"
            ruleflow-group "productdeleteprepareparam1"
            when
            then
                            productdeleteupdate_obj.set("isdeleted","1");
                            productdeleteupdate_obj.set("id",productdeletedefault.get("id"));
                        update(productdeletedefault);//更新fact中变量值
                        update(productdeleteupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[更新产品的删除标识]
            rule "deaction1"
            ruleflow-group "productdeletedeaction1"
            when
            then
                        productservice.update(productdeleteupdate_obj);
                        update(productdeletedefault);//更新fact中变量值
                        update(productdeleteupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[删除最近访问]
            rule "rawsqlcall1"
            ruleflow-group "productdeleterawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",productdeletedefault.get("id"));
    String strSql="update recent set IS_DELETED=1 where owner_id=#{et.param0} and owner_subtype='product'";
                        iBzSysProductDefaultService.execute(strSql,param);//SQL调用
                        update(productdeletedefault);//更新fact中变量值
                        update(productdeleteupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "productdeleteend1"
            when
            then
                        update(productdeletedefault);//更新fact中变量值
                        update(productdeleteupdate_obj);//更新fact中变量值
            end