package cn.ibizlab.plm.prodmgmt.logic.productlogic.product_re_space;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productproduct_re_spacedefault;
                global cn.ibizlab.plm.core.base.domain.relation productproduct_re_spacerelationobj;
                global cn.ibizlab.plm.core.base.domain.relation productproduct_re_spacerelationobj2;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IproductService iBzSysProductDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "productproduct_re_spacebegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "productproduct_re_spaceend1"
            when
            then
                        update(productproduct_re_spacedefault);//更新fact中变量值
                        update(productproduct_re_spacerelationobj);//更新fact中变量值
                        update(productproduct_re_spacerelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[设置正/反向关联参数]
            rule "prepareparam1"
            ruleflow-group "productproduct_re_spaceprepareparam1"
            when
            then
                            productproduct_re_spacerelationobj2.set("targetid",productproduct_re_spacedefault.get("space_id"));
                            productproduct_re_spacerelationobj2.set("targettype",productproduct_re_spacedefault.get("target_type"));
                            productproduct_re_spacerelationobj2.set("principalid",productproduct_re_spacedefault.get("target_id"));
                            productproduct_re_spacerelationobj2.set("principaltype",productproduct_re_spacedefault.get("principal_type"));
                            productproduct_re_spacerelationobj.set("targetid",productproduct_re_spacedefault.get("target_id"));
                            productproduct_re_spacerelationobj.set("targettype",productproduct_re_spacedefault.get("principal_type"));
                            productproduct_re_spacerelationobj.set("principalid",productproduct_re_spacedefault.get("space_id"));
                            productproduct_re_spacerelationobj.set("principaltype",productproduct_re_spacedefault.get("target_type"));
                        update(productproduct_re_spacedefault);//更新fact中变量值
                        update(productproduct_re_spacerelationobj);//更新fact中变量值
                        update(productproduct_re_spacerelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[生成正向关联数据]
            rule "deaction1"
            ruleflow-group "productproduct_re_spacedeaction1"
            when
            then
                        relationservice.create(productproduct_re_spacerelationobj);
                        update(productproduct_re_spacedefault);//更新fact中变量值
                        update(productproduct_re_spacerelationobj);//更新fact中变量值
                        update(productproduct_re_spacerelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[生成反向关联数据]
            rule "deaction2"
            ruleflow-group "productproduct_re_spacedeaction2"
            when
            then
                        relationservice.create(productproduct_re_spacerelationobj2);
                        update(productproduct_re_spacedefault);//更新fact中变量值
                        update(productproduct_re_spacerelationobj);//更新fact中变量值
                        update(productproduct_re_spacerelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[抛出异常]
            rule "throwexception1"
            ruleflow-group "productproduct_re_spacethrowexception1"
            when
            then
                        update(productproduct_re_spacedefault);//更新fact中变量值
                        update(productproduct_re_spacerelationobj);//更新fact中变量值
                        update(productproduct_re_spacerelationobj2);//更新fact中变量值
            end