package cn.ibizlab.plm.prodmgmt.logic.productlogic.recover;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productrecoverdefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productrecoverupdate_obj;
                    global cn.ibizlab.plm.core.prodmgmt.service.IproductService productservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IproductService iBzSysProductDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "productrecoverbegin"
            when
            then
            end

            //逻辑处理节点[设置删除状态]
            rule "prepareparam1"
            ruleflow-group "productrecoverprepareparam1"
            when
            then
                            productrecoverupdate_obj.set("isdeleted","0");
                            productrecoverupdate_obj.set("id",productrecoverdefault.get("id"));
                        update(productrecoverdefault);//更新fact中变量值
                        update(productrecoverupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[恢复]
            rule "deaction1"
            ruleflow-group "productrecoverdeaction1"
            when
            then
                        productservice.update(productrecoverupdate_obj);
                        update(productrecoverdefault);//更新fact中变量值
                        update(productrecoverupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[恢复最近访问]
            rule "rawsqlcall1"
            ruleflow-group "productrecoverrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",productrecoverdefault.get("id"));
    String strSql="update recent set IS_DELETED=0 where owner_id=#{et.param0} and owner_subtype='product'";
                        iBzSysProductDefaultService.execute(strSql,param);//SQL调用
                        update(productrecoverdefault);//更新fact中变量值
                        update(productrecoverupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "productrecoverend1"
            when
            then
                        update(productrecoverdefault);//更新fact中变量值
                        update(productrecoverupdate_obj);//更新fact中变量值
            end