package cn.ibizlab.plm.base.logic.versionlogic.run_is_newest;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.version versionrun_is_newestdefault;
                global cn.ibizlab.plm.core.testmgmt.domain.run versionrun_is_newestfilter;
                global cn.ibizlab.plm.core.testmgmt.domain.run versionrun_is_newestfor_run;
                global cn.ibizlab.plm.core.testmgmt.domain.run versionrun_is_newestrun_page;
                    global cn.ibizlab.plm.core.testmgmt.service.IrunService runservice;
        global cn.ibizlab.plm.core.base.service.IversionService iBzSysVersionDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "versionrun_is_newestbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "versionrun_is_newestend1"
            when
            then
                        update(versionrun_is_newestdefault);//更新fact中变量值
                        update(versionrun_is_newestfilter);//更新fact中变量值
                        update(versionrun_is_newestfor_run);//更新fact中变量值
                        update(versionrun_is_newestrun_page);//更新fact中变量值
            end

            //逻辑处理节点[设置过滤器参数]
            rule "prepareparam1"
            ruleflow-group "versionrun_is_newestprepareparam1"
            when
            then
                            versionrun_is_newestfilter.set("n_case_id_eq",versionrun_is_newestdefault.get("ownerid"));
                        update(versionrun_is_newestdefault);//更新fact中变量值
                        update(versionrun_is_newestfilter);//更新fact中变量值
                        update(versionrun_is_newestfor_run);//更新fact中变量值
                        update(versionrun_is_newestrun_page);//更新fact中变量值
            end

            //逻辑处理节点[查询执行用例数据]
            rule "dedataset1"
            ruleflow-group "versionrun_is_newestdedataset1"
            when
            then
                        update(versionrun_is_newestdefault);//更新fact中变量值
                        update(versionrun_is_newestfilter);//更新fact中变量值
                        update(versionrun_is_newestfor_run);//更新fact中变量值
                        update(versionrun_is_newestrun_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "versionrun_is_newestloopsubcall1"
            when
            then
                        update(versionrun_is_newestdefault);//更新fact中变量值
                        update(versionrun_is_newestfilter);//更新fact中变量值
                        update(versionrun_is_newestfor_run);//更新fact中变量值
                        update(versionrun_is_newestrun_page);//更新fact中变量值
            end

            //逻辑处理节点[输出循环执行用例结果]
            rule "debugparam2"
            ruleflow-group "versionrun_is_newestdebugparam2"
            when
            then
                        update(versionrun_is_newestdefault);//更新fact中变量值
                        update(versionrun_is_newestfilter);//更新fact中变量值
                        update(versionrun_is_newestfor_run);//更新fact中变量值
                        update(versionrun_is_newestrun_page);//更新fact中变量值
            end

            //逻辑处理节点[设置是否最新版本参数]
            rule "prepareparam2"
            ruleflow-group "versionrun_is_newestprepareparam2"
            when
            then
                            versionrun_is_newestfor_run.set("isnewest","1");
                        update(versionrun_is_newestdefault);//更新fact中变量值
                        update(versionrun_is_newestfilter);//更新fact中变量值
                        update(versionrun_is_newestfor_run);//更新fact中变量值
                        update(versionrun_is_newestrun_page);//更新fact中变量值
            end

            //逻辑处理节点[更新执行用例]
            rule "deaction1"
            ruleflow-group "versionrun_is_newestdeaction1"
            when
            then
                        runservice.update(versionrun_is_newestfor_run);
                        update(versionrun_is_newestdefault);//更新fact中变量值
                        update(versionrun_is_newestfilter);//更新fact中变量值
                        update(versionrun_is_newestfor_run);//更新fact中变量值
                        update(versionrun_is_newestrun_page);//更新fact中变量值
            end