package cn.ibizlab.plm.prodmgmt.logic.ticketlogic.activate;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.Ticket ticketactivatedefault;
                global java.util.Map ticketactivateid;
                global java.util.Map ticketactivateids;
                global cn.ibizlab.plm.core.prodmgmt.domain.Ticket ticketactivatetemp_obj;
                    global cn.ibizlab.plm.core.prodmgmt.service.ITicketService ticketservice;
        global cn.ibizlab.plm.core.prodmgmt.service.ITicketService iBzSysTicketDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ticketactivatebegin"
            when
            then
            end

            //逻辑处理节点[拆分选中主键]
            rule "rawsfcode1"
            ruleflow-group "ticketactivaterawsfcode1"
            when
            then
                        update(ticketactivatedefault);//更新fact中变量值
                        update(ticketactivateid);//更新fact中变量值
                        update(ticketactivateids);//更新fact中变量值
                        update(ticketactivatetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "ticketactivateloopsubcall1"
            when
            then
                        update(ticketactivatedefault);//更新fact中变量值
                        update(ticketactivateid);//更新fact中变量值
                        update(ticketactivateids);//更新fact中变量值
                        update(ticketactivatetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "ticketactivaterenewparam1"
            when
            then
                        update(ticketactivatedefault);//更新fact中变量值
                        update(ticketactivateid);//更新fact中变量值
                        update(ticketactivateids);//更新fact中变量值
                        update(ticketactivatetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "ticketactivateprepareparam1"
            when
            then
                            ticketactivatedefault.set("isarchived","0");
                        update(ticketactivatedefault);//更新fact中变量值
                        update(ticketactivateid);//更新fact中变量值
                        update(ticketactivateids);//更新fact中变量值
                        update(ticketactivatetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[update]
            rule "deaction1"
            ruleflow-group "ticketactivatedeaction1"
            when
            then
                        ticketservice.update(ticketactivatedefault);
                        update(ticketactivatedefault);//更新fact中变量值
                        update(ticketactivateid);//更新fact中变量值
                        update(ticketactivateids);//更新fact中变量值
                        update(ticketactivatetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ticketactivateend1"
            when
            then
                        update(ticketactivatedefault);//更新fact中变量值
                        update(ticketactivateid);//更新fact中变量值
                        update(ticketactivateids);//更新fact中变量值
                        update(ticketactivatetemp_obj);//更新fact中变量值
            end