package cn.ibizlab.plm.prodmgmt.logic.ticketlogic.create_recent;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.Ticket ticketcreate_recentdefault;
                global cn.ibizlab.plm.core.base.domain.Recent ticketcreate_recentrecent;
                    global cn.ibizlab.plm.core.base.service.IRecentService recentservice;
        global cn.ibizlab.plm.core.prodmgmt.service.ITicketService iBzSysTicketDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ticketcreate_recentbegin"
            when
            then
            end

            //逻辑处理节点[准备最近访问参数]
            rule "prepareparam1"
            ruleflow-group "ticketcreate_recentprepareparam1"
            when
            then
                            ticketcreate_recentrecent.set("ownerid",ticketcreate_recentdefault.get("id"));
                            ticketcreate_recentrecent.set("recentparentidentifier",ticketcreate_recentdefault.get("productidentifier"));
                            ticketcreate_recentrecent.set("recentparentname",ticketcreate_recentdefault.get("productname"));
                            ticketcreate_recentrecent.set("recentparent",ticketcreate_recentdefault.get("productid"));
                                ticketcreate_recentrecent.set("createman",curuser.getSessionParams().get("srfpersonid"));
                            ticketcreate_recentrecent.set("identifier",ticketcreate_recentdefault.get("identifier"));
                            ticketcreate_recentrecent.set("type","2");
                            ticketcreate_recentrecent.set("name",ticketcreate_recentdefault.get("title"));
                            ticketcreate_recentrecent.set("ownertype","product");
                            ticketcreate_recentrecent.set("ownersubtype","ticket");
                        update(ticketcreate_recentdefault);//更新fact中变量值
                        update(ticketcreate_recentrecent);//更新fact中变量值
            end

            //逻辑处理节点[保存最近访问]
            rule "deaction1"
            ruleflow-group "ticketcreate_recentdeaction1"
            when
            then
                        recentservice.save(ticketcreate_recentrecent);
                        update(ticketcreate_recentdefault);//更新fact中变量值
                        update(ticketcreate_recentrecent);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ticketcreate_recentend1"
            when
            then
                        update(ticketcreate_recentdefault);//更新fact中变量值
                        update(ticketcreate_recentrecent);//更新fact中变量值
            end