package cn.ibizlab.plm.prodmgmt.logic.ticketlogic.customer_choose_ticket;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket ticketcustomer_choose_ticketdefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket ticketcustomer_choose_ticketfor_temp_obj;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket ticketcustomer_choose_ticketsrfactionparam;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket ticketcustomer_choose_ticketthis_ticket;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket ticketcustomer_choose_ticketupdate_obj;
                    global cn.ibizlab.plm.core.prodmgmt.service.IticketService ticketservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IticketService iBzSysTicketDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ticketcustomer_choose_ticketbegin"
            when
            then
            end

            //逻辑处理节点[获取选中数据]
            rule "prepareparam1"
            ruleflow-group "ticketcustomer_choose_ticketprepareparam1"
            when
            then
                            ticketcustomer_choose_ticketsrfactionparam.set("",ticketcustomer_choose_ticketdefault.get("srfactionparam"));
                        update(ticketcustomer_choose_ticketdefault);//更新fact中变量值
                        update(ticketcustomer_choose_ticketfor_temp_obj);//更新fact中变量值
                        update(ticketcustomer_choose_ticketsrfactionparam);//更新fact中变量值
                        update(ticketcustomer_choose_ticketthis_ticket);//更新fact中变量值
                        update(ticketcustomer_choose_ticketupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "ticketcustomer_choose_ticketloopsubcall1"
            when
            then
                        update(ticketcustomer_choose_ticketdefault);//更新fact中变量值
                        update(ticketcustomer_choose_ticketfor_temp_obj);//更新fact中变量值
                        update(ticketcustomer_choose_ticketsrfactionparam);//更新fact中变量值
                        update(ticketcustomer_choose_ticketthis_ticket);//更新fact中变量值
                        update(ticketcustomer_choose_ticketupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "ticketcustomer_choose_ticketrenewparam1"
            when
            then
                        update(ticketcustomer_choose_ticketdefault);//更新fact中变量值
                        update(ticketcustomer_choose_ticketfor_temp_obj);//更新fact中变量值
                        update(ticketcustomer_choose_ticketsrfactionparam);//更新fact中变量值
                        update(ticketcustomer_choose_ticketthis_ticket);//更新fact中变量值
                        update(ticketcustomer_choose_ticketupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[填充更新属性]
            rule "prepareparam2"
            ruleflow-group "ticketcustomer_choose_ticketprepareparam2"
            when
            then
                            ticketcustomer_choose_ticketupdate_obj.set("id",ticketcustomer_choose_ticketfor_temp_obj.get("owner_id"));
                            ticketcustomer_choose_ticketupdate_obj.set("customerid",ticketcustomer_choose_ticketdefault.get("customerid"));
                        update(ticketcustomer_choose_ticketdefault);//更新fact中变量值
                        update(ticketcustomer_choose_ticketfor_temp_obj);//更新fact中变量值
                        update(ticketcustomer_choose_ticketsrfactionparam);//更新fact中变量值
                        update(ticketcustomer_choose_ticketthis_ticket);//更新fact中变量值
                        update(ticketcustomer_choose_ticketupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[修改工单信息]
            rule "deaction1"
            ruleflow-group "ticketcustomer_choose_ticketdeaction1"
            when
            then
                        ticketservice.update(ticketcustomer_choose_ticketupdate_obj);
                        update(ticketcustomer_choose_ticketdefault);//更新fact中变量值
                        update(ticketcustomer_choose_ticketfor_temp_obj);//更新fact中变量值
                        update(ticketcustomer_choose_ticketsrfactionparam);//更新fact中变量值
                        update(ticketcustomer_choose_ticketthis_ticket);//更新fact中变量值
                        update(ticketcustomer_choose_ticketupdate_obj);//更新fact中变量值
            end