package cn.ibizlab.plm.prodmgmt.logic.ticketlogic.del_relation;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket ticketdel_relationdefault;
                global cn.ibizlab.plm.core.base.domain.relation ticketdel_relationforward_relation_obj;
                global cn.ibizlab.plm.core.base.domain.relation ticketdel_relationreverse_relation_obj;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IticketService iBzSysTicketDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ticketdel_relationbegin"
            when
            then
            end

            //逻辑处理节点[填充正反关联对象的主要关联属性]
            rule "prepareparam1"
            ruleflow-group "ticketdel_relationprepareparam1"
            when
            then
                            ticketdel_relationforward_relation_obj.set("principalid",ticketdel_relationdefault.get("principal_id"));
                            ticketdel_relationreverse_relation_obj.set("targetid",ticketdel_relationdefault.get("principal_id"));
                            ticketdel_relationreverse_relation_obj.set("principalid",ticketdel_relationdefault.get("id"));
                            ticketdel_relationforward_relation_obj.set("targetid",ticketdel_relationdefault.get("id"));
                        update(ticketdel_relationdefault);//更新fact中变量值
                        update(ticketdel_relationforward_relation_obj);//更新fact中变量值
                        update(ticketdel_relationreverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[拼接关联对象的主键]
            rule "rawsfcode1"
            ruleflow-group "ticketdel_relationrawsfcode1"
            when
            then
                        update(ticketdel_relationdefault);//更新fact中变量值
                        update(ticketdel_relationforward_relation_obj);//更新fact中变量值
                        update(ticketdel_relationreverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[删除正向关联]
            rule "deaction2"
            ruleflow-group "ticketdel_relationdeaction2"
            when
            then
                        relationservice.remove(ticketdel_relationforward_relation_obj.getId());
                        update(ticketdel_relationdefault);//更新fact中变量值
                        update(ticketdel_relationforward_relation_obj);//更新fact中变量值
                        update(ticketdel_relationreverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[删除反向关联]
            rule "deaction3"
            ruleflow-group "ticketdel_relationdeaction3"
            when
            then
                        relationservice.remove(ticketdel_relationreverse_relation_obj.getId());
                        update(ticketdel_relationdefault);//更新fact中变量值
                        update(ticketdel_relationforward_relation_obj);//更新fact中变量值
                        update(ticketdel_relationreverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ticketdel_relationend1"
            when
            then
                        update(ticketdel_relationdefault);//更新fact中变量值
                        update(ticketdel_relationforward_relation_obj);//更新fact中变量值
                        update(ticketdel_relationreverse_relation_obj);//更新fact中变量值
            end