package cn.ibizlab.plm.prodmgmt.logic.ticketlogic.delete;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.Ticket ticketdeletedefault;
                    global cn.ibizlab.plm.core.prodmgmt.service.ITicketService ticketservice;
        global cn.ibizlab.plm.core.prodmgmt.service.ITicketService iBzSysTicketDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ticketdeletebegin"
            when
            then
            end

            //逻辑处理节点[更新删除标识]
            rule "prepareparam1"
            ruleflow-group "ticketdeleteprepareparam1"
            when
            then
                            ticketdeletedefault.set("isdeleted","1");
                        update(ticketdeletedefault);//更新fact中变量值
            end

            //逻辑处理节点[执行更新操作]
            rule "deaction1"
            ruleflow-group "ticketdeletedeaction1"
            when
            then
                        ticketservice.update(ticketdeletedefault);
                        update(ticketdeletedefault);//更新fact中变量值
            end

            //逻辑处理节点[删除最近访问]
            rule "rawsqlcall1"
            ruleflow-group "ticketdeleterawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",ticketdeletedefault.get("id"));
    String strSql="update recent set IS_DELETED=1 where owner_id=#{et.param0} and owner_subtype='ticket'";
                        iBzSysTicketDefaultService.execute(strSql,param);//SQL调用
                        update(ticketdeletedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ticketdeleteend1"
            when
            then
                        update(ticketdeletedefault);//更新fact中变量值
            end