package cn.ibizlab.plm.prodmgmt.logic.ticketlogic.get_product_member;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket ticketget_product_memberdefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_member ticketget_product_memberfilter;
                global java.util.Map ticketget_product_memberfor_obj;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_member ticketget_product_membermembers;
                global cn.ibizlab.plm.core.prodmgmt.domain.product ticketget_product_memberproduct_info;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket ticketget_product_memberticket;
                global java.util.Map ticketget_product_memberuser;
                global java.util.Map ticketget_product_memberviewctx;
                global java.util.Map ticketget_product_memberwebctx;
                    global cn.ibizlab.plm.core.prodmgmt.service.Iproduct_memberService product_memberservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IticketService iBzSysTicketDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ticketget_product_memberbegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam3"
            ruleflow-group "ticketget_product_memberdebugparam3"
            when
            then
                        update(ticketget_product_memberdefault);//更新fact中变量值
                        update(ticketget_product_memberfilter);//更新fact中变量值
                        update(ticketget_product_memberfor_obj);//更新fact中变量值
                        update(ticketget_product_membermembers);//更新fact中变量值
                        update(ticketget_product_memberproduct_info);//更新fact中变量值
                        update(ticketget_product_memberticket);//更新fact中变量值
                        update(ticketget_product_memberuser);//更新fact中变量值
                        update(ticketget_product_memberviewctx);//更新fact中变量值
                        update(ticketget_product_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[获取产品id]
            rule "prepareparam2"
            ruleflow-group "ticketget_product_memberprepareparam2"
            when
            then
                            ticketget_product_memberproduct_info.set("id",ticketget_product_memberdefault.get("productid"));
                            ticketget_product_memberfilter.set("n_product_id_eq",ticketget_product_memberdefault.get("productid"));
                                ticketget_product_memberfilter.set("n_user_id_eq",curuser.getSessionParams().get("srfpersonid"));
                        update(ticketget_product_memberdefault);//更新fact中变量值
                        update(ticketget_product_memberfilter);//更新fact中变量值
                        update(ticketget_product_memberfor_obj);//更新fact中变量值
                        update(ticketget_product_membermembers);//更新fact中变量值
                        update(ticketget_product_memberproduct_info);//更新fact中变量值
                        update(ticketget_product_memberticket);//更新fact中变量值
                        update(ticketget_product_memberuser);//更新fact中变量值
                        update(ticketget_product_memberviewctx);//更新fact中变量值
                        update(ticketget_product_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam6"
            ruleflow-group "ticketget_product_memberdebugparam6"
            when
            then
                        update(ticketget_product_memberdefault);//更新fact中变量值
                        update(ticketget_product_memberfilter);//更新fact中变量值
                        update(ticketget_product_memberfor_obj);//更新fact中变量值
                        update(ticketget_product_membermembers);//更新fact中变量值
                        update(ticketget_product_memberproduct_info);//更新fact中变量值
                        update(ticketget_product_memberticket);//更新fact中变量值
                        update(ticketget_product_memberuser);//更新fact中变量值
                        update(ticketget_product_memberviewctx);//更新fact中变量值
                        update(ticketget_product_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset3"
            ruleflow-group "ticketget_product_memberdedataset3"
            when
            then
                        update(ticketget_product_memberdefault);//更新fact中变量值
                        update(ticketget_product_memberfilter);//更新fact中变量值
                        update(ticketget_product_memberfor_obj);//更新fact中变量值
                        update(ticketget_product_membermembers);//更新fact中变量值
                        update(ticketget_product_memberproduct_info);//更新fact中变量值
                        update(ticketget_product_memberticket);//更新fact中变量值
                        update(ticketget_product_memberuser);//更新fact中变量值
                        update(ticketget_product_memberviewctx);//更新fact中变量值
                        update(ticketget_product_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall3"
            ruleflow-group "ticketget_product_memberloopsubcall3"
            when
            then
                        update(ticketget_product_memberdefault);//更新fact中变量值
                        update(ticketget_product_memberfilter);//更新fact中变量值
                        update(ticketget_product_memberfor_obj);//更新fact中变量值
                        update(ticketget_product_membermembers);//更新fact中变量值
                        update(ticketget_product_memberproduct_info);//更新fact中变量值
                        update(ticketget_product_memberticket);//更新fact中变量值
                        update(ticketget_product_memberuser);//更新fact中变量值
                        update(ticketget_product_memberviewctx);//更新fact中变量值
                        update(ticketget_product_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[只读]
            rule "prepareparam10"
            ruleflow-group "ticketget_product_memberprepareparam10"
            when
            then
                            ticketget_product_memberuser.set("readonly","true");
                        update(ticketget_product_memberdefault);//更新fact中变量值
                        update(ticketget_product_memberfilter);//更新fact中变量值
                        update(ticketget_product_memberfor_obj);//更新fact中变量值
                        update(ticketget_product_membermembers);//更新fact中变量值
                        update(ticketget_product_memberproduct_info);//更新fact中变量值
                        update(ticketget_product_memberticket);//更新fact中变量值
                        update(ticketget_product_memberuser);//更新fact中变量值
                        update(ticketget_product_memberviewctx);//更新fact中变量值
                        update(ticketget_product_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[只读]
            rule "prepareparam8"
            ruleflow-group "ticketget_product_memberprepareparam8"
            when
            then
                            ticketget_product_memberuser.set("readonly","true");
                        update(ticketget_product_memberdefault);//更新fact中变量值
                        update(ticketget_product_memberfilter);//更新fact中变量值
                        update(ticketget_product_memberfor_obj);//更新fact中变量值
                        update(ticketget_product_membermembers);//更新fact中变量值
                        update(ticketget_product_memberproduct_info);//更新fact中变量值
                        update(ticketget_product_memberticket);//更新fact中变量值
                        update(ticketget_product_memberuser);//更新fact中变量值
                        update(ticketget_product_memberviewctx);//更新fact中变量值
                        update(ticketget_product_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[非只读]
            rule "prepareparam9"
            ruleflow-group "ticketget_product_memberprepareparam9"
            when
            then
                            ticketget_product_memberuser.set("readonly","false");
                        update(ticketget_product_memberdefault);//更新fact中变量值
                        update(ticketget_product_memberfilter);//更新fact中变量值
                        update(ticketget_product_memberfor_obj);//更新fact中变量值
                        update(ticketget_product_membermembers);//更新fact中变量值
                        update(ticketget_product_memberproduct_info);//更新fact中变量值
                        update(ticketget_product_memberticket);//更新fact中变量值
                        update(ticketget_product_memberuser);//更新fact中变量值
                        update(ticketget_product_memberviewctx);//更新fact中变量值
                        update(ticketget_product_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end6"
            ruleflow-group "ticketget_product_memberend6"
            when
            then
                        update(ticketget_product_memberdefault);//更新fact中变量值
                        update(ticketget_product_memberfilter);//更新fact中变量值
                        update(ticketget_product_memberfor_obj);//更新fact中变量值
                        update(ticketget_product_membermembers);//更新fact中变量值
                        update(ticketget_product_memberproduct_info);//更新fact中变量值
                        update(ticketget_product_memberticket);//更新fact中变量值
                        update(ticketget_product_memberuser);//更新fact中变量值
                        update(ticketget_product_memberviewctx);//更新fact中变量值
                        update(ticketget_product_memberwebctx);//更新fact中变量值
            end