package cn.ibizlab.plm.prodmgmt.logic.ticketlogic.ticket_archive;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.Ticket ticketticket_archivedefault;
                global java.util.Map ticketticket_archiveid;
                global java.util.Map ticketticket_archiveids;
                global cn.ibizlab.plm.core.prodmgmt.domain.Ticket ticketticket_archivetemp_obj;
                    global cn.ibizlab.plm.core.prodmgmt.service.ITicketService ticketservice;
        global cn.ibizlab.plm.core.prodmgmt.service.ITicketService iBzSysTicketDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ticketticket_archivebegin"
            when
            then
            end

            //逻辑处理节点[拆分选中主键]
            rule "rawsfcode1"
            ruleflow-group "ticketticket_archiverawsfcode1"
            when
            then
                        update(ticketticket_archivedefault);//更新fact中变量值
                        update(ticketticket_archiveid);//更新fact中变量值
                        update(ticketticket_archiveids);//更新fact中变量值
                        update(ticketticket_archivetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "ticketticket_archiveloopsubcall1"
            when
            then
                        update(ticketticket_archivedefault);//更新fact中变量值
                        update(ticketticket_archiveid);//更新fact中变量值
                        update(ticketticket_archiveids);//更新fact中变量值
                        update(ticketticket_archivetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "ticketticket_archiverenewparam1"
            when
            then
                        update(ticketticket_archivedefault);//更新fact中变量值
                        update(ticketticket_archiveid);//更新fact中变量值
                        update(ticketticket_archiveids);//更新fact中变量值
                        update(ticketticket_archivetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[修改是否归档标识]
            rule "prepareparam1"
            ruleflow-group "ticketticket_archiveprepareparam1"
            when
            then
                            ticketticket_archivetemp_obj.set("isarchived","1");
                        update(ticketticket_archivedefault);//更新fact中变量值
                        update(ticketticket_archiveid);//更新fact中变量值
                        update(ticketticket_archiveids);//更新fact中变量值
                        update(ticketticket_archivetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[执行更新操作]
            rule "deaction1"
            ruleflow-group "ticketticket_archivedeaction1"
            when
            then
                        ticketservice.update(ticketticket_archivetemp_obj);
                        update(ticketticket_archivedefault);//更新fact中变量值
                        update(ticketticket_archiveid);//更新fact中变量值
                        update(ticketticket_archiveids);//更新fact中变量值
                        update(ticketticket_archivetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ticketticket_archiveend1"
            when
            then
                        update(ticketticket_archivedefault);//更新fact中变量值
                        update(ticketticket_archiveid);//更新fact中变量值
                        update(ticketticket_archiveids);//更新fact中变量值
                        update(ticketticket_archivetemp_obj);//更新fact中变量值
            end