package cn.ibizlab.plm.prodmgmt.logic.ticketlogic.ticket_recover;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.Ticket ticketticket_recoverdefault;
                    global cn.ibizlab.plm.core.prodmgmt.service.ITicketService ticketservice;
        global cn.ibizlab.plm.core.prodmgmt.service.ITicketService iBzSysTicketDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ticketticket_recoverbegin"
            when
            then
            end

            //逻辑处理节点[更新删除标识]
            rule "prepareparam1"
            ruleflow-group "ticketticket_recoverprepareparam1"
            when
            then
                            ticketticket_recoverdefault.set("isdeleted","0");
                        update(ticketticket_recoverdefault);//更新fact中变量值
            end

            //逻辑处理节点[执行更新操作]
            rule "deaction1"
            ruleflow-group "ticketticket_recoverdeaction1"
            when
            then
                        ticketservice.update(ticketticket_recoverdefault);
                        update(ticketticket_recoverdefault);//更新fact中变量值
            end

            //逻辑处理节点[恢复最近访问]
            rule "rawsqlcall1"
            ruleflow-group "ticketticket_recoverrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",ticketticket_recoverdefault.get("id"));
    String strSql="update recent set IS_DELETED=0 where owner_id=#{et.param0} and owner_subtype='ticket'";
                        iBzSysTicketDefaultService.execute(strSql,param);//SQL调用
                        update(ticketticket_recoverdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ticketticket_recoverend1"
            when
            then
                        update(ticketticket_recoverdefault);//更新fact中变量值
            end