package cn.ibizlab.plm.base.logic.userlogic.activate;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.user useractivatedefault;
                    global cn.ibizlab.plm.core.base.service.IuserService userservice;
        global cn.ibizlab.plm.core.base.service.IuserService iBzSysUserDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "useractivatebegin"
            when
            then
            end

            //逻辑处理节点[获取用户全量信息]
            rule "deaction2"
            ruleflow-group "useractivatedeaction2"
            when
            then
                        userservice.getFull(useractivatedefault);
                        update(useractivatedefault);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "useractivateprepareparam1"
            when
            then
                            useractivatedefault.set("status","1");
                            useractivatedefault.set("reportflag","1");
                        update(useractivatedefault);//更新fact中变量值
            end

            //逻辑处理节点[激活用户]
            rule "deaction1"
            ruleflow-group "useractivatedeaction1"
            when
            then
                        userservice.update(useractivatedefault);
                        update(useractivatedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "useractivateend1"
            when
            then
                        update(useractivatedefault);//更新fact中变量值
            end