package cn.ibizlab.plm.base.logic.commentlogic.top;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.comment commenttopdefault;
                    global cn.ibizlab.plm.core.base.service.IcommentService commentservice;
        global cn.ibizlab.plm.core.base.service.IcommentService iBzSysCommentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "commenttopbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "commenttopprepareparam1"
            when
            then
                            commenttopdefault.set("istop","1");
                        update(commenttopdefault);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "commenttopdeaction1"
            when
            then
                        commentservice.update(commenttopdefault);
                        update(commenttopdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "commenttopend1"
            when
            then
                        update(commenttopdefault);//更新fact中变量值
            end