package cn.ibizlab.plm.ai.logic.ai_kb_memberlogic.change_role;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_member ai_kb_memberchange_roledefault;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_member ai_kb_memberchange_rolefor_temp_obj;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_member ai_kb_memberchange_rolesrfactionparam;
                    global cn.ibizlab.plm.core.ai.service.Iai_kb_memberService ai_kb_memberservice;
        global cn.ibizlab.plm.core.ai.service.Iai_kb_memberService iBzSysAi_kb_memberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_kb_memberchange_rolebegin"
            when
            then
            end

            //逻辑处理节点[获取传递的参数]
            rule "bindparam1"
            ruleflow-group "ai_kb_memberchange_rolebindparam1"
            when
            then
                        update(ai_kb_memberchange_roledefault);//更新fact中变量值
                        update(ai_kb_memberchange_rolefor_temp_obj);//更新fact中变量值
                        update(ai_kb_memberchange_rolesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[获取传递的状态]
            rule "prepareparam2"
            ruleflow-group "ai_kb_memberchange_roleprepareparam2"
            when
            then
                            ai_kb_memberchange_roledefault.set("roleid",ai_kb_memberchange_rolefor_temp_obj.get("roleid"));
                        update(ai_kb_memberchange_roledefault);//更新fact中变量值
                        update(ai_kb_memberchange_rolefor_temp_obj);//更新fact中变量值
                        update(ai_kb_memberchange_rolesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[变更状态]
            rule "deaction1"
            ruleflow-group "ai_kb_memberchange_roledeaction1"
            when
            then
                        ai_kb_memberservice.update(ai_kb_memberchange_roledefault);
                        update(ai_kb_memberchange_roledefault);//更新fact中变量值
                        update(ai_kb_memberchange_rolefor_temp_obj);//更新fact中变量值
                        update(ai_kb_memberchange_rolesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环id列表进行操作]
            rule "loopsubcall1"
            ruleflow-group "ai_kb_memberchange_roleloopsubcall1"
            when
            then
                        update(ai_kb_memberchange_roledefault);//更新fact中变量值
                        update(ai_kb_memberchange_rolefor_temp_obj);//更新fact中变量值
                        update(ai_kb_memberchange_rolesrfactionparam);//更新fact中变量值
            end