package cn.ibizlab.plm.ai.logic.ai_kb_memberlogic.remove_kb_member_notify;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_member ai_kb_memberremove_kb_member_notifydefault;
                    global cn.ibizlab.plm.core.ai.service.Iai_kb_memberService ai_kb_memberservice;
        global cn.ibizlab.plm.core.ai.service.Iai_kb_memberService iBzSysAi_kb_memberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_kb_memberremove_kb_member_notifybegin"
            when
            then
            end

            //逻辑处理节点[获取知识库成员数据]
            rule "deaction1"
            ruleflow-group "ai_kb_memberremove_kb_member_notifydeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(ai_kb_memberservice.get(ai_kb_memberremove_kb_member_notifydefault.getId()),ai_kb_memberremove_kb_member_notifydefault);
                        update(ai_kb_memberremove_kb_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[绑定当前操作人]
            rule "prepareparam1"
            ruleflow-group "ai_kb_memberremove_kb_member_notifyprepareparam1"
            when
            then
                                ai_kb_memberremove_kb_member_notifydefault.set("updateman",curuser.getSessionParams().get("srfpersonid"));
                        update(ai_kb_memberremove_kb_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[获取当前操作时间]
            rule "rawsfcode1"
            ruleflow-group "ai_kb_memberremove_kb_member_notifyrawsfcode1"
            when
            then
                        update(ai_kb_memberremove_kb_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[移除知识库成员通知]
            rule "denotify1"
            ruleflow-group "ai_kb_memberremove_kb_member_notifydenotify1"
            when
            then
                        update(ai_kb_memberremove_kb_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ai_kb_memberremove_kb_member_notifyend1"
            when
            then
                        update(ai_kb_memberremove_kb_member_notifydefault);//更新fact中变量值
            end