package cn.ibizlab.plm.base.logic.baselinelogic.create_plan_snapshot;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.baseline baselinecreate_plan_snapshotdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item baselinecreate_plan_snapshotfor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.relation baselinecreate_plan_snapshotrelation;
                global cn.ibizlab.plm.core.base.domain.version baselinecreate_plan_snapshotversion;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item baselinecreate_plan_snapshotwork_item_filter;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item baselinecreate_plan_snapshotwork_item_page;
                    global cn.ibizlab.plm.core.base.service.IbaselineService baselineservice;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
                    global cn.ibizlab.plm.core.base.service.IversionService versionservice;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.base.service.IbaselineService iBzSysBaselineDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "baselinecreate_plan_snapshotbegin"
            when
            then
            end

            //逻辑处理节点[设置快照类型]
            rule "prepareparam8"
            ruleflow-group "baselinecreate_plan_snapshotprepareparam8"
            when
            then
                            baselinecreate_plan_snapshotdefault.set("type","plan");
                        update(baselinecreate_plan_snapshotdefault);//更新fact中变量值
                        update(baselinecreate_plan_snapshotfor_temp_obj);//更新fact中变量值
                        update(baselinecreate_plan_snapshotrelation);//更新fact中变量值
                        update(baselinecreate_plan_snapshotversion);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_filter);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[设置基线状态]
            rule "prepareparam1"
            ruleflow-group "baselinecreate_plan_snapshotprepareparam1"
            when
            then
                            baselinecreate_plan_snapshotdefault.set("status","1");
                        update(baselinecreate_plan_snapshotdefault);//更新fact中变量值
                        update(baselinecreate_plan_snapshotfor_temp_obj);//更新fact中变量值
                        update(baselinecreate_plan_snapshotrelation);//更新fact中变量值
                        update(baselinecreate_plan_snapshotversion);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_filter);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[设置快照状态]
            rule "prepareparam2"
            ruleflow-group "baselinecreate_plan_snapshotprepareparam2"
            when
            then
                            baselinecreate_plan_snapshotdefault.set("status","3");
                        update(baselinecreate_plan_snapshotdefault);//更新fact中变量值
                        update(baselinecreate_plan_snapshotfor_temp_obj);//更新fact中变量值
                        update(baselinecreate_plan_snapshotrelation);//更新fact中变量值
                        update(baselinecreate_plan_snapshotversion);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_filter);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[创建规划快照]
            rule "deaction1"
            ruleflow-group "baselinecreate_plan_snapshotdeaction1"
            when
            then
                        baselineservice.create(baselinecreate_plan_snapshotdefault);
                        update(baselinecreate_plan_snapshotdefault);//更新fact中变量值
                        update(baselinecreate_plan_snapshotfor_temp_obj);//更新fact中变量值
                        update(baselinecreate_plan_snapshotrelation);//更新fact中变量值
                        update(baselinecreate_plan_snapshotversion);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_filter);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[传入项目标识至查询过滤器]
            rule "prepareparam3"
            ruleflow-group "baselinecreate_plan_snapshotprepareparam3"
            when
            then
                            baselinecreate_plan_snapshotwork_item_filter.set("n_project_id_eq",baselinecreate_plan_snapshotdefault.get("ownerid"));
                            baselinecreate_plan_snapshotwork_item_filter.set("size","10000");
                        update(baselinecreate_plan_snapshotdefault);//更新fact中变量值
                        update(baselinecreate_plan_snapshotfor_temp_obj);//更新fact中变量值
                        update(baselinecreate_plan_snapshotrelation);//更新fact中变量值
                        update(baselinecreate_plan_snapshotversion);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_filter);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[获取指定项目下的所有工作项]
            rule "dedataset1"
            ruleflow-group "baselinecreate_plan_snapshotdedataset1"
            when
            then
                        update(baselinecreate_plan_snapshotdefault);//更新fact中变量值
                        update(baselinecreate_plan_snapshotfor_temp_obj);//更新fact中变量值
                        update(baselinecreate_plan_snapshotrelation);//更新fact中变量值
                        update(baselinecreate_plan_snapshotversion);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_filter);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "baselinecreate_plan_snapshotloopsubcall1"
            when
            then
                        update(baselinecreate_plan_snapshotdefault);//更新fact中变量值
                        update(baselinecreate_plan_snapshotfor_temp_obj);//更新fact中变量值
                        update(baselinecreate_plan_snapshotrelation);//更新fact中变量值
                        update(baselinecreate_plan_snapshotversion);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_filter);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[重置关联对象]
            rule "resetparam1"
            ruleflow-group "baselinecreate_plan_snapshotresetparam1"
            when
            then
                        update(baselinecreate_plan_snapshotdefault);//更新fact中变量值
                        update(baselinecreate_plan_snapshotfor_temp_obj);//更新fact中变量值
                        update(baselinecreate_plan_snapshotrelation);//更新fact中变量值
                        update(baselinecreate_plan_snapshotversion);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_filter);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[将工作项标识赋值于关联对象]
            rule "prepareparam4"
            ruleflow-group "baselinecreate_plan_snapshotprepareparam4"
            when
            then
                            baselinecreate_plan_snapshotrelation.set("targetid",baselinecreate_plan_snapshotfor_temp_obj.get("id"));
                            baselinecreate_plan_snapshotrelation.set("principalid",baselinecreate_plan_snapshotdefault.get("id"));
                            baselinecreate_plan_snapshotrelation.set("targettype","work_item");
                            baselinecreate_plan_snapshotrelation.set("principaltype","baseline");
                        update(baselinecreate_plan_snapshotdefault);//更新fact中变量值
                        update(baselinecreate_plan_snapshotfor_temp_obj);//更新fact中变量值
                        update(baselinecreate_plan_snapshotrelation);//更新fact中变量值
                        update(baselinecreate_plan_snapshotversion);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_filter);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[关联对象版本标识]
            rule "prepareparam5"
            ruleflow-group "baselinecreate_plan_snapshotprepareparam5"
            when
            then
                            baselinecreate_plan_snapshotrelation.set("targetversionid",baselinecreate_plan_snapshotfor_temp_obj.get("curversionid"));
                        update(baselinecreate_plan_snapshotdefault);//更新fact中变量值
                        update(baselinecreate_plan_snapshotfor_temp_obj);//更新fact中变量值
                        update(baselinecreate_plan_snapshotrelation);//更新fact中变量值
                        update(baselinecreate_plan_snapshotversion);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_filter);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[重置版本对象]
            rule "resetparam2"
            ruleflow-group "baselinecreate_plan_snapshotresetparam2"
            when
            then
                        update(baselinecreate_plan_snapshotdefault);//更新fact中变量值
                        update(baselinecreate_plan_snapshotfor_temp_obj);//更新fact中变量值
                        update(baselinecreate_plan_snapshotrelation);//更新fact中变量值
                        update(baselinecreate_plan_snapshotversion);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_filter);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[准备初始化版本属性]
            rule "prepareparam6"
            ruleflow-group "baselinecreate_plan_snapshotprepareparam6"
            when
            then
                            baselinecreate_plan_snapshotversion.set("ownerid",baselinecreate_plan_snapshotfor_temp_obj.get("id"));
                            baselinecreate_plan_snapshotversion.set("description","初始化创建");
                            baselinecreate_plan_snapshotversion.set("ownertype","WORK_ITEM");
                            baselinecreate_plan_snapshotversion.set("name","v1");
                        update(baselinecreate_plan_snapshotdefault);//更新fact中变量值
                        update(baselinecreate_plan_snapshotfor_temp_obj);//更新fact中变量值
                        update(baselinecreate_plan_snapshotrelation);//更新fact中变量值
                        update(baselinecreate_plan_snapshotversion);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_filter);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[修复初始化版本]
            rule "deaction2"
            ruleflow-group "baselinecreate_plan_snapshotdeaction2"
            when
            then
                        versionservice.fix_commit(baselinecreate_plan_snapshotversion);
                        update(baselinecreate_plan_snapshotdefault);//更新fact中变量值
                        update(baselinecreate_plan_snapshotfor_temp_obj);//更新fact中变量值
                        update(baselinecreate_plan_snapshotrelation);//更新fact中变量值
                        update(baselinecreate_plan_snapshotversion);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_filter);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[关联对象版本标识]
            rule "prepareparam7"
            ruleflow-group "baselinecreate_plan_snapshotprepareparam7"
            when
            then
                            baselinecreate_plan_snapshotrelation.set("targetversionid",baselinecreate_plan_snapshotversion.get("id"));
                        update(baselinecreate_plan_snapshotdefault);//更新fact中变量值
                        update(baselinecreate_plan_snapshotfor_temp_obj);//更新fact中变量值
                        update(baselinecreate_plan_snapshotrelation);//更新fact中变量值
                        update(baselinecreate_plan_snapshotversion);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_filter);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[建立快照关联工作项数据]
            rule "deaction3"
            ruleflow-group "baselinecreate_plan_snapshotdeaction3"
            when
            then
                        relationservice.save(baselinecreate_plan_snapshotrelation);
                        update(baselinecreate_plan_snapshotdefault);//更新fact中变量值
                        update(baselinecreate_plan_snapshotfor_temp_obj);//更新fact中变量值
                        update(baselinecreate_plan_snapshotrelation);//更新fact中变量值
                        update(baselinecreate_plan_snapshotversion);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_filter);//更新fact中变量值
                        update(baselinecreate_plan_snapshotwork_item_page);//更新fact中变量值
            end