package cn.ibizlab.plm.base.logic.baselinelogic.set_complete;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.baseline baselineset_completedefault;
                global cn.ibizlab.plm.core.base.domain.relation baselineset_completefor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.relation baselineset_completerelation_filter;
                global cn.ibizlab.plm.core.base.domain.relation baselineset_completerelation_page;
                    global cn.ibizlab.plm.core.base.service.IbaselineService baselineservice;
        global cn.ibizlab.plm.core.base.service.IbaselineService iBzSysBaselineDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "baselineset_completebegin"
            when
            then
            end

            //逻辑处理节点[设立完成状态]
            rule "prepareparam1"
            ruleflow-group "baselineset_completeprepareparam1"
            when
            then
                            baselineset_completedefault.set("status","2");
                        update(baselineset_completedefault);//更新fact中变量值
                        update(baselineset_completefor_temp_obj);//更新fact中变量值
                        update(baselineset_completerelation_filter);//更新fact中变量值
                        update(baselineset_completerelation_page);//更新fact中变量值
            end

            //逻辑处理节点[设立完成]
            rule "deaction1"
            ruleflow-group "baselineset_completedeaction1"
            when
            then
                        baselineservice.update(baselineset_completedefault);
                        update(baselineset_completedefault);//更新fact中变量值
                        update(baselineset_completefor_temp_obj);//更新fact中变量值
                        update(baselineset_completerelation_filter);//更新fact中变量值
                        update(baselineset_completerelation_page);//更新fact中变量值
            end

            //逻辑处理节点[准备过滤器参数]
            rule "prepareparam2"
            ruleflow-group "baselineset_completeprepareparam2"
            when
            then
                            baselineset_completerelation_filter.set("n_principal_id_eq",baselineset_completedefault.get("id"));
                            baselineset_completerelation_filter.set("n_principal_type_eq","baseline");
                            baselineset_completerelation_filter.set("n_target_type_eq","work_item");
                        update(baselineset_completedefault);//更新fact中变量值
                        update(baselineset_completefor_temp_obj);//更新fact中变量值
                        update(baselineset_completerelation_filter);//更新fact中变量值
                        update(baselineset_completerelation_page);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "baselineset_completededataset1"
            when
            then
                        update(baselineset_completedefault);//更新fact中变量值
                        update(baselineset_completefor_temp_obj);//更新fact中变量值
                        update(baselineset_completerelation_filter);//更新fact中变量值
                        update(baselineset_completerelation_page);//更新fact中变量值
            end