package cn.ibizlab.plm.ai.logic.ai_modellogic.get_cloud_config;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_model ai_modelget_cloud_configdefault;
                global java.util.Map ai_modelget_cloud_configmap;
        global cn.ibizlab.plm.core.ai.service.Iai_modelService iBzSysAi_modelDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_modelget_cloud_configbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_modelget_cloud_configend_01"
            when
            then
                        update(ai_modelget_cloud_configdefault);//更新fact中变量值
                        update(ai_modelget_cloud_configmap);//更新fact中变量值
            end

            //逻辑处理节点[设置流和vlm]
            rule "prepareparam_02"
            ruleflow-group "ai_modelget_cloud_configprepareparam_02"
            when
            then
                            ai_modelget_cloud_configmap.set("descossimage","true");
                        update(ai_modelget_cloud_configdefault);//更新fact中变量值
                        update(ai_modelget_cloud_configmap);//更新fact中变量值
            end

            //逻辑处理节点[准备多模态类型]
            rule "prepareparam_07"
            ruleflow-group "ai_modelget_cloud_configprepareparam_07"
            when
            then
                            ai_modelget_cloud_configmap.set("aitype","QWENVL");
                        update(ai_modelget_cloud_configdefault);//更新fact中变量值
                        update(ai_modelget_cloud_configmap);//更新fact中变量值
            end

            //逻辑处理节点[发布oss配置代码]
            rule "rawsfcode_01"
            ruleflow-group "ai_modelget_cloud_configrawsfcode_01"
            when
            then
                        update(ai_modelget_cloud_configdefault);//更新fact中变量值
                        update(ai_modelget_cloud_configmap);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_06"
            ruleflow-group "ai_modelget_cloud_configprepareparam_06"
            when
            then
                            ai_modelget_cloud_configmap.set("stream","true");
                        update(ai_modelget_cloud_configdefault);//更新fact中变量值
                        update(ai_modelget_cloud_configmap);//更新fact中变量值
            end

            //逻辑处理节点[设置禁用]
            rule "prepareparam_01"
            ruleflow-group "ai_modelget_cloud_configprepareparam_01"
            when
            then
                            ai_modelget_cloud_configmap.set("disabled","1");
                        update(ai_modelget_cloud_configdefault);//更新fact中变量值
                        update(ai_modelget_cloud_configmap);//更新fact中变量值
            end

            //逻辑处理节点[设置tools]
            rule "prepareparam_04"
            ruleflow-group "ai_modelget_cloud_configprepareparam_04"
            when
            then
                            ai_modelget_cloud_configmap.set("tools","true");
                            ai_modelget_cloud_configmap.set("toolmaxcalls","20");
                        update(ai_modelget_cloud_configdefault);//更新fact中变量值
                        update(ai_modelget_cloud_configmap);//更新fact中变量值
            end

            //逻辑处理节点[设置aitype]
            rule "prepareparam_05"
            ruleflow-group "ai_modelget_cloud_configprepareparam_05"
            when
            then
                            ai_modelget_cloud_configmap.set("aitype","deepseek");
                        update(ai_modelget_cloud_configdefault);//更新fact中变量值
                        update(ai_modelget_cloud_configmap);//更新fact中变量值
            end

            //逻辑处理节点[设置think]
            rule "prepareparam_03"
            ruleflow-group "ai_modelget_cloud_configprepareparam_03"
            when
            then
                            ai_modelget_cloud_configmap.set("think","true");
                        update(ai_modelget_cloud_configdefault);//更新fact中变量值
                        update(ai_modelget_cloud_configmap);//更新fact中变量值
            end