package cn.ibizlab.plm.wiki.logic.article_pagelogic.access_password;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pageaccess_passworddefault;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pageaccess_passwordcheck_page;
                    global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService article_pageservice;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pageaccess_passwordbegin"
            when
            then
            end

            //逻辑处理节点[填充校验标识]
            rule "prepareparam3"
            ruleflow-group "article_pageaccess_passwordprepareparam3"
            when
            then
                            article_pageaccess_passwordcheck_page.set("id",article_pageaccess_passworddefault.get("id"));
                        update(article_pageaccess_passworddefault);//更新fact中变量值
                        update(article_pageaccess_passwordcheck_page);//更新fact中变量值
            end

            //逻辑处理节点[获取共享页面]
            rule "deaction1"
            ruleflow-group "article_pageaccess_passworddeaction1"
            when
            then
                        article_pageservice.shared(article_pageaccess_passwordcheck_page);
                        update(article_pageaccess_passworddefault);//更新fact中变量值
                        update(article_pageaccess_passwordcheck_page);//更新fact中变量值
            end

            //逻辑处理节点[校验链接是否有效]
            rule "rawsfcode1"
            ruleflow-group "article_pageaccess_passwordrawsfcode1"
            when
            then
                        update(article_pageaccess_passworddefault);//更新fact中变量值
                        update(article_pageaccess_passwordcheck_page);//更新fact中变量值
            end

            //逻辑处理节点[密码正确]
            rule "prepareparam1"
            ruleflow-group "article_pageaccess_passwordprepareparam1"
            when
            then
                            article_pageaccess_passworddefault.set("check_access_password","1");
                        update(article_pageaccess_passworddefault);//更新fact中变量值
                        update(article_pageaccess_passwordcheck_page);//更新fact中变量值
            end

            //逻辑处理节点[密码错误]
            rule "prepareparam2"
            ruleflow-group "article_pageaccess_passwordprepareparam2"
            when
            then
                            article_pageaccess_passworddefault.set("check_access_password","0");
                        update(article_pageaccess_passworddefault);//更新fact中变量值
                        update(article_pageaccess_passwordcheck_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pageaccess_passwordend1"
            when
            then
                        update(article_pageaccess_passworddefault);//更新fact中变量值
                        update(article_pageaccess_passwordcheck_page);//更新fact中变量值
            end