package cn.ibizlab.plm.wiki.logic.article_pagelogic.ai_create_page;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pageai_create_pagedefault;
                global cn.ibizlab.plm.core.base.domain.relation article_pageai_create_pagefilter;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pageai_create_pagepage;
                    global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService article_pageservice;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pageai_create_pagebegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "article_pageai_create_pagedebugparam1"
            when
            then
                        update(article_pageai_create_pagedefault);//更新fact中变量值
                        update(article_pageai_create_pagefilter);//更新fact中变量值
                        update(article_pageai_create_pagepage);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "article_pageai_create_pageprepareparam2"
            when
            then
                            article_pageai_create_pagefilter.set("n_principal_id_eq","");
                            article_pageai_create_pagefilter.set("n_target_type_eq","space");
                            article_pageai_create_pagefilter.set("n_principal_type_eq","project");
                            article_pageai_create_pagefilter.set("n_relation_type_eq","main_space");
                        update(article_pageai_create_pagedefault);//更新fact中变量值
                        update(article_pageai_create_pagefilter);//更新fact中变量值
                        update(article_pageai_create_pagepage);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "article_pageai_create_pageprepareparam1"
            when
            then
                            article_pageai_create_pagepage.set("formattype","MD");
                            article_pageai_create_pagepage.set("isarchived","0");
                            article_pageai_create_pagepage.set("isdeleted","0");
                            article_pageai_create_pagepage.set("isleaf","1");
                            article_pageai_create_pagepage.set("islock","0");
                            article_pageai_create_pagepage.set("ispublished","0");
                            article_pageai_create_pagepage.set("isshared","0");
                            article_pageai_create_pagepage.set("issharedsubset","0");
                            article_pageai_create_pagepage.set("name",article_pageai_create_pagedefault.get("name"));
                            article_pageai_create_pagepage.set("published","0");
                            article_pageai_create_pagepage.set("reviewresultstate","1");
                            article_pageai_create_pagepage.set("space","plm_space");
                            article_pageai_create_pagepage.set("spaceid","plm_space");
                            article_pageai_create_pagepage.set("spaceidentifier","PLM");
                            article_pageai_create_pagepage.set("spacename","产品生命周期管理系统");
                            article_pageai_create_pagepage.set("title",article_pageai_create_pagedefault.get("name"));
                            article_pageai_create_pagepage.set("type","1");
                            article_pageai_create_pagepage.set("content",article_pageai_create_pagedefault.get("content"));
                        update(article_pageai_create_pagedefault);//更新fact中变量值
                        update(article_pageai_create_pagefilter);//更新fact中变量值
                        update(article_pageai_create_pagepage);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "article_pageai_create_pagedeaction1"
            when
            then
                        article_pageservice.publish_page(article_pageai_create_pagepage);
                        update(article_pageai_create_pagedefault);//更新fact中变量值
                        update(article_pageai_create_pagefilter);//更新fact中变量值
                        update(article_pageai_create_pagepage);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pageai_create_pageend1"
            when
            then
                        update(article_pageai_create_pagedefault);//更新fact中变量值
                        update(article_pageai_create_pagefilter);//更新fact中变量值
                        update(article_pageai_create_pagepage);//更新fact中变量值
            end