package cn.ibizlab.plm.wiki.logic.article_pagelogic.check_shared;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagecheck_shareddefault;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagecheck_sharedresult;
                    global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService article_pageservice;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pagecheck_sharedbegin"
            when
            then
            end

            //逻辑处理节点[获取共享属性]
            rule "deaction1"
            ruleflow-group "article_pagecheck_shareddeaction1"
            when
            then
                        article_pageservice.shared(article_pagecheck_shareddefault);
                        update(article_pagecheck_shareddefault);//更新fact中变量值
                        update(article_pagecheck_sharedresult);//更新fact中变量值
            end

            //逻辑处理节点[检验是否有效]
            rule "rawsfcode1"
            ruleflow-group "article_pagecheck_sharedrawsfcode1"
            when
            then
                        update(article_pagecheck_shareddefault);//更新fact中变量值
                        update(article_pagecheck_sharedresult);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pagecheck_sharedend1"
            when
            then
                        update(article_pagecheck_shareddefault);//更新fact中变量值
                        update(article_pagecheck_sharedresult);//更新fact中变量值
            end