package cn.ibizlab.plm.wiki.logic.article_pagelogic.closed_shared;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pageclosed_shareddefault;
                    global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService article_pageservice;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pageclosed_sharedbegin"
            when
            then
            end

            //逻辑处理节点[设置页面关闭参数]
            rule "prepareparam1"
            ruleflow-group "article_pageclosed_sharedprepareparam1"
            when
            then
                            article_pageclosed_shareddefault.set("issharedsubset","0");
                                article_pageclosed_shareddefault.set("sharedtime",null);
                                article_pageclosed_shareddefault.set("sharedby",null);
                            article_pageclosed_shareddefault.set("isshared","0");
                                article_pageclosed_shareddefault.set("expirationdate",null);
                        update(article_pageclosed_shareddefault);//更新fact中变量值
            end

            //逻辑处理节点[更新页面信息]
            rule "deaction1"
            ruleflow-group "article_pageclosed_shareddeaction1"
            when
            then
                        article_pageservice.update(article_pageclosed_shareddefault);
                        update(article_pageclosed_shareddefault);//更新fact中变量值
            end

            //逻辑处理节点[直接sql调用]
            rule "rawsqlcall1"
            ruleflow-group "article_pageclosed_sharedrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",article_pageclosed_shareddefault.get("id"));
    String strSql="delete from `member` where owner_id = #{et.param0} and owner_type = 'PAGE' and OWNER_SUBTYPE = 'SHARED'";
                        iBzSysArticle_pageDefaultService.execute(strSql,param);//SQL调用
                        update(article_pageclosed_shareddefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pageclosed_sharedend1"
            when
            then
                        update(article_pageclosed_shareddefault);//更新fact中变量值
            end