package cn.ibizlab.plm.wiki.logic.article_pagelogic.encrypt_access_key;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pageencrypt_access_keydefault;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pageencrypt_access_keybegin"
            when
            then
            end

            //逻辑处理节点[加密]
            rule "prepareparam1"
            ruleflow-group "article_pageencrypt_access_keyprepareparam1"
            when
            then
                            article_pageencrypt_access_keydefault.set("accesspassword",article_pageencrypt_access_keydefault.get("accesspassword"));
                        update(article_pageencrypt_access_keydefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pageencrypt_access_keyend1"
            when
            then
                        update(article_pageencrypt_access_keydefault);//更新fact中变量值
            end