package cn.ibizlab.plm.wiki.logic.article_pagelogic.finish_add_attention;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagefinish_add_attentiondefault;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagefinish_add_attentionpage;
                global cn.ibizlab.plm.core.base.domain.attention article_pagefinish_add_attentionattention;
                global cn.ibizlab.plm.core.wiki.domain.space_member article_pagefinish_add_attentionfor_obj;
                global cn.ibizlab.plm.core.wiki.domain.space_member article_pagefinish_add_attentionsrfactionparam;
                    global cn.ibizlab.plm.core.base.service.IattentionService attentionservice;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pagefinish_add_attentionbegin"
            when
            then
            end

            //逻辑处理节点[获取列表]
            rule "bindparam1"
            ruleflow-group "article_pagefinish_add_attentionbindparam1"
            when
            then
                        update(article_pagefinish_add_attentiondefault);//更新fact中变量值
                        update(article_pagefinish_add_attentionpage);//更新fact中变量值
                        update(article_pagefinish_add_attentionattention);//更新fact中变量值
                        update(article_pagefinish_add_attentionfor_obj);//更新fact中变量值
                        update(article_pagefinish_add_attentionsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "article_pagefinish_add_attentionloopsubcall1"
            when
            then
                        update(article_pagefinish_add_attentiondefault);//更新fact中变量值
                        update(article_pagefinish_add_attentionpage);//更新fact中变量值
                        update(article_pagefinish_add_attentionattention);//更新fact中变量值
                        update(article_pagefinish_add_attentionfor_obj);//更新fact中变量值
                        update(article_pagefinish_add_attentionsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pagefinish_add_attentionend1"
            when
            then
                        update(article_pagefinish_add_attentiondefault);//更新fact中变量值
                        update(article_pagefinish_add_attentionpage);//更新fact中变量值
                        update(article_pagefinish_add_attentionattention);//更新fact中变量值
                        update(article_pagefinish_add_attentionfor_obj);//更新fact中变量值
                        update(article_pagefinish_add_attentionsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[设置参数]
            rule "prepareparam1"
            ruleflow-group "article_pagefinish_add_attentionprepareparam1"
            when
            then
                            article_pagefinish_add_attentionattention.set("ownerid",article_pagefinish_add_attentiondefault.get("id"));
                            article_pagefinish_add_attentionattention.set("ownersubtype","PAGE");
                            article_pagefinish_add_attentionattention.set("ownertype","PAGE");
                            article_pagefinish_add_attentionattention.set("type","40");
                            article_pagefinish_add_attentionattention.set("userid",article_pagefinish_add_attentionfor_obj.get("userid"));
                            article_pagefinish_add_attentionattention.set("name",article_pagefinish_add_attentionfor_obj.get("name"));
                        update(article_pagefinish_add_attentiondefault);//更新fact中变量值
                        update(article_pagefinish_add_attentionpage);//更新fact中变量值
                        update(article_pagefinish_add_attentionattention);//更新fact中变量值
                        update(article_pagefinish_add_attentionfor_obj);//更新fact中变量值
                        update(article_pagefinish_add_attentionsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[创建关注人]
            rule "deaction1"
            ruleflow-group "article_pagefinish_add_attentiondeaction1"
            when
            then
                        attentionservice.create(article_pagefinish_add_attentionattention);
                        update(article_pagefinish_add_attentiondefault);//更新fact中变量值
                        update(article_pagefinish_add_attentionpage);//更新fact中变量值
                        update(article_pagefinish_add_attentionattention);//更新fact中变量值
                        update(article_pagefinish_add_attentionfor_obj);//更新fact中变量值
                        update(article_pagefinish_add_attentionsrfactionparam);//更新fact中变量值
            end