package cn.ibizlab.plm.wiki.logic.article_pagelogic.get_by_version;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pageget_by_versiondefault;
                global cn.ibizlab.plm.core.base.domain.version article_pageget_by_versionversion;
                    global cn.ibizlab.plm.core.base.service.IversionService versionservice;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pageget_by_versionbegin"
            when
            then
            end

            //逻辑处理节点[版本不存在]
            rule "throwexception1"
            ruleflow-group "article_pageget_by_versionthrowexception1"
            when
            then
                        update(article_pageget_by_versiondefault);//更新fact中变量值
                        update(article_pageget_by_versionversion);//更新fact中变量值
            end

            //逻辑处理节点[拆分id]
            rule "rawsfcode1"
            ruleflow-group "article_pageget_by_versionrawsfcode1"
            when
            then
                        update(article_pageget_by_versiondefault);//更新fact中变量值
                        update(article_pageget_by_versionversion);//更新fact中变量值
            end

            //逻辑处理节点[获取版本数据]
            rule "deaction1"
            ruleflow-group "article_pageget_by_versiondeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(versionservice.get(article_pageget_by_versionversion.getId()),article_pageget_by_versionversion);
                        update(article_pageget_by_versiondefault);//更新fact中变量值
                        update(article_pageget_by_versionversion);//更新fact中变量值
            end

            //逻辑处理节点[版本不匹配]
            rule "throwexception2"
            ruleflow-group "article_pageget_by_versionthrowexception2"
            when
            then
                        update(article_pageget_by_versiondefault);//更新fact中变量值
                        update(article_pageget_by_versionversion);//更新fact中变量值
            end

            //逻辑处理节点[提取数据]
            rule "prepareparam2"
            ruleflow-group "article_pageget_by_versionprepareparam2"
            when
            then
                            article_pageget_by_versiondefault.set("",article_pageget_by_versionversion.get("data"));
                        update(article_pageget_by_versiondefault);//更新fact中变量值
                        update(article_pageget_by_versionversion);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pageget_by_versionend1"
            when
            then
                        update(article_pageget_by_versiondefault);//更新fact中变量值
                        update(article_pageget_by_versionversion);//更新fact中变量值
            end