package cn.ibizlab.plm.wiki.logic.article_pagelogic.lock_page;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagelock_pagedefault;
                global java.util.Map article_pagelock_pagepage_id;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagelock_pagepage_obj;
                    global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService article_pageservice;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pagelock_pagebegin"
            when
            then
            end

            //逻辑处理节点[设置主键]
            rule "prepareparam1"
            ruleflow-group "article_pagelock_pageprepareparam1"
            when
            then
                            article_pagelock_pagepage_id.set("",article_pagelock_pagedefault.get("id"));
                        update(article_pagelock_pagedefault);//更新fact中变量值
                        update(article_pagelock_pagepage_id);//更新fact中变量值
                        update(article_pagelock_pagepage_obj);//更新fact中变量值
            end

            //逻辑处理节点[获取页面数据]
            rule "deaction1"
            ruleflow-group "article_pagelock_pagedeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(article_pageservice.get(article_pagelock_pagepage_id.getId()),article_pagelock_pagepage_id);
                        update(article_pagelock_pagedefault);//更新fact中变量值
                        update(article_pagelock_pagepage_id);//更新fact中变量值
                        update(article_pagelock_pagepage_obj);//更新fact中变量值
            end

            //逻辑处理节点[设置is_lock字段]
            rule "prepareparam2"
            ruleflow-group "article_pagelock_pageprepareparam2"
            when
            then
                            article_pagelock_pagepage_obj.set("islock","1");
                        update(article_pagelock_pagedefault);//更新fact中变量值
                        update(article_pagelock_pagepage_id);//更新fact中变量值
                        update(article_pagelock_pagepage_obj);//更新fact中变量值
            end

            //逻辑处理节点[更新页面]
            rule "deaction2"
            ruleflow-group "article_pagelock_pagedeaction2"
            when
            then
                        article_pageservice.update(article_pagelock_pagepage_obj);
                        update(article_pagelock_pagedefault);//更新fact中变量值
                        update(article_pagelock_pagepage_id);//更新fact中变量值
                        update(article_pagelock_pagepage_obj);//更新fact中变量值
            end