package cn.ibizlab.plm.wiki.logic.article_pagelogic.set_name_version;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pageset_name_versiondefault;
                global java.util.Map article_pageset_name_versionform_data;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pageset_name_versionpage_detail;
                global java.util.Map article_pageset_name_versionsrfactionparam;
                global cn.ibizlab.plm.core.base.domain.version article_pageset_name_versionversion;
                    global cn.ibizlab.plm.core.base.service.IversionService versionservice;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pageset_name_versionbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pageset_name_versionend1"
            when
            then
                        update(article_pageset_name_versiondefault);//更新fact中变量值
                        update(article_pageset_name_versionform_data);//更新fact中变量值
                        update(article_pageset_name_versionpage_detail);//更新fact中变量值
                        update(article_pageset_name_versionsrfactionparam);//更新fact中变量值
                        update(article_pageset_name_versionversion);//更新fact中变量值
            end

            //逻辑处理节点[获取操作表单数据]
            rule "prepareparam2"
            ruleflow-group "article_pageset_name_versionprepareparam2"
            when
            then
                            article_pageset_name_versionsrfactionparam.set("",article_pageset_name_versiondefault.get("srfactionparam"));
                            article_pageset_name_versionform_data.set("",article_pageset_name_versionsrfactionparam.get("0"));
                        update(article_pageset_name_versiondefault);//更新fact中变量值
                        update(article_pageset_name_versionform_data);//更新fact中变量值
                        update(article_pageset_name_versionpage_detail);//更新fact中变量值
                        update(article_pageset_name_versionsrfactionparam);//更新fact中变量值
                        update(article_pageset_name_versionversion);//更新fact中变量值
            end

            //逻辑处理节点[版本数据]
            rule "prepareparam3"
            ruleflow-group "article_pageset_name_versionprepareparam3"
            when
            then
                            article_pageset_name_versionversion.set("id",article_pageset_name_versionform_data.get("version_id"));
                            article_pageset_name_versionversion.set("name",article_pageset_name_versionform_data.get("version_name"));
                            article_pageset_name_versionversion.set("isnamed","1");
                        update(article_pageset_name_versiondefault);//更新fact中变量值
                        update(article_pageset_name_versionform_data);//更新fact中变量值
                        update(article_pageset_name_versionpage_detail);//更新fact中变量值
                        update(article_pageset_name_versionsrfactionparam);//更新fact中变量值
                        update(article_pageset_name_versionversion);//更新fact中变量值
            end

            //逻辑处理节点[更新版本数据]
            rule "deaction2"
            ruleflow-group "article_pageset_name_versiondeaction2"
            when
            then
                        versionservice.update(article_pageset_name_versionversion);
                        update(article_pageset_name_versiondefault);//更新fact中变量值
                        update(article_pageset_name_versionform_data);//更新fact中变量值
                        update(article_pageset_name_versionpage_detail);//更新fact中变量值
                        update(article_pageset_name_versionsrfactionparam);//更新fact中变量值
                        update(article_pageset_name_versionversion);//更新fact中变量值
            end