package cn.ibizlab.plm.wiki.logic.article_pagelogic.shared_url;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pageshared_urldefault;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pageshared_urlbegin"
            when
            then
            end

            //逻辑处理节点[拼接共享链接]
            rule "rawsfcode1"
            ruleflow-group "article_pageshared_urlrawsfcode1"
            when
            then
                        update(article_pageshared_urldefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pageshared_urlend1"
            when
            then
                        update(article_pageshared_urldefault);//更新fact中变量值
            end