package cn.ibizlab.plm.wiki.logic.space_memberlogic.remove_space_member_notify;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.space_member space_memberremove_space_member_notifydefault;
                    global cn.ibizlab.plm.core.wiki.service.Ispace_memberService space_memberservice;
        global cn.ibizlab.plm.core.wiki.service.Ispace_memberService iBzSysSpace_memberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "space_memberremove_space_member_notifybegin"
            when
            then
            end

            //逻辑处理节点[获取数据]
            rule "deaction1"
            ruleflow-group "space_memberremove_space_member_notifydeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(space_memberservice.get(space_memberremove_space_member_notifydefault.getId()),space_memberremove_space_member_notifydefault);
                        update(space_memberremove_space_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[绑定当前操作人]
            rule "prepareparam1"
            ruleflow-group "space_memberremove_space_member_notifyprepareparam1"
            when
            then
                                space_memberremove_space_member_notifydefault.set("updateman",curuser.getSessionParams().get("srfpersonid"));
                        update(space_memberremove_space_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[获取当前操作时间]
            rule "rawsfcode1"
            ruleflow-group "space_memberremove_space_member_notifyrawsfcode1"
            when
            then
                        update(space_memberremove_space_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[移除空间成员通知]
            rule "denotify1"
            ruleflow-group "space_memberremove_space_member_notifydenotify1"
            when
            then
                        update(space_memberremove_space_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "space_memberremove_space_member_notifyend1"
            when
            then
                        update(space_memberremove_space_member_notifydefault);//更新fact中变量值
            end