package cn.ibizlab.plm.base.logic.dyna_dashboardlogic.fill_other_board;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.dyna_dashboard dyna_dashboardfill_other_boarddefault;
                global cn.ibizlab.plm.core.base.domain.dyna_dashboard dyna_dashboardfill_other_boardboard_info;
                global cn.ibizlab.plm.core.base.domain.dyna_dashboard dyna_dashboardfill_other_boardboard_page;
                global cn.ibizlab.plm.core.base.domain.dyna_dashboard dyna_dashboardfill_other_boardfilter;
                    global cn.ibizlab.plm.core.base.service.Idyna_dashboardService dyna_dashboardservice;
        global cn.ibizlab.plm.core.base.service.Idyna_dashboardService iBzSysDyna_dashboardDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "dyna_dashboardfill_other_boardbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "dyna_dashboardfill_other_boardend1"
            when
            then
                        update(dyna_dashboardfill_other_boarddefault);//更新fact中变量值
                        update(dyna_dashboardfill_other_boardboard_info);//更新fact中变量值
                        update(dyna_dashboardfill_other_boardboard_page);//更新fact中变量值
                        update(dyna_dashboardfill_other_boardfilter);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "dyna_dashboardfill_other_boarddebugparam1"
            when
            then
                        update(dyna_dashboardfill_other_boarddefault);//更新fact中变量值
                        update(dyna_dashboardfill_other_boardboard_info);//更新fact中变量值
                        update(dyna_dashboardfill_other_boardboard_page);//更新fact中变量值
                        update(dyna_dashboardfill_other_boardfilter);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "dyna_dashboardfill_other_boardprepareparam1"
            when
            then
                            dyna_dashboardfill_other_boardfilter.set("n_owner_id_eq",dyna_dashboardfill_other_boarddefault.get("ownerid"));
                        update(dyna_dashboardfill_other_boarddefault);//更新fact中变量值
                        update(dyna_dashboardfill_other_boardboard_info);//更新fact中变量值
                        update(dyna_dashboardfill_other_boardboard_page);//更新fact中变量值
                        update(dyna_dashboardfill_other_boardfilter);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "dyna_dashboardfill_other_boarddedataset1"
            when
            then
                        update(dyna_dashboardfill_other_boarddefault);//更新fact中变量值
                        update(dyna_dashboardfill_other_boardboard_info);//更新fact中变量值
                        update(dyna_dashboardfill_other_boardboard_page);//更新fact中变量值
                        update(dyna_dashboardfill_other_boardfilter);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "dyna_dashboardfill_other_boardprepareparam2"
            when
            then
                            dyna_dashboardfill_other_boardboard_info.set("",dyna_dashboardfill_other_boardboard_page.get("0"));
                        update(dyna_dashboardfill_other_boarddefault);//更新fact中变量值
                        update(dyna_dashboardfill_other_boardboard_info);//更新fact中变量值
                        update(dyna_dashboardfill_other_boardboard_page);//更新fact中变量值
                        update(dyna_dashboardfill_other_boardfilter);//更新fact中变量值
            end