package cn.ibizlab.plm.base.logic.dyna_dashboardlogic.sync_portlet_model;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.dyna_dashboard dyna_dashboardsync_portlet_modeldefault;
        global cn.ibizlab.plm.core.base.service.Idyna_dashboardService iBzSysDyna_dashboardDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "dyna_dashboardsync_portlet_modelbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "dyna_dashboardsync_portlet_modelend1"
            when
            then
                        update(dyna_dashboardsync_portlet_modeldefault);//更新fact中变量值
            end

            //逻辑处理节点[更新看板部件模型]
            rule "rawsfcode1"
            ruleflow-group "dyna_dashboardsync_portlet_modelrawsfcode1"
            when
            then
                        update(dyna_dashboardsync_portlet_modeldefault);//更新fact中变量值
            end