package cn.ibizlab.plm.base.logic.workloadlogic.ai_add_estimated_workload;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.workload workloadai_add_estimated_workloaddefault;
        global cn.ibizlab.plm.core.base.service.IworkloadService iBzSysWorkloadDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "workloadai_add_estimated_workloadbegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "workloadai_add_estimated_workloaddebugparam1"
            when
            then
                        update(workloadai_add_estimated_workloaddefault);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "workloadai_add_estimated_workloadprepareparam1"
            when
            then
                        update(workloadai_add_estimated_workloaddefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "workloadai_add_estimated_workloadend1"
            when
            then
                        update(workloadai_add_estimated_workloaddefault);//更新fact中变量值
            end