package cn.ibizlab.plm.base.logic.workloadlogic.fill_workload_data;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.workload workloadfill_workload_datadefault;
                global java.util.Map workloadfill_workload_dataobj;
                global cn.ibizlab.plm.core.base.domain.workload workloadfill_workload_dataresult;
        global cn.ibizlab.plm.core.base.service.IworkloadService iBzSysWorkloadDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "workloadfill_workload_databegin"
            when
            then
            end

            //逻辑处理节点[设置工时principal_id]
            rule "prepareparam1"
            ruleflow-group "workloadfill_workload_dataprepareparam1"
            when
            then
                            workloadfill_workload_dataobj.set("principal_id",workloadfill_workload_datadefault.get("n_principal_id_eq"));
                        update(workloadfill_workload_datadefault);//更新fact中变量值
                        update(workloadfill_workload_dataobj);//更新fact中变量值
                        update(workloadfill_workload_dataresult);//更新fact中变量值
            end

            //逻辑处理节点[获取工时信息外加work_item_type_id]
            rule "rawsqlcall1"
            ruleflow-group "workloadfill_workload_datarawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",workloadfill_workload_dataobj.get("principal_id"));
    String strSql="SELECT t1.PRINCIPAL_ID,        t1.PRINCIPAL_TYPE,        t1.DURATION,        t2.WORK_ITEM_TYPE_ID,        t1.`ID`,        t1.`NAME`,        t1.`PRINCIPAL_TYPE`,        concat(t1.`RECENT_PARENT_IDENTIFIER`, '-', t1.`IDENTIFIER`) AS `SHOW_IDENTIFIER` FROM workload t1          LEFT JOIN `work_item` t2 ON t1.PRINCIPAL_ID = t2.ID where t1.PRINCIPAL_ID = #{et.param0} limit 1";
                        java.util.List<JSONObject> entities=iBzSysWorkloadDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    workloadfill_workload_dataresult.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(workloadfill_workload_datadefault);//更新fact中变量值
                        update(workloadfill_workload_dataobj);//更新fact中变量值
                        update(workloadfill_workload_dataresult);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "workloadfill_workload_dataend1"
            when
            then
                        update(workloadfill_workload_datadefault);//更新fact中变量值
                        update(workloadfill_workload_dataobj);//更新fact中变量值
                        update(workloadfill_workload_dataresult);//更新fact中变量值
            end