package cn.ibizlab.plm.base.logic.workloadlogic.get_redirect_data;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.workload workloadget_redirect_datadefault;
                    global cn.ibizlab.plm.core.base.service.IworkloadService workloadservice;
        global cn.ibizlab.plm.core.base.service.IworkloadService iBzSysWorkloadDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "workloadget_redirect_databegin"
            when
            then
            end

            //逻辑处理节点[获取重定向数据]
            rule "deaction1"
            ruleflow-group "workloadget_redirect_datadeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(workloadservice.get(workloadget_redirect_datadefault.getId()),workloadget_redirect_datadefault);
                        update(workloadget_redirect_datadefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "workloadget_redirect_dataend1"
            when
            then
                        update(workloadget_redirect_datadefault);//更新fact中变量值
            end