package cn.ibizlab.plm.base.logic.workloadlogic.group_member_dimension;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.workload workloadgroup_member_dimensiondefault;
                global cn.ibizlab.plm.core.base.domain.workload workloadgroup_member_dimensionworkload_page;
                    global cn.ibizlab.plm.core.base.service.IworkloadService workloadservice;
        global cn.ibizlab.plm.core.base.service.IworkloadService iBzSysWorkloadDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "workloadgroup_member_dimensionbegin"
            when
            then
            end

            //逻辑处理节点[重置查询分页参数]
            rule "prepareparam1"
            ruleflow-group "workloadgroup_member_dimensionprepareparam1"
            when
            then
                            workloadgroup_member_dimensiondefault.set("size","10000");
                        update(workloadgroup_member_dimensiondefault);//更新fact中变量值
                        update(workloadgroup_member_dimensionworkload_page);//更新fact中变量值
            end

            //逻辑处理节点[查询工时数据]
            rule "dedataset1"
            ruleflow-group "workloadgroup_member_dimensiondedataset1"
            when
            then
                        update(workloadgroup_member_dimensiondefault);//更新fact中变量值
                        update(workloadgroup_member_dimensionworkload_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "workloadgroup_member_dimensionend1"
            when
            then
                        update(workloadgroup_member_dimensiondefault);//更新fact中变量值
                        update(workloadgroup_member_dimensionworkload_page);//更新fact中变量值
            end