package cn.ibizlab.plm.base.logic.workloadlogic.idea_dimension;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.workload workloadidea_dimensiondefault;
                global cn.ibizlab.plm.core.base.domain.workload workloadidea_dimensionpage;
                    global cn.ibizlab.plm.core.base.service.IworkloadService workloadservice;
        global cn.ibizlab.plm.core.base.service.IworkloadService iBzSysWorkloadDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "workloadidea_dimensionbegin"
            when
            then
            end

            //逻辑处理节点[重置分页参数]
            rule "prepareparam1"
            ruleflow-group "workloadidea_dimensionprepareparam1"
            when
            then
                            workloadidea_dimensiondefault.set("size","10000");
                        update(workloadidea_dimensiondefault);//更新fact中变量值
                        update(workloadidea_dimensionpage);//更新fact中变量值
            end

            //逻辑处理节点[查询我登记的产品需求工时]
            rule "dedataset1"
            ruleflow-group "workloadidea_dimensiondedataset1"
            when
            then
                        update(workloadidea_dimensiondefault);//更新fact中变量值
                        update(workloadidea_dimensionpage);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "workloadidea_dimensionend1"
            when
            then
                        update(workloadidea_dimensiondefault);//更新fact中变量值
                        update(workloadidea_dimensionpage);//更新fact中变量值
            end