package cn.ibizlab.plm.base.logic.departmentlogic.dept_filter;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.department departmentdept_filterdefault;
                global cn.ibizlab.plm.core.base.domain.department departmentdept_filterdept_filter;
                global cn.ibizlab.plm.core.base.domain.department departmentdept_filterdept_page;
                global cn.ibizlab.plm.core.base.domain.department departmentdept_filterresult_list;
                global java.util.Map departmentdept_filtertemp;
                    global cn.ibizlab.plm.core.base.service.IdepartmentService departmentservice;
        global cn.ibizlab.plm.core.base.service.IdepartmentService iBzSysDepartmentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "departmentdept_filterbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "departmentdept_filterend2"
            when
            then
                        update(departmentdept_filterdefault);//更新fact中变量值
                        update(departmentdept_filterdept_filter);//更新fact中变量值
                        update(departmentdept_filterdept_page);//更新fact中变量值
                        update(departmentdept_filterresult_list);//更新fact中变量值
                        update(departmentdept_filtertemp);//更新fact中变量值
            end

            //逻辑处理节点[部门过滤]
            rule "dedataset1"
            ruleflow-group "departmentdept_filterdedataset1"
            when
            then
                        update(departmentdept_filterdefault);//更新fact中变量值
                        update(departmentdept_filterdept_filter);//更新fact中变量值
                        update(departmentdept_filterdept_page);//更新fact中变量值
                        update(departmentdept_filterresult_list);//更新fact中变量值
                        update(departmentdept_filtertemp);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "departmentdept_filterprepareparam1"
            when
            then
                            departmentdept_filterdept_filter.set("n_id_noteq",departmentdept_filterdefault.get("cur_id"));
                        update(departmentdept_filterdefault);//更新fact中变量值
                        update(departmentdept_filterdept_filter);//更新fact中变量值
                        update(departmentdept_filterdept_page);//更新fact中变量值
                        update(departmentdept_filterresult_list);//更新fact中变量值
                        update(departmentdept_filtertemp);//更新fact中变量值
            end