package cn.ibizlab.plm.wiki.logic.spacelogic.create_recent;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.space spacecreate_recentdefault;
                global cn.ibizlab.plm.core.base.domain.recent spacecreate_recentrecent;
                    global cn.ibizlab.plm.core.base.service.IrecentService recentservice;
        global cn.ibizlab.plm.core.wiki.service.IspaceService iBzSysSpaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "spacecreate_recentbegin"
            when
            then
            end

            //逻辑处理节点[准备最近访问参数]
            rule "prepareparam1"
            ruleflow-group "spacecreate_recentprepareparam1"
            when
            then
                            spacecreate_recentrecent.set("ownerid",spacecreate_recentdefault.get("id"));
                            spacecreate_recentrecent.set("recentparentidentifier",spacecreate_recentdefault.get("identifier"));
                            spacecreate_recentrecent.set("recentparentname",spacecreate_recentdefault.get("name"));
                            spacecreate_recentrecent.set("recentparent",spacecreate_recentdefault.get("id"));
                                spacecreate_recentrecent.set("createman",curuser.getSessionParams().get("srfpersonid"));
                            spacecreate_recentrecent.set("type","1");
                            spacecreate_recentrecent.set("name",spacecreate_recentdefault.get("name"));
                            spacecreate_recentrecent.set("ownertype","space");
                            spacecreate_recentrecent.set("ownersubtype","space");
                        update(spacecreate_recentdefault);//更新fact中变量值
                        update(spacecreate_recentrecent);//更新fact中变量值
            end

            //逻辑处理节点[保存最近访问]
            rule "deaction1"
            ruleflow-group "spacecreate_recentdeaction1"
            when
            then
                        recentservice.save(spacecreate_recentrecent);
                        update(spacecreate_recentdefault);//更新fact中变量值
                        update(spacecreate_recentrecent);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "spacecreate_recentend1"
            when
            then
                        update(spacecreate_recentdefault);//更新fact中变量值
                        update(spacecreate_recentrecent);//更新fact中变量值
            end