package cn.ibizlab.plm.wiki.logic.spacelogic.get_space_member_one;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.space spaceget_space_member_onedefault;
                global cn.ibizlab.plm.core.wiki.domain.space_member spaceget_space_member_onefilter;
                global java.util.Map spaceget_space_member_onefor_obj;
                global cn.ibizlab.plm.core.wiki.domain.space_member spaceget_space_member_onemembers;
                global java.util.Map spaceget_space_member_oneuser;
                    global cn.ibizlab.plm.core.wiki.service.Ispace_memberService space_memberservice;
        global cn.ibizlab.plm.core.wiki.service.IspaceService iBzSysSpaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "spaceget_space_member_onebegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "spaceget_space_member_oneend2"
            when
            then
                        update(spaceget_space_member_onedefault);//更新fact中变量值
                        update(spaceget_space_member_onefilter);//更新fact中变量值
                        update(spaceget_space_member_onefor_obj);//更新fact中变量值
                        update(spaceget_space_member_onemembers);//更新fact中变量值
                        update(spaceget_space_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[获取知识空间id并设置过滤参数]
            rule "prepareparam2"
            ruleflow-group "spaceget_space_member_oneprepareparam2"
            when
            then
                            spaceget_space_member_onefilter.set("n_space_id_eq",spaceget_space_member_onedefault.get("id"));
                                spaceget_space_member_onefilter.set("n_user_id_eq",curuser.getSessionParams().get("srfpersonid"));
                        update(spaceget_space_member_onedefault);//更新fact中变量值
                        update(spaceget_space_member_onefilter);//更新fact中变量值
                        update(spaceget_space_member_onefor_obj);//更新fact中变量值
                        update(spaceget_space_member_onemembers);//更新fact中变量值
                        update(spaceget_space_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[查询当前用户是否为知识空间成员]
            rule "dedataset3"
            ruleflow-group "spaceget_space_member_onededataset3"
            when
            then
                        update(spaceget_space_member_onedefault);//更新fact中变量值
                        update(spaceget_space_member_onefilter);//更新fact中变量值
                        update(spaceget_space_member_onefor_obj);//更新fact中变量值
                        update(spaceget_space_member_onemembers);//更新fact中变量值
                        update(spaceget_space_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[绑定用户数据到for_obj]
            rule "prepareparam5"
            ruleflow-group "spaceget_space_member_oneprepareparam5"
            when
            then
                            spaceget_space_member_onefor_obj.set("",spaceget_space_member_onemembers.get("0"));
                        update(spaceget_space_member_onedefault);//更新fact中变量值
                        update(spaceget_space_member_onefilter);//更新fact中变量值
                        update(spaceget_space_member_onefor_obj);//更新fact中变量值
                        update(spaceget_space_member_onemembers);//更新fact中变量值
                        update(spaceget_space_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[只读权限]
            rule "rawsfcode1"
            ruleflow-group "spaceget_space_member_onerawsfcode1"
            when
            then
                        update(spaceget_space_member_onedefault);//更新fact中变量值
                        update(spaceget_space_member_onefilter);//更新fact中变量值
                        update(spaceget_space_member_onefor_obj);//更新fact中变量值
                        update(spaceget_space_member_onemembers);//更新fact中变量值
                        update(spaceget_space_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[非只读权限]
            rule "rawsfcode2"
            ruleflow-group "spaceget_space_member_onerawsfcode2"
            when
            then
                        update(spaceget_space_member_onedefault);//更新fact中变量值
                        update(spaceget_space_member_onefilter);//更新fact中变量值
                        update(spaceget_space_member_onefor_obj);//更新fact中变量值
                        update(spaceget_space_member_onemembers);//更新fact中变量值
                        update(spaceget_space_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end6"
            ruleflow-group "spaceget_space_member_oneend6"
            when
            then
                        update(spaceget_space_member_onedefault);//更新fact中变量值
                        update(spaceget_space_member_onefilter);//更新fact中变量值
                        update(spaceget_space_member_onefor_obj);//更新fact中变量值
                        update(spaceget_space_member_onemembers);//更新fact中变量值
                        update(spaceget_space_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[判断系统管理员身份]
            rule "rawsfcode3"
            ruleflow-group "spaceget_space_member_onerawsfcode3"
            when
            then
                        update(spaceget_space_member_onedefault);//更新fact中变量值
                        update(spaceget_space_member_onefilter);//更新fact中变量值
                        update(spaceget_space_member_onefor_obj);//更新fact中变量值
                        update(spaceget_space_member_onemembers);//更新fact中变量值
                        update(spaceget_space_member_oneuser);//更新fact中变量值
            end