package cn.ibizlab.plm.wiki.logic.spacelogic.get_re_space;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.space spaceget_re_spacedefault;
        global cn.ibizlab.plm.core.wiki.service.IspaceService iBzSysSpaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "spaceget_re_spacebegin"
            when
            then
            end

            //逻辑处理节点[直接sql调用]
            rule "rawsqlcall1"
            ruleflow-group "spaceget_re_spacerawsqlcall1"
            when
            then
                        Map param = null;
                        String strSql="";
                        iBzSysSpaceDefaultService.execute(strSql,param);//SQL调用
                        update(spaceget_re_spacedefault);//更新fact中变量值
            end