package cn.ibizlab.plm.wiki.logic.spacelogic.move_space;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.space spacemove_spacedefault;
                global cn.ibizlab.plm.core.wiki.domain.space spacemove_spacefor_temp;
                global java.util.Map spacemove_spaceid;
                global cn.ibizlab.plm.core.wiki.domain.space spacemove_spacesrfactionparam;
                global cn.ibizlab.plm.core.wiki.domain.space spacemove_spacetemp_space;
                    global cn.ibizlab.plm.core.wiki.service.IspaceService spaceservice;
        global cn.ibizlab.plm.core.wiki.service.IspaceService iBzSysSpaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "spacemove_spacebegin"
            when
            then
            end

            //逻辑处理节点[绑定要更改的数据]
            rule "bindparam1"
            ruleflow-group "spacemove_spacebindparam1"
            when
            then
                        update(spacemove_spacedefault);//更新fact中变量值
                        update(spacemove_spacefor_temp);//更新fact中变量值
                        update(spacemove_spaceid);//更新fact中变量值
                        update(spacemove_spacesrfactionparam);//更新fact中变量值
                        update(spacemove_spacetemp_space);//更新fact中变量值
            end

            //逻辑处理节点[绑定id]
            rule "bindparam2"
            ruleflow-group "spacemove_spacebindparam2"
            when
            then
                        update(spacemove_spacedefault);//更新fact中变量值
                        update(spacemove_spacefor_temp);//更新fact中变量值
                        update(spacemove_spaceid);//更新fact中变量值
                        update(spacemove_spacesrfactionparam);//更新fact中变量值
                        update(spacemove_spacetemp_space);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "spacemove_spaceend1"
            when
            then
                        update(spacemove_spacedefault);//更新fact中变量值
                        update(spacemove_spacefor_temp);//更新fact中变量值
                        update(spacemove_spaceid);//更新fact中变量值
                        update(spacemove_spacesrfactionparam);//更新fact中变量值
                        update(spacemove_spacetemp_space);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "spacemove_spaceloopsubcall1"
            when
            then
                        update(spacemove_spacedefault);//更新fact中变量值
                        update(spacemove_spacefor_temp);//更新fact中变量值
                        update(spacemove_spaceid);//更新fact中变量值
                        update(spacemove_spacesrfactionparam);//更新fact中变量值
                        update(spacemove_spacetemp_space);//更新fact中变量值
            end

            //逻辑处理节点[准备待更新的空间数据]
            rule "prepareparam1"
            ruleflow-group "spacemove_spaceprepareparam1"
            when
            then
                            spacemove_spacetemp_space.set("id",spacemove_spaceid.get(""));
                            spacemove_spacetemp_space.set("scopeid",spacemove_spacefor_temp.get("scopeid"));
                            spacemove_spacetemp_space.set("scopetype",spacemove_spacefor_temp.get("scopetype"));
                            spacemove_spacetemp_space.set("visibility",spacemove_spacefor_temp.get("visibility"));
                        update(spacemove_spacedefault);//更新fact中变量值
                        update(spacemove_spacefor_temp);//更新fact中变量值
                        update(spacemove_spaceid);//更新fact中变量值
                        update(spacemove_spacesrfactionparam);//更新fact中变量值
                        update(spacemove_spacetemp_space);//更新fact中变量值
            end

            //逻辑处理节点[更新空间数据]
            rule "deaction1"
            ruleflow-group "spacemove_spacedeaction1"
            when
            then
                        spaceservice.update(spacemove_spacetemp_space);
                        update(spacemove_spacedefault);//更新fact中变量值
                        update(spacemove_spacefor_temp);//更新fact中变量值
                        update(spacemove_spaceid);//更新fact中变量值
                        update(spacemove_spacesrfactionparam);//更新fact中变量值
                        update(spacemove_spacetemp_space);//更新fact中变量值
            end