package cn.ibizlab.plm.wiki.logic.spacelogic.open_shared;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.space spaceopen_shareddefault;
                global cn.ibizlab.plm.core.wiki.domain.shared_space spaceopen_sharedshared_space;
                    global cn.ibizlab.plm.core.wiki.service.Ishared_spaceService shared_spaceservice;
        global cn.ibizlab.plm.core.wiki.service.IspaceService iBzSysSpaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "spaceopen_sharedbegin"
            when
            then
            end

            //逻辑处理节点[设置默认共享状态]
            rule "prepareparam1"
            ruleflow-group "spaceopen_sharedprepareparam1"
            when
            then
                            spaceopen_sharedshared_space.set("isshared","1");
                            spaceopen_sharedshared_space.set("id",spaceopen_shareddefault.get("id"));
                                spaceopen_sharedshared_space.set("sharedby",curuser.getSessionParams().get("srfpersonid"));
                        update(spaceopen_shareddefault);//更新fact中变量值
                        update(spaceopen_sharedshared_space);//更新fact中变量值
            end

            //逻辑处理节点[填充共享时间]
            rule "rawsfcode1"
            ruleflow-group "spaceopen_sharedrawsfcode1"
            when
            then
                        update(spaceopen_shareddefault);//更新fact中变量值
                        update(spaceopen_sharedshared_space);//更新fact中变量值
            end

            //逻辑处理节点[开启共享]
            rule "deaction1"
            ruleflow-group "spaceopen_shareddeaction1"
            when
            then
                        shared_spaceservice.update(spaceopen_sharedshared_space);
                        update(spaceopen_shareddefault);//更新fact中变量值
                        update(spaceopen_sharedshared_space);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "spaceopen_sharedend1"
            when
            then
                        update(spaceopen_shareddefault);//更新fact中变量值
                        update(spaceopen_sharedshared_space);//更新fact中变量值
            end