package cn.ibizlab.plm.wiki.logic.spacelogic.other_re_space;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.space spaceother_re_spacedefault;
                global cn.ibizlab.plm.core.base.domain.relation spaceother_re_spacerelationobj;
                global cn.ibizlab.plm.core.base.domain.relation spaceother_re_spacerelationobj2;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.wiki.service.IspaceService iBzSysSpaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "spaceother_re_spacebegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "spaceother_re_spacedebugparam1"
            when
            then
                        update(spaceother_re_spacedefault);//更新fact中变量值
                        update(spaceother_re_spacerelationobj);//更新fact中变量值
                        update(spaceother_re_spacerelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[准备关联参数]
            rule "prepareparam1"
            ruleflow-group "spaceother_re_spaceprepareparam1"
            when
            then
                            spaceother_re_spacerelationobj2.set("targetid",spaceother_re_spacedefault.get("space_id"));
                            spaceother_re_spacerelationobj2.set("targettype",spaceother_re_spacedefault.get("target_type"));
                            spaceother_re_spacerelationobj2.set("principalid",spaceother_re_spacedefault.get("target_id"));
                            spaceother_re_spacerelationobj2.set("principaltype",spaceother_re_spacedefault.get("principal_type"));
                            spaceother_re_spacerelationobj.set("targetid",spaceother_re_spacedefault.get("target_id"));
                            spaceother_re_spacerelationobj.set("targettype",spaceother_re_spacedefault.get("principal_type"));
                            spaceother_re_spacerelationobj.set("principalid",spaceother_re_spacedefault.get("space_id"));
                            spaceother_re_spacerelationobj.set("principaltype",spaceother_re_spacedefault.get("target_type"));
                        update(spaceother_re_spacedefault);//更新fact中变量值
                        update(spaceother_re_spacerelationobj);//更新fact中变量值
                        update(spaceother_re_spacerelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[生成正向关联数据]
            rule "deaction1"
            ruleflow-group "spaceother_re_spacedeaction1"
            when
            then
                        relationservice.create(spaceother_re_spacerelationobj);
                        update(spaceother_re_spacedefault);//更新fact中变量值
                        update(spaceother_re_spacerelationobj);//更新fact中变量值
                        update(spaceother_re_spacerelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[生成反向关联数据]
            rule "deaction2"
            ruleflow-group "spaceother_re_spacedeaction2"
            when
            then
                        relationservice.create(spaceother_re_spacerelationobj2);
                        update(spaceother_re_spacedefault);//更新fact中变量值
                        update(spaceother_re_spacerelationobj);//更新fact中变量值
                        update(spaceother_re_spacerelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[抛出异常]
            rule "throwexception1"
            ruleflow-group "spaceother_re_spacethrowexception1"
            when
            then
                        update(spaceother_re_spacedefault);//更新fact中变量值
                        update(spaceother_re_spacerelationobj);//更新fact中变量值
                        update(spaceother_re_spacerelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "spaceother_re_spaceend1"
            when
            then
                        update(spaceother_re_spacedefault);//更新fact中变量值
                        update(spaceother_re_spacerelationobj);//更新fact中变量值
                        update(spaceother_re_spacerelationobj2);//更新fact中变量值
            end