package cn.ibizlab.plm.prodmgmt.logic.productlogic.before_create;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.Product productbefore_createdefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.Product_member productbefore_createmember;
                global cn.ibizlab.plm.core.prodmgmt.domain.Product_member productbefore_createmembers;
        global cn.ibizlab.plm.core.prodmgmt.service.IProductService iBzSysProductDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "productbefore_createbegin"
            when
            then
            end

            //逻辑处理节点[绑定members]
            rule "bindparam1"
            ruleflow-group "productbefore_createbindparam1"
            when
            then
                        update(productbefore_createdefault);//更新fact中变量值
                        update(productbefore_createmember);//更新fact中变量值
                        update(productbefore_createmembers);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "productbefore_createend1"
            when
            then
                        update(productbefore_createdefault);//更新fact中变量值
                        update(productbefore_createmember);//更新fact中变量值
                        update(productbefore_createmembers);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "productbefore_createloopsubcall1"
            when
            then
                        update(productbefore_createdefault);//更新fact中变量值
                        update(productbefore_createmember);//更新fact中变量值
                        update(productbefore_createmembers);//更新fact中变量值
            end

            //逻辑处理节点[重置id]
            rule "prepareparam1"
            ruleflow-group "productbefore_createprepareparam1"
            when
            then
                                productbefore_createmember.set("id",null);
                        update(productbefore_createdefault);//更新fact中变量值
                        update(productbefore_createmember);//更新fact中变量值
                        update(productbefore_createmembers);//更新fact中变量值
            end