package cn.ibizlab.plm.prodmgmt.logic.productlogic.change_role;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productchange_roledefault;
                global cn.ibizlab.plm.core.base.domain.user productchange_rolefor_temp_obj;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_member productchange_rolemember_obj;
                global cn.ibizlab.plm.core.base.domain.user productchange_roleselectdata;
                    global cn.ibizlab.plm.core.prodmgmt.service.Iproduct_memberService product_memberservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IproductService iBzSysProductDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "productchange_rolebegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "productchange_rolebindparam1"
            when
            then
                        update(productchange_roledefault);//更新fact中变量值
                        update(productchange_rolefor_temp_obj);//更新fact中变量值
                        update(productchange_rolemember_obj);//更新fact中变量值
                        update(productchange_roleselectdata);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "productchange_roleloopsubcall1"
            when
            then
                        update(productchange_roledefault);//更新fact中变量值
                        update(productchange_rolefor_temp_obj);//更新fact中变量值
                        update(productchange_rolemember_obj);//更新fact中变量值
                        update(productchange_roleselectdata);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "productchange_rolerenewparam1"
            when
            then
                        update(productchange_roledefault);//更新fact中变量值
                        update(productchange_rolefor_temp_obj);//更新fact中变量值
                        update(productchange_rolemember_obj);//更新fact中变量值
                        update(productchange_roleselectdata);//更新fact中变量值
            end

            //逻辑处理节点[填充成员信息]
            rule "prepareparam1"
            ruleflow-group "productchange_roleprepareparam1"
            when
            then
                            productchange_rolemember_obj.set("userid",productchange_rolefor_temp_obj.get("id"));
                            productchange_rolemember_obj.set("",productchange_roledefault.get("ownerid"));
                        update(productchange_roledefault);//更新fact中变量值
                        update(productchange_rolefor_temp_obj);//更新fact中变量值
                        update(productchange_rolemember_obj);//更新fact中变量值
                        update(productchange_roleselectdata);//更新fact中变量值
            end

            //逻辑处理节点[更新管理员身份]
            rule "deaction1"
            ruleflow-group "productchange_roledeaction1"
            when
            then
                        product_memberservice.save(productchange_rolemember_obj);
                        update(productchange_roledefault);//更新fact中变量值
                        update(productchange_rolefor_temp_obj);//更新fact中变量值
                        update(productchange_rolemember_obj);//更新fact中变量值
                        update(productchange_roleselectdata);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "productchange_roleend1"
            when
            then
                        update(productchange_roledefault);//更新fact中变量值
                        update(productchange_rolefor_temp_obj);//更新fact中变量值
                        update(productchange_rolemember_obj);//更新fact中变量值
                        update(productchange_roleselectdata);//更新fact中变量值
            end