package cn.ibizlab.plm.prodmgmt.logic.productlogic.get_product_member_one;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productget_product_member_onedefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_member productget_product_member_onefilter;
                global java.util.Map productget_product_member_onefor_obj;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_member productget_product_member_onemembers;
                global java.util.Map productget_product_member_oneuser;
                    global cn.ibizlab.plm.core.prodmgmt.service.Iproduct_memberService product_memberservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IproductService iBzSysProductDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "productget_product_member_onebegin"
            when
            then
            end

            //逻辑处理节点[获取产品id并设置过滤参数]
            rule "prepareparam2"
            ruleflow-group "productget_product_member_oneprepareparam2"
            when
            then
                            productget_product_member_onefilter.set("n_product_id_eq",productget_product_member_onedefault.get("id"));
                                productget_product_member_onefilter.set("n_user_id_eq",curuser.getSessionParams().get("srfpersonid"));
                        update(productget_product_member_onedefault);//更新fact中变量值
                        update(productget_product_member_onefilter);//更新fact中变量值
                        update(productget_product_member_onefor_obj);//更新fact中变量值
                        update(productget_product_member_onemembers);//更新fact中变量值
                        update(productget_product_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[查询当前用户是否为产品成员]
            rule "dedataset3"
            ruleflow-group "productget_product_member_onededataset3"
            when
            then
                        update(productget_product_member_onedefault);//更新fact中变量值
                        update(productget_product_member_onefilter);//更新fact中变量值
                        update(productget_product_member_onefor_obj);//更新fact中变量值
                        update(productget_product_member_onemembers);//更新fact中变量值
                        update(productget_product_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "productget_product_member_oneend2"
            when
            then
                        update(productget_product_member_onedefault);//更新fact中变量值
                        update(productget_product_member_onefilter);//更新fact中变量值
                        update(productget_product_member_onefor_obj);//更新fact中变量值
                        update(productget_product_member_onemembers);//更新fact中变量值
                        update(productget_product_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[只读权限]
            rule "rawsfcode1"
            ruleflow-group "productget_product_member_onerawsfcode1"
            when
            then
                        update(productget_product_member_onedefault);//更新fact中变量值
                        update(productget_product_member_onefilter);//更新fact中变量值
                        update(productget_product_member_onefor_obj);//更新fact中变量值
                        update(productget_product_member_onemembers);//更新fact中变量值
                        update(productget_product_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[非只读权限]
            rule "rawsfcode2"
            ruleflow-group "productget_product_member_onerawsfcode2"
            when
            then
                        update(productget_product_member_onedefault);//更新fact中变量值
                        update(productget_product_member_onefilter);//更新fact中变量值
                        update(productget_product_member_onefor_obj);//更新fact中变量值
                        update(productget_product_member_onemembers);//更新fact中变量值
                        update(productget_product_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end6"
            ruleflow-group "productget_product_member_oneend6"
            when
            then
                        update(productget_product_member_onedefault);//更新fact中变量值
                        update(productget_product_member_onefilter);//更新fact中变量值
                        update(productget_product_member_onefor_obj);//更新fact中变量值
                        update(productget_product_member_onemembers);//更新fact中变量值
                        update(productget_product_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam3"
            ruleflow-group "productget_product_member_oneprepareparam3"
            when
            then
                        update(productget_product_member_onedefault);//更新fact中变量值
                        update(productget_product_member_onefilter);//更新fact中变量值
                        update(productget_product_member_onefor_obj);//更新fact中变量值
                        update(productget_product_member_onemembers);//更新fact中变量值
                        update(productget_product_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[绑定用户数据到for_obj]
            rule "prepareparam5"
            ruleflow-group "productget_product_member_oneprepareparam5"
            when
            then
                            productget_product_member_onefor_obj.set("",productget_product_member_onemembers.get("0"));
                        update(productget_product_member_onedefault);//更新fact中变量值
                        update(productget_product_member_onefilter);//更新fact中变量值
                        update(productget_product_member_onefor_obj);//更新fact中变量值
                        update(productget_product_member_onemembers);//更新fact中变量值
                        update(productget_product_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[判断系统管理员身份]
            rule "rawsfcode3"
            ruleflow-group "productget_product_member_onerawsfcode3"
            when
            then
                        update(productget_product_member_onedefault);//更新fact中变量值
                        update(productget_product_member_onefilter);//更新fact中变量值
                        update(productget_product_member_onefor_obj);//更新fact中变量值
                        update(productget_product_member_onemembers);//更新fact中变量值
                        update(productget_product_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode4"
            ruleflow-group "productget_product_member_onerawsfcode4"
            when
            then
                        update(productget_product_member_onedefault);//更新fact中变量值
                        update(productget_product_member_onefilter);//更新fact中变量值
                        update(productget_product_member_onefor_obj);//更新fact中变量值
                        update(productget_product_member_onemembers);//更新fact中变量值
                        update(productget_product_member_oneuser);//更新fact中变量值
            end