package cn.ibizlab.plm.prodmgmt.logic.productlogic.other_re_space;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.Product productother_re_spacedefault;
                global cn.ibizlab.plm.core.base.domain.Relation productother_re_spacerelationobj;
                global cn.ibizlab.plm.core.base.domain.Relation productother_re_spacerelationobj2;
                    global cn.ibizlab.plm.core.base.service.IRelationService relationservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IProductService iBzSysProductDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "productother_re_spacebegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "productother_re_spacedebugparam1"
            when
            then
                        update(productother_re_spacedefault);//更新fact中变量值
                        update(productother_re_spacerelationobj);//更新fact中变量值
                        update(productother_re_spacerelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "productother_re_spaceprepareparam1"
            when
            then
                            productother_re_spacerelationobj2.set("targetid",productother_re_spacedefault.get("space_id"));
                            productother_re_spacerelationobj2.set("targettype",productother_re_spacedefault.get("target_type"));
                            productother_re_spacerelationobj2.set("principalid",productother_re_spacedefault.get("target_id"));
                            productother_re_spacerelationobj2.set("principaltype",productother_re_spacedefault.get("principal_type"));
                            productother_re_spacerelationobj.set("targetid",productother_re_spacedefault.get("target_id"));
                            productother_re_spacerelationobj.set("targettype",productother_re_spacedefault.get("principal_type"));
                            productother_re_spacerelationobj.set("principalid",productother_re_spacedefault.get("space_id"));
                            productother_re_spacerelationobj.set("principaltype",productother_re_spacedefault.get("target_type"));
                        update(productother_re_spacedefault);//更新fact中变量值
                        update(productother_re_spacerelationobj);//更新fact中变量值
                        update(productother_re_spacerelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[生成正向关联数据]
            rule "deaction1"
            ruleflow-group "productother_re_spacedeaction1"
            when
            then
                        relationservice.create(productother_re_spacerelationobj);
                        update(productother_re_spacedefault);//更新fact中变量值
                        update(productother_re_spacerelationobj);//更新fact中变量值
                        update(productother_re_spacerelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[生成反向关联数据]
            rule "deaction2"
            ruleflow-group "productother_re_spacedeaction2"
            when
            then
                        relationservice.create(productother_re_spacerelationobj2);
                        update(productother_re_spacedefault);//更新fact中变量值
                        update(productother_re_spacerelationobj);//更新fact中变量值
                        update(productother_re_spacerelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[抛出异常]
            rule "throwexception1"
            ruleflow-group "productother_re_spacethrowexception1"
            when
            then
                        update(productother_re_spacedefault);//更新fact中变量值
                        update(productother_re_spacerelationobj);//更新fact中变量值
                        update(productother_re_spacerelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "productother_re_spaceend1"
            when
            then
                        update(productother_re_spacedefault);//更新fact中变量值
                        update(productother_re_spacerelationobj);//更新fact中变量值
                        update(productother_re_spacerelationobj2);//更新fact中变量值
            end