package cn.ibizlab.plm.prodmgmt.logic.productlogic.other_re_product;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productother_re_productdefault;
                global cn.ibizlab.plm.core.base.domain.relation productother_re_productrelationobj;
                global cn.ibizlab.plm.core.base.domain.relation productother_re_productrelationobj2;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IproductService iBzSysProductDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "productother_re_productbegin"
            when
            then
            end

            //逻辑处理节点[填充关联参数]
            rule "prepareparam1"
            ruleflow-group "productother_re_productprepareparam1"
            when
            then
                            productother_re_productrelationobj2.set("targetid",productother_re_productdefault.get("target_id"));
                            productother_re_productrelationobj2.set("targettype",productother_re_productdefault.get("target_type"));
                            productother_re_productrelationobj2.set("principalid",productother_re_productdefault.get("principal_id"));
                            productother_re_productrelationobj2.set("principaltype",productother_re_productdefault.get("principal_type"));
                            productother_re_productrelationobj.set("targetid",productother_re_productdefault.get("principal_id"));
                            productother_re_productrelationobj.set("targettype",productother_re_productdefault.get("principal_type"));
                            productother_re_productrelationobj.set("principalid",productother_re_productdefault.get("target_id"));
                            productother_re_productrelationobj.set("principaltype",productother_re_productdefault.get("target_type"));
                        update(productother_re_productdefault);//更新fact中变量值
                        update(productother_re_productrelationobj);//更新fact中变量值
                        update(productother_re_productrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[生成反向关联数据]
            rule "deaction2"
            ruleflow-group "productother_re_productdeaction2"
            when
            then
                        relationservice.create(productother_re_productrelationobj2);
                        update(productother_re_productdefault);//更新fact中变量值
                        update(productother_re_productrelationobj);//更新fact中变量值
                        update(productother_re_productrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[生成正向关联数据]
            rule "deaction1"
            ruleflow-group "productother_re_productdeaction1"
            when
            then
                        relationservice.create(productother_re_productrelationobj);
                        update(productother_re_productdefault);//更新fact中变量值
                        update(productother_re_productrelationobj);//更新fact中变量值
                        update(productother_re_productrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[抛出异常]
            rule "throwexception1"
            ruleflow-group "productother_re_productthrowexception1"
            when
            then
                        update(productother_re_productdefault);//更新fact中变量值
                        update(productother_re_productrelationobj);//更新fact中变量值
                        update(productother_re_productrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "productother_re_productend1"
            when
            then
                        update(productother_re_productdefault);//更新fact中变量值
                        update(productother_re_productrelationobj);//更新fact中变量值
                        update(productother_re_productrelationobj2);//更新fact中变量值
            end