package cn.ibizlab.plm.prodmgmt.logic.productlogic.product_move;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productproduct_movedefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productproduct_movefor_temp_obj;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productproduct_movesrfactionparam;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productproduct_moveupdate_obj;
                    global cn.ibizlab.plm.core.prodmgmt.service.IproductService productservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IproductService iBzSysProductDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "productproduct_movebegin"
            when
            then
            end

            //逻辑处理节点[绑定项目参数]
            rule "bindparam1"
            ruleflow-group "productproduct_movebindparam1"
            when
            then
                        update(productproduct_movedefault);//更新fact中变量值
                        update(productproduct_movefor_temp_obj);//更新fact中变量值
                        update(productproduct_movesrfactionparam);//更新fact中变量值
                        update(productproduct_moveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "productproduct_moveloopsubcall1"
            when
            then
                        update(productproduct_movedefault);//更新fact中变量值
                        update(productproduct_movefor_temp_obj);//更新fact中变量值
                        update(productproduct_movesrfactionparam);//更新fact中变量值
                        update(productproduct_moveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[准备更新项目数据]
            rule "prepareparam1"
            ruleflow-group "productproduct_moveprepareparam1"
            when
            then
                            productproduct_moveupdate_obj.set("visibility",productproduct_movefor_temp_obj.get("visibility"));
                            productproduct_moveupdate_obj.set("scopeid",productproduct_movefor_temp_obj.get("scopeid"));
                            productproduct_moveupdate_obj.set("scopetype",productproduct_movefor_temp_obj.get("scopetype"));
                            productproduct_moveupdate_obj.set("id",productproduct_movedefault.get("id"));
                        update(productproduct_movedefault);//更新fact中变量值
                        update(productproduct_movefor_temp_obj);//更新fact中变量值
                        update(productproduct_movesrfactionparam);//更新fact中变量值
                        update(productproduct_moveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[移动项目]
            rule "deaction1"
            ruleflow-group "productproduct_movedeaction1"
            when
            then
                        productservice.update(productproduct_moveupdate_obj);
                        update(productproduct_movedefault);//更新fact中变量值
                        update(productproduct_movefor_temp_obj);//更新fact中变量值
                        update(productproduct_movesrfactionparam);//更新fact中变量值
                        update(productproduct_moveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "productproduct_moveend1"
            when
            then
                        update(productproduct_movedefault);//更新fact中变量值
                        update(productproduct_movefor_temp_obj);//更新fact中变量值
                        update(productproduct_movesrfactionparam);//更新fact中变量值
                        update(productproduct_moveupdate_obj);//更新fact中变量值
            end