package cn.ibizlab.plm.prodmgmt.logic.productlogic.quick_create;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productquick_createdefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.product productquick_createproducts;
                    global cn.ibizlab.plm.core.prodmgmt.service.IproductService productservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IproductService iBzSysProductDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "productquick_createbegin"
            when
            then
            end

            //逻辑处理节点[获取主表格查询数据集]
            rule "dedataset2"
            ruleflow-group "productquick_creatededataset2"
            when
            then
                        update(productquick_createdefault);//更新fact中变量值
                        update(productquick_createproducts);//更新fact中变量值
            end

            //逻辑处理节点[获取用户快速新建数据集]
            rule "dedataset4"
            ruleflow-group "productquick_creatededataset4"
            when
            then
                        update(productquick_createdefault);//更新fact中变量值
                        update(productquick_createproducts);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "productquick_createend2"
            when
            then
                        update(productquick_createdefault);//更新fact中变量值
                        update(productquick_createproducts);//更新fact中变量值
            end

            //逻辑处理节点[判断系统管理员身份]
            rule "rawsfcode3"
            ruleflow-group "productquick_createrawsfcode3"
            when
            then
                        update(productquick_createdefault);//更新fact中变量值
                        update(productquick_createproducts);//更新fact中变量值
            end