package cn.ibizlab.plm.prodmgmt.logic.productlogic.test_usercontext_res;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product producttest_usercontext_resdefault;
        global cn.ibizlab.plm.core.prodmgmt.service.IproductService iBzSysProductDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "producttest_usercontext_resbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "producttest_usercontext_resend1"
            when
            then
                        update(producttest_usercontext_resdefault);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode1"
            ruleflow-group "producttest_usercontext_resrawsfcode1"
            when
            then
                        update(producttest_usercontext_resdefault);//更新fact中变量值
            end