package cn.ibizlab.plm.projmgmt.logic.project_memberlogic.change_position;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.project_member project_memberchange_positiondefault;
                global cn.ibizlab.plm.core.projmgmt.domain.project_member project_memberchange_positionfor_temp_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.project_member project_memberchange_positionsrfactionparam;
                    global cn.ibizlab.plm.core.projmgmt.service.Iproject_memberService project_memberservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iproject_memberService iBzSysProject_memberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "project_memberchange_positionbegin"
            when
            then
            end

            //逻辑处理节点[获取传递的参数]
            rule "bindparam1"
            ruleflow-group "project_memberchange_positionbindparam1"
            when
            then
                        update(project_memberchange_positiondefault);//更新fact中变量值
                        update(project_memberchange_positionfor_temp_obj);//更新fact中变量值
                        update(project_memberchange_positionsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[变更状态]
            rule "deaction1"
            ruleflow-group "project_memberchange_positiondeaction1"
            when
            then
                        project_memberservice.update(project_memberchange_positiondefault);
                        update(project_memberchange_positiondefault);//更新fact中变量值
                        update(project_memberchange_positionfor_temp_obj);//更新fact中变量值
                        update(project_memberchange_positionsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环id列表进行操作]
            rule "loopsubcall1"
            ruleflow-group "project_memberchange_positionloopsubcall1"
            when
            then
                        update(project_memberchange_positiondefault);//更新fact中变量值
                        update(project_memberchange_positionfor_temp_obj);//更新fact中变量值
                        update(project_memberchange_positionsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[获取传递的状态]
            rule "prepareparam2"
            ruleflow-group "project_memberchange_positionprepareparam2"
            when
            then
                            project_memberchange_positiondefault.set("title",project_memberchange_positionfor_temp_obj.get("target_title"));
                        update(project_memberchange_positiondefault);//更新fact中变量值
                        update(project_memberchange_positionfor_temp_obj);//更新fact中变量值
                        update(project_memberchange_positionsrfactionparam);//更新fact中变量值
            end