package cn.ibizlab.plm.projmgmt.logic.project_memberlogic.create_project_member;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Project_member project_membercreate_project_memberdefault;
                global cn.ibizlab.plm.core.base.domain.User project_membercreate_project_memberfor_temp_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.Project_member project_membercreate_project_membermember_obj;
                global cn.ibizlab.plm.core.base.domain.User project_membercreate_project_memberselectdata;
                    global cn.ibizlab.plm.core.projmgmt.service.IProject_memberService project_memberservice;
        global cn.ibizlab.plm.core.projmgmt.service.IProject_memberService iBzSysProject_memberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "project_membercreate_project_memberbegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "project_membercreate_project_memberbindparam1"
            when
            then
                        update(project_membercreate_project_memberdefault);//更新fact中变量值
                        update(project_membercreate_project_memberfor_temp_obj);//更新fact中变量值
                        update(project_membercreate_project_membermember_obj);//更新fact中变量值
                        update(project_membercreate_project_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "project_membercreate_project_memberloopsubcall1"
            when
            then
                        update(project_membercreate_project_memberdefault);//更新fact中变量值
                        update(project_membercreate_project_memberfor_temp_obj);//更新fact中变量值
                        update(project_membercreate_project_membermember_obj);//更新fact中变量值
                        update(project_membercreate_project_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "project_membercreate_project_memberrenewparam1"
            when
            then
                        update(project_membercreate_project_memberdefault);//更新fact中变量值
                        update(project_membercreate_project_memberfor_temp_obj);//更新fact中变量值
                        update(project_membercreate_project_membermember_obj);//更新fact中变量值
                        update(project_membercreate_project_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "project_membercreate_project_memberprepareparam1"
            when
            then
                            project_membercreate_project_membermember_obj.set("userid",project_membercreate_project_memberfor_temp_obj.get("id"));
                            project_membercreate_project_membermember_obj.set("name",project_membercreate_project_memberfor_temp_obj.get("displayname"));
                            project_membercreate_project_membermember_obj.set("projectid",project_membercreate_project_memberdefault.get("projectid"));
                        update(project_membercreate_project_memberdefault);//更新fact中变量值
                        update(project_membercreate_project_memberfor_temp_obj);//更新fact中变量值
                        update(project_membercreate_project_membermember_obj);//更新fact中变量值
                        update(project_membercreate_project_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[建立项目成员]
            rule "deaction1"
            ruleflow-group "project_membercreate_project_memberdeaction1"
            when
            then
                        project_memberservice.create(project_membercreate_project_membermember_obj);
                        update(project_membercreate_project_memberdefault);//更新fact中变量值
                        update(project_membercreate_project_memberfor_temp_obj);//更新fact中变量值
                        update(project_membercreate_project_membermember_obj);//更新fact中变量值
                        update(project_membercreate_project_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "project_membercreate_project_memberend1"
            when
            then
                        update(project_membercreate_project_memberdefault);//更新fact中变量值
                        update(project_membercreate_project_memberfor_temp_obj);//更新fact中变量值
                        update(project_membercreate_project_membermember_obj);//更新fact中变量值
                        update(project_membercreate_project_memberselectdata);//更新fact中变量值
            end