package cn.ibizlab.plm.projmgmt.logic.project_memberlogic.notify_by_id;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Project_member project_membernotify_by_iddefault;
                    global cn.ibizlab.plm.core.projmgmt.service.IProject_memberService project_memberservice;
        global cn.ibizlab.plm.core.projmgmt.service.IProject_memberService iBzSysProject_memberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "project_membernotify_by_idbegin"
            when
            then
            end

            //逻辑处理节点[获取数据]
            rule "deaction1"
            ruleflow-group "project_membernotify_by_iddeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(project_memberservice.get(project_membernotify_by_iddefault.getId()),project_membernotify_by_iddefault);
                        update(project_membernotify_by_iddefault);//更新fact中变量值
            end

            //逻辑处理节点[填充当前操作人]
            rule "prepareparam1"
            ruleflow-group "project_membernotify_by_idprepareparam1"
            when
            then
                                project_membernotify_by_iddefault.set("updateman",curuser.getSessionParams().get("srfpersonid"));
                        update(project_membernotify_by_iddefault);//更新fact中变量值
            end

            //逻辑处理节点[填充操作时间]
            rule "rawsfcode1"
            ruleflow-group "project_membernotify_by_idrawsfcode1"
            when
            then
                        update(project_membernotify_by_iddefault);//更新fact中变量值
            end

            //逻辑处理节点[移除成员通知]
            rule "denotify1"
            ruleflow-group "project_membernotify_by_iddenotify1"
            when
            then
                        update(project_membernotify_by_iddefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "project_membernotify_by_idend1"
            when
            then
                        update(project_membernotify_by_iddefault);//更新fact中变量值
            end