package cn.ibizlab.plm.projmgmt.logic.project_memberlogic.remove_project_member_notify;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.project_member project_memberremove_project_member_notifydefault;
                    global cn.ibizlab.plm.core.projmgmt.service.Iproject_memberService project_memberservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iproject_memberService iBzSysProject_memberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "project_memberremove_project_member_notifybegin"
            when
            then
            end

            //逻辑处理节点[获取项目成员数据]
            rule "deaction1"
            ruleflow-group "project_memberremove_project_member_notifydeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(project_memberservice.get(project_memberremove_project_member_notifydefault.getId()),project_memberremove_project_member_notifydefault);
                        update(project_memberremove_project_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[填充当前操作人]
            rule "prepareparam1"
            ruleflow-group "project_memberremove_project_member_notifyprepareparam1"
            when
            then
                                project_memberremove_project_member_notifydefault.set("updateman",curuser.getSessionParams().get("srfpersonid"));
                        update(project_memberremove_project_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[填充操作时间]
            rule "rawsfcode1"
            ruleflow-group "project_memberremove_project_member_notifyrawsfcode1"
            when
            then
                        update(project_memberremove_project_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[移除成员通知]
            rule "denotify1"
            ruleflow-group "project_memberremove_project_member_notifydenotify1"
            when
            then
                        update(project_memberremove_project_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "project_memberremove_project_member_notifyend1"
            when
            then
                        update(project_memberremove_project_member_notifydefault);//更新fact中变量值
            end