package cn.ibizlab.plm.testmgmt.logic.runlogic.this_run_details;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.run runthis_run_detailsdefault;
                    global cn.ibizlab.plm.core.testmgmt.service.IrunService runservice;
        global cn.ibizlab.plm.core.testmgmt.service.IrunService iBzSysRunDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "runthis_run_detailsbegin"
            when
            then
            end

            //逻辑处理节点[获取run信息]
            rule "deaction1"
            ruleflow-group "runthis_run_detailsdeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(runservice.get(runthis_run_detailsdefault.getId()),runthis_run_detailsdefault);
                        update(runthis_run_detailsdefault);//更新fact中变量值
            end

            //逻辑处理节点[获取最近执行的一条数据]
            rule "rawsqlcall1"
            ruleflow-group "runthis_run_detailsrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",runthis_run_detailsdefault.get("caseid"));
    String strSql="-- 最近执行	 SELECT 	t2.NAME AS RECENT_TEST_PLAN, 	t.EXECUTOR_NAME AS RECENT_EXECUTOR_NAME, 	t.EXECUTED_AT AS RECENT_EXECUTED_AT, 	t.`STATUS` AS RECENT_RUN_HISTORY FROM 	run t, 	test_plan t2 WHERE 	t.CASE_ID = #{et.param0} 	AND t.`STATUS` IS NOT NULL  	AND t.PLAN_ID = t2.id  ORDER BY 	EXECUTED_AT DESC  	LIMIT 1";
                        java.util.List<JSONObject> entities=iBzSysRunDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    runthis_run_detailsdefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(runthis_run_detailsdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "runthis_run_detailsend1"
            when
            then
                        update(runthis_run_detailsdefault);//更新fact中变量值
            end