package cn.ibizlab.plm.base.logic.relationlogic.add_dependency;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.relation relationadd_dependencydefault;
                global cn.ibizlab.plm.core.base.domain.relation relationadd_dependencydependency;
                global cn.ibizlab.plm.core.base.domain.relation relationadd_dependencyfor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.relation relationadd_dependencyselectdata;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.base.service.IrelationService iBzSysRelationDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "relationadd_dependencybegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "relationadd_dependencybindparam1"
            when
            then
                        update(relationadd_dependencydefault);//更新fact中变量值
                        update(relationadd_dependencydependency);//更新fact中变量值
                        update(relationadd_dependencyfor_temp_obj);//更新fact中变量值
                        update(relationadd_dependencyselectdata);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "relationadd_dependencyprepareparam1"
            when
            then
                            relationadd_dependencydependency.set("principalid",relationadd_dependencyfor_temp_obj.get("owner_id"));
                            relationadd_dependencydependency.set("principaltype","dependency");
                            relationadd_dependencydependency.set("targetid",relationadd_dependencydefault.get("principalid"));
                            relationadd_dependencydependency.set("relationtype","1");
                        update(relationadd_dependencydefault);//更新fact中变量值
                        update(relationadd_dependencydependency);//更新fact中变量值
                        update(relationadd_dependencyfor_temp_obj);//更新fact中变量值
                        update(relationadd_dependencyselectdata);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "relationadd_dependencyloopsubcall1"
            when
            then
                        update(relationadd_dependencydefault);//更新fact中变量值
                        update(relationadd_dependencydependency);//更新fact中变量值
                        update(relationadd_dependencyfor_temp_obj);//更新fact中变量值
                        update(relationadd_dependencyselectdata);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "relationadd_dependencyrenewparam1"
            when
            then
                        update(relationadd_dependencydefault);//更新fact中变量值
                        update(relationadd_dependencydependency);//更新fact中变量值
                        update(relationadd_dependencyfor_temp_obj);//更新fact中变量值
                        update(relationadd_dependencyselectdata);//更新fact中变量值
            end

            //逻辑处理节点[添加依赖]
            rule "deaction1"
            ruleflow-group "relationadd_dependencydeaction1"
            when
            then
                        relationservice.save(relationadd_dependencydependency);
                        update(relationadd_dependencydefault);//更新fact中变量值
                        update(relationadd_dependencydependency);//更新fact中变量值
                        update(relationadd_dependencyfor_temp_obj);//更新fact中变量值
                        update(relationadd_dependencyselectdata);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "relationadd_dependencyprepareparam2"
            when
            then
                            relationadd_dependencydependency.set("principaltype","dependency");
                            relationadd_dependencydependency.set("relationtype","5");
                            relationadd_dependencydependency.set("targetid",relationadd_dependencyfor_temp_obj.get("owner_id"));
                            relationadd_dependencydependency.set("principalid",relationadd_dependencydefault.get("principalid"));
                        update(relationadd_dependencydefault);//更新fact中变量值
                        update(relationadd_dependencydependency);//更新fact中变量值
                        update(relationadd_dependencyfor_temp_obj);//更新fact中变量值
                        update(relationadd_dependencyselectdata);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "relationadd_dependencyend1"
            when
            then
                        update(relationadd_dependencydefault);//更新fact中变量值
                        update(relationadd_dependencydependency);//更新fact中变量值
                        update(relationadd_dependencyfor_temp_obj);//更新fact中变量值
                        update(relationadd_dependencyselectdata);//更新fact中变量值
            end