package cn.ibizlab.plm.base.logic.relationlogic.program_test_case;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.relation relationprogram_test_casedefault;
                global cn.ibizlab.plm.core.base.domain.relation relationprogram_test_casefor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.relation relationprogram_test_caseforward_relation_obj;
                global cn.ibizlab.plm.core.base.domain.relation relationprogram_test_casereverse_relation_obj;
                global cn.ibizlab.plm.core.base.domain.relation relationprogram_test_caseselectdata;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.base.service.IrelationService iBzSysRelationDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "relationprogram_test_casebegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "relationprogram_test_casedebugparam1"
            when
            then
                        update(relationprogram_test_casedefault);//更新fact中变量值
                        update(relationprogram_test_casefor_temp_obj);//更新fact中变量值
                        update(relationprogram_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationprogram_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationprogram_test_caseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "relationprogram_test_casebindparam1"
            when
            then
                        update(relationprogram_test_casedefault);//更新fact中变量值
                        update(relationprogram_test_casefor_temp_obj);//更新fact中变量值
                        update(relationprogram_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationprogram_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationprogram_test_caseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "relationprogram_test_caseloopsubcall1"
            when
            then
                        update(relationprogram_test_casedefault);//更新fact中变量值
                        update(relationprogram_test_casefor_temp_obj);//更新fact中变量值
                        update(relationprogram_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationprogram_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationprogram_test_caseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "relationprogram_test_caserenewparam1"
            when
            then
                        update(relationprogram_test_casedefault);//更新fact中变量值
                        update(relationprogram_test_casefor_temp_obj);//更新fact中变量值
                        update(relationprogram_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationprogram_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationprogram_test_caseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam2"
            ruleflow-group "relationprogram_test_caserenewparam2"
            when
            then
                        update(relationprogram_test_casedefault);//更新fact中变量值
                        update(relationprogram_test_casefor_temp_obj);//更新fact中变量值
                        update(relationprogram_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationprogram_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationprogram_test_caseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[填充需要的属性值]
            rule "prepareparam1"
            ruleflow-group "relationprogram_test_caseprepareparam1"
            when
            then
                            relationprogram_test_caseforward_relation_obj.set("principalid",relationprogram_test_casedefault.get("principalid"));
                            relationprogram_test_casereverse_relation_obj.set("principalid",relationprogram_test_casefor_temp_obj.get("owner_id"));
                            relationprogram_test_casereverse_relation_obj.set("targetid",relationprogram_test_casedefault.get("principalid"));
                            relationprogram_test_casereverse_relation_obj.set("principaltype",relationprogram_test_casedefault.get("targettype"));
                            relationprogram_test_casereverse_relation_obj.set("targettype",relationprogram_test_casedefault.get("principaltype"));
                            relationprogram_test_caseforward_relation_obj.set("principaltype",relationprogram_test_casedefault.get("principaltype"));
                            relationprogram_test_caseforward_relation_obj.set("targettype",relationprogram_test_casedefault.get("targettype"));
                            relationprogram_test_caseforward_relation_obj.set("targetid",relationprogram_test_casefor_temp_obj.get("owner_id"));
                        update(relationprogram_test_casedefault);//更新fact中变量值
                        update(relationprogram_test_casefor_temp_obj);//更新fact中变量值
                        update(relationprogram_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationprogram_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationprogram_test_caseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "relationprogram_test_caseend1"
            when
            then
                        update(relationprogram_test_casedefault);//更新fact中变量值
                        update(relationprogram_test_casefor_temp_obj);//更新fact中变量值
                        update(relationprogram_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationprogram_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationprogram_test_caseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[生成正向关联数据]
            rule "deaction1"
            ruleflow-group "relationprogram_test_casedeaction1"
            when
            then
                        relationservice.save(relationprogram_test_caseforward_relation_obj);
                        update(relationprogram_test_casedefault);//更新fact中变量值
                        update(relationprogram_test_casefor_temp_obj);//更新fact中变量值
                        update(relationprogram_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationprogram_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationprogram_test_caseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[生成反向关联数据]
            rule "deaction2"
            ruleflow-group "relationprogram_test_casedeaction2"
            when
            then
                        relationservice.save(relationprogram_test_casereverse_relation_obj);
                        update(relationprogram_test_casedefault);//更新fact中变量值
                        update(relationprogram_test_casefor_temp_obj);//更新fact中变量值
                        update(relationprogram_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationprogram_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationprogram_test_caseselectdata);//更新fact中变量值
            end