package cn.ibizlab.plm.base.logic.relationlogic.run_del_relation_bug;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.relation relationrun_del_relation_bugdefault;
                global cn.ibizlab.plm.core.base.domain.relation relationrun_del_relation_bugbug_relation_test_case;
                global cn.ibizlab.plm.core.base.domain.relation relationrun_del_relation_bugfor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.relation relationrun_del_relation_bugforward_relation_obj;
                global cn.ibizlab.plm.core.base.domain.relation relationrun_del_relation_bugrelation_filter;
                global cn.ibizlab.plm.core.base.domain.relation relationrun_del_relation_bugrelation_page;
                global cn.ibizlab.plm.core.base.domain.relation relationrun_del_relation_bugreverse_relation_obj;
                global cn.ibizlab.plm.core.testmgmt.domain.run relationrun_del_relation_bugrun;
                global cn.ibizlab.plm.core.base.domain.relation relationrun_del_relation_bugtest_case_relation_bug;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
                    global cn.ibizlab.plm.core.testmgmt.service.IrunService runservice;
        global cn.ibizlab.plm.core.base.service.IrelationService iBzSysRelationDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "relationrun_del_relation_bugbegin"
            when
            then
            end

            //逻辑处理节点[拼接关联对象的主键]
            rule "rawsfcode1"
            ruleflow-group "relationrun_del_relation_bugrawsfcode1"
            when
            then
                        update(relationrun_del_relation_bugdefault);//更新fact中变量值
                        update(relationrun_del_relation_bugbug_relation_test_case);//更新fact中变量值
                        update(relationrun_del_relation_bugfor_temp_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_filter);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_page);//更新fact中变量值
                        update(relationrun_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrun);//更新fact中变量值
                        update(relationrun_del_relation_bugtest_case_relation_bug);//更新fact中变量值
            end

            //逻辑处理节点[删除正向关联]
            rule "deaction2"
            ruleflow-group "relationrun_del_relation_bugdeaction2"
            when
            then
                        relationservice.remove(relationrun_del_relation_bugforward_relation_obj.getId());
                        update(relationrun_del_relation_bugdefault);//更新fact中变量值
                        update(relationrun_del_relation_bugbug_relation_test_case);//更新fact中变量值
                        update(relationrun_del_relation_bugfor_temp_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_filter);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_page);//更新fact中变量值
                        update(relationrun_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrun);//更新fact中变量值
                        update(relationrun_del_relation_bugtest_case_relation_bug);//更新fact中变量值
            end

            //逻辑处理节点[删除反向关联]
            rule "deaction3"
            ruleflow-group "relationrun_del_relation_bugdeaction3"
            when
            then
                        relationservice.remove(relationrun_del_relation_bugreverse_relation_obj.getId());
                        update(relationrun_del_relation_bugdefault);//更新fact中变量值
                        update(relationrun_del_relation_bugbug_relation_test_case);//更新fact中变量值
                        update(relationrun_del_relation_bugfor_temp_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_filter);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_page);//更新fact中变量值
                        update(relationrun_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrun);//更新fact中变量值
                        update(relationrun_del_relation_bugtest_case_relation_bug);//更新fact中变量值
            end

            //逻辑处理节点[获取执行用例]
            rule "deaction6"
            ruleflow-group "relationrun_del_relation_bugdeaction6"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(runservice.get(relationrun_del_relation_bugrun.getId()),relationrun_del_relation_bugrun);
                        update(relationrun_del_relation_bugdefault);//更新fact中变量值
                        update(relationrun_del_relation_bugbug_relation_test_case);//更新fact中变量值
                        update(relationrun_del_relation_bugfor_temp_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_filter);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_page);//更新fact中变量值
                        update(relationrun_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrun);//更新fact中变量值
                        update(relationrun_del_relation_bugtest_case_relation_bug);//更新fact中变量值
            end

            //逻辑处理节点[对应测试用例关联缺陷]
            rule "dedataset1"
            ruleflow-group "relationrun_del_relation_bugdedataset1"
            when
            then
                        update(relationrun_del_relation_bugdefault);//更新fact中变量值
                        update(relationrun_del_relation_bugbug_relation_test_case);//更新fact中变量值
                        update(relationrun_del_relation_bugfor_temp_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_filter);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_page);//更新fact中变量值
                        update(relationrun_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrun);//更新fact中变量值
                        update(relationrun_del_relation_bugtest_case_relation_bug);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "relationrun_del_relation_bugloopsubcall1"
            when
            then
                        update(relationrun_del_relation_bugdefault);//更新fact中变量值
                        update(relationrun_del_relation_bugbug_relation_test_case);//更新fact中变量值
                        update(relationrun_del_relation_bugfor_temp_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_filter);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_page);//更新fact中变量值
                        update(relationrun_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrun);//更新fact中变量值
                        update(relationrun_del_relation_bugtest_case_relation_bug);//更新fact中变量值
            end

            //逻辑处理节点[填充正反关联对象的主要关联属性]
            rule "prepareparam1"
            ruleflow-group "relationrun_del_relation_bugprepareparam1"
            when
            then
                            relationrun_del_relation_bugforward_relation_obj.set("principalid",relationrun_del_relation_bugdefault.get("principalid"));
                            relationrun_del_relation_bugreverse_relation_obj.set("targetid",relationrun_del_relation_bugdefault.get("principalid"));
                            relationrun_del_relation_bugreverse_relation_obj.set("principalid",relationrun_del_relation_bugdefault.get("targetid"));
                            relationrun_del_relation_bugforward_relation_obj.set("targetid",relationrun_del_relation_bugdefault.get("targetid"));
                        update(relationrun_del_relation_bugdefault);//更新fact中变量值
                        update(relationrun_del_relation_bugbug_relation_test_case);//更新fact中变量值
                        update(relationrun_del_relation_bugfor_temp_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_filter);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_page);//更新fact中变量值
                        update(relationrun_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrun);//更新fact中变量值
                        update(relationrun_del_relation_bugtest_case_relation_bug);//更新fact中变量值
            end

            //逻辑处理节点[准备执行用例参数]
            rule "prepareparam3"
            ruleflow-group "relationrun_del_relation_bugprepareparam3"
            when
            then
                            relationrun_del_relation_bugrun.set("id",relationrun_del_relation_bugdefault.get("principalid"));
                        update(relationrun_del_relation_bugdefault);//更新fact中变量值
                        update(relationrun_del_relation_bugbug_relation_test_case);//更新fact中变量值
                        update(relationrun_del_relation_bugfor_temp_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_filter);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_page);//更新fact中变量值
                        update(relationrun_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrun);//更新fact中变量值
                        update(relationrun_del_relation_bugtest_case_relation_bug);//更新fact中变量值
            end

            //逻辑处理节点[准备关联数据过滤参数]
            rule "prepareparam2"
            ruleflow-group "relationrun_del_relation_bugprepareparam2"
            when
            then
                            relationrun_del_relation_bugrelation_filter.set("n_target_id_eq",relationrun_del_relation_bugdefault.get("targetid"));
                            relationrun_del_relation_bugrelation_filter.set("n_target_type_eq","work_item");
                            relationrun_del_relation_bugrelation_filter.set("n_principal_id_eq",relationrun_del_relation_bugrun.get("caseid"));
                            relationrun_del_relation_bugrelation_filter.set("n_principal_type_eq","test_case");
                        update(relationrun_del_relation_bugdefault);//更新fact中变量值
                        update(relationrun_del_relation_bugbug_relation_test_case);//更新fact中变量值
                        update(relationrun_del_relation_bugfor_temp_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_filter);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_page);//更新fact中变量值
                        update(relationrun_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrun);//更新fact中变量值
                        update(relationrun_del_relation_bugtest_case_relation_bug);//更新fact中变量值
            end

            //逻辑处理节点[填充主键]
            rule "rawsfcode2"
            ruleflow-group "relationrun_del_relation_bugrawsfcode2"
            when
            then
                        update(relationrun_del_relation_bugdefault);//更新fact中变量值
                        update(relationrun_del_relation_bugbug_relation_test_case);//更新fact中变量值
                        update(relationrun_del_relation_bugfor_temp_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_filter);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_page);//更新fact中变量值
                        update(relationrun_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrun);//更新fact中变量值
                        update(relationrun_del_relation_bugtest_case_relation_bug);//更新fact中变量值
            end

            //逻辑处理节点[删除测试用例关联缺陷数据]
            rule "deaction4"
            ruleflow-group "relationrun_del_relation_bugdeaction4"
            when
            then
                        relationservice.remove(relationrun_del_relation_bugtest_case_relation_bug.getId());
                        update(relationrun_del_relation_bugdefault);//更新fact中变量值
                        update(relationrun_del_relation_bugbug_relation_test_case);//更新fact中变量值
                        update(relationrun_del_relation_bugfor_temp_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_filter);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_page);//更新fact中变量值
                        update(relationrun_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrun);//更新fact中变量值
                        update(relationrun_del_relation_bugtest_case_relation_bug);//更新fact中变量值
            end

            //逻辑处理节点[删除缺陷关联测试用例数据]
            rule "deaction5"
            ruleflow-group "relationrun_del_relation_bugdeaction5"
            when
            then
                        relationservice.remove(relationrun_del_relation_bugbug_relation_test_case.getId());
                        update(relationrun_del_relation_bugdefault);//更新fact中变量值
                        update(relationrun_del_relation_bugbug_relation_test_case);//更新fact中变量值
                        update(relationrun_del_relation_bugfor_temp_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_filter);//更新fact中变量值
                        update(relationrun_del_relation_bugrelation_page);//更新fact中变量值
                        update(relationrun_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationrun_del_relation_bugrun);//更新fact中变量值
                        update(relationrun_del_relation_bugtest_case_relation_bug);//更新fact中变量值
            end