package cn.ibizlab.plm.base.logic.relationlogic.test_case_del_relation_bug;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.relation relationtest_case_del_relation_bugdefault;
                global cn.ibizlab.plm.core.base.domain.relation relationtest_case_del_relation_bugbug_relation_run;
                global cn.ibizlab.plm.core.base.domain.relation relationtest_case_del_relation_bugforward_relation_obj;
                global cn.ibizlab.plm.core.base.domain.relation relationtest_case_del_relation_bugrelation_for_temp_obj;
                global cn.ibizlab.plm.core.base.domain.relation relationtest_case_del_relation_bugreverse_relation_obj;
                global cn.ibizlab.plm.core.base.domain.relation relationtest_case_del_relation_bugrun_relation_bug;
                global cn.ibizlab.plm.core.base.domain.relation relationtest_case_del_relation_bugrun_relation_filter;
                global cn.ibizlab.plm.core.base.domain.relation relationtest_case_del_relation_bugrun_relation_page;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.base.service.IrelationService iBzSysRelationDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "relationtest_case_del_relation_bugbegin"
            when
            then
            end

            //逻辑处理节点[填充关联对象的主要关联属性]
            rule "prepareparam1"
            ruleflow-group "relationtest_case_del_relation_bugprepareparam1"
            when
            then
                            relationtest_case_del_relation_bugforward_relation_obj.set("principalid",relationtest_case_del_relation_bugdefault.get("principalid"));
                            relationtest_case_del_relation_bugreverse_relation_obj.set("targetid",relationtest_case_del_relation_bugdefault.get("principalid"));
                            relationtest_case_del_relation_bugreverse_relation_obj.set("principalid",relationtest_case_del_relation_bugdefault.get("targetid"));
                            relationtest_case_del_relation_bugforward_relation_obj.set("targetid",relationtest_case_del_relation_bugdefault.get("targetid"));
                        update(relationtest_case_del_relation_bugdefault);//更新fact中变量值
                        update(relationtest_case_del_relation_bugbug_relation_run);//更新fact中变量值
                        update(relationtest_case_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrelation_for_temp_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_bug);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_filter);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[拼接关联对象的主键]
            rule "rawsfcode1"
            ruleflow-group "relationtest_case_del_relation_bugrawsfcode1"
            when
            then
                        update(relationtest_case_del_relation_bugdefault);//更新fact中变量值
                        update(relationtest_case_del_relation_bugbug_relation_run);//更新fact中变量值
                        update(relationtest_case_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrelation_for_temp_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_bug);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_filter);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[删除测试用例关联缺陷数据]
            rule "deaction2"
            ruleflow-group "relationtest_case_del_relation_bugdeaction2"
            when
            then
                        relationservice.remove(relationtest_case_del_relation_bugforward_relation_obj.getId());
                        update(relationtest_case_del_relation_bugdefault);//更新fact中变量值
                        update(relationtest_case_del_relation_bugbug_relation_run);//更新fact中变量值
                        update(relationtest_case_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrelation_for_temp_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_bug);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_filter);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[删除缺陷关联测试用例数据]
            rule "deaction3"
            ruleflow-group "relationtest_case_del_relation_bugdeaction3"
            when
            then
                        relationservice.remove(relationtest_case_del_relation_bugreverse_relation_obj.getId());
                        update(relationtest_case_del_relation_bugdefault);//更新fact中变量值
                        update(relationtest_case_del_relation_bugbug_relation_run);//更新fact中变量值
                        update(relationtest_case_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrelation_for_temp_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_bug);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_filter);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "relationtest_case_del_relation_bugprepareparam2"
            when
            then
                            relationtest_case_del_relation_bugrun_relation_filter.set("targetid",relationtest_case_del_relation_bugdefault.get("targetid"));
                            relationtest_case_del_relation_bugrun_relation_filter.set("principalid",relationtest_case_del_relation_bugdefault.get("principalid"));
                        update(relationtest_case_del_relation_bugdefault);//更新fact中变量值
                        update(relationtest_case_del_relation_bugbug_relation_run);//更新fact中变量值
                        update(relationtest_case_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrelation_for_temp_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_bug);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_filter);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[查询对应的执行用例存在关联此缺陷]
            rule "dedataset1"
            ruleflow-group "relationtest_case_del_relation_bugdedataset1"
            when
            then
                        update(relationtest_case_del_relation_bugdefault);//更新fact中变量值
                        update(relationtest_case_del_relation_bugbug_relation_run);//更新fact中变量值
                        update(relationtest_case_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrelation_for_temp_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_bug);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_filter);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "relationtest_case_del_relation_bugloopsubcall1"
            when
            then
                        update(relationtest_case_del_relation_bugdefault);//更新fact中变量值
                        update(relationtest_case_del_relation_bugbug_relation_run);//更新fact中变量值
                        update(relationtest_case_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrelation_for_temp_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_bug);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_filter);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[重置执行用例关联缺陷参数]
            rule "resetparam1"
            ruleflow-group "relationtest_case_del_relation_bugresetparam1"
            when
            then
                        update(relationtest_case_del_relation_bugdefault);//更新fact中变量值
                        update(relationtest_case_del_relation_bugbug_relation_run);//更新fact中变量值
                        update(relationtest_case_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrelation_for_temp_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_bug);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_filter);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[重置缺陷关联执行用例参数]
            rule "resetparam2"
            ruleflow-group "relationtest_case_del_relation_bugresetparam2"
            when
            then
                        update(relationtest_case_del_relation_bugdefault);//更新fact中变量值
                        update(relationtest_case_del_relation_bugbug_relation_run);//更新fact中变量值
                        update(relationtest_case_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrelation_for_temp_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_bug);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_filter);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[获取执行用例关联缺陷对象主键]
            rule "rawsfcode2"
            ruleflow-group "relationtest_case_del_relation_bugrawsfcode2"
            when
            then
                        update(relationtest_case_del_relation_bugdefault);//更新fact中变量值
                        update(relationtest_case_del_relation_bugbug_relation_run);//更新fact中变量值
                        update(relationtest_case_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrelation_for_temp_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_bug);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_filter);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[删除执行用例关联缺陷]
            rule "deaction4"
            ruleflow-group "relationtest_case_del_relation_bugdeaction4"
            when
            then
                        relationservice.remove(relationtest_case_del_relation_bugrun_relation_bug.getId());
                        update(relationtest_case_del_relation_bugdefault);//更新fact中变量值
                        update(relationtest_case_del_relation_bugbug_relation_run);//更新fact中变量值
                        update(relationtest_case_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrelation_for_temp_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_bug);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_filter);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[删除缺陷关联执行用例]
            rule "deaction5"
            ruleflow-group "relationtest_case_del_relation_bugdeaction5"
            when
            then
                        relationservice.remove(relationtest_case_del_relation_bugbug_relation_run.getId());
                        update(relationtest_case_del_relation_bugdefault);//更新fact中变量值
                        update(relationtest_case_del_relation_bugbug_relation_run);//更新fact中变量值
                        update(relationtest_case_del_relation_bugforward_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrelation_for_temp_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugreverse_relation_obj);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_bug);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_filter);//更新fact中变量值
                        update(relationtest_case_del_relation_bugrun_relation_page);//更新fact中变量值
            end