package cn.ibizlab.plm.base.logic.relationlogic.work_item_del_relation_test_case;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.relation relationwork_item_del_relation_test_casedefault;
                global cn.ibizlab.plm.core.base.domain.relation relationwork_item_del_relation_test_casebug_relation_run;
                global cn.ibizlab.plm.core.base.domain.relation relationwork_item_del_relation_test_caseforward_relation_obj;
                global cn.ibizlab.plm.core.base.domain.relation relationwork_item_del_relation_test_caserelation_for_temp_obj;
                global cn.ibizlab.plm.core.base.domain.relation relationwork_item_del_relation_test_casereverse_relation_obj;
                global cn.ibizlab.plm.core.base.domain.relation relationwork_item_del_relation_test_caserun_relation_bug;
                global cn.ibizlab.plm.core.base.domain.relation relationwork_item_del_relation_test_caserun_relation_filter;
                global cn.ibizlab.plm.core.base.domain.relation relationwork_item_del_relation_test_caserun_relation_page;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.base.service.IrelationService iBzSysRelationDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "relationwork_item_del_relation_test_casebegin"
            when
            then
            end

            //逻辑处理节点[填充关联对象的主要关联属性]
            rule "prepareparam1"
            ruleflow-group "relationwork_item_del_relation_test_caseprepareparam1"
            when
            then
                            relationwork_item_del_relation_test_caseforward_relation_obj.set("principalid",relationwork_item_del_relation_test_casedefault.get("principalid"));
                            relationwork_item_del_relation_test_casereverse_relation_obj.set("targetid",relationwork_item_del_relation_test_casedefault.get("principalid"));
                            relationwork_item_del_relation_test_casereverse_relation_obj.set("principalid",relationwork_item_del_relation_test_casedefault.get("targetid"));
                            relationwork_item_del_relation_test_caseforward_relation_obj.set("targetid",relationwork_item_del_relation_test_casedefault.get("targetid"));
                        update(relationwork_item_del_relation_test_casedefault);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casebug_relation_run);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserelation_for_temp_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_bug);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_filter);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[拼接关联对象的主键]
            rule "rawsfcode1"
            ruleflow-group "relationwork_item_del_relation_test_caserawsfcode1"
            when
            then
                        update(relationwork_item_del_relation_test_casedefault);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casebug_relation_run);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserelation_for_temp_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_bug);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_filter);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[删除工作项关联测试用例数据]
            rule "deaction2"
            ruleflow-group "relationwork_item_del_relation_test_casedeaction2"
            when
            then
                        relationservice.remove(relationwork_item_del_relation_test_caseforward_relation_obj.getId());
                        update(relationwork_item_del_relation_test_casedefault);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casebug_relation_run);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserelation_for_temp_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_bug);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_filter);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[删除测试用例关联工作项数据]
            rule "deaction3"
            ruleflow-group "relationwork_item_del_relation_test_casedeaction3"
            when
            then
                        relationservice.remove(relationwork_item_del_relation_test_casereverse_relation_obj.getId());
                        update(relationwork_item_del_relation_test_casedefault);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casebug_relation_run);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserelation_for_temp_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_bug);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_filter);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "relationwork_item_del_relation_test_caseprepareparam2"
            when
            then
                            relationwork_item_del_relation_test_caserun_relation_filter.set("targetid",relationwork_item_del_relation_test_casedefault.get("principalid"));
                            relationwork_item_del_relation_test_caserun_relation_filter.set("principalid",relationwork_item_del_relation_test_casedefault.get("targetid"));
                        update(relationwork_item_del_relation_test_casedefault);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casebug_relation_run);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserelation_for_temp_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_bug);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_filter);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[查询对应的执行用例存在关联此缺陷]
            rule "dedataset1"
            ruleflow-group "relationwork_item_del_relation_test_casededataset1"
            when
            then
                        update(relationwork_item_del_relation_test_casedefault);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casebug_relation_run);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserelation_for_temp_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_bug);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_filter);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "relationwork_item_del_relation_test_caseloopsubcall1"
            when
            then
                        update(relationwork_item_del_relation_test_casedefault);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casebug_relation_run);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserelation_for_temp_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_bug);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_filter);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[重置参数]
            rule "resetparam1"
            ruleflow-group "relationwork_item_del_relation_test_caseresetparam1"
            when
            then
                        update(relationwork_item_del_relation_test_casedefault);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casebug_relation_run);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserelation_for_temp_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_bug);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_filter);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[重置参数]
            rule "resetparam2"
            ruleflow-group "relationwork_item_del_relation_test_caseresetparam2"
            when
            then
                        update(relationwork_item_del_relation_test_casedefault);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casebug_relation_run);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserelation_for_temp_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_bug);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_filter);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[获取执行用例关联缺陷对象主键]
            rule "rawsfcode2"
            ruleflow-group "relationwork_item_del_relation_test_caserawsfcode2"
            when
            then
                        update(relationwork_item_del_relation_test_casedefault);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casebug_relation_run);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserelation_for_temp_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_bug);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_filter);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[删除执行用例关联缺陷]
            rule "deaction4"
            ruleflow-group "relationwork_item_del_relation_test_casedeaction4"
            when
            then
                        relationservice.remove(relationwork_item_del_relation_test_caserun_relation_bug.getId());
                        update(relationwork_item_del_relation_test_casedefault);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casebug_relation_run);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserelation_for_temp_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_bug);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_filter);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_page);//更新fact中变量值
            end

            //逻辑处理节点[删除缺陷关联执行用例]
            rule "deaction5"
            ruleflow-group "relationwork_item_del_relation_test_casedeaction5"
            when
            then
                        relationservice.remove(relationwork_item_del_relation_test_casebug_relation_run.getId());
                        update(relationwork_item_del_relation_test_casedefault);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casebug_relation_run);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caseforward_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserelation_for_temp_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_casereverse_relation_obj);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_bug);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_filter);//更新fact中变量值
                        update(relationwork_item_del_relation_test_caserun_relation_page);//更新fact中变量值
            end