package cn.ibizlab.plm.prodmgmt.logic.product_planlogic.delete;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_plan product_plandeletedefault;
                    global cn.ibizlab.plm.core.prodmgmt.service.Iproduct_planService product_planservice;
        global cn.ibizlab.plm.core.prodmgmt.service.Iproduct_planService iBzSysProduct_planDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "product_plandeletebegin"
            when
            then
            end

            //逻辑处理节点[设置已删除状态]
            rule "prepareparam1"
            ruleflow-group "product_plandeleteprepareparam1"
            when
            then
                            product_plandeletedefault.set("isdeleted","1");
                        update(product_plandeletedefault);//更新fact中变量值
            end

            //逻辑处理节点[更新产品排期]
            rule "deaction1"
            ruleflow-group "product_plandeletedeaction1"
            when
            then
                        product_planservice.update(product_plandeletedefault);
                        update(product_plandeletedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "product_plandeleteend1"
            when
            then
                        update(product_plandeletedefault);//更新fact中变量值
            end