package cn.ibizlab.plm.prodmgmt.logic.product_planlogic.fill_categories_name;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_plan product_planfill_categories_namedefault;
        global cn.ibizlab.plm.core.prodmgmt.service.Iproduct_planService iBzSysProduct_planDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "product_planfill_categories_namebegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "product_planfill_categories_nameend1"
            when
            then
                        update(product_planfill_categories_namedefault);//更新fact中变量值
            end

            //逻辑处理节点[类别转换]
            rule "prepareparam1"
            ruleflow-group "product_planfill_categories_nameprepareparam1"
            when
            then
                            product_planfill_categories_namedefault.set("categoriesname",product_planfill_categories_namedefault.get("categories"));
                        update(product_planfill_categories_namedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "product_planfill_categories_nameend2"
            when
            then
                        update(product_planfill_categories_namedefault);//更新fact中变量值
            end