package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.aggregate_actual_workload;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemaggregate_actual_workloaddefault;
                global java.util.Map work_itemaggregate_actual_workloadactual_workload;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemaggregate_actual_workloadcur_child_work_item_filter;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemaggregate_actual_workloadcur_child_work_item_page;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemaggregate_actual_workloadcur_work_item_temp;
                global java.util.Map work_itemaggregate_actual_workloadestimated_workload;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemaggregate_actual_workloadp_work_item;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemaggregate_actual_workloadp_work_item_filter;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemaggregate_actual_workloadp_work_item_page;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemaggregate_actual_workloadworkload_data;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemaggregate_actual_workloadbegin"
            when
            then
            end

            //逻辑处理节点[本次更新数据111]
            rule "debugparam5"
            ruleflow-group "work_itemaggregate_actual_workloaddebugparam5"
            when
            then
                        update(work_itemaggregate_actual_workloaddefault);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadactual_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_work_item_temp);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadestimated_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadworkload_data);//更新fact中变量值
            end

            //逻辑处理节点[设置父工作项过滤条件]
            rule "prepareparam1"
            ruleflow-group "work_itemaggregate_actual_workloadprepareparam1"
            when
            then
                            work_itemaggregate_actual_workloadp_work_item_filter.set("n_id_eq",work_itemaggregate_actual_workloaddefault.get("pid"));
                        update(work_itemaggregate_actual_workloaddefault);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadactual_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_work_item_temp);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadestimated_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadworkload_data);//更新fact中变量值
            end

            //逻辑处理节点[获取父工作项]
            rule "dedataset1"
            ruleflow-group "work_itemaggregate_actual_workloaddedataset1"
            when
            then
                        update(work_itemaggregate_actual_workloaddefault);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadactual_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_work_item_temp);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadestimated_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadworkload_data);//更新fact中变量值
            end

            //逻辑处理节点[设置父工作项]
            rule "prepareparam2"
            ruleflow-group "work_itemaggregate_actual_workloadprepareparam2"
            when
            then
                            work_itemaggregate_actual_workloadp_work_item.set("",work_itemaggregate_actual_workloadp_work_item_page.get("0"));
                        update(work_itemaggregate_actual_workloaddefault);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadactual_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_work_item_temp);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadestimated_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadworkload_data);//更新fact中变量值
            end

            //逻辑处理节点[设置当前同级工作项过滤条件]
            rule "prepareparam3"
            ruleflow-group "work_itemaggregate_actual_workloadprepareparam3"
            when
            then
                            work_itemaggregate_actual_workloadcur_child_work_item_filter.set("n_pid_eq",work_itemaggregate_actual_workloadp_work_item.get("id"));
                        update(work_itemaggregate_actual_workloaddefault);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadactual_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_work_item_temp);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadestimated_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadworkload_data);//更新fact中变量值
            end

            //逻辑处理节点[获取同级数据]
            rule "dedataset2"
            ruleflow-group "work_itemaggregate_actual_workloaddedataset2"
            when
            then
                        update(work_itemaggregate_actual_workloaddefault);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadactual_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_work_item_temp);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadestimated_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadworkload_data);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemaggregate_actual_workloadloopsubcall1"
            when
            then
                        update(work_itemaggregate_actual_workloaddefault);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadactual_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_work_item_temp);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadestimated_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadworkload_data);//更新fact中变量值
            end

            //逻辑处理节点[待更新父工作项]
            rule "debugparam3"
            ruleflow-group "work_itemaggregate_actual_workloaddebugparam3"
            when
            then
                        update(work_itemaggregate_actual_workloaddefault);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadactual_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_work_item_temp);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadestimated_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadworkload_data);//更新fact中变量值
            end

            //逻辑处理节点[更新父工作项]
            rule "deaction1"
            ruleflow-group "work_itemaggregate_actual_workloaddeaction1"
            when
            then
                        work_itemservice.update(work_itemaggregate_actual_workloadp_work_item);
                        update(work_itemaggregate_actual_workloaddefault);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadactual_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_work_item_temp);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadestimated_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadworkload_data);//更新fact中变量值
            end

            //逻辑处理节点[调试当前级子数据]
            rule "debugparam4"
            ruleflow-group "work_itemaggregate_actual_workloaddebugparam4"
            when
            then
                        update(work_itemaggregate_actual_workloaddefault);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadactual_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_work_item_temp);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadestimated_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadworkload_data);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam4"
            ruleflow-group "work_itemaggregate_actual_workloadprepareparam4"
            when
            then
                            work_itemaggregate_actual_workloadp_work_item.set("actualworkload",work_itemaggregate_actual_workloadworkload_data.get("actualworkload"));
                            work_itemaggregate_actual_workloadp_work_item.set("estimatedworkload",work_itemaggregate_actual_workloadworkload_data.get("estimatedworkload"));
                        update(work_itemaggregate_actual_workloaddefault);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadactual_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_work_item_temp);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadestimated_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadworkload_data);//更新fact中变量值
            end

            //逻辑处理节点[获取当前级的工时，赋值给父]
            rule "rawsfcode1"
            ruleflow-group "work_itemaggregate_actual_workloadrawsfcode1"
            when
            then
                        update(work_itemaggregate_actual_workloaddefault);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadactual_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_work_item_temp);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadestimated_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadworkload_data);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemaggregate_actual_workloadend1"
            when
            then
                        update(work_itemaggregate_actual_workloaddefault);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadactual_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_work_item_temp);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadestimated_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadworkload_data);//更新fact中变量值
            end

            //逻辑处理节点[调试工时数据]
            rule "debugparam2"
            ruleflow-group "work_itemaggregate_actual_workloaddebugparam2"
            when
            then
                        update(work_itemaggregate_actual_workloaddefault);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadactual_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_child_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadcur_work_item_temp);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadestimated_workload);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_filter);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadp_work_item_page);//更新fact中变量值
                        update(work_itemaggregate_actual_workloadworkload_data);//更新fact中变量值
            end