package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.fill_idea_form;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemfill_idea_formdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemfill_idea_formdraft_data;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemfill_idea_formfill_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.project work_itemfill_idea_formproject_data;
                global cn.ibizlab.plm.core.base.domain.recent work_itemfill_idea_formrecent_filter;
                global cn.ibizlab.plm.core.base.domain.recent work_itemfill_idea_formrecent_obj;
                global cn.ibizlab.plm.core.base.domain.recent work_itemfill_idea_formrecent_page;
                    global cn.ibizlab.plm.core.prodmgmt.service.IideaService ideaservice;
                    global cn.ibizlab.plm.core.base.service.IrecentService recentservice;
                    global cn.ibizlab.plm.core.projmgmt.service.IprojectService projectservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemfill_idea_formbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemfill_idea_formend1"
            when
            then
                        update(work_itemfill_idea_formdefault);//更新fact中变量值
                        update(work_itemfill_idea_formdraft_data);//更新fact中变量值
                        update(work_itemfill_idea_formfill_obj);//更新fact中变量值
                        update(work_itemfill_idea_formproject_data);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_filter);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_obj);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_page);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam9"
            ruleflow-group "work_itemfill_idea_formprepareparam9"
            when
            then
                        update(work_itemfill_idea_formdefault);//更新fact中变量值
                        update(work_itemfill_idea_formdraft_data);//更新fact中变量值
                        update(work_itemfill_idea_formfill_obj);//更新fact中变量值
                        update(work_itemfill_idea_formproject_data);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_filter);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_obj);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_page);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "work_itemfill_idea_formprepareparam1"
            when
            then
                            work_itemfill_idea_formfill_obj.set("id",work_itemfill_idea_formdefault.get("fill_id"));
                        update(work_itemfill_idea_formdefault);//更新fact中变量值
                        update(work_itemfill_idea_formdraft_data);//更新fact中变量值
                        update(work_itemfill_idea_formfill_obj);//更新fact中变量值
                        update(work_itemfill_idea_formproject_data);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_filter);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_obj);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_page);//更新fact中变量值
            end

            //逻辑处理节点[获取需求详情]
            rule "deaction1"
            ruleflow-group "work_itemfill_idea_formdeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(ideaservice.get(work_itemfill_idea_formfill_obj.getId()),work_itemfill_idea_formfill_obj);
                        update(work_itemfill_idea_formdefault);//更新fact中变量值
                        update(work_itemfill_idea_formdraft_data);//更新fact中变量值
                        update(work_itemfill_idea_formfill_obj);//更新fact中变量值
                        update(work_itemfill_idea_formproject_data);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_filter);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_obj);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_page);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "work_itemfill_idea_formprepareparam2"
            when
            then
                            work_itemfill_idea_formdefault.set("title",work_itemfill_idea_formfill_obj.get("title"));
                            work_itemfill_idea_formdefault.set("description",work_itemfill_idea_formfill_obj.get("description"));
                        update(work_itemfill_idea_formdefault);//更新fact中变量值
                        update(work_itemfill_idea_formdraft_data);//更新fact中变量值
                        update(work_itemfill_idea_formfill_obj);//更新fact中变量值
                        update(work_itemfill_idea_formproject_data);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_filter);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_obj);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_page);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam11"
            ruleflow-group "work_itemfill_idea_formprepareparam11"
            when
            then
                        update(work_itemfill_idea_formdefault);//更新fact中变量值
                        update(work_itemfill_idea_formdraft_data);//更新fact中变量值
                        update(work_itemfill_idea_formfill_obj);//更新fact中变量值
                        update(work_itemfill_idea_formproject_data);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_filter);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_obj);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_page);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam3"
            ruleflow-group "work_itemfill_idea_formprepareparam3"
            when
            then
                            work_itemfill_idea_formrecent_filter.set("size","1");
                            work_itemfill_idea_formrecent_filter.set("n_type_eq","1");
                        update(work_itemfill_idea_formdefault);//更新fact中变量值
                        update(work_itemfill_idea_formdraft_data);//更新fact中变量值
                        update(work_itemfill_idea_formfill_obj);//更新fact中变量值
                        update(work_itemfill_idea_formproject_data);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_filter);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_obj);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_page);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "work_itemfill_idea_formdedataset1"
            when
            then
                        update(work_itemfill_idea_formdefault);//更新fact中变量值
                        update(work_itemfill_idea_formdraft_data);//更新fact中变量值
                        update(work_itemfill_idea_formfill_obj);//更新fact中变量值
                        update(work_itemfill_idea_formproject_data);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_filter);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_obj);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_page);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam4"
            ruleflow-group "work_itemfill_idea_formprepareparam4"
            when
            then
                            work_itemfill_idea_formrecent_obj.set("",work_itemfill_idea_formrecent_page.get("0"));
                            work_itemfill_idea_formdefault.set("projectname",work_itemfill_idea_formrecent_obj.get("recentparentname"));
                            work_itemfill_idea_formdefault.set("projectid",work_itemfill_idea_formrecent_obj.get("ownerid"));
                        update(work_itemfill_idea_formdefault);//更新fact中变量值
                        update(work_itemfill_idea_formdraft_data);//更新fact中变量值
                        update(work_itemfill_idea_formfill_obj);//更新fact中变量值
                        update(work_itemfill_idea_formproject_data);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_filter);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_obj);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_page);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam10"
            ruleflow-group "work_itemfill_idea_formprepareparam10"
            when
            then
                            work_itemfill_idea_formproject_data.set("id",work_itemfill_idea_formrecent_obj.get("ownerid"));
                        update(work_itemfill_idea_formdefault);//更新fact中变量值
                        update(work_itemfill_idea_formdraft_data);//更新fact中变量值
                        update(work_itemfill_idea_formfill_obj);//更新fact中变量值
                        update(work_itemfill_idea_formproject_data);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_filter);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_obj);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_page);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction2"
            ruleflow-group "work_itemfill_idea_formdeaction2"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(projectservice.get(work_itemfill_idea_formproject_data.getId()),work_itemfill_idea_formproject_data);
                        update(work_itemfill_idea_formdefault);//更新fact中变量值
                        update(work_itemfill_idea_formdraft_data);//更新fact中变量值
                        update(work_itemfill_idea_formfill_obj);//更新fact中变量值
                        update(work_itemfill_idea_formproject_data);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_filter);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_obj);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_page);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam5"
            ruleflow-group "work_itemfill_idea_formprepareparam5"
            when
            then
                            work_itemfill_idea_formdefault.set("workitemtypeid","scrum_epic");
                            work_itemfill_idea_formdefault.set("projectname",work_itemfill_idea_formproject_data.get("name"));
                            work_itemfill_idea_formdefault.set("workitemtypename","史诗");
                        update(work_itemfill_idea_formdefault);//更新fact中变量值
                        update(work_itemfill_idea_formdraft_data);//更新fact中变量值
                        update(work_itemfill_idea_formfill_obj);//更新fact中变量值
                        update(work_itemfill_idea_formproject_data);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_filter);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_obj);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_page);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam6"
            ruleflow-group "work_itemfill_idea_formprepareparam6"
            when
            then
                            work_itemfill_idea_formdefault.set("workitemtypeid","kanban_epic");
                            work_itemfill_idea_formdefault.set("projectname",work_itemfill_idea_formproject_data.get("name"));
                            work_itemfill_idea_formdefault.set("workitemtypename","史诗");
                        update(work_itemfill_idea_formdefault);//更新fact中变量值
                        update(work_itemfill_idea_formdraft_data);//更新fact中变量值
                        update(work_itemfill_idea_formfill_obj);//更新fact中变量值
                        update(work_itemfill_idea_formproject_data);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_filter);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_obj);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_page);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam7"
            ruleflow-group "work_itemfill_idea_formprepareparam7"
            when
            then
                            work_itemfill_idea_formdefault.set("workitemtypeid","waterfall_stage");
                            work_itemfill_idea_formdefault.set("projectname",work_itemfill_idea_formproject_data.get("name"));
                            work_itemfill_idea_formdefault.set("workitemtypename","阶段");
                        update(work_itemfill_idea_formdefault);//更新fact中变量值
                        update(work_itemfill_idea_formdraft_data);//更新fact中变量值
                        update(work_itemfill_idea_formfill_obj);//更新fact中变量值
                        update(work_itemfill_idea_formproject_data);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_filter);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_obj);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_page);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam8"
            ruleflow-group "work_itemfill_idea_formprepareparam8"
            when
            then
                            work_itemfill_idea_formdefault.set("workitemtypeid","hybrid_epic");
                            work_itemfill_idea_formdefault.set("projectname",work_itemfill_idea_formproject_data.get("name"));
                            work_itemfill_idea_formdefault.set("workitemtypename","史诗");
                        update(work_itemfill_idea_formdefault);//更新fact中变量值
                        update(work_itemfill_idea_formdraft_data);//更新fact中变量值
                        update(work_itemfill_idea_formfill_obj);//更新fact中变量值
                        update(work_itemfill_idea_formproject_data);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_filter);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_obj);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "work_itemfill_idea_formend2"
            when
            then
                        update(work_itemfill_idea_formdefault);//更新fact中变量值
                        update(work_itemfill_idea_formdraft_data);//更新fact中变量值
                        update(work_itemfill_idea_formfill_obj);//更新fact中变量值
                        update(work_itemfill_idea_formproject_data);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_filter);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_obj);//更新fact中变量值
                        update(work_itemfill_idea_formrecent_page);//更新fact中变量值
            end