package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.fill_not_completed_num;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemfill_not_completed_numdefault;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemfill_not_completed_numbegin"
            when
            then
            end

            //逻辑处理节点[获取待完成事项数量]
            rule "rawsqlcall1"
            ruleflow-group "work_itemfill_not_completed_numrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",curuser.getSessionParams().get("srfpersonid"));
    String strSql="SELECT count(1) as `not_completed_num` FROM `WORK_ITEM` t1  LEFT JOIN `WORK_ITEM_STATE` t31 ON t1.`STATE` = t31.`ID`  WHERE  ( t1.`ASSIGNEE_ID` = #{et.param0}  AND  t1.`IS_ARCHIVED` = 0  AND  t1.`IS_DELETED` = 0  AND  t31.`TYPE` <> 'completed' )";
                        java.util.List<JSONObject> entities=iBzSysWork_itemDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    work_itemfill_not_completed_numdefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(work_itemfill_not_completed_numdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemfill_not_completed_numend1"
            when
            then
                        update(work_itemfill_not_completed_numdefault);//更新fact中变量值
            end