package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.fill_actual_time;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemfill_actual_timedefault;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemfill_actual_timework_item_obj;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemfill_actual_timebegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemfill_actual_timeend1"
            when
            then
                        update(work_itemfill_actual_timedefault);//更新fact中变量值
                        update(work_itemfill_actual_timework_item_obj);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "work_itemfill_actual_timedebugparam1"
            when
            then
                        update(work_itemfill_actual_timedefault);//更新fact中变量值
                        update(work_itemfill_actual_timework_item_obj);//更新fact中变量值
            end

            //逻辑处理节点[填充开始或结束时间]
            rule "rawsfcode1"
            ruleflow-group "work_itemfill_actual_timerawsfcode1"
            when
            then
                        update(work_itemfill_actual_timedefault);//更新fact中变量值
                        update(work_itemfill_actual_timework_item_obj);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "work_itemfill_actual_timedeaction1"
            when
            then
                        work_itemservice.save(work_itemfill_actual_timework_item_obj);
                        update(work_itemfill_actual_timedefault);//更新fact中变量值
                        update(work_itemfill_actual_timework_item_obj);//更新fact中变量值
            end