package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.fix_commit;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemfix_commitdefault;
                global cn.ibizlab.plm.core.base.domain.version work_itemfix_commitversion;
                    global cn.ibizlab.plm.core.base.service.IversionService versionservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemfix_commitbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemfix_commitend1"
            when
            then
                        update(work_itemfix_commitdefault);//更新fact中变量值
                        update(work_itemfix_commitversion);//更新fact中变量值
            end

            //逻辑处理节点[准备版本数据]
            rule "prepareparam1"
            ruleflow-group "work_itemfix_commitprepareparam1"
            when
            then
                            work_itemfix_commitversion.set("ownerid",work_itemfix_commitdefault.get("id"));
                            work_itemfix_commitversion.set("ownertype","WORK_ITEM");
                        update(work_itemfix_commitdefault);//更新fact中变量值
                        update(work_itemfix_commitversion);//更新fact中变量值
            end

            //逻辑处理节点[修复版本]
            rule "deaction1"
            ruleflow-group "work_itemfix_commitdeaction1"
            when
            then
                        versionservice.fix_commit(work_itemfix_commitversion);
                        update(work_itemfix_commitdefault);//更新fact中变量值
                        update(work_itemfix_commitversion);//更新fact中变量值
            end