package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.get_work_item_type;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemget_work_item_typedefault;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemget_work_item_typebegin"
            when
            then
            end

            //逻辑处理节点[查询工作项类型]
            rule "rawsqlcall1"
            ruleflow-group "work_itemget_work_item_typerawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",work_itemget_work_item_typedefault.get("id"));
    String strSql="select work_item_type_id from work_item where id = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysWork_itemDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    work_itemget_work_item_typedefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(work_itemget_work_item_typedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemget_work_item_typeend1"
            when
            then
                        update(work_itemget_work_item_typedefault);//更新fact中变量值
            end