package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.get_baseline_name;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemget_baseline_namedefault;
                global cn.ibizlab.plm.core.base.domain.baseline work_itemget_baseline_namebaseline;
                global cn.ibizlab.plm.core.base.domain.relation work_itemget_baseline_namerelation;
                global cn.ibizlab.plm.core.base.domain.relation work_itemget_baseline_namerelation_filter;
                global cn.ibizlab.plm.core.base.domain.relation work_itemget_baseline_namerelation_page;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
                    global cn.ibizlab.plm.core.base.service.IbaselineService baselineservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemget_baseline_namebegin"
            when
            then
            end

            //逻辑处理节点[准备关联过滤器参数]
            rule "prepareparam1"
            ruleflow-group "work_itemget_baseline_nameprepareparam1"
            when
            then
                            work_itemget_baseline_namerelation_filter.set("n_target_type_eq","work_item");
                            work_itemget_baseline_namerelation_filter.set("n_principal_type_eq","baseline");
                            work_itemget_baseline_namerelation_filter.set("n_target_id_eq",work_itemget_baseline_namedefault.get("id"));
                            work_itemget_baseline_namerelation_filter.set("sort","create_time,desc");
                            work_itemget_baseline_namerelation_filter.set("n_target_version_id_eq",work_itemget_baseline_namedefault.get("curversionid"));
                        update(work_itemget_baseline_namedefault);//更新fact中变量值
                        update(work_itemget_baseline_namebaseline);//更新fact中变量值
                        update(work_itemget_baseline_namerelation);//更新fact中变量值
                        update(work_itemget_baseline_namerelation_filter);//更新fact中变量值
                        update(work_itemget_baseline_namerelation_page);//更新fact中变量值
            end

            //逻辑处理节点[获取此工作项引入的基线]
            rule "dedataset1"
            ruleflow-group "work_itemget_baseline_namededataset1"
            when
            then
                        update(work_itemget_baseline_namedefault);//更新fact中变量值
                        update(work_itemget_baseline_namebaseline);//更新fact中变量值
                        update(work_itemget_baseline_namerelation);//更新fact中变量值
                        update(work_itemget_baseline_namerelation_filter);//更新fact中变量值
                        update(work_itemget_baseline_namerelation_page);//更新fact中变量值
            end

            //逻辑处理节点[绑定最近移入的基线]
            rule "bindparam1"
            ruleflow-group "work_itemget_baseline_namebindparam1"
            when
            then
                        update(work_itemget_baseline_namedefault);//更新fact中变量值
                        update(work_itemget_baseline_namebaseline);//更新fact中变量值
                        update(work_itemget_baseline_namerelation);//更新fact中变量值
                        update(work_itemget_baseline_namerelation_filter);//更新fact中变量值
                        update(work_itemget_baseline_namerelation_page);//更新fact中变量值
            end

            //逻辑处理节点[填充基线标识]
            rule "prepareparam2"
            ruleflow-group "work_itemget_baseline_nameprepareparam2"
            when
            then
                            work_itemget_baseline_namebaseline.set("id",work_itemget_baseline_namerelation.get("principalid"));
                        update(work_itemget_baseline_namedefault);//更新fact中变量值
                        update(work_itemget_baseline_namebaseline);//更新fact中变量值
                        update(work_itemget_baseline_namerelation);//更新fact中变量值
                        update(work_itemget_baseline_namerelation_filter);//更新fact中变量值
                        update(work_itemget_baseline_namerelation_page);//更新fact中变量值
            end

            //逻辑处理节点[获取基线]
            rule "deaction2"
            ruleflow-group "work_itemget_baseline_namedeaction2"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(baselineservice.get(work_itemget_baseline_namebaseline.getId()),work_itemget_baseline_namebaseline);
                        update(work_itemget_baseline_namedefault);//更新fact中变量值
                        update(work_itemget_baseline_namebaseline);//更新fact中变量值
                        update(work_itemget_baseline_namerelation);//更新fact中变量值
                        update(work_itemget_baseline_namerelation_filter);//更新fact中变量值
                        update(work_itemget_baseline_namerelation_page);//更新fact中变量值
            end

            //逻辑处理节点[将基线名称填充至工作项对象中]
            rule "prepareparam3"
            ruleflow-group "work_itemget_baseline_nameprepareparam3"
            when
            then
                            work_itemget_baseline_namedefault.set("baseline_name",work_itemget_baseline_namebaseline.get("name"));
                        update(work_itemget_baseline_namedefault);//更新fact中变量值
                        update(work_itemget_baseline_namebaseline);//更新fact中变量值
                        update(work_itemget_baseline_namerelation);//更新fact中变量值
                        update(work_itemget_baseline_namerelation_filter);//更新fact中变量值
                        update(work_itemget_baseline_namerelation_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemget_baseline_nameend1"
            when
            then
                        update(work_itemget_baseline_namedefault);//更新fact中变量值
                        update(work_itemget_baseline_namebaseline);//更新fact中变量值
                        update(work_itemget_baseline_namerelation);//更新fact中变量值
                        update(work_itemget_baseline_namerelation_filter);//更新fact中变量值
                        update(work_itemget_baseline_namerelation_page);//更新fact中变量值
            end