package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.project_resource_setting;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemproject_resource_settingdefault;
                global cn.ibizlab.plm.core.base.domain.addon_resource work_itemproject_resource_settingaddon_resource;
                global cn.ibizlab.plm.core.base.domain.addon_resource work_itemproject_resource_settingaddon_resource_filter;
                global cn.ibizlab.plm.core.base.domain.addon_resource work_itemproject_resource_settingaddon_resource_page;
                global cn.ibizlab.plm.core.projmgmt.domain.day_capacity work_itemproject_resource_settingday_capacity;
                global cn.ibizlab.plm.core.base.domain.member work_itemproject_resource_settingfor_choose_obj;
                global cn.ibizlab.plm.core.base.domain.member work_itemproject_resource_settingfor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.resource_member work_itemproject_resource_settinginsert_members;
                global cn.ibizlab.plm.core.base.domain.resource_member work_itemproject_resource_settingresource_member;
                global cn.ibizlab.plm.core.base.domain.resource_member work_itemproject_resource_settingresource_members;
                global cn.ibizlab.plm.core.base.domain.member work_itemproject_resource_settingsrfactionparam;
                    global cn.ibizlab.plm.core.base.service.Iaddon_resourceService addon_resourceservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemproject_resource_settingbegin"
            when
            then
            end

            //逻辑处理节点[绑定选择成员列表]
            rule "bindparam1"
            ruleflow-group "work_itemproject_resource_settingbindparam1"
            when
            then
                        update(work_itemproject_resource_settingdefault);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_filter);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_page);//更新fact中变量值
                        update(work_itemproject_resource_settingday_capacity);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_choose_obj);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_temp_obj);//更新fact中变量值
                        update(work_itemproject_resource_settinginsert_members);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_member);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_members);//更新fact中变量值
                        update(work_itemproject_resource_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[准备资源组件过滤器参数]
            rule "prepareparam3"
            ruleflow-group "work_itemproject_resource_settingprepareparam3"
            when
            then
                            work_itemproject_resource_settingaddon_resource_filter.set("n_owner_id_eq",work_itemproject_resource_settingdefault.get("projectid"));
                            work_itemproject_resource_settingaddon_resource_filter.set("n_owner_type_eq","project");
                            work_itemproject_resource_settingaddon_resource_filter.set("n_addon_type_eq","resource");
                        update(work_itemproject_resource_settingdefault);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_filter);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_page);//更新fact中变量值
                        update(work_itemproject_resource_settingday_capacity);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_choose_obj);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_temp_obj);//更新fact中变量值
                        update(work_itemproject_resource_settinginsert_members);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_member);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_members);//更新fact中变量值
                        update(work_itemproject_resource_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[获取当前项目下的资源组件]
            rule "dedataset1"
            ruleflow-group "work_itemproject_resource_settingdedataset1"
            when
            then
                        update(work_itemproject_resource_settingdefault);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_filter);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_page);//更新fact中变量值
                        update(work_itemproject_resource_settingday_capacity);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_choose_obj);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_temp_obj);//更新fact中变量值
                        update(work_itemproject_resource_settinginsert_members);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_member);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_members);//更新fact中变量值
                        update(work_itemproject_resource_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[绑定资源组件]
            rule "bindparam3"
            ruleflow-group "work_itemproject_resource_settingbindparam3"
            when
            then
                        update(work_itemproject_resource_settingdefault);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_filter);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_page);//更新fact中变量值
                        update(work_itemproject_resource_settingday_capacity);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_choose_obj);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_temp_obj);//更新fact中变量值
                        update(work_itemproject_resource_settinginsert_members);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_member);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_members);//更新fact中变量值
                        update(work_itemproject_resource_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[绑定资源成员列表]
            rule "bindparam2"
            ruleflow-group "work_itemproject_resource_settingbindparam2"
            when
            then
                        update(work_itemproject_resource_settingdefault);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_filter);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_page);//更新fact中变量值
                        update(work_itemproject_resource_settingday_capacity);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_choose_obj);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_temp_obj);//更新fact中变量值
                        update(work_itemproject_resource_settinginsert_members);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_member);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_members);//更新fact中变量值
                        update(work_itemproject_resource_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall2"
            ruleflow-group "work_itemproject_resource_settingloopsubcall2"
            when
            then
                        update(work_itemproject_resource_settingdefault);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_filter);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_page);//更新fact中变量值
                        update(work_itemproject_resource_settingday_capacity);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_choose_obj);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_temp_obj);//更新fact中变量值
                        update(work_itemproject_resource_settinginsert_members);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_member);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_members);//更新fact中变量值
                        update(work_itemproject_resource_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall3"
            ruleflow-group "work_itemproject_resource_settingloopsubcall3"
            when
            then
                        update(work_itemproject_resource_settingdefault);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_filter);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_page);//更新fact中变量值
                        update(work_itemproject_resource_settingday_capacity);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_choose_obj);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_temp_obj);//更新fact中变量值
                        update(work_itemproject_resource_settinginsert_members);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_member);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_members);//更新fact中变量值
                        update(work_itemproject_resource_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[判定节点（无业务操作）]
            rule "prepareparam4"
            ruleflow-group "work_itemproject_resource_settingprepareparam4"
            when
            then
                        update(work_itemproject_resource_settingdefault);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_filter);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_page);//更新fact中变量值
                        update(work_itemproject_resource_settingday_capacity);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_choose_obj);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_temp_obj);//更新fact中变量值
                        update(work_itemproject_resource_settinginsert_members);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_member);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_members);//更新fact中变量值
                        update(work_itemproject_resource_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[附加到数组参数]
            rule "appendparam2"
            ruleflow-group "work_itemproject_resource_settingappendparam2"
            when
            then
                        update(work_itemproject_resource_settingdefault);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_filter);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_page);//更新fact中变量值
                        update(work_itemproject_resource_settingday_capacity);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_choose_obj);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_temp_obj);//更新fact中变量值
                        update(work_itemproject_resource_settinginsert_members);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_member);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_members);//更新fact中变量值
                        update(work_itemproject_resource_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemproject_resource_settingloopsubcall1"
            when
            then
                        update(work_itemproject_resource_settingdefault);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_filter);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_page);//更新fact中变量值
                        update(work_itemproject_resource_settingday_capacity);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_choose_obj);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_temp_obj);//更新fact中变量值
                        update(work_itemproject_resource_settinginsert_members);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_member);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_members);//更新fact中变量值
                        update(work_itemproject_resource_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[判断此成员是否已加入至资源]
            rule "rawsfcode4"
            ruleflow-group "work_itemproject_resource_settingrawsfcode4"
            when
            then
                        update(work_itemproject_resource_settingdefault);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_filter);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_page);//更新fact中变量值
                        update(work_itemproject_resource_settingday_capacity);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_choose_obj);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_temp_obj);//更新fact中变量值
                        update(work_itemproject_resource_settinginsert_members);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_member);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_members);//更新fact中变量值
                        update(work_itemproject_resource_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[重新建立资源列表成员]
            rule "renewparam1"
            ruleflow-group "work_itemproject_resource_settingrenewparam1"
            when
            then
                        update(work_itemproject_resource_settingdefault);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_filter);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_page);//更新fact中变量值
                        update(work_itemproject_resource_settingday_capacity);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_choose_obj);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_temp_obj);//更新fact中变量值
                        update(work_itemproject_resource_settinginsert_members);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_member);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_members);//更新fact中变量值
                        update(work_itemproject_resource_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[填充默认容量/工作日]
            rule "prepareparam1"
            ruleflow-group "work_itemproject_resource_settingprepareparam1"
            when
            then
                            work_itemproject_resource_settingresource_member.set("id",work_itemproject_resource_settingfor_choose_obj.get("userid"));
                            work_itemproject_resource_settingresource_member.set("addonid",work_itemproject_resource_settingaddon_resource.get("id"));
                            work_itemproject_resource_settingresource_member.set("name",work_itemproject_resource_settingfor_choose_obj.get("name"));
                            work_itemproject_resource_settingresource_member.set("userid",work_itemproject_resource_settingfor_choose_obj.get("userid"));
                            work_itemproject_resource_settingresource_member.set("weekday","1,2,3,4,5");
                            work_itemproject_resource_settingday_capacity.set("id",work_itemproject_resource_settingfor_choose_obj.get("userid"));
                            work_itemproject_resource_settingday_capacity.set("workitemcount","3");
                            work_itemproject_resource_settingday_capacity.set("estimatedworkload","8");
                            work_itemproject_resource_settingday_capacity.set("remainingworkload","1");
                            work_itemproject_resource_settingday_capacity.set("storypoints","2");
                        update(work_itemproject_resource_settingdefault);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_filter);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_page);//更新fact中变量值
                        update(work_itemproject_resource_settingday_capacity);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_choose_obj);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_temp_obj);//更新fact中变量值
                        update(work_itemproject_resource_settinginsert_members);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_member);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_members);//更新fact中变量值
                        update(work_itemproject_resource_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[资源成员绑定容量属性]
            rule "rawsfcode2"
            ruleflow-group "work_itemproject_resource_settingrawsfcode2"
            when
            then
                        update(work_itemproject_resource_settingdefault);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_filter);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_page);//更新fact中变量值
                        update(work_itemproject_resource_settingday_capacity);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_choose_obj);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_temp_obj);//更新fact中变量值
                        update(work_itemproject_resource_settinginsert_members);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_member);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_members);//更新fact中变量值
                        update(work_itemproject_resource_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[附加到数组参数]
            rule "appendparam1"
            ruleflow-group "work_itemproject_resource_settingappendparam1"
            when
            then
                        update(work_itemproject_resource_settingdefault);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_filter);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_page);//更新fact中变量值
                        update(work_itemproject_resource_settingday_capacity);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_choose_obj);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_temp_obj);//更新fact中变量值
                        update(work_itemproject_resource_settinginsert_members);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_member);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_members);//更新fact中变量值
                        update(work_itemproject_resource_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[资源成员绑定至组件]
            rule "rawsfcode3"
            ruleflow-group "work_itemproject_resource_settingrawsfcode3"
            when
            then
                        update(work_itemproject_resource_settingdefault);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_filter);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_page);//更新fact中变量值
                        update(work_itemproject_resource_settingday_capacity);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_choose_obj);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_temp_obj);//更新fact中变量值
                        update(work_itemproject_resource_settinginsert_members);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_member);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_members);//更新fact中变量值
                        update(work_itemproject_resource_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[保存资源成员]
            rule "deaction2"
            ruleflow-group "work_itemproject_resource_settingdeaction2"
            when
            then
                        addon_resourceservice.update(work_itemproject_resource_settingaddon_resource);
                        update(work_itemproject_resource_settingdefault);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_filter);//更新fact中变量值
                        update(work_itemproject_resource_settingaddon_resource_page);//更新fact中变量值
                        update(work_itemproject_resource_settingday_capacity);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_choose_obj);//更新fact中变量值
                        update(work_itemproject_resource_settingfor_temp_obj);//更新fact中变量值
                        update(work_itemproject_resource_settinginsert_members);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_member);//更新fact中变量值
                        update(work_itemproject_resource_settingresource_members);//更新fact中变量值
                        update(work_itemproject_resource_settingsrfactionparam);//更新fact中变量值
            end