package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.requirement_tree_or_tile_query;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrequirement_tree_or_tile_querydefault;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrequirement_tree_or_tile_queryresult_page;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemrequirement_tree_or_tile_querybegin"
            when
            then
            end

            //逻辑处理节点[平铺表格查询]
            rule "dedataset1"
            ruleflow-group "work_itemrequirement_tree_or_tile_querydedataset1"
            when
            then
                        update(work_itemrequirement_tree_or_tile_querydefault);//更新fact中变量值
                        update(work_itemrequirement_tree_or_tile_queryresult_page);//更新fact中变量值
            end

            //逻辑处理节点[树状表格查询]
            rule "dedataset2"
            ruleflow-group "work_itemrequirement_tree_or_tile_querydedataset2"
            when
            then
                        update(work_itemrequirement_tree_or_tile_querydefault);//更新fact中变量值
                        update(work_itemrequirement_tree_or_tile_queryresult_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemrequirement_tree_or_tile_queryend1"
            when
            then
                        update(work_itemrequirement_tree_or_tile_querydefault);//更新fact中变量值
                        update(work_itemrequirement_tree_or_tile_queryresult_page);//更新fact中变量值
            end