package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.require_burn_out;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrequire_burn_outdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.sprint_alteration work_itemrequire_burn_outchange_filter;
                global cn.ibizlab.plm.core.projmgmt.domain.sprint_alteration work_itemrequire_burn_outchange_page;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrequire_burn_outresult_list;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrequire_burn_outresult_page;
                global cn.ibizlab.plm.core.projmgmt.domain.sprint work_itemrequire_burn_outsprint;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrequire_burn_outwork_item_filter;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrequire_burn_outwork_item_page;
                    global cn.ibizlab.plm.core.projmgmt.service.IsprintService sprintservice;
                    global cn.ibizlab.plm.core.projmgmt.service.Isprint_alterationService sprint_alterationservice;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin1"
            ruleflow-group "work_itemrequire_burn_outbegin1"
            when
            then
                        update(work_itemrequire_burn_outdefault);//更新fact中变量值
                        update(work_itemrequire_burn_outchange_filter);//更新fact中变量值
                        update(work_itemrequire_burn_outchange_page);//更新fact中变量值
                        update(work_itemrequire_burn_outresult_list);//更新fact中变量值
                        update(work_itemrequire_burn_outresult_page);//更新fact中变量值
                        update(work_itemrequire_burn_outsprint);//更新fact中变量值
                        update(work_itemrequire_burn_outwork_item_filter);//更新fact中变量值
                        update(work_itemrequire_burn_outwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[填充迭代标识]
            rule "prepareparam1"
            ruleflow-group "work_itemrequire_burn_outprepareparam1"
            when
            then
                            work_itemrequire_burn_outsprint.set("id",work_itemrequire_burn_outdefault.get("sprint"));
                            work_itemrequire_burn_outwork_item_filter.set("n_sprint_id_eq",work_itemrequire_burn_outdefault.get("sprint"));
                            work_itemrequire_burn_outchange_filter.set("n_sprint_id_eq",work_itemrequire_burn_outdefault.get("sprint"));
                        update(work_itemrequire_burn_outdefault);//更新fact中变量值
                        update(work_itemrequire_burn_outchange_filter);//更新fact中变量值
                        update(work_itemrequire_burn_outchange_page);//更新fact中变量值
                        update(work_itemrequire_burn_outresult_list);//更新fact中变量值
                        update(work_itemrequire_burn_outresult_page);//更新fact中变量值
                        update(work_itemrequire_burn_outsprint);//更新fact中变量值
                        update(work_itemrequire_burn_outwork_item_filter);//更新fact中变量值
                        update(work_itemrequire_burn_outwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[获取迭代]
            rule "deaction1"
            ruleflow-group "work_itemrequire_burn_outdeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(sprintservice.get(work_itemrequire_burn_outsprint.getId()),work_itemrequire_burn_outsprint);
                        update(work_itemrequire_burn_outdefault);//更新fact中变量值
                        update(work_itemrequire_burn_outchange_filter);//更新fact中变量值
                        update(work_itemrequire_burn_outchange_page);//更新fact中变量值
                        update(work_itemrequire_burn_outresult_list);//更新fact中变量值
                        update(work_itemrequire_burn_outresult_page);//更新fact中变量值
                        update(work_itemrequire_burn_outsprint);//更新fact中变量值
                        update(work_itemrequire_burn_outwork_item_filter);//更新fact中变量值
                        update(work_itemrequire_burn_outwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[查询迭代变更记录]
            rule "dedataset1"
            ruleflow-group "work_itemrequire_burn_outdedataset1"
            when
            then
                        update(work_itemrequire_burn_outdefault);//更新fact中变量值
                        update(work_itemrequire_burn_outchange_filter);//更新fact中变量值
                        update(work_itemrequire_burn_outchange_page);//更新fact中变量值
                        update(work_itemrequire_burn_outresult_list);//更新fact中变量值
                        update(work_itemrequire_burn_outresult_page);//更新fact中变量值
                        update(work_itemrequire_burn_outsprint);//更新fact中变量值
                        update(work_itemrequire_burn_outwork_item_filter);//更新fact中变量值
                        update(work_itemrequire_burn_outwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[获取迭代下的已完成工作项]
            rule "dedataset2"
            ruleflow-group "work_itemrequire_burn_outdedataset2"
            when
            then
                        update(work_itemrequire_burn_outdefault);//更新fact中变量值
                        update(work_itemrequire_burn_outchange_filter);//更新fact中变量值
                        update(work_itemrequire_burn_outchange_page);//更新fact中变量值
                        update(work_itemrequire_burn_outresult_list);//更新fact中变量值
                        update(work_itemrequire_burn_outresult_page);//更新fact中变量值
                        update(work_itemrequire_burn_outsprint);//更新fact中变量值
                        update(work_itemrequire_burn_outwork_item_filter);//更新fact中变量值
                        update(work_itemrequire_burn_outwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[根据迭代日期，计算统计数量]
            rule "rawsfcode2"
            ruleflow-group "work_itemrequire_burn_outrawsfcode2"
            when
            then
                        update(work_itemrequire_burn_outdefault);//更新fact中变量值
                        update(work_itemrequire_burn_outchange_filter);//更新fact中变量值
                        update(work_itemrequire_burn_outchange_page);//更新fact中变量值
                        update(work_itemrequire_burn_outresult_list);//更新fact中变量值
                        update(work_itemrequire_burn_outresult_page);//更新fact中变量值
                        update(work_itemrequire_burn_outsprint);//更新fact中变量值
                        update(work_itemrequire_burn_outwork_item_filter);//更新fact中变量值
                        update(work_itemrequire_burn_outwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[绑定返回结果]
            rule "bindparam1"
            ruleflow-group "work_itemrequire_burn_outbindparam1"
            when
            then
                        update(work_itemrequire_burn_outdefault);//更新fact中变量值
                        update(work_itemrequire_burn_outchange_filter);//更新fact中变量值
                        update(work_itemrequire_burn_outchange_page);//更新fact中变量值
                        update(work_itemrequire_burn_outresult_list);//更新fact中变量值
                        update(work_itemrequire_burn_outresult_page);//更新fact中变量值
                        update(work_itemrequire_burn_outsprint);//更新fact中变量值
                        update(work_itemrequire_burn_outwork_item_filter);//更新fact中变量值
                        update(work_itemrequire_burn_outwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemrequire_burn_outend1"
            when
            then
                        update(work_itemrequire_burn_outdefault);//更新fact中变量值
                        update(work_itemrequire_burn_outchange_filter);//更新fact中变量值
                        update(work_itemrequire_burn_outchange_page);//更新fact中变量值
                        update(work_itemrequire_burn_outresult_list);//更新fact中变量值
                        update(work_itemrequire_burn_outresult_page);//更新fact中变量值
                        update(work_itemrequire_burn_outsprint);//更新fact中变量值
                        update(work_itemrequire_burn_outwork_item_filter);//更新fact中变量值
                        update(work_itemrequire_burn_outwork_item_page);//更新fact中变量值
            end