package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.resource_assignment;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemresource_assignmentdefault;
                global cn.ibizlab.plm.core.base.domain.addon_resource work_itemresource_assignmentaddon_resource;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemresource_assignmentwork_item_page;
                    global cn.ibizlab.plm.core.base.service.Iaddon_resourceService addon_resourceservice;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemresource_assignmentbegin"
            when
            then
            end

            //逻辑处理节点[设置过滤参数]
            rule "prepareparam1"
            ruleflow-group "work_itemresource_assignmentprepareparam1"
            when
            then
                            work_itemresource_assignmentaddon_resource.set("id","42e3898e-d43b-3f3c-611b-87b5e6ed2233_resource");
                            work_itemresource_assignmentdefault.set("size","10000");
                        update(work_itemresource_assignmentdefault);//更新fact中变量值
                        update(work_itemresource_assignmentaddon_resource);//更新fact中变量值
                        update(work_itemresource_assignmentwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[获取组件数据]
            rule "deaction1"
            ruleflow-group "work_itemresource_assignmentdeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(addon_resourceservice.get(work_itemresource_assignmentaddon_resource.getId()),work_itemresource_assignmentaddon_resource);
                        update(work_itemresource_assignmentdefault);//更新fact中变量值
                        update(work_itemresource_assignmentaddon_resource);//更新fact中变量值
                        update(work_itemresource_assignmentwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[获取工作项]
            rule "dedataset1"
            ruleflow-group "work_itemresource_assignmentdedataset1"
            when
            then
                        update(work_itemresource_assignmentdefault);//更新fact中变量值
                        update(work_itemresource_assignmentaddon_resource);//更新fact中变量值
                        update(work_itemresource_assignmentwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[获取members中的user_id]
            rule "rawsfcode1"
            ruleflow-group "work_itemresource_assignmentrawsfcode1"
            when
            then
                        update(work_itemresource_assignmentdefault);//更新fact中变量值
                        update(work_itemresource_assignmentaddon_resource);//更新fact中变量值
                        update(work_itemresource_assignmentwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemresource_assignmentend1"
            when
            then
                        update(work_itemresource_assignmentdefault);//更新fact中变量值
                        update(work_itemresource_assignmentaddon_resource);//更新fact中变量值
                        update(work_itemresource_assignmentwork_item_page);//更新fact中变量值
            end