package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.set_type_bug;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemset_type_bugdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.project work_itemset_type_bugproject;
                    global cn.ibizlab.plm.core.projmgmt.service.IprojectService projectservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemset_type_bugbegin"
            when
            then
            end

            //逻辑处理节点[准备项目id]
            rule "prepareparam1"
            ruleflow-group "work_itemset_type_bugprepareparam1"
            when
            then
                            work_itemset_type_bugproject.set("id",work_itemset_type_bugdefault.get("projectid"));
                        update(work_itemset_type_bugdefault);//更新fact中变量值
                        update(work_itemset_type_bugproject);//更新fact中变量值
            end

            //逻辑处理节点[获取项目信息]
            rule "deaction1"
            ruleflow-group "work_itemset_type_bugdeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(projectservice.get(work_itemset_type_bugproject.getId()),work_itemset_type_bugproject);
                        update(work_itemset_type_bugdefault);//更新fact中变量值
                        update(work_itemset_type_bugproject);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "work_itemset_type_bugdebugparam1"
            when
            then
                        update(work_itemset_type_bugdefault);//更新fact中变量值
                        update(work_itemset_type_bugproject);//更新fact中变量值
            end

            //逻辑处理节点[设置项目类别]
            rule "prepareparam2"
            ruleflow-group "work_itemset_type_bugprepareparam2"
            when
            then
                            work_itemset_type_bugdefault.set("projecttype",work_itemset_type_bugproject.get("type"));
                            work_itemset_type_bugdefault.set("projectname",work_itemset_type_bugproject.get("name"));
                        update(work_itemset_type_bugdefault);//更新fact中变量值
                        update(work_itemset_type_bugproject);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode2"
            ruleflow-group "work_itemset_type_bugrawsfcode2"
            when
            then
                        update(work_itemset_type_bugdefault);//更新fact中变量值
                        update(work_itemset_type_bugproject);//更新fact中变量值
            end

            //逻辑处理节点[设置缺陷类型]
            rule "rawsfcode1"
            ruleflow-group "work_itemset_type_bugrawsfcode1"
            when
            then
                        update(work_itemset_type_bugdefault);//更新fact中变量值
                        update(work_itemset_type_bugproject);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemset_type_bugend1"
            when
            then
                        update(work_itemset_type_bugdefault);//更新fact中变量值
                        update(work_itemset_type_bugproject);//更新fact中变量值
            end