package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.workload_work_item;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemworkload_work_itemdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.project_member work_itemworkload_work_itemfilter;
                global java.util.Map work_itemworkload_work_itemfor_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.project_member work_itemworkload_work_itemmembers;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemworkload_work_itemwork_item_filter;
                    global cn.ibizlab.plm.core.projmgmt.service.Iproject_memberService project_memberservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemworkload_work_itembegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "work_itemworkload_work_itemdebugparam1"
            when
            then
                        update(work_itemworkload_work_itemdefault);//更新fact中变量值
                        update(work_itemworkload_work_itemfilter);//更新fact中变量值
                        update(work_itemworkload_work_itemfor_obj);//更新fact中变量值
                        update(work_itemworkload_work_itemmembers);//更新fact中变量值
                        update(work_itemworkload_work_itemwork_item_filter);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "work_itemworkload_work_itemend2"
            when
            then
                        update(work_itemworkload_work_itemdefault);//更新fact中变量值
                        update(work_itemworkload_work_itemfilter);//更新fact中变量值
                        update(work_itemworkload_work_itemfor_obj);//更新fact中变量值
                        update(work_itemworkload_work_itemmembers);//更新fact中变量值
                        update(work_itemworkload_work_itemwork_item_filter);//更新fact中变量值
            end

            //逻辑处理节点[获取产品id并设置过滤参数]
            rule "prepareparam2"
            ruleflow-group "work_itemworkload_work_itemprepareparam2"
            when
            then
                            work_itemworkload_work_itemfilter.set("n_project_id_eq",work_itemworkload_work_itemdefault.get("projectid"));
                                work_itemworkload_work_itemfilter.set("n_user_id_eq",curuser.getSessionParams().get("srfpersonid"));
                        update(work_itemworkload_work_itemdefault);//更新fact中变量值
                        update(work_itemworkload_work_itemfilter);//更新fact中变量值
                        update(work_itemworkload_work_itemfor_obj);//更新fact中变量值
                        update(work_itemworkload_work_itemmembers);//更新fact中变量值
                        update(work_itemworkload_work_itemwork_item_filter);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam3"
            ruleflow-group "work_itemworkload_work_itemprepareparam3"
            when
            then
                            work_itemworkload_work_itemwork_item_filter.set("n_is_deleted_eq","0");
                            work_itemworkload_work_itemwork_item_filter.set("n_is_archived_eq","0");
                            work_itemworkload_work_itemwork_item_filter.set("n_project_is_archived_eq","0");
                        update(work_itemworkload_work_itemdefault);//更新fact中变量值
                        update(work_itemworkload_work_itemfilter);//更新fact中变量值
                        update(work_itemworkload_work_itemfor_obj);//更新fact中变量值
                        update(work_itemworkload_work_itemmembers);//更新fact中变量值
                        update(work_itemworkload_work_itemwork_item_filter);//更新fact中变量值
            end

            //逻辑处理节点[判断系统管理员身份]
            rule "rawsfcode3"
            ruleflow-group "work_itemworkload_work_itemrawsfcode3"
            when
            then
                        update(work_itemworkload_work_itemdefault);//更新fact中变量值
                        update(work_itemworkload_work_itemfilter);//更新fact中变量值
                        update(work_itemworkload_work_itemfor_obj);//更新fact中变量值
                        update(work_itemworkload_work_itemmembers);//更新fact中变量值
                        update(work_itemworkload_work_itemwork_item_filter);//更新fact中变量值
            end

            //逻辑处理节点[查询当前用户是否为项目成员]
            rule "dedataset3"
            ruleflow-group "work_itemworkload_work_itemdedataset3"
            when
            then
                        update(work_itemworkload_work_itemdefault);//更新fact中变量值
                        update(work_itemworkload_work_itemfilter);//更新fact中变量值
                        update(work_itemworkload_work_itemfor_obj);//更新fact中变量值
                        update(work_itemworkload_work_itemmembers);//更新fact中变量值
                        update(work_itemworkload_work_itemwork_item_filter);//更新fact中变量值
            end

            //逻辑处理节点[绑定用户数据到for_obj]
            rule "prepareparam5"
            ruleflow-group "work_itemworkload_work_itemprepareparam5"
            when
            then
                            work_itemworkload_work_itemfor_obj.set("",work_itemworkload_work_itemmembers.get("0"));
                        update(work_itemworkload_work_itemdefault);//更新fact中变量值
                        update(work_itemworkload_work_itemfilter);//更新fact中变量值
                        update(work_itemworkload_work_itemfor_obj);//更新fact中变量值
                        update(work_itemworkload_work_itemmembers);//更新fact中变量值
                        update(work_itemworkload_work_itemwork_item_filter);//更新fact中变量值
            end

            //逻辑处理节点[只读权限]
            rule "rawsfcode1"
            ruleflow-group "work_itemworkload_work_itemrawsfcode1"
            when
            then
                        update(work_itemworkload_work_itemdefault);//更新fact中变量值
                        update(work_itemworkload_work_itemfilter);//更新fact中变量值
                        update(work_itemworkload_work_itemfor_obj);//更新fact中变量值
                        update(work_itemworkload_work_itemmembers);//更新fact中变量值
                        update(work_itemworkload_work_itemwork_item_filter);//更新fact中变量值
            end

            //逻辑处理节点[非只读权限]
            rule "rawsfcode2"
            ruleflow-group "work_itemworkload_work_itemrawsfcode2"
            when
            then
                        update(work_itemworkload_work_itemdefault);//更新fact中变量值
                        update(work_itemworkload_work_itemfilter);//更新fact中变量值
                        update(work_itemworkload_work_itemfor_obj);//更新fact中变量值
                        update(work_itemworkload_work_itemmembers);//更新fact中变量值
                        update(work_itemworkload_work_itemwork_item_filter);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end6"
            ruleflow-group "work_itemworkload_work_itemend6"
            when
            then
                        update(work_itemworkload_work_itemdefault);//更新fact中变量值
                        update(work_itemworkload_work_itemfilter);//更新fact中变量值
                        update(work_itemworkload_work_itemfor_obj);//更新fact中变量值
                        update(work_itemworkload_work_itemmembers);//更新fact中变量值
                        update(work_itemworkload_work_itemwork_item_filter);//更新fact中变量值
            end