package cn.ibizlab.plm.extension.logic.pscoreprdfunclogic.versions;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.extension.domain.PSCorePrdFunc pscoreprdfuncversionsdefault;
                global cn.ibizlab.plm.core.extension.domain.PSCorePrdFunc pscoreprdfuncversionsfunc;
                global java.util.Map pscoreprdfuncversionsversions;
                    global cn.ibizlab.plm.core.extension.service.IPSCorePrdFuncService pscoreprdfuncservice;
        global cn.ibizlab.plm.core.extension.service.IPSCorePrdFuncService iBzSysPscoreprdfuncDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "pscoreprdfuncversionsbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "pscoreprdfuncversionsprepareparam_01"
            when
            then
                        update(pscoreprdfuncversionsdefault);//更新fact中变量值
                        update(pscoreprdfuncversionsfunc);//更新fact中变量值
                        update(pscoreprdfuncversionsversions);//更新fact中变量值
            end

            //逻辑处理节点[getfunc]
            rule "deaction_01"
            ruleflow-group "pscoreprdfuncversionsdeaction_01"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(pscoreprdfuncservice.get(pscoreprdfuncversionsdefault.getPscoreprdfuncid()),pscoreprdfuncversionsdefault);
                        update(pscoreprdfuncversionsdefault);//更新fact中变量值
                        update(pscoreprdfuncversionsfunc);//更新fact中变量值
                        update(pscoreprdfuncversionsversions);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode_01"
            ruleflow-group "pscoreprdfuncversionsrawsfcode_01"
            when
            then
                        update(pscoreprdfuncversionsdefault);//更新fact中变量值
                        update(pscoreprdfuncversionsfunc);//更新fact中变量值
                        update(pscoreprdfuncversionsversions);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "pscoreprdfuncversionsend_01"
            when
            then
                        update(pscoreprdfuncversionsdefault);//更新fact中变量值
                        update(pscoreprdfuncversionsfunc);//更新fact中变量值
                        update(pscoreprdfuncversionsversions);//更新fact中变量值
            end