package cn.ibizlab.plm.extension.logic.pscoreprdfunclogic.versions;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.extension.domain.PSCorePrdFunc pscoreprdfuncversionsdefault;
        global cn.ibizlab.plm.core.extension.service.IPSCorePrdFuncService iBzSysPscoreprdfuncDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "pscoreprdfuncversionsbegin"
            when
            then
            end