package cn.ibizlab.plm.projmgmt.logic.sprint_alterationlogic.rep_change;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.sprint_alteration sprint_alterationrep_changedefault;
        global cn.ibizlab.plm.core.projmgmt.service.Isprint_alterationService iBzSysSprint_alterationDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "sprint_alterationrep_changebegin"
            when
            then
            end

            //逻辑处理节点[起始数量]
            rule "rawsqlcall1"
            ruleflow-group "sprint_alterationrep_changerawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",sprint_alterationrep_changedefault.get("sprint"));
    String strSql="select count(1) as `first_count` from sprint_alteration where SPRINT_ID = #{et.param0} and `type` = '1' and SPRINT_STATUS = '1'";
                        java.util.List<JSONObject> entities=iBzSysSprint_alterationDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    sprint_alterationrep_changedefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(sprint_alterationrep_changedefault);//更新fact中变量值
            end

            //逻辑处理节点[移入数量]
            rule "rawsqlcall2"
            ruleflow-group "sprint_alterationrep_changerawsqlcall2"
            when
            then
    Map param =new HashMap();
        param.put("param0",sprint_alterationrep_changedefault.get("sprint"));
    String strSql="select count(1) as `shift_in_count` from sprint_alteration where SPRINT_ID = #{et.param0} and `type` = '1'  ";
                        java.util.List<JSONObject> entities=iBzSysSprint_alterationDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    sprint_alterationrep_changedefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(sprint_alterationrep_changedefault);//更新fact中变量值
            end

            //逻辑处理节点[移出数量]
            rule "rawsqlcall3"
            ruleflow-group "sprint_alterationrep_changerawsqlcall3"
            when
            then
    Map param =new HashMap();
        param.put("param0",sprint_alterationrep_changedefault.get("sprint"));
    String strSql="select count(1) as `shift_in_count` from sprint_alteration where SPRINT_ID = #{et.param0} and `type` = '2'  ";
                        java.util.List<JSONObject> entities=iBzSysSprint_alterationDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    sprint_alterationrep_changedefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(sprint_alterationrep_changedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "sprint_alterationrep_changeend1"
            when
            then
                        update(sprint_alterationrep_changedefault);//更新fact中变量值
            end