package cn.ibizlab.plm.base.logic.addon_resourcelogic.check_resource_is_deleted;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.addon_resource addon_resourcecheck_resource_is_deleteddefault;
                global java.util.Map addon_resourcecheck_resource_is_deletedcheckkey;
                    global cn.ibizlab.plm.core.base.service.Iaddon_resourceService addon_resourceservice;
        global cn.ibizlab.plm.core.base.service.Iaddon_resourceService iBzSysAddon_resourceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "addon_resourcecheck_resource_is_deletedbegin"
            when
            then
            end

            //逻辑处理节点[验证主键是否存在]
            rule "deaction1"
            ruleflow-group "addon_resourcecheck_resource_is_deleteddeaction1"
            when
            then
                        addon_resourceservice.checkKey(addon_resourcecheck_resource_is_deleteddefault);
                        update(addon_resourcecheck_resource_is_deleteddefault);//更新fact中变量值
                        update(addon_resourcecheck_resource_is_deletedcheckkey);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "addon_resourcecheck_resource_is_deletedprepareparam1"
            when
            then
                            addon_resourcecheck_resource_is_deleteddefault.set("checkkey",addon_resourcecheck_resource_is_deletedcheckkey.get(""));
                        update(addon_resourcecheck_resource_is_deleteddefault);//更新fact中变量值
                        update(addon_resourcecheck_resource_is_deletedcheckkey);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "addon_resourcecheck_resource_is_deletedend1"
            when
            then
                        update(addon_resourcecheck_resource_is_deleteddefault);//更新fact中变量值
                        update(addon_resourcecheck_resource_is_deletedcheckkey);//更新fact中变量值
            end