package cn.ibizlab.plm.ai.logic.ai_agent_contextlogic.agent_flow_clone;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_agent_context ai_agent_contextagent_flow_clonedefault;
                    global cn.ibizlab.plm.core.ai.service.Iai_agent_contextService ai_agent_contextservice;
        global cn.ibizlab.plm.core.ai.service.Iai_agent_contextService iBzSysAi_agent_contextDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_agent_contextagent_flow_clonebegin"
            when
            then
            end

            //逻辑处理节点[获取选中flow智能体数据]
            rule "deaction_01"
            ruleflow-group "ai_agent_contextagent_flow_clonedeaction_01"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(ai_agent_contextservice.get(ai_agent_contextagent_flow_clonedefault.getId()),ai_agent_contextagent_flow_clonedefault);
                        update(ai_agent_contextagent_flow_clonedefault);//更新fact中变量值
            end