package cn.ibizlab.plm.ai.logic.ai_agent_contextlogic.create_default_flow_logic;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_agent_context ai_agent_contextcreate_default_flow_logicdefault;
                global cn.ibizlab.plm.core.ai.domain.ai_agent_context ai_agent_contextcreate_default_flow_logicoriginal_ag_context;
                global cn.ibizlab.plm.core.extension.domain.PSDELogic ai_agent_contextcreate_default_flow_logicoriginal_delogic;
                    global cn.ibizlab.plm.core.extension.service.IPSDELogicService psdelogicservice;
        global cn.ibizlab.plm.core.ai.service.Iai_agent_contextService iBzSysAi_agent_contextDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_agent_contextcreate_default_flow_logicbegin"
            when
            then
            end

            //逻辑处理节点[准备模板智能体逻辑]
            rule "prepareparam_01"
            ruleflow-group "ai_agent_contextcreate_default_flow_logicprepareparam_01"
            when
            then
                            ai_agent_contextcreate_default_flow_logicoriginal_delogic.set("psdelogicid","ai.AI_AGENT_CONTEXT.agent_flow_templ");
                        update(ai_agent_contextcreate_default_flow_logicdefault);//更新fact中变量值
                        update(ai_agent_contextcreate_default_flow_logicoriginal_ag_context);//更新fact中变量值
                        update(ai_agent_contextcreate_default_flow_logicoriginal_delogic);//更新fact中变量值
            end

            //逻辑处理节点[获取选择flow智能体逻辑]
            rule "deaction_03"
            ruleflow-group "ai_agent_contextcreate_default_flow_logicdeaction_03"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(psdelogicservice.get(ai_agent_contextcreate_default_flow_logicoriginal_delogic.getPsdelogicid()),ai_agent_contextcreate_default_flow_logicoriginal_delogic);
                        update(ai_agent_contextcreate_default_flow_logicdefault);//更新fact中变量值
                        update(ai_agent_contextcreate_default_flow_logicoriginal_ag_context);//更新fact中变量值
                        update(ai_agent_contextcreate_default_flow_logicoriginal_delogic);//更新fact中变量值
            end

            //逻辑处理节点[创建logic]
            rule "deaction_04"
            ruleflow-group "ai_agent_contextcreate_default_flow_logicdeaction_04"
            when
            then
                        psdelogicservice.create(ai_agent_contextcreate_default_flow_logicoriginal_delogic);
                        update(ai_agent_contextcreate_default_flow_logicdefault);//更新fact中变量值
                        update(ai_agent_contextcreate_default_flow_logicoriginal_ag_context);//更新fact中变量值
                        update(ai_agent_contextcreate_default_flow_logicoriginal_delogic);//更新fact中变量值
            end

            //逻辑处理节点[构造新逻辑信息]
            rule "rawsfcode_03"
            ruleflow-group "ai_agent_contextcreate_default_flow_logicrawsfcode_03"
            when
            then
                        update(ai_agent_contextcreate_default_flow_logicdefault);//更新fact中变量值
                        update(ai_agent_contextcreate_default_flow_logicoriginal_ag_context);//更新fact中变量值
                        update(ai_agent_contextcreate_default_flow_logicoriginal_delogic);//更新fact中变量值
            end

            //逻辑处理节点[应用逻辑]
            rule "deaction_05"
            ruleflow-group "ai_agent_contextcreate_default_flow_logicdeaction_05"
            when
            then
                        psdelogicservice.apply(ai_agent_contextcreate_default_flow_logicoriginal_delogic);
                        update(ai_agent_contextcreate_default_flow_logicdefault);//更新fact中变量值
                        update(ai_agent_contextcreate_default_flow_logicoriginal_ag_context);//更新fact中变量值
                        update(ai_agent_contextcreate_default_flow_logicoriginal_delogic);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_agent_contextcreate_default_flow_logicend_01"
            when
            then
                        update(ai_agent_contextcreate_default_flow_logicdefault);//更新fact中变量值
                        update(ai_agent_contextcreate_default_flow_logicoriginal_ag_context);//更新fact中变量值
                        update(ai_agent_contextcreate_default_flow_logicoriginal_delogic);//更新fact中变量值
            end