package cn.ibizlab.plm.ai.logic.ai_agent_contextlogic.delete_extend_model;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_agent_context ai_agent_contextdelete_extend_modeldefault;
                global cn.ibizlab.plm.core.extension.domain.PSDELogic ai_agent_contextdelete_extend_modeldelogic;
                    global cn.ibizlab.plm.core.extension.service.IPSDELogicService psdelogicservice;
                    global cn.ibizlab.plm.core.ai.service.Iai_agent_contextService ai_agent_contextservice;
        global cn.ibizlab.plm.core.ai.service.Iai_agent_contextService iBzSysAi_agent_contextDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_agent_contextdelete_extend_modelbegin"
            when
            then
            end

            //逻辑处理节点[获取extend_logic]
            rule "deaction_01"
            ruleflow-group "ai_agent_contextdelete_extend_modeldeaction_01"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(psdelogicservice.get(ai_agent_contextdelete_extend_modeldelogic.getPsdelogicid()),ai_agent_contextdelete_extend_modeldelogic);
                        update(ai_agent_contextdelete_extend_modeldefault);//更新fact中变量值
                        update(ai_agent_contextdelete_extend_modeldelogic);//更新fact中变量值
            end

            //逻辑处理节点[删除extend_logic]
            rule "deaction_02"
            ruleflow-group "ai_agent_contextdelete_extend_modeldeaction_02"
            when
            then
                        psdelogicservice.remove(ai_agent_contextdelete_extend_modeldelogic.getPsdelogicid());
                        update(ai_agent_contextdelete_extend_modeldefault);//更新fact中变量值
                        update(ai_agent_contextdelete_extend_modeldelogic);//更新fact中变量值
            end

            //逻辑处理节点[获取agent_context]
            rule "deaction_03"
            ruleflow-group "ai_agent_contextdelete_extend_modeldeaction_03"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(ai_agent_contextservice.get(ai_agent_contextdelete_extend_modeldefault.getId()),ai_agent_contextdelete_extend_modeldefault);
                        update(ai_agent_contextdelete_extend_modeldefault);//更新fact中变量值
                        update(ai_agent_contextdelete_extend_modeldelogic);//更新fact中变量值
            end

            //逻辑处理节点[查看logic数据]
            rule "debugparam_01"
            ruleflow-group "ai_agent_contextdelete_extend_modeldebugparam_01"
            when
            then
                        update(ai_agent_contextdelete_extend_modeldefault);//更新fact中变量值
                        update(ai_agent_contextdelete_extend_modeldelogic);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_agent_contextdelete_extend_modelend_01"
            when
            then
                        update(ai_agent_contextdelete_extend_modeldefault);//更新fact中变量值
                        update(ai_agent_contextdelete_extend_modeldelogic);//更新fact中变量值
            end

            //逻辑处理节点[拼接model标识]
            rule "rawsfcode_01"
            ruleflow-group "ai_agent_contextdelete_extend_modelrawsfcode_01"
            when
            then
                        update(ai_agent_contextdelete_extend_modeldefault);//更新fact中变量值
                        update(ai_agent_contextdelete_extend_modeldelogic);//更新fact中变量值
            end