package cn.ibizlab.plm.ai.logic.ai_agent_contextlogic.fill_with_agent;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_agent_context ai_agent_contextfill_with_agentdefault;
                    global cn.ibizlab.plm.core.ai.service.Iai_agent_contextService ai_agent_contextservice;
        global cn.ibizlab.plm.core.ai.service.Iai_agent_contextService iBzSysAi_agent_contextDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_agent_contextfill_with_agentbegin"
            when
            then
            end

            //逻辑处理节点[获取数据]
            rule "deaction_01"
            ruleflow-group "ai_agent_contextfill_with_agentdeaction_01"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(ai_agent_contextservice.get(ai_agent_contextfill_with_agentdefault.getId()),ai_agent_contextfill_with_agentdefault);
                        update(ai_agent_contextfill_with_agentdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_agent_contextfill_with_agentend_01"
            when
            then
                        update(ai_agent_contextfill_with_agentdefault);//更新fact中变量值
            end