package cn.ibizlab.plm.base.logic.recentlogic.create_bug;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.recent recentcreate_bugdefault;
        global cn.ibizlab.plm.core.base.service.IrecentService iBzSysRecentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "recentcreate_bugbegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "recentcreate_bugdebugparam1"
            when
            then
                        update(recentcreate_bugdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "recentcreate_bugend1"
            when
            then
                        update(recentcreate_bugdefault);//更新fact中变量值
            end