package cn.ibizlab.plm.base.logic.recentlogic.recent_access;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.recent recentrecent_accessdefault;
                global java.util.Map recentrecent_accessowner_id;
                global cn.ibizlab.plm.core.base.domain.recent recentrecent_accessrecent_access;
                global java.util.Map recentrecent_accessreturn_data;
                global cn.ibizlab.plm.core.base.domain.recent recentrecent_accesssq_access_page;
                global cn.ibizlab.plm.core.base.domain.recent recentrecent_accesstemp_access_data;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea recentrecent_accesstemp_idea_data;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket recentrecent_accesstemp_ticket_data;
                    global cn.ibizlab.plm.core.base.service.IrecentService recentservice;
                    global cn.ibizlab.plm.core.prodmgmt.service.IideaService ideaservice;
                    global cn.ibizlab.plm.core.prodmgmt.service.IticketService ticketservice;
                    global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService test_caseservice;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.base.service.IrecentService iBzSysRecentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "recentrecent_accessbegin"
            when
            then
            end

            //逻辑处理节点[查询20条最近访问数据]
            rule "dedataset1"
            ruleflow-group "recentrecent_accessdedataset1"
            when
            then
                        update(recentrecent_accessdefault);//更新fact中变量值
                        update(recentrecent_accessowner_id);//更新fact中变量值
                        update(recentrecent_accessrecent_access);//更新fact中变量值
                        update(recentrecent_accessreturn_data);//更新fact中变量值
                        update(recentrecent_accesssq_access_page);//更新fact中变量值
                        update(recentrecent_accesstemp_access_data);//更新fact中变量值
                        update(recentrecent_accesstemp_idea_data);//更新fact中变量值
                        update(recentrecent_accesstemp_ticket_data);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "recentrecent_accessloopsubcall1"
            when
            then
                        update(recentrecent_accessdefault);//更新fact中变量值
                        update(recentrecent_accessowner_id);//更新fact中变量值
                        update(recentrecent_accessrecent_access);//更新fact中变量值
                        update(recentrecent_accessreturn_data);//更新fact中变量值
                        update(recentrecent_accesssq_access_page);//更新fact中变量值
                        update(recentrecent_accesstemp_access_data);//更新fact中变量值
                        update(recentrecent_accesstemp_idea_data);//更新fact中变量值
                        update(recentrecent_accesstemp_ticket_data);//更新fact中变量值
            end

            //逻辑处理节点[获取所属对象id]
            rule "prepareparam1"
            ruleflow-group "recentrecent_accessprepareparam1"
            when
            then
                            recentrecent_accessowner_id.set("",recentrecent_accesstemp_access_data.get("ownerid"));
                        update(recentrecent_accessdefault);//更新fact中变量值
                        update(recentrecent_accessowner_id);//更新fact中变量值
                        update(recentrecent_accessrecent_access);//更新fact中变量值
                        update(recentrecent_accessreturn_data);//更新fact中变量值
                        update(recentrecent_accesssq_access_page);//更新fact中变量值
                        update(recentrecent_accesstemp_access_data);//更新fact中变量值
                        update(recentrecent_accesstemp_idea_data);//更新fact中变量值
                        update(recentrecent_accesstemp_ticket_data);//更新fact中变量值
            end

            //逻辑处理节点[绑定结果参数]
            rule "bindparam1"
            ruleflow-group "recentrecent_accessbindparam1"
            when
            then
                        update(recentrecent_accessdefault);//更新fact中变量值
                        update(recentrecent_accessowner_id);//更新fact中变量值
                        update(recentrecent_accessrecent_access);//更新fact中变量值
                        update(recentrecent_accessreturn_data);//更新fact中变量值
                        update(recentrecent_accesssq_access_page);//更新fact中变量值
                        update(recentrecent_accesstemp_access_data);//更新fact中变量值
                        update(recentrecent_accesstemp_idea_data);//更新fact中变量值
                        update(recentrecent_accesstemp_ticket_data);//更新fact中变量值
            end

            //逻辑处理节点[获取idea类数据]
            rule "deaction1"
            ruleflow-group "recentrecent_accessdeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(ideaservice.get(recentrecent_accessowner_id.getId()),recentrecent_accessowner_id);
                        update(recentrecent_accessdefault);//更新fact中变量值
                        update(recentrecent_accessowner_id);//更新fact中变量值
                        update(recentrecent_accessrecent_access);//更新fact中变量值
                        update(recentrecent_accessreturn_data);//更新fact中变量值
                        update(recentrecent_accesssq_access_page);//更新fact中变量值
                        update(recentrecent_accesstemp_access_data);//更新fact中变量值
                        update(recentrecent_accesstemp_idea_data);//更新fact中变量值
                        update(recentrecent_accesstemp_ticket_data);//更新fact中变量值
            end

            //逻辑处理节点[获取ticket类数据]
            rule "deaction2"
            ruleflow-group "recentrecent_accessdeaction2"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(ticketservice.get(recentrecent_accessowner_id.getId()),recentrecent_accessowner_id);
                        update(recentrecent_accessdefault);//更新fact中变量值
                        update(recentrecent_accessowner_id);//更新fact中变量值
                        update(recentrecent_accessrecent_access);//更新fact中变量值
                        update(recentrecent_accessreturn_data);//更新fact中变量值
                        update(recentrecent_accesssq_access_page);//更新fact中变量值
                        update(recentrecent_accesstemp_access_data);//更新fact中变量值
                        update(recentrecent_accesstemp_idea_data);//更新fact中变量值
                        update(recentrecent_accesstemp_ticket_data);//更新fact中变量值
            end

            //逻辑处理节点[获取测试用例类数据]
            rule "deaction3"
            ruleflow-group "recentrecent_accessdeaction3"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(test_caseservice.get(recentrecent_accessowner_id.getId()),recentrecent_accessowner_id);
                        update(recentrecent_accessdefault);//更新fact中变量值
                        update(recentrecent_accessowner_id);//更新fact中变量值
                        update(recentrecent_accessrecent_access);//更新fact中变量值
                        update(recentrecent_accessreturn_data);//更新fact中变量值
                        update(recentrecent_accesssq_access_page);//更新fact中变量值
                        update(recentrecent_accesstemp_access_data);//更新fact中变量值
                        update(recentrecent_accesstemp_idea_data);//更新fact中变量值
                        update(recentrecent_accesstemp_ticket_data);//更新fact中变量值
            end

            //逻辑处理节点[获取工作项类数据]
            rule "deaction4"
            ruleflow-group "recentrecent_accessdeaction4"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(work_itemservice.get(recentrecent_accessowner_id.getId()),recentrecent_accessowner_id);
                        update(recentrecent_accessdefault);//更新fact中变量值
                        update(recentrecent_accessowner_id);//更新fact中变量值
                        update(recentrecent_accessrecent_access);//更新fact中变量值
                        update(recentrecent_accessreturn_data);//更新fact中变量值
                        update(recentrecent_accesssq_access_page);//更新fact中变量值
                        update(recentrecent_accesstemp_access_data);//更新fact中变量值
                        update(recentrecent_accesstemp_idea_data);//更新fact中变量值
                        update(recentrecent_accesstemp_ticket_data);//更新fact中变量值
            end

            //逻辑处理节点[获取所属产品]
            rule "prepareparam2"
            ruleflow-group "recentrecent_accessprepareparam2"
            when
            then
                            recentrecent_accesstemp_access_data.set("recentparent",recentrecent_accessreturn_data.get("product_id"));
                            recentrecent_accesstemp_access_data.set("recentparentname",recentrecent_accessreturn_data.get("product_name"));
                        update(recentrecent_accessdefault);//更新fact中变量值
                        update(recentrecent_accessowner_id);//更新fact中变量值
                        update(recentrecent_accessrecent_access);//更新fact中变量值
                        update(recentrecent_accessreturn_data);//更新fact中变量值
                        update(recentrecent_accesssq_access_page);//更新fact中变量值
                        update(recentrecent_accesstemp_access_data);//更新fact中变量值
                        update(recentrecent_accesstemp_idea_data);//更新fact中变量值
                        update(recentrecent_accesstemp_ticket_data);//更新fact中变量值
            end

            //逻辑处理节点[获取工单所属产品]
            rule "prepareparam3"
            ruleflow-group "recentrecent_accessprepareparam3"
            when
            then
                            recentrecent_accesstemp_access_data.set("recentparent",recentrecent_accessreturn_data.get("product_id"));
                            recentrecent_accesstemp_access_data.set("recentparentname",recentrecent_accessreturn_data.get("product_name"));
                        update(recentrecent_accessdefault);//更新fact中变量值
                        update(recentrecent_accessowner_id);//更新fact中变量值
                        update(recentrecent_accessrecent_access);//更新fact中变量值
                        update(recentrecent_accessreturn_data);//更新fact中变量值
                        update(recentrecent_accesssq_access_page);//更新fact中变量值
                        update(recentrecent_accesstemp_access_data);//更新fact中变量值
                        update(recentrecent_accesstemp_idea_data);//更新fact中变量值
                        update(recentrecent_accesstemp_ticket_data);//更新fact中变量值
            end

            //逻辑处理节点[获取测试用例所属测试库]
            rule "prepareparam4"
            ruleflow-group "recentrecent_accessprepareparam4"
            when
            then
                            recentrecent_accesstemp_access_data.set("recentparent",recentrecent_accessreturn_data.get("test_library_id"));
                            recentrecent_accesstemp_access_data.set("recentparentname",recentrecent_accessreturn_data.get("test_library_name"));
                        update(recentrecent_accessdefault);//更新fact中变量值
                        update(recentrecent_accessowner_id);//更新fact中变量值
                        update(recentrecent_accessrecent_access);//更新fact中变量值
                        update(recentrecent_accessreturn_data);//更新fact中变量值
                        update(recentrecent_accesssq_access_page);//更新fact中变量值
                        update(recentrecent_accesstemp_access_data);//更新fact中变量值
                        update(recentrecent_accesstemp_idea_data);//更新fact中变量值
                        update(recentrecent_accesstemp_ticket_data);//更新fact中变量值
            end

            //逻辑处理节点[获取工作项所属项目]
            rule "prepareparam5"
            ruleflow-group "recentrecent_accessprepareparam5"
            when
            then
                            recentrecent_accesstemp_access_data.set("recentparent",recentrecent_accessreturn_data.get("project_id"));
                            recentrecent_accesstemp_access_data.set("recentparentname",recentrecent_accessreturn_data.get("project_name"));
                        update(recentrecent_accessdefault);//更新fact中变量值
                        update(recentrecent_accessowner_id);//更新fact中变量值
                        update(recentrecent_accessrecent_access);//更新fact中变量值
                        update(recentrecent_accessreturn_data);//更新fact中变量值
                        update(recentrecent_accesssq_access_page);//更新fact中变量值
                        update(recentrecent_accesstemp_access_data);//更新fact中变量值
                        update(recentrecent_accesstemp_idea_data);//更新fact中变量值
                        update(recentrecent_accesstemp_ticket_data);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "recentrecent_accessend2"
            when
            then
                        update(recentrecent_accessdefault);//更新fact中变量值
                        update(recentrecent_accessowner_id);//更新fact中变量值
                        update(recentrecent_accessrecent_access);//更新fact中变量值
                        update(recentrecent_accessreturn_data);//更新fact中变量值
                        update(recentrecent_accesssq_access_page);//更新fact中变量值
                        update(recentrecent_accesstemp_access_data);//更新fact中变量值
                        update(recentrecent_accesstemp_idea_data);//更新fact中变量值
                        update(recentrecent_accesstemp_ticket_data);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "recentrecent_accessend1"
            when
            then
                        update(recentrecent_accessdefault);//更新fact中变量值
                        update(recentrecent_accessowner_id);//更新fact中变量值
                        update(recentrecent_accessrecent_access);//更新fact中变量值
                        update(recentrecent_accessreturn_data);//更新fact中变量值
                        update(recentrecent_accesssq_access_page);//更新fact中变量值
                        update(recentrecent_accesstemp_access_data);//更新fact中变量值
                        update(recentrecent_accesstemp_idea_data);//更新fact中变量值
                        update(recentrecent_accesstemp_ticket_data);//更新fact中变量值
            end

            //逻辑处理节点[附加到数组参数]
            rule "appendparam1"
            ruleflow-group "recentrecent_accessappendparam1"
            when
            then
                        update(recentrecent_accessdefault);//更新fact中变量值
                        update(recentrecent_accessowner_id);//更新fact中变量值
                        update(recentrecent_accessrecent_access);//更新fact中变量值
                        update(recentrecent_accessreturn_data);//更新fact中变量值
                        update(recentrecent_accesssq_access_page);//更新fact中变量值
                        update(recentrecent_accesstemp_access_data);//更新fact中变量值
                        update(recentrecent_accesstemp_idea_data);//更新fact中变量值
                        update(recentrecent_accesstemp_ticket_data);//更新fact中变量值
            end