package cn.ibizlab.plm.base.logic.portfoliologic.delete_project_set;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.portfolio portfoliodelete_project_setdefault;
                    global cn.ibizlab.plm.core.base.service.IportfolioService portfolioservice;
        global cn.ibizlab.plm.core.base.service.IportfolioService iBzSysPortfolioDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "portfoliodelete_project_setbegin"
            when
            then
            end

            //逻辑处理节点[设置删除状态]
            rule "prepareparam1"
            ruleflow-group "portfoliodelete_project_setprepareparam1"
            when
            then
                            portfoliodelete_project_setdefault.set("isdeleted","1");
                        update(portfoliodelete_project_setdefault);//更新fact中变量值
            end

            //逻辑处理节点[删除]
            rule "deaction1"
            ruleflow-group "portfoliodelete_project_setdeaction1"
            when
            then
                        portfolioservice.update(portfoliodelete_project_setdefault);
                        update(portfoliodelete_project_setdefault);//更新fact中变量值
            end