package cn.ibizlab.plm.base.logic.portfoliologic.favorite;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.Portfolio portfoliofavoritedefault;
                global java.util.Map portfoliofavoritectx;
                global cn.ibizlab.plm.core.base.domain.Favorite portfoliofavoritefavorite;
                    global cn.ibizlab.plm.core.base.service.IFavoriteService favoriteservice;
        global cn.ibizlab.plm.core.base.service.IPortfolioService iBzSysPortfolioDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "portfoliofavoritebegin"
            when
            then
            end

            //逻辑处理节点[填充用户标识和收藏业务对象标识]
            rule "prepareparam1"
            ruleflow-group "portfoliofavoriteprepareparam1"
            when
            then
                                portfoliofavoritefavorite.set("createman",curuser.getSessionParams().get("srfuserid"));
                            portfoliofavoritefavorite.set("ownertype","project_portfolio");
                            portfoliofavoritefavorite.set("ownerid",portfoliofavoritedefault.get("owner_id"));
                        update(portfoliofavoritedefault);//更新fact中变量值
                        update(portfoliofavoritectx);//更新fact中变量值
                        update(portfoliofavoritefavorite);//更新fact中变量值
            end

            //逻辑处理节点[生成收藏数据]
            rule "deaction1"
            ruleflow-group "portfoliofavoritedeaction1"
            when
            then
                        favoriteservice.save(portfoliofavoritefavorite);
                        update(portfoliofavoritedefault);//更新fact中变量值
                        update(portfoliofavoritectx);//更新fact中变量值
                        update(portfoliofavoritefavorite);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "portfoliofavoriteend1"
            when
            then
                        update(portfoliofavoritedefault);//更新fact中变量值
                        update(portfoliofavoritectx);//更新fact中变量值
                        update(portfoliofavoritefavorite);//更新fact中变量值
            end