package cn.ibizlab.plm.base.logic.portfoliologic.project_resource_member_setting;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.portfolio portfolioproject_resource_member_settingdefault;
                global cn.ibizlab.plm.core.base.domain.addon_resource portfolioproject_resource_member_settingaddon_resource;
                global cn.ibizlab.plm.core.projmgmt.domain.day_capacity portfolioproject_resource_member_settingday_capacity;
                global cn.ibizlab.plm.core.base.domain.member portfolioproject_resource_member_settingfor_choose_obj;
                global cn.ibizlab.plm.core.base.domain.member portfolioproject_resource_member_settingfor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.resource_member portfolioproject_resource_member_settinginsert_members;
                global cn.ibizlab.plm.core.base.domain.resource_member portfolioproject_resource_member_settingresource_member;
                global cn.ibizlab.plm.core.base.domain.resource_member portfolioproject_resource_member_settingresource_members;
                global cn.ibizlab.plm.core.base.domain.member portfolioproject_resource_member_settingsrfactionparam;
                    global cn.ibizlab.plm.core.base.service.Iaddon_resourceService addon_resourceservice;
        global cn.ibizlab.plm.core.base.service.IportfolioService iBzSysPortfolioDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "portfolioproject_resource_member_settingbegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "portfolioproject_resource_member_settingbindparam1"
            when
            then
                        update(portfolioproject_resource_member_settingdefault);//更新fact中变量值
                        update(portfolioproject_resource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioproject_resource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_member);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[获取资源组件标识]
            rule "rawsfcode1"
            ruleflow-group "portfolioproject_resource_member_settingrawsfcode1"
            when
            then
                        update(portfolioproject_resource_member_settingdefault);//更新fact中变量值
                        update(portfolioproject_resource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioproject_resource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_member);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[获取资源组件]
            rule "deaction1"
            ruleflow-group "portfolioproject_resource_member_settingdeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(addon_resourceservice.get(portfolioproject_resource_member_settingaddon_resource.getId()),portfolioproject_resource_member_settingaddon_resource);
                        update(portfolioproject_resource_member_settingdefault);//更新fact中变量值
                        update(portfolioproject_resource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioproject_resource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_member);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam2"
            ruleflow-group "portfolioproject_resource_member_settingbindparam2"
            when
            then
                        update(portfolioproject_resource_member_settingdefault);//更新fact中变量值
                        update(portfolioproject_resource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioproject_resource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_member);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall2"
            ruleflow-group "portfolioproject_resource_member_settingloopsubcall2"
            when
            then
                        update(portfolioproject_resource_member_settingdefault);//更新fact中变量值
                        update(portfolioproject_resource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioproject_resource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_member);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall3"
            ruleflow-group "portfolioproject_resource_member_settingloopsubcall3"
            when
            then
                        update(portfolioproject_resource_member_settingdefault);//更新fact中变量值
                        update(portfolioproject_resource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioproject_resource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_member);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam4"
            ruleflow-group "portfolioproject_resource_member_settingprepareparam4"
            when
            then
                        update(portfolioproject_resource_member_settingdefault);//更新fact中变量值
                        update(portfolioproject_resource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioproject_resource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_member);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[附加到数组参数]
            rule "appendparam2"
            ruleflow-group "portfolioproject_resource_member_settingappendparam2"
            when
            then
                        update(portfolioproject_resource_member_settingdefault);//更新fact中变量值
                        update(portfolioproject_resource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioproject_resource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_member);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "portfolioproject_resource_member_settingloopsubcall1"
            when
            then
                        update(portfolioproject_resource_member_settingdefault);//更新fact中变量值
                        update(portfolioproject_resource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioproject_resource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_member);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode4"
            ruleflow-group "portfolioproject_resource_member_settingrawsfcode4"
            when
            then
                        update(portfolioproject_resource_member_settingdefault);//更新fact中变量值
                        update(portfolioproject_resource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioproject_resource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_member);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "portfolioproject_resource_member_settingrenewparam1"
            when
            then
                        update(portfolioproject_resource_member_settingdefault);//更新fact中变量值
                        update(portfolioproject_resource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioproject_resource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_member);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[填充默认容量/工作日]
            rule "prepareparam1"
            ruleflow-group "portfolioproject_resource_member_settingprepareparam1"
            when
            then
                            portfolioproject_resource_member_settingresource_member.set("id",portfolioproject_resource_member_settingfor_choose_obj.get("userid"));
                            portfolioproject_resource_member_settingresource_member.set("addonid",portfolioproject_resource_member_settingaddon_resource.get("id"));
                            portfolioproject_resource_member_settingresource_member.set("name",portfolioproject_resource_member_settingfor_choose_obj.get("name"));
                            portfolioproject_resource_member_settingresource_member.set("userid",portfolioproject_resource_member_settingfor_choose_obj.get("userid"));
                            portfolioproject_resource_member_settingresource_member.set("weekday","1,2,3,4,5");
                            portfolioproject_resource_member_settingday_capacity.set("id",portfolioproject_resource_member_settingfor_choose_obj.get("userid"));
                            portfolioproject_resource_member_settingday_capacity.set("workitemcount","3");
                            portfolioproject_resource_member_settingday_capacity.set("estimatedworkload","8");
                            portfolioproject_resource_member_settingday_capacity.set("remainingworkload","1");
                            portfolioproject_resource_member_settingday_capacity.set("storypoints","2");
                        update(portfolioproject_resource_member_settingdefault);//更新fact中变量值
                        update(portfolioproject_resource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioproject_resource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_member);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[资源成员绑定容量属性]
            rule "rawsfcode2"
            ruleflow-group "portfolioproject_resource_member_settingrawsfcode2"
            when
            then
                        update(portfolioproject_resource_member_settingdefault);//更新fact中变量值
                        update(portfolioproject_resource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioproject_resource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_member);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[附加到数组参数]
            rule "appendparam1"
            ruleflow-group "portfolioproject_resource_member_settingappendparam1"
            when
            then
                        update(portfolioproject_resource_member_settingdefault);//更新fact中变量值
                        update(portfolioproject_resource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioproject_resource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_member);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[资源成员绑定至组件]
            rule "rawsfcode3"
            ruleflow-group "portfolioproject_resource_member_settingrawsfcode3"
            when
            then
                        update(portfolioproject_resource_member_settingdefault);//更新fact中变量值
                        update(portfolioproject_resource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioproject_resource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_member);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[保存资源成员]
            rule "deaction2"
            ruleflow-group "portfolioproject_resource_member_settingdeaction2"
            when
            then
                        addon_resourceservice.update(portfolioproject_resource_member_settingaddon_resource);
                        update(portfolioproject_resource_member_settingdefault);//更新fact中变量值
                        update(portfolioproject_resource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioproject_resource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioproject_resource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_member);//更新fact中变量值
                        update(portfolioproject_resource_member_settingresource_members);//更新fact中变量值
                        update(portfolioproject_resource_member_settingsrfactionparam);//更新fact中变量值
            end