package cn.ibizlab.plm.base.logic.portfoliologic.recover_project_set;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.portfolio portfoliorecover_project_setdefault;
                    global cn.ibizlab.plm.core.base.service.IportfolioService portfolioservice;
        global cn.ibizlab.plm.core.base.service.IportfolioService iBzSysPortfolioDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "portfoliorecover_project_setbegin"
            when
            then
            end

            //逻辑处理节点[恢复状态]
            rule "prepareparam1"
            ruleflow-group "portfoliorecover_project_setprepareparam1"
            when
            then
                            portfoliorecover_project_setdefault.set("isdeleted","0");
                        update(portfoliorecover_project_setdefault);//更新fact中变量值
            end

            //逻辑处理节点[恢复]
            rule "deaction1"
            ruleflow-group "portfoliorecover_project_setdeaction1"
            when
            then
                        portfolioservice.update(portfoliorecover_project_setdefault);
                        update(portfoliorecover_project_setdefault);//更新fact中变量值
            end