package cn.ibizlab.plm.base.logic.portfoliologic.resource_member_setting;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.portfolio portfolioresource_member_settingdefault;
                global cn.ibizlab.plm.core.base.domain.addon_resource portfolioresource_member_settingaddon_resource;
                global cn.ibizlab.plm.core.base.domain.addon_resource portfolioresource_member_settingaddon_resource_filter;
                global cn.ibizlab.plm.core.base.domain.addon_resource portfolioresource_member_settingaddon_resource_page;
                global cn.ibizlab.plm.core.projmgmt.domain.day_capacity portfolioresource_member_settingday_capacity;
                global cn.ibizlab.plm.core.base.domain.member portfolioresource_member_settingfor_choose_obj;
                global cn.ibizlab.plm.core.base.domain.member portfolioresource_member_settingfor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.resource_member portfolioresource_member_settinginsert_members;
                global cn.ibizlab.plm.core.base.domain.resource_member portfolioresource_member_settingresource_member;
                global cn.ibizlab.plm.core.base.domain.resource_member portfolioresource_member_settingresource_members;
                global cn.ibizlab.plm.core.base.domain.member portfolioresource_member_settingsrfactionparam;
                    global cn.ibizlab.plm.core.base.service.Iaddon_resourceService addon_resourceservice;
        global cn.ibizlab.plm.core.base.service.IportfolioService iBzSysPortfolioDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "portfolioresource_member_settingbegin"
            when
            then
            end

            //逻辑处理节点[绑定srfactionparam参数]
            rule "bindparam1"
            ruleflow-group "portfolioresource_member_settingbindparam1"
            when
            then
                        update(portfolioresource_member_settingdefault);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_filter);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_page);//更新fact中变量值
                        update(portfolioresource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioresource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioresource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioresource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioresource_member_settingresource_member);//更新fact中变量值
                        update(portfolioresource_member_settingresource_members);//更新fact中变量值
                        update(portfolioresource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[设置资源组件查询过滤器参数]
            rule "prepareparam3"
            ruleflow-group "portfolioresource_member_settingprepareparam3"
            when
            then
                            portfolioresource_member_settingaddon_resource_filter.set("n_owner_id_eq",portfolioresource_member_settingdefault.get("portfolio_id"));
                            portfolioresource_member_settingaddon_resource_filter.set("n_owner_type_eq","portfolio");
                            portfolioresource_member_settingaddon_resource_filter.set("n_addon_type_eq","resource");
                        update(portfolioresource_member_settingdefault);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_filter);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_page);//更新fact中变量值
                        update(portfolioresource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioresource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioresource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioresource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioresource_member_settingresource_member);//更新fact中变量值
                        update(portfolioresource_member_settingresource_members);//更新fact中变量值
                        update(portfolioresource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[获取此项目集下的资源组件]
            rule "dedataset1"
            ruleflow-group "portfolioresource_member_settingdedataset1"
            when
            then
                        update(portfolioresource_member_settingdefault);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_filter);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_page);//更新fact中变量值
                        update(portfolioresource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioresource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioresource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioresource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioresource_member_settingresource_member);//更新fact中变量值
                        update(portfolioresource_member_settingresource_members);//更新fact中变量值
                        update(portfolioresource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[绑定资源组件]
            rule "bindparam3"
            ruleflow-group "portfolioresource_member_settingbindparam3"
            when
            then
                        update(portfolioresource_member_settingdefault);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_filter);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_page);//更新fact中变量值
                        update(portfolioresource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioresource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioresource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioresource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioresource_member_settingresource_member);//更新fact中变量值
                        update(portfolioresource_member_settingresource_members);//更新fact中变量值
                        update(portfolioresource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[绑定成员参数]
            rule "bindparam2"
            ruleflow-group "portfolioresource_member_settingbindparam2"
            when
            then
                        update(portfolioresource_member_settingdefault);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_filter);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_page);//更新fact中变量值
                        update(portfolioresource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioresource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioresource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioresource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioresource_member_settingresource_member);//更新fact中变量值
                        update(portfolioresource_member_settingresource_members);//更新fact中变量值
                        update(portfolioresource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall2"
            ruleflow-group "portfolioresource_member_settingloopsubcall2"
            when
            then
                        update(portfolioresource_member_settingdefault);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_filter);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_page);//更新fact中变量值
                        update(portfolioresource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioresource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioresource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioresource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioresource_member_settingresource_member);//更新fact中变量值
                        update(portfolioresource_member_settingresource_members);//更新fact中变量值
                        update(portfolioresource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall3"
            ruleflow-group "portfolioresource_member_settingloopsubcall3"
            when
            then
                        update(portfolioresource_member_settingdefault);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_filter);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_page);//更新fact中变量值
                        update(portfolioresource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioresource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioresource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioresource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioresource_member_settingresource_member);//更新fact中变量值
                        update(portfolioresource_member_settingresource_members);//更新fact中变量值
                        update(portfolioresource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[空节点（为了增加条件判断）]
            rule "prepareparam4"
            ruleflow-group "portfolioresource_member_settingprepareparam4"
            when
            then
                        update(portfolioresource_member_settingdefault);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_filter);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_page);//更新fact中变量值
                        update(portfolioresource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioresource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioresource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioresource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioresource_member_settingresource_member);//更新fact中变量值
                        update(portfolioresource_member_settingresource_members);//更新fact中变量值
                        update(portfolioresource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[附加到数组参数]
            rule "appendparam2"
            ruleflow-group "portfolioresource_member_settingappendparam2"
            when
            then
                        update(portfolioresource_member_settingdefault);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_filter);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_page);//更新fact中变量值
                        update(portfolioresource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioresource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioresource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioresource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioresource_member_settingresource_member);//更新fact中变量值
                        update(portfolioresource_member_settingresource_members);//更新fact中变量值
                        update(portfolioresource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "portfolioresource_member_settingloopsubcall1"
            when
            then
                        update(portfolioresource_member_settingdefault);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_filter);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_page);//更新fact中变量值
                        update(portfolioresource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioresource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioresource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioresource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioresource_member_settingresource_member);//更新fact中变量值
                        update(portfolioresource_member_settingresource_members);//更新fact中变量值
                        update(portfolioresource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[判断此成员是否已加入资源]
            rule "rawsfcode4"
            ruleflow-group "portfolioresource_member_settingrawsfcode4"
            when
            then
                        update(portfolioresource_member_settingdefault);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_filter);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_page);//更新fact中变量值
                        update(portfolioresource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioresource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioresource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioresource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioresource_member_settingresource_member);//更新fact中变量值
                        update(portfolioresource_member_settingresource_members);//更新fact中变量值
                        update(portfolioresource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "portfolioresource_member_settingrenewparam1"
            when
            then
                        update(portfolioresource_member_settingdefault);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_filter);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_page);//更新fact中变量值
                        update(portfolioresource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioresource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioresource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioresource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioresource_member_settingresource_member);//更新fact中变量值
                        update(portfolioresource_member_settingresource_members);//更新fact中变量值
                        update(portfolioresource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[填充默认容量/工作日]
            rule "prepareparam1"
            ruleflow-group "portfolioresource_member_settingprepareparam1"
            when
            then
                            portfolioresource_member_settingresource_member.set("id",portfolioresource_member_settingfor_choose_obj.get("userid"));
                            portfolioresource_member_settingresource_member.set("addonid",portfolioresource_member_settingaddon_resource.get("id"));
                            portfolioresource_member_settingresource_member.set("name",portfolioresource_member_settingfor_choose_obj.get("name"));
                            portfolioresource_member_settingresource_member.set("userid",portfolioresource_member_settingfor_choose_obj.get("userid"));
                            portfolioresource_member_settingresource_member.set("weekday","1,2,3,4,5");
                            portfolioresource_member_settingday_capacity.set("id",portfolioresource_member_settingfor_choose_obj.get("userid"));
                            portfolioresource_member_settingday_capacity.set("workitemcount","3");
                            portfolioresource_member_settingday_capacity.set("estimatedworkload","8");
                            portfolioresource_member_settingday_capacity.set("remainingworkload","1");
                            portfolioresource_member_settingday_capacity.set("storypoints","2");
                        update(portfolioresource_member_settingdefault);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_filter);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_page);//更新fact中变量值
                        update(portfolioresource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioresource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioresource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioresource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioresource_member_settingresource_member);//更新fact中变量值
                        update(portfolioresource_member_settingresource_members);//更新fact中变量值
                        update(portfolioresource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[资源成员绑定容量属性]
            rule "rawsfcode2"
            ruleflow-group "portfolioresource_member_settingrawsfcode2"
            when
            then
                        update(portfolioresource_member_settingdefault);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_filter);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_page);//更新fact中变量值
                        update(portfolioresource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioresource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioresource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioresource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioresource_member_settingresource_member);//更新fact中变量值
                        update(portfolioresource_member_settingresource_members);//更新fact中变量值
                        update(portfolioresource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[附加到数组参数]
            rule "appendparam1"
            ruleflow-group "portfolioresource_member_settingappendparam1"
            when
            then
                        update(portfolioresource_member_settingdefault);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_filter);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_page);//更新fact中变量值
                        update(portfolioresource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioresource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioresource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioresource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioresource_member_settingresource_member);//更新fact中变量值
                        update(portfolioresource_member_settingresource_members);//更新fact中变量值
                        update(portfolioresource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[资源成员绑定至组件]
            rule "rawsfcode3"
            ruleflow-group "portfolioresource_member_settingrawsfcode3"
            when
            then
                        update(portfolioresource_member_settingdefault);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_filter);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_page);//更新fact中变量值
                        update(portfolioresource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioresource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioresource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioresource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioresource_member_settingresource_member);//更新fact中变量值
                        update(portfolioresource_member_settingresource_members);//更新fact中变量值
                        update(portfolioresource_member_settingsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[保存资源成员]
            rule "deaction2"
            ruleflow-group "portfolioresource_member_settingdeaction2"
            when
            then
                        addon_resourceservice.update(portfolioresource_member_settingaddon_resource);
                        update(portfolioresource_member_settingdefault);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_filter);//更新fact中变量值
                        update(portfolioresource_member_settingaddon_resource_page);//更新fact中变量值
                        update(portfolioresource_member_settingday_capacity);//更新fact中变量值
                        update(portfolioresource_member_settingfor_choose_obj);//更新fact中变量值
                        update(portfolioresource_member_settingfor_temp_obj);//更新fact中变量值
                        update(portfolioresource_member_settinginsert_members);//更新fact中变量值
                        update(portfolioresource_member_settingresource_member);//更新fact中变量值
                        update(portfolioresource_member_settingresource_members);//更新fact中变量值
                        update(portfolioresource_member_settingsrfactionparam);//更新fact中变量值
            end