package cn.ibizlab.plm.base.logic.login_loglogic.calc_active_chart_datas;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.login_log login_logcalc_active_chart_datasdefault;
                global cn.ibizlab.plm.core.base.domain.login_log login_logcalc_active_chart_datasechart_obj;
                global cn.ibizlab.plm.core.base.domain.login_log login_logcalc_active_chart_datasechart_page;
                global java.util.Map login_logcalc_active_chart_datasendtime;
                global java.util.Map login_logcalc_active_chart_datasstarttime;
                global cn.ibizlab.plm.core.base.domain.user login_logcalc_active_chart_datasuser_filter;
                global cn.ibizlab.plm.core.base.domain.user login_logcalc_active_chart_datasuser_page;
                global cn.ibizlab.plm.core.base.domain.user login_logcalc_active_chart_datasuser_total;
                    global cn.ibizlab.plm.core.base.service.IuserService userservice;
                    global cn.ibizlab.plm.core.base.service.Ilogin_logService login_logservice;
        global cn.ibizlab.plm.core.base.service.Ilogin_logService iBzSysLogin_logDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "login_logcalc_active_chart_datasbegin"
            when
            then
            end

            //逻辑处理节点[计算前15天和今天的日期]
            rule "rawsfcode1"
            ruleflow-group "login_logcalc_active_chart_datasrawsfcode1"
            when
            then
                        update(login_logcalc_active_chart_datasdefault);//更新fact中变量值
                        update(login_logcalc_active_chart_datasechart_obj);//更新fact中变量值
                        update(login_logcalc_active_chart_datasechart_page);//更新fact中变量值
                        update(login_logcalc_active_chart_datasendtime);//更新fact中变量值
                        update(login_logcalc_active_chart_datasstarttime);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_filter);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_page);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_total);//更新fact中变量值
            end

            //逻辑处理节点[准备日期过滤参数]
            rule "prepareparam1"
            ruleflow-group "login_logcalc_active_chart_datasprepareparam1"
            when
            then
                            login_logcalc_active_chart_datasdefault.set("n_authtime_gtandeq",login_logcalc_active_chart_datasstarttime.get(""));
                            login_logcalc_active_chart_datasdefault.set("n_authtime_ltandeq",login_logcalc_active_chart_datasendtime.get(""));
                            login_logcalc_active_chart_datasuser_filter.set("size","1");
                        update(login_logcalc_active_chart_datasdefault);//更新fact中变量值
                        update(login_logcalc_active_chart_datasechart_obj);//更新fact中变量值
                        update(login_logcalc_active_chart_datasechart_page);//更新fact中变量值
                        update(login_logcalc_active_chart_datasendtime);//更新fact中变量值
                        update(login_logcalc_active_chart_datasstarttime);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_filter);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_page);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_total);//更新fact中变量值
            end

            //逻辑处理节点[查询活跃总人数]
            rule "dedataset2"
            ruleflow-group "login_logcalc_active_chart_datasdedataset2"
            when
            then
                        update(login_logcalc_active_chart_datasdefault);//更新fact中变量值
                        update(login_logcalc_active_chart_datasechart_obj);//更新fact中变量值
                        update(login_logcalc_active_chart_datasechart_page);//更新fact中变量值
                        update(login_logcalc_active_chart_datasendtime);//更新fact中变量值
                        update(login_logcalc_active_chart_datasstarttime);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_filter);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_page);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_total);//更新fact中变量值
            end

            //逻辑处理节点[赋值活跃总人数]
            rule "prepareparam2"
            ruleflow-group "login_logcalc_active_chart_datasprepareparam2"
            when
            then
                            login_logcalc_active_chart_datasuser_total.set("total",login_logcalc_active_chart_datasuser_page.get("total"));
                        update(login_logcalc_active_chart_datasdefault);//更新fact中变量值
                        update(login_logcalc_active_chart_datasechart_obj);//更新fact中变量值
                        update(login_logcalc_active_chart_datasechart_page);//更新fact中变量值
                        update(login_logcalc_active_chart_datasendtime);//更新fact中变量值
                        update(login_logcalc_active_chart_datasstarttime);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_filter);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_page);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_total);//更新fact中变量值
            end

            //逻辑处理节点[获取图表默认数据]
            rule "dedataset1"
            ruleflow-group "login_logcalc_active_chart_datasdedataset1"
            when
            then
                        update(login_logcalc_active_chart_datasdefault);//更新fact中变量值
                        update(login_logcalc_active_chart_datasechart_obj);//更新fact中变量值
                        update(login_logcalc_active_chart_datasechart_page);//更新fact中变量值
                        update(login_logcalc_active_chart_datasendtime);//更新fact中变量值
                        update(login_logcalc_active_chart_datasstarttime);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_filter);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_page);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_total);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "login_logcalc_active_chart_datasloopsubcall1"
            when
            then
                        update(login_logcalc_active_chart_datasdefault);//更新fact中变量值
                        update(login_logcalc_active_chart_datasechart_obj);//更新fact中变量值
                        update(login_logcalc_active_chart_datasechart_page);//更新fact中变量值
                        update(login_logcalc_active_chart_datasendtime);//更新fact中变量值
                        update(login_logcalc_active_chart_datasstarttime);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_filter);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_page);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_total);//更新fact中变量值
            end

            //逻辑处理节点[计算图表所需数据]
            rule "rawsfcode2"
            ruleflow-group "login_logcalc_active_chart_datasrawsfcode2"
            when
            then
                        update(login_logcalc_active_chart_datasdefault);//更新fact中变量值
                        update(login_logcalc_active_chart_datasechart_obj);//更新fact中变量值
                        update(login_logcalc_active_chart_datasechart_page);//更新fact中变量值
                        update(login_logcalc_active_chart_datasendtime);//更新fact中变量值
                        update(login_logcalc_active_chart_datasstarttime);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_filter);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_page);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_total);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "login_logcalc_active_chart_datasend1"
            when
            then
                        update(login_logcalc_active_chart_datasdefault);//更新fact中变量值
                        update(login_logcalc_active_chart_datasechart_obj);//更新fact中变量值
                        update(login_logcalc_active_chart_datasechart_page);//更新fact中变量值
                        update(login_logcalc_active_chart_datasendtime);//更新fact中变量值
                        update(login_logcalc_active_chart_datasstarttime);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_filter);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_page);//更新fact中变量值
                        update(login_logcalc_active_chart_datasuser_total);//更新fact中变量值
            end