package cn.ibizlab.plm.base.logic.login_loglogic.calc_active_member_info;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.login_log login_logcalc_active_member_infodefault;
                global cn.ibizlab.plm.core.base.domain.login_log login_logcalc_active_member_infodatas;
                global cn.ibizlab.plm.core.base.domain.login_log login_logcalc_active_member_infolast_active_members;
                global java.util.Map login_logcalc_active_member_infolast_day_endtime;
                global java.util.Map login_logcalc_active_member_infolast_day_starttime;
                global cn.ibizlab.plm.core.base.domain.login_log login_logcalc_active_member_infologin_log_filter;
                global cn.ibizlab.plm.core.base.domain.login_log login_logcalc_active_member_infologin_log_obj;
                global cn.ibizlab.plm.core.base.domain.login_log login_logcalc_active_member_infologin_log_page;
                global cn.ibizlab.plm.core.base.domain.login_log login_logcalc_active_member_infoseven_active_members;
                global java.util.Map login_logcalc_active_member_infoseven_day_endtime;
                global java.util.Map login_logcalc_active_member_infoseven_day_starttime;
                global cn.ibizlab.plm.core.base.domain.user login_logcalc_active_member_infouser_filter;
                global cn.ibizlab.plm.core.base.domain.login_log login_logcalc_active_member_infouser_page;
                    global cn.ibizlab.plm.core.base.service.IuserService userservice;
                    global cn.ibizlab.plm.core.base.service.Ilogin_logService login_logservice;
        global cn.ibizlab.plm.core.base.service.Ilogin_logService iBzSysLogin_logDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "login_logcalc_active_member_infobegin"
            when
            then
            end

            //逻辑处理节点[准备用户过滤器参数]
            rule "prepareparam1"
            ruleflow-group "login_logcalc_active_member_infoprepareparam1"
            when
            then
                            login_logcalc_active_member_infouser_filter.set("size","1");
                        update(login_logcalc_active_member_infodefault);//更新fact中变量值
                        update(login_logcalc_active_member_infodatas);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_obj);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_page);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_page);//更新fact中变量值
            end

            //逻辑处理节点[查询活跃总人数]
            rule "dedataset1"
            ruleflow-group "login_logcalc_active_member_infodedataset1"
            when
            then
                        update(login_logcalc_active_member_infodefault);//更新fact中变量值
                        update(login_logcalc_active_member_infodatas);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_obj);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_page);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "login_logcalc_active_member_infoloopsubcall1"
            when
            then
                        update(login_logcalc_active_member_infodefault);//更新fact中变量值
                        update(login_logcalc_active_member_infodatas);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_obj);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_page);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_page);//更新fact中变量值
            end

            //逻辑处理节点[查询昨日活跃人数]
            rule "dedataset2"
            ruleflow-group "login_logcalc_active_member_infodedataset2"
            when
            then
                        update(login_logcalc_active_member_infodefault);//更新fact中变量值
                        update(login_logcalc_active_member_infodatas);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_obj);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_page);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_page);//更新fact中变量值
            end

            //逻辑处理节点[准备日志过滤参数]
            rule "prepareparam3"
            ruleflow-group "login_logcalc_active_member_infoprepareparam3"
            when
            then
                            login_logcalc_active_member_infologin_log_filter.set("n_authtime_gtandeq",login_logcalc_active_member_infolast_day_starttime.get(""));
                            login_logcalc_active_member_infologin_log_filter.set("n_authtime_ltandeq",login_logcalc_active_member_infolast_day_endtime.get(""));
                        update(login_logcalc_active_member_infodefault);//更新fact中变量值
                        update(login_logcalc_active_member_infodatas);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_obj);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_page);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_page);//更新fact中变量值
            end

            //逻辑处理节点[准备昨日活跃总人数]
            rule "prepareparam4"
            ruleflow-group "login_logcalc_active_member_infoprepareparam4"
            when
            then
                            login_logcalc_active_member_infolast_active_members.set("activemembers",login_logcalc_active_member_infologin_log_obj.get("activemembers"));
                        update(login_logcalc_active_member_infodefault);//更新fact中变量值
                        update(login_logcalc_active_member_infodatas);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_obj);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_page);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_page);//更新fact中变量值
            end

            //逻辑处理节点[ 准备昨日开始结束时间]
            rule "rawsfcode1"
            ruleflow-group "login_logcalc_active_member_inforawsfcode1"
            when
            then
                        update(login_logcalc_active_member_infodefault);//更新fact中变量值
                        update(login_logcalc_active_member_infodatas);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_obj);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_page);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_page);//更新fact中变量值
            end

            //逻辑处理节点[重置过滤器]
            rule "renewparam1"
            ruleflow-group "login_logcalc_active_member_inforenewparam1"
            when
            then
                        update(login_logcalc_active_member_infodefault);//更新fact中变量值
                        update(login_logcalc_active_member_infodatas);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_obj);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_page);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_page);//更新fact中变量值
            end

            //逻辑处理节点[重置分页结果变量]
            rule "renewparam2"
            ruleflow-group "login_logcalc_active_member_inforenewparam2"
            when
            then
                        update(login_logcalc_active_member_infodefault);//更新fact中变量值
                        update(login_logcalc_active_member_infodatas);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_obj);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_page);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_page);//更新fact中变量值
            end

            //逻辑处理节点[重置结果变量]
            rule "renewparam3"
            ruleflow-group "login_logcalc_active_member_inforenewparam3"
            when
            then
                        update(login_logcalc_active_member_infodefault);//更新fact中变量值
                        update(login_logcalc_active_member_infodatas);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_obj);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_page);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_page);//更新fact中变量值
            end

            //逻辑处理节点[准备近七日开始结束时间]
            rule "rawsfcode3"
            ruleflow-group "login_logcalc_active_member_inforawsfcode3"
            when
            then
                        update(login_logcalc_active_member_infodefault);//更新fact中变量值
                        update(login_logcalc_active_member_infodatas);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_obj);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_page);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_page);//更新fact中变量值
            end

            //逻辑处理节点[准备近七日活跃总人数]
            rule "prepareparam6"
            ruleflow-group "login_logcalc_active_member_infoprepareparam6"
            when
            then
                            login_logcalc_active_member_infoseven_active_members.set("activemembers",login_logcalc_active_member_infologin_log_obj.get("activemembers"));
                        update(login_logcalc_active_member_infodefault);//更新fact中变量值
                        update(login_logcalc_active_member_infodatas);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_obj);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_page);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall2"
            ruleflow-group "login_logcalc_active_member_infoloopsubcall2"
            when
            then
                        update(login_logcalc_active_member_infodefault);//更新fact中变量值
                        update(login_logcalc_active_member_infodatas);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_obj);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_page);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_page);//更新fact中变量值
            end

            //逻辑处理节点[查询近七日活跃人数]
            rule "dedataset3"
            ruleflow-group "login_logcalc_active_member_infodedataset3"
            when
            then
                        update(login_logcalc_active_member_infodefault);//更新fact中变量值
                        update(login_logcalc_active_member_infodatas);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_obj);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_page);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_page);//更新fact中变量值
            end

            //逻辑处理节点[准备日志过滤参数]
            rule "prepareparam5"
            ruleflow-group "login_logcalc_active_member_infoprepareparam5"
            when
            then
                            login_logcalc_active_member_infologin_log_filter.set("n_authtime_gtandeq",login_logcalc_active_member_infoseven_day_starttime.get(""));
                            login_logcalc_active_member_infologin_log_filter.set("n_authtime_ltandeq",login_logcalc_active_member_infoseven_day_endtime.get(""));
                        update(login_logcalc_active_member_infodefault);//更新fact中变量值
                        update(login_logcalc_active_member_infodatas);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_obj);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_page);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_page);//更新fact中变量值
            end

            //逻辑处理节点[赋值活跃总人数]
            rule "prepareparam2"
            ruleflow-group "login_logcalc_active_member_infoprepareparam2"
            when
            then
                            login_logcalc_active_member_infodatas.set("active_count",login_logcalc_active_member_infouser_page.get("total"));
                        update(login_logcalc_active_member_infodefault);//更新fact中变量值
                        update(login_logcalc_active_member_infodatas);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_obj);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_page);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_page);//更新fact中变量值
            end

            //逻辑处理节点[赋值昨日和近七日活跃人数、活跃率]
            rule "rawsfcode2"
            ruleflow-group "login_logcalc_active_member_inforawsfcode2"
            when
            then
                        update(login_logcalc_active_member_infodefault);//更新fact中变量值
                        update(login_logcalc_active_member_infodatas);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_obj);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_page);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "login_logcalc_active_member_infoend1"
            when
            then
                        update(login_logcalc_active_member_infodefault);//更新fact中变量值
                        update(login_logcalc_active_member_infodatas);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infolast_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_obj);//更新fact中变量值
                        update(login_logcalc_active_member_infologin_log_page);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_active_members);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_endtime);//更新fact中变量值
                        update(login_logcalc_active_member_infoseven_day_starttime);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_filter);//更新fact中变量值
                        update(login_logcalc_active_member_infouser_page);//更新fact中变量值
            end