global cn.ibizlab.plm.core.extension.service.IPSDEFieldService  psdefieldService;
global cn.ibizlab.plm.core.extension.domain.PSDEField et;

    no-loop

    rule "psdefieldapply"
    ruleflow-group "B42DF4D0-B8D8-4CCD-99E4-2F5ADB1CF736"
    when
    then
    cn.ibizlab.plm.core.extension.domain.PSDEField actionLogicDE =new cn.ibizlab.plm.core.extension.domain.PSDEField();
    et.copyTo(actionLogicDE,true);
    psdefieldService.apply(actionLogicDE);
    end