global cn.ibizlab.plm.core.extension.service.IPSDEFieldService  psdefieldService;
global cn.ibizlab.plm.core.extension.domain.PSDEField et;

    no-loop

    rule "psdefieldapply"
    ruleflow-group "DB886AE9-9AC9-4584-A20A-168EF93F35D7"
    when
    then
    cn.ibizlab.plm.core.extension.domain.PSDEField actionLogicDE =new cn.ibizlab.plm.core.extension.domain.PSDEField();
    et.copyTo(actionLogicDE,true);
    psdefieldService.apply(actionLogicDE);
    end