global cn.ibizlab.plm.core.projmgmt.service.IVersionService  versionService;
global cn.ibizlab.plm.core.wiki.domain.Article_page et;

    no-loop

    rule "versioncommit"
    ruleflow-group "C3554A23-6A76-4031-8F8E-69C412E618FF"
    when
    then
    cn.ibizlab.plm.core.projmgmt.domain.Version actionLogicDE =new cn.ibizlab.plm.core.projmgmt.domain.Version();
    et.copyTo(actionLogicDE,true);
    versionService.commit(actionLogicDE);
    end