global cn.ibizlab.plm.core.projmgmt.service.IVersionService  versionService;
global cn.ibizlab.plm.core.wiki.domain.Article_page et;

    no-loop

    rule "versioncommit"
    ruleflow-group "420BF477-6780-4901-A8EE-066C56DBCF81"
    when
    then
    cn.ibizlab.plm.core.projmgmt.domain.Version actionLogicDE =new cn.ibizlab.plm.core.projmgmt.domain.Version();
    et.copyTo(actionLogicDE,true);
    versionService.commit(actionLogicDE);
    end