package cn.ibizlab.plm.projmgmt.logic.sprintlogic.start_sprint;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Sprint sprintstart_sprintdefault;
                    global cn.ibizlab.plm.core.projmgmt.service.ISprintService sprintservice;
        global cn.ibizlab.plm.core.projmgmt.service.ISprintService iBzSysSprintDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "sprintstart_sprintbegin"
            when
            then
            end

            //逻辑处理节点[设置迭代状态（进行中）]
            rule "prepareparam1"
            ruleflow-group "sprintstart_sprintprepareparam1"
            when
            then
                            sprintstart_sprintdefault.set("status","2");
                        update(sprintstart_sprintdefault);//更新fact中变量值
            end

            //逻辑处理节点[更新迭代状态]
            rule "deaction1"
            ruleflow-group "sprintstart_sprintdeaction1"
            when
            then
                        sprintservice.update(sprintstart_sprintdefault);
                        update(sprintstart_sprintdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "sprintstart_sprintend1"
            when
            then
                        update(sprintstart_sprintdefault);//更新fact中变量值
            end