package cn.ibizlab.plm.testmgmt.logic.guidelinelogic.fill_stage_order;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.guideline guidelinefill_stage_orderdefault;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage guidelinefill_stage_orderfor_stage;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage guidelinefill_stage_orderstage_arr;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage guidelinefill_stage_orderstage_list;
        global cn.ibizlab.plm.core.testmgmt.service.IguidelineService iBzSysGuidelineDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "guidelinefill_stage_orderbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "guidelinefill_stage_orderend1"
            when
            then
                        update(guidelinefill_stage_orderdefault);//更新fact中变量值
                        update(guidelinefill_stage_orderfor_stage);//更新fact中变量值
                        update(guidelinefill_stage_orderstage_arr);//更新fact中变量值
                        update(guidelinefill_stage_orderstage_list);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "guidelinefill_stage_orderprepareparam1"
            when
            then
                            guidelinefill_stage_orderstage_list.set("",guidelinefill_stage_orderdefault.get("reviewstage"));
                        update(guidelinefill_stage_orderdefault);//更新fact中变量值
                        update(guidelinefill_stage_orderfor_stage);//更新fact中变量值
                        update(guidelinefill_stage_orderstage_arr);//更新fact中变量值
                        update(guidelinefill_stage_orderstage_list);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "guidelinefill_stage_orderloopsubcall1"
            when
            then
                        update(guidelinefill_stage_orderdefault);//更新fact中变量值
                        update(guidelinefill_stage_orderfor_stage);//更新fact中变量值
                        update(guidelinefill_stage_orderstage_arr);//更新fact中变量值
                        update(guidelinefill_stage_orderstage_list);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam3"
            ruleflow-group "guidelinefill_stage_orderprepareparam3"
            when
            then
                            guidelinefill_stage_orderdefault.set("reviewstage",guidelinefill_stage_orderstage_arr.get(""));
                        update(guidelinefill_stage_orderdefault);//更新fact中变量值
                        update(guidelinefill_stage_orderfor_stage);//更新fact中变量值
                        update(guidelinefill_stage_orderstage_arr);//更新fact中变量值
                        update(guidelinefill_stage_orderstage_list);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam2"
            ruleflow-group "guidelinefill_stage_orderdebugparam2"
            when
            then
                        update(guidelinefill_stage_orderdefault);//更新fact中变量值
                        update(guidelinefill_stage_orderfor_stage);//更新fact中变量值
                        update(guidelinefill_stage_orderstage_arr);//更新fact中变量值
                        update(guidelinefill_stage_orderstage_list);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "guidelinefill_stage_orderprepareparam2"
            when
            then
                            guidelinefill_stage_orderfor_stage.set("order",guidelinefill_stage_orderfor_stage.get("srfordervalue"));
                            guidelinefill_stage_orderstage_arr.set("",guidelinefill_stage_orderfor_stage.get(""));
                        update(guidelinefill_stage_orderdefault);//更新fact中变量值
                        update(guidelinefill_stage_orderfor_stage);//更新fact中变量值
                        update(guidelinefill_stage_orderstage_arr);//更新fact中变量值
                        update(guidelinefill_stage_orderstage_list);//更新fact中变量值
            end