package cn.ibizlab.plm.projmgmt.logic.releaselogic.change_draft;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.release releasechange_draftdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.stage releasechange_draftcurrent_stage;
                global cn.ibizlab.plm.core.projmgmt.domain.stage releasechange_draftfirst_stage;
                global cn.ibizlab.plm.core.projmgmt.domain.stage releasechange_draftlast_stage;
                global cn.ibizlab.plm.core.projmgmt.domain.stage releasechange_draftstage_filter;
                global cn.ibizlab.plm.core.projmgmt.domain.stage releasechange_draftstage_transitions;
                global cn.ibizlab.plm.core.projmgmt.domain.stage releasechange_draftstages;
                global cn.ibizlab.plm.core.projmgmt.domain.stage releasechange_drafttarget_stage;
                    global cn.ibizlab.plm.core.projmgmt.service.IstageService stageservice;
        global cn.ibizlab.plm.core.projmgmt.service.IreleaseService iBzSysReleaseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "releasechange_draftbegin"
            when
            then
            end

            //逻辑处理节点[设置阶段查询过滤器参数]
            rule "prepareparam1"
            ruleflow-group "releasechange_draftprepareparam1"
            when
            then
                            releasechange_draftstage_filter.set("release",releasechange_draftdefault.get("release"));
                        update(releasechange_draftdefault);//更新fact中变量值
                        update(releasechange_draftcurrent_stage);//更新fact中变量值
                        update(releasechange_draftfirst_stage);//更新fact中变量值
                        update(releasechange_draftlast_stage);//更新fact中变量值
                        update(releasechange_draftstage_filter);//更新fact中变量值
                        update(releasechange_draftstage_transitions);//更新fact中变量值
                        update(releasechange_draftstages);//更新fact中变量值
                        update(releasechange_drafttarget_stage);//更新fact中变量值
            end

            //逻辑处理节点[获取阶段列表]
            rule "dedataset1"
            ruleflow-group "releasechange_draftdedataset1"
            when
            then
                        update(releasechange_draftdefault);//更新fact中变量值
                        update(releasechange_draftcurrent_stage);//更新fact中变量值
                        update(releasechange_draftfirst_stage);//更新fact中变量值
                        update(releasechange_draftlast_stage);//更新fact中变量值
                        update(releasechange_draftstage_filter);//更新fact中变量值
                        update(releasechange_draftstage_transitions);//更新fact中变量值
                        update(releasechange_draftstages);//更新fact中变量值
                        update(releasechange_drafttarget_stage);//更新fact中变量值
            end

            //逻辑处理节点[返回结果]
            rule "rawsfcode2"
            ruleflow-group "releasechange_draftrawsfcode2"
            when
            then
                        update(releasechange_draftdefault);//更新fact中变量值
                        update(releasechange_draftcurrent_stage);//更新fact中变量值
                        update(releasechange_draftfirst_stage);//更新fact中变量值
                        update(releasechange_draftlast_stage);//更新fact中变量值
                        update(releasechange_draftstage_filter);//更新fact中变量值
                        update(releasechange_draftstage_transitions);//更新fact中变量值
                        update(releasechange_draftstages);//更新fact中变量值
                        update(releasechange_drafttarget_stage);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "releasechange_draftend1"
            when
            then
                        update(releasechange_draftdefault);//更新fact中变量值
                        update(releasechange_draftcurrent_stage);//更新fact中变量值
                        update(releasechange_draftfirst_stage);//更新fact中变量值
                        update(releasechange_draftlast_stage);//更新fact中变量值
                        update(releasechange_draftstage_filter);//更新fact中变量值
                        update(releasechange_draftstage_transitions);//更新fact中变量值
                        update(releasechange_draftstages);//更新fact中变量值
                        update(releasechange_drafttarget_stage);//更新fact中变量值
            end