package cn.ibizlab.plm.projmgmt.logic.releaselogic.mob_project_release;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.release releasemob_project_releasedefault;
                global cn.ibizlab.plm.core.projmgmt.domain.release releasemob_project_releasefilter;
                global cn.ibizlab.plm.core.projmgmt.domain.release releasemob_project_releaserelease_page_result;
                    global cn.ibizlab.plm.core.projmgmt.service.IreleaseService releaseservice;
        global cn.ibizlab.plm.core.projmgmt.service.IreleaseService iBzSysReleaseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "releasemob_project_releasebegin"
            when
            then
            end

            //逻辑处理节点[设置过滤器]
            rule "prepareparam1"
            ruleflow-group "releasemob_project_releaseprepareparam1"
            when
            then
                            releasemob_project_releasefilter.set("n_project_id_eq",releasemob_project_releasedefault.get("project"));
                        update(releasemob_project_releasedefault);//更新fact中变量值
                        update(releasemob_project_releasefilter);//更新fact中变量值
                        update(releasemob_project_releaserelease_page_result);//更新fact中变量值
            end

            //逻辑处理节点[项目下发布]
            rule "dedataset1"
            ruleflow-group "releasemob_project_releasededataset1"
            when
            then
                        update(releasemob_project_releasedefault);//更新fact中变量值
                        update(releasemob_project_releasefilter);//更新fact中变量值
                        update(releasemob_project_releaserelease_page_result);//更新fact中变量值
            end

            //逻辑处理节点[设置进度]
            rule "rawsfcode1"
            ruleflow-group "releasemob_project_releaserawsfcode1"
            when
            then
                        update(releasemob_project_releasedefault);//更新fact中变量值
                        update(releasemob_project_releasefilter);//更新fact中变量值
                        update(releasemob_project_releaserelease_page_result);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "releasemob_project_releaseend1"
            when
            then
                        update(releasemob_project_releasedefault);//更新fact中变量值
                        update(releasemob_project_releasefilter);//更新fact中变量值
                        update(releasemob_project_releaserelease_page_result);//更新fact中变量值
            end