package cn.ibizlab.plm.projmgmt.logic.releaselogic.plan_work_item;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.release releaseplan_work_itemdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.release releaseplan_work_itemfor_temp_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.release releaseplan_work_itemsrfactionparam;
                global cn.ibizlab.plm.core.projmgmt.domain.release releaseplan_work_itemupdate_obj;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.IreleaseService iBzSysReleaseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "releaseplan_work_itembegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "releaseplan_work_itembindparam1"
            when
            then
                        update(releaseplan_work_itemdefault);//更新fact中变量值
                        update(releaseplan_work_itemfor_temp_obj);//更新fact中变量值
                        update(releaseplan_work_itemsrfactionparam);//更新fact中变量值
                        update(releaseplan_work_itemupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "releaseplan_work_itemloopsubcall1"
            when
            then
                        update(releaseplan_work_itemdefault);//更新fact中变量值
                        update(releaseplan_work_itemfor_temp_obj);//更新fact中变量值
                        update(releaseplan_work_itemsrfactionparam);//更新fact中变量值
                        update(releaseplan_work_itemupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "releaseplan_work_itemrenewparam1"
            when
            then
                        update(releaseplan_work_itemdefault);//更新fact中变量值
                        update(releaseplan_work_itemfor_temp_obj);//更新fact中变量值
                        update(releaseplan_work_itemsrfactionparam);//更新fact中变量值
                        update(releaseplan_work_itemupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "releaseplan_work_itemprepareparam1"
            when
            then
                            releaseplan_work_itemupdate_obj.set("id",releaseplan_work_itemfor_temp_obj.get("id"));
                            releaseplan_work_itemupdate_obj.set("release_id",releaseplan_work_itemdefault.get("release_id"));
                        update(releaseplan_work_itemdefault);//更新fact中变量值
                        update(releaseplan_work_itemfor_temp_obj);//更新fact中变量值
                        update(releaseplan_work_itemsrfactionparam);//更新fact中变量值
                        update(releaseplan_work_itemupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[更新工作项]
            rule "deaction1"
            ruleflow-group "releaseplan_work_itemdeaction1"
            when
            then
                        work_itemservice.update(releaseplan_work_itemupdate_obj);
                        update(releaseplan_work_itemdefault);//更新fact中变量值
                        update(releaseplan_work_itemfor_temp_obj);//更新fact中变量值
                        update(releaseplan_work_itemsrfactionparam);//更新fact中变量值
                        update(releaseplan_work_itemupdate_obj);//更新fact中变量值
            end