package cn.ibizlab.plm.ai.logic.ai_kb_document_synclogic.prepare_create;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document_sync ai_kb_document_syncprepare_createdefault;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document_wizard ai_kb_document_syncprepare_createai_kb_doc_wizard;
        global cn.ibizlab.plm.core.ai.service.Iai_kb_document_syncService iBzSysAi_kb_document_syncDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_kb_document_syncprepare_createbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "ai_kb_document_syncprepare_createprepareparam_01"
            when
            then
                            ai_kb_document_syncprepare_createai_kb_doc_wizard.set("parserconfig",ai_kb_document_syncprepare_createdefault.get("parser_config"));
                            ai_kb_document_syncprepare_createai_kb_doc_wizard.set("customchunk",ai_kb_document_syncprepare_createdefault.get("custom_chunk"));
                            ai_kb_document_syncprepare_createai_kb_doc_wizard.set("chunkmethod",ai_kb_document_syncprepare_createdefault.get("chunk_method"));
                        update(ai_kb_document_syncprepare_createdefault);//更新fact中变量值
                        update(ai_kb_document_syncprepare_createai_kb_doc_wizard);//更新fact中变量值
            end

            //逻辑处理节点[查看创建前的参数]
            rule "debugparam_01"
            ruleflow-group "ai_kb_document_syncprepare_createdebugparam_01"
            when
            then
                        update(ai_kb_document_syncprepare_createdefault);//更新fact中变量值
                        update(ai_kb_document_syncprepare_createai_kb_doc_wizard);//更新fact中变量值
            end