package cn.ibizlab.plm.ai.logic.ai_kb_document_synclogic.space_parse;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document_sync ai_kb_document_syncspace_parsedefault;
                global cn.ibizlab.plm.core.wiki.domain.article_page ai_kb_document_syncspace_parseall_pages;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document ai_kb_document_syncspace_parsedoc;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document ai_kb_document_syncspace_parsedoc_filter;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document_sync ai_kb_document_syncspace_parsedoc_sync;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document ai_kb_document_syncspace_parsedocs;
                global cn.ibizlab.plm.core.wiki.domain.article_page ai_kb_document_syncspace_parsepage;
                global cn.ibizlab.plm.core.wiki.domain.article_page ai_kb_document_syncspace_parsepage_filter;
                global cn.ibizlab.plm.core.wiki.domain.article_page ai_kb_document_syncspace_parsepages_notin_docs;
                global java.util.Map ai_kb_document_syncspace_parsetemp_docs;
                    global cn.ibizlab.plm.core.ai.service.Iai_kb_document_syncService ai_kb_document_syncservice;
                    global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService article_pageservice;
                    global cn.ibizlab.plm.core.ai.service.Iai_kb_documentService ai_kb_documentservice;
        global cn.ibizlab.plm.core.ai.service.Iai_kb_document_syncService iBzSysAi_kb_document_syncDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_kb_document_syncspace_parsebegin"
            when
            then
            end

            //逻辑处理节点[准备文档参数]
            rule "prepareparam_02"
            ruleflow-group "ai_kb_document_syncspace_parseprepareparam_02"
            when
            then
                            ai_kb_document_syncspace_parsedoc_filter.set("n_sync_id_eq",ai_kb_document_syncspace_parsedoc_sync.get("id"));
                            ai_kb_document_syncspace_parsedoc_filter.set("size","2000");
                        update(ai_kb_document_syncspace_parsedefault);//更新fact中变量值
                        update(ai_kb_document_syncspace_parseall_pages);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_sync);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedocs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepages_notin_docs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsetemp_docs);//更新fact中变量值
            end

            //逻辑处理节点[获取文档同步数据]
            rule "deaction_01"
            ruleflow-group "ai_kb_document_syncspace_parsedeaction_01"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(ai_kb_document_syncservice.get(ai_kb_document_syncspace_parsedefault.getId()),ai_kb_document_syncspace_parsedefault);
                        update(ai_kb_document_syncspace_parsedefault);//更新fact中变量值
                        update(ai_kb_document_syncspace_parseall_pages);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_sync);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedocs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepages_notin_docs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsetemp_docs);//更新fact中变量值
            end

            //逻辑处理节点[准备空间参数]
            rule "prepareparam_01"
            ruleflow-group "ai_kb_document_syncspace_parseprepareparam_01"
            when
            then
                            ai_kb_document_syncspace_parsepage_filter.set("n_space_id_eq",ai_kb_document_syncspace_parsedoc_sync.get("sourceid"));
                            ai_kb_document_syncspace_parsepage_filter.set("size","1500");
                        update(ai_kb_document_syncspace_parsedefault);//更新fact中变量值
                        update(ai_kb_document_syncspace_parseall_pages);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_sync);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedocs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepages_notin_docs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsetemp_docs);//更新fact中变量值
            end

            //逻辑处理节点[查询空间启用的页面]
            rule "dedataset_01"
            ruleflow-group "ai_kb_document_syncspace_parsededataset_01"
            when
            then
                        update(ai_kb_document_syncspace_parsedefault);//更新fact中变量值
                        update(ai_kb_document_syncspace_parseall_pages);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_sync);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedocs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepages_notin_docs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsetemp_docs);//更新fact中变量值
            end

            //逻辑处理节点[查询已同步页面]
            rule "dedataset_02"
            ruleflow-group "ai_kb_document_syncspace_parsededataset_02"
            when
            then
                        update(ai_kb_document_syncspace_parsedefault);//更新fact中变量值
                        update(ai_kb_document_syncspace_parseall_pages);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_sync);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedocs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepages_notin_docs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsetemp_docs);//更新fact中变量值
            end

            //逻辑处理节点[查询最新空间文档]
            rule "dedataset_03"
            ruleflow-group "ai_kb_document_syncspace_parsededataset_03"
            when
            then
                        update(ai_kb_document_syncspace_parsedefault);//更新fact中变量值
                        update(ai_kb_document_syncspace_parseall_pages);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_sync);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedocs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepages_notin_docs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsetemp_docs);//更新fact中变量值
            end

            //逻辑处理节点[处理未同步页面]
            rule "rawsfcode_01"
            ruleflow-group "ai_kb_document_syncspace_parserawsfcode_01"
            when
            then
                        update(ai_kb_document_syncspace_parsedefault);//更新fact中变量值
                        update(ai_kb_document_syncspace_parseall_pages);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_sync);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedocs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepages_notin_docs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsetemp_docs);//更新fact中变量值
            end

            //逻辑处理节点[清理冗余的doc]
            rule "rawsfcode_02"
            ruleflow-group "ai_kb_document_syncspace_parserawsfcode_02"
            when
            then
                        update(ai_kb_document_syncspace_parsedefault);//更新fact中变量值
                        update(ai_kb_document_syncspace_parseall_pages);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_sync);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedocs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepages_notin_docs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsetemp_docs);//更新fact中变量值
            end

            //逻辑处理节点[解析空间下文档]
            rule "loopsubcall_02"
            ruleflow-group "ai_kb_document_syncspace_parseloopsubcall_02"
            when
            then
                        update(ai_kb_document_syncspace_parsedefault);//更新fact中变量值
                        update(ai_kb_document_syncspace_parseall_pages);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_sync);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedocs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepages_notin_docs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsetemp_docs);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_kb_document_syncspace_parseend_01"
            when
            then
                        update(ai_kb_document_syncspace_parsedefault);//更新fact中变量值
                        update(ai_kb_document_syncspace_parseall_pages);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_sync);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedocs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepages_notin_docs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsetemp_docs);//更新fact中变量值
            end

            //逻辑处理节点[解析文档]
            rule "deaction_03"
            ruleflow-group "ai_kb_document_syncspace_parsedeaction_03"
            when
            then
                        ai_kb_documentservice.parse(ai_kb_document_syncspace_parsedoc);
                        update(ai_kb_document_syncspace_parsedefault);//更新fact中变量值
                        update(ai_kb_document_syncspace_parseall_pages);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedoc_sync);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsedocs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepage_filter);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsepages_notin_docs);//更新fact中变量值
                        update(ai_kb_document_syncspace_parsetemp_docs);//更新fact中变量值
            end