package cn.ibizlab.plm.ai.logic.ai_kb_document_synclogic.sync_document;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document_sync ai_kb_document_syncsync_documentdefault;
                global cn.ibizlab.plm.core.wiki.domain.article_page ai_kb_document_syncsync_documentpage_filter;
                global cn.ibizlab.plm.core.wiki.domain.article_page ai_kb_document_syncsync_documentpages;
                    global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService article_pageservice;
        global cn.ibizlab.plm.core.ai.service.Iai_kb_document_syncService iBzSysAi_kb_document_syncDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_kb_document_syncsync_documentbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "ai_kb_document_syncsync_documentprepareparam_01"
            when
            then
                            ai_kb_document_syncsync_documentpage_filter.set("n_space_id_eq",ai_kb_document_syncsync_documentdefault.get("sourceid"));
                            ai_kb_document_syncsync_documentpage_filter.set("size","1000");
                        update(ai_kb_document_syncsync_documentdefault);//更新fact中变量值
                        update(ai_kb_document_syncsync_documentpage_filter);//更新fact中变量值
                        update(ai_kb_document_syncsync_documentpages);//更新fact中变量值
            end

            //逻辑处理节点[查询空间下的页面]
            rule "dedataset_01"
            ruleflow-group "ai_kb_document_syncsync_documentdedataset_01"
            when
            then
                        update(ai_kb_document_syncsync_documentdefault);//更新fact中变量值
                        update(ai_kb_document_syncsync_documentpage_filter);//更新fact中变量值
                        update(ai_kb_document_syncsync_documentpages);//更新fact中变量值
            end