package cn.ibizlab.plm.ai.logic.ai_kb_document_synclogic.sync_remove_doc_chunk;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document_sync ai_kb_document_syncsync_remove_doc_chunkdefault;
        global cn.ibizlab.plm.core.ai.service.Iai_kb_document_syncService iBzSysAi_kb_document_syncDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_kb_document_syncsync_remove_doc_chunkbegin"
            when
            then
            end

            //逻辑处理节点[删除文档分块]
            rule "rawsqlcall_02"
            ruleflow-group "ai_kb_document_syncsync_remove_doc_chunkrawsqlcall_02"
            when
            then
    Map param =new HashMap();
        param.put("param0",ai_kb_document_syncsync_remove_doc_chunkdefault.get("id"));
    String strSql="DELETE c FROM ai_kb_chunk  c WHERE  exists (select 1 from ai_kb_document doc where doc.id=c.document_id and doc.SYNC_ID= #{et.param0} )";
                        iBzSysAi_kb_document_syncDefaultService.execute(strSql,param);//SQL调用
                        update(ai_kb_document_syncsync_remove_doc_chunkdefault);//更新fact中变量值
            end

            //逻辑处理节点[删除文档]
            rule "rawsqlcall_01"
            ruleflow-group "ai_kb_document_syncsync_remove_doc_chunkrawsqlcall_01"
            when
            then
    Map param =new HashMap();
        param.put("param0",ai_kb_document_syncsync_remove_doc_chunkdefault.get("id"));
    String strSql="DELETE doc FROM ai_kb_document doc WHERE doc.sync_id = #{et.param0}";
                        iBzSysAi_kb_document_syncDefaultService.execute(strSql,param);//SQL调用
                        update(ai_kb_document_syncsync_remove_doc_chunkdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_kb_document_syncsync_remove_doc_chunkend_01"
            when
            then
                        update(ai_kb_document_syncsync_remove_doc_chunkdefault);//更新fact中变量值
            end