package cn.ibizlab.plm.team.logic.discuss_topiclogic.activate;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_topic discuss_topicactivatedefault;
                global cn.ibizlab.plm.core.team.domain.discuss_topic discuss_topicactivateupdate_obj;
                    global cn.ibizlab.plm.core.team.service.Idiscuss_topicService discuss_topicservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_topicService iBzSysDiscuss_topicDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_topicactivatebegin"
            when
            then
            end

            //逻辑处理节点[设置归档状态]
            rule "prepareparam1"
            ruleflow-group "discuss_topicactivateprepareparam1"
            when
            then
                            discuss_topicactivateupdate_obj.set("isarchived","0");
                            discuss_topicactivateupdate_obj.set("id",discuss_topicactivatedefault.get("id"));
                        update(discuss_topicactivatedefault);//更新fact中变量值
                        update(discuss_topicactivateupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[激活]
            rule "deaction1"
            ruleflow-group "discuss_topicactivatedeaction1"
            when
            then
                        discuss_topicservice.update(discuss_topicactivateupdate_obj);
                        update(discuss_topicactivatedefault);//更新fact中变量值
                        update(discuss_topicactivateupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_topicactivateend1"
            when
            then
                        update(discuss_topicactivatedefault);//更新fact中变量值
                        update(discuss_topicactivateupdate_obj);//更新fact中变量值
            end