package cn.ibizlab.plm.team.logic.discuss_topiclogic.archive;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_topic discuss_topicarchivedefault;
                global cn.ibizlab.plm.core.team.domain.discuss_topic discuss_topicarchiveupdate_obj;
                    global cn.ibizlab.plm.core.team.service.Idiscuss_topicService discuss_topicservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_topicService iBzSysDiscuss_topicDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_topicarchivebegin"
            when
            then
            end

            //逻辑处理节点[设置已归档状态]
            rule "prepareparam1"
            ruleflow-group "discuss_topicarchiveprepareparam1"
            when
            then
                            discuss_topicarchiveupdate_obj.set("isarchived","1");
                            discuss_topicarchiveupdate_obj.set("id",discuss_topicarchivedefault.get("id"));
                        update(discuss_topicarchivedefault);//更新fact中变量值
                        update(discuss_topicarchiveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[归档]
            rule "deaction1"
            ruleflow-group "discuss_topicarchivedeaction1"
            when
            then
                        discuss_topicservice.update(discuss_topicarchiveupdate_obj);
                        update(discuss_topicarchivedefault);//更新fact中变量值
                        update(discuss_topicarchiveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_topicarchiveend1"
            when
            then
                        update(discuss_topicarchivedefault);//更新fact中变量值
                        update(discuss_topicarchiveupdate_obj);//更新fact中变量值
            end