package cn.ibizlab.plm.team.logic.discuss_topiclogic.create_recent;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_topic discuss_topiccreate_recentdefault;
                global cn.ibizlab.plm.core.base.domain.recent discuss_topiccreate_recentrecent;
                    global cn.ibizlab.plm.core.base.service.IrecentService recentservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_topicService iBzSysDiscuss_topicDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_topiccreate_recentbegin"
            when
            then
            end

            //逻辑处理节点[准备最近访问参数]
            rule "prepareparam1"
            ruleflow-group "discuss_topiccreate_recentprepareparam1"
            when
            then
                            discuss_topiccreate_recentrecent.set("ownerid",discuss_topiccreate_recentdefault.get("id"));
                            discuss_topiccreate_recentrecent.set("recentparentidentifier",discuss_topiccreate_recentdefault.get("identifier"));
                            discuss_topiccreate_recentrecent.set("recentparentname",discuss_topiccreate_recentdefault.get("name"));
                            discuss_topiccreate_recentrecent.set("recentparent",discuss_topiccreate_recentdefault.get("id"));
                                discuss_topiccreate_recentrecent.set("createman",curuser.getSessionParams().get("srfpersonid"));
                            discuss_topiccreate_recentrecent.set("type","3");
                            discuss_topiccreate_recentrecent.set("name",discuss_topiccreate_recentdefault.get("name"));
                            discuss_topiccreate_recentrecent.set("ownertype","discuss");
                            discuss_topiccreate_recentrecent.set("ownersubtype","discuss");
                        update(discuss_topiccreate_recentdefault);//更新fact中变量值
                        update(discuss_topiccreate_recentrecent);//更新fact中变量值
            end

            //逻辑处理节点[保存最近访问]
            rule "deaction1"
            ruleflow-group "discuss_topiccreate_recentdeaction1"
            when
            then
                        recentservice.save(discuss_topiccreate_recentrecent);
                        update(discuss_topiccreate_recentdefault);//更新fact中变量值
                        update(discuss_topiccreate_recentrecent);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_topiccreate_recentend1"
            when
            then
                        update(discuss_topiccreate_recentdefault);//更新fact中变量值
                        update(discuss_topiccreate_recentrecent);//更新fact中变量值
            end