package cn.ibizlab.plm.team.logic.discuss_topiclogic.delete;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_topic discuss_topicdeletedefault;
                global cn.ibizlab.plm.core.team.domain.discuss_topic discuss_topicdeleteupdate_obj;
                    global cn.ibizlab.plm.core.team.service.Idiscuss_topicService discuss_topicservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_topicService iBzSysDiscuss_topicDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_topicdeletebegin"
            when
            then
            end

            //逻辑处理节点[设置删除状态]
            rule "prepareparam1"
            ruleflow-group "discuss_topicdeleteprepareparam1"
            when
            then
                            discuss_topicdeleteupdate_obj.set("isdeleted","1");
                            discuss_topicdeleteupdate_obj.set("id",discuss_topicdeletedefault.get("id"));
                        update(discuss_topicdeletedefault);//更新fact中变量值
                        update(discuss_topicdeleteupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[更新话题的删除状态]
            rule "deaction1"
            ruleflow-group "discuss_topicdeletedeaction1"
            when
            then
                        discuss_topicservice.update(discuss_topicdeleteupdate_obj);
                        update(discuss_topicdeletedefault);//更新fact中变量值
                        update(discuss_topicdeleteupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_topicdeleteend1"
            when
            then
                        update(discuss_topicdeletedefault);//更新fact中变量值
                        update(discuss_topicdeleteupdate_obj);//更新fact中变量值
            end