package cn.ibizlab.plm.team.logic.discuss_topiclogic.favorite;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_topic discuss_topicfavoritedefault;
                global cn.ibizlab.plm.core.base.domain.favorite discuss_topicfavoritefavorite;
                    global cn.ibizlab.plm.core.base.service.IfavoriteService favoriteservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_topicService iBzSysDiscuss_topicDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_topicfavoritebegin"
            when
            then
            end

            //逻辑处理节点[填充用户标识和收藏业务对象标识]
            rule "prepareparam1"
            ruleflow-group "discuss_topicfavoriteprepareparam1"
            when
            then
                                discuss_topicfavoritefavorite.set("createman",curuser.getSessionParams().get("srfuserid"));
                            discuss_topicfavoritefavorite.set("ownertype","discuss_topic");
                            discuss_topicfavoritefavorite.set("ownerid",discuss_topicfavoritedefault.get("owner_id"));
                        update(discuss_topicfavoritedefault);//更新fact中变量值
                        update(discuss_topicfavoritefavorite);//更新fact中变量值
            end

            //逻辑处理节点[生成收藏数据]
            rule "deaction1"
            ruleflow-group "discuss_topicfavoritedeaction1"
            when
            then
                        favoriteservice.save(discuss_topicfavoritefavorite);
                        update(discuss_topicfavoritedefault);//更新fact中变量值
                        update(discuss_topicfavoritefavorite);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_topicfavoriteend1"
            when
            then
                        update(discuss_topicfavoritedefault);//更新fact中变量值
                        update(discuss_topicfavoritefavorite);//更新fact中变量值
            end