package cn.ibizlab.plm.team.logic.discuss_topiclogic.get_discuss_member_one;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_topic discuss_topicget_discuss_member_onedefault;
                global cn.ibizlab.plm.core.team.domain.discuss_member discuss_topicget_discuss_member_onefilter;
                global java.util.Map discuss_topicget_discuss_member_onefor_obj;
                global cn.ibizlab.plm.core.team.domain.discuss_member discuss_topicget_discuss_member_onemembers;
                global java.util.Map discuss_topicget_discuss_member_oneuser;
                    global cn.ibizlab.plm.core.team.service.Idiscuss_memberService discuss_memberservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_topicService iBzSysDiscuss_topicDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_topicget_discuss_member_onebegin"
            when
            then
            end

            //逻辑处理节点[判断系统管理员身份]
            rule "rawsfcode3"
            ruleflow-group "discuss_topicget_discuss_member_onerawsfcode3"
            when
            then
                        update(discuss_topicget_discuss_member_onedefault);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefilter);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefor_obj);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onemembers);//更新fact中变量值
                        update(discuss_topicget_discuss_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "discuss_topicget_discuss_member_oneend2"
            when
            then
                        update(discuss_topicget_discuss_member_onedefault);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefilter);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefor_obj);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onemembers);//更新fact中变量值
                        update(discuss_topicget_discuss_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[获取话题id并设置过滤参数]
            rule "prepareparam2"
            ruleflow-group "discuss_topicget_discuss_member_oneprepareparam2"
            when
            then
                            discuss_topicget_discuss_member_onefilter.set("n_owner_id_eq",discuss_topicget_discuss_member_onedefault.get("id"));
                                discuss_topicget_discuss_member_onefilter.set("n_user_id_eq",curuser.getSessionParams().get("srfpersonid"));
                        update(discuss_topicget_discuss_member_onedefault);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefilter);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefor_obj);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onemembers);//更新fact中变量值
                        update(discuss_topicget_discuss_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[查询当前用户是否为话题成员]
            rule "dedataset3"
            ruleflow-group "discuss_topicget_discuss_member_onededataset3"
            when
            then
                        update(discuss_topicget_discuss_member_onedefault);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefilter);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefor_obj);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onemembers);//更新fact中变量值
                        update(discuss_topicget_discuss_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[只读权限]
            rule "rawsfcode1"
            ruleflow-group "discuss_topicget_discuss_member_onerawsfcode1"
            when
            then
                        update(discuss_topicget_discuss_member_onedefault);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefilter);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefor_obj);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onemembers);//更新fact中变量值
                        update(discuss_topicget_discuss_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end6"
            ruleflow-group "discuss_topicget_discuss_member_oneend6"
            when
            then
                        update(discuss_topicget_discuss_member_onedefault);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefilter);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefor_obj);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onemembers);//更新fact中变量值
                        update(discuss_topicget_discuss_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[空，承载判断]
            rule "prepareparam3"
            ruleflow-group "discuss_topicget_discuss_member_oneprepareparam3"
            when
            then
                        update(discuss_topicget_discuss_member_onedefault);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefilter);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefor_obj);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onemembers);//更新fact中变量值
                        update(discuss_topicget_discuss_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[绑定用户数据到for_obj]
            rule "prepareparam5"
            ruleflow-group "discuss_topicget_discuss_member_oneprepareparam5"
            when
            then
                            discuss_topicget_discuss_member_onefor_obj.set("",discuss_topicget_discuss_member_onemembers.get("0"));
                        update(discuss_topicget_discuss_member_onedefault);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefilter);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefor_obj);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onemembers);//更新fact中变量值
                        update(discuss_topicget_discuss_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[非只读权限]
            rule "rawsfcode2"
            ruleflow-group "discuss_topicget_discuss_member_onerawsfcode2"
            when
            then
                        update(discuss_topicget_discuss_member_onedefault);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefilter);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefor_obj);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onemembers);//更新fact中变量值
                        update(discuss_topicget_discuss_member_oneuser);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode4"
            ruleflow-group "discuss_topicget_discuss_member_onerawsfcode4"
            when
            then
                        update(discuss_topicget_discuss_member_onedefault);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefilter);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onefor_obj);//更新fact中变量值
                        update(discuss_topicget_discuss_member_onemembers);//更新fact中变量值
                        update(discuss_topicget_discuss_member_oneuser);//更新fact中变量值
            end