package cn.ibizlab.plm.team.logic.discuss_topiclogic.quick_create;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_topic discuss_topicquick_createdefault;
                global cn.ibizlab.plm.core.team.domain.discuss_topic discuss_topicquick_creatediscuss_topics;
                    global cn.ibizlab.plm.core.team.service.Idiscuss_topicService discuss_topicservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_topicService iBzSysDiscuss_topicDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_topicquick_createbegin"
            when
            then
            end

            //逻辑处理节点[获取主表格查询数据集]
            rule "dedataset2"
            ruleflow-group "discuss_topicquick_creatededataset2"
            when
            then
                        update(discuss_topicquick_createdefault);//更新fact中变量值
                        update(discuss_topicquick_creatediscuss_topics);//更新fact中变量值
            end

            //逻辑处理节点[获取用户快速新建数据集]
            rule "dedataset4"
            ruleflow-group "discuss_topicquick_creatededataset4"
            when
            then
                        update(discuss_topicquick_createdefault);//更新fact中变量值
                        update(discuss_topicquick_creatediscuss_topics);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "discuss_topicquick_createend2"
            when
            then
                        update(discuss_topicquick_createdefault);//更新fact中变量值
                        update(discuss_topicquick_creatediscuss_topics);//更新fact中变量值
            end

            //逻辑处理节点[判断系统管理员身份]
            rule "rawsfcode3"
            ruleflow-group "discuss_topicquick_createrawsfcode3"
            when
            then
                        update(discuss_topicquick_createdefault);//更新fact中变量值
                        update(discuss_topicquick_creatediscuss_topics);//更新fact中变量值
            end