package cn.ibizlab.plm.team.logic.discuss_topiclogic.recover;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_topic discuss_topicrecoverdefault;
                global cn.ibizlab.plm.core.team.domain.discuss_topic discuss_topicrecoverupdate_obj;
                    global cn.ibizlab.plm.core.team.service.Idiscuss_topicService discuss_topicservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_topicService iBzSysDiscuss_topicDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_topicrecoverbegin"
            when
            then
            end

            //逻辑处理节点[设置删除状态]
            rule "prepareparam1"
            ruleflow-group "discuss_topicrecoverprepareparam1"
            when
            then
                            discuss_topicrecoverupdate_obj.set("isdeleted","0");
                            discuss_topicrecoverupdate_obj.set("id",discuss_topicrecoverdefault.get("id"));
                        update(discuss_topicrecoverdefault);//更新fact中变量值
                        update(discuss_topicrecoverupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[恢复]
            rule "deaction1"
            ruleflow-group "discuss_topicrecoverdeaction1"
            when
            then
                        discuss_topicservice.update(discuss_topicrecoverupdate_obj);
                        update(discuss_topicrecoverdefault);//更新fact中变量值
                        update(discuss_topicrecoverupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_topicrecoverend1"
            when
            then
                        update(discuss_topicrecoverdefault);//更新fact中变量值
                        update(discuss_topicrecoverupdate_obj);//更新fact中变量值
            end