package cn.ibizlab.plm.prodmgmt.logic.product_memberlogic.remove_product_member_notify;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_member product_memberremove_product_member_notifydefault;
                    global cn.ibizlab.plm.core.prodmgmt.service.Iproduct_memberService product_memberservice;
        global cn.ibizlab.plm.core.prodmgmt.service.Iproduct_memberService iBzSysProduct_memberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "product_memberremove_product_member_notifybegin"
            when
            then
            end

            //逻辑处理节点[获取数据]
            rule "deaction1"
            ruleflow-group "product_memberremove_product_member_notifydeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(product_memberservice.get(product_memberremove_product_member_notifydefault.getId()),product_memberremove_product_member_notifydefault);
                        update(product_memberremove_product_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[绑定当前操作人]
            rule "prepareparam1"
            ruleflow-group "product_memberremove_product_member_notifyprepareparam1"
            when
            then
                                product_memberremove_product_member_notifydefault.set("updateman",curuser.getSessionParams().get("srfpersonid"));
                        update(product_memberremove_product_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[获取当前操作时间]
            rule "rawsfcode1"
            ruleflow-group "product_memberremove_product_member_notifyrawsfcode1"
            when
            then
                        update(product_memberremove_product_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[移除产品成员通知]
            rule "denotify1"
            ruleflow-group "product_memberremove_product_member_notifydenotify1"
            when
            then
                        update(product_memberremove_product_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "product_memberremove_product_member_notifyend1"
            when
            then
                        update(product_memberremove_product_member_notifydefault);//更新fact中变量值
            end