package cn.ibizlab.plm.base.logic.template_flowlogic.archive_completed;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.Template_flow template_flowarchive_completeddefault;
        global cn.ibizlab.plm.core.base.service.ITemplate_flowService iBzSysTemplate_flowDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "template_flowarchive_completedbegin"
            when
            then
            end