package cn.ibizlab.plm.base.logic.template_flowlogic.auto_create_sub_work_item;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.Template_flow template_flowauto_create_sub_work_itemdefault;
        global cn.ibizlab.plm.core.base.service.ITemplate_flowService iBzSysTemplate_flowDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "template_flowauto_create_sub_work_itembegin"
            when
            then
            end