package cn.ibizlab.plm.base.logic.template_flowlogic.auto_add_new_group_member_to_space;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.template_flow template_flowauto_add_new_group_member_to_spacedefault;
                global cn.ibizlab.plm.core.wiki.domain.space_member template_flowauto_add_new_group_member_to_spacespace_member;
                    global cn.ibizlab.plm.core.wiki.service.Ispace_memberService space_memberservice;
        global cn.ibizlab.plm.core.base.service.Itemplate_flowService iBzSysTemplate_flowDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "template_flowauto_add_new_group_member_to_spacebegin"
            when
            then
            end

            //逻辑处理节点[设置空间成员]
            rule "prepareparam1"
            ruleflow-group "template_flowauto_add_new_group_member_to_spaceprepareparam1"
            when
            then
                            template_flowauto_add_new_group_member_to_spacespace_member.set("userid",template_flowauto_add_new_group_member_to_spacedefault.get("user_id"));
                            template_flowauto_add_new_group_member_to_spacespace_member.set("roleid",template_flowauto_add_new_group_member_to_spacedefault.get("role_id"));
                            template_flowauto_add_new_group_member_to_spacespace_member.set("name",template_flowauto_add_new_group_member_to_spacedefault.get("name"));
                            template_flowauto_add_new_group_member_to_spacespace_member.set("spaceid","plm_space");
                        update(template_flowauto_add_new_group_member_to_spacedefault);//更新fact中变量值
                        update(template_flowauto_add_new_group_member_to_spacespace_member);//更新fact中变量值
            end

            //逻辑处理节点[添加空间成员]
            rule "deaction1"
            ruleflow-group "template_flowauto_add_new_group_member_to_spacedeaction1"
            when
            then
                        space_memberservice.save(template_flowauto_add_new_group_member_to_spacespace_member);
                        update(template_flowauto_add_new_group_member_to_spacedefault);//更新fact中变量值
                        update(template_flowauto_add_new_group_member_to_spacespace_member);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "template_flowauto_add_new_group_member_to_spaceend1"
            when
            then
                        update(template_flowauto_add_new_group_member_to_spacedefault);//更新fact中变量值
                        update(template_flowauto_add_new_group_member_to_spacespace_member);//更新fact中变量值
            end