package cn.ibizlab.plm.ebsx.logic.todologic.gettododata;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ebsx.domain.todo todogettododatadefault;
                    global cn.ibizlab.plm.core.ebsx.service.ISysTodoService systodoservice;
        global cn.ibizlab.plm.core.ebsx.service.ItodoService iBzSysTodoDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "todogettododatabegin"
            when
            then
            end

            //逻辑处理节点[实体行为]
            rule "deaction7"
            ruleflow-group "todogettododatadeaction7"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(systodoservice.get(todogettododatadefault.getTodoid()),todogettododatadefault);
                        update(todogettododatadefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end3"
            ruleflow-group "todogettododataend3"
            when
            then
                        update(todogettododatadefault);//更新fact中变量值
            end