package cn.ibizlab.plm.testmgmt.logic.test_planlogic.delete_categories;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.test_plan test_plandelete_categoriesdefault;
        global cn.ibizlab.plm.core.testmgmt.service.Itest_planService iBzSysTest_planDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_plandelete_categoriesbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_plandelete_categoriesend1"
            when
            then
                        update(test_plandelete_categoriesdefault);//更新fact中变量值
            end

            //逻辑处理节点[当类别删除时修改发布的类别属性]
            rule "rawsqlcall1"
            ruleflow-group "test_plandelete_categoriesrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",test_plandelete_categoriesdefault.get("id"));
        param.put("param1",test_plandelete_categoriesdefault.get("id"));
    String strSql="UPDATE test_plan SET categories = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', categories, ','), CONCAT(',', #{et.param0}, ','), ',')) WHERE FIND_IN_SET(#{et.param1}, categories) > 0 ;";
                        iBzSysTest_planDefaultService.execute(strSql,param);//SQL调用
                        update(test_plandelete_categoriesdefault);//更新fact中变量值
            end