package cn.ibizlab.plm.prodmgmt.logic.product_planlogic.get_delete_plan;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_plan product_planget_delete_plandefault;
                global java.util.Map product_planget_delete_planfilter;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_plan product_planget_delete_planplan_filter;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_plan product_planget_delete_planproduct_plan_pages;
                    global cn.ibizlab.plm.core.prodmgmt.service.Iproduct_planService product_planservice;
        global cn.ibizlab.plm.core.prodmgmt.service.Iproduct_planService iBzSysProduct_planDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "product_planget_delete_planbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "product_planget_delete_planprepareparam1"
            when
            then
                            product_planget_delete_planplan_filter.set("n_categories_like",product_planget_delete_plandefault.get("id"));
                        update(product_planget_delete_plandefault);//更新fact中变量值
                        update(product_planget_delete_planfilter);//更新fact中变量值
                        update(product_planget_delete_planplan_filter);//更新fact中变量值
                        update(product_planget_delete_planproduct_plan_pages);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "product_planget_delete_plandedataset1"
            when
            then
                        update(product_planget_delete_plandefault);//更新fact中变量值
                        update(product_planget_delete_planfilter);//更新fact中变量值
                        update(product_planget_delete_planplan_filter);//更新fact中变量值
                        update(product_planget_delete_planproduct_plan_pages);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam2"
            ruleflow-group "product_planget_delete_plandebugparam2"
            when
            then
                        update(product_planget_delete_plandefault);//更新fact中变量值
                        update(product_planget_delete_planfilter);//更新fact中变量值
                        update(product_planget_delete_planplan_filter);//更新fact中变量值
                        update(product_planget_delete_planproduct_plan_pages);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "product_planget_delete_planend1"
            when
            then
                        update(product_planget_delete_plandefault);//更新fact中变量值
                        update(product_planget_delete_planfilter);//更新fact中变量值
                        update(product_planget_delete_planplan_filter);//更新fact中变量值
                        update(product_planget_delete_planproduct_plan_pages);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "product_planget_delete_plandebugparam1"
            when
            then
                        update(product_planget_delete_plandefault);//更新fact中变量值
                        update(product_planget_delete_planfilter);//更新fact中变量值
                        update(product_planget_delete_planplan_filter);//更新fact中变量值
                        update(product_planget_delete_planproduct_plan_pages);//更新fact中变量值
            end

            //逻辑处理节点[直接sql调用]
            rule "rawsqlcall1"
            ruleflow-group "product_planget_delete_planrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",product_planget_delete_plandefault.get("id"));
        param.put("param1",product_planget_delete_plandefault.get("id"));
    String strSql="UPDATE product_plan SET categories = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', categories, ','), CONCAT(',', #{et.param0}, ','), ',')) WHERE FIND_IN_SET(#{et.param1}, categories) > 0 ;";
                        iBzSysProduct_planDefaultService.execute(strSql,param);//SQL调用
                        update(product_planget_delete_plandefault);//更新fact中变量值
                        update(product_planget_delete_planfilter);//更新fact中变量值
                        update(product_planget_delete_planplan_filter);//更新fact中变量值
                        update(product_planget_delete_planproduct_plan_pages);//更新fact中变量值
            end