package cn.ibizlab.plm.base.logic.userlogic.cancel_report_flag;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.user usercancel_report_flagdefault;
                    global cn.ibizlab.plm.core.base.service.IuserService userservice;
        global cn.ibizlab.plm.core.base.service.IuserService iBzSysUserDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "usercancel_report_flagbegin"
            when
            then
            end

            //逻辑处理节点[获取用户全量信息]
            rule "deaction2"
            ruleflow-group "usercancel_report_flagdeaction2"
            when
            then
                        userservice.getFull(usercancel_report_flagdefault);
                        update(usercancel_report_flagdefault);//更新fact中变量值
            end

            //逻辑处理节点[设置用户参数]
            rule "prepareparam1"
            ruleflow-group "usercancel_report_flagprepareparam1"
            when
            then
                            usercancel_report_flagdefault.set("reportflag","0");
                        update(usercancel_report_flagdefault);//更新fact中变量值
            end

            //逻辑处理节点[取消用户统计状态]
            rule "deaction1"
            ruleflow-group "usercancel_report_flagdeaction1"
            when
            then
                        userservice.update(usercancel_report_flagdefault);
                        update(usercancel_report_flagdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "usercancel_report_flagend1"
            when
            then
                        update(usercancel_report_flagdefault);//更新fact中变量值
            end