package cn.ibizlab.plm.base.logic.userlogic.freeze;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.user userfreezedefault;
                    global cn.ibizlab.plm.core.base.service.IuserService userservice;
        global cn.ibizlab.plm.core.base.service.IuserService iBzSysUserDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "userfreezebegin"
            when
            then
            end

            //逻辑处理节点[获取用户全量信息]
            rule "deaction2"
            ruleflow-group "userfreezedeaction2"
            when
            then
                        userservice.getFull(userfreezedefault);
                        update(userfreezedefault);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "userfreezeprepareparam1"
            when
            then
                            userfreezedefault.set("status","0");
                            userfreezedefault.set("reportflag","0");
                        update(userfreezedefault);//更新fact中变量值
            end

            //逻辑处理节点[冻结用户]
            rule "deaction1"
            ruleflow-group "userfreezedeaction1"
            when
            then
                        userservice.update(userfreezedefault);
                        update(userfreezedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "userfreezeend1"
            when
            then
                        update(userfreezedefault);//更新fact中变量值
            end