package cn.ibizlab.plm.base.logic.userlogic.workload;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.user userworkloaddefault;
                    global cn.ibizlab.plm.core.base.service.IuserService userservice;
        global cn.ibizlab.plm.core.base.service.IuserService iBzSysUserDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "userworkloadbegin"
            when
            then
            end

            //逻辑处理节点[设置用户参数]
            rule "prepareparam1"
            ruleflow-group "userworkloadprepareparam1"
            when
            then
                            userworkloaddefault.set("workloadflag","1");
                        update(userworkloaddefault);//更新fact中变量值
            end

            //逻辑处理节点[更新用户工时统计状态]
            rule "deaction1"
            ruleflow-group "userworkloaddeaction1"
            when
            then
                        userservice.update(userworkloaddefault);
                        update(userworkloaddefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "userworkloadend1"
            when
            then
                        update(userworkloaddefault);//更新fact中变量值
            end