package cn.ibizlab.plm.base.logic.userlogic.workload_flag_filter;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.user userworkload_flag_filterdefault;
                global cn.ibizlab.plm.core.base.domain.extend_storage userworkload_flag_filterstorage_filter;
                global cn.ibizlab.plm.core.base.domain.extend_storage userworkload_flag_filterstorage_page;
                global cn.ibizlab.plm.core.base.domain.user userworkload_flag_filteruser_filter;
                global cn.ibizlab.plm.core.base.domain.user userworkload_flag_filteruser_page;
                    global cn.ibizlab.plm.core.base.service.Iextend_storageService extend_storageservice;
                    global cn.ibizlab.plm.core.base.service.IuserService userservice;
        global cn.ibizlab.plm.core.base.service.IuserService iBzSysUserDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "userworkload_flag_filterbegin"
            when
            then
            end

            //逻辑处理节点[设置条件]
            rule "prepareparam1"
            ruleflow-group "userworkload_flag_filterprepareparam1"
            when
            then
                            userworkload_flag_filterstorage_filter.set("n_name_eq","REPORT_FLAG");
                            userworkload_flag_filterstorage_filter.set("n_int_value_eq","0");
                        update(userworkload_flag_filterdefault);//更新fact中变量值
                        update(userworkload_flag_filterstorage_filter);//更新fact中变量值
                        update(userworkload_flag_filterstorage_page);//更新fact中变量值
                        update(userworkload_flag_filteruser_filter);//更新fact中变量值
                        update(userworkload_flag_filteruser_page);//更新fact中变量值
            end

            //逻辑处理节点[过滤非统计人员]
            rule "dedataset1"
            ruleflow-group "userworkload_flag_filterdedataset1"
            when
            then
                        update(userworkload_flag_filterdefault);//更新fact中变量值
                        update(userworkload_flag_filterstorage_filter);//更新fact中变量值
                        update(userworkload_flag_filterstorage_page);//更新fact中变量值
                        update(userworkload_flag_filteruser_filter);//更新fact中变量值
                        update(userworkload_flag_filteruser_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "userworkload_flag_filterend1"
            when
            then
                        update(userworkload_flag_filterdefault);//更新fact中变量值
                        update(userworkload_flag_filterstorage_filter);//更新fact中变量值
                        update(userworkload_flag_filterstorage_page);//更新fact中变量值
                        update(userworkload_flag_filteruser_filter);//更新fact中变量值
                        update(userworkload_flag_filteruser_page);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode1"
            ruleflow-group "userworkload_flag_filterrawsfcode1"
            when
            then
                        update(userworkload_flag_filterdefault);//更新fact中变量值
                        update(userworkload_flag_filterstorage_filter);//更新fact中变量值
                        update(userworkload_flag_filterstorage_page);//更新fact中变量值
                        update(userworkload_flag_filteruser_filter);//更新fact中变量值
                        update(userworkload_flag_filteruser_page);//更新fact中变量值
            end

            //逻辑处理节点[获取用户数据]
            rule "dedataset2"
            ruleflow-group "userworkload_flag_filterdedataset2"
            when
            then
                        update(userworkload_flag_filterdefault);//更新fact中变量值
                        update(userworkload_flag_filterstorage_filter);//更新fact中变量值
                        update(userworkload_flag_filterstorage_page);//更新fact中变量值
                        update(userworkload_flag_filteruser_filter);//更新fact中变量值
                        update(userworkload_flag_filteruser_page);//更新fact中变量值
            end