global cn.ibizlab.plm.core.extension.service.IPSDENotifyService  psdenotifyService;
global cn.ibizlab.plm.core.extension.domain.PSDENotify et;

    no-loop

    rule "psdenotifyapply"
    ruleflow-group "1B8272F5-1BFA-4EAA-9BA2-00F95F944199"
    when
    then
    cn.ibizlab.plm.core.extension.domain.PSDENotify actionLogicDE =new cn.ibizlab.plm.core.extension.domain.PSDENotify();
    et.copyTo(actionLogicDE,true);
    psdenotifyService.apply(actionLogicDE);
    end