global cn.ibizlab.plm.core.extension.service.IPSDENotifyService  psdenotifyService;
global cn.ibizlab.plm.core.extension.domain.PSDENotify et;

    no-loop

    rule "psdenotifyapply"
    ruleflow-group "e31cb798738e04b39323548777d5f59e"
    when
    then
    cn.ibizlab.plm.core.extension.domain.PSDENotify actionLogicDE =new cn.ibizlab.plm.core.extension.domain.PSDENotify();
    et.copyTo(actionLogicDE,true);
    psdenotifyService.apply(actionLogicDE);
    end