global cn.ibizlab.plm.core.extension.service.IPSDENotifyService  psdenotifyService;
global cn.ibizlab.plm.core.extension.domain.PSDENotify et;

    no-loop

    rule "psdenotifyapply"
    ruleflow-group "f9bf427a932bdfcf5b7f640ae2498fdf"
    when
    then
    cn.ibizlab.plm.core.extension.domain.PSDENotify actionLogicDE =new cn.ibizlab.plm.core.extension.domain.PSDENotify();
    et.copyTo(actionLogicDE,true);
    psdenotifyService.apply(actionLogicDE);
    end