global cn.ibizlab.plm.core.extension.service.IPSDENotifyService  psdenotifyService;
global cn.ibizlab.plm.core.extension.domain.PSDENotify et;

    no-loop

    rule "psdenotifyapply"
    ruleflow-group "0A708356-B889-4A72-AA5B-528CFB9801CE"
    when
    then
    cn.ibizlab.plm.core.extension.domain.PSDENotify actionLogicDE =new cn.ibizlab.plm.core.extension.domain.PSDENotify();
    et.copyTo(actionLogicDE,true);
    psdenotifyService.apply(actionLogicDE);
    end