package cn.ibizlab.plm.base.logic.view_theme_settinglogic.distinctdata;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.view_theme_setting view_theme_settingdistinctdatadefault;
                global cn.ibizlab.plm.core.ebsx.domain.app_view_theme view_theme_settingdistinctdataoutsettinglist;
                global cn.ibizlab.plm.core.base.domain.view_theme_setting view_theme_settingdistinctdatasettinglist;
                    global cn.ibizlab.plm.core.base.service.Iview_theme_settingService view_theme_settingservice;
        global cn.ibizlab.plm.core.base.service.Iview_theme_settingService iBzSysView_theme_settingDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "view_theme_settingdistinctdatabegin"
            when
            then
            end

            //逻辑处理节点[查询数据]
            rule "dedataset1"
            ruleflow-group "view_theme_settingdistinctdatadedataset1"
            when
            then
                        update(view_theme_settingdistinctdatadefault);//更新fact中变量值
                        update(view_theme_settingdistinctdataoutsettinglist);//更新fact中变量值
                        update(view_theme_settingdistinctdatasettinglist);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "view_theme_settingdistinctdataend1"
            when
            then
                        update(view_theme_settingdistinctdatadefault);//更新fact中变量值
                        update(view_theme_settingdistinctdataoutsettinglist);//更新fact中变量值
                        update(view_theme_settingdistinctdatasettinglist);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode1"
            ruleflow-group "view_theme_settingdistinctdatarawsfcode1"
            when
            then
                        update(view_theme_settingdistinctdatadefault);//更新fact中变量值
                        update(view_theme_settingdistinctdataoutsettinglist);//更新fact中变量值
                        update(view_theme_settingdistinctdatasettinglist);//更新fact中变量值
            end