package cn.ibizlab.plm.base.logic.view_theme_settinglogic.fill_search_conds;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.view_theme_setting view_theme_settingfill_search_condsdefault;
        global cn.ibizlab.plm.core.base.service.Iview_theme_settingService iBzSysView_theme_settingDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "view_theme_settingfill_search_condsbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "view_theme_settingfill_search_condsend1"
            when
            then
                        update(view_theme_settingfill_search_condsdefault);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode1"
            ruleflow-group "view_theme_settingfill_search_condsrawsfcode1"
            when
            then
                        update(view_theme_settingfill_search_condsdefault);//更新fact中变量值
            end