package cn.ibizlab.plm.projmgmt.logic.projectlogic.archive;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectarchivedefault;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectarchiveupdate_obj;
                    global cn.ibizlab.plm.core.projmgmt.service.IprojectService projectservice;
        global cn.ibizlab.plm.core.projmgmt.service.IprojectService iBzSysProjectDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectarchivebegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "projectarchiveprepareparam1"
            when
            then
                            projectarchiveupdate_obj.set("isarchived","1");
                            projectarchiveupdate_obj.set("id",projectarchivedefault.get("id"));
                        update(projectarchivedefault);//更新fact中变量值
                        update(projectarchiveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[归档]
            rule "deaction1"
            ruleflow-group "projectarchivedeaction1"
            when
            then
                        projectservice.update(projectarchiveupdate_obj);
                        update(projectarchivedefault);//更新fact中变量值
                        update(projectarchiveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "projectarchiveend1"
            when
            then
                        update(projectarchivedefault);//更新fact中变量值
                        update(projectarchiveupdate_obj);//更新fact中变量值
            end