package cn.ibizlab.plm.projmgmt.logic.projectlogic.before_create;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Project projectbefore_createdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.Project_member projectbefore_createmember;
                global cn.ibizlab.plm.core.projmgmt.domain.Project_member projectbefore_createmembers;
        global cn.ibizlab.plm.core.projmgmt.service.IProjectService iBzSysProjectDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectbefore_createbegin"
            when
            then
            end

            //逻辑处理节点[绑定members]
            rule "bindparam1"
            ruleflow-group "projectbefore_createbindparam1"
            when
            then
                        update(projectbefore_createdefault);//更新fact中变量值
                        update(projectbefore_createmember);//更新fact中变量值
                        update(projectbefore_createmembers);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "projectbefore_createend1"
            when
            then
                        update(projectbefore_createdefault);//更新fact中变量值
                        update(projectbefore_createmember);//更新fact中变量值
                        update(projectbefore_createmembers);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "projectbefore_createloopsubcall1"
            when
            then
                        update(projectbefore_createdefault);//更新fact中变量值
                        update(projectbefore_createmember);//更新fact中变量值
                        update(projectbefore_createmembers);//更新fact中变量值
            end

            //逻辑处理节点[重置id]
            rule "prepareparam1"
            ruleflow-group "projectbefore_createprepareparam1"
            when
            then
                                projectbefore_createmember.set("id",null);
                        update(projectbefore_createdefault);//更新fact中变量值
                        update(projectbefore_createmember);//更新fact中变量值
                        update(projectbefore_createmembers);//更新fact中变量值
            end