package cn.ibizlab.plm.projmgmt.logic.projectlogic.change_parent;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Project projectchange_parentdefault;
        global cn.ibizlab.plm.core.projmgmt.service.IProjectService iBzSysProjectDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectchange_parentbegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "projectchange_parentdebugparam1"
            when
            then
                        update(projectchange_parentdefault);//更新fact中变量值
            end