package cn.ibizlab.plm.projmgmt.logic.projectlogic.copy_work_item;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Project projectcopy_work_itemdefault;
        global cn.ibizlab.plm.core.projmgmt.service.IProjectService iBzSysProjectDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectcopy_work_itembegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "projectcopy_work_itemdebugparam1"
            when
            then
                        update(projectcopy_work_itemdefault);//更新fact中变量值
            end