package cn.ibizlab.plm.projmgmt.logic.projectlogic.create_default_addon;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectcreate_default_addondefault;
                global cn.ibizlab.plm.core.base.domain.addon projectcreate_default_addonaddon_filter;
                global cn.ibizlab.plm.core.base.domain.addon projectcreate_default_addonaddon_page;
                global cn.ibizlab.plm.core.base.domain.addon projectcreate_default_addonfor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.addon projectcreate_default_addonnew_addon;
                    global cn.ibizlab.plm.core.base.service.IaddonService addonservice;
        global cn.ibizlab.plm.core.projmgmt.service.IprojectService iBzSysProjectDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectcreate_default_addonbegin"
            when
            then
            end

            //逻辑处理节点[准备项目组件过滤参数]
            rule "prepareparam1"
            ruleflow-group "projectcreate_default_addonprepareparam1"
            when
            then
                            projectcreate_default_addonaddon_filter.set("n_owner_type_eq","project");
                            projectcreate_default_addonaddon_filter.set("n_owner_id_isnull","1");
                            projectcreate_default_addonaddon_filter.set("n_owner_subtype_eq",projectcreate_default_addondefault.get("type"));
                        update(projectcreate_default_addondefault);//更新fact中变量值
                        update(projectcreate_default_addonaddon_filter);//更新fact中变量值
                        update(projectcreate_default_addonaddon_page);//更新fact中变量值
                        update(projectcreate_default_addonfor_temp_obj);//更新fact中变量值
                        update(projectcreate_default_addonnew_addon);//更新fact中变量值
            end

            //逻辑处理节点[获取项目默认组件配置]
            rule "dedataset1"
            ruleflow-group "projectcreate_default_addondedataset1"
            when
            then
                        update(projectcreate_default_addondefault);//更新fact中变量值
                        update(projectcreate_default_addonaddon_filter);//更新fact中变量值
                        update(projectcreate_default_addonaddon_page);//更新fact中变量值
                        update(projectcreate_default_addonfor_temp_obj);//更新fact中变量值
                        update(projectcreate_default_addonnew_addon);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "projectcreate_default_addonloopsubcall1"
            when
            then
                        update(projectcreate_default_addondefault);//更新fact中变量值
                        update(projectcreate_default_addonaddon_filter);//更新fact中变量值
                        update(projectcreate_default_addonaddon_page);//更新fact中变量值
                        update(projectcreate_default_addonfor_temp_obj);//更新fact中变量值
                        update(projectcreate_default_addonnew_addon);//更新fact中变量值
            end

            //逻辑处理节点[组件填充数据属性]
            rule "prepareparam2"
            ruleflow-group "projectcreate_default_addonprepareparam2"
            when
            then
                            projectcreate_default_addonnew_addon.set("isenabled",projectcreate_default_addonfor_temp_obj.get("isenabled"));
                            projectcreate_default_addonnew_addon.set("ownersubtype",projectcreate_default_addonfor_temp_obj.get("ownersubtype"));
                            projectcreate_default_addonnew_addon.set("ownerid",projectcreate_default_addondefault.get("id"));
                            projectcreate_default_addonnew_addon.set("ownertype",projectcreate_default_addonfor_temp_obj.get("ownertype"));
                            projectcreate_default_addonnew_addon.set("addontype",projectcreate_default_addonfor_temp_obj.get("addontype"));
                            projectcreate_default_addonnew_addon.set("description",projectcreate_default_addonfor_temp_obj.get("description"));
                            projectcreate_default_addonnew_addon.set("name",projectcreate_default_addonfor_temp_obj.get("name"));
                            projectcreate_default_addonnew_addon.set("ordervalue",projectcreate_default_addonfor_temp_obj.get("ordervalue"));
                        update(projectcreate_default_addondefault);//更新fact中变量值
                        update(projectcreate_default_addonaddon_filter);//更新fact中变量值
                        update(projectcreate_default_addonaddon_page);//更新fact中变量值
                        update(projectcreate_default_addonfor_temp_obj);//更新fact中变量值
                        update(projectcreate_default_addonnew_addon);//更新fact中变量值
            end

            //逻辑处理节点[生成项目组件信息]
            rule "deaction1"
            ruleflow-group "projectcreate_default_addondeaction1"
            when
            then
                        addonservice.create(projectcreate_default_addonnew_addon);
                        update(projectcreate_default_addondefault);//更新fact中变量值
                        update(projectcreate_default_addonaddon_filter);//更新fact中变量值
                        update(projectcreate_default_addonaddon_page);//更新fact中变量值
                        update(projectcreate_default_addonfor_temp_obj);//更新fact中变量值
                        update(projectcreate_default_addonnew_addon);//更新fact中变量值
            end