package cn.ibizlab.plm.projmgmt.logic.projectlogic.favorite;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Project projectfavoritedefault;
                global java.util.Map projectfavoritectx;
                global cn.ibizlab.plm.core.base.domain.Favorite projectfavoritefavorite;
                    global cn.ibizlab.plm.core.base.service.IFavoriteService favoriteservice;
        global cn.ibizlab.plm.core.projmgmt.service.IProjectService iBzSysProjectDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectfavoritebegin"
            when
            then
            end

            //逻辑处理节点[填充用户标识和收藏业务对象标识]
            rule "prepareparam1"
            ruleflow-group "projectfavoriteprepareparam1"
            when
            then
                                projectfavoritefavorite.set("createman",curuser.getSessionParams().get("srfuserid"));
                            projectfavoritefavorite.set("ownertype","project");
                            projectfavoritefavorite.set("ownerid",projectfavoritedefault.get("owner_id"));
                        update(projectfavoritedefault);//更新fact中变量值
                        update(projectfavoritectx);//更新fact中变量值
                        update(projectfavoritefavorite);//更新fact中变量值
            end

            //逻辑处理节点[生成收藏数据]
            rule "deaction1"
            ruleflow-group "projectfavoritedeaction1"
            when
            then
                        favoriteservice.save(projectfavoritefavorite);
                        update(projectfavoritedefault);//更新fact中变量值
                        update(projectfavoritectx);//更新fact中变量值
                        update(projectfavoritefavorite);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "projectfavoriteend1"
            when
            then
                        update(projectfavoritedefault);//更新fact中变量值
                        update(projectfavoritectx);//更新fact中变量值
                        update(projectfavoritefavorite);//更新fact中变量值
            end