package cn.ibizlab.plm.projmgmt.logic.projectlogic.project_automatic_change_state;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectproject_automatic_change_statedefault;
                global java.util.Map projectproject_automatic_change_statehas_child_data;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectproject_automatic_change_stateproject_filter;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectproject_automatic_change_stateproject_temp;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectproject_automatic_change_stateprojects;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectproject_automatic_change_stateselect_result;
                    global cn.ibizlab.plm.core.projmgmt.service.IprojectService projectservice;
        global cn.ibizlab.plm.core.projmgmt.service.IprojectService iBzSysProjectDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectproject_automatic_change_statebegin"
            when
            then
            end

            //逻辑处理节点[设置逾期项目过滤条件]
            rule "prepareparam1"
            ruleflow-group "projectproject_automatic_change_stateprepareparam1"
            when
            then
                            projectproject_automatic_change_stateproject_filter.set("n_is_deleted_eq","0");
                            projectproject_automatic_change_stateproject_filter.set("n_id_eq",projectproject_automatic_change_statedefault.get("id"));
                            projectproject_automatic_change_stateproject_filter.set("n_is_archived_eq","0");
                            projectproject_automatic_change_stateproject_filter.set("n_state_type_noteq","completed");
                            projectproject_automatic_change_stateproject_filter.set("size","1000");
                        update(projectproject_automatic_change_statedefault);//更新fact中变量值
                        update(projectproject_automatic_change_statehas_child_data);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_filter);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_temp);//更新fact中变量值
                        update(projectproject_automatic_change_stateprojects);//更新fact中变量值
                        update(projectproject_automatic_change_stateselect_result);//更新fact中变量值
            end

            //逻辑处理节点[获取符合条件的逾期项目]
            rule "dedataset1"
            ruleflow-group "projectproject_automatic_change_statededataset1"
            when
            then
                        update(projectproject_automatic_change_statedefault);//更新fact中变量值
                        update(projectproject_automatic_change_statehas_child_data);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_filter);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_temp);//更新fact中变量值
                        update(projectproject_automatic_change_stateprojects);//更新fact中变量值
                        update(projectproject_automatic_change_stateselect_result);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "projectproject_automatic_change_stateend2"
            when
            then
                        update(projectproject_automatic_change_statedefault);//更新fact中变量值
                        update(projectproject_automatic_change_statehas_child_data);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_filter);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_temp);//更新fact中变量值
                        update(projectproject_automatic_change_stateprojects);//更新fact中变量值
                        update(projectproject_automatic_change_stateselect_result);//更新fact中变量值
            end

            //逻辑处理节点[循环执行]
            rule "loopsubcall1"
            ruleflow-group "projectproject_automatic_change_stateloopsubcall1"
            when
            then
                        update(projectproject_automatic_change_statedefault);//更新fact中变量值
                        update(projectproject_automatic_change_statehas_child_data);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_filter);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_temp);//更新fact中变量值
                        update(projectproject_automatic_change_stateprojects);//更新fact中变量值
                        update(projectproject_automatic_change_stateselect_result);//更新fact中变量值
            end

            //逻辑处理节点[空节点，承载判断]
            rule "prepareparam3"
            ruleflow-group "projectproject_automatic_change_stateprepareparam3"
            when
            then
                        update(projectproject_automatic_change_statedefault);//更新fact中变量值
                        update(projectproject_automatic_change_statehas_child_data);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_filter);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_temp);//更新fact中变量值
                        update(projectproject_automatic_change_stateprojects);//更新fact中变量值
                        update(projectproject_automatic_change_stateselect_result);//更新fact中变量值
            end

            //逻辑处理节点[判断当前项目是否存在工作项]
            rule "rawsqlcall1"
            ruleflow-group "projectproject_automatic_change_staterawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",projectproject_automatic_change_statedefault.get("id"));
    String strSql="SELECT count(1) as work_item_data FROM work_item WHERE PROJECT_ID = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysProjectDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                projectproject_automatic_change_statehas_child_data.putAll(entity);
                            }
                        update(projectproject_automatic_change_statedefault);//更新fact中变量值
                        update(projectproject_automatic_change_statehas_child_data);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_filter);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_temp);//更新fact中变量值
                        update(projectproject_automatic_change_stateprojects);//更新fact中变量值
                        update(projectproject_automatic_change_stateselect_result);//更新fact中变量值
            end

            //逻辑处理节点[设置状态为延期]
            rule "prepareparam2"
            ruleflow-group "projectproject_automatic_change_stateprepareparam2"
            when
            then
                            projectproject_automatic_change_stateproject_temp.set("state","delay");
                        update(projectproject_automatic_change_statedefault);//更新fact中变量值
                        update(projectproject_automatic_change_statehas_child_data);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_filter);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_temp);//更新fact中变量值
                        update(projectproject_automatic_change_stateprojects);//更新fact中变量值
                        update(projectproject_automatic_change_stateselect_result);//更新fact中变量值
            end

            //逻辑处理节点[设置状态为预警]
            rule "prepareparam4"
            ruleflow-group "projectproject_automatic_change_stateprepareparam4"
            when
            then
                            projectproject_automatic_change_stateproject_temp.set("state","warning");
                        update(projectproject_automatic_change_statedefault);//更新fact中变量值
                        update(projectproject_automatic_change_statehas_child_data);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_filter);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_temp);//更新fact中变量值
                        update(projectproject_automatic_change_stateprojects);//更新fact中变量值
                        update(projectproject_automatic_change_stateselect_result);//更新fact中变量值
            end

            //逻辑处理节点[汇聚预计、消耗工时]
            rule "rawsqlcall2"
            ruleflow-group "projectproject_automatic_change_staterawsqlcall2"
            when
            then
    Map param =new HashMap();
        param.put("param0",projectproject_automatic_change_stateproject_temp.get("id"));
    String strSql="SELECT     SUM(CASE WHEN es.name = 'estimated_workload' THEN es.DECIMAL_VALUE ELSE 0 END) AS estimated_workload,     SUM(CASE WHEN es.name = 'actual_workload' THEN es.DECIMAL_VALUE ELSE 0 END) AS actual_workload FROM     project p JOIN     work_item wi ON p.id = wi.project_id JOIN     extend_storage es ON wi.id = es.owner_id WHERE     p.id = #{et.param0}     AND es.owner_type = 'work_item'     AND (es.name = 'estimated_workload' OR es.name = 'actual_workload')     AND wi.pid is null;";
                        java.util.List<JSONObject> entities=iBzSysProjectDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    projectproject_automatic_change_stateselect_result.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(projectproject_automatic_change_statedefault);//更新fact中变量值
                        update(projectproject_automatic_change_statehas_child_data);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_filter);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_temp);//更新fact中变量值
                        update(projectproject_automatic_change_stateprojects);//更新fact中变量值
                        update(projectproject_automatic_change_stateselect_result);//更新fact中变量值
            end

            //逻辑处理节点[设置状态为正常]
            rule "prepareparam5"
            ruleflow-group "projectproject_automatic_change_stateprepareparam5"
            when
            then
                            projectproject_automatic_change_stateproject_temp.set("state","normal");
                        update(projectproject_automatic_change_statedefault);//更新fact中变量值
                        update(projectproject_automatic_change_statehas_child_data);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_filter);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_temp);//更新fact中变量值
                        update(projectproject_automatic_change_stateprojects);//更新fact中变量值
                        update(projectproject_automatic_change_stateselect_result);//更新fact中变量值
            end

            //逻辑处理节点[直接sql调用]
            rule "rawsqlcall3"
            ruleflow-group "projectproject_automatic_change_staterawsqlcall3"
            when
            then
    Map param =new HashMap();
        param.put("param0",projectproject_automatic_change_stateproject_temp.get("id"));
    String strSql="SELECT     MIN(wi.ACTUAL_START_AT) AS ACTUAL_START_AT FROM     project p JOIN     work_item wi ON p.id = wi.project_id WHERE     p.id = #{et.param0} ";
                        java.util.List<JSONObject> entities=iBzSysProjectDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    projectproject_automatic_change_stateselect_result.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(projectproject_automatic_change_statedefault);//更新fact中变量值
                        update(projectproject_automatic_change_statehas_child_data);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_filter);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_temp);//更新fact中变量值
                        update(projectproject_automatic_change_stateprojects);//更新fact中变量值
                        update(projectproject_automatic_change_stateselect_result);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam6"
            ruleflow-group "projectproject_automatic_change_stateprepareparam6"
            when
            then
                            projectproject_automatic_change_stateproject_temp.set("expectedtime",projectproject_automatic_change_stateselect_result.get("estimated_workload"));
                            projectproject_automatic_change_stateproject_temp.set("consumetime",projectproject_automatic_change_stateselect_result.get("actual_workload"));
                            projectproject_automatic_change_stateproject_temp.set("actualstartat",projectproject_automatic_change_stateselect_result.get("actualstartat"));
                        update(projectproject_automatic_change_statedefault);//更新fact中变量值
                        update(projectproject_automatic_change_statehas_child_data);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_filter);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_temp);//更新fact中变量值
                        update(projectproject_automatic_change_stateprojects);//更新fact中变量值
                        update(projectproject_automatic_change_stateselect_result);//更新fact中变量值
            end

            //逻辑处理节点[更新项目状态]
            rule "deaction1"
            ruleflow-group "projectproject_automatic_change_statedeaction1"
            when
            then
                        projectservice.update(projectproject_automatic_change_stateproject_temp);
                        update(projectproject_automatic_change_statedefault);//更新fact中变量值
                        update(projectproject_automatic_change_statehas_child_data);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_filter);//更新fact中变量值
                        update(projectproject_automatic_change_stateproject_temp);//更新fact中变量值
                        update(projectproject_automatic_change_stateprojects);//更新fact中变量值
                        update(projectproject_automatic_change_stateselect_result);//更新fact中变量值
            end