package cn.ibizlab.plm.projmgmt.logic.projectlogic.recover;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Project projectrecoverdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.Project projectrecoverupdate_obj;
                    global cn.ibizlab.plm.core.projmgmt.service.IProjectService projectservice;
        global cn.ibizlab.plm.core.projmgmt.service.IProjectService iBzSysProjectDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectrecoverbegin"
            when
            then
            end

            //逻辑处理节点[设置恢复参数]
            rule "prepareparam1"
            ruleflow-group "projectrecoverprepareparam1"
            when
            then
                            projectrecoverupdate_obj.set("isdeleted","0");
                            projectrecoverupdate_obj.set("id",projectrecoverdefault.get("id"));
                        update(projectrecoverdefault);//更新fact中变量值
                        update(projectrecoverupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[执行更新]
            rule "deaction1"
            ruleflow-group "projectrecoverdeaction1"
            when
            then
                        projectservice.update(projectrecoverupdate_obj);
                        update(projectrecoverdefault);//更新fact中变量值
                        update(projectrecoverupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[恢复最近访问]
            rule "rawsqlcall1"
            ruleflow-group "projectrecoverrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",projectrecoverdefault.get("id"));
    String strSql="update recent set IS_DELETED=0 where owner_id=#{et.param0} and owner_subtype='project'";
                        iBzSysProjectDefaultService.execute(strSql,param);//SQL调用
                        update(projectrecoverdefault);//更新fact中变量值
                        update(projectrecoverupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "projectrecoverend1"
            when
            then
                        update(projectrecoverdefault);//更新fact中变量值
                        update(projectrecoverupdate_obj);//更新fact中变量值
            end