package cn.ibizlab.plm.base.logic.commentlogic.after_create_notify;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.Comment commentafter_create_notifydefault;
                    global cn.ibizlab.plm.core.base.service.ICommentService commentservice;
        global cn.ibizlab.plm.core.base.service.ICommentService iBzSysCommentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "commentafter_create_notifybegin"
            when
            then
            end

            //逻辑处理节点[评论工作项通知]
            rule "denotify1"
            ruleflow-group "commentafter_create_notifydenotify1"
            when
            then
                        update(commentafter_create_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[评论需求通知]
            rule "denotify2"
            ruleflow-group "commentafter_create_notifydenotify2"
            when
            then
                        update(commentafter_create_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[评论工单通知]
            rule "denotify3"
            ruleflow-group "commentafter_create_notifydenotify3"
            when
            then
                        update(commentafter_create_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[评论客户通知]
            rule "denotify4"
            ruleflow-group "commentafter_create_notifydenotify4"
            when
            then
                        update(commentafter_create_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[评论测试用例通知]
            rule "denotify5"
            ruleflow-group "commentafter_create_notifydenotify5"
            when
            then
                        update(commentafter_create_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[评论执行用例通知]
            rule "denotify6"
            ruleflow-group "commentafter_create_notifydenotify6"
            when
            then
                        update(commentafter_create_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[评论页面通知]
            rule "denotify7"
            ruleflow-group "commentafter_create_notifydenotify7"
            when
            then
                        update(commentafter_create_notifydefault);//更新fact中变量值
            end