package cn.ibizlab.plm.base.logic.commentlogic.del_comment;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.Comment commentdel_commentdefault;
                    global cn.ibizlab.plm.core.base.service.ICommentService commentservice;
        global cn.ibizlab.plm.core.base.service.ICommentService iBzSysCommentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "commentdel_commentbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "commentdel_commentprepareparam1"
            when
            then
                            commentdel_commentdefault.set("content","<p><del>该评论已删除</del></p>");
                        update(commentdel_commentdefault);//更新fact中变量值
            end

            //逻辑处理节点[将评论内容修改为"已删除"]
            rule "deaction1"
            ruleflow-group "commentdel_commentdeaction1"
            when
            then
                        commentservice.update(commentdel_commentdefault);
                        update(commentdel_commentdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "commentdel_commentend1"
            when
            then
                        update(commentdel_commentdefault);//更新fact中变量值
            end