package cn.ibizlab.plm.base.logic.commentlogic.delete;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.comment commentdeletedefault;
                    global cn.ibizlab.plm.core.base.service.IcommentService commentservice;
        global cn.ibizlab.plm.core.base.service.IcommentService iBzSysCommentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "commentdeletebegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "commentdeleteprepareparam1"
            when
            then
                            commentdeletedefault.set("content","<p><del>该评论已删除</del></p>");
                        update(commentdeletedefault);//更新fact中变量值
            end

            //逻辑处理节点[将评论内容修改为"已删除"]
            rule "deaction1"
            ruleflow-group "commentdeletedeaction1"
            when
            then
                        commentservice.update(commentdeletedefault);
                        update(commentdeletedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "commentdeleteend1"
            when
            then
                        update(commentdeletedefault);//更新fact中变量值
            end