package cn.ibizlab.plm.base.logic.worklogic.add_project_portfolio;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.Work workadd_project_portfoliodefault;
                global cn.ibizlab.plm.core.base.domain.Work workadd_project_portfoliocreate_obj;
                global cn.ibizlab.plm.core.base.domain.Portfolio workadd_project_portfoliofor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.Portfolio workadd_project_portfoliosrfactionparam;
                    global cn.ibizlab.plm.core.base.service.IWorkService workservice;
        global cn.ibizlab.plm.core.base.service.IWorkService iBzSysWorkDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "workadd_project_portfoliobegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "workadd_project_portfolioprepareparam2"
            when
            then
                            workadd_project_portfoliosrfactionparam.set("",workadd_project_portfoliodefault.get("srfactionparam"));
                        update(workadd_project_portfoliodefault);//更新fact中变量值
                        update(workadd_project_portfoliocreate_obj);//更新fact中变量值
                        update(workadd_project_portfoliofor_temp_obj);//更新fact中变量值
                        update(workadd_project_portfoliosrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "workadd_project_portfolioloopsubcall1"
            when
            then
                        update(workadd_project_portfoliodefault);//更新fact中变量值
                        update(workadd_project_portfoliocreate_obj);//更新fact中变量值
                        update(workadd_project_portfoliofor_temp_obj);//更新fact中变量值
                        update(workadd_project_portfoliosrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[重置参数]
            rule "resetparam1"
            ruleflow-group "workadd_project_portfolioresetparam1"
            when
            then
                        update(workadd_project_portfoliodefault);//更新fact中变量值
                        update(workadd_project_portfoliocreate_obj);//更新fact中变量值
                        update(workadd_project_portfoliofor_temp_obj);//更新fact中变量值
                        update(workadd_project_portfoliosrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "workadd_project_portfolioprepareparam1"
            when
            then
                            workadd_project_portfoliocreate_obj.set("principalid",workadd_project_portfoliofor_temp_obj.get("id"));
                            workadd_project_portfoliocreate_obj.set("portfolioid",workadd_project_portfoliodefault.get("portfolio"));
                            workadd_project_portfoliocreate_obj.set("principaltype","project_portfolio");
                        update(workadd_project_portfoliodefault);//更新fact中变量值
                        update(workadd_project_portfoliocreate_obj);//更新fact中变量值
                        update(workadd_project_portfoliofor_temp_obj);//更新fact中变量值
                        update(workadd_project_portfoliosrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "workadd_project_portfoliodeaction1"
            when
            then
                        workservice.save(workadd_project_portfoliocreate_obj);
                        update(workadd_project_portfoliodefault);//更新fact中变量值
                        update(workadd_project_portfoliocreate_obj);//更新fact中变量值
                        update(workadd_project_portfoliofor_temp_obj);//更新fact中变量值
                        update(workadd_project_portfoliosrfactionparam);//更新fact中变量值
            end