package cn.ibizlab.plm.base.logic.worklogic.add_item_set;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.Work workadd_item_setdefault;
                global cn.ibizlab.plm.core.base.domain.Work workadd_item_setcreate_obj;
                global cn.ibizlab.plm.core.base.domain.Portfolio workadd_item_setfor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.Portfolio workadd_item_setsrfactionparam;
                    global cn.ibizlab.plm.core.base.service.IWorkService workservice;
        global cn.ibizlab.plm.core.base.service.IWorkService iBzSysWorkDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "workadd_item_setbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "workadd_item_setprepareparam2"
            when
            then
                            workadd_item_setsrfactionparam.set("",workadd_item_setdefault.get("srfactionparam"));
                        update(workadd_item_setdefault);//更新fact中变量值
                        update(workadd_item_setcreate_obj);//更新fact中变量值
                        update(workadd_item_setfor_temp_obj);//更新fact中变量值
                        update(workadd_item_setsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "workadd_item_setloopsubcall1"
            when
            then
                        update(workadd_item_setdefault);//更新fact中变量值
                        update(workadd_item_setcreate_obj);//更新fact中变量值
                        update(workadd_item_setfor_temp_obj);//更新fact中变量值
                        update(workadd_item_setsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[重置参数]
            rule "resetparam1"
            ruleflow-group "workadd_item_setresetparam1"
            when
            then
                        update(workadd_item_setdefault);//更新fact中变量值
                        update(workadd_item_setcreate_obj);//更新fact中变量值
                        update(workadd_item_setfor_temp_obj);//更新fact中变量值
                        update(workadd_item_setsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "workadd_item_setprepareparam1"
            when
            then
                            workadd_item_setcreate_obj.set("principalid",workadd_item_setfor_temp_obj.get("id"));
                            workadd_item_setcreate_obj.set("portfolioid",workadd_item_setdefault.get("portfolio"));
                            workadd_item_setcreate_obj.set("principaltype","item_set");
                        update(workadd_item_setdefault);//更新fact中变量值
                        update(workadd_item_setcreate_obj);//更新fact中变量值
                        update(workadd_item_setfor_temp_obj);//更新fact中变量值
                        update(workadd_item_setsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "workadd_item_setdeaction1"
            when
            then
                        workservice.create(workadd_item_setcreate_obj);
                        update(workadd_item_setdefault);//更新fact中变量值
                        update(workadd_item_setcreate_obj);//更新fact中变量值
                        update(workadd_item_setfor_temp_obj);//更新fact中变量值
                        update(workadd_item_setsrfactionparam);//更新fact中变量值
            end