package cn.ibizlab.plm.base.logic.portfolio_memberlogic.remove_project_set_member_notify;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.portfolio_member portfolio_memberremove_project_set_member_notifydefault;
                    global cn.ibizlab.plm.core.base.service.Iportfolio_memberService portfolio_memberservice;
        global cn.ibizlab.plm.core.base.service.Iportfolio_memberService iBzSysPortfolio_memberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "portfolio_memberremove_project_set_member_notifybegin"
            when
            then
            end

            //逻辑处理节点[获取文件夹成员数据]
            rule "deaction1"
            ruleflow-group "portfolio_memberremove_project_set_member_notifydeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(portfolio_memberservice.get(portfolio_memberremove_project_set_member_notifydefault.getId()),portfolio_memberremove_project_set_member_notifydefault);
                        update(portfolio_memberremove_project_set_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[绑定当前操作人]
            rule "prepareparam1"
            ruleflow-group "portfolio_memberremove_project_set_member_notifyprepareparam1"
            when
            then
                                portfolio_memberremove_project_set_member_notifydefault.set("updateman",curuser.getSessionParams().get("srfpersonid"));
                        update(portfolio_memberremove_project_set_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[获取当前操作时间]
            rule "rawsfcode1"
            ruleflow-group "portfolio_memberremove_project_set_member_notifyrawsfcode1"
            when
            then
                        update(portfolio_memberremove_project_set_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[移除成员通知]
            rule "denotify1"
            ruleflow-group "portfolio_memberremove_project_set_member_notifydenotify1"
            when
            then
                        update(portfolio_memberremove_project_set_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "portfolio_memberremove_project_set_member_notifyend1"
            when
            then
                        update(portfolio_memberremove_project_set_member_notifydefault);//更新fact中变量值
            end