package cn.ibizlab.plm.testmgmt.logic.test_case_templatelogic.choose_case_template;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case_template test_case_templatechoose_case_templatedefault;
                    global cn.ibizlab.plm.core.testmgmt.service.Itest_case_templateService test_case_templateservice;
        global cn.ibizlab.plm.core.testmgmt.service.Itest_case_templateService iBzSysTest_case_templateDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_case_templatechoose_case_templatebegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_case_templatechoose_case_templateend1"
            when
            then
                        update(test_case_templatechoose_case_templatedefault);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "test_case_templatechoose_case_templatedebugparam1"
            when
            then
                        update(test_case_templatechoose_case_templatedefault);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "test_case_templatechoose_case_templatedeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(test_case_templateservice.get(test_case_templatechoose_case_templatedefault.getId()),test_case_templatechoose_case_templatedefault);
                        update(test_case_templatechoose_case_templatedefault);//更新fact中变量值
            end