package cn.ibizlab.plm.extension.logic.aboutlogic.checkversion;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.extension.domain.ABOUT aboutcheckversiondefault;
        global cn.ibizlab.plm.core.extension.service.IABOUTService iBzSysAboutDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "aboutcheckversionbegin"
            when
            then
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode_01"
            ruleflow-group "aboutcheckversionrawsfcode_01"
            when
            then
                        update(aboutcheckversiondefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "aboutcheckversionend_01"
            when
            then
                        update(aboutcheckversiondefault);//更新fact中变量值
            end