package cn.ibizlab.plm.extension.logic.aboutlogic.getaboutinfo;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.extension.domain.ABOUT aboutgetaboutinfodefault;
        global cn.ibizlab.plm.core.extension.service.IABOUTService iBzSysAboutDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "aboutgetaboutinfobegin"
            when
            then
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode_01"
            ruleflow-group "aboutgetaboutinforawsfcode_01"
            when
            then
                        update(aboutgetaboutinfodefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "aboutgetaboutinfoend1"
            when
            then
                        update(aboutgetaboutinfodefault);//更新fact中变量值
            end