package cn.ibizlab.plm.base.logic.portfoliologic.un_favorite;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.portfolio portfolioun_favoritedefault;
                global cn.ibizlab.plm.core.base.domain.portfolio portfolioun_favoriteupdateobj;
        global cn.ibizlab.plm.core.base.service.IportfolioService iBzSysPortfolioDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "portfolioun_favoritebegin"
            when
            then
            end

            //逻辑处理节点[删除收藏数据]
            rule "rawsqlcall1"
            ruleflow-group "portfolioun_favoriterawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",curuser.getSessionParams().get("srfuserid"));
        param.put("param1",portfolioun_favoritedefault.get("owner_id"));
    String strSql="delete from `favorite` where create_man = #{et.param0} and owner_id = #{et.param1}";
                        iBzSysPortfolioDefaultService.execute(strSql,param);//SQL调用
                        update(portfolioun_favoritedefault);//更新fact中变量值
                        update(portfolioun_favoriteupdateobj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "portfolioun_favoriteend1"
            when
            then
                        update(portfolioun_favoritedefault);//更新fact中变量值
                        update(portfolioun_favoriteupdateobj);//更新fact中变量值
            end