package cn.ibizlab.plm.base.logic.templatelogic.save_template;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.template templatesave_templatedefault;
                    global cn.ibizlab.plm.core.base.service.ItemplateService templateservice;
        global cn.ibizlab.plm.core.base.service.ItemplateService iBzSysTemplateDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "templatesave_templatebegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "templatesave_templateend1"
            when
            then
                        update(templatesave_templatedefault);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode1"
            ruleflow-group "templatesave_templaterawsfcode1"
            when
            then
                        update(templatesave_templatedefault);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "templatesave_templatedeaction1"
            when
            then
                        templateservice.save(templatesave_templatedefault);
                        update(templatesave_templatedefault);//更新fact中变量值
            end