package cn.ibizlab.plm.base.logic.attentionlogic.after_create_notify;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.attention attentionafter_create_notifydefault;
                    global cn.ibizlab.plm.core.base.service.IattentionService attentionservice;
        global cn.ibizlab.plm.core.base.service.IattentionService iBzSysAttentionDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attentionafter_create_notifybegin"
            when
            then
            end

            //逻辑处理节点[提醒关注通知]
            rule "denotify1"
            ruleflow-group "attentionafter_create_notifydenotify1"
            when
            then
                        update(attentionafter_create_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[提醒关注页面通知]
            rule "denotify2"
            ruleflow-group "attentionafter_create_notifydenotify2"
            when
            then
                        update(attentionafter_create_notifydefault);//更新fact中变量值
            end