package cn.ibizlab.plm.projmgmt.logic.projectlogic.activate;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectactivatedefault;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectactivateupdate_obj;
                    global cn.ibizlab.plm.core.projmgmt.service.IprojectService projectservice;
        global cn.ibizlab.plm.core.projmgmt.service.IprojectService iBzSysProjectDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectactivatebegin"
            when
            then
            end

            //逻辑处理节点[设置激活状态]
            rule "prepareparam1"
            ruleflow-group "projectactivateprepareparam1"
            when
            then
                            projectactivateupdate_obj.set("isarchived","0");
                            projectactivateupdate_obj.set("id",projectactivatedefault.get("id"));
                        update(projectactivatedefault);//更新fact中变量值
                        update(projectactivateupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[激活]
            rule "deaction1"
            ruleflow-group "projectactivatedeaction1"
            when
            then
                        projectservice.update(projectactivateupdate_obj);
                        update(projectactivatedefault);//更新fact中变量值
                        update(projectactivateupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "projectactivateend1"
            when
            then
                        update(projectactivatedefault);//更新fact中变量值
                        update(projectactivateupdate_obj);//更新fact中变量值
            end