package cn.ibizlab.plm.projmgmt.logic.projectlogic.auto_create_guideline;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectauto_create_guidelinedefault;
                global cn.ibizlab.plm.core.testmgmt.domain.guideline projectauto_create_guidelinefor_obj_guideline;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage projectauto_create_guidelinefor_obj_review_stage;
                global cn.ibizlab.plm.core.testmgmt.domain.guideline projectauto_create_guidelineguideline;
                global cn.ibizlab.plm.core.testmgmt.domain.guideline projectauto_create_guidelineguideline_filter;
                global cn.ibizlab.plm.core.testmgmt.domain.guideline projectauto_create_guidelineguideline_pages;
                global cn.ibizlab.plm.core.testmgmt.domain.guideline projectauto_create_guidelinenew_guideline;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage projectauto_create_guidelinenew_review_stage;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage projectauto_create_guidelinereview_stage_list;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage projectauto_create_guidelinestage_arr;
                    global cn.ibizlab.plm.core.testmgmt.service.IguidelineService guidelineservice;
        global cn.ibizlab.plm.core.projmgmt.service.IprojectService iBzSysProjectDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectauto_create_guidelinebegin"
            when
            then
            end

            //逻辑处理节点[设置过滤参数]
            rule "prepareparam1"
            ruleflow-group "projectauto_create_guidelineprepareparam1"
            when
            then
                            projectauto_create_guidelineguideline_filter.set("n_object_type_eq","PROJECT");
                            projectauto_create_guidelineguideline_filter.set("n_scope_id_isnull","1");
                        update(projectauto_create_guidelinedefault);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelineguideline);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_filter);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_pages);//更新fact中变量值
                        update(projectauto_create_guidelinenew_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinenew_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelinereview_stage_list);//更新fact中变量值
                        update(projectauto_create_guidelinestage_arr);//更新fact中变量值
            end

            //逻辑处理节点[查询项目全局流程规则]
            rule "dedataset1"
            ruleflow-group "projectauto_create_guidelinededataset1"
            when
            then
                        update(projectauto_create_guidelinedefault);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelineguideline);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_filter);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_pages);//更新fact中变量值
                        update(projectauto_create_guidelinenew_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinenew_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelinereview_stage_list);//更新fact中变量值
                        update(projectauto_create_guidelinestage_arr);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "projectauto_create_guidelineloopsubcall1"
            when
            then
                        update(projectauto_create_guidelinedefault);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelineguideline);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_filter);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_pages);//更新fact中变量值
                        update(projectauto_create_guidelinenew_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinenew_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelinereview_stage_list);//更新fact中变量值
                        update(projectauto_create_guidelinestage_arr);//更新fact中变量值
            end

            //逻辑处理节点[绑定阶段用于后续循环，设置新建流程准则参数]
            rule "prepareparam2"
            ruleflow-group "projectauto_create_guidelineprepareparam2"
            when
            then
                            projectauto_create_guidelinereview_stage_list.set("",projectauto_create_guidelinefor_obj_guideline.get("reviewstage"));
                            projectauto_create_guidelinenew_guideline.set("isenabled",projectauto_create_guidelinefor_obj_guideline.get("isenabled"));
                            projectauto_create_guidelinenew_guideline.set("name",projectauto_create_guidelinefor_obj_guideline.get("name"));
                            projectauto_create_guidelinenew_guideline.set("subjecttype",projectauto_create_guidelinefor_obj_guideline.get("subjecttype"));
                            projectauto_create_guidelinenew_guideline.set("objecttype",projectauto_create_guidelinefor_obj_guideline.get("objecttype"));
                            projectauto_create_guidelinenew_guideline.set("scopeid",projectauto_create_guidelinedefault.get("id"));
                        update(projectauto_create_guidelinedefault);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelineguideline);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_filter);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_pages);//更新fact中变量值
                        update(projectauto_create_guidelinenew_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinenew_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelinereview_stage_list);//更新fact中变量值
                        update(projectauto_create_guidelinestage_arr);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall2"
            ruleflow-group "projectauto_create_guidelineloopsubcall2"
            when
            then
                        update(projectauto_create_guidelinedefault);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelineguideline);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_filter);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_pages);//更新fact中变量值
                        update(projectauto_create_guidelinenew_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinenew_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelinereview_stage_list);//更新fact中变量值
                        update(projectauto_create_guidelinestage_arr);//更新fact中变量值
            end

            //逻辑处理节点[将阶段数据设置进guideline]
            rule "prepareparam3"
            ruleflow-group "projectauto_create_guidelineprepareparam3"
            when
            then
                            projectauto_create_guidelinenew_guideline.set("reviewstage",projectauto_create_guidelinestage_arr.get(""));
                        update(projectauto_create_guidelinedefault);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelineguideline);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_filter);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_pages);//更新fact中变量值
                        update(projectauto_create_guidelinenew_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinenew_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelinereview_stage_list);//更新fact中变量值
                        update(projectauto_create_guidelinestage_arr);//更新fact中变量值
            end

            //逻辑处理节点[拼接guideline_id]
            rule "rawsfcode1"
            ruleflow-group "projectauto_create_guidelinerawsfcode1"
            when
            then
                        update(projectauto_create_guidelinedefault);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelineguideline);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_filter);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_pages);//更新fact中变量值
                        update(projectauto_create_guidelinenew_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinenew_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelinereview_stage_list);//更新fact中变量值
                        update(projectauto_create_guidelinestage_arr);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "projectauto_create_guidelineend1"
            when
            then
                        update(projectauto_create_guidelinedefault);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelineguideline);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_filter);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_pages);//更新fact中变量值
                        update(projectauto_create_guidelinenew_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinenew_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelinereview_stage_list);//更新fact中变量值
                        update(projectauto_create_guidelinestage_arr);//更新fact中变量值
            end

            //逻辑处理节点[置空阶段的所属id与id]
            rule "prepareparam4"
            ruleflow-group "projectauto_create_guidelineprepareparam4"
            when
            then
                        update(projectauto_create_guidelinedefault);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelineguideline);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_filter);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_pages);//更新fact中变量值
                        update(projectauto_create_guidelinenew_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinenew_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelinereview_stage_list);//更新fact中变量值
                        update(projectauto_create_guidelinestage_arr);//更新fact中变量值
            end

            //逻辑处理节点[创建属于项目的流程准则]
            rule "deaction1"
            ruleflow-group "projectauto_create_guidelinedeaction1"
            when
            then
                        guidelineservice.create(projectauto_create_guidelinenew_guideline);
                        update(projectauto_create_guidelinedefault);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelineguideline);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_filter);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_pages);//更新fact中变量值
                        update(projectauto_create_guidelinenew_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinenew_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelinereview_stage_list);//更新fact中变量值
                        update(projectauto_create_guidelinestage_arr);//更新fact中变量值
            end

            //逻辑处理节点[设置阶段至流程准则]
            rule "prepareparam5"
            ruleflow-group "projectauto_create_guidelineprepareparam5"
            when
            then
                            projectauto_create_guidelinestage_arr.set("",projectauto_create_guidelinefor_obj_review_stage.get(""));
                        update(projectauto_create_guidelinedefault);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelineguideline);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_filter);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_pages);//更新fact中变量值
                        update(projectauto_create_guidelinenew_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinenew_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelinereview_stage_list);//更新fact中变量值
                        update(projectauto_create_guidelinestage_arr);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "projectauto_create_guidelinerenewparam1"
            when
            then
                        update(projectauto_create_guidelinedefault);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelineguideline);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_filter);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_pages);//更新fact中变量值
                        update(projectauto_create_guidelinenew_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinenew_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelinereview_stage_list);//更新fact中变量值
                        update(projectauto_create_guidelinestage_arr);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam2"
            ruleflow-group "projectauto_create_guidelinerenewparam2"
            when
            then
                        update(projectauto_create_guidelinedefault);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinefor_obj_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelineguideline);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_filter);//更新fact中变量值
                        update(projectauto_create_guidelineguideline_pages);//更新fact中变量值
                        update(projectauto_create_guidelinenew_guideline);//更新fact中变量值
                        update(projectauto_create_guidelinenew_review_stage);//更新fact中变量值
                        update(projectauto_create_guidelinereview_stage_list);//更新fact中变量值
                        update(projectauto_create_guidelinestage_arr);//更新fact中变量值
            end