package cn.ibizlab.plm.projmgmt.logic.projectlogic.create_recent;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectcreate_recentdefault;
                global cn.ibizlab.plm.core.base.domain.recent projectcreate_recentrecent;
                    global cn.ibizlab.plm.core.base.service.IrecentService recentservice;
        global cn.ibizlab.plm.core.projmgmt.service.IprojectService iBzSysProjectDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectcreate_recentbegin"
            when
            then
            end

            //逻辑处理节点[准备最近访问参数]
            rule "prepareparam1"
            ruleflow-group "projectcreate_recentprepareparam1"
            when
            then
                            projectcreate_recentrecent.set("ownerid",projectcreate_recentdefault.get("id"));
                            projectcreate_recentrecent.set("recentparentidentifier",projectcreate_recentdefault.get("identifier"));
                            projectcreate_recentrecent.set("recentparentname",projectcreate_recentdefault.get("name"));
                            projectcreate_recentrecent.set("recentparent",projectcreate_recentdefault.get("id"));
                                projectcreate_recentrecent.set("createman",curuser.getSessionParams().get("srfpersonid"));
                            projectcreate_recentrecent.set("type","1");
                            projectcreate_recentrecent.set("name",projectcreate_recentdefault.get("name"));
                            projectcreate_recentrecent.set("ownertype","project");
                            projectcreate_recentrecent.set("ownersubtype",projectcreate_recentdefault.get("type"));
                        update(projectcreate_recentdefault);//更新fact中变量值
                        update(projectcreate_recentrecent);//更新fact中变量值
            end

            //逻辑处理节点[保存最近访问]
            rule "deaction1"
            ruleflow-group "projectcreate_recentdeaction1"
            when
            then
                        recentservice.save(projectcreate_recentrecent);
                        update(projectcreate_recentdefault);//更新fact中变量值
                        update(projectcreate_recentrecent);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "projectcreate_recentend1"
            when
            then
                        update(projectcreate_recentdefault);//更新fact中变量值
                        update(projectcreate_recentrecent);//更新fact中变量值
            end