package cn.ibizlab.plm.projmgmt.logic.projectlogic.delete;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectdeletedefault;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectdeleteupdate_obj;
                    global cn.ibizlab.plm.core.projmgmt.service.IprojectService projectservice;
        global cn.ibizlab.plm.core.projmgmt.service.IprojectService iBzSysProjectDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectdeletebegin"
            when
            then
            end

            //逻辑处理节点[设置删除参数]
            rule "prepareparam1"
            ruleflow-group "projectdeleteprepareparam1"
            when
            then
                            projectdeleteupdate_obj.set("isdeleted","1");
                            projectdeleteupdate_obj.set("id",projectdeletedefault.get("id"));
                        update(projectdeletedefault);//更新fact中变量值
                        update(projectdeleteupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[执行更新]
            rule "deaction1"
            ruleflow-group "projectdeletedeaction1"
            when
            then
                        projectservice.update(projectdeleteupdate_obj);
                        update(projectdeletedefault);//更新fact中变量值
                        update(projectdeleteupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[删除最近访问]
            rule "rawsqlcall1"
            ruleflow-group "projectdeleterawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",projectdeletedefault.get("id"));
    String strSql="update recent set IS_DELETED=1 where owner_id=#{et.param0} and owner_type='project'";
                        iBzSysProjectDefaultService.execute(strSql,param);//SQL调用
                        update(projectdeletedefault);//更新fact中变量值
                        update(projectdeleteupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "projectdeleteend1"
            when
            then
                        update(projectdeletedefault);//更新fact中变量值
                        update(projectdeleteupdate_obj);//更新fact中变量值
            end