package cn.ibizlab.plm.projmgmt.logic.projectlogic.fill_copy_info;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectfill_copy_infodefault;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectfill_copy_infoproject;
                    global cn.ibizlab.plm.core.projmgmt.service.IprojectService projectservice;
        global cn.ibizlab.plm.core.projmgmt.service.IprojectService iBzSysProjectDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectfill_copy_infobegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "projectfill_copy_infoprepareparam1"
            when
            then
                            projectfill_copy_infoproject.set("id",projectfill_copy_infodefault.get("cur_project"));
                        update(projectfill_copy_infodefault);//更新fact中变量值
                        update(projectfill_copy_infoproject);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "projectfill_copy_infodeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(projectservice.get(projectfill_copy_infoproject.getId()),projectfill_copy_infoproject);
                        update(projectfill_copy_infodefault);//更新fact中变量值
                        update(projectfill_copy_infoproject);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "projectfill_copy_infoprepareparam2"
            when
            then
                            projectfill_copy_infoproject.set("id",projectfill_copy_infodefault.get("new_project"));
                        update(projectfill_copy_infodefault);//更新fact中变量值
                        update(projectfill_copy_infoproject);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "projectfill_copy_infoend1"
            when
            then
                        update(projectfill_copy_infodefault);//更新fact中变量值
                        update(projectfill_copy_infoproject);//更新fact中变量值
            end