package cn.ibizlab.plm.projmgmt.logic.projectlogic.other_re_project;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectother_re_projectdefault;
                global cn.ibizlab.plm.core.base.domain.relation projectother_re_projectrelationobj;
                global cn.ibizlab.plm.core.base.domain.relation projectother_re_projectrelationobj2;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.projmgmt.service.IprojectService iBzSysProjectDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectother_re_projectbegin"
            when
            then
            end

            //逻辑处理节点[填充关联参数]
            rule "prepareparam1"
            ruleflow-group "projectother_re_projectprepareparam1"
            when
            then
                            projectother_re_projectrelationobj2.set("targetid",projectother_re_projectdefault.get("target_id"));
                            projectother_re_projectrelationobj2.set("targettype",projectother_re_projectdefault.get("target_type"));
                            projectother_re_projectrelationobj2.set("principalid",projectother_re_projectdefault.get("principal_id"));
                            projectother_re_projectrelationobj2.set("principaltype",projectother_re_projectdefault.get("principal_type"));
                            projectother_re_projectrelationobj.set("targetid",projectother_re_projectdefault.get("principal_id"));
                            projectother_re_projectrelationobj.set("targettype",projectother_re_projectdefault.get("principal_type"));
                            projectother_re_projectrelationobj.set("principalid",projectother_re_projectdefault.get("target_id"));
                            projectother_re_projectrelationobj.set("principaltype",projectother_re_projectdefault.get("target_type"));
                        update(projectother_re_projectdefault);//更新fact中变量值
                        update(projectother_re_projectrelationobj);//更新fact中变量值
                        update(projectother_re_projectrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[生成反向关联数据]
            rule "deaction2"
            ruleflow-group "projectother_re_projectdeaction2"
            when
            then
                        relationservice.create(projectother_re_projectrelationobj2);
                        update(projectother_re_projectdefault);//更新fact中变量值
                        update(projectother_re_projectrelationobj);//更新fact中变量值
                        update(projectother_re_projectrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "projectother_re_projectdebugparam1"
            when
            then
                        update(projectother_re_projectdefault);//更新fact中变量值
                        update(projectother_re_projectrelationobj);//更新fact中变量值
                        update(projectother_re_projectrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[生成正向关联数据]
            rule "deaction1"
            ruleflow-group "projectother_re_projectdeaction1"
            when
            then
                        relationservice.create(projectother_re_projectrelationobj);
                        update(projectother_re_projectdefault);//更新fact中变量值
                        update(projectother_re_projectrelationobj);//更新fact中变量值
                        update(projectother_re_projectrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[抛出异常]
            rule "throwexception1"
            ruleflow-group "projectother_re_projectthrowexception1"
            when
            then
                        update(projectother_re_projectdefault);//更新fact中变量值
                        update(projectother_re_projectrelationobj);//更新fact中变量值
                        update(projectother_re_projectrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "projectother_re_projectend1"
            when
            then
                        update(projectother_re_projectdefault);//更新fact中变量值
                        update(projectother_re_projectrelationobj);//更新fact中变量值
                        update(projectother_re_projectrelationobj2);//更新fact中变量值
            end