package cn.ibizlab.plm.projmgmt.logic.projectlogic.project_move;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectproject_movedefault;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectproject_movefor_temp_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectproject_movesrfactionparam;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectproject_moveupdate_obj;
                    global cn.ibizlab.plm.core.projmgmt.service.IprojectService projectservice;
        global cn.ibizlab.plm.core.projmgmt.service.IprojectService iBzSysProjectDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectproject_movebegin"
            when
            then
            end

            //逻辑处理节点[绑定项目参数]
            rule "bindparam1"
            ruleflow-group "projectproject_movebindparam1"
            when
            then
                        update(projectproject_movedefault);//更新fact中变量值
                        update(projectproject_movefor_temp_obj);//更新fact中变量值
                        update(projectproject_movesrfactionparam);//更新fact中变量值
                        update(projectproject_moveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "projectproject_moveloopsubcall1"
            when
            then
                        update(projectproject_movedefault);//更新fact中变量值
                        update(projectproject_movefor_temp_obj);//更新fact中变量值
                        update(projectproject_movesrfactionparam);//更新fact中变量值
                        update(projectproject_moveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[准备更新项目参数]
            rule "prepareparam1"
            ruleflow-group "projectproject_moveprepareparam1"
            when
            then
                            projectproject_moveupdate_obj.set("scopeid",projectproject_movefor_temp_obj.get("scopeid"));
                            projectproject_moveupdate_obj.set("scopetype",projectproject_movefor_temp_obj.get("scopetype"));
                            projectproject_moveupdate_obj.set("visibility",projectproject_movefor_temp_obj.get("visibility"));
                            projectproject_moveupdate_obj.set("id",projectproject_movefor_temp_obj.get("id"));
                        update(projectproject_movedefault);//更新fact中变量值
                        update(projectproject_movefor_temp_obj);//更新fact中变量值
                        update(projectproject_movesrfactionparam);//更新fact中变量值
                        update(projectproject_moveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[更新项目信息]
            rule "deaction2"
            ruleflow-group "projectproject_movedeaction2"
            when
            then
                        projectservice.update(projectproject_moveupdate_obj);
                        update(projectproject_movedefault);//更新fact中变量值
                        update(projectproject_movefor_temp_obj);//更新fact中变量值
                        update(projectproject_movesrfactionparam);//更新fact中变量值
                        update(projectproject_moveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "projectproject_moveend2"
            when
            then
                        update(projectproject_movedefault);//更新fact中变量值
                        update(projectproject_movefor_temp_obj);//更新fact中变量值
                        update(projectproject_movesrfactionparam);//更新fact中变量值
                        update(projectproject_moveupdate_obj);//更新fact中变量值
            end