package cn.ibizlab.plm.projmgmt.logic.projectlogic.quick_create;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectquick_createdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectquick_createprojects;
                    global cn.ibizlab.plm.core.projmgmt.service.IprojectService projectservice;
        global cn.ibizlab.plm.core.projmgmt.service.IprojectService iBzSysProjectDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectquick_createbegin"
            when
            then
            end

            //逻辑处理节点[获取主表格查询数据集]
            rule "dedataset2"
            ruleflow-group "projectquick_creatededataset2"
            when
            then
                        update(projectquick_createdefault);//更新fact中变量值
                        update(projectquick_createprojects);//更新fact中变量值
            end

            //逻辑处理节点[获取用户快速新建数据集]
            rule "dedataset4"
            ruleflow-group "projectquick_creatededataset4"
            when
            then
                        update(projectquick_createdefault);//更新fact中变量值
                        update(projectquick_createprojects);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "projectquick_createend2"
            when
            then
                        update(projectquick_createdefault);//更新fact中变量值
                        update(projectquick_createprojects);//更新fact中变量值
            end

            //逻辑处理节点[判断系统管理员身份]
            rule "rawsfcode3"
            ruleflow-group "projectquick_createrawsfcode3"
            when
            then
                        update(projectquick_createdefault);//更新fact中变量值
                        update(projectquick_createprojects);//更新fact中变量值
            end