package cn.ibizlab.plm.projmgmt.logic.projectlogic.un_favorite;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectun_favoritedefault;
                global cn.ibizlab.plm.core.projmgmt.domain.project projectun_favoriteupdateobj;
        global cn.ibizlab.plm.core.projmgmt.service.IprojectService iBzSysProjectDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectun_favoritebegin"
            when
            then
            end

            //逻辑处理节点[删除收藏数据]
            rule "rawsqlcall1"
            ruleflow-group "projectun_favoriterawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",curuser.getSessionParams().get("srfpersonid"));
        param.put("param1",projectun_favoritedefault.get("owner_id"));
    String strSql="delete from `favorite` where create_man = #{et.param0} and owner_id = #{et.param1}";
                        iBzSysProjectDefaultService.execute(strSql,param);//SQL调用
                        update(projectun_favoritedefault);//更新fact中变量值
                        update(projectun_favoriteupdateobj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "projectun_favoriteend1"
            when
            then
                        update(projectun_favoritedefault);//更新fact中变量值
                        update(projectun_favoriteupdateobj);//更新fact中变量值
            end