package cn.ibizlab.plm.projmgmt.logic.work_item_typelogic.delete_custom_form;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item_type work_item_typedelete_custom_formdefault;
                global cn.ibizlab.plm.core.extension.domain.PSDEForm work_item_typedelete_custom_formmain_deform;
                global cn.ibizlab.plm.core.extension.domain.PSDEForm work_item_typedelete_custom_formnew_deform;
                    global cn.ibizlab.plm.core.extension.service.IPSDEFormService psdeformservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_item_typeService iBzSysWork_item_typeDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_item_typedelete_custom_formbegin"
            when
            then
            end

            //逻辑处理节点[拼接form标识]
            rule "rawsfcode_01"
            ruleflow-group "work_item_typedelete_custom_formrawsfcode_01"
            when
            then
                        update(work_item_typedelete_custom_formdefault);//更新fact中变量值
                        update(work_item_typedelete_custom_formmain_deform);//更新fact中变量值
                        update(work_item_typedelete_custom_formnew_deform);//更新fact中变量值
            end

            //逻辑处理节点[获取主视图表单]
            rule "deaction_03"
            ruleflow-group "work_item_typedelete_custom_formdeaction_03"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(psdeformservice.get(work_item_typedelete_custom_formmain_deform.getPsdeformid()),work_item_typedelete_custom_formmain_deform);
                        update(work_item_typedelete_custom_formdefault);//更新fact中变量值
                        update(work_item_typedelete_custom_formmain_deform);//更新fact中变量值
                        update(work_item_typedelete_custom_formnew_deform);//更新fact中变量值
            end

            //逻辑处理节点[获取新建表单]
            rule "deaction_01"
            ruleflow-group "work_item_typedelete_custom_formdeaction_01"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(psdeformservice.get(work_item_typedelete_custom_formnew_deform.getPsdeformid()),work_item_typedelete_custom_formnew_deform);
                        update(work_item_typedelete_custom_formdefault);//更新fact中变量值
                        update(work_item_typedelete_custom_formmain_deform);//更新fact中变量值
                        update(work_item_typedelete_custom_formnew_deform);//更新fact中变量值
            end

            //逻辑处理节点[删除新建表单]
            rule "deaction_02"
            ruleflow-group "work_item_typedelete_custom_formdeaction_02"
            when
            then
                        psdeformservice.remove(work_item_typedelete_custom_formnew_deform.getPsdeformid());
                        update(work_item_typedelete_custom_formdefault);//更新fact中变量值
                        update(work_item_typedelete_custom_formmain_deform);//更新fact中变量值
                        update(work_item_typedelete_custom_formnew_deform);//更新fact中变量值
            end

            //逻辑处理节点[删除主视图表单]
            rule "deaction_04"
            ruleflow-group "work_item_typedelete_custom_formdeaction_04"
            when
            then
                        psdeformservice.remove(work_item_typedelete_custom_formmain_deform.getPsdeformid());
                        update(work_item_typedelete_custom_formdefault);//更新fact中变量值
                        update(work_item_typedelete_custom_formmain_deform);//更新fact中变量值
                        update(work_item_typedelete_custom_formnew_deform);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "work_item_typedelete_custom_formend_01"
            when
            then
                        update(work_item_typedelete_custom_formdefault);//更新fact中变量值
                        update(work_item_typedelete_custom_formmain_deform);//更新fact中变量值
                        update(work_item_typedelete_custom_formnew_deform);//更新fact中变量值
            end