package cn.ibizlab.plm.projmgmt.logic.work_item_typelogic.delete_custom_model;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item_type work_item_typedelete_custom_modeldefault;
                global cn.ibizlab.plm.core.extension.domain.PSDEMSLogic work_item_typedelete_custom_modeldefault_ms_logic;
                global cn.ibizlab.plm.core.extension.domain.PSDEForm work_item_typedelete_custom_modelmain_deform;
                global cn.ibizlab.plm.core.extension.domain.PSDEForm work_item_typedelete_custom_modelnew_deform;
                    global cn.ibizlab.plm.core.extension.service.IPSDEMSLogicService psdemslogicservice;
                    global cn.ibizlab.plm.core.extension.service.IPSDEFormService psdeformservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_item_typeService iBzSysWork_item_typeDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_item_typedelete_custom_modelbegin"
            when
            then
            end

            //逻辑处理节点[拼接model标识]
            rule "rawsfcode_01"
            ruleflow-group "work_item_typedelete_custom_modelrawsfcode_01"
            when
            then
                        update(work_item_typedelete_custom_modeldefault);//更新fact中变量值
                        update(work_item_typedelete_custom_modeldefault_ms_logic);//更新fact中变量值
                        update(work_item_typedelete_custom_modelmain_deform);//更新fact中变量值
                        update(work_item_typedelete_custom_modelnew_deform);//更新fact中变量值
            end

            //逻辑处理节点[获取主状态信息]
            rule "deaction_05"
            ruleflow-group "work_item_typedelete_custom_modeldeaction_05"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(psdemslogicservice.get(work_item_typedelete_custom_modeldefault_ms_logic.getPsdelogicid()),work_item_typedelete_custom_modeldefault_ms_logic);
                        update(work_item_typedelete_custom_modeldefault);//更新fact中变量值
                        update(work_item_typedelete_custom_modeldefault_ms_logic);//更新fact中变量值
                        update(work_item_typedelete_custom_modelmain_deform);//更新fact中变量值
                        update(work_item_typedelete_custom_modelnew_deform);//更新fact中变量值
            end

            //逻辑处理节点[获取主视图form]
            rule "deaction_03"
            ruleflow-group "work_item_typedelete_custom_modeldeaction_03"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(psdeformservice.get(work_item_typedelete_custom_modelmain_deform.getPsdeformid()),work_item_typedelete_custom_modelmain_deform);
                        update(work_item_typedelete_custom_modeldefault);//更新fact中变量值
                        update(work_item_typedelete_custom_modeldefault_ms_logic);//更新fact中变量值
                        update(work_item_typedelete_custom_modelmain_deform);//更新fact中变量值
                        update(work_item_typedelete_custom_modelnew_deform);//更新fact中变量值
            end

            //逻辑处理节点[获取新建form]
            rule "deaction_01"
            ruleflow-group "work_item_typedelete_custom_modeldeaction_01"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(psdeformservice.get(work_item_typedelete_custom_modelnew_deform.getPsdeformid()),work_item_typedelete_custom_modelnew_deform);
                        update(work_item_typedelete_custom_modeldefault);//更新fact中变量值
                        update(work_item_typedelete_custom_modeldefault_ms_logic);//更新fact中变量值
                        update(work_item_typedelete_custom_modelmain_deform);//更新fact中变量值
                        update(work_item_typedelete_custom_modelnew_deform);//更新fact中变量值
            end

            //逻辑处理节点[删除]
            rule "deaction_06"
            ruleflow-group "work_item_typedelete_custom_modeldeaction_06"
            when
            then
                        psdemslogicservice.remove(work_item_typedelete_custom_modeldefault_ms_logic.getPsdelogicid());
                        update(work_item_typedelete_custom_modeldefault);//更新fact中变量值
                        update(work_item_typedelete_custom_modeldefault_ms_logic);//更新fact中变量值
                        update(work_item_typedelete_custom_modelmain_deform);//更新fact中变量值
                        update(work_item_typedelete_custom_modelnew_deform);//更新fact中变量值
            end

            //逻辑处理节点[删除]
            rule "deaction_02"
            ruleflow-group "work_item_typedelete_custom_modeldeaction_02"
            when
            then
                        psdeformservice.remove(work_item_typedelete_custom_modelnew_deform.getPsdeformid());
                        update(work_item_typedelete_custom_modeldefault);//更新fact中变量值
                        update(work_item_typedelete_custom_modeldefault_ms_logic);//更新fact中变量值
                        update(work_item_typedelete_custom_modelmain_deform);//更新fact中变量值
                        update(work_item_typedelete_custom_modelnew_deform);//更新fact中变量值
            end

            //逻辑处理节点[删除]
            rule "deaction_04"
            ruleflow-group "work_item_typedelete_custom_modeldeaction_04"
            when
            then
                        psdeformservice.remove(work_item_typedelete_custom_modelmain_deform.getPsdeformid());
                        update(work_item_typedelete_custom_modeldefault);//更新fact中变量值
                        update(work_item_typedelete_custom_modeldefault_ms_logic);//更新fact中变量值
                        update(work_item_typedelete_custom_modelmain_deform);//更新fact中变量值
                        update(work_item_typedelete_custom_modelnew_deform);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "work_item_typedelete_custom_modelend_01"
            when
            then
                        update(work_item_typedelete_custom_modeldefault);//更新fact中变量值
                        update(work_item_typedelete_custom_modeldefault_ms_logic);//更新fact中变量值
                        update(work_item_typedelete_custom_modelmain_deform);//更新fact中变量值
                        update(work_item_typedelete_custom_modelnew_deform);//更新fact中变量值
            end