package cn.ibizlab.plm.projmgmt.logic.work_item_typelogic.delete_custom_form;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item_type work_item_typedelete_custom_formdefault;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_item_typeService iBzSysWork_item_typeDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_item_typedelete_custom_formbegin"
            when
            then
            end