package cn.ibizlab.plm.projmgmt.logic.work_item_typelogic.prepare_default_model;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item_type work_item_typeprepare_default_modeldefault;
                global cn.ibizlab.plm.core.extension.domain.PSDEForm work_item_typeprepare_default_modeldefault_create_form;
                global cn.ibizlab.plm.core.extension.domain.PSDEForm work_item_typeprepare_default_modeldefault_main_form;
                global cn.ibizlab.plm.core.extension.domain.PSDEMSLogic work_item_typeprepare_default_modeldefault_ms_logic;
                    global cn.ibizlab.plm.core.extension.service.IPSDEFormService psdeformservice;
                    global cn.ibizlab.plm.core.extension.service.IPSDEMSLogicService psdemslogicservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_item_typeService iBzSysWork_item_typeDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_item_typeprepare_default_modelbegin"
            when
            then
            end

            //逻辑处理节点[构造默认主状态逻辑标识]
            rule "rawsfcode_04"
            ruleflow-group "work_item_typeprepare_default_modelrawsfcode_04"
            when
            then
                        update(work_item_typeprepare_default_modeldefault);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_create_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_main_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_ms_logic);//更新fact中变量值
            end

            //逻辑处理节点[构造默认表单id]
            rule "rawsfcode_01"
            ruleflow-group "work_item_typeprepare_default_modelrawsfcode_01"
            when
            then
                        update(work_item_typeprepare_default_modeldefault);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_create_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_main_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_ms_logic);//更新fact中变量值
            end

            //逻辑处理节点[获取默认任务主视图表单]
            rule "deaction_02"
            ruleflow-group "work_item_typeprepare_default_modeldeaction_02"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(psdeformservice.get(work_item_typeprepare_default_modeldefault_main_form.getPsdeformid()),work_item_typeprepare_default_modeldefault_main_form);
                        update(work_item_typeprepare_default_modeldefault);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_create_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_main_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_ms_logic);//更新fact中变量值
            end

            //逻辑处理节点[获取默认任务新建表单]
            rule "deaction_01"
            ruleflow-group "work_item_typeprepare_default_modeldeaction_01"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(psdeformservice.get(work_item_typeprepare_default_modeldefault_create_form.getPsdeformid()),work_item_typeprepare_default_modeldefault_create_form);
                        update(work_item_typeprepare_default_modeldefault);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_create_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_main_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_ms_logic);//更新fact中变量值
            end

            //逻辑处理节点[准备主视图表单参数]
            rule "rawsfcode_02"
            ruleflow-group "work_item_typeprepare_default_modelrawsfcode_02"
            when
            then
                        update(work_item_typeprepare_default_modeldefault);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_create_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_main_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_ms_logic);//更新fact中变量值
            end

            //逻辑处理节点[获取默认任务主状态逻辑]
            rule "deaction_07"
            ruleflow-group "work_item_typeprepare_default_modeldeaction_07"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(psdemslogicservice.get(work_item_typeprepare_default_modeldefault_ms_logic.getPsdelogicid()),work_item_typeprepare_default_modeldefault_ms_logic);
                        update(work_item_typeprepare_default_modeldefault);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_create_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_main_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_ms_logic);//更新fact中变量值
            end

            //逻辑处理节点[准备新建表单的参数]
            rule "rawsfcode_03"
            ruleflow-group "work_item_typeprepare_default_modelrawsfcode_03"
            when
            then
                        update(work_item_typeprepare_default_modeldefault);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_create_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_main_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_ms_logic);//更新fact中变量值
            end

            //逻辑处理节点[准备主状态逻辑参数]
            rule "rawsfcode_05"
            ruleflow-group "work_item_typeprepare_default_modelrawsfcode_05"
            when
            then
                        update(work_item_typeprepare_default_modeldefault);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_create_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_main_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_ms_logic);//更新fact中变量值
            end

            //逻辑处理节点[创建新建表单]
            rule "deaction_03"
            ruleflow-group "work_item_typeprepare_default_modeldeaction_03"
            when
            then
                        psdeformservice.create(work_item_typeprepare_default_modeldefault_create_form);
                        update(work_item_typeprepare_default_modeldefault);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_create_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_main_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_ms_logic);//更新fact中变量值
            end

            //逻辑处理节点[创建主视图表单]
            rule "deaction_05"
            ruleflow-group "work_item_typeprepare_default_modeldeaction_05"
            when
            then
                        psdeformservice.create(work_item_typeprepare_default_modeldefault_main_form);
                        update(work_item_typeprepare_default_modeldefault);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_create_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_main_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_ms_logic);//更新fact中变量值
            end

            //逻辑处理节点[创建主状态逻辑]
            rule "deaction_08"
            ruleflow-group "work_item_typeprepare_default_modeldeaction_08"
            when
            then
                        psdemslogicservice.create(work_item_typeprepare_default_modeldefault_ms_logic);
                        update(work_item_typeprepare_default_modeldefault);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_create_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_main_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_ms_logic);//更新fact中变量值
            end

            //逻辑处理节点[应用新建表单]
            rule "deaction_04"
            ruleflow-group "work_item_typeprepare_default_modeldeaction_04"
            when
            then
                        psdeformservice.apply(work_item_typeprepare_default_modeldefault_create_form);
                        update(work_item_typeprepare_default_modeldefault);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_create_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_main_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_ms_logic);//更新fact中变量值
            end

            //逻辑处理节点[应用主视图表单]
            rule "deaction_06"
            ruleflow-group "work_item_typeprepare_default_modeldeaction_06"
            when
            then
                        psdeformservice.apply(work_item_typeprepare_default_modeldefault_main_form);
                        update(work_item_typeprepare_default_modeldefault);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_create_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_main_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_ms_logic);//更新fact中变量值
            end

            //逻辑处理节点[应用主状态逻辑]
            rule "deaction_09"
            ruleflow-group "work_item_typeprepare_default_modeldeaction_09"
            when
            then
                        psdemslogicservice.apply(work_item_typeprepare_default_modeldefault_ms_logic);
                        update(work_item_typeprepare_default_modeldefault);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_create_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_main_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_ms_logic);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "work_item_typeprepare_default_modelend_01"
            when
            then
                        update(work_item_typeprepare_default_modeldefault);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_create_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_main_form);//更新fact中变量值
                        update(work_item_typeprepare_default_modeldefault_ms_logic);//更新fact中变量值
            end