package cn.ibizlab.plm.projmgmt.logic.work_item_typelogic.set_default_code;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item_type work_item_typeset_default_codedefault;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_item_typeService iBzSysWork_item_typeDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_item_typeset_default_codebegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "work_item_typeset_default_codeprepareparam_01"
            when
            then
                            work_item_typeset_default_codedefault.set("code",work_item_typeset_default_codedefault.get("id"));
                        update(work_item_typeset_default_codedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "work_item_typeset_default_codeend_01"
            when
            then
                        update(work_item_typeset_default_codedefault);//更新fact中变量值
            end