package cn.ibizlab.plm.projmgmt.logic.work_item_typelogic.sort;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item_type work_item_typesortdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item_type work_item_typesortfilter;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item_type work_item_typesortpage;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_item_typeService work_item_typeservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_item_typeService iBzSysWork_item_typeDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_item_typesortbegin"
            when
            then
            end

            //逻辑处理节点[填充默认编码值]
            rule "prepareparam_01"
            ruleflow-group "work_item_typesortprepareparam_01"
            when
            then
                            work_item_typesortdefault.set("code",work_item_typesortdefault.get("id"));
                        update(work_item_typesortdefault);//更新fact中变量值
                        update(work_item_typesortfilter);//更新fact中变量值
                        update(work_item_typesortpage);//更新fact中变量值
            end

            //逻辑处理节点[准备查询参数]
            rule "prepareparam1"
            ruleflow-group "work_item_typesortprepareparam1"
            when
            then
                            work_item_typesortfilter.set("sort","sequence,desc");
                        update(work_item_typesortdefault);//更新fact中变量值
                        update(work_item_typesortfilter);//更新fact中变量值
                        update(work_item_typesortpage);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "work_item_typesortdedataset1"
            when
            then
                        update(work_item_typesortdefault);//更新fact中变量值
                        update(work_item_typesortfilter);//更新fact中变量值
                        update(work_item_typesortpage);//更新fact中变量值
            end

            //逻辑处理节点[设置最大排序值]
            rule "rawsfcode1"
            ruleflow-group "work_item_typesortrawsfcode1"
            when
            then
                        update(work_item_typesortdefault);//更新fact中变量值
                        update(work_item_typesortfilter);//更新fact中变量值
                        update(work_item_typesortpage);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_item_typesortend1"
            when
            then
                        update(work_item_typesortdefault);//更新fact中变量值
                        update(work_item_typesortfilter);//更新fact中变量值
                        update(work_item_typesortpage);//更新fact中变量值
            end