package cn.ibizlab.plm.projmgmt.logic.boardlogic.check_board_is_deleted;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.board boardcheck_board_is_deleteddefault;
                global java.util.Map boardcheck_board_is_deletedcheckkey;
                    global cn.ibizlab.plm.core.projmgmt.service.IboardService boardservice;
        global cn.ibizlab.plm.core.projmgmt.service.IboardService iBzSysBoardDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "boardcheck_board_is_deletedbegin"
            when
            then
            end

            //逻辑处理节点[验证主键是否存在]
            rule "deaction1"
            ruleflow-group "boardcheck_board_is_deleteddeaction1"
            when
            then
                        boardservice.checkKey(boardcheck_board_is_deleteddefault);
                        update(boardcheck_board_is_deleteddefault);//更新fact中变量值
                        update(boardcheck_board_is_deletedcheckkey);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "boardcheck_board_is_deletedprepareparam1"
            when
            then
                            boardcheck_board_is_deleteddefault.set("checkkey",boardcheck_board_is_deletedcheckkey.get(""));
                        update(boardcheck_board_is_deleteddefault);//更新fact中变量值
                        update(boardcheck_board_is_deletedcheckkey);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "boardcheck_board_is_deletedend1"
            when
            then
                        update(boardcheck_board_is_deleteddefault);//更新fact中变量值
                        update(boardcheck_board_is_deletedcheckkey);//更新fact中变量值
            end