package cn.ibizlab.plm.projmgmt.logic.boardlogic.create_default_entry;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.board boardcreate_default_entrydefault;
                global cn.ibizlab.plm.core.projmgmt.domain.board boardcreate_default_entryboard;
                global cn.ibizlab.plm.core.projmgmt.domain.entry boardcreate_default_entrydesign_entry;
                global cn.ibizlab.plm.core.projmgmt.domain.entry boardcreate_default_entryidea_pool_entry;
                global cn.ibizlab.plm.core.projmgmt.domain.entry boardcreate_default_entryissue_entry;
                global cn.ibizlab.plm.core.projmgmt.domain.entry boardcreate_default_entryrd_entry;
                global cn.ibizlab.plm.core.projmgmt.domain.swimlane boardcreate_default_entryswimlane;
                global cn.ibizlab.plm.core.projmgmt.domain.entry boardcreate_default_entrytest_entry;
                    global cn.ibizlab.plm.core.projmgmt.service.IswimlaneService swimlaneservice;
                    global cn.ibizlab.plm.core.projmgmt.service.IentryService entryservice;
        global cn.ibizlab.plm.core.projmgmt.service.IboardService iBzSysBoardDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "boardcreate_default_entrybegin"
            when
            then
            end

            //逻辑处理节点[默认泳道名称]
            rule "prepareparam2"
            ruleflow-group "boardcreate_default_entryprepareparam2"
            when
            then
                            boardcreate_default_entryswimlane.set("name","默认泳道");
                            boardcreate_default_entryswimlane.set("id",boardcreate_default_entrydefault.get("id"));
                            boardcreate_default_entryswimlane.set("boardid",boardcreate_default_entrydefault.get("id"));
                        update(boardcreate_default_entrydefault);//更新fact中变量值
                        update(boardcreate_default_entryboard);//更新fact中变量值
                        update(boardcreate_default_entrydesign_entry);//更新fact中变量值
                        update(boardcreate_default_entryidea_pool_entry);//更新fact中变量值
                        update(boardcreate_default_entryissue_entry);//更新fact中变量值
                        update(boardcreate_default_entryrd_entry);//更新fact中变量值
                        update(boardcreate_default_entryswimlane);//更新fact中变量值
                        update(boardcreate_default_entrytest_entry);//更新fact中变量值
            end

            //逻辑处理节点[建立默认泳道]
            rule "deaction2"
            ruleflow-group "boardcreate_default_entrydeaction2"
            when
            then
                        swimlaneservice.create(boardcreate_default_entryswimlane);
                        update(boardcreate_default_entrydefault);//更新fact中变量值
                        update(boardcreate_default_entryboard);//更新fact中变量值
                        update(boardcreate_default_entrydesign_entry);//更新fact中变量值
                        update(boardcreate_default_entryidea_pool_entry);//更新fact中变量值
                        update(boardcreate_default_entryissue_entry);//更新fact中变量值
                        update(boardcreate_default_entryrd_entry);//更新fact中变量值
                        update(boardcreate_default_entryswimlane);//更新fact中变量值
                        update(boardcreate_default_entrytest_entry);//更新fact中变量值
            end

            //逻辑处理节点[默认看板栏名称]
            rule "prepareparam3"
            ruleflow-group "boardcreate_default_entryprepareparam3"
            when
            then
                            boardcreate_default_entryidea_pool_entry.set("issplit","0");
                            boardcreate_default_entryidea_pool_entry.set("showorder","1");
                            boardcreate_default_entrydesign_entry.set("showorder","2");
                            boardcreate_default_entryrd_entry.set("showorder","3");
                            boardcreate_default_entrytest_entry.set("showorder","4");
                            boardcreate_default_entryissue_entry.set("showorder","5");
                            boardcreate_default_entryidea_pool_entry.set("issystem","1");
                            boardcreate_default_entrydesign_entry.set("issplit","0");
                            boardcreate_default_entrydesign_entry.set("issystem","0");
                            boardcreate_default_entryrd_entry.set("issplit","1");
                            boardcreate_default_entryrd_entry.set("issystem","0");
                            boardcreate_default_entrytest_entry.set("issplit","0");
                            boardcreate_default_entrytest_entry.set("issplit","0");
                            boardcreate_default_entryissue_entry.set("issplit","0");
                            boardcreate_default_entryissue_entry.set("issystem","0");
                            boardcreate_default_entryidea_pool_entry.set("boardid",boardcreate_default_entrydefault.get("id"));
                            boardcreate_default_entrydesign_entry.set("boardid",boardcreate_default_entrydefault.get("id"));
                            boardcreate_default_entryrd_entry.set("boardid",boardcreate_default_entrydefault.get("id"));
                            boardcreate_default_entrytest_entry.set("boardid",boardcreate_default_entrydefault.get("id"));
                            boardcreate_default_entryissue_entry.set("boardid",boardcreate_default_entrydefault.get("id"));
                            boardcreate_default_entryidea_pool_entry.set("name","需求池");
                            boardcreate_default_entrydesign_entry.set("name","设计");
                            boardcreate_default_entryrd_entry.set("name","研发");
                            boardcreate_default_entrytest_entry.set("name","测试");
                            boardcreate_default_entryissue_entry.set("name","发布");
                        update(boardcreate_default_entrydefault);//更新fact中变量值
                        update(boardcreate_default_entryboard);//更新fact中变量值
                        update(boardcreate_default_entrydesign_entry);//更新fact中变量值
                        update(boardcreate_default_entryidea_pool_entry);//更新fact中变量值
                        update(boardcreate_default_entryissue_entry);//更新fact中变量值
                        update(boardcreate_default_entryrd_entry);//更新fact中变量值
                        update(boardcreate_default_entryswimlane);//更新fact中变量值
                        update(boardcreate_default_entrytest_entry);//更新fact中变量值
            end

            //逻辑处理节点[建立默认需求池看板栏]
            rule "deaction3"
            ruleflow-group "boardcreate_default_entrydeaction3"
            when
            then
                        entryservice.create(boardcreate_default_entryidea_pool_entry);
                        update(boardcreate_default_entrydefault);//更新fact中变量值
                        update(boardcreate_default_entryboard);//更新fact中变量值
                        update(boardcreate_default_entrydesign_entry);//更新fact中变量值
                        update(boardcreate_default_entryidea_pool_entry);//更新fact中变量值
                        update(boardcreate_default_entryissue_entry);//更新fact中变量值
                        update(boardcreate_default_entryrd_entry);//更新fact中变量值
                        update(boardcreate_default_entryswimlane);//更新fact中变量值
                        update(boardcreate_default_entrytest_entry);//更新fact中变量值
            end

            //逻辑处理节点[建立默认设计看板栏]
            rule "deaction4"
            ruleflow-group "boardcreate_default_entrydeaction4"
            when
            then
                        entryservice.create(boardcreate_default_entrydesign_entry);
                        update(boardcreate_default_entrydefault);//更新fact中变量值
                        update(boardcreate_default_entryboard);//更新fact中变量值
                        update(boardcreate_default_entrydesign_entry);//更新fact中变量值
                        update(boardcreate_default_entryidea_pool_entry);//更新fact中变量值
                        update(boardcreate_default_entryissue_entry);//更新fact中变量值
                        update(boardcreate_default_entryrd_entry);//更新fact中变量值
                        update(boardcreate_default_entryswimlane);//更新fact中变量值
                        update(boardcreate_default_entrytest_entry);//更新fact中变量值
            end

            //逻辑处理节点[建立默认研发看板栏]
            rule "deaction5"
            ruleflow-group "boardcreate_default_entrydeaction5"
            when
            then
                        entryservice.create(boardcreate_default_entryrd_entry);
                        update(boardcreate_default_entrydefault);//更新fact中变量值
                        update(boardcreate_default_entryboard);//更新fact中变量值
                        update(boardcreate_default_entrydesign_entry);//更新fact中变量值
                        update(boardcreate_default_entryidea_pool_entry);//更新fact中变量值
                        update(boardcreate_default_entryissue_entry);//更新fact中变量值
                        update(boardcreate_default_entryrd_entry);//更新fact中变量值
                        update(boardcreate_default_entryswimlane);//更新fact中变量值
                        update(boardcreate_default_entrytest_entry);//更新fact中变量值
            end

            //逻辑处理节点[建立默认测试看板栏]
            rule "deaction6"
            ruleflow-group "boardcreate_default_entrydeaction6"
            when
            then
                        entryservice.create(boardcreate_default_entrytest_entry);
                        update(boardcreate_default_entrydefault);//更新fact中变量值
                        update(boardcreate_default_entryboard);//更新fact中变量值
                        update(boardcreate_default_entrydesign_entry);//更新fact中变量值
                        update(boardcreate_default_entryidea_pool_entry);//更新fact中变量值
                        update(boardcreate_default_entryissue_entry);//更新fact中变量值
                        update(boardcreate_default_entryrd_entry);//更新fact中变量值
                        update(boardcreate_default_entryswimlane);//更新fact中变量值
                        update(boardcreate_default_entrytest_entry);//更新fact中变量值
            end

            //逻辑处理节点[建立默认发布看板栏]
            rule "deaction7"
            ruleflow-group "boardcreate_default_entrydeaction7"
            when
            then
                        entryservice.create(boardcreate_default_entryissue_entry);
                        update(boardcreate_default_entrydefault);//更新fact中变量值
                        update(boardcreate_default_entryboard);//更新fact中变量值
                        update(boardcreate_default_entrydesign_entry);//更新fact中变量值
                        update(boardcreate_default_entryidea_pool_entry);//更新fact中变量值
                        update(boardcreate_default_entryissue_entry);//更新fact中变量值
                        update(boardcreate_default_entryrd_entry);//更新fact中变量值
                        update(boardcreate_default_entryswimlane);//更新fact中变量值
                        update(boardcreate_default_entrytest_entry);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "boardcreate_default_entryend1"
            when
            then
                        update(boardcreate_default_entrydefault);//更新fact中变量值
                        update(boardcreate_default_entryboard);//更新fact中变量值
                        update(boardcreate_default_entrydesign_entry);//更新fact中变量值
                        update(boardcreate_default_entryidea_pool_entry);//更新fact中变量值
                        update(boardcreate_default_entryissue_entry);//更新fact中变量值
                        update(boardcreate_default_entryrd_entry);//更新fact中变量值
                        update(boardcreate_default_entryswimlane);//更新fact中变量值
                        update(boardcreate_default_entrytest_entry);//更新fact中变量值
            end