package cn.ibizlab.plm.insight.logic.insight_viewlogic.auto_create_members;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.insight.domain.insight_view insight_viewauto_create_membersdefault;
                global cn.ibizlab.plm.core.base.domain.member insight_viewauto_create_membersmember;
                global cn.ibizlab.plm.core.base.domain.member insight_viewauto_create_membersmember_obj;
                global cn.ibizlab.plm.core.base.domain.member insight_viewauto_create_membersmember_page;
                global cn.ibizlab.plm.core.insight.domain.insight_member insight_viewauto_create_membersview_member;
                    global cn.ibizlab.plm.core.base.service.ImemberService memberservice;
        global cn.ibizlab.plm.core.insight.service.Iinsight_viewService iBzSysInsight_viewDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "insight_viewauto_create_membersbegin"
            when
            then
            end

            //逻辑处理节点[准备用户数据]
            rule "prepareparam1"
            ruleflow-group "insight_viewauto_create_membersprepareparam1"
            when
            then
                            insight_viewauto_create_membersview_member.set("ownerid",insight_viewauto_create_membersdefault.get("id"));
                            insight_viewauto_create_membersview_member.set("ownertype","INSIGHT");
                            insight_viewauto_create_membersview_member.set("ownersubtype","INSIGHT");
                            insight_viewauto_create_membersview_member.set("roleid","admin");
                                insight_viewauto_create_membersview_member.set("userid",curuser.getSessionParams().get("srfpersonid"));
                                insight_viewauto_create_membersview_member.set("name",curuser.getSessionParams().get("srfpersonname"));
                        update(insight_viewauto_create_membersdefault);//更新fact中变量值
                        update(insight_viewauto_create_membersmember);//更新fact中变量值
                        update(insight_viewauto_create_membersmember_obj);//更新fact中变量值
                        update(insight_viewauto_create_membersmember_page);//更新fact中变量值
                        update(insight_viewauto_create_membersview_member);//更新fact中变量值
            end

            //逻辑处理节点[准备查询数据]
            rule "prepareparam2"
            ruleflow-group "insight_viewauto_create_membersprepareparam2"
            when
            then
                            insight_viewauto_create_membersmember.set("n_owner_id_eq",insight_viewauto_create_membersdefault.get("scopeid"));
                            insight_viewauto_create_membersmember.set("n_owner_type_eq","GROUP");
                        update(insight_viewauto_create_membersdefault);//更新fact中变量值
                        update(insight_viewauto_create_membersmember);//更新fact中变量值
                        update(insight_viewauto_create_membersmember_obj);//更新fact中变量值
                        update(insight_viewauto_create_membersmember_page);//更新fact中变量值
                        update(insight_viewauto_create_membersview_member);//更新fact中变量值
            end

            //逻辑处理节点[生成用户]
            rule "deaction1"
            ruleflow-group "insight_viewauto_create_membersdeaction1"
            when
            then
                        memberservice.create(insight_viewauto_create_membersview_member);
                        update(insight_viewauto_create_membersdefault);//更新fact中变量值
                        update(insight_viewauto_create_membersmember);//更新fact中变量值
                        update(insight_viewauto_create_membersmember_obj);//更新fact中变量值
                        update(insight_viewauto_create_membersmember_page);//更新fact中变量值
                        update(insight_viewauto_create_membersview_member);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "insight_viewauto_create_membersdedataset1"
            when
            then
                        update(insight_viewauto_create_membersdefault);//更新fact中变量值
                        update(insight_viewauto_create_membersmember);//更新fact中变量值
                        update(insight_viewauto_create_membersmember_obj);//更新fact中变量值
                        update(insight_viewauto_create_membersmember_page);//更新fact中变量值
                        update(insight_viewauto_create_membersview_member);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "insight_viewauto_create_membersloopsubcall1"
            when
            then
                        update(insight_viewauto_create_membersdefault);//更新fact中变量值
                        update(insight_viewauto_create_membersmember);//更新fact中变量值
                        update(insight_viewauto_create_membersmember_obj);//更新fact中变量值
                        update(insight_viewauto_create_membersmember_page);//更新fact中变量值
                        update(insight_viewauto_create_membersview_member);//更新fact中变量值
            end

            //逻辑处理节点[重置参数]
            rule "resetparam1"
            ruleflow-group "insight_viewauto_create_membersresetparam1"
            when
            then
                        update(insight_viewauto_create_membersdefault);//更新fact中变量值
                        update(insight_viewauto_create_membersmember);//更新fact中变量值
                        update(insight_viewauto_create_membersmember_obj);//更新fact中变量值
                        update(insight_viewauto_create_membersmember_page);//更新fact中变量值
                        update(insight_viewauto_create_membersview_member);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam3"
            ruleflow-group "insight_viewauto_create_membersprepareparam3"
            when
            then
                            insight_viewauto_create_membersview_member.set("ownerid",insight_viewauto_create_membersdefault.get("id"));
                            insight_viewauto_create_membersview_member.set("ownertype","INSIGHT");
                            insight_viewauto_create_membersview_member.set("ownersubtype","INSIGHT");
                            insight_viewauto_create_membersview_member.set("name",insight_viewauto_create_membersmember_obj.get("name"));
                            insight_viewauto_create_membersview_member.set("userid",insight_viewauto_create_membersmember_obj.get("userid"));
                            insight_viewauto_create_membersview_member.set("roleid",insight_viewauto_create_membersmember_obj.get("roleid"));
                        update(insight_viewauto_create_membersdefault);//更新fact中变量值
                        update(insight_viewauto_create_membersmember);//更新fact中变量值
                        update(insight_viewauto_create_membersmember_obj);//更新fact中变量值
                        update(insight_viewauto_create_membersmember_page);//更新fact中变量值
                        update(insight_viewauto_create_membersview_member);//更新fact中变量值
            end

            //逻辑处理节点[生成用户数据]
            rule "deaction2"
            ruleflow-group "insight_viewauto_create_membersdeaction2"
            when
            then
                        memberservice.create(insight_viewauto_create_membersview_member);
                        update(insight_viewauto_create_membersdefault);//更新fact中变量值
                        update(insight_viewauto_create_membersmember);//更新fact中变量值
                        update(insight_viewauto_create_membersmember_obj);//更新fact中变量值
                        update(insight_viewauto_create_membersmember_page);//更新fact中变量值
                        update(insight_viewauto_create_membersview_member);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "insight_viewauto_create_membersend1"
            when
            then
                        update(insight_viewauto_create_membersdefault);//更新fact中变量值
                        update(insight_viewauto_create_membersmember);//更新fact中变量值
                        update(insight_viewauto_create_membersmember_obj);//更新fact中变量值
                        update(insight_viewauto_create_membersmember_page);//更新fact中变量值
                        update(insight_viewauto_create_membersview_member);//更新fact中变量值
            end