package cn.ibizlab.plm.insight.logic.insight_viewlogic.change_admin_role;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.insight.domain.insight_view insight_viewchange_admin_roledefault;
                global cn.ibizlab.plm.core.base.domain.user insight_viewchange_admin_rolefor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.user insight_viewchange_admin_roleinsight_view_member;
                global cn.ibizlab.plm.core.insight.domain.insight_member insight_viewchange_admin_roleupdate_member_info;
                    global cn.ibizlab.plm.core.insight.service.Iinsight_memberService insight_memberservice;
        global cn.ibizlab.plm.core.insight.service.Iinsight_viewService iBzSysInsight_viewDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "insight_viewchange_admin_rolebegin"
            when
            then
            end

            //逻辑处理节点[成员信息]
            rule "debugparam1"
            ruleflow-group "insight_viewchange_admin_roledebugparam1"
            when
            then
                        update(insight_viewchange_admin_roledefault);//更新fact中变量值
                        update(insight_viewchange_admin_rolefor_temp_obj);//更新fact中变量值
                        update(insight_viewchange_admin_roleinsight_view_member);//更新fact中变量值
                        update(insight_viewchange_admin_roleupdate_member_info);//更新fact中变量值
            end

            //逻辑处理节点[绑定视图成员参数]
            rule "bindparam1"
            ruleflow-group "insight_viewchange_admin_rolebindparam1"
            when
            then
                        update(insight_viewchange_admin_roledefault);//更新fact中变量值
                        update(insight_viewchange_admin_rolefor_temp_obj);//更新fact中变量值
                        update(insight_viewchange_admin_roleinsight_view_member);//更新fact中变量值
                        update(insight_viewchange_admin_roleupdate_member_info);//更新fact中变量值
            end

            //逻辑处理节点[循环处理成员信息]
            rule "loopsubcall1"
            ruleflow-group "insight_viewchange_admin_roleloopsubcall1"
            when
            then
                        update(insight_viewchange_admin_roledefault);//更新fact中变量值
                        update(insight_viewchange_admin_rolefor_temp_obj);//更新fact中变量值
                        update(insight_viewchange_admin_roleinsight_view_member);//更新fact中变量值
                        update(insight_viewchange_admin_roleupdate_member_info);//更新fact中变量值
            end

            //逻辑处理节点[重新建立更新成员参数]
            rule "renewparam1"
            ruleflow-group "insight_viewchange_admin_rolerenewparam1"
            when
            then
                        update(insight_viewchange_admin_roledefault);//更新fact中变量值
                        update(insight_viewchange_admin_rolefor_temp_obj);//更新fact中变量值
                        update(insight_viewchange_admin_roleinsight_view_member);//更新fact中变量值
                        update(insight_viewchange_admin_roleupdate_member_info);//更新fact中变量值
            end

            //逻辑处理节点[准备更新管理员身份]
            rule "prepareparam1"
            ruleflow-group "insight_viewchange_admin_roleprepareparam1"
            when
            then
                            insight_viewchange_admin_roleupdate_member_info.set("userid",insight_viewchange_admin_rolefor_temp_obj.get("id"));
                            insight_viewchange_admin_roleupdate_member_info.set("roleid","admin");
                            insight_viewchange_admin_roleupdate_member_info.set("ownerid",insight_viewchange_admin_roledefault.get("id"));
                        update(insight_viewchange_admin_roledefault);//更新fact中变量值
                        update(insight_viewchange_admin_rolefor_temp_obj);//更新fact中变量值
                        update(insight_viewchange_admin_roleinsight_view_member);//更新fact中变量值
                        update(insight_viewchange_admin_roleupdate_member_info);//更新fact中变量值
            end

            //逻辑处理节点[更新管理员身份]
            rule "deaction1"
            ruleflow-group "insight_viewchange_admin_roledeaction1"
            when
            then
                        insight_memberservice.save(insight_viewchange_admin_roleupdate_member_info);
                        update(insight_viewchange_admin_roledefault);//更新fact中变量值
                        update(insight_viewchange_admin_rolefor_temp_obj);//更新fact中变量值
                        update(insight_viewchange_admin_roleinsight_view_member);//更新fact中变量值
                        update(insight_viewchange_admin_roleupdate_member_info);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "insight_viewchange_admin_roleend1"
            when
            then
                        update(insight_viewchange_admin_roledefault);//更新fact中变量值
                        update(insight_viewchange_admin_rolefor_temp_obj);//更新fact中变量值
                        update(insight_viewchange_admin_roleinsight_view_member);//更新fact中变量值
                        update(insight_viewchange_admin_roleupdate_member_info);//更新fact中变量值
            end