package cn.ibizlab.plm.insight.logic.insight_viewlogic.delete;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.insight.domain.insight_view insight_viewdeletedefault;
                global cn.ibizlab.plm.core.insight.domain.insight_view insight_viewdeleteupdate_obj;
                    global cn.ibizlab.plm.core.insight.service.Iinsight_viewService insight_viewservice;
        global cn.ibizlab.plm.core.insight.service.Iinsight_viewService iBzSysInsight_viewDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "insight_viewdeletebegin"
            when
            then
            end

            //逻辑处理节点[设置更新属性信息]
            rule "prepareparam1"
            ruleflow-group "insight_viewdeleteprepareparam1"
            when
            then
                            insight_viewdeleteupdate_obj.set("id",insight_viewdeletedefault.get("id"));
                            insight_viewdeleteupdate_obj.set("isdeleted","1");
                        update(insight_viewdeletedefault);//更新fact中变量值
                        update(insight_viewdeleteupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[更新视图信息]
            rule "deaction1"
            ruleflow-group "insight_viewdeletedeaction1"
            when
            then
                        insight_viewservice.update(insight_viewdeleteupdate_obj);
                        update(insight_viewdeletedefault);//更新fact中变量值
                        update(insight_viewdeleteupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "insight_viewdeleteend1"
            when
            then
                        update(insight_viewdeletedefault);//更新fact中变量值
                        update(insight_viewdeleteupdate_obj);//更新fact中变量值
            end