package cn.ibizlab.plm.insight.logic.insight_viewlogic.favorite;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.insight.domain.insight_view insight_viewfavoritedefault;
                global cn.ibizlab.plm.core.base.domain.favorite insight_viewfavoritefavorite;
                    global cn.ibizlab.plm.core.base.service.IfavoriteService favoriteservice;
        global cn.ibizlab.plm.core.insight.service.Iinsight_viewService iBzSysInsight_viewDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "insight_viewfavoritebegin"
            when
            then
            end

            //逻辑处理节点[填充用户标识和收藏业务对象标识]
            rule "prepareparam1"
            ruleflow-group "insight_viewfavoriteprepareparam1"
            when
            then
                                insight_viewfavoritefavorite.set("createman",curuser.getSessionParams().get("srfuserid"));
                            insight_viewfavoritefavorite.set("ownertype","insight_view");
                            insight_viewfavoritefavorite.set("ownerid",insight_viewfavoritedefault.get("owner_id"));
                        update(insight_viewfavoritedefault);//更新fact中变量值
                        update(insight_viewfavoritefavorite);//更新fact中变量值
            end

            //逻辑处理节点[生成收藏数据]
            rule "deaction1"
            ruleflow-group "insight_viewfavoritedeaction1"
            when
            then
                        favoriteservice.save(insight_viewfavoritefavorite);
                        update(insight_viewfavoritedefault);//更新fact中变量值
                        update(insight_viewfavoritefavorite);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "insight_viewfavoriteend1"
            when
            then
                        update(insight_viewfavoritedefault);//更新fact中变量值
                        update(insight_viewfavoritefavorite);//更新fact中变量值
            end