package cn.ibizlab.plm.insight.logic.insight_viewlogic.recover;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.insight.domain.insight_view insight_viewrecoverdefault;
                global cn.ibizlab.plm.core.insight.domain.insight_view insight_viewrecoverupdate_obj;
                    global cn.ibizlab.plm.core.insight.service.Iinsight_viewService insight_viewservice;
        global cn.ibizlab.plm.core.insight.service.Iinsight_viewService iBzSysInsight_viewDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "insight_viewrecoverbegin"
            when
            then
            end

            //逻辑处理节点[设置视图参数信息]
            rule "prepareparam1"
            ruleflow-group "insight_viewrecoverprepareparam1"
            when
            then
                            insight_viewrecoverupdate_obj.set("id",insight_viewrecoverdefault.get("id"));
                            insight_viewrecoverupdate_obj.set("isdeleted","0");
                        update(insight_viewrecoverdefault);//更新fact中变量值
                        update(insight_viewrecoverupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[更新视图参数]
            rule "deaction1"
            ruleflow-group "insight_viewrecoverdeaction1"
            when
            then
                        insight_viewservice.update(insight_viewrecoverupdate_obj);
                        update(insight_viewrecoverdefault);//更新fact中变量值
                        update(insight_viewrecoverupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "insight_viewrecoverend1"
            when
            then
                        update(insight_viewrecoverdefault);//更新fact中变量值
                        update(insight_viewrecoverupdate_obj);//更新fact中变量值
            end