package cn.ibizlab.plm.insight.logic.insight_viewlogic.recognize_choose_template;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.insight.domain.insight_view insight_viewrecognize_choose_templatedefault;
                global cn.ibizlab.plm.core.base.domain.dyna_dashboard insight_viewrecognize_choose_templateboard_page;
                global cn.ibizlab.plm.core.base.domain.dyna_dashboard insight_viewrecognize_choose_templatefilter;
                global cn.ibizlab.plm.core.base.domain.dyna_dashboard insight_viewrecognize_choose_templatefirst_board;
                    global cn.ibizlab.plm.core.base.service.Idyna_dashboardService dyna_dashboardservice;
        global cn.ibizlab.plm.core.insight.service.Iinsight_viewService iBzSysInsight_viewDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "insight_viewrecognize_choose_templatebegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "insight_viewrecognize_choose_templateend1"
            when
            then
                        update(insight_viewrecognize_choose_templatedefault);//更新fact中变量值
                        update(insight_viewrecognize_choose_templateboard_page);//更新fact中变量值
                        update(insight_viewrecognize_choose_templatefilter);//更新fact中变量值
                        update(insight_viewrecognize_choose_templatefirst_board);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "insight_viewrecognize_choose_templateprepareparam1"
            when
            then
                            insight_viewrecognize_choose_templatefilter.set("n_owner_id_eq",insight_viewrecognize_choose_templatedefault.get("id"));
                        update(insight_viewrecognize_choose_templatedefault);//更新fact中变量值
                        update(insight_viewrecognize_choose_templateboard_page);//更新fact中变量值
                        update(insight_viewrecognize_choose_templatefilter);//更新fact中变量值
                        update(insight_viewrecognize_choose_templatefirst_board);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "insight_viewrecognize_choose_templatededataset1"
            when
            then
                        update(insight_viewrecognize_choose_templatedefault);//更新fact中变量值
                        update(insight_viewrecognize_choose_templateboard_page);//更新fact中变量值
                        update(insight_viewrecognize_choose_templatefilter);//更新fact中变量值
                        update(insight_viewrecognize_choose_templatefirst_board);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "insight_viewrecognize_choose_templatedebugparam1"
            when
            then
                        update(insight_viewrecognize_choose_templatedefault);//更新fact中变量值
                        update(insight_viewrecognize_choose_templateboard_page);//更新fact中变量值
                        update(insight_viewrecognize_choose_templatefilter);//更新fact中变量值
                        update(insight_viewrecognize_choose_templatefirst_board);//更新fact中变量值
            end

            //逻辑处理节点[返回无仪表盘]
            rule "prepareparam2"
            ruleflow-group "insight_viewrecognize_choose_templateprepareparam2"
            when
            then
                            insight_viewrecognize_choose_templatedefault.set("no_board","true");
                        update(insight_viewrecognize_choose_templatedefault);//更新fact中变量值
                        update(insight_viewrecognize_choose_templateboard_page);//更新fact中变量值
                        update(insight_viewrecognize_choose_templatefilter);//更新fact中变量值
                        update(insight_viewrecognize_choose_templatefirst_board);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam3"
            ruleflow-group "insight_viewrecognize_choose_templateprepareparam3"
            when
            then
                            insight_viewrecognize_choose_templatefirst_board.set("",insight_viewrecognize_choose_templateboard_page.get("0"));
                        update(insight_viewrecognize_choose_templatedefault);//更新fact中变量值
                        update(insight_viewrecognize_choose_templateboard_page);//更新fact中变量值
                        update(insight_viewrecognize_choose_templatefilter);//更新fact中变量值
                        update(insight_viewrecognize_choose_templatefirst_board);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "insight_viewrecognize_choose_templateend2"
            when
            then
                        update(insight_viewrecognize_choose_templatedefault);//更新fact中变量值
                        update(insight_viewrecognize_choose_templateboard_page);//更新fact中变量值
                        update(insight_viewrecognize_choose_templatefilter);//更新fact中变量值
                        update(insight_viewrecognize_choose_templatefirst_board);//更新fact中变量值
            end