package cn.ibizlab.plm.insight.logic.insight_viewlogic.un_favorite;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.insight.domain.insight_view insight_viewun_favoritedefault;
                global cn.ibizlab.plm.core.insight.domain.insight_view insight_viewun_favoriteupdateobj;
        global cn.ibizlab.plm.core.insight.service.Iinsight_viewService iBzSysInsight_viewDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "insight_viewun_favoritebegin"
            when
            then
            end

            //逻辑处理节点[直接sql调用]
            rule "rawsqlcall1"
            ruleflow-group "insight_viewun_favoriterawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",curuser.getSessionParams().get("srfuserid"));
        param.put("param1",insight_viewun_favoritedefault.get("owner_id"));
    String strSql="delete from `favorite` where create_man = #{et.param0} and owner_id = #{et.param1}";
                        iBzSysInsight_viewDefaultService.execute(strSql,param);//SQL调用
                        update(insight_viewun_favoritedefault);//更新fact中变量值
                        update(insight_viewun_favoriteupdateobj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "insight_viewun_favoriteend1"
            when
            then
                        update(insight_viewun_favoritedefault);//更新fact中变量值
                        update(insight_viewun_favoriteupdateobj);//更新fact中变量值
            end