package cn.ibizlab.plm.insight.logic.insight_viewlogic.view_move;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.insight.domain.insight_view insight_viewview_movedefault;
                global cn.ibizlab.plm.core.insight.domain.insight_view insight_viewview_movefor_temp_obj;
                global cn.ibizlab.plm.core.insight.domain.insight_view insight_viewview_movesrfactionparam;
                global cn.ibizlab.plm.core.insight.domain.insight_view insight_viewview_moveupdate_obj;
                    global cn.ibizlab.plm.core.insight.service.Iinsight_viewService insight_viewservice;
        global cn.ibizlab.plm.core.insight.service.Iinsight_viewService iBzSysInsight_viewDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "insight_viewview_movebegin"
            when
            then
            end

            //逻辑处理节点[绑定视图参数]
            rule "bindparam1"
            ruleflow-group "insight_viewview_movebindparam1"
            when
            then
                        update(insight_viewview_movedefault);//更新fact中变量值
                        update(insight_viewview_movefor_temp_obj);//更新fact中变量值
                        update(insight_viewview_movesrfactionparam);//更新fact中变量值
                        update(insight_viewview_moveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "insight_viewview_moveloopsubcall1"
            when
            then
                        update(insight_viewview_movedefault);//更新fact中变量值
                        update(insight_viewview_movefor_temp_obj);//更新fact中变量值
                        update(insight_viewview_movesrfactionparam);//更新fact中变量值
                        update(insight_viewview_moveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[准备更新视图参数]
            rule "prepareparam1"
            ruleflow-group "insight_viewview_moveprepareparam1"
            when
            then
                            insight_viewview_moveupdate_obj.set("scopeid",insight_viewview_movefor_temp_obj.get("scopeid"));
                            insight_viewview_moveupdate_obj.set("scopetype",insight_viewview_movefor_temp_obj.get("scopetype"));
                            insight_viewview_moveupdate_obj.set("visibility",insight_viewview_movefor_temp_obj.get("visibility"));
                            insight_viewview_moveupdate_obj.set("id",insight_viewview_movefor_temp_obj.get("id"));
                        update(insight_viewview_movedefault);//更新fact中变量值
                        update(insight_viewview_movefor_temp_obj);//更新fact中变量值
                        update(insight_viewview_movesrfactionparam);//更新fact中变量值
                        update(insight_viewview_moveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[更新视图信息]
            rule "deaction2"
            ruleflow-group "insight_viewview_movedeaction2"
            when
            then
                        insight_viewservice.update(insight_viewview_moveupdate_obj);
                        update(insight_viewview_movedefault);//更新fact中变量值
                        update(insight_viewview_movefor_temp_obj);//更新fact中变量值
                        update(insight_viewview_movesrfactionparam);//更新fact中变量值
                        update(insight_viewview_moveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "insight_viewview_moveend2"
            when
            then
                        update(insight_viewview_movedefault);//更新fact中变量值
                        update(insight_viewview_movefor_temp_obj);//更新fact中变量值
                        update(insight_viewview_movesrfactionparam);//更新fact中变量值
                        update(insight_viewview_moveupdate_obj);//更新fact中变量值
            end