package cn.ibizlab.plm.wiki.logic.shared_spacelogic.access_password;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.shared_space shared_spaceaccess_passworddefault;
                global cn.ibizlab.plm.core.wiki.domain.shared_space shared_spaceaccess_passwordcheck_space;
                    global cn.ibizlab.plm.core.wiki.service.Ishared_spaceService shared_spaceservice;
        global cn.ibizlab.plm.core.wiki.service.Ishared_spaceService iBzSysShared_spaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "shared_spaceaccess_passwordbegin"
            when
            then
            end

            //逻辑处理节点[获取共享空间]
            rule "deaction1"
            ruleflow-group "shared_spaceaccess_passworddeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(shared_spaceservice.get(shared_spaceaccess_passwordcheck_space.getId()),shared_spaceaccess_passwordcheck_space);
                        update(shared_spaceaccess_passworddefault);//更新fact中变量值
                        update(shared_spaceaccess_passwordcheck_space);//更新fact中变量值
            end

            //逻辑处理节点[查询共享空间密码信息]
            rule "rawsqlcall1"
            ruleflow-group "shared_spaceaccess_passwordrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",shared_spaceaccess_passworddefault.get("id"));
    String strSql="select `ACCESS_PASSWORD` from `space` where id = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysShared_spaceDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    shared_spaceaccess_passwordcheck_space.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(shared_spaceaccess_passworddefault);//更新fact中变量值
                        update(shared_spaceaccess_passwordcheck_space);//更新fact中变量值
            end

            //逻辑处理节点[解密密码信息]
            rule "delogic1"
            ruleflow-group "shared_spaceaccess_passworddelogic1"
            when
            then
                        update(shared_spaceaccess_passworddefault);//更新fact中变量值
                        update(shared_spaceaccess_passwordcheck_space);//更新fact中变量值
            end

            //逻辑处理节点[填充校验标识]
            rule "prepareparam3"
            ruleflow-group "shared_spaceaccess_passwordprepareparam3"
            when
            then
                            shared_spaceaccess_passwordcheck_space.set("id",shared_spaceaccess_passworddefault.get("id"));
                        update(shared_spaceaccess_passworddefault);//更新fact中变量值
                        update(shared_spaceaccess_passwordcheck_space);//更新fact中变量值
            end

            //逻辑处理节点[校验链接是否有效]
            rule "rawsfcode1"
            ruleflow-group "shared_spaceaccess_passwordrawsfcode1"
            when
            then
                        update(shared_spaceaccess_passworddefault);//更新fact中变量值
                        update(shared_spaceaccess_passwordcheck_space);//更新fact中变量值
            end

            //逻辑处理节点[密码正确]
            rule "prepareparam1"
            ruleflow-group "shared_spaceaccess_passwordprepareparam1"
            when
            then
                            shared_spaceaccess_passworddefault.set("check_access_password","1");
                        update(shared_spaceaccess_passworddefault);//更新fact中变量值
                        update(shared_spaceaccess_passwordcheck_space);//更新fact中变量值
            end

            //逻辑处理节点[密码错误]
            rule "prepareparam2"
            ruleflow-group "shared_spaceaccess_passwordprepareparam2"
            when
            then
                            shared_spaceaccess_passworddefault.set("check_access_password","0");
                        update(shared_spaceaccess_passworddefault);//更新fact中变量值
                        update(shared_spaceaccess_passwordcheck_space);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "shared_spaceaccess_passwordend1"
            when
            then
                        update(shared_spaceaccess_passworddefault);//更新fact中变量值
                        update(shared_spaceaccess_passwordcheck_space);//更新fact中变量值
            end