package cn.ibizlab.plm.wiki.logic.shared_spacelogic.check_shared;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.shared_space shared_spacecheck_shareddefault;
                global cn.ibizlab.plm.core.wiki.domain.shared_space shared_spacecheck_sharedresult;
                    global cn.ibizlab.plm.core.wiki.service.Ishared_spaceService shared_spaceservice;
        global cn.ibizlab.plm.core.wiki.service.Ishared_spaceService iBzSysShared_spaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "shared_spacecheck_sharedbegin"
            when
            then
            end

            //逻辑处理节点[获取共享空间]
            rule "deaction1"
            ruleflow-group "shared_spacecheck_shareddeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(shared_spaceservice.get(shared_spacecheck_shareddefault.getId()),shared_spacecheck_shareddefault);
                        update(shared_spacecheck_shareddefault);//更新fact中变量值
                        update(shared_spacecheck_sharedresult);//更新fact中变量值
            end

            //逻辑处理节点[查询共享空间密码信息]
            rule "rawsqlcall1"
            ruleflow-group "shared_spacecheck_sharedrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",shared_spacecheck_shareddefault.get("id"));
    String strSql="select `ACCESS_PASSWORD` from `space` where id = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysShared_spaceDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    shared_spacecheck_shareddefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(shared_spacecheck_shareddefault);//更新fact中变量值
                        update(shared_spacecheck_sharedresult);//更新fact中变量值
            end

            //逻辑处理节点[检验是否有效]
            rule "rawsfcode1"
            ruleflow-group "shared_spacecheck_sharedrawsfcode1"
            when
            then
                        update(shared_spacecheck_shareddefault);//更新fact中变量值
                        update(shared_spacecheck_sharedresult);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "shared_spacecheck_sharedend1"
            when
            then
                        update(shared_spacecheck_shareddefault);//更新fact中变量值
                        update(shared_spacecheck_sharedresult);//更新fact中变量值
            end