package cn.ibizlab.plm.wiki.logic.shared_spacelogic.closed_shared;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.shared_space shared_spaceclosed_shareddefault;
                    global cn.ibizlab.plm.core.wiki.service.Ishared_spaceService shared_spaceservice;
        global cn.ibizlab.plm.core.wiki.service.Ishared_spaceService iBzSysShared_spaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "shared_spaceclosed_sharedbegin"
            when
            then
            end

            //逻辑处理节点[设置页面关闭参数]
            rule "prepareparam1"
            ruleflow-group "shared_spaceclosed_sharedprepareparam1"
            when
            then
                                shared_spaceclosed_shareddefault.set("sharedpages",null);
                                shared_spaceclosed_shareddefault.set("sharedby",null);
                                shared_spaceclosed_shareddefault.set("sharedtime",null);
                                shared_spaceclosed_shareddefault.set("showlogo",null);
                                shared_spaceclosed_shareddefault.set("showtitle",null);
                                shared_spaceclosed_shareddefault.set("accesspassword",null);
                            shared_spaceclosed_shareddefault.set("isshared","0");
                                shared_spaceclosed_shareddefault.set("expirationdate",null);
                        update(shared_spaceclosed_shareddefault);//更新fact中变量值
            end

            //逻辑处理节点[更新页面信息]
            rule "deaction1"
            ruleflow-group "shared_spaceclosed_shareddeaction1"
            when
            then
                        shared_spaceservice.update(shared_spaceclosed_shareddefault);
                        update(shared_spaceclosed_shareddefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "shared_spaceclosed_sharedend1"
            when
            then
                        update(shared_spaceclosed_shareddefault);//更新fact中变量值
            end