package cn.ibizlab.plm.wiki.logic.shared_spacelogic.shared_url;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.shared_space shared_spaceshared_urldefault;
        global cn.ibizlab.plm.core.wiki.service.Ishared_spaceService iBzSysShared_spaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "shared_spaceshared_urlbegin"
            when
            then
            end

            //逻辑处理节点[拼接共享链接]
            rule "rawsfcode1"
            ruleflow-group "shared_spaceshared_urlrawsfcode1"
            when
            then
                        update(shared_spaceshared_urldefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "shared_spaceshared_urlend1"
            when
            then
                        update(shared_spaceshared_urldefault);//更新fact中变量值
            end