package cn.ibizlab.plm.wiki.logic.shared_spacelogic.shared_setting;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.shared_space shared_spaceshared_settingdefault;
                    global cn.ibizlab.plm.core.wiki.service.Ishared_spaceService shared_spaceservice;
        global cn.ibizlab.plm.core.wiki.service.Ishared_spaceService iBzSysShared_spaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "shared_spaceshared_settingbegin"
            when
            then
            end

            //逻辑处理节点[置空有效期]
            rule "prepareparam1"
            ruleflow-group "shared_spaceshared_settingprepareparam1"
            when
            then
                                shared_spaceshared_settingdefault.set("expirationdate",null);
                        update(shared_spaceshared_settingdefault);//更新fact中变量值
            end

            //逻辑处理节点[抛出异常]
            rule "throwexception1"
            ruleflow-group "shared_spaceshared_settingthrowexception1"
            when
            then
                        update(shared_spaceshared_settingdefault);//更新fact中变量值
            end

            //逻辑处理节点[共享范围]
            rule "prepareparam2"
            ruleflow-group "shared_spaceshared_settingprepareparam2"
            when
            then
                            shared_spaceshared_settingdefault.set("isshared",shared_spaceshared_settingdefault.get("shared_scope"));
                        update(shared_spaceshared_settingdefault);//更新fact中变量值
            end

            //逻辑处理节点[抛出异常]
            rule "throwexception2"
            ruleflow-group "shared_spaceshared_settingthrowexception2"
            when
            then
                        update(shared_spaceshared_settingdefault);//更新fact中变量值
            end

            //逻辑处理节点[置空密码]
            rule "prepareparam3"
            ruleflow-group "shared_spaceshared_settingprepareparam3"
            when
            then
                                shared_spaceshared_settingdefault.set("accesspassword",null);
                        update(shared_spaceshared_settingdefault);//更新fact中变量值
            end

            //逻辑处理节点[更新页面共享设置]
            rule "deaction1"
            ruleflow-group "shared_spaceshared_settingdeaction1"
            when
            then
                        shared_spaceservice.update(shared_spaceshared_settingdefault);
                        update(shared_spaceshared_settingdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "shared_spaceshared_settingend1"
            when
            then
                        update(shared_spaceshared_settingdefault);//更新fact中变量值
            end