package cn.ibizlab.plm.ai.logic.ai_credentiallogic.get_cloud_config;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_credential ai_credentialget_cloud_configdefault;
                global java.util.Map ai_credentialget_cloud_configmap;
        global cn.ibizlab.plm.core.ai.service.Iai_credentialService iBzSysAi_credentialDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_credentialget_cloud_configbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_credentialget_cloud_configend_01"
            when
            then
                        update(ai_credentialget_cloud_configdefault);//更新fact中变量值
                        update(ai_credentialget_cloud_configmap);//更新fact中变量值
            end

            //逻辑处理节点[设置禁用]
            rule "prepareparam_01"
            ruleflow-group "ai_credentialget_cloud_configprepareparam_01"
            when
            then
                            ai_credentialget_cloud_configmap.set("disabled","1");
                        update(ai_credentialget_cloud_configdefault);//更新fact中变量值
                        update(ai_credentialget_cloud_configmap);//更新fact中变量值
            end