package cn.ibizlab.plm.base.logic.baselinelogic.before_remove;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.baseline baselinebefore_removedefault;
        global cn.ibizlab.plm.core.base.service.IbaselineService iBzSysBaselineDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "baselinebefore_removebegin"
            when
            then
            end

            //逻辑处理节点[删除基线关联数据]
            rule "rawsqlcall1"
            ruleflow-group "baselinebefore_removerawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",baselinebefore_removedefault.get("id"));
    String strSql="delete from `relation` where principal_id = #{et.param0} and principal_type = 'baseline'";
                        iBzSysBaselineDefaultService.execute(strSql,param);//SQL调用
                        update(baselinebefore_removedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "baselinebefore_removeend1"
            when
            then
                        update(baselinebefore_removedefault);//更新fact中变量值
            end