package cn.ibizlab.plm.base.logic.baselinelogic.set_complete_project;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.baseline baselineset_complete_projectdefault;
                global cn.ibizlab.plm.core.base.domain.relation baselineset_complete_projectfor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.relation baselineset_complete_projectrelation_filter;
                global cn.ibizlab.plm.core.base.domain.relation baselineset_complete_projectrelation_page;
                global cn.ibizlab.plm.core.base.domain.version baselineset_complete_projectversion;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item baselineset_complete_projectwork_item;
                    global cn.ibizlab.plm.core.base.service.IbaselineService baselineservice;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
                    global cn.ibizlab.plm.core.base.service.IversionService versionservice;
        global cn.ibizlab.plm.core.base.service.IbaselineService iBzSysBaselineDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "baselineset_complete_projectbegin"
            when
            then
            end

            //逻辑处理节点[设置基线状态为完成状态]
            rule "prepareparam1"
            ruleflow-group "baselineset_complete_projectprepareparam1"
            when
            then
                            baselineset_complete_projectdefault.set("status","2");
                        update(baselineset_complete_projectdefault);//更新fact中变量值
                        update(baselineset_complete_projectfor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_projectrelation_filter);//更新fact中变量值
                        update(baselineset_complete_projectrelation_page);//更新fact中变量值
                        update(baselineset_complete_projectversion);//更新fact中变量值
                        update(baselineset_complete_projectwork_item);//更新fact中变量值
            end

            //逻辑处理节点[更新基线状态]
            rule "deaction1"
            ruleflow-group "baselineset_complete_projectdeaction1"
            when
            then
                        baselineservice.update(baselineset_complete_projectdefault);
                        update(baselineset_complete_projectdefault);//更新fact中变量值
                        update(baselineset_complete_projectfor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_projectrelation_filter);//更新fact中变量值
                        update(baselineset_complete_projectrelation_page);//更新fact中变量值
                        update(baselineset_complete_projectversion);//更新fact中变量值
                        update(baselineset_complete_projectwork_item);//更新fact中变量值
            end

            //逻辑处理节点[准备关联查询过滤器参数]
            rule "prepareparam2"
            ruleflow-group "baselineset_complete_projectprepareparam2"
            when
            then
                            baselineset_complete_projectrelation_filter.set("n_principal_id_eq",baselineset_complete_projectdefault.get("id"));
                            baselineset_complete_projectrelation_filter.set("size","10000");
                            baselineset_complete_projectrelation_filter.set("n_principal_type_eq","baseline");
                            baselineset_complete_projectrelation_filter.set("n_target_type_eq","work_item");
                        update(baselineset_complete_projectdefault);//更新fact中变量值
                        update(baselineset_complete_projectfor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_projectrelation_filter);//更新fact中变量值
                        update(baselineset_complete_projectrelation_page);//更新fact中变量值
                        update(baselineset_complete_projectversion);//更新fact中变量值
                        update(baselineset_complete_projectwork_item);//更新fact中变量值
            end

            //逻辑处理节点[获取基线下关联的工作项]
            rule "dedataset1"
            ruleflow-group "baselineset_complete_projectdedataset1"
            when
            then
                        update(baselineset_complete_projectdefault);//更新fact中变量值
                        update(baselineset_complete_projectfor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_projectrelation_filter);//更新fact中变量值
                        update(baselineset_complete_projectrelation_page);//更新fact中变量值
                        update(baselineset_complete_projectversion);//更新fact中变量值
                        update(baselineset_complete_projectwork_item);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "baselineset_complete_projectloopsubcall1"
            when
            then
                        update(baselineset_complete_projectdefault);//更新fact中变量值
                        update(baselineset_complete_projectfor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_projectrelation_filter);//更新fact中变量值
                        update(baselineset_complete_projectrelation_page);//更新fact中变量值
                        update(baselineset_complete_projectversion);//更新fact中变量值
                        update(baselineset_complete_projectwork_item);//更新fact中变量值
            end

            //逻辑处理节点[重置工作项参数]
            rule "resetparam1"
            ruleflow-group "baselineset_complete_projectresetparam1"
            when
            then
                        update(baselineset_complete_projectdefault);//更新fact中变量值
                        update(baselineset_complete_projectfor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_projectrelation_filter);//更新fact中变量值
                        update(baselineset_complete_projectrelation_page);//更新fact中变量值
                        update(baselineset_complete_projectversion);//更新fact中变量值
                        update(baselineset_complete_projectwork_item);//更新fact中变量值
            end

            //逻辑处理节点[重置版本参数]
            rule "resetparam2"
            ruleflow-group "baselineset_complete_projectresetparam2"
            when
            then
                        update(baselineset_complete_projectdefault);//更新fact中变量值
                        update(baselineset_complete_projectfor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_projectrelation_filter);//更新fact中变量值
                        update(baselineset_complete_projectrelation_page);//更新fact中变量值
                        update(baselineset_complete_projectversion);//更新fact中变量值
                        update(baselineset_complete_projectwork_item);//更新fact中变量值
            end

            //逻辑处理节点[填充工作项对象主键标识]
            rule "prepareparam3"
            ruleflow-group "baselineset_complete_projectprepareparam3"
            when
            then
                            baselineset_complete_projectwork_item.set("id",baselineset_complete_projectfor_temp_obj.get("targetid"));
                        update(baselineset_complete_projectdefault);//更新fact中变量值
                        update(baselineset_complete_projectfor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_projectrelation_filter);//更新fact中变量值
                        update(baselineset_complete_projectrelation_page);//更新fact中变量值
                        update(baselineset_complete_projectversion);//更新fact中变量值
                        update(baselineset_complete_projectwork_item);//更新fact中变量值
            end

            //逻辑处理节点[获取工作项]
            rule "deaction2"
            ruleflow-group "baselineset_complete_projectdeaction2"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(work_itemservice.get(baselineset_complete_projectwork_item.getId()),baselineset_complete_projectwork_item);
                        update(baselineset_complete_projectdefault);//更新fact中变量值
                        update(baselineset_complete_projectfor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_projectrelation_filter);//更新fact中变量值
                        update(baselineset_complete_projectrelation_page);//更新fact中变量值
                        update(baselineset_complete_projectversion);//更新fact中变量值
                        update(baselineset_complete_projectwork_item);//更新fact中变量值
            end

            //逻辑处理节点[填充版本属性]
            rule "prepareparam4"
            ruleflow-group "baselineset_complete_projectprepareparam4"
            when
            then
                            baselineset_complete_projectversion.set("ownerid",baselineset_complete_projectfor_temp_obj.get("targetid"));
                            baselineset_complete_projectversion.set("ownertype","WORK_ITEM");
                            baselineset_complete_projectversion.set("name","设立基线创建版本");
                        update(baselineset_complete_projectdefault);//更新fact中变量值
                        update(baselineset_complete_projectfor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_projectrelation_filter);//更新fact中变量值
                        update(baselineset_complete_projectrelation_page);//更新fact中变量值
                        update(baselineset_complete_projectversion);//更新fact中变量值
                        update(baselineset_complete_projectwork_item);//更新fact中变量值
            end

            //逻辑处理节点[创建新版本]
            rule "deaction3"
            ruleflow-group "baselineset_complete_projectdeaction3"
            when
            then
                        versionservice.commit(baselineset_complete_projectversion);
                        update(baselineset_complete_projectdefault);//更新fact中变量值
                        update(baselineset_complete_projectfor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_projectrelation_filter);//更新fact中变量值
                        update(baselineset_complete_projectrelation_page);//更新fact中变量值
                        update(baselineset_complete_projectversion);//更新fact中变量值
                        update(baselineset_complete_projectwork_item);//更新fact中变量值
            end