package cn.ibizlab.plm.base.logic.baselinelogic.set_complete_space;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.baseline baselineset_complete_spacedefault;
                global cn.ibizlab.plm.core.base.domain.relation baselineset_complete_spacefor_temp_obj;
                global cn.ibizlab.plm.core.wiki.domain.article_page baselineset_complete_spacepage;
                global cn.ibizlab.plm.core.base.domain.relation baselineset_complete_spacerelation_filter;
                global cn.ibizlab.plm.core.base.domain.relation baselineset_complete_spacerelation_page;
                global cn.ibizlab.plm.core.base.domain.version baselineset_complete_spaceversion;
                    global cn.ibizlab.plm.core.base.service.IbaselineService baselineservice;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
                    global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService article_pageservice;
                    global cn.ibizlab.plm.core.base.service.IversionService versionservice;
        global cn.ibizlab.plm.core.base.service.IbaselineService iBzSysBaselineDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "baselineset_complete_spacebegin"
            when
            then
            end

            //逻辑处理节点[设立完成状态]
            rule "prepareparam1"
            ruleflow-group "baselineset_complete_spaceprepareparam1"
            when
            then
                            baselineset_complete_spacedefault.set("status","2");
                        update(baselineset_complete_spacedefault);//更新fact中变量值
                        update(baselineset_complete_spacefor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_spacepage);//更新fact中变量值
                        update(baselineset_complete_spacerelation_filter);//更新fact中变量值
                        update(baselineset_complete_spacerelation_page);//更新fact中变量值
                        update(baselineset_complete_spaceversion);//更新fact中变量值
            end

            //逻辑处理节点[设立完成]
            rule "deaction1"
            ruleflow-group "baselineset_complete_spacedeaction1"
            when
            then
                        baselineservice.update(baselineset_complete_spacedefault);
                        update(baselineset_complete_spacedefault);//更新fact中变量值
                        update(baselineset_complete_spacefor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_spacepage);//更新fact中变量值
                        update(baselineset_complete_spacerelation_filter);//更新fact中变量值
                        update(baselineset_complete_spacerelation_page);//更新fact中变量值
                        update(baselineset_complete_spaceversion);//更新fact中变量值
            end

            //逻辑处理节点[准备关联查询过滤器参数]
            rule "prepareparam2"
            ruleflow-group "baselineset_complete_spaceprepareparam2"
            when
            then
                            baselineset_complete_spacerelation_filter.set("n_principal_id_eq",baselineset_complete_spacedefault.get("id"));
                            baselineset_complete_spacerelation_filter.set("size","10000");
                            baselineset_complete_spacerelation_filter.set("n_principal_type_eq","baseline");
                            baselineset_complete_spacerelation_filter.set("n_target_type_eq","page");
                        update(baselineset_complete_spacedefault);//更新fact中变量值
                        update(baselineset_complete_spacefor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_spacepage);//更新fact中变量值
                        update(baselineset_complete_spacerelation_filter);//更新fact中变量值
                        update(baselineset_complete_spacerelation_page);//更新fact中变量值
                        update(baselineset_complete_spaceversion);//更新fact中变量值
            end

            //逻辑处理节点[获取基线下关联的页面]
            rule "dedataset1"
            ruleflow-group "baselineset_complete_spacededataset1"
            when
            then
                        update(baselineset_complete_spacedefault);//更新fact中变量值
                        update(baselineset_complete_spacefor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_spacepage);//更新fact中变量值
                        update(baselineset_complete_spacerelation_filter);//更新fact中变量值
                        update(baselineset_complete_spacerelation_page);//更新fact中变量值
                        update(baselineset_complete_spaceversion);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "baselineset_complete_spaceloopsubcall1"
            when
            then
                        update(baselineset_complete_spacedefault);//更新fact中变量值
                        update(baselineset_complete_spacefor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_spacepage);//更新fact中变量值
                        update(baselineset_complete_spacerelation_filter);//更新fact中变量值
                        update(baselineset_complete_spacerelation_page);//更新fact中变量值
                        update(baselineset_complete_spaceversion);//更新fact中变量值
            end

            //逻辑处理节点[重置产品需求参数]
            rule "resetparam1"
            ruleflow-group "baselineset_complete_spaceresetparam1"
            when
            then
                        update(baselineset_complete_spacedefault);//更新fact中变量值
                        update(baselineset_complete_spacefor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_spacepage);//更新fact中变量值
                        update(baselineset_complete_spacerelation_filter);//更新fact中变量值
                        update(baselineset_complete_spacerelation_page);//更新fact中变量值
                        update(baselineset_complete_spaceversion);//更新fact中变量值
            end

            //逻辑处理节点[重置版本参数]
            rule "resetparam2"
            ruleflow-group "baselineset_complete_spaceresetparam2"
            when
            then
                        update(baselineset_complete_spacedefault);//更新fact中变量值
                        update(baselineset_complete_spacefor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_spacepage);//更新fact中变量值
                        update(baselineset_complete_spacerelation_filter);//更新fact中变量值
                        update(baselineset_complete_spacerelation_page);//更新fact中变量值
                        update(baselineset_complete_spaceversion);//更新fact中变量值
            end

            //逻辑处理节点[填充产品需求主键标识]
            rule "prepareparam3"
            ruleflow-group "baselineset_complete_spaceprepareparam3"
            when
            then
                            baselineset_complete_spacepage.set("id",baselineset_complete_spacefor_temp_obj.get("targetid"));
                        update(baselineset_complete_spacedefault);//更新fact中变量值
                        update(baselineset_complete_spacefor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_spacepage);//更新fact中变量值
                        update(baselineset_complete_spacerelation_filter);//更新fact中变量值
                        update(baselineset_complete_spacerelation_page);//更新fact中变量值
                        update(baselineset_complete_spaceversion);//更新fact中变量值
            end

            //逻辑处理节点[获取页面]
            rule "deaction2"
            ruleflow-group "baselineset_complete_spacedeaction2"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(article_pageservice.get(baselineset_complete_spacepage.getId()),baselineset_complete_spacepage);
                        update(baselineset_complete_spacedefault);//更新fact中变量值
                        update(baselineset_complete_spacefor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_spacepage);//更新fact中变量值
                        update(baselineset_complete_spacerelation_filter);//更新fact中变量值
                        update(baselineset_complete_spacerelation_page);//更新fact中变量值
                        update(baselineset_complete_spaceversion);//更新fact中变量值
            end

            //逻辑处理节点[填充版本属性]
            rule "prepareparam4"
            ruleflow-group "baselineset_complete_spaceprepareparam4"
            when
            then
                            baselineset_complete_spaceversion.set("ownerid",baselineset_complete_spacefor_temp_obj.get("targetid"));
                            baselineset_complete_spaceversion.set("ownertype","PAGE");
                            baselineset_complete_spaceversion.set("name","设立基线创建版本");
                        update(baselineset_complete_spacedefault);//更新fact中变量值
                        update(baselineset_complete_spacefor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_spacepage);//更新fact中变量值
                        update(baselineset_complete_spacerelation_filter);//更新fact中变量值
                        update(baselineset_complete_spacerelation_page);//更新fact中变量值
                        update(baselineset_complete_spaceversion);//更新fact中变量值
            end

            //逻辑处理节点[创建新版本]
            rule "deaction3"
            ruleflow-group "baselineset_complete_spacedeaction3"
            when
            then
                        versionservice.commit(baselineset_complete_spaceversion);
                        update(baselineset_complete_spacedefault);//更新fact中变量值
                        update(baselineset_complete_spacefor_temp_obj);//更新fact中变量值
                        update(baselineset_complete_spacepage);//更新fact中变量值
                        update(baselineset_complete_spacerelation_filter);//更新fact中变量值
                        update(baselineset_complete_spacerelation_page);//更新fact中变量值
                        update(baselineset_complete_spaceversion);//更新fact中变量值
            end