package cn.ibizlab.plm.wiki.logic.article_pagelogic.count_comment;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagecount_commentdefault;
                global java.util.Map article_pagecount_commentcomment_num;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pagecount_commentbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pagecount_commentend1"
            when
            then
                        update(article_pagecount_commentdefault);//更新fact中变量值
                        update(article_pagecount_commentcomment_num);//更新fact中变量值
            end

            //逻辑处理节点[统计页面评论数]
            rule "rawsqlcall1"
            ruleflow-group "article_pagecount_commentrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",article_pagecount_commentdefault.get("article_page"));
    String strSql="SELECT COUNT(*) AS total FROM `comment` WHERE PRINCIPAL_TYPE = 'PAGE' AND CONTENT <> '<p><del>该评论已删除</del></p>' AND PRINCIPAL_ID = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysArticle_pageDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                article_pagecount_commentcomment_num.putAll(entity);
                            }
                        update(article_pagecount_commentdefault);//更新fact中变量值
                        update(article_pagecount_commentcomment_num);//更新fact中变量值
            end