package cn.ibizlab.plm.wiki.logic.article_pagelogic.create_recent;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagecreate_recentdefault;
                global cn.ibizlab.plm.core.base.domain.recent article_pagecreate_recentrecent;
                    global cn.ibizlab.plm.core.base.service.IrecentService recentservice;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pagecreate_recentbegin"
            when
            then
            end

            //逻辑处理节点[准备最近访问参数]
            rule "prepareparam1"
            ruleflow-group "article_pagecreate_recentprepareparam1"
            when
            then
                            article_pagecreate_recentrecent.set("ownerid",article_pagecreate_recentdefault.get("id"));
                            article_pagecreate_recentrecent.set("recentparentidentifier",article_pagecreate_recentdefault.get("spaceidentifier"));
                            article_pagecreate_recentrecent.set("identifier",article_pagecreate_recentdefault.get("identifier"));
                            article_pagecreate_recentrecent.set("recentparentname",article_pagecreate_recentdefault.get("spacename"));
                            article_pagecreate_recentrecent.set("recentparent",article_pagecreate_recentdefault.get("spaceid"));
                                article_pagecreate_recentrecent.set("createman",curuser.getSessionParams().get("srfpersonid"));
                            article_pagecreate_recentrecent.set("type","2");
                            article_pagecreate_recentrecent.set("name",article_pagecreate_recentdefault.get("publishname"));
                            article_pagecreate_recentrecent.set("ownertype","space");
                            article_pagecreate_recentrecent.set("ownersubtype","page");
                        update(article_pagecreate_recentdefault);//更新fact中变量值
                        update(article_pagecreate_recentrecent);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pagecreate_recentend1"
            when
            then
                        update(article_pagecreate_recentdefault);//更新fact中变量值
                        update(article_pagecreate_recentrecent);//更新fact中变量值
            end

            //逻辑处理节点[保存最近访问]
            rule "deaction1"
            ruleflow-group "article_pagecreate_recentdeaction1"
            when
            then
                        recentservice.save(article_pagecreate_recentrecent);
                        update(article_pagecreate_recentdefault);//更新fact中变量值
                        update(article_pagecreate_recentrecent);//更新fact中变量值
            end