package cn.ibizlab.plm.wiki.logic.article_pagelogic.create_categories;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagecreate_categoriesdefault;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagecreate_categoriesfilter;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagecreate_categoriespage;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagecreate_categoriespage_obj;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagecreate_categoriespage_page;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagecreate_categoriespagelist;
                    global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService article_pageservice;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pagecreate_categoriesbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "article_pagecreate_categoriesend2"
            when
            then
                        update(article_pagecreate_categoriesdefault);//更新fact中变量值
                        update(article_pagecreate_categoriesfilter);//更新fact中变量值
                        update(article_pagecreate_categoriespage);//更新fact中变量值
                        update(article_pagecreate_categoriespage_obj);//更新fact中变量值
                        update(article_pagecreate_categoriespage_page);//更新fact中变量值
                        update(article_pagecreate_categoriespagelist);//更新fact中变量值
            end

            //逻辑处理节点[直接sql调用]
            rule "rawsqlcall2"
            ruleflow-group "article_pagecreate_categoriesrawsqlcall2"
            when
            then
                        Map param = null;
                        String strSql="SELECT GROUP_CONCAT(t2.parent_id ORDER BY t1._id ASC SEPARATOR '/') AS concatenated_parent_ids FROM (     SELECT @r := parent_id as _id     FROM page     WHERE id = '4a9db83886481a910ad8e2189d44214e'     UNION ALL     SELECT @r := parent_id     FROM page, (SELECT @r := '4a9db83886481a910ad8e2189d44214e') as vars     WHERE page.id = @r AND @r IS NOT NULL ) t1 JOIN page t2 ON t1._id = t2.id";
                        iBzSysArticle_pageDefaultService.execute(strSql,param);//SQL调用
                        update(article_pagecreate_categoriesdefault);//更新fact中变量值
                        update(article_pagecreate_categoriesfilter);//更新fact中变量值
                        update(article_pagecreate_categoriespage);//更新fact中变量值
                        update(article_pagecreate_categoriespage_obj);//更新fact中变量值
                        update(article_pagecreate_categoriespage_page);//更新fact中变量值
                        update(article_pagecreate_categoriespagelist);//更新fact中变量值
            end

            //逻辑处理节点[准备过滤参数]
            rule "prepareparam1"
            ruleflow-group "article_pagecreate_categoriesprepareparam1"
            when
            then
                            article_pagecreate_categoriesfilter.set("n_space_id_eq","plm_space");
                            article_pagecreate_categoriesfilter.set("n_is_deleted_eq","0");
                            article_pagecreate_categoriesfilter.set("n_parent_id_isnotnull","1");
                        update(article_pagecreate_categoriesdefault);//更新fact中变量值
                        update(article_pagecreate_categoriesfilter);//更新fact中变量值
                        update(article_pagecreate_categoriespage);//更新fact中变量值
                        update(article_pagecreate_categoriespage_obj);//更新fact中变量值
                        update(article_pagecreate_categoriespage_page);//更新fact中变量值
                        update(article_pagecreate_categoriespagelist);//更新fact中变量值
            end

            //逻辑处理节点[查询指定页面结果]
            rule "dedataset1"
            ruleflow-group "article_pagecreate_categoriesdedataset1"
            when
            then
                        update(article_pagecreate_categoriesdefault);//更新fact中变量值
                        update(article_pagecreate_categoriesfilter);//更新fact中变量值
                        update(article_pagecreate_categoriespage);//更新fact中变量值
                        update(article_pagecreate_categoriespage_obj);//更新fact中变量值
                        update(article_pagecreate_categoriespage_page);//更新fact中变量值
                        update(article_pagecreate_categoriespagelist);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pagecreate_categoriesend1"
            when
            then
                        update(article_pagecreate_categoriesdefault);//更新fact中变量值
                        update(article_pagecreate_categoriesfilter);//更新fact中变量值
                        update(article_pagecreate_categoriespage);//更新fact中变量值
                        update(article_pagecreate_categoriespage_obj);//更新fact中变量值
                        update(article_pagecreate_categoriespage_page);//更新fact中变量值
                        update(article_pagecreate_categoriespagelist);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "article_pagecreate_categoriesloopsubcall1"
            when
            then
                        update(article_pagecreate_categoriesdefault);//更新fact中变量值
                        update(article_pagecreate_categoriesfilter);//更新fact中变量值
                        update(article_pagecreate_categoriespage);//更新fact中变量值
                        update(article_pagecreate_categoriespage_obj);//更新fact中变量值
                        update(article_pagecreate_categoriespage_page);//更新fact中变量值
                        update(article_pagecreate_categoriespagelist);//更新fact中变量值
            end

            //逻辑处理节点[重置page参数]
            rule "resetparam1"
            ruleflow-group "article_pagecreate_categoriesresetparam1"
            when
            then
                        update(article_pagecreate_categoriesdefault);//更新fact中变量值
                        update(article_pagecreate_categoriesfilter);//更新fact中变量值
                        update(article_pagecreate_categoriespage);//更新fact中变量值
                        update(article_pagecreate_categoriespage_obj);//更新fact中变量值
                        update(article_pagecreate_categoriespage_page);//更新fact中变量值
                        update(article_pagecreate_categoriespagelist);//更新fact中变量值
            end

            //逻辑处理节点[重置pagelist参数]
            rule "resetparam2"
            ruleflow-group "article_pagecreate_categoriesresetparam2"
            when
            then
                        update(article_pagecreate_categoriesdefault);//更新fact中变量值
                        update(article_pagecreate_categoriesfilter);//更新fact中变量值
                        update(article_pagecreate_categoriespage);//更新fact中变量值
                        update(article_pagecreate_categoriespage_obj);//更新fact中变量值
                        update(article_pagecreate_categoriespage_page);//更新fact中变量值
                        update(article_pagecreate_categoriespagelist);//更新fact中变量值
            end

            //逻辑处理节点[通过id查询树级结构]
            rule "rawsqlcall1"
            ruleflow-group "article_pagecreate_categoriesrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",article_pagecreate_categoriespage_obj.get("id"));
        param.put("param1",article_pagecreate_categoriespage_obj.get("id"));
    String strSql="SELECT GROUP_CONCAT(t2.parent_id ORDER BY t1._id ASC SEPARATOR '/') AS concatenated_parent_ids FROM (     SELECT @r := parent_id as _id     FROM page     WHERE id = #{et.param0}     UNION ALL     SELECT @r := parent_id     FROM page, (SELECT @r := #{et.param1}) as vars     WHERE page.id = @r AND @r IS NOT NULL ) t1 JOIN page t2 ON t1._id = t2.id";
                        java.util.List<JSONObject> entities=iBzSysArticle_pageDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    article_pagecreate_categoriespagelist.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(article_pagecreate_categoriesdefault);//更新fact中变量值
                        update(article_pagecreate_categoriesfilter);//更新fact中变量值
                        update(article_pagecreate_categoriespage);//更新fact中变量值
                        update(article_pagecreate_categoriespage_obj);//更新fact中变量值
                        update(article_pagecreate_categoriespage_page);//更新fact中变量值
                        update(article_pagecreate_categoriespagelist);//更新fact中变量值
            end

            //逻辑处理节点[拼接类别路径]
            rule "rawsfcode1"
            ruleflow-group "article_pagecreate_categoriesrawsfcode1"
            when
            then
                        update(article_pagecreate_categoriesdefault);//更新fact中变量值
                        update(article_pagecreate_categoriesfilter);//更新fact中变量值
                        update(article_pagecreate_categoriespage);//更新fact中变量值
                        update(article_pagecreate_categoriespage_obj);//更新fact中变量值
                        update(article_pagecreate_categoriespage_page);//更新fact中变量值
                        update(article_pagecreate_categoriespagelist);//更新fact中变量值
            end

            //逻辑处理节点[准备更新参数]
            rule "prepareparam2"
            ruleflow-group "article_pagecreate_categoriesprepareparam2"
            when
            then
                            article_pagecreate_categoriespage.set("id",article_pagecreate_categoriespage_obj.get("id"));
                            article_pagecreate_categoriespage.set("categories",article_pagecreate_categoriespagelist.get("concatenated_parent_ids"));
                        update(article_pagecreate_categoriesdefault);//更新fact中变量值
                        update(article_pagecreate_categoriesfilter);//更新fact中变量值
                        update(article_pagecreate_categoriespage);//更新fact中变量值
                        update(article_pagecreate_categoriespage_obj);//更新fact中变量值
                        update(article_pagecreate_categoriespage_page);//更新fact中变量值
                        update(article_pagecreate_categoriespagelist);//更新fact中变量值
            end

            //逻辑处理节点[更新操作]
            rule "deaction1"
            ruleflow-group "article_pagecreate_categoriesdeaction1"
            when
            then
                        article_pageservice.update(article_pagecreate_categoriespage);
                        update(article_pagecreate_categoriesdefault);//更新fact中变量值
                        update(article_pagecreate_categoriesfilter);//更新fact中变量值
                        update(article_pagecreate_categoriespage);//更新fact中变量值
                        update(article_pagecreate_categoriespage_obj);//更新fact中变量值
                        update(article_pagecreate_categoriespage_page);//更新fact中变量值
                        update(article_pagecreate_categoriespagelist);//更新fact中变量值
            end