package cn.ibizlab.plm.wiki.logic.article_pagelogic.export_to_pdf;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pageexport_to_pdfdefault;
                global java.util.Map article_pageexport_to_pdfpdf_file;
                global java.util.Map article_pageexport_to_pdfweb_response;
                    global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService article_pageservice;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pageexport_to_pdfbegin"
            when
            then
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "article_pageexport_to_pdfdeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(article_pageservice.get(article_pageexport_to_pdfdefault.getId()),article_pageexport_to_pdfdefault);
                        update(article_pageexport_to_pdfdefault);//更新fact中变量值
                        update(article_pageexport_to_pdfpdf_file);//更新fact中变量值
                        update(article_pageexport_to_pdfweb_response);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pageexport_to_pdfend1"
            when
            then
                        update(article_pageexport_to_pdfdefault);//更新fact中变量值
                        update(article_pageexport_to_pdfpdf_file);//更新fact中变量值
                        update(article_pageexport_to_pdfweb_response);//更新fact中变量值
            end

            //逻辑处理节点[服务插件]
            rule "sfplugin1"
            ruleflow-group "article_pageexport_to_pdfsfplugin1"
            when
            then
                        update(article_pageexport_to_pdfdefault);//更新fact中变量值
                        update(article_pageexport_to_pdfpdf_file);//更新fact中变量值
                        update(article_pageexport_to_pdfweb_response);//更新fact中变量值
            end