package cn.ibizlab.plm.wiki.logic.article_pagelogic.favorite;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.Article_page article_pagefavoritedefault;
                global java.util.Map article_pagefavoritectx;
                global cn.ibizlab.plm.core.base.domain.Favorite article_pagefavoritefavorite;
                    global cn.ibizlab.plm.core.base.service.IFavoriteService favoriteservice;
        global cn.ibizlab.plm.core.wiki.service.IArticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pagefavoritebegin"
            when
            then
            end

            //逻辑处理节点[填充用户标识和收藏业务对象标识]
            rule "prepareparam1"
            ruleflow-group "article_pagefavoriteprepareparam1"
            when
            then
                                article_pagefavoritefavorite.set("createman",curuser.getSessionParams().get("srfuserid"));
                            article_pagefavoritefavorite.set("ownertype","article_page");
                            article_pagefavoritefavorite.set("ownerid",article_pagefavoritedefault.get("owner_id"));
                        update(article_pagefavoritedefault);//更新fact中变量值
                        update(article_pagefavoritectx);//更新fact中变量值
                        update(article_pagefavoritefavorite);//更新fact中变量值
            end

            //逻辑处理节点[生成收藏数据]
            rule "deaction1"
            ruleflow-group "article_pagefavoritedeaction1"
            when
            then
                        favoriteservice.save(article_pagefavoritefavorite);
                        update(article_pagefavoritedefault);//更新fact中变量值
                        update(article_pagefavoritectx);//更新fact中变量值
                        update(article_pagefavoritefavorite);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pagefavoriteend1"
            when
            then
                        update(article_pagefavoritedefault);//更新fact中变量值
                        update(article_pagefavoritectx);//更新fact中变量值
                        update(article_pagefavoritefavorite);//更新fact中变量值
            end