package cn.ibizlab.plm.wiki.logic.article_pagelogic.get_shared_info;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pageget_shared_infodefault;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pageget_shared_inforesult;
                    global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService article_pageservice;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pageget_shared_infobegin"
            when
            then
            end

            //逻辑处理节点[获取共享页面]
            rule "deaction1"
            ruleflow-group "article_pageget_shared_infodeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(article_pageservice.get(article_pageget_shared_infodefault.getId()),article_pageget_shared_infodefault);
                        update(article_pageget_shared_infodefault);//更新fact中变量值
                        update(article_pageget_shared_inforesult);//更新fact中变量值
            end

            //逻辑处理节点[获取访问密码]
            rule "rawsqlcall1"
            ruleflow-group "article_pageget_shared_inforawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",article_pageget_shared_infodefault.get("id"));
    String strSql="select `access_password` from `page` where `id` = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysArticle_pageDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    article_pageget_shared_infodefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(article_pageget_shared_infodefault);//更新fact中变量值
                        update(article_pageget_shared_inforesult);//更新fact中变量值
            end

            //逻辑处理节点[访问密码解密]
            rule "delogic1"
            ruleflow-group "article_pageget_shared_infodelogic1"
            when
            then
                        update(article_pageget_shared_infodefault);//更新fact中变量值
                        update(article_pageget_shared_inforesult);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "article_pageget_shared_infodebugparam1"
            when
            then
                        update(article_pageget_shared_infodefault);//更新fact中变量值
                        update(article_pageget_shared_inforesult);//更新fact中变量值
            end

            //逻辑处理节点[设置结果参数]
            rule "prepareparam2"
            ruleflow-group "article_pageget_shared_infoprepareparam2"
            when
            then
                            article_pageget_shared_inforesult.set("id",article_pageget_shared_infodefault.get("id"));
                            article_pageget_shared_inforesult.set("sharedby",article_pageget_shared_infodefault.get("sharedby"));
                            article_pageget_shared_inforesult.set("sharedtime",article_pageget_shared_infodefault.get("sharedtime"));
                            article_pageget_shared_inforesult.set("accesspassword",article_pageget_shared_infodefault.get("accesspassword"));
                            article_pageget_shared_inforesult.set("isshared",article_pageget_shared_infodefault.get("isshared"));
                            article_pageget_shared_inforesult.set("issharedsubset",article_pageget_shared_infodefault.get("issharedsubset"));
                            article_pageget_shared_inforesult.set("expirationdate",article_pageget_shared_infodefault.get("expirationdate"));
                            article_pageget_shared_inforesult.set("spaceid",article_pageget_shared_infodefault.get("spaceid"));
                            article_pageget_shared_infodefault.set("name",article_pageget_shared_infodefault.get("name"));
                            article_pageget_shared_inforesult.set("publishname",article_pageget_shared_infodefault.get("publishname"));
                        update(article_pageget_shared_infodefault);//更新fact中变量值
                        update(article_pageget_shared_inforesult);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pageget_shared_infoend1"
            when
            then
                        update(article_pageget_shared_infodefault);//更新fact中变量值
                        update(article_pageget_shared_inforesult);//更新fact中变量值
            end