package cn.ibizlab.plm.wiki.logic.article_pagelogic.publish_page_test;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagepublish_page_testdefault;
                global java.util.Map article_pagepublish_page_testfilter;
                global cn.ibizlab.plm.core.base.domain.version article_pagepublish_page_testversion_pages;
                    global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService article_pageservice;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pagepublish_page_testbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pagepublish_page_testend1"
            when
            then
                        update(article_pagepublish_page_testdefault);//更新fact中变量值
                        update(article_pagepublish_page_testfilter);//更新fact中变量值
                        update(article_pagepublish_page_testversion_pages);//更新fact中变量值
            end

            //逻辑处理节点[设置发布时间]
            rule "rawsfcode1"
            ruleflow-group "article_pagepublish_page_testrawsfcode1"
            when
            then
                        update(article_pagepublish_page_testdefault);//更新fact中变量值
                        update(article_pagepublish_page_testfilter);//更新fact中变量值
                        update(article_pagepublish_page_testversion_pages);//更新fact中变量值
            end

            //逻辑处理节点[设置发布状态及发布人]
            rule "prepareparam1"
            ruleflow-group "article_pagepublish_page_testprepareparam1"
            when
            then
                            article_pagepublish_page_testdefault.set("ispublished","1");
                                article_pagepublish_page_testdefault.set("publishman",curuser.getSessionParams().get("srfpersonid"));
                        update(article_pagepublish_page_testdefault);//更新fact中变量值
                        update(article_pagepublish_page_testfilter);//更新fact中变量值
                        update(article_pagepublish_page_testversion_pages);//更新fact中变量值
            end

            //逻辑处理节点[删除草稿版本]
            rule "rawsqlcall1"
            ruleflow-group "article_pagepublish_page_testrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",article_pagepublish_page_testdefault.get("id"));
    String strSql="DELETE FROM version  where OWNER_ID = #{et.param0}  and JSON_EXTRACT(data, '$.is_published') = 0  and OWNER_TYPE = 'PAGE' ORDER BY name desc;";
                        iBzSysArticle_pageDefaultService.execute(strSql,param);//SQL调用
                        update(article_pagepublish_page_testdefault);//更新fact中变量值
                        update(article_pagepublish_page_testfilter);//更新fact中变量值
                        update(article_pagepublish_page_testversion_pages);//更新fact中变量值
            end

            //逻辑处理节点[保存发布页面信息]
            rule "deaction1"
            ruleflow-group "article_pagepublish_page_testdeaction1"
            when
            then
                        article_pageservice.save(article_pagepublish_page_testdefault);
                        update(article_pagepublish_page_testdefault);//更新fact中变量值
                        update(article_pagepublish_page_testfilter);//更新fact中变量值
                        update(article_pagepublish_page_testversion_pages);//更新fact中变量值
            end