package cn.ibizlab.plm.wiki.logic.article_pagelogic.publish_page;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagepublish_pagedefault;
                global java.util.Map article_pagepublish_pagefilter;
                global cn.ibizlab.plm.core.base.domain.version article_pagepublish_pageversion_filter;
                global cn.ibizlab.plm.core.base.domain.version article_pagepublish_pageversion_pages;
                global cn.ibizlab.plm.core.base.domain.version article_pagepublish_pageversion_temp;
                    global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService article_pageservice;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pagepublish_pagebegin"
            when
            then
            end

            //逻辑处理节点[设置发布信息]
            rule "prepareparam1"
            ruleflow-group "article_pagepublish_pageprepareparam1"
            when
            then
                            article_pagepublish_pagedefault.set("publishcontent",article_pagepublish_pagedefault.get("content"));
                            article_pagepublish_pagedefault.set("publishname",article_pagepublish_pagedefault.get("name"));
                                article_pagepublish_pagedefault.set("publishman",curuser.getSessionParams().get("srfpersonid"));
                        update(article_pagepublish_pagedefault);//更新fact中变量值
                        update(article_pagepublish_pagefilter);//更新fact中变量值
                        update(article_pagepublish_pageversion_filter);//更新fact中变量值
                        update(article_pagepublish_pageversion_pages);//更新fact中变量值
                        update(article_pagepublish_pageversion_temp);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam5"
            ruleflow-group "article_pagepublish_pageprepareparam5"
            when
            then
                        update(article_pagepublish_pagedefault);//更新fact中变量值
                        update(article_pagepublish_pagefilter);//更新fact中变量值
                        update(article_pagepublish_pageversion_filter);//更新fact中变量值
                        update(article_pagepublish_pageversion_pages);//更新fact中变量值
                        update(article_pagepublish_pageversion_temp);//更新fact中变量值
            end

            //逻辑处理节点[设置发布时间]
            rule "rawsfcode1"
            ruleflow-group "article_pagepublish_pagerawsfcode1"
            when
            then
                        update(article_pagepublish_pagedefault);//更新fact中变量值
                        update(article_pagepublish_pagefilter);//更新fact中变量值
                        update(article_pagepublish_pageversion_filter);//更新fact中变量值
                        update(article_pagepublish_pageversion_pages);//更新fact中变量值
                        update(article_pagepublish_pageversion_temp);//更新fact中变量值
            end

            //逻辑处理节点[重置id]
            rule "prepareparam4"
            ruleflow-group "article_pagepublish_pageprepareparam4"
            when
            then
                                article_pagepublish_pagedefault.set("id",null);
                        update(article_pagepublish_pagedefault);//更新fact中变量值
                        update(article_pagepublish_pagefilter);//更新fact中变量值
                        update(article_pagepublish_pageversion_filter);//更新fact中变量值
                        update(article_pagepublish_pageversion_pages);//更新fact中变量值
                        update(article_pagepublish_pageversion_temp);//更新fact中变量值
            end

            //逻辑处理节点[设置发布状态]
            rule "prepareparam2"
            ruleflow-group "article_pagepublish_pageprepareparam2"
            when
            then
                            article_pagepublish_pagedefault.set("ispublished","1");
                            article_pagepublish_pagedefault.set("published","1");
                        update(article_pagepublish_pagedefault);//更新fact中变量值
                        update(article_pagepublish_pagefilter);//更新fact中变量值
                        update(article_pagepublish_pageversion_filter);//更新fact中变量值
                        update(article_pagepublish_pageversion_pages);//更新fact中变量值
                        update(article_pagepublish_pageversion_temp);//更新fact中变量值
            end

            //逻辑处理节点[保存发布页面信息]
            rule "deaction2"
            ruleflow-group "article_pagepublish_pagedeaction2"
            when
            then
                        article_pageservice.save(article_pagepublish_pagedefault);
                        update(article_pagepublish_pagedefault);//更新fact中变量值
                        update(article_pagepublish_pagefilter);//更新fact中变量值
                        update(article_pagepublish_pageversion_filter);//更新fact中变量值
                        update(article_pagepublish_pageversion_pages);//更新fact中变量值
                        update(article_pagepublish_pageversion_temp);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "article_pagepublish_pageend2"
            when
            then
                        update(article_pagepublish_pagedefault);//更新fact中变量值
                        update(article_pagepublish_pagefilter);//更新fact中变量值
                        update(article_pagepublish_pageversion_filter);//更新fact中变量值
                        update(article_pagepublish_pageversion_pages);//更新fact中变量值
                        update(article_pagepublish_pageversion_temp);//更新fact中变量值
            end