package cn.ibizlab.plm.wiki.logic.article_pagelogic.recover;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagerecoverdefault;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagerecoverfor_temp_obj;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagerecoveridea_filter;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagerecoveridea_page;
                    global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService article_pageservice;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pagerecoverbegin"
            when
            then
            end

            //逻辑处理节点[设置删除状态]
            rule "prepareparam2"
            ruleflow-group "article_pagerecoverprepareparam2"
            when
            then
                            article_pagerecoverdefault.set("isdeleted","0");
                                article_pagerecoverdefault.set("parentid",null);
                        update(article_pagerecoverdefault);//更新fact中变量值
                        update(article_pagerecoverfor_temp_obj);//更新fact中变量值
                        update(article_pagerecoveridea_filter);//更新fact中变量值
                        update(article_pagerecoveridea_page);//更新fact中变量值
            end

            //逻辑处理节点[更新删除状态]
            rule "deaction1"
            ruleflow-group "article_pagerecoverdeaction1"
            when
            then
                        article_pageservice.update(article_pagerecoverdefault);
                        update(article_pagerecoverdefault);//更新fact中变量值
                        update(article_pagerecoverfor_temp_obj);//更新fact中变量值
                        update(article_pagerecoveridea_filter);//更新fact中变量值
                        update(article_pagerecoveridea_page);//更新fact中变量值
            end

            //逻辑处理节点[恢复最近访问]
            rule "rawsqlcall1"
            ruleflow-group "article_pagerecoverrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",article_pagerecoverdefault.get("id"));
    String strSql="update recent set IS_DELETED=0 where owner_id=#{et.param0} and owner_subtype='page'";
                        iBzSysArticle_pageDefaultService.execute(strSql,param);//SQL调用
                        update(article_pagerecoverdefault);//更新fact中变量值
                        update(article_pagerecoverfor_temp_obj);//更新fact中变量值
                        update(article_pagerecoveridea_filter);//更新fact中变量值
                        update(article_pagerecoveridea_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pagerecoverend1"
            when
            then
                        update(article_pagerecoverdefault);//更新fact中变量值
                        update(article_pagerecoverfor_temp_obj);//更新fact中变量值
                        update(article_pagerecoveridea_filter);//更新fact中变量值
                        update(article_pagerecoveridea_page);//更新fact中变量值
            end