package cn.ibizlab.plm.wiki.logic.article_pagelogic.recover_version;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.Article_page article_pagerecover_versiondefault;
                global cn.ibizlab.plm.core.projmgmt.domain.Version article_pagerecover_versionversion;
                    global cn.ibizlab.plm.core.projmgmt.service.IVersionService versionservice;
        global cn.ibizlab.plm.core.wiki.service.IArticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pagerecover_versionbegin"
            when
            then
            end

            //逻辑处理节点[提取版本]
            rule "prepareparam"
            ruleflow-group "article_pagerecover_versionprepareparam"
            when
            then
                            article_pagerecover_versionversion.set("id",article_pagerecover_versiondefault.get("srfversionid"));
                            article_pagerecover_versionversion.set("ownertype","PAGE");
                            article_pagerecover_versionversion.set("ownerid",article_pagerecover_versiondefault.get("id"));
                        update(article_pagerecover_versiondefault);//更新fact中变量值
                        update(article_pagerecover_versionversion);//更新fact中变量值
            end

            //逻辑处理节点[恢复版本]
            rule "deaction"
            ruleflow-group "article_pagerecover_versiondeaction"
            when
            then
                        versionservice.restore(article_pagerecover_versionversion);
                        update(article_pagerecover_versiondefault);//更新fact中变量值
                        update(article_pagerecover_versionversion);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pagerecover_versionend1"
            when
            then
                        update(article_pagerecover_versiondefault);//更新fact中变量值
                        update(article_pagerecover_versionversion);//更新fact中变量值
            end