package cn.ibizlab.plm.wiki.logic.article_pagelogic.reset_shared_pwd;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagereset_shared_pwddefault;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pagereset_shared_pwdbegin"
            when
            then
            end

            //逻辑处理节点[置空访问密码]
            rule "prepareparam1"
            ruleflow-group "article_pagereset_shared_pwdprepareparam1"
            when
            then
                                article_pagereset_shared_pwddefault.set("accesspassword",null);
                        update(article_pagereset_shared_pwddefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pagereset_shared_pwdend1"
            when
            then
                        update(article_pagereset_shared_pwddefault);//更新fact中变量值
            end