package cn.ibizlab.plm.wiki.logic.article_pagelogic.save_draft;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagesave_draftdefault;
                    global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService article_pageservice;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pagesave_draftbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pagesave_draftend1"
            when
            then
                        update(article_pagesave_draftdefault);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "article_pagesave_draftprepareparam1"
            when
            then
                            article_pagesave_draftdefault.set("ispublished","1");
                        update(article_pagesave_draftdefault);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "article_pagesave_draftdeaction1"
            when
            then
                        article_pageservice.save(article_pagesave_draftdefault);
                        update(article_pagesave_draftdefault);//更新fact中变量值
            end