package cn.ibizlab.plm.wiki.logic.article_pagelogic.save_to_stencil;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.Article_page article_pagesave_to_stencildefault;
                global java.util.Map article_pagesave_to_stencilfor_temp_obj;
                global java.util.Map article_pagesave_to_stencilsrfactionparam;
                global cn.ibizlab.plm.core.wiki.domain.Stencil article_pagesave_to_stencilstencil_info;
                    global cn.ibizlab.plm.core.wiki.service.IStencilService stencilservice;
        global cn.ibizlab.plm.core.wiki.service.IArticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pagesave_to_stencilbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "article_pagesave_to_stencilprepareparam2"
            when
            then
                            article_pagesave_to_stencilstencil_info.set("name",article_pagesave_to_stencilfor_temp_obj.get("name"));
                            article_pagesave_to_stencilstencil_info.set("content",article_pagesave_to_stencildefault.get("content"));
                            article_pagesave_to_stencilstencil_info.set("spaceid",article_pagesave_to_stencildefault.get("spaceid"));
                        update(article_pagesave_to_stencildefault);//更新fact中变量值
                        update(article_pagesave_to_stencilfor_temp_obj);//更新fact中变量值
                        update(article_pagesave_to_stencilsrfactionparam);//更新fact中变量值
                        update(article_pagesave_to_stencilstencil_info);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pagesave_to_stencilend1"
            when
            then
                        update(article_pagesave_to_stencildefault);//更新fact中变量值
                        update(article_pagesave_to_stencilfor_temp_obj);//更新fact中变量值
                        update(article_pagesave_to_stencilsrfactionparam);//更新fact中变量值
                        update(article_pagesave_to_stencilstencil_info);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "article_pagesave_to_stencildeaction1"
            when
            then
                        stencilservice.create(article_pagesave_to_stencilstencil_info);
                        update(article_pagesave_to_stencildefault);//更新fact中变量值
                        update(article_pagesave_to_stencilfor_temp_obj);//更新fact中变量值
                        update(article_pagesave_to_stencilsrfactionparam);//更新fact中变量值
                        update(article_pagesave_to_stencilstencil_info);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "article_pagesave_to_stencildebugparam1"
            when
            then
                        update(article_pagesave_to_stencildefault);//更新fact中变量值
                        update(article_pagesave_to_stencilfor_temp_obj);//更新fact中变量值
                        update(article_pagesave_to_stencilsrfactionparam);//更新fact中变量值
                        update(article_pagesave_to_stencilstencil_info);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "article_pagesave_to_stencilprepareparam1"
            when
            then
                            article_pagesave_to_stencilsrfactionparam.set("",article_pagesave_to_stencildefault.get("srfactionparam"));
                        update(article_pagesave_to_stencildefault);//更新fact中变量值
                        update(article_pagesave_to_stencilfor_temp_obj);//更新fact中变量值
                        update(article_pagesave_to_stencilsrfactionparam);//更新fact中变量值
                        update(article_pagesave_to_stencilstencil_info);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "article_pagesave_to_stencilloopsubcall1"
            when
            then
                        update(article_pagesave_to_stencildefault);//更新fact中变量值
                        update(article_pagesave_to_stencilfor_temp_obj);//更新fact中变量值
                        update(article_pagesave_to_stencilsrfactionparam);//更新fact中变量值
                        update(article_pagesave_to_stencilstencil_info);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam2"
            ruleflow-group "article_pagesave_to_stencildebugparam2"
            when
            then
                        update(article_pagesave_to_stencildefault);//更新fact中变量值
                        update(article_pagesave_to_stencilfor_temp_obj);//更新fact中变量值
                        update(article_pagesave_to_stencilsrfactionparam);//更新fact中变量值
                        update(article_pagesave_to_stencilstencil_info);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam3"
            ruleflow-group "article_pagesave_to_stencilprepareparam3"
            when
            then
                            article_pagesave_to_stencilstencil_info.set("name",article_pagesave_to_stencilfor_temp_obj.get("name"));
                            article_pagesave_to_stencilstencil_info.set("content",article_pagesave_to_stencildefault.get("content"));
                        update(article_pagesave_to_stencildefault);//更新fact中变量值
                        update(article_pagesave_to_stencilfor_temp_obj);//更新fact中变量值
                        update(article_pagesave_to_stencilsrfactionparam);//更新fact中变量值
                        update(article_pagesave_to_stencilstencil_info);//更新fact中变量值
            end