package cn.ibizlab.plm.wiki.logic.article_pagelogic.shared_setting;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pageshared_settingdefault;
                    global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService article_pageservice;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pageshared_settingbegin"
            when
            then
            end

            //逻辑处理节点[置空有效期]
            rule "prepareparam1"
            ruleflow-group "article_pageshared_settingprepareparam1"
            when
            then
                                article_pageshared_settingdefault.set("expirationdate",null);
                        update(article_pageshared_settingdefault);//更新fact中变量值
            end

            //逻辑处理节点[抛出异常]
            rule "throwexception1"
            ruleflow-group "article_pageshared_settingthrowexception1"
            when
            then
                        update(article_pageshared_settingdefault);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "article_pageshared_settingprepareparam2"
            when
            then
                            article_pageshared_settingdefault.set("isshared","1");
                        update(article_pageshared_settingdefault);//更新fact中变量值
            end

            //逻辑处理节点[抛出异常]
            rule "throwexception2"
            ruleflow-group "article_pageshared_settingthrowexception2"
            when
            then
                        update(article_pageshared_settingdefault);//更新fact中变量值
            end

            //逻辑处理节点[置空密码]
            rule "prepareparam3"
            ruleflow-group "article_pageshared_settingprepareparam3"
            when
            then
                                article_pageshared_settingdefault.set("accesspassword",null);
                        update(article_pageshared_settingdefault);//更新fact中变量值
            end

            //逻辑处理节点[填充共享时间、共享人]
            rule "rawsfcode1"
            ruleflow-group "article_pageshared_settingrawsfcode1"
            when
            then
                        update(article_pageshared_settingdefault);//更新fact中变量值
            end

            //逻辑处理节点[更新页面共享设置]
            rule "deaction1"
            ruleflow-group "article_pageshared_settingdeaction1"
            when
            then
                        article_pageservice.update(article_pageshared_settingdefault);
                        update(article_pageshared_settingdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pageshared_settingend1"
            when
            then
                        update(article_pageshared_settingdefault);//更新fact中变量值
            end