package cn.ibizlab.plm.wiki.logic.article_pagelogic.sync_name;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.article_page article_pagesync_namedefault;
        global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService iBzSysArticle_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "article_pagesync_namebegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "article_pagesync_nameend1"
            when
            then
                        update(article_pagesync_namedefault);//更新fact中变量值
            end

            //逻辑处理节点[设置共享人名称]
            rule "prepareparam1"
            ruleflow-group "article_pagesync_nameprepareparam1"
            when
            then
                            article_pagesync_namedefault.set("publishname",article_pagesync_namedefault.get("name"));
                        update(article_pagesync_namedefault);//更新fact中变量值
            end