package cn.ibizlab.plm.testmgmt.logic.reviewlogic.all_submit;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.review reviewall_submitdefault;
        global cn.ibizlab.plm.core.testmgmt.service.IreviewService iBzSysReviewDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "reviewall_submitbegin"
            when
            then
            end