package cn.ibizlab.plm.testmgmt.logic.reviewlogic.completed_review;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.review reviewcompleted_reviewdefault;
                global java.util.Map reviewcompleted_reviewcase_number;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content reviewcompleted_reviewcontent_fliter;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content reviewcompleted_reviewcontent_list;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content reviewcompleted_reviewcontent_obj;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content reviewcompleted_reviewcontent_page;
                global java.util.Map reviewcompleted_reviewresult;
                global cn.ibizlab.plm.core.testmgmt.domain.review_result reviewcompleted_reviewresult_list;
                global cn.ibizlab.plm.core.testmgmt.domain.review_result reviewcompleted_reviewresult_obj;
                global cn.ibizlab.plm.core.testmgmt.domain.review reviewcompleted_reviewreview_obj;
                global java.util.Map reviewcompleted_reviewsrfactionparam;
                global java.util.Map reviewcompleted_reviewtmp_obj;
                    global cn.ibizlab.plm.core.testmgmt.service.Ireview_contentService review_contentservice;
                    global cn.ibizlab.plm.core.testmgmt.service.Ireview_resultService review_resultservice;
        global cn.ibizlab.plm.core.testmgmt.service.IreviewService iBzSysReviewDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "reviewcompleted_reviewbegin"
            when
            then
            end

            //逻辑处理节点[完成评审]
            rule "deaction2"
            ruleflow-group "reviewcompleted_reviewdeaction2"
            when
            then
                        review_contentservice.complete_review(reviewcompleted_reviewdefault);
                        update(reviewcompleted_reviewdefault);//更新fact中变量值
                        update(reviewcompleted_reviewcase_number);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_fliter);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_list);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_obj);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_page);//更新fact中变量值
                        update(reviewcompleted_reviewresult);//更新fact中变量值
                        update(reviewcompleted_reviewresult_list);//更新fact中变量值
                        update(reviewcompleted_reviewresult_obj);//更新fact中变量值
                        update(reviewcompleted_reviewreview_obj);//更新fact中变量值
                        update(reviewcompleted_reviewsrfactionparam);//更新fact中变量值
                        update(reviewcompleted_reviewtmp_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall3"
            ruleflow-group "reviewcompleted_reviewloopsubcall3"
            when
            then
                        update(reviewcompleted_reviewdefault);//更新fact中变量值
                        update(reviewcompleted_reviewcase_number);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_fliter);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_list);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_obj);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_page);//更新fact中变量值
                        update(reviewcompleted_reviewresult);//更新fact中变量值
                        update(reviewcompleted_reviewresult_list);//更新fact中变量值
                        update(reviewcompleted_reviewresult_obj);//更新fact中变量值
                        update(reviewcompleted_reviewreview_obj);//更新fact中变量值
                        update(reviewcompleted_reviewsrfactionparam);//更新fact中变量值
                        update(reviewcompleted_reviewtmp_obj);//更新fact中变量值
            end

            //逻辑处理节点[设置评审内容过滤器]
            rule "prepareparam10"
            ruleflow-group "reviewcompleted_reviewprepareparam10"
            when
            then
                            reviewcompleted_reviewcontent_fliter.set("n_principal_id_eq",reviewcompleted_reviewdefault.get("id"));
                        update(reviewcompleted_reviewdefault);//更新fact中变量值
                        update(reviewcompleted_reviewcase_number);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_fliter);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_list);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_obj);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_page);//更新fact中变量值
                        update(reviewcompleted_reviewresult);//更新fact中变量值
                        update(reviewcompleted_reviewresult_list);//更新fact中变量值
                        update(reviewcompleted_reviewresult_obj);//更新fact中变量值
                        update(reviewcompleted_reviewreview_obj);//更新fact中变量值
                        update(reviewcompleted_reviewsrfactionparam);//更新fact中变量值
                        update(reviewcompleted_reviewtmp_obj);//更新fact中变量值
            end

            //逻辑处理节点[获取评审内容]
            rule "dedataset1"
            ruleflow-group "reviewcompleted_reviewdedataset1"
            when
            then
                        update(reviewcompleted_reviewdefault);//更新fact中变量值
                        update(reviewcompleted_reviewcase_number);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_fliter);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_list);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_obj);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_page);//更新fact中变量值
                        update(reviewcompleted_reviewresult);//更新fact中变量值
                        update(reviewcompleted_reviewresult_list);//更新fact中变量值
                        update(reviewcompleted_reviewresult_obj);//更新fact中变量值
                        update(reviewcompleted_reviewreview_obj);//更新fact中变量值
                        update(reviewcompleted_reviewsrfactionparam);//更新fact中变量值
                        update(reviewcompleted_reviewtmp_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环评审内容]
            rule "loopsubcall1"
            ruleflow-group "reviewcompleted_reviewloopsubcall1"
            when
            then
                        update(reviewcompleted_reviewdefault);//更新fact中变量值
                        update(reviewcompleted_reviewcase_number);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_fliter);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_list);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_obj);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_page);//更新fact中变量值
                        update(reviewcompleted_reviewresult);//更新fact中变量值
                        update(reviewcompleted_reviewresult_list);//更新fact中变量值
                        update(reviewcompleted_reviewresult_obj);//更新fact中变量值
                        update(reviewcompleted_reviewreview_obj);//更新fact中变量值
                        update(reviewcompleted_reviewsrfactionparam);//更新fact中变量值
                        update(reviewcompleted_reviewtmp_obj);//更新fact中变量值
            end

            //逻辑处理节点[准备评审参数]
            rule "prepareparam9"
            ruleflow-group "reviewcompleted_reviewprepareparam9"
            when
            then
                            reviewcompleted_reviewsrfactionparam.set("",reviewcompleted_reviewdefault.get("srfactionparam"));
                        update(reviewcompleted_reviewdefault);//更新fact中变量值
                        update(reviewcompleted_reviewcase_number);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_fliter);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_list);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_obj);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_page);//更新fact中变量值
                        update(reviewcompleted_reviewresult);//更新fact中变量值
                        update(reviewcompleted_reviewresult_list);//更新fact中变量值
                        update(reviewcompleted_reviewresult_obj);//更新fact中变量值
                        update(reviewcompleted_reviewreview_obj);//更新fact中变量值
                        update(reviewcompleted_reviewsrfactionparam);//更新fact中变量值
                        update(reviewcompleted_reviewtmp_obj);//更新fact中变量值
            end

            //逻辑处理节点[设置变量]
            rule "prepareparam7"
            ruleflow-group "reviewcompleted_reviewprepareparam7"
            when
            then
                            reviewcompleted_reviewreview_obj.set("id",reviewcompleted_reviewdefault.get("id"));
                            reviewcompleted_reviewdefault.set("curstage_id",reviewcompleted_reviewtmp_obj.get("stage_id"));
                            reviewcompleted_reviewdefault.set("principal_id",reviewcompleted_reviewdefault.get("id"));
                            reviewcompleted_reviewresult.set("",reviewcompleted_reviewtmp_obj.get("result"));
                            reviewcompleted_reviewcase_number.set("",reviewcompleted_reviewtmp_obj.get("case_number"));
                        update(reviewcompleted_reviewdefault);//更新fact中变量值
                        update(reviewcompleted_reviewcase_number);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_fliter);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_list);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_obj);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_page);//更新fact中变量值
                        update(reviewcompleted_reviewresult);//更新fact中变量值
                        update(reviewcompleted_reviewresult_list);//更新fact中变量值
                        update(reviewcompleted_reviewresult_obj);//更新fact中变量值
                        update(reviewcompleted_reviewreview_obj);//更新fact中变量值
                        update(reviewcompleted_reviewsrfactionparam);//更新fact中变量值
                        update(reviewcompleted_reviewtmp_obj);//更新fact中变量值
            end

            //逻辑处理节点[设置评审结果]
            rule "prepareparam2"
            ruleflow-group "reviewcompleted_reviewprepareparam2"
            when
            then
                            reviewcompleted_reviewresult_list.set("",reviewcompleted_reviewcontent_obj.get("stageresults"));
                        update(reviewcompleted_reviewdefault);//更新fact中变量值
                        update(reviewcompleted_reviewcase_number);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_fliter);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_list);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_obj);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_page);//更新fact中变量值
                        update(reviewcompleted_reviewresult);//更新fact中变量值
                        update(reviewcompleted_reviewresult_list);//更新fact中变量值
                        update(reviewcompleted_reviewresult_obj);//更新fact中变量值
                        update(reviewcompleted_reviewreview_obj);//更新fact中变量值
                        update(reviewcompleted_reviewsrfactionparam);//更新fact中变量值
                        update(reviewcompleted_reviewtmp_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环评审结果]
            rule "loopsubcall2"
            ruleflow-group "reviewcompleted_reviewloopsubcall2"
            when
            then
                        update(reviewcompleted_reviewdefault);//更新fact中变量值
                        update(reviewcompleted_reviewcase_number);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_fliter);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_list);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_obj);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_page);//更新fact中变量值
                        update(reviewcompleted_reviewresult);//更新fact中变量值
                        update(reviewcompleted_reviewresult_list);//更新fact中变量值
                        update(reviewcompleted_reviewresult_obj);//更新fact中变量值
                        update(reviewcompleted_reviewreview_obj);//更新fact中变量值
                        update(reviewcompleted_reviewsrfactionparam);//更新fact中变量值
                        update(reviewcompleted_reviewtmp_obj);//更新fact中变量值
            end

            //逻辑处理节点[输出循环数据]
            rule "debugparam1"
            ruleflow-group "reviewcompleted_reviewdebugparam1"
            when
            then
                        update(reviewcompleted_reviewdefault);//更新fact中变量值
                        update(reviewcompleted_reviewcase_number);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_fliter);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_list);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_obj);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_page);//更新fact中变量值
                        update(reviewcompleted_reviewresult);//更新fact中变量值
                        update(reviewcompleted_reviewresult_list);//更新fact中变量值
                        update(reviewcompleted_reviewresult_obj);//更新fact中变量值
                        update(reviewcompleted_reviewreview_obj);//更新fact中变量值
                        update(reviewcompleted_reviewsrfactionparam);//更新fact中变量值
                        update(reviewcompleted_reviewtmp_obj);//更新fact中变量值
            end

            //逻辑处理节点[通过]
            rule "prepareparam4"
            ruleflow-group "reviewcompleted_reviewprepareparam4"
            when
            then
                            reviewcompleted_reviewresult_obj.set("resultstate","3");
                        update(reviewcompleted_reviewdefault);//更新fact中变量值
                        update(reviewcompleted_reviewcase_number);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_fliter);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_list);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_obj);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_page);//更新fact中变量值
                        update(reviewcompleted_reviewresult);//更新fact中变量值
                        update(reviewcompleted_reviewresult_list);//更新fact中变量值
                        update(reviewcompleted_reviewresult_obj);//更新fact中变量值
                        update(reviewcompleted_reviewreview_obj);//更新fact中变量值
                        update(reviewcompleted_reviewsrfactionparam);//更新fact中变量值
                        update(reviewcompleted_reviewtmp_obj);//更新fact中变量值
            end

            //逻辑处理节点[拒绝]
            rule "prepareparam5"
            ruleflow-group "reviewcompleted_reviewprepareparam5"
            when
            then
                            reviewcompleted_reviewresult_obj.set("resultstate","4");
                        update(reviewcompleted_reviewdefault);//更新fact中变量值
                        update(reviewcompleted_reviewcase_number);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_fliter);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_list);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_obj);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_page);//更新fact中变量值
                        update(reviewcompleted_reviewresult);//更新fact中变量值
                        update(reviewcompleted_reviewresult_list);//更新fact中变量值
                        update(reviewcompleted_reviewresult_obj);//更新fact中变量值
                        update(reviewcompleted_reviewreview_obj);//更新fact中变量值
                        update(reviewcompleted_reviewsrfactionparam);//更新fact中变量值
                        update(reviewcompleted_reviewtmp_obj);//更新fact中变量值
            end

            //逻辑处理节点[更新]
            rule "deaction1"
            ruleflow-group "reviewcompleted_reviewdeaction1"
            when
            then
                        review_resultservice.update(reviewcompleted_reviewresult_obj);
                        update(reviewcompleted_reviewdefault);//更新fact中变量值
                        update(reviewcompleted_reviewcase_number);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_fliter);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_list);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_obj);//更新fact中变量值
                        update(reviewcompleted_reviewcontent_page);//更新fact中变量值
                        update(reviewcompleted_reviewresult);//更新fact中变量值
                        update(reviewcompleted_reviewresult_list);//更新fact中变量值
                        update(reviewcompleted_reviewresult_obj);//更新fact中变量值
                        update(reviewcompleted_reviewreview_obj);//更新fact中变量值
                        update(reviewcompleted_reviewsrfactionparam);//更新fact中变量值
                        update(reviewcompleted_reviewtmp_obj);//更新fact中变量值
            end