package cn.ibizlab.plm.testmgmt.logic.reviewlogic.fill_guideline;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.review reviewfill_guidelinedefault;
                global cn.ibizlab.plm.core.testmgmt.domain.guideline reviewfill_guidelineguideline_detail;
                global cn.ibizlab.plm.core.testmgmt.domain.guideline reviewfill_guidelineguideline_filter;
                global cn.ibizlab.plm.core.testmgmt.domain.guideline reviewfill_guidelineguideline_page;
                    global cn.ibizlab.plm.core.testmgmt.service.IguidelineService guidelineservice;
        global cn.ibizlab.plm.core.testmgmt.service.IreviewService iBzSysReviewDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "reviewfill_guidelinebegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "reviewfill_guidelineend1"
            when
            then
                        update(reviewfill_guidelinedefault);//更新fact中变量值
                        update(reviewfill_guidelineguideline_detail);//更新fact中变量值
                        update(reviewfill_guidelineguideline_filter);//更新fact中变量值
                        update(reviewfill_guidelineguideline_page);//更新fact中变量值
            end

            //逻辑处理节点[设置过滤参数]
            rule "prepareparam1"
            ruleflow-group "reviewfill_guidelineprepareparam1"
            when
            then
                            reviewfill_guidelineguideline_filter.set("n_subject_type_eq",reviewfill_guidelinedefault.get("type"));
                            reviewfill_guidelineguideline_filter.set("n_object_type_eq","LIBRARY");
                            reviewfill_guidelineguideline_filter.set("n_scope_id_eq",reviewfill_guidelinedefault.get("libraryid"));
                        update(reviewfill_guidelinedefault);//更新fact中变量值
                        update(reviewfill_guidelineguideline_detail);//更新fact中变量值
                        update(reviewfill_guidelineguideline_filter);//更新fact中变量值
                        update(reviewfill_guidelineguideline_page);//更新fact中变量值
            end

            //逻辑处理节点[查询当前测试库指定类型的规则]
            rule "dedataset1"
            ruleflow-group "reviewfill_guidelinededataset1"
            when
            then
                        update(reviewfill_guidelinedefault);//更新fact中变量值
                        update(reviewfill_guidelineguideline_detail);//更新fact中变量值
                        update(reviewfill_guidelineguideline_filter);//更新fact中变量值
                        update(reviewfill_guidelineguideline_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "reviewfill_guidelineloopsubcall1"
            when
            then
                        update(reviewfill_guidelinedefault);//更新fact中变量值
                        update(reviewfill_guidelineguideline_detail);//更新fact中变量值
                        update(reviewfill_guidelineguideline_filter);//更新fact中变量值
                        update(reviewfill_guidelineguideline_page);//更新fact中变量值
            end

            //逻辑处理节点[设置返回的guideline_id]
            rule "prepareparam2"
            ruleflow-group "reviewfill_guidelineprepareparam2"
            when
            then
                            reviewfill_guidelineguideline_detail.set("guideline_id",reviewfill_guidelineguideline_detail.get("id"));
                        update(reviewfill_guidelinedefault);//更新fact中变量值
                        update(reviewfill_guidelineguideline_detail);//更新fact中变量值
                        update(reviewfill_guidelineguideline_filter);//更新fact中变量值
                        update(reviewfill_guidelineguideline_page);//更新fact中变量值
            end