package cn.ibizlab.plm.testmgmt.logic.reviewlogic.get_redirect_data;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.review reviewget_redirect_datadefault;
                    global cn.ibizlab.plm.core.testmgmt.service.IreviewService reviewservice;
        global cn.ibizlab.plm.core.testmgmt.service.IreviewService iBzSysReviewDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "reviewget_redirect_databegin"
            when
            then
            end

            //逻辑处理节点[获取需求数据]
            rule "deaction1"
            ruleflow-group "reviewget_redirect_datadeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(reviewservice.get(reviewget_redirect_datadefault.getId()),reviewget_redirect_datadefault);
                        update(reviewget_redirect_datadefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "reviewget_redirect_dataend1"
            when
            then
                        update(reviewget_redirect_datadefault);//更新fact中变量值
            end