package cn.ibizlab.plm.testmgmt.logic.test_caselogic.check_refresh_data;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case test_casecheck_refresh_datadefault;
                global java.util.Map test_casecheck_refresh_datactx;
        global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService iBzSysTest_caseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_casecheck_refresh_databegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_casecheck_refresh_dataend1"
            when
            then
                        update(test_casecheck_refresh_datadefault);//更新fact中变量值
                        update(test_casecheck_refresh_datactx);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "test_casecheck_refresh_datadebugparam1"
            when
            then
                        update(test_casecheck_refresh_datadefault);//更新fact中变量值
                        update(test_casecheck_refresh_datactx);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数ctx]
            rule "debugparam3"
            ruleflow-group "test_casecheck_refresh_datadebugparam3"
            when
            then
                        update(test_casecheck_refresh_datadefault);//更新fact中变量值
                        update(test_casecheck_refresh_datactx);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "test_casecheck_refresh_dataprepareparam1"
            when
            then
                        update(test_casecheck_refresh_datadefault);//更新fact中变量值
                        update(test_casecheck_refresh_datactx);//更新fact中变量值
            end