package cn.ibizlab.plm.testmgmt.logic.test_caselogic.common;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case test_casecommondefault;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case test_casecommonpage;
                    global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService test_caseservice;
        global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService iBzSysTest_caseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_casecommonbegin"
            when
            then
            end

            //逻辑处理节点[获取测试用例]
            rule "dedataset1"
            ruleflow-group "test_casecommondedataset1"
            when
            then
                        update(test_casecommondefault);//更新fact中变量值
                        update(test_casecommonpage);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_casecommonend1"
            when
            then
                        update(test_casecommondefault);//更新fact中变量值
                        update(test_casecommonpage);//更新fact中变量值
            end

            //逻辑处理节点[设置过滤参数]
            rule "prepareparam2"
            ruleflow-group "test_casecommonprepareparam2"
            when
            then
                            test_casecommondefault.set("n_id_in",test_casecommondefault.get("srfkeys"));
                        update(test_casecommondefault);//更新fact中变量值
                        update(test_casecommonpage);//更新fact中变量值
            end