package cn.ibizlab.plm.testmgmt.logic.test_caselogic.common;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case test_casecommondefault;
                global java.util.Map test_casecommonfilter;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case test_casecommonpage;
                    global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService test_caseservice;
        global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService iBzSysTest_caseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_casecommonbegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "test_casecommondebugparam1"
            when
            then
                        update(test_casecommondefault);//更新fact中变量值
                        update(test_casecommonfilter);//更新fact中变量值
                        update(test_casecommonpage);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode1"
            ruleflow-group "test_casecommonrawsfcode1"
            when
            then
                        update(test_casecommondefault);//更新fact中变量值
                        update(test_casecommonfilter);//更新fact中变量值
                        update(test_casecommonpage);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam2"
            ruleflow-group "test_casecommondebugparam2"
            when
            then
                        update(test_casecommondefault);//更新fact中变量值
                        update(test_casecommonfilter);//更新fact中变量值
                        update(test_casecommonpage);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "test_casecommondedataset1"
            when
            then
                        update(test_casecommondefault);//更新fact中变量值
                        update(test_casecommonfilter);//更新fact中变量值
                        update(test_casecommonpage);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_casecommonend1"
            when
            then
                        update(test_casecommondefault);//更新fact中变量值
                        update(test_casecommonfilter);//更新fact中变量值
                        update(test_casecommonpage);//更新fact中变量值
            end