package cn.ibizlab.plm.testmgmt.logic.test_caselogic.finish_add_attention;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case test_casefinish_add_attentiondefault;
                global cn.ibizlab.plm.core.base.domain.attention test_casefinish_add_attentionattention;
                global cn.ibizlab.plm.core.testmgmt.domain.library_member test_casefinish_add_attentionfor_obj;
                global cn.ibizlab.plm.core.testmgmt.domain.library_member test_casefinish_add_attentionsrfactionparam;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case test_casefinish_add_attentiontest_case;
                    global cn.ibizlab.plm.core.base.service.IattentionService attentionservice;
        global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService iBzSysTest_caseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_casefinish_add_attentionbegin"
            when
            then
            end

            //逻辑处理节点[获取列表]
            rule "bindparam1"
            ruleflow-group "test_casefinish_add_attentionbindparam1"
            when
            then
                        update(test_casefinish_add_attentiondefault);//更新fact中变量值
                        update(test_casefinish_add_attentionattention);//更新fact中变量值
                        update(test_casefinish_add_attentionfor_obj);//更新fact中变量值
                        update(test_casefinish_add_attentionsrfactionparam);//更新fact中变量值
                        update(test_casefinish_add_attentiontest_case);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "test_casefinish_add_attentionloopsubcall1"
            when
            then
                        update(test_casefinish_add_attentiondefault);//更新fact中变量值
                        update(test_casefinish_add_attentionattention);//更新fact中变量值
                        update(test_casefinish_add_attentionfor_obj);//更新fact中变量值
                        update(test_casefinish_add_attentionsrfactionparam);//更新fact中变量值
                        update(test_casefinish_add_attentiontest_case);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_casefinish_add_attentionend1"
            when
            then
                        update(test_casefinish_add_attentiondefault);//更新fact中变量值
                        update(test_casefinish_add_attentionattention);//更新fact中变量值
                        update(test_casefinish_add_attentionfor_obj);//更新fact中变量值
                        update(test_casefinish_add_attentionsrfactionparam);//更新fact中变量值
                        update(test_casefinish_add_attentiontest_case);//更新fact中变量值
            end

            //逻辑处理节点[设置参数]
            rule "prepareparam1"
            ruleflow-group "test_casefinish_add_attentionprepareparam1"
            when
            then
                            test_casefinish_add_attentionattention.set("ownerid",test_casefinish_add_attentiondefault.get("id"));
                            test_casefinish_add_attentionattention.set("ownersubtype","TEST_CASE");
                            test_casefinish_add_attentionattention.set("ownertype","TEST_CASE");
                            test_casefinish_add_attentionattention.set("type","40");
                            test_casefinish_add_attentionattention.set("userid",test_casefinish_add_attentionfor_obj.get("userid"));
                            test_casefinish_add_attentionattention.set("name",test_casefinish_add_attentionfor_obj.get("name"));
                        update(test_casefinish_add_attentiondefault);//更新fact中变量值
                        update(test_casefinish_add_attentionattention);//更新fact中变量值
                        update(test_casefinish_add_attentionfor_obj);//更新fact中变量值
                        update(test_casefinish_add_attentionsrfactionparam);//更新fact中变量值
                        update(test_casefinish_add_attentiontest_case);//更新fact中变量值
            end

            //逻辑处理节点[创建关注人]
            rule "deaction1"
            ruleflow-group "test_casefinish_add_attentiondeaction1"
            when
            then
                        attentionservice.save(test_casefinish_add_attentionattention);
                        update(test_casefinish_add_attentiondefault);//更新fact中变量值
                        update(test_casefinish_add_attentionattention);//更新fact中变量值
                        update(test_casefinish_add_attentionfor_obj);//更新fact中变量值
                        update(test_casefinish_add_attentionsrfactionparam);//更新fact中变量值
                        update(test_casefinish_add_attentiontest_case);//更新fact中变量值
            end