package cn.ibizlab.plm.testmgmt.logic.review_wizardlogic.add_guideline_after_created;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.review_wizard review_wizardadd_guideline_after_createddefault;
                global cn.ibizlab.plm.core.testmgmt.domain.guideline review_wizardadd_guideline_after_createdguideline_detail;
                    global cn.ibizlab.plm.core.testmgmt.service.IguidelineService guidelineservice;
                    global cn.ibizlab.plm.core.testmgmt.service.Ireview_wizardService review_wizardservice;
        global cn.ibizlab.plm.core.testmgmt.service.Ireview_wizardService iBzSysReview_wizardDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "review_wizardadd_guideline_after_createdbegin"
            when
            then
            end

            //逻辑处理节点[获取流程准则id]
            rule "prepareparam3"
            ruleflow-group "review_wizardadd_guideline_after_createdprepareparam3"
            when
            then
                            review_wizardadd_guideline_after_createdguideline_detail.set("id",review_wizardadd_guideline_after_createddefault.get("guidelineid"));
                        update(review_wizardadd_guideline_after_createddefault);//更新fact中变量值
                        update(review_wizardadd_guideline_after_createdguideline_detail);//更新fact中变量值
            end

            //逻辑处理节点[查询流程准则]
            rule "deaction1"
            ruleflow-group "review_wizardadd_guideline_after_createddeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(guidelineservice.get(review_wizardadd_guideline_after_createdguideline_detail.getId()),review_wizardadd_guideline_after_createdguideline_detail);
                        update(review_wizardadd_guideline_after_createddefault);//更新fact中变量值
                        update(review_wizardadd_guideline_after_createdguideline_detail);//更新fact中变量值
            end

            //逻辑处理节点[获取步骤及类型]
            rule "prepareparam2"
            ruleflow-group "review_wizardadd_guideline_after_createdprepareparam2"
            when
            then
                            review_wizardadd_guideline_after_createddefault.set("stage",review_wizardadd_guideline_after_createdguideline_detail.get("reviewstage"));
                            review_wizardadd_guideline_after_createddefault.set("type",review_wizardadd_guideline_after_createdguideline_detail.get("subjecttype"));
                        update(review_wizardadd_guideline_after_createddefault);//更新fact中变量值
                        update(review_wizardadd_guideline_after_createdguideline_detail);//更新fact中变量值
            end

            //逻辑处理节点[保存评审]
            rule "deaction2"
            ruleflow-group "review_wizardadd_guideline_after_createddeaction2"
            when
            then
                        review_wizardservice.save(review_wizardadd_guideline_after_createddefault);
                        update(review_wizardadd_guideline_after_createddefault);//更新fact中变量值
                        update(review_wizardadd_guideline_after_createdguideline_detail);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "review_wizardadd_guideline_after_createdend1"
            when
            then
                        update(review_wizardadd_guideline_after_createddefault);//更新fact中变量值
                        update(review_wizardadd_guideline_after_createdguideline_detail);//更新fact中变量值
            end