package cn.ibizlab.plm.testmgmt.logic.run_historylogic.run_history_get;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Run_history run_historyrun_history_getdefault;
                global cn.ibizlab.plm.core.testmgmt.domain.Run_history run_historyrun_history_getrun_history_list;
                global cn.ibizlab.plm.core.testmgmt.domain.Run run_historyrun_history_getrun_info;
        global cn.ibizlab.plm.core.testmgmt.service.IRun_historyService iBzSysRun_historyDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "run_historyrun_history_getbegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "run_historyrun_history_getdebugparam1"
            when
            then
                        update(run_historyrun_history_getdefault);//更新fact中变量值
                        update(run_historyrun_history_getrun_history_list);//更新fact中变量值
                        update(run_historyrun_history_getrun_info);//更新fact中变量值
            end

            //逻辑处理节点[直接sql调用]
            rule "rawsqlcall1"
            ruleflow-group "run_historyrun_history_getrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",run_historyrun_history_getdefault.get("runid"));
    String strSql="SELECT * FROM run_history t1 WHERE t1.RUN_ID = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysRun_historyDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    run_historyrun_history_getrun_history_list.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(run_historyrun_history_getdefault);//更新fact中变量值
                        update(run_historyrun_history_getrun_history_list);//更新fact中变量值
                        update(run_historyrun_history_getrun_info);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "run_historyrun_history_getend1"
            when
            then
                        update(run_historyrun_history_getdefault);//更新fact中变量值
                        update(run_historyrun_history_getrun_history_list);//更新fact中变量值
                        update(run_historyrun_history_getrun_info);//更新fact中变量值
            end