package cn.ibizlab.plm.projmgmt.logic.project_taglogic.get_con_ticket;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.project_tag project_tagget_con_ticketdefault;
        global cn.ibizlab.plm.core.projmgmt.service.Iproject_tagService iBzSysProject_tagDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "project_tagget_con_ticketbegin"
            when
            then
            end

            //逻辑处理节点[查询所关联的工单数量]
            rule "rawsqlcall1"
            ruleflow-group "project_tagget_con_ticketrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",project_tagget_con_ticketdefault.get("id"));
    String strSql="select count(1) as ticket_num from ticket  where  type = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysProject_tagDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    project_tagget_con_ticketdefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(project_tagget_con_ticketdefault);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "project_tagget_con_ticketprepareparam1"
            when
            then
                            project_tagget_con_ticketdefault.set("remind","工单类型删除后不可恢复，后续不可再新建此类型的工单。");
                            project_tagget_con_ticketdefault.set("disabled","0");
                        update(project_tagget_con_ticketdefault);//更新fact中变量值
            end

            //逻辑处理节点[添加工单数量提醒内容]
            rule "rawsfcode1"
            ruleflow-group "project_tagget_con_ticketrawsfcode1"
            when
            then
                        update(project_tagget_con_ticketdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "project_tagget_con_ticketend1"
            when
            then
                        update(project_tagget_con_ticketdefault);//更新fact中变量值
            end