package cn.ibizlab.plm.base.logic.search_attachmentlogic.advanced_search;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.search_attachment search_attachmentadvanced_searchdefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.customer search_attachmentadvanced_searchcustomer;
                global cn.ibizlab.plm.core.base.domain.search_attachment search_attachmentadvanced_searchfor_temp_obj;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea search_attachmentadvanced_searchidea;
                global cn.ibizlab.plm.core.wiki.domain.article_page search_attachmentadvanced_searchpage;
                global cn.ibizlab.plm.core.base.domain.search_attachment search_attachmentadvanced_searchresult_page;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case search_attachmentadvanced_searchtest_case;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket search_attachmentadvanced_searchticket;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item search_attachmentadvanced_searchwork_item;
                    global cn.ibizlab.plm.core.base.service.Isearch_attachmentService search_attachmentservice;
        global cn.ibizlab.plm.core.base.service.Isearch_attachmentService iBzSysSearch_attachmentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "search_attachmentadvanced_searchbegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "search_attachmentadvanced_searchbindparam1"
            when
            then
                        update(search_attachmentadvanced_searchdefault);//更新fact中变量值
                        update(search_attachmentadvanced_searchcustomer);//更新fact中变量值
                        update(search_attachmentadvanced_searchfor_temp_obj);//更新fact中变量值
                        update(search_attachmentadvanced_searchidea);//更新fact中变量值
                        update(search_attachmentadvanced_searchpage);//更新fact中变量值
                        update(search_attachmentadvanced_searchresult_page);//更新fact中变量值
                        update(search_attachmentadvanced_searchtest_case);//更新fact中变量值
                        update(search_attachmentadvanced_searchticket);//更新fact中变量值
                        update(search_attachmentadvanced_searchwork_item);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "search_attachmentadvanced_searchprepareparam1"
            when
            then
                            search_attachmentadvanced_searchfor_temp_obj.set("owneridentifier",search_attachmentadvanced_searchwork_item.get("showidentifier"));
                            search_attachmentadvanced_searchfor_temp_obj.set("ownerparentid",search_attachmentadvanced_searchwork_item.get("projectid"));
                            search_attachmentadvanced_searchfor_temp_obj.set("ownerparentname",search_attachmentadvanced_searchwork_item.get("projectname"));
                            search_attachmentadvanced_searchfor_temp_obj.set("ownertitle",search_attachmentadvanced_searchwork_item.get("title"));
                        update(search_attachmentadvanced_searchdefault);//更新fact中变量值
                        update(search_attachmentadvanced_searchcustomer);//更新fact中变量值
                        update(search_attachmentadvanced_searchfor_temp_obj);//更新fact中变量值
                        update(search_attachmentadvanced_searchidea);//更新fact中变量值
                        update(search_attachmentadvanced_searchpage);//更新fact中变量值
                        update(search_attachmentadvanced_searchresult_page);//更新fact中变量值
                        update(search_attachmentadvanced_searchtest_case);//更新fact中变量值
                        update(search_attachmentadvanced_searchticket);//更新fact中变量值
                        update(search_attachmentadvanced_searchwork_item);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "search_attachmentadvanced_searchdebugparam1"
            when
            then
                        update(search_attachmentadvanced_searchdefault);//更新fact中变量值
                        update(search_attachmentadvanced_searchcustomer);//更新fact中变量值
                        update(search_attachmentadvanced_searchfor_temp_obj);//更新fact中变量值
                        update(search_attachmentadvanced_searchidea);//更新fact中变量值
                        update(search_attachmentadvanced_searchpage);//更新fact中变量值
                        update(search_attachmentadvanced_searchresult_page);//更新fact中变量值
                        update(search_attachmentadvanced_searchtest_case);//更新fact中变量值
                        update(search_attachmentadvanced_searchticket);//更新fact中变量值
                        update(search_attachmentadvanced_searchwork_item);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam2"
            ruleflow-group "search_attachmentadvanced_searchbindparam2"
            when
            then
                        update(search_attachmentadvanced_searchdefault);//更新fact中变量值
                        update(search_attachmentadvanced_searchcustomer);//更新fact中变量值
                        update(search_attachmentadvanced_searchfor_temp_obj);//更新fact中变量值
                        update(search_attachmentadvanced_searchidea);//更新fact中变量值
                        update(search_attachmentadvanced_searchpage);//更新fact中变量值
                        update(search_attachmentadvanced_searchresult_page);//更新fact中变量值
                        update(search_attachmentadvanced_searchtest_case);//更新fact中变量值
                        update(search_attachmentadvanced_searchticket);//更新fact中变量值
                        update(search_attachmentadvanced_searchwork_item);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "search_attachmentadvanced_searchprepareparam2"
            when
            then
                            search_attachmentadvanced_searchfor_temp_obj.set("owneridentifier",search_attachmentadvanced_searchidea.get("showidentifier"));
                            search_attachmentadvanced_searchfor_temp_obj.set("ownerparentid",search_attachmentadvanced_searchidea.get("productid"));
                            search_attachmentadvanced_searchfor_temp_obj.set("ownerparentname",search_attachmentadvanced_searchidea.get("productname"));
                            search_attachmentadvanced_searchfor_temp_obj.set("ownertitle",search_attachmentadvanced_searchidea.get("title"));
                        update(search_attachmentadvanced_searchdefault);//更新fact中变量值
                        update(search_attachmentadvanced_searchcustomer);//更新fact中变量值
                        update(search_attachmentadvanced_searchfor_temp_obj);//更新fact中变量值
                        update(search_attachmentadvanced_searchidea);//更新fact中变量值
                        update(search_attachmentadvanced_searchpage);//更新fact中变量值
                        update(search_attachmentadvanced_searchresult_page);//更新fact中变量值
                        update(search_attachmentadvanced_searchtest_case);//更新fact中变量值
                        update(search_attachmentadvanced_searchticket);//更新fact中变量值
                        update(search_attachmentadvanced_searchwork_item);//更新fact中变量值
            end

            //逻辑处理节点[关联查询]
            rule "dedataset1"
            ruleflow-group "search_attachmentadvanced_searchdedataset1"
            when
            then
                        update(search_attachmentadvanced_searchdefault);//更新fact中变量值
                        update(search_attachmentadvanced_searchcustomer);//更新fact中变量值
                        update(search_attachmentadvanced_searchfor_temp_obj);//更新fact中变量值
                        update(search_attachmentadvanced_searchidea);//更新fact中变量值
                        update(search_attachmentadvanced_searchpage);//更新fact中变量值
                        update(search_attachmentadvanced_searchresult_page);//更新fact中变量值
                        update(search_attachmentadvanced_searchtest_case);//更新fact中变量值
                        update(search_attachmentadvanced_searchticket);//更新fact中变量值
                        update(search_attachmentadvanced_searchwork_item);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "search_attachmentadvanced_searchloopsubcall1"
            when
            then
                        update(search_attachmentadvanced_searchdefault);//更新fact中变量值
                        update(search_attachmentadvanced_searchcustomer);//更新fact中变量值
                        update(search_attachmentadvanced_searchfor_temp_obj);//更新fact中变量值
                        update(search_attachmentadvanced_searchidea);//更新fact中变量值
                        update(search_attachmentadvanced_searchpage);//更新fact中变量值
                        update(search_attachmentadvanced_searchresult_page);//更新fact中变量值
                        update(search_attachmentadvanced_searchtest_case);//更新fact中变量值
                        update(search_attachmentadvanced_searchticket);//更新fact中变量值
                        update(search_attachmentadvanced_searchwork_item);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam3"
            ruleflow-group "search_attachmentadvanced_searchbindparam3"
            when
            then
                        update(search_attachmentadvanced_searchdefault);//更新fact中变量值
                        update(search_attachmentadvanced_searchcustomer);//更新fact中变量值
                        update(search_attachmentadvanced_searchfor_temp_obj);//更新fact中变量值
                        update(search_attachmentadvanced_searchidea);//更新fact中变量值
                        update(search_attachmentadvanced_searchpage);//更新fact中变量值
                        update(search_attachmentadvanced_searchresult_page);//更新fact中变量值
                        update(search_attachmentadvanced_searchtest_case);//更新fact中变量值
                        update(search_attachmentadvanced_searchticket);//更新fact中变量值
                        update(search_attachmentadvanced_searchwork_item);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam3"
            ruleflow-group "search_attachmentadvanced_searchprepareparam3"
            when
            then
                            search_attachmentadvanced_searchfor_temp_obj.set("ownertitle",search_attachmentadvanced_searchticket.get("title"));
                            search_attachmentadvanced_searchfor_temp_obj.set("ownerparentid",search_attachmentadvanced_searchticket.get("productid"));
                            search_attachmentadvanced_searchfor_temp_obj.set("ownerparentname",search_attachmentadvanced_searchticket.get("productname"));
                            search_attachmentadvanced_searchfor_temp_obj.set("owneridentifier",search_attachmentadvanced_searchticket.get("showidentifier"));
                        update(search_attachmentadvanced_searchdefault);//更新fact中变量值
                        update(search_attachmentadvanced_searchcustomer);//更新fact中变量值
                        update(search_attachmentadvanced_searchfor_temp_obj);//更新fact中变量值
                        update(search_attachmentadvanced_searchidea);//更新fact中变量值
                        update(search_attachmentadvanced_searchpage);//更新fact中变量值
                        update(search_attachmentadvanced_searchresult_page);//更新fact中变量值
                        update(search_attachmentadvanced_searchtest_case);//更新fact中变量值
                        update(search_attachmentadvanced_searchticket);//更新fact中变量值
                        update(search_attachmentadvanced_searchwork_item);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam4"
            ruleflow-group "search_attachmentadvanced_searchbindparam4"
            when
            then
                        update(search_attachmentadvanced_searchdefault);//更新fact中变量值
                        update(search_attachmentadvanced_searchcustomer);//更新fact中变量值
                        update(search_attachmentadvanced_searchfor_temp_obj);//更新fact中变量值
                        update(search_attachmentadvanced_searchidea);//更新fact中变量值
                        update(search_attachmentadvanced_searchpage);//更新fact中变量值
                        update(search_attachmentadvanced_searchresult_page);//更新fact中变量值
                        update(search_attachmentadvanced_searchtest_case);//更新fact中变量值
                        update(search_attachmentadvanced_searchticket);//更新fact中变量值
                        update(search_attachmentadvanced_searchwork_item);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam4"
            ruleflow-group "search_attachmentadvanced_searchprepareparam4"
            when
            then
                            search_attachmentadvanced_searchfor_temp_obj.set("ownertitle",search_attachmentadvanced_searchcustomer.get("name"));
                            search_attachmentadvanced_searchfor_temp_obj.set("ownerparentid",search_attachmentadvanced_searchcustomer.get("productid"));
                            search_attachmentadvanced_searchfor_temp_obj.set("ownerparentname",search_attachmentadvanced_searchcustomer.get("productname"));
                        update(search_attachmentadvanced_searchdefault);//更新fact中变量值
                        update(search_attachmentadvanced_searchcustomer);//更新fact中变量值
                        update(search_attachmentadvanced_searchfor_temp_obj);//更新fact中变量值
                        update(search_attachmentadvanced_searchidea);//更新fact中变量值
                        update(search_attachmentadvanced_searchpage);//更新fact中变量值
                        update(search_attachmentadvanced_searchresult_page);//更新fact中变量值
                        update(search_attachmentadvanced_searchtest_case);//更新fact中变量值
                        update(search_attachmentadvanced_searchticket);//更新fact中变量值
                        update(search_attachmentadvanced_searchwork_item);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam5"
            ruleflow-group "search_attachmentadvanced_searchbindparam5"
            when
            then
                        update(search_attachmentadvanced_searchdefault);//更新fact中变量值
                        update(search_attachmentadvanced_searchcustomer);//更新fact中变量值
                        update(search_attachmentadvanced_searchfor_temp_obj);//更新fact中变量值
                        update(search_attachmentadvanced_searchidea);//更新fact中变量值
                        update(search_attachmentadvanced_searchpage);//更新fact中变量值
                        update(search_attachmentadvanced_searchresult_page);//更新fact中变量值
                        update(search_attachmentadvanced_searchtest_case);//更新fact中变量值
                        update(search_attachmentadvanced_searchticket);//更新fact中变量值
                        update(search_attachmentadvanced_searchwork_item);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam5"
            ruleflow-group "search_attachmentadvanced_searchprepareparam5"
            when
            then
                            search_attachmentadvanced_searchfor_temp_obj.set("owneridentifier",search_attachmentadvanced_searchtest_case.get("showidentifier"));
                            search_attachmentadvanced_searchfor_temp_obj.set("ownerparentid",search_attachmentadvanced_searchtest_case.get("testlibraryid"));
                            search_attachmentadvanced_searchfor_temp_obj.set("ownertitle",search_attachmentadvanced_searchtest_case.get("title"));
                            search_attachmentadvanced_searchfor_temp_obj.set("ownerparentname",search_attachmentadvanced_searchtest_case.get("testlibraryname"));
                        update(search_attachmentadvanced_searchdefault);//更新fact中变量值
                        update(search_attachmentadvanced_searchcustomer);//更新fact中变量值
                        update(search_attachmentadvanced_searchfor_temp_obj);//更新fact中变量值
                        update(search_attachmentadvanced_searchidea);//更新fact中变量值
                        update(search_attachmentadvanced_searchpage);//更新fact中变量值
                        update(search_attachmentadvanced_searchresult_page);//更新fact中变量值
                        update(search_attachmentadvanced_searchtest_case);//更新fact中变量值
                        update(search_attachmentadvanced_searchticket);//更新fact中变量值
                        update(search_attachmentadvanced_searchwork_item);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "search_attachmentadvanced_searchend1"
            when
            then
                        update(search_attachmentadvanced_searchdefault);//更新fact中变量值
                        update(search_attachmentadvanced_searchcustomer);//更新fact中变量值
                        update(search_attachmentadvanced_searchfor_temp_obj);//更新fact中变量值
                        update(search_attachmentadvanced_searchidea);//更新fact中变量值
                        update(search_attachmentadvanced_searchpage);//更新fact中变量值
                        update(search_attachmentadvanced_searchresult_page);//更新fact中变量值
                        update(search_attachmentadvanced_searchtest_case);//更新fact中变量值
                        update(search_attachmentadvanced_searchticket);//更新fact中变量值
                        update(search_attachmentadvanced_searchwork_item);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam6"
            ruleflow-group "search_attachmentadvanced_searchbindparam6"
            when
            then
                        update(search_attachmentadvanced_searchdefault);//更新fact中变量值
                        update(search_attachmentadvanced_searchcustomer);//更新fact中变量值
                        update(search_attachmentadvanced_searchfor_temp_obj);//更新fact中变量值
                        update(search_attachmentadvanced_searchidea);//更新fact中变量值
                        update(search_attachmentadvanced_searchpage);//更新fact中变量值
                        update(search_attachmentadvanced_searchresult_page);//更新fact中变量值
                        update(search_attachmentadvanced_searchtest_case);//更新fact中变量值
                        update(search_attachmentadvanced_searchticket);//更新fact中变量值
                        update(search_attachmentadvanced_searchwork_item);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam6"
            ruleflow-group "search_attachmentadvanced_searchprepareparam6"
            when
            then
                            search_attachmentadvanced_searchfor_temp_obj.set("ownertitle",search_attachmentadvanced_searchpage.get("name"));
                            search_attachmentadvanced_searchfor_temp_obj.set("ownerparentid",search_attachmentadvanced_searchpage.get("spaceid"));
                            search_attachmentadvanced_searchfor_temp_obj.set("ownerparentname",search_attachmentadvanced_searchpage.get("spacename"));
                            search_attachmentadvanced_searchfor_temp_obj.set("owneridentifier",search_attachmentadvanced_searchpage.get("showidentifier"));
                        update(search_attachmentadvanced_searchdefault);//更新fact中变量值
                        update(search_attachmentadvanced_searchcustomer);//更新fact中变量值
                        update(search_attachmentadvanced_searchfor_temp_obj);//更新fact中变量值
                        update(search_attachmentadvanced_searchidea);//更新fact中变量值
                        update(search_attachmentadvanced_searchpage);//更新fact中变量值
                        update(search_attachmentadvanced_searchresult_page);//更新fact中变量值
                        update(search_attachmentadvanced_searchtest_case);//更新fact中变量值
                        update(search_attachmentadvanced_searchticket);//更新fact中变量值
                        update(search_attachmentadvanced_searchwork_item);//更新fact中变量值
            end