package cn.ibizlab.plm.team.logic.discuss_replylogic.add_reply;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_reply discuss_replyadd_replydefault;
                global cn.ibizlab.plm.core.team.domain.discuss_reply discuss_replyadd_replycreate_obj;
                    global cn.ibizlab.plm.core.team.service.Idiscuss_replyService discuss_replyservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_replyService iBzSysDiscuss_replyDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_replyadd_replybegin"
            when
            then
            end

            //逻辑处理节点[填充回复内容]
            rule "prepareparam1"
            ruleflow-group "discuss_replyadd_replyprepareparam1"
            when
            then
                            discuss_replyadd_replycreate_obj.set("content",discuss_replyadd_replydefault.get("content"));
                            discuss_replyadd_replycreate_obj.set("postid",discuss_replyadd_replydefault.get("postid"));
                        update(discuss_replyadd_replydefault);//更新fact中变量值
                        update(discuss_replyadd_replycreate_obj);//更新fact中变量值
            end

            //逻辑处理节点[添加回复]
            rule "deaction1"
            ruleflow-group "discuss_replyadd_replydeaction1"
            when
            then
                        discuss_replyservice.create(discuss_replyadd_replycreate_obj);
                        update(discuss_replyadd_replydefault);//更新fact中变量值
                        update(discuss_replyadd_replycreate_obj);//更新fact中变量值
            end

            //逻辑处理节点[讨论热度+5]
            rule "rawsqlcall1"
            ruleflow-group "discuss_replyadd_replyrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",discuss_replyadd_replydefault.get("postid"));
    String strSql="update discuss_post t1 set t1.heat = t1.heat + 5  where t1.id = #{et.param0}";
                        iBzSysDiscuss_replyDefaultService.execute(strSql,param);//SQL调用
                        update(discuss_replyadd_replydefault);//更新fact中变量值
                        update(discuss_replyadd_replycreate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_replyadd_replyend1"
            when
            then
                        update(discuss_replyadd_replydefault);//更新fact中变量值
                        update(discuss_replyadd_replycreate_obj);//更新fact中变量值
            end