package cn.ibizlab.plm.team.logic.discuss_replylogic.del_comment;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_reply discuss_replydel_commentdefault;
                global cn.ibizlab.plm.core.base.domain.comment discuss_replydel_commentcomment;
                    global cn.ibizlab.plm.core.base.service.IcommentService commentservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_replyService iBzSysDiscuss_replyDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_replydel_commentbegin"
            when
            then
            end

            //逻辑处理节点[填充评论属性]
            rule "prepareparam1"
            ruleflow-group "discuss_replydel_commentprepareparam1"
            when
            then
                            discuss_replydel_commentcomment.set("id",discuss_replydel_commentdefault.get("id"));
                        update(discuss_replydel_commentdefault);//更新fact中变量值
                        update(discuss_replydel_commentcomment);//更新fact中变量值
            end

            //逻辑处理节点[删除评论]
            rule "deaction1"
            ruleflow-group "discuss_replydel_commentdeaction1"
            when
            then
                        commentservice.remove(discuss_replydel_commentcomment.getId());
                        update(discuss_replydel_commentdefault);//更新fact中变量值
                        update(discuss_replydel_commentcomment);//更新fact中变量值
            end

            //逻辑处理节点[讨论热度-2]
            rule "rawsqlcall1"
            ruleflow-group "discuss_replydel_commentrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",discuss_replydel_commentdefault.get("id"));
    String strSql="update discuss_post t1 set t1.heat = t1.heat - 2  where exists(select 1 from `comment` t2  where t2.principal_id = t1.id  and t2.principal_type = 'DISCUSS_REPLY' and t2.id = #{et.param0})";
                        iBzSysDiscuss_replyDefaultService.execute(strSql,param);//SQL调用
                        update(discuss_replydel_commentdefault);//更新fact中变量值
                        update(discuss_replydel_commentcomment);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_replydel_commentend1"
            when
            then
                        update(discuss_replydel_commentdefault);//更新fact中变量值
                        update(discuss_replydel_commentcomment);//更新fact中变量值
            end