package cn.ibizlab.plm.team.logic.discuss_replylogic.sub_reply_data;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_reply discuss_replysub_reply_datadefault;
                global cn.ibizlab.plm.core.team.domain.discuss_reply discuss_replysub_reply_datareply_dto;
                global cn.ibizlab.plm.core.team.domain.discuss_reply discuss_replysub_reply_dataresult;
                global cn.ibizlab.plm.core.team.domain.discuss_reply discuss_replysub_reply_datasubreply_filter;
                global cn.ibizlab.plm.core.team.domain.discuss_reply discuss_replysub_reply_datasubreply_page;
                    global cn.ibizlab.plm.core.team.service.Idiscuss_replyService discuss_replyservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_replyService iBzSysDiscuss_replyDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_replysub_reply_databegin"
            when
            then
            end

            //逻辑处理节点[获取回复数据]
            rule "dedataset1"
            ruleflow-group "discuss_replysub_reply_datadedataset1"
            when
            then
                        update(discuss_replysub_reply_datadefault);//更新fact中变量值
                        update(discuss_replysub_reply_datareply_dto);//更新fact中变量值
                        update(discuss_replysub_reply_dataresult);//更新fact中变量值
                        update(discuss_replysub_reply_datasubreply_filter);//更新fact中变量值
                        update(discuss_replysub_reply_datasubreply_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "discuss_replysub_reply_dataloopsubcall1"
            when
            then
                        update(discuss_replysub_reply_datadefault);//更新fact中变量值
                        update(discuss_replysub_reply_datareply_dto);//更新fact中变量值
                        update(discuss_replysub_reply_dataresult);//更新fact中变量值
                        update(discuss_replysub_reply_datasubreply_filter);//更新fact中变量值
                        update(discuss_replysub_reply_datasubreply_page);//更新fact中变量值
            end

            //逻辑处理节点[设置子回复过滤器]
            rule "prepareparam1"
            ruleflow-group "discuss_replysub_reply_dataprepareparam1"
            when
            then
                            discuss_replysub_reply_datasubreply_filter.set("n_pid_eq",discuss_replysub_reply_datareply_dto.get("id"));
                        update(discuss_replysub_reply_datadefault);//更新fact中变量值
                        update(discuss_replysub_reply_datareply_dto);//更新fact中变量值
                        update(discuss_replysub_reply_dataresult);//更新fact中变量值
                        update(discuss_replysub_reply_datasubreply_filter);//更新fact中变量值
                        update(discuss_replysub_reply_datasubreply_page);//更新fact中变量值
            end

            //逻辑处理节点[获取子回复数据]
            rule "dedataset2"
            ruleflow-group "discuss_replysub_reply_datadedataset2"
            when
            then
                        update(discuss_replysub_reply_datadefault);//更新fact中变量值
                        update(discuss_replysub_reply_datareply_dto);//更新fact中变量值
                        update(discuss_replysub_reply_dataresult);//更新fact中变量值
                        update(discuss_replysub_reply_datasubreply_filter);//更新fact中变量值
                        update(discuss_replysub_reply_datasubreply_page);//更新fact中变量值
            end

            //逻辑处理节点[设置数据]
            rule "rawsfcode1"
            ruleflow-group "discuss_replysub_reply_datarawsfcode1"
            when
            then
                        update(discuss_replysub_reply_datadefault);//更新fact中变量值
                        update(discuss_replysub_reply_datareply_dto);//更新fact中变量值
                        update(discuss_replysub_reply_dataresult);//更新fact中变量值
                        update(discuss_replysub_reply_datasubreply_filter);//更新fact中变量值
                        update(discuss_replysub_reply_datasubreply_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_replysub_reply_dataend1"
            when
            then
                        update(discuss_replysub_reply_datadefault);//更新fact中变量值
                        update(discuss_replysub_reply_datareply_dto);//更新fact中变量值
                        update(discuss_replysub_reply_dataresult);//更新fact中变量值
                        update(discuss_replysub_reply_datasubreply_filter);//更新fact中变量值
                        update(discuss_replysub_reply_datasubreply_page);//更新fact中变量值
            end