package cn.ibizlab.plm.team.logic.discuss_replylogic.update_post_time;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_reply discuss_replyupdate_post_timedefault;
                global cn.ibizlab.plm.core.team.domain.discuss_post discuss_replyupdate_post_timepost_obj;
                    global cn.ibizlab.plm.core.team.service.Idiscuss_postService discuss_postservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_replyService iBzSysDiscuss_replyDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_replyupdate_post_timebegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "discuss_replyupdate_post_timedebugparam1"
            when
            then
                        update(discuss_replyupdate_post_timedefault);//更新fact中变量值
                        update(discuss_replyupdate_post_timepost_obj);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "discuss_replyupdate_post_timeprepareparam1"
            when
            then
                            discuss_replyupdate_post_timepost_obj.set("id",discuss_replyupdate_post_timedefault.get("postid"));
                        update(discuss_replyupdate_post_timedefault);//更新fact中变量值
                        update(discuss_replyupdate_post_timepost_obj);//更新fact中变量值
            end

            //逻辑处理节点[更新讨论]
            rule "deaction1"
            ruleflow-group "discuss_replyupdate_post_timedeaction1"
            when
            then
                        discuss_postservice.update(discuss_replyupdate_post_timepost_obj);
                        update(discuss_replyupdate_post_timedefault);//更新fact中变量值
                        update(discuss_replyupdate_post_timepost_obj);//更新fact中变量值
            end