package cn.ibizlab.plm.base.logic.recentlogic.recent_jump_other_view;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.recent recentrecent_jump_other_viewdefault;
        global cn.ibizlab.plm.core.base.service.IrecentService iBzSysRecentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "recentrecent_jump_other_viewbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "recentrecent_jump_other_viewend1"
            when
            then
                        update(recentrecent_jump_other_viewdefault);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "recentrecent_jump_other_viewdebugparam1"
            when
            then
                        update(recentrecent_jump_other_viewdefault);//更新fact中变量值
            end