package cn.ibizlab.plm.testmgmt.logic.runlogic.add_steps;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.run runadd_stepsdefault;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case runadd_stepstest_case_obj;
                    global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService test_caseservice;
        global cn.ibizlab.plm.core.testmgmt.service.IrunService iBzSysRunDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "runadd_stepsbegin"
            when
            then
            end

            //逻辑处理节点[填充case的主键]
            rule "prepareparam1"
            ruleflow-group "runadd_stepsprepareparam1"
            when
            then
                            runadd_stepstest_case_obj.set("id",runadd_stepsdefault.get("caseid"));
                        update(runadd_stepsdefault);//更新fact中变量值
                        update(runadd_stepstest_case_obj);//更新fact中变量值
            end

            //逻辑处理节点[get case]
            rule "deaction1"
            ruleflow-group "runadd_stepsdeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(test_caseservice.get(runadd_stepstest_case_obj.getId()),runadd_stepstest_case_obj);
                        update(runadd_stepsdefault);//更新fact中变量值
                        update(runadd_stepstest_case_obj);//更新fact中变量值
            end

            //逻辑处理节点[填充run中的用例步骤]
            rule "prepareparam2"
            ruleflow-group "runadd_stepsprepareparam2"
            when
            then
                            runadd_stepsdefault.set("steps",runadd_stepstest_case_obj.get("steps"));
                        update(runadd_stepsdefault);//更新fact中变量值
                        update(runadd_stepstest_case_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "runadd_stepsend1"
            when
            then
                        update(runadd_stepsdefault);//更新fact中变量值
                        update(runadd_stepstest_case_obj);//更新fact中变量值
            end