package cn.ibizlab.plm.testmgmt.logic.runlogic.case_latest_executed;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.run runcase_latest_executeddefault;
                global cn.ibizlab.plm.core.testmgmt.domain.run runcase_latest_executedpage;
                    global cn.ibizlab.plm.core.testmgmt.service.IrunService runservice;
        global cn.ibizlab.plm.core.testmgmt.service.IrunService iBzSysRunDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "runcase_latest_executedbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "runcase_latest_executedprepareparam1"
            when
            then
                            runcase_latest_executeddefault.set("size","1");
                            runcase_latest_executeddefault.set("sort","executed_at,desc");
                            runcase_latest_executeddefault.set("n_status_isnotnull","1");
                        update(runcase_latest_executeddefault);//更新fact中变量值
                        update(runcase_latest_executedpage);//更新fact中变量值
            end

            //逻辑处理节点[获取最近执行]
            rule "dedataset1"
            ruleflow-group "runcase_latest_executeddedataset1"
            when
            then
                        update(runcase_latest_executeddefault);//更新fact中变量值
                        update(runcase_latest_executedpage);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "runcase_latest_executedend1"
            when
            then
                        update(runcase_latest_executeddefault);//更新fact中变量值
                        update(runcase_latest_executedpage);//更新fact中变量值
            end