package cn.ibizlab.plm.testmgmt.logic.runlogic.create_plan_run;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Run runcreate_plan_rundefault;
                global cn.ibizlab.plm.core.testmgmt.domain.Run runcreate_plan_runrunarray;
                    global cn.ibizlab.plm.core.testmgmt.service.IRunService runservice;
        global cn.ibizlab.plm.core.testmgmt.service.IRunService iBzSysRunDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "runcreate_plan_runbegin"
            when
            then
            end

            //逻辑处理节点[主键置空]
            rule "prepareparam1"
            ruleflow-group "runcreate_plan_runprepareparam1"
            when
            then
                                runcreate_plan_rundefault.set("id",null);
                        update(runcreate_plan_rundefault);//更新fact中变量值
                        update(runcreate_plan_runrunarray);//更新fact中变量值
            end

            //逻辑处理节点[附加到数组参数]
            rule "appendparam1"
            ruleflow-group "runcreate_plan_runappendparam1"
            when
            then
                        update(runcreate_plan_rundefault);//更新fact中变量值
                        update(runcreate_plan_runrunarray);//更新fact中变量值
            end

            //逻辑处理节点[执行create]
            rule "deaction1"
            ruleflow-group "runcreate_plan_rundeaction1"
            when
            then
                        runservice.create(runcreate_plan_runrunarray);
                        update(runcreate_plan_rundefault);//更新fact中变量值
                        update(runcreate_plan_runrunarray);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "runcreate_plan_runend1"
            when
            then
                        update(runcreate_plan_rundefault);//更新fact中变量值
                        update(runcreate_plan_runrunarray);//更新fact中变量值
            end