package cn.ibizlab.plm.testmgmt.logic.runlogic.delete;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Run rundeletedefault;
                global cn.ibizlab.plm.core.testmgmt.domain.Run rundeletefor_temp_obj;
                global cn.ibizlab.plm.core.testmgmt.domain.Run rundeleteidea_filter;
                global cn.ibizlab.plm.core.testmgmt.domain.Run rundeleteidea_page;
                    global cn.ibizlab.plm.core.testmgmt.service.IRunService runservice;
        global cn.ibizlab.plm.core.testmgmt.service.IRunService iBzSysRunDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "rundeletebegin"
            when
            then
            end

            //逻辑处理节点[设置删除状态]
            rule "prepareparam2"
            ruleflow-group "rundeleteprepareparam2"
            when
            then
                            rundeletedefault.set("is_deleted","1");
                        update(rundeletedefault);//更新fact中变量值
                        update(rundeletefor_temp_obj);//更新fact中变量值
                        update(rundeleteidea_filter);//更新fact中变量值
                        update(rundeleteidea_page);//更新fact中变量值
            end

            //逻辑处理节点[更新删除状态]
            rule "deaction1"
            ruleflow-group "rundeletedeaction1"
            when
            then
                        runservice.update(rundeletedefault);
                        update(rundeletedefault);//更新fact中变量值
                        update(rundeletefor_temp_obj);//更新fact中变量值
                        update(rundeleteidea_filter);//更新fact中变量值
                        update(rundeleteidea_page);//更新fact中变量值
            end

            //逻辑处理节点[删除最近访问]
            rule "rawsqlcall1"
            ruleflow-group "rundeleterawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",rundeletedefault.get("id"));
    String strSql="update recent set IS_DELETED=1 where owner_id=#{et.param0} and owner_subtype='run'";
                        iBzSysRunDefaultService.execute(strSql,param);//SQL调用
                        update(rundeletedefault);//更新fact中变量值
                        update(rundeletefor_temp_obj);//更新fact中变量值
                        update(rundeleteidea_filter);//更新fact中变量值
                        update(rundeleteidea_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "rundeleteend1"
            when
            then
                        update(rundeletedefault);//更新fact中变量值
                        update(rundeletefor_temp_obj);//更新fact中变量值
                        update(rundeleteidea_filter);//更新fact中变量值
                        update(rundeleteidea_page);//更新fact中变量值
            end