package cn.ibizlab.plm.testmgmt.logic.runlogic.delete_run_info;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Run rundelete_run_infodefault;
                global cn.ibizlab.plm.core.base.domain.Attachment rundelete_run_infoattachment;
                global cn.ibizlab.plm.core.base.domain.Attachment rundelete_run_infoattachments;
                global java.util.Map rundelete_run_infoid;
                global java.util.Map rundelete_run_infoids;
                global cn.ibizlab.plm.core.testmgmt.domain.Run rundelete_run_infotemp_obj;
        global cn.ibizlab.plm.core.testmgmt.service.IRunService iBzSysRunDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "rundelete_run_infobegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "rundelete_run_infodebugparam1"
            when
            then
                        update(rundelete_run_infodefault);//更新fact中变量值
                        update(rundelete_run_infoattachment);//更新fact中变量值
                        update(rundelete_run_infoattachments);//更新fact中变量值
                        update(rundelete_run_infoid);//更新fact中变量值
                        update(rundelete_run_infoids);//更新fact中变量值
                        update(rundelete_run_infotemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[移除执行用例关联附件]
            rule "rawsqlcall1"
            ruleflow-group "rundelete_run_inforawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",rundelete_run_infodefault.get("id"));
    String strSql="DELETE FROM attachment WHERE OWNER_ID = #{et.param0} ; ";
                        iBzSysRunDefaultService.execute(strSql,param);//SQL调用
                        update(rundelete_run_infodefault);//更新fact中变量值
                        update(rundelete_run_infoattachment);//更新fact中变量值
                        update(rundelete_run_infoattachments);//更新fact中变量值
                        update(rundelete_run_infoid);//更新fact中变量值
                        update(rundelete_run_infoids);//更新fact中变量值
                        update(rundelete_run_infotemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[移除执行用例关联缺陷]
            rule "rawsqlcall2"
            ruleflow-group "rundelete_run_inforawsqlcall2"
            when
            then
    Map param =new HashMap();
        param.put("param0",rundelete_run_infodefault.get("id"));
        param.put("param1",rundelete_run_infodefault.get("id"));
    String strSql="DELETE FROM relation WHERE  TARGET_ID = #{et.param0}   OR PRINCIPAL_ID = #{et.param1}; ";
                        iBzSysRunDefaultService.execute(strSql,param);//SQL调用
                        update(rundelete_run_infodefault);//更新fact中变量值
                        update(rundelete_run_infoattachment);//更新fact中变量值
                        update(rundelete_run_infoattachments);//更新fact中变量值
                        update(rundelete_run_infoid);//更新fact中变量值
                        update(rundelete_run_infoids);//更新fact中变量值
                        update(rundelete_run_infotemp_obj);//更新fact中变量值
            end