package cn.ibizlab.plm.testmgmt.logic.runlogic.get_actual_workload;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Run runget_actual_workloaddefault;
                    global cn.ibizlab.plm.core.testmgmt.service.IRunService runservice;
        global cn.ibizlab.plm.core.testmgmt.service.IRunService iBzSysRunDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "runget_actual_workloadbegin"
            when
            then
            end

            //逻辑处理节点[获取执行用例]
            rule "deaction1"
            ruleflow-group "runget_actual_workloaddeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(runservice.get(runget_actual_workloaddefault.getId()),runget_actual_workloaddefault);
                        update(runget_actual_workloaddefault);//更新fact中变量值
            end

            //逻辑处理节点[获取已登记的工时]
            rule "rawsqlcall1"
            ruleflow-group "runget_actual_workloadrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",runget_actual_workloaddefault.get("caseid"));
    String strSql="select sum(DURATION) as `ACTUAL_WORKLOAD` from `workload` where  PRINCIPAL_TYPE = 'TEST_CASE' and PRINCIPAL_ID = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysRunDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    runget_actual_workloaddefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(runget_actual_workloaddefault);//更新fact中变量值
            end

            //逻辑处理节点[获取剩余工时]
            rule "rawsqlcall2"
            ruleflow-group "runget_actual_workloadrawsqlcall2"
            when
            then
    Map param =new HashMap();
        param.put("param0",runget_actual_workloaddefault.get("caseid"));
    String strSql="select DECIMAL_VALUE as REMAINING_WORKLOAD  from extend_storage where owner_id = #{et.param0} and owner_type = 'TEST_CASE' and `name` = 'REMAINING_WORKLOAD'";
                        java.util.List<JSONObject> entities=iBzSysRunDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    runget_actual_workloaddefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(runget_actual_workloaddefault);//更新fact中变量值
            end

            //逻辑处理节点[获取预估工时]
            rule "rawsqlcall3"
            ruleflow-group "runget_actual_workloadrawsqlcall3"
            when
            then
    Map param =new HashMap();
        param.put("param0",runget_actual_workloaddefault.get("caseid"));
    String strSql="select DECIMAL_VALUE as ESTIMATED_WORKLOAD  from extend_storage where owner_id = #{et.param0} and owner_type = 'TEST_CASE' and `name` = 'ESTIMATED_WORKLOAD'";
                        java.util.List<JSONObject> entities=iBzSysRunDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    runget_actual_workloaddefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(runget_actual_workloaddefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "runget_actual_workloadend1"
            when
            then
                        update(runget_actual_workloaddefault);//更新fact中变量值
            end