package cn.ibizlab.plm.testmgmt.logic.runlogic.get_library_member;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.run runget_library_memberdefault;
                global cn.ibizlab.plm.core.testmgmt.domain.library_member runget_library_memberfilter;
                global java.util.Map runget_library_memberfor_obj;
                global cn.ibizlab.plm.core.testmgmt.domain.library_member runget_library_membermembers;
                    global cn.ibizlab.plm.core.testmgmt.service.Ilibrary_memberService library_memberservice;
        global cn.ibizlab.plm.core.testmgmt.service.IrunService iBzSysRunDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "runget_library_memberbegin"
            when
            then
            end

            //逻辑处理节点[判断系统管理员身份]
            rule "rawsfcode3"
            ruleflow-group "runget_library_memberrawsfcode3"
            when
            then
                        update(runget_library_memberdefault);//更新fact中变量值
                        update(runget_library_memberfilter);//更新fact中变量值
                        update(runget_library_memberfor_obj);//更新fact中变量值
                        update(runget_library_membermembers);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "runget_library_memberend2"
            when
            then
                        update(runget_library_memberdefault);//更新fact中变量值
                        update(runget_library_memberfilter);//更新fact中变量值
                        update(runget_library_memberfor_obj);//更新fact中变量值
                        update(runget_library_membermembers);//更新fact中变量值
            end

            //逻辑处理节点[获取测试库id并设置过滤参数]
            rule "prepareparam2"
            ruleflow-group "runget_library_memberprepareparam2"
            when
            then
                            runget_library_memberfilter.set("n_library_id_eq",runget_library_memberdefault.get("product_id"));
                                runget_library_memberfilter.set("n_user_id_eq",curuser.getSessionParams().get("srfpersonid"));
                        update(runget_library_memberdefault);//更新fact中变量值
                        update(runget_library_memberfilter);//更新fact中变量值
                        update(runget_library_memberfor_obj);//更新fact中变量值
                        update(runget_library_membermembers);//更新fact中变量值
            end

            //逻辑处理节点[查询当前用户是否为测试库成员]
            rule "dedataset3"
            ruleflow-group "runget_library_memberdedataset3"
            when
            then
                        update(runget_library_memberdefault);//更新fact中变量值
                        update(runget_library_memberfilter);//更新fact中变量值
                        update(runget_library_memberfor_obj);//更新fact中变量值
                        update(runget_library_membermembers);//更新fact中变量值
            end

            //逻辑处理节点[绑定用户数据到for_obj]
            rule "prepareparam5"
            ruleflow-group "runget_library_memberprepareparam5"
            when
            then
                            runget_library_memberfor_obj.set("",runget_library_membermembers.get("0"));
                        update(runget_library_memberdefault);//更新fact中变量值
                        update(runget_library_memberfilter);//更新fact中变量值
                        update(runget_library_memberfor_obj);//更新fact中变量值
                        update(runget_library_membermembers);//更新fact中变量值
            end

            //逻辑处理节点[只读权限]
            rule "rawsfcode1"
            ruleflow-group "runget_library_memberrawsfcode1"
            when
            then
                        update(runget_library_memberdefault);//更新fact中变量值
                        update(runget_library_memberfilter);//更新fact中变量值
                        update(runget_library_memberfor_obj);//更新fact中变量值
                        update(runget_library_membermembers);//更新fact中变量值
            end

            //逻辑处理节点[非只读权限]
            rule "rawsfcode2"
            ruleflow-group "runget_library_memberrawsfcode2"
            when
            then
                        update(runget_library_memberdefault);//更新fact中变量值
                        update(runget_library_memberfilter);//更新fact中变量值
                        update(runget_library_memberfor_obj);//更新fact中变量值
                        update(runget_library_membermembers);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end6"
            ruleflow-group "runget_library_memberend6"
            when
            then
                        update(runget_library_memberdefault);//更新fact中变量值
                        update(runget_library_memberfilter);//更新fact中变量值
                        update(runget_library_memberfor_obj);//更新fact中变量值
                        update(runget_library_membermembers);//更新fact中变量值
            end