package cn.ibizlab.plm.testmgmt.logic.runlogic.program_plan;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.run runprogram_plandefault;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case runprogram_plantest_case_info;
                global cn.ibizlab.plm.core.testmgmt.domain.run runprogram_planfor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.relation runprogram_planrelationobj;
                global cn.ibizlab.plm.core.base.domain.relation runprogram_planrelationobj2;
                global cn.ibizlab.plm.core.testmgmt.domain.run runprogram_planselect_create_data;
                global cn.ibizlab.plm.core.testmgmt.domain.run runprogram_planselectdata;
                    global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService test_caseservice;
                    global cn.ibizlab.plm.core.testmgmt.service.IrunService runservice;
        global cn.ibizlab.plm.core.testmgmt.service.IrunService iBzSysRunDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "runprogram_planbegin"
            when
            then
            end

            //逻辑处理节点[绑定关联列表参数]
            rule "bindparam1"
            ruleflow-group "runprogram_planbindparam1"
            when
            then
                        update(runprogram_plandefault);//更新fact中变量值
                        update(runprogram_plantest_case_info);//更新fact中变量值
                        update(runprogram_planfor_temp_obj);//更新fact中变量值
                        update(runprogram_planrelationobj);//更新fact中变量值
                        update(runprogram_planrelationobj2);//更新fact中变量值
                        update(runprogram_planselect_create_data);//更新fact中变量值
                        update(runprogram_planselectdata);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "runprogram_planloopsubcall1"
            when
            then
                        update(runprogram_plandefault);//更新fact中变量值
                        update(runprogram_plantest_case_info);//更新fact中变量值
                        update(runprogram_planfor_temp_obj);//更新fact中变量值
                        update(runprogram_planrelationobj);//更新fact中变量值
                        update(runprogram_planrelationobj2);//更新fact中变量值
                        update(runprogram_planselect_create_data);//更新fact中变量值
                        update(runprogram_planselectdata);//更新fact中变量值
            end

            //逻辑处理节点[设置测试用例id]
            rule "prepareparam3"
            ruleflow-group "runprogram_planprepareparam3"
            when
            then
                            runprogram_plantest_case_info.set("id",runprogram_planfor_temp_obj.get("id"));
                        update(runprogram_plandefault);//更新fact中变量值
                        update(runprogram_plantest_case_info);//更新fact中变量值
                        update(runprogram_planfor_temp_obj);//更新fact中变量值
                        update(runprogram_planrelationobj);//更新fact中变量值
                        update(runprogram_planrelationobj2);//更新fact中变量值
                        update(runprogram_planselect_create_data);//更新fact中变量值
                        update(runprogram_planselectdata);//更新fact中变量值
            end

            //逻辑处理节点[拷贝创建参数]
            rule "copyparam1"
            ruleflow-group "runprogram_plancopyparam1"
            when
            then
                        update(runprogram_plandefault);//更新fact中变量值
                        update(runprogram_plantest_case_info);//更新fact中变量值
                        update(runprogram_planfor_temp_obj);//更新fact中变量值
                        update(runprogram_planrelationobj);//更新fact中变量值
                        update(runprogram_planrelationobj2);//更新fact中变量值
                        update(runprogram_planselect_create_data);//更新fact中变量值
                        update(runprogram_planselectdata);//更新fact中变量值
            end

            //逻辑处理节点[获取测试用例详情]
            rule "deaction2"
            ruleflow-group "runprogram_plandeaction2"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(test_caseservice.get(runprogram_plantest_case_info.getId()),runprogram_plantest_case_info);
                        update(runprogram_plandefault);//更新fact中变量值
                        update(runprogram_plantest_case_info);//更新fact中变量值
                        update(runprogram_planfor_temp_obj);//更新fact中变量值
                        update(runprogram_planrelationobj);//更新fact中变量值
                        update(runprogram_planrelationobj2);//更新fact中变量值
                        update(runprogram_planselect_create_data);//更新fact中变量值
                        update(runprogram_planselectdata);//更新fact中变量值
            end

            //逻辑处理节点[准备执行用例数据]
            rule "prepareparam2"
            ruleflow-group "runprogram_planprepareparam2"
            when
            then
                            runprogram_planselect_create_data.set("caseid",runprogram_planfor_temp_obj.get("id"));
                            runprogram_planselect_create_data.set("steps",runprogram_plantest_case_info.get("steps"));
                                runprogram_planselect_create_data.set("createman",curuser.getSessionParams().get("srfpersonid"));
                                runprogram_planselect_create_data.set("updateman",curuser.getSessionParams().get("srfpersonid"));
                                runprogram_planselect_create_data.set("id",null);
                            runprogram_planselect_create_data.set("planid",runprogram_plandefault.get("principal_id"));
                        update(runprogram_plandefault);//更新fact中变量值
                        update(runprogram_plantest_case_info);//更新fact中变量值
                        update(runprogram_planfor_temp_obj);//更新fact中变量值
                        update(runprogram_planrelationobj);//更新fact中变量值
                        update(runprogram_planrelationobj2);//更新fact中变量值
                        update(runprogram_planselect_create_data);//更新fact中变量值
                        update(runprogram_planselectdata);//更新fact中变量值
            end

            //逻辑处理节点[创建执行用例]
            rule "deaction1"
            ruleflow-group "runprogram_plandeaction1"
            when
            then
                        runservice.save(runprogram_planselect_create_data);
                        update(runprogram_plandefault);//更新fact中变量值
                        update(runprogram_plantest_case_info);//更新fact中变量值
                        update(runprogram_planfor_temp_obj);//更新fact中变量值
                        update(runprogram_planrelationobj);//更新fact中变量值
                        update(runprogram_planrelationobj2);//更新fact中变量值
                        update(runprogram_planselect_create_data);//更新fact中变量值
                        update(runprogram_planselectdata);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "runprogram_planend1"
            when
            then
                        update(runprogram_plandefault);//更新fact中变量值
                        update(runprogram_plantest_case_info);//更新fact中变量值
                        update(runprogram_planfor_temp_obj);//更新fact中变量值
                        update(runprogram_planrelationobj);//更新fact中变量值
                        update(runprogram_planrelationobj2);//更新fact中变量值
                        update(runprogram_planselect_create_data);//更新fact中变量值
                        update(runprogram_planselectdata);//更新fact中变量值
            end