package cn.ibizlab.plm.testmgmt.logic.runlogic.reset_not_test;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.run runreset_not_testdefault;
                global java.util.Map runreset_not_testid;
                global java.util.Map runreset_not_testids;
                    global cn.ibizlab.plm.core.testmgmt.service.IrunService runservice;
        global cn.ibizlab.plm.core.testmgmt.service.IrunService iBzSysRunDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "runreset_not_testbegin"
            when
            then
            end

            //逻辑处理节点[获取选中的用例id]
            rule "rawsfcode1"
            ruleflow-group "runreset_not_testrawsfcode1"
            when
            then
                        update(runreset_not_testdefault);//更新fact中变量值
                        update(runreset_not_testid);//更新fact中变量值
                        update(runreset_not_testids);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "runreset_not_testend1"
            when
            then
                        update(runreset_not_testdefault);//更新fact中变量值
                        update(runreset_not_testid);//更新fact中变量值
                        update(runreset_not_testids);//更新fact中变量值
            end

            //逻辑处理节点[循环处理]
            rule "loopsubcall1"
            ruleflow-group "runreset_not_testloopsubcall1"
            when
            then
                        update(runreset_not_testdefault);//更新fact中变量值
                        update(runreset_not_testid);//更新fact中变量值
                        update(runreset_not_testids);//更新fact中变量值
            end

            //逻辑处理节点[设置当前循环用例的执行状态]
            rule "prepareparam1"
            ruleflow-group "runreset_not_testprepareparam1"
            when
            then
                                runreset_not_testdefault.set("status",null);
                            runreset_not_testdefault.set("id",runreset_not_testid.get(""));
                        update(runreset_not_testdefault);//更新fact中变量值
                        update(runreset_not_testid);//更新fact中变量值
                        update(runreset_not_testids);//更新fact中变量值
            end

            //逻辑处理节点[修改用例]
            rule "deaction1"
            ruleflow-group "runreset_not_testdeaction1"
            when
            then
                        runservice.update(runreset_not_testdefault);
                        update(runreset_not_testdefault);//更新fact中变量值
                        update(runreset_not_testid);//更新fact中变量值
                        update(runreset_not_testids);//更新fact中变量值
            end