package cn.ibizlab.plm.testmgmt.logic.runlogic.update_executor;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Run runupdate_executordefault;
                global java.util.Map runupdate_executorid;
                global java.util.Map runupdate_executorids;
                global cn.ibizlab.plm.core.testmgmt.domain.Run runupdate_executortemp_obj;
                    global cn.ibizlab.plm.core.testmgmt.service.IRunService runservice;
        global cn.ibizlab.plm.core.testmgmt.service.IRunService iBzSysRunDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "runupdate_executorbegin"
            when
            then
            end

            //逻辑处理节点[获取选中的id]
            rule "rawsfcode1"
            ruleflow-group "runupdate_executorrawsfcode1"
            when
            then
                        update(runupdate_executordefault);//更新fact中变量值
                        update(runupdate_executorid);//更新fact中变量值
                        update(runupdate_executorids);//更新fact中变量值
                        update(runupdate_executortemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "runupdate_executorend1"
            when
            then
                        update(runupdate_executordefault);//更新fact中变量值
                        update(runupdate_executorid);//更新fact中变量值
                        update(runupdate_executorids);//更新fact中变量值
                        update(runupdate_executortemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "runupdate_executorloopsubcall1"
            when
            then
                        update(runupdate_executordefault);//更新fact中变量值
                        update(runupdate_executorid);//更新fact中变量值
                        update(runupdate_executorids);//更新fact中变量值
                        update(runupdate_executortemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[重置临时变量]
            rule "renewparam1"
            ruleflow-group "runupdate_executorrenewparam1"
            when
            then
                        update(runupdate_executordefault);//更新fact中变量值
                        update(runupdate_executorid);//更新fact中变量值
                        update(runupdate_executorids);//更新fact中变量值
                        update(runupdate_executortemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[将执行人信息赋予临时变量]
            rule "prepareparam1"
            ruleflow-group "runupdate_executorprepareparam1"
            when
            then
                            runupdate_executortemp_obj.set("executorid",runupdate_executordefault.get("executorid"));
                            runupdate_executortemp_obj.set("executorname",runupdate_executordefault.get("executorname"));
                            runupdate_executortemp_obj.set("id",runupdate_executorid.get(""));
                        update(runupdate_executordefault);//更新fact中变量值
                        update(runupdate_executorid);//更新fact中变量值
                        update(runupdate_executorids);//更新fact中变量值
                        update(runupdate_executortemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[执行更新操作]
            rule "deaction1"
            ruleflow-group "runupdate_executordeaction1"
            when
            then
                        runservice.update(runupdate_executortemp_obj);
                        update(runupdate_executordefault);//更新fact中变量值
                        update(runupdate_executorid);//更新fact中变量值
                        update(runupdate_executorids);//更新fact中变量值
                        update(runupdate_executortemp_obj);//更新fact中变量值
            end