package cn.ibizlab.plm.testmgmt.logic.test_suitelogic.suites_count;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Test_suite test_suitesuites_countdefault;
                global cn.ibizlab.plm.core.testmgmt.domain.Test_suite test_suitesuites_countsuite_info;
                global cn.ibizlab.plm.core.testmgmt.domain.Test_case test_suitesuites_counttest_case_info;
                    global cn.ibizlab.plm.core.testmgmt.service.ITest_caseService test_caseservice;
                    global cn.ibizlab.plm.core.testmgmt.service.ITest_suiteService test_suiteservice;
        global cn.ibizlab.plm.core.testmgmt.service.ITest_suiteService iBzSysTest_suiteDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_suitesuites_countbegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam3"
            ruleflow-group "test_suitesuites_countdebugparam3"
            when
            then
                        update(test_suitesuites_countdefault);//更新fact中变量值
                        update(test_suitesuites_countsuite_info);//更新fact中变量值
                        update(test_suitesuites_counttest_case_info);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "test_suitesuites_countprepareparam1"
            when
            then
                            test_suitesuites_counttest_case_info.set("id",test_suitesuites_countdefault.get("case_id"));
                        update(test_suitesuites_countdefault);//更新fact中变量值
                        update(test_suitesuites_countsuite_info);//更新fact中变量值
                        update(test_suitesuites_counttest_case_info);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "test_suitesuites_countdeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(test_caseservice.get(test_suitesuites_counttest_case_info.getId()),test_suitesuites_counttest_case_info);
                        update(test_suitesuites_countdefault);//更新fact中变量值
                        update(test_suitesuites_countsuite_info);//更新fact中变量值
                        update(test_suitesuites_counttest_case_info);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode1"
            ruleflow-group "test_suitesuites_countrawsfcode1"
            when
            then
                        update(test_suitesuites_countdefault);//更新fact中变量值
                        update(test_suitesuites_countsuite_info);//更新fact中变量值
                        update(test_suitesuites_counttest_case_info);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam2"
            ruleflow-group "test_suitesuites_countdebugparam2"
            when
            then
                        update(test_suitesuites_countdefault);//更新fact中变量值
                        update(test_suitesuites_countsuite_info);//更新fact中变量值
                        update(test_suitesuites_counttest_case_info);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_suitesuites_countend1"
            when
            then
                        update(test_suitesuites_countdefault);//更新fact中变量值
                        update(test_suitesuites_countsuite_info);//更新fact中变量值
                        update(test_suitesuites_counttest_case_info);//更新fact中变量值
            end

            //逻辑处理节点[递归调用]
            rule "delogic1"
            ruleflow-group "test_suitesuites_countdelogic1"
            when
            then
                        update(test_suitesuites_countdefault);//更新fact中变量值
                        update(test_suitesuites_countsuite_info);//更新fact中变量值
                        update(test_suitesuites_counttest_case_info);//更新fact中变量值
            end