package cn.ibizlab.plm.base.logic.executorlogic.after_create_notice;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.executor executorafter_create_noticedefault;
                    global cn.ibizlab.plm.core.base.service.IexecutorService executorservice;
        global cn.ibizlab.plm.core.base.service.IexecutorService iBzSysExecutorDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "executorafter_create_noticebegin"
            when
            then
            end

            //逻辑处理节点[通知工作项执行人]
            rule "denotify1"
            ruleflow-group "executorafter_create_noticedenotify1"
            when
            then
                        update(executorafter_create_noticedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "executorafter_create_noticeend1"
            when
            then
                        update(executorafter_create_noticedefault);//更新fact中变量值
            end