package cn.ibizlab.plm.base.logic.executorlogic.del_notice;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.executor executordel_noticedefault;
                    global cn.ibizlab.plm.core.base.service.IexecutorService executorservice;
        global cn.ibizlab.plm.core.base.service.IexecutorService iBzSysExecutorDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "executordel_noticebegin"
            when
            then
            end

            //逻辑处理节点[获取执行人]
            rule "deaction1"
            ruleflow-group "executordel_noticedeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(executorservice.get(executordel_noticedefault.getId()),executordel_noticedefault);
                        update(executordel_noticedefault);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode1"
            ruleflow-group "executordel_noticerawsfcode1"
            when
            then
                        update(executordel_noticedefault);//更新fact中变量值
            end

            //逻辑处理节点[通知取消工作项分配执行人]
            rule "denotify1"
            ruleflow-group "executordel_noticedenotify1"
            when
            then
                        update(executordel_noticedefault);//更新fact中变量值
            end