package cn.ibizlab.plm.projmgmt.logic.sprintlogic.cal_sprint_work_item_num;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.sprint sprintcal_sprint_work_item_numdefault;
        global cn.ibizlab.plm.core.projmgmt.service.IsprintService iBzSysSprintDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "sprintcal_sprint_work_item_numbegin"
            when
            then
            end

            //逻辑处理节点[查询迭代全部工作项]
            rule "rawsqlcall1"
            ruleflow-group "sprintcal_sprint_work_item_numrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",sprintcal_sprint_work_item_numdefault.get("id"));
    String strSql="select count(1) as `all` from work_item where IS_DELETED = '0' and SPRINT_ID = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysSprintDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    sprintcal_sprint_work_item_numdefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(sprintcal_sprint_work_item_numdefault);//更新fact中变量值
            end

            //逻辑处理节点[查询迭代进行中工作项]
            rule "rawsqlcall2"
            ruleflow-group "sprintcal_sprint_work_item_numrawsqlcall2"
            when
            then
    Map param =new HashMap();
        param.put("param0",sprintcal_sprint_work_item_numdefault.get("id"));
    String strSql="select count(1) as `in_progress` from work_item where IS_DELETED = '0' and `STATE` IN ('20','30','32','34','36') and SPRINT_ID = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysSprintDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    sprintcal_sprint_work_item_numdefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(sprintcal_sprint_work_item_numdefault);//更新fact中变量值
            end

            //逻辑处理节点[查询迭代已完成工作项]
            rule "rawsqlcall3"
            ruleflow-group "sprintcal_sprint_work_item_numrawsqlcall3"
            when
            then
    Map param =new HashMap();
        param.put("param0",sprintcal_sprint_work_item_numdefault.get("id"));
    String strSql="select count(1) as `completed` from work_item where IS_DELETED = '0' and `STATE` = '40' and SPRINT_ID = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysSprintDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    sprintcal_sprint_work_item_numdefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(sprintcal_sprint_work_item_numdefault);//更新fact中变量值
            end

            //逻辑处理节点[查询迭代未开始工作项]
            rule "rawsqlcall4"
            ruleflow-group "sprintcal_sprint_work_item_numrawsqlcall4"
            when
            then
    Map param =new HashMap();
        param.put("param0",sprintcal_sprint_work_item_numdefault.get("id"));
    String strSql="select count(1) as `pending` from work_item where IS_DELETED = '0' and `STATE` IN ('10','14','16','50','60') and SPRINT_ID = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysSprintDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    sprintcal_sprint_work_item_numdefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(sprintcal_sprint_work_item_numdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "sprintcal_sprint_work_item_numend1"
            when
            then
                        update(sprintcal_sprint_work_item_numdefault);//更新fact中变量值
            end