package cn.ibizlab.plm.projmgmt.logic.sprintlogic.del_relation;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.sprint sprintdel_relationdefault;
                global cn.ibizlab.plm.core.base.domain.relation sprintdel_relationforward_relation_obj;
                global cn.ibizlab.plm.core.base.domain.relation sprintdel_relationreverse_relation_obj;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.projmgmt.service.IsprintService iBzSysSprintDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "sprintdel_relationbegin"
            when
            then
            end

            //逻辑处理节点[填充正反关联对象的主要关联属性]
            rule "prepareparam1"
            ruleflow-group "sprintdel_relationprepareparam1"
            when
            then
                            sprintdel_relationforward_relation_obj.set("principalid",sprintdel_relationdefault.get("principal_id"));
                            sprintdel_relationreverse_relation_obj.set("principalid",sprintdel_relationdefault.get("id"));
                            sprintdel_relationreverse_relation_obj.set("targetid",sprintdel_relationdefault.get("principal_id"));
                            sprintdel_relationforward_relation_obj.set("targetid",sprintdel_relationdefault.get("id"));
                        update(sprintdel_relationdefault);//更新fact中变量值
                        update(sprintdel_relationforward_relation_obj);//更新fact中变量值
                        update(sprintdel_relationreverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[拼接关联对象的主键]
            rule "rawsfcode1"
            ruleflow-group "sprintdel_relationrawsfcode1"
            when
            then
                        update(sprintdel_relationdefault);//更新fact中变量值
                        update(sprintdel_relationforward_relation_obj);//更新fact中变量值
                        update(sprintdel_relationreverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[删除正向关联]
            rule "deaction1"
            ruleflow-group "sprintdel_relationdeaction1"
            when
            then
                        relationservice.remove(sprintdel_relationforward_relation_obj.getId());
                        update(sprintdel_relationdefault);//更新fact中变量值
                        update(sprintdel_relationforward_relation_obj);//更新fact中变量值
                        update(sprintdel_relationreverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[删除反向关联]
            rule "deaction2"
            ruleflow-group "sprintdel_relationdeaction2"
            when
            then
                        relationservice.remove(sprintdel_relationreverse_relation_obj.getId());
                        update(sprintdel_relationdefault);//更新fact中变量值
                        update(sprintdel_relationforward_relation_obj);//更新fact中变量值
                        update(sprintdel_relationreverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "sprintdel_relationend1"
            when
            then
                        update(sprintdel_relationdefault);//更新fact中变量值
                        update(sprintdel_relationforward_relation_obj);//更新fact中变量值
                        update(sprintdel_relationreverse_relation_obj);//更新fact中变量值
            end