package cn.ibizlab.plm.projmgmt.logic.sprintlogic.mob_project_sprint;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.sprint sprintmob_project_sprintdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.sprint sprintmob_project_sprintfilter;
                global cn.ibizlab.plm.core.projmgmt.domain.sprint sprintmob_project_sprintsprint_page_result;
                    global cn.ibizlab.plm.core.projmgmt.service.IsprintService sprintservice;
        global cn.ibizlab.plm.core.projmgmt.service.IsprintService iBzSysSprintDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "sprintmob_project_sprintbegin"
            when
            then
            end

            //逻辑处理节点[设置过滤器]
            rule "prepareparam1"
            ruleflow-group "sprintmob_project_sprintprepareparam1"
            when
            then
                            sprintmob_project_sprintfilter.set("n_project_id_eq",sprintmob_project_sprintdefault.get("project"));
                        update(sprintmob_project_sprintdefault);//更新fact中变量值
                        update(sprintmob_project_sprintfilter);//更新fact中变量值
                        update(sprintmob_project_sprintsprint_page_result);//更新fact中变量值
            end

            //逻辑处理节点[项目下迭代]
            rule "dedataset1"
            ruleflow-group "sprintmob_project_sprintdedataset1"
            when
            then
                        update(sprintmob_project_sprintdefault);//更新fact中变量值
                        update(sprintmob_project_sprintfilter);//更新fact中变量值
                        update(sprintmob_project_sprintsprint_page_result);//更新fact中变量值
            end

            //逻辑处理节点[填充进度信息]
            rule "rawsfcode1"
            ruleflow-group "sprintmob_project_sprintrawsfcode1"
            when
            then
                        update(sprintmob_project_sprintdefault);//更新fact中变量值
                        update(sprintmob_project_sprintfilter);//更新fact中变量值
                        update(sprintmob_project_sprintsprint_page_result);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "sprintmob_project_sprintend1"
            when
            then
                        update(sprintmob_project_sprintdefault);//更新fact中变量值
                        update(sprintmob_project_sprintfilter);//更新fact中变量值
                        update(sprintmob_project_sprintsprint_page_result);//更新fact中变量值
            end