package cn.ibizlab.plm.projmgmt.logic.sprintlogic.oppriv_logic;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.sprint sprintoppriv_logicdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.sprint sprintoppriv_logicoppriv;
        global cn.ibizlab.plm.core.projmgmt.service.IsprintService iBzSysSprintDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "sprintoppriv_logicbegin"
            when
            then
            end

            //逻辑处理节点[不允许修改]
            rule "prepareparam1"
            ruleflow-group "sprintoppriv_logicprepareparam1"
            when
            then
                            sprintoppriv_logicoppriv.set("update","false");
                        update(sprintoppriv_logicdefault);//更新fact中变量值
                        update(sprintoppriv_logicoppriv);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "sprintoppriv_logicend1"
            when
            then
                        update(sprintoppriv_logicdefault);//更新fact中变量值
                        update(sprintoppriv_logicoppriv);//更新fact中变量值
            end