package cn.ibizlab.plm.projmgmt.logic.sprintlogic.overview_num;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.sprint sprintoverview_numdefault;
                    global cn.ibizlab.plm.core.projmgmt.service.IsprintService sprintservice;
        global cn.ibizlab.plm.core.projmgmt.service.IsprintService iBzSysSprintDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "sprintoverview_numbegin"
            when
            then
            end

            //逻辑处理节点[获取迭代信息]
            rule "deaction1"
            ruleflow-group "sprintoverview_numdeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(sprintservice.get(sprintoverview_numdefault.getId()),sprintoverview_numdefault);
                        update(sprintoverview_numdefault);//更新fact中变量值
            end

            //逻辑处理节点[计算迭代结束日期距离今天的天数]
            rule "rawsfcode1"
            ruleflow-group "sprintoverview_numrawsfcode1"
            when
            then
                        update(sprintoverview_numdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "sprintoverview_numend1"
            when
            then
                        update(sprintoverview_numdefault);//更新fact中变量值
            end