package cn.ibizlab.plm.projmgmt.logic.sprintlogic.sprint_relation_release;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.sprint sprintsprint_relation_releasedefault;
                global cn.ibizlab.plm.core.projmgmt.domain.release sprintsprint_relation_releasefor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.relation sprintsprint_relation_releaseforward_relation_obj;
                global cn.ibizlab.plm.core.base.domain.relation sprintsprint_relation_releasereverse_relation_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.release sprintsprint_relation_releaseselectdata;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.projmgmt.service.IsprintService iBzSysSprintDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "sprintsprint_relation_releasebegin"
            when
            then
            end

            //逻辑处理节点[绑定选中发布列表]
            rule "bindparam1"
            ruleflow-group "sprintsprint_relation_releasebindparam1"
            when
            then
                        update(sprintsprint_relation_releasedefault);//更新fact中变量值
                        update(sprintsprint_relation_releasefor_temp_obj);//更新fact中变量值
                        update(sprintsprint_relation_releaseforward_relation_obj);//更新fact中变量值
                        update(sprintsprint_relation_releasereverse_relation_obj);//更新fact中变量值
                        update(sprintsprint_relation_releaseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "sprintsprint_relation_releaseloopsubcall1"
            when
            then
                        update(sprintsprint_relation_releasedefault);//更新fact中变量值
                        update(sprintsprint_relation_releasefor_temp_obj);//更新fact中变量值
                        update(sprintsprint_relation_releaseforward_relation_obj);//更新fact中变量值
                        update(sprintsprint_relation_releasereverse_relation_obj);//更新fact中变量值
                        update(sprintsprint_relation_releaseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[重新建立正向关系参数]
            rule "renewparam1"
            ruleflow-group "sprintsprint_relation_releaserenewparam1"
            when
            then
                        update(sprintsprint_relation_releasedefault);//更新fact中变量值
                        update(sprintsprint_relation_releasefor_temp_obj);//更新fact中变量值
                        update(sprintsprint_relation_releaseforward_relation_obj);//更新fact中变量值
                        update(sprintsprint_relation_releasereverse_relation_obj);//更新fact中变量值
                        update(sprintsprint_relation_releaseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[重新建立反向关系参数]
            rule "renewparam2"
            ruleflow-group "sprintsprint_relation_releaserenewparam2"
            when
            then
                        update(sprintsprint_relation_releasedefault);//更新fact中变量值
                        update(sprintsprint_relation_releasefor_temp_obj);//更新fact中变量值
                        update(sprintsprint_relation_releaseforward_relation_obj);//更新fact中变量值
                        update(sprintsprint_relation_releasereverse_relation_obj);//更新fact中变量值
                        update(sprintsprint_relation_releaseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[填充需要的属性值]
            rule "prepareparam1"
            ruleflow-group "sprintsprint_relation_releaseprepareparam1"
            when
            then
                            sprintsprint_relation_releaseforward_relation_obj.set("principalid",sprintsprint_relation_releasedefault.get("principal_id"));
                            sprintsprint_relation_releasereverse_relation_obj.set("principalid",sprintsprint_relation_releasefor_temp_obj.get("id"));
                            sprintsprint_relation_releasereverse_relation_obj.set("targetid",sprintsprint_relation_releasedefault.get("principal_id"));
                            sprintsprint_relation_releasereverse_relation_obj.set("principaltype","release");
                            sprintsprint_relation_releasereverse_relation_obj.set("targettype","sprint");
                            sprintsprint_relation_releaseforward_relation_obj.set("principaltype","sprint");
                            sprintsprint_relation_releaseforward_relation_obj.set("targettype","release");
                            sprintsprint_relation_releaseforward_relation_obj.set("targetid",sprintsprint_relation_releasefor_temp_obj.get("id"));
                        update(sprintsprint_relation_releasedefault);//更新fact中变量值
                        update(sprintsprint_relation_releasefor_temp_obj);//更新fact中变量值
                        update(sprintsprint_relation_releaseforward_relation_obj);//更新fact中变量值
                        update(sprintsprint_relation_releasereverse_relation_obj);//更新fact中变量值
                        update(sprintsprint_relation_releaseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[生成正向关联数据]
            rule "deaction1"
            ruleflow-group "sprintsprint_relation_releasedeaction1"
            when
            then
                        relationservice.save(sprintsprint_relation_releaseforward_relation_obj);
                        update(sprintsprint_relation_releasedefault);//更新fact中变量值
                        update(sprintsprint_relation_releasefor_temp_obj);//更新fact中变量值
                        update(sprintsprint_relation_releaseforward_relation_obj);//更新fact中变量值
                        update(sprintsprint_relation_releasereverse_relation_obj);//更新fact中变量值
                        update(sprintsprint_relation_releaseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "sprintsprint_relation_releaseend1"
            when
            then
                        update(sprintsprint_relation_releasedefault);//更新fact中变量值
                        update(sprintsprint_relation_releasefor_temp_obj);//更新fact中变量值
                        update(sprintsprint_relation_releaseforward_relation_obj);//更新fact中变量值
                        update(sprintsprint_relation_releasereverse_relation_obj);//更新fact中变量值
                        update(sprintsprint_relation_releaseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[生成反向关联数据]
            rule "deaction2"
            ruleflow-group "sprintsprint_relation_releasedeaction2"
            when
            then
                        relationservice.save(sprintsprint_relation_releasereverse_relation_obj);
                        update(sprintsprint_relation_releasedefault);//更新fact中变量值
                        update(sprintsprint_relation_releasefor_temp_obj);//更新fact中变量值
                        update(sprintsprint_relation_releaseforward_relation_obj);//更新fact中变量值
                        update(sprintsprint_relation_releasereverse_relation_obj);//更新fact中变量值
                        update(sprintsprint_relation_releaseselectdata);//更新fact中变量值
            end