package cn.ibizlab.plm.testmgmt.logic.review_stagelogic.cur_reviewer;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage review_stagecur_reviewerdefault;
                global cn.ibizlab.plm.core.testmgmt.domain.review review_stagecur_reviewertemp;
                    global cn.ibizlab.plm.core.testmgmt.service.IreviewService reviewservice;
        global cn.ibizlab.plm.core.testmgmt.service.Ireview_stageService iBzSysReview_stageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "review_stagecur_reviewerbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "review_stagecur_reviewerprepareparam1"
            when
            then
                        update(review_stagecur_reviewerdefault);//更新fact中变量值
                        update(review_stagecur_reviewertemp);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "review_stagecur_reviewerdeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(reviewservice.get(review_stagecur_reviewertemp.getId()),review_stagecur_reviewertemp);
                        update(review_stagecur_reviewerdefault);//更新fact中变量值
                        update(review_stagecur_reviewertemp);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "review_stagecur_reviewerdebugparam1"
            when
            then
                        update(review_stagecur_reviewerdefault);//更新fact中变量值
                        update(review_stagecur_reviewertemp);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "review_stagecur_reviewerend1"
            when
            then
                        update(review_stagecur_reviewerdefault);//更新fact中变量值
                        update(review_stagecur_reviewertemp);//更新fact中变量值
            end