package cn.ibizlab.plm.testmgmt.logic.review_stagelogic.reviewers;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage review_stagereviewersdefault;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage review_stagereviewerspages;
                global cn.ibizlab.plm.core.testmgmt.domain.review review_stagereviewersreview;
                    global cn.ibizlab.plm.core.testmgmt.service.IreviewService reviewservice;
                    global cn.ibizlab.plm.core.testmgmt.service.Ireview_stageService review_stageservice;
        global cn.ibizlab.plm.core.testmgmt.service.Ireview_stageService iBzSysReview_stageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "review_stagereviewersbegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam2"
            ruleflow-group "review_stagereviewersdebugparam2"
            when
            then
                        update(review_stagereviewersdefault);//更新fact中变量值
                        update(review_stagereviewerspages);//更新fact中变量值
                        update(review_stagereviewersreview);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "review_stagereviewersprepareparam1"
            when
            then
                            review_stagereviewersreview.set("id",review_stagereviewersdefault.get("id"));
                        update(review_stagereviewersdefault);//更新fact中变量值
                        update(review_stagereviewerspages);//更新fact中变量值
                        update(review_stagereviewersreview);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "review_stagereviewersdeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(reviewservice.get(review_stagereviewersreview.getId()),review_stagereviewersreview);
                        update(review_stagereviewersdefault);//更新fact中变量值
                        update(review_stagereviewerspages);//更新fact中变量值
                        update(review_stagereviewersreview);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "review_stagereviewersdedataset1"
            when
            then
                        update(review_stagereviewersdefault);//更新fact中变量值
                        update(review_stagereviewerspages);//更新fact中变量值
                        update(review_stagereviewersreview);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "review_stagereviewersdebugparam1"
            when
            then
                        update(review_stagereviewersdefault);//更新fact中变量值
                        update(review_stagereviewerspages);//更新fact中变量值
                        update(review_stagereviewersreview);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "review_stagereviewersbindparam1"
            when
            then
                        update(review_stagereviewersdefault);//更新fact中变量值
                        update(review_stagereviewerspages);//更新fact中变量值
                        update(review_stagereviewersreview);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "review_stagereviewersend1"
            when
            then
                        update(review_stagereviewersdefault);//更新fact中变量值
                        update(review_stagereviewerspages);//更新fact中变量值
                        update(review_stagereviewersreview);//更新fact中变量值
            end