package cn.ibizlab.plm.team.logic.discuss_postlogic.get_post_auth;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_post discuss_postget_post_authdefault;
        global cn.ibizlab.plm.core.team.service.Idiscuss_postService iBzSysDiscuss_postDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_postget_post_authbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_postget_post_authend1"
            when
            then
                        update(discuss_postget_post_authdefault);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "discuss_postget_post_authdebugparam1"
            when
            then
                        update(discuss_postget_post_authdefault);//更新fact中变量值
            end

            //逻辑处理节点[判断]
            rule "rawsfcode1"
            ruleflow-group "discuss_postget_post_authrawsfcode1"
            when
            then
                        update(discuss_postget_post_authdefault);//更新fact中变量值
            end