package cn.ibizlab.plm.team.logic.discuss_postlogic.in_progress;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_post discuss_postin_progressdefault;
                global cn.ibizlab.plm.core.team.domain.discuss_post discuss_postin_progressupdate_obj;
                    global cn.ibizlab.plm.core.team.service.Idiscuss_postService discuss_postservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_postService iBzSysDiscuss_postDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_postin_progressbegin"
            when
            then
            end

            //逻辑处理节点[设置为进行中状态]
            rule "prepareparam1"
            ruleflow-group "discuss_postin_progressprepareparam1"
            when
            then
                            discuss_postin_progressupdate_obj.set("id",discuss_postin_progressdefault.get("id"));
                            discuss_postin_progressupdate_obj.set("status","1");
                        update(discuss_postin_progressdefault);//更新fact中变量值
                        update(discuss_postin_progressupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[执行更新]
            rule "deaction1"
            ruleflow-group "discuss_postin_progressdeaction1"
            when
            then
                        discuss_postservice.update(discuss_postin_progressupdate_obj);
                        update(discuss_postin_progressdefault);//更新fact中变量值
                        update(discuss_postin_progressupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_postin_progressend1"
            when
            then
                        update(discuss_postin_progressdefault);//更新fact中变量值
                        update(discuss_postin_progressupdate_obj);//更新fact中变量值
            end