package cn.ibizlab.plm.team.logic.discuss_postlogic.recover;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_post discuss_postrecoverdefault;
                global cn.ibizlab.plm.core.team.domain.discuss_post discuss_postrecoverupdate_obj;
                    global cn.ibizlab.plm.core.team.service.Idiscuss_postService discuss_postservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_postService iBzSysDiscuss_postDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_postrecoverbegin"
            when
            then
            end

            //逻辑处理节点[设置删除状态]
            rule "prepareparam2"
            ruleflow-group "discuss_postrecoverprepareparam2"
            when
            then
                            discuss_postrecoverupdate_obj.set("isdeleted","0");
                            discuss_postrecoverupdate_obj.set("id",discuss_postrecoverdefault.get("id"));
                        update(discuss_postrecoverdefault);//更新fact中变量值
                        update(discuss_postrecoverupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[更新删除状态]
            rule "deaction1"
            ruleflow-group "discuss_postrecoverdeaction1"
            when
            then
                        discuss_postservice.update(discuss_postrecoverupdate_obj);
                        update(discuss_postrecoverdefault);//更新fact中变量值
                        update(discuss_postrecoverupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[恢复最近访问]
            rule "rawsqlcall1"
            ruleflow-group "discuss_postrecoverrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",discuss_postrecoverdefault.get("id"));
    String strSql="update recent set IS_DELETED=0 where owner_id=#{et.param0} and owner_subtype='idea'";
                        iBzSysDiscuss_postDefaultService.execute(strSql,param);//SQL调用
                        update(discuss_postrecoverdefault);//更新fact中变量值
                        update(discuss_postrecoverupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_postrecoverend1"
            when
            then
                        update(discuss_postrecoverdefault);//更新fact中变量值
                        update(discuss_postrecoverupdate_obj);//更新fact中变量值
            end