package cn.ibizlab.plm.team.logic.discuss_postlogic.send_comment;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_post discuss_postsend_commentdefault;
                global cn.ibizlab.plm.core.base.domain.comment discuss_postsend_commentcommnet;
                    global cn.ibizlab.plm.core.base.service.IcommentService commentservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_postService iBzSysDiscuss_postDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_postsend_commentbegin"
            when
            then
            end

            //逻辑处理节点[准备评论数据]
            rule "prepareparam1"
            ruleflow-group "discuss_postsend_commentprepareparam1"
            when
            then
                            discuss_postsend_commentcommnet.set("principalid",discuss_postsend_commentdefault.get("principal_id"));
                            discuss_postsend_commentcommnet.set("content",discuss_postsend_commentdefault.get("content"));
                            discuss_postsend_commentcommnet.set("ownertype","DISCUSS_POST");
                            discuss_postsend_commentcommnet.set("principaltype","DISCUSS_POST");
                        update(discuss_postsend_commentdefault);//更新fact中变量值
                        update(discuss_postsend_commentcommnet);//更新fact中变量值
            end

            //逻辑处理节点[添加评论]
            rule "deaction1"
            ruleflow-group "discuss_postsend_commentdeaction1"
            when
            then
                        commentservice.save(discuss_postsend_commentcommnet);
                        update(discuss_postsend_commentdefault);//更新fact中变量值
                        update(discuss_postsend_commentcommnet);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_postsend_commentend1"
            when
            then
                        update(discuss_postsend_commentdefault);//更新fact中变量值
                        update(discuss_postsend_commentcommnet);//更新fact中变量值
            end