package cn.ibizlab.plm.team.logic.discuss_postlogic.update_comment;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_post discuss_postupdate_commentdefault;
                global cn.ibizlab.plm.core.base.domain.comment discuss_postupdate_commentcommnet;
                    global cn.ibizlab.plm.core.base.service.IcommentService commentservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_postService iBzSysDiscuss_postDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_postupdate_commentbegin"
            when
            then
            end

            //逻辑处理节点[准备评论数据]
            rule "prepareparam1"
            ruleflow-group "discuss_postupdate_commentprepareparam1"
            when
            then
                            discuss_postupdate_commentcommnet.set("id",discuss_postupdate_commentdefault.get("comment_id"));
                            discuss_postupdate_commentcommnet.set("content",discuss_postupdate_commentdefault.get("content"));
                        update(discuss_postupdate_commentdefault);//更新fact中变量值
                        update(discuss_postupdate_commentcommnet);//更新fact中变量值
            end

            //逻辑处理节点[修改评论]
            rule "deaction1"
            ruleflow-group "discuss_postupdate_commentdeaction1"
            when
            then
                        commentservice.update(discuss_postupdate_commentcommnet);
                        update(discuss_postupdate_commentdefault);//更新fact中变量值
                        update(discuss_postupdate_commentcommnet);//更新fact中变量值
            end

            //逻辑处理节点[修改评论内容]
            rule "rawsqlcall1"
            ruleflow-group "discuss_postupdate_commentrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",discuss_postupdate_commentcommnet.get("content"));
        param.put("param1",discuss_postupdate_commentcommnet.get("id"));
    String strSql="update comment set CONTENT = #{et.param0} where id = #{et.param1}";
                        iBzSysDiscuss_postDefaultService.execute(strSql,param);//SQL调用
                        update(discuss_postupdate_commentdefault);//更新fact中变量值
                        update(discuss_postupdate_commentcommnet);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_postupdate_commentend1"
            when
            then
                        update(discuss_postupdate_commentdefault);//更新fact中变量值
                        update(discuss_postupdate_commentcommnet);//更新fact中变量值
            end