package cn.ibizlab.plm.base.logic.memberlogic.add_member_position;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.member memberadd_member_positiondefault;
                global cn.ibizlab.plm.core.base.domain.user memberadd_member_positionfor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.member memberadd_member_positionmember_obj;
                global cn.ibizlab.plm.core.base.domain.user memberadd_member_positionselectdata;
                    global cn.ibizlab.plm.core.base.service.ImemberService memberservice;
        global cn.ibizlab.plm.core.base.service.ImemberService iBzSysMemberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "memberadd_member_positionbegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "memberadd_member_positionbindparam1"
            when
            then
                        update(memberadd_member_positiondefault);//更新fact中变量值
                        update(memberadd_member_positionfor_temp_obj);//更新fact中变量值
                        update(memberadd_member_positionmember_obj);//更新fact中变量值
                        update(memberadd_member_positionselectdata);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "memberadd_member_positionloopsubcall1"
            when
            then
                        update(memberadd_member_positiondefault);//更新fact中变量值
                        update(memberadd_member_positionfor_temp_obj);//更新fact中变量值
                        update(memberadd_member_positionmember_obj);//更新fact中变量值
                        update(memberadd_member_positionselectdata);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "memberadd_member_positionrenewparam1"
            when
            then
                        update(memberadd_member_positiondefault);//更新fact中变量值
                        update(memberadd_member_positionfor_temp_obj);//更新fact中变量值
                        update(memberadd_member_positionmember_obj);//更新fact中变量值
                        update(memberadd_member_positionselectdata);//更新fact中变量值
            end

            //逻辑处理节点[填充团队成员属性]
            rule "prepareparam1"
            ruleflow-group "memberadd_member_positionprepareparam1"
            when
            then
                            memberadd_member_positionmember_obj.set("userid",memberadd_member_positionfor_temp_obj.get("id"));
                            memberadd_member_positionmember_obj.set("ownertype","GROUP");
                            memberadd_member_positionmember_obj.set("ownersubtype","GROUP");
                            memberadd_member_positionmember_obj.set("name",memberadd_member_positionfor_temp_obj.get("displayname"));
                            memberadd_member_positionmember_obj.set("ownerid",memberadd_member_positiondefault.get("ownerid"));
                        update(memberadd_member_positiondefault);//更新fact中变量值
                        update(memberadd_member_positionfor_temp_obj);//更新fact中变量值
                        update(memberadd_member_positionmember_obj);//更新fact中变量值
                        update(memberadd_member_positionselectdata);//更新fact中变量值
            end

            //逻辑处理节点[建立团队成员]
            rule "deaction1"
            ruleflow-group "memberadd_member_positiondeaction1"
            when
            then
                        memberservice.update(memberadd_member_positionmember_obj);
                        update(memberadd_member_positiondefault);//更新fact中变量值
                        update(memberadd_member_positionfor_temp_obj);//更新fact中变量值
                        update(memberadd_member_positionmember_obj);//更新fact中变量值
                        update(memberadd_member_positionselectdata);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "memberadd_member_positionend1"
            when
            then
                        update(memberadd_member_positiondefault);//更新fact中变量值
                        update(memberadd_member_positionfor_temp_obj);//更新fact中变量值
                        update(memberadd_member_positionmember_obj);//更新fact中变量值
                        update(memberadd_member_positionselectdata);//更新fact中变量值
            end