package cn.ibizlab.plm.base.logic.memberlogic.create_member;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.member membercreate_memberdefault;
                global cn.ibizlab.plm.core.base.domain.user membercreate_memberfor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.member membercreate_membermember_obj;
                global cn.ibizlab.plm.core.base.domain.user membercreate_memberselectdata;
                    global cn.ibizlab.plm.core.base.service.ImemberService memberservice;
        global cn.ibizlab.plm.core.base.service.ImemberService iBzSysMemberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "membercreate_memberbegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "membercreate_memberbindparam1"
            when
            then
                        update(membercreate_memberdefault);//更新fact中变量值
                        update(membercreate_memberfor_temp_obj);//更新fact中变量值
                        update(membercreate_membermember_obj);//更新fact中变量值
                        update(membercreate_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "membercreate_memberloopsubcall1"
            when
            then
                        update(membercreate_memberdefault);//更新fact中变量值
                        update(membercreate_memberfor_temp_obj);//更新fact中变量值
                        update(membercreate_membermember_obj);//更新fact中变量值
                        update(membercreate_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "membercreate_memberrenewparam1"
            when
            then
                        update(membercreate_memberdefault);//更新fact中变量值
                        update(membercreate_memberfor_temp_obj);//更新fact中变量值
                        update(membercreate_membermember_obj);//更新fact中变量值
                        update(membercreate_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[填充团队成员属性]
            rule "prepareparam1"
            ruleflow-group "membercreate_memberprepareparam1"
            when
            then
                            membercreate_membermember_obj.set("userid",membercreate_memberfor_temp_obj.get("id"));
                            membercreate_membermember_obj.set("jobname",membercreate_memberfor_temp_obj.get("title"));
                            membercreate_membermember_obj.set("ownertype","GROUP");
                            membercreate_membermember_obj.set("ownersubtype","GROUP");
                            membercreate_membermember_obj.set("name",membercreate_memberfor_temp_obj.get("displayname"));
                            membercreate_membermember_obj.set("ownerid",membercreate_memberdefault.get("ownerid"));
                        update(membercreate_memberdefault);//更新fact中变量值
                        update(membercreate_memberfor_temp_obj);//更新fact中变量值
                        update(membercreate_membermember_obj);//更新fact中变量值
                        update(membercreate_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[建立团队成员]
            rule "deaction1"
            ruleflow-group "membercreate_memberdeaction1"
            when
            then
                        memberservice.create(membercreate_membermember_obj);
                        update(membercreate_memberdefault);//更新fact中变量值
                        update(membercreate_memberfor_temp_obj);//更新fact中变量值
                        update(membercreate_membermember_obj);//更新fact中变量值
                        update(membercreate_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "membercreate_memberend1"
            when
            then
                        update(membercreate_memberdefault);//更新fact中变量值
                        update(membercreate_memberfor_temp_obj);//更新fact中变量值
                        update(membercreate_membermember_obj);//更新fact中变量值
                        update(membercreate_memberselectdata);//更新fact中变量值
            end