package cn.ibizlab.plm.base.logic.memberlogic.not_space_mmeber;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.member membernot_space_mmeberdefault;
                global cn.ibizlab.plm.core.base.domain.member membernot_space_mmebershared_page_member_filter;
                global cn.ibizlab.plm.core.base.domain.member membernot_space_mmebershared_page_members;
                global cn.ibizlab.plm.core.wiki.domain.space_member membernot_space_mmeberspace_member_filter;
                global cn.ibizlab.plm.core.wiki.domain.space_member membernot_space_mmeberspace_members;
                global cn.ibizlab.plm.core.base.domain.member membernot_space_mmeberuser_page;
                    global cn.ibizlab.plm.core.wiki.service.Ispace_memberService space_memberservice;
                    global cn.ibizlab.plm.core.base.service.ImemberService memberservice;
        global cn.ibizlab.plm.core.base.service.ImemberService iBzSysMemberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "membernot_space_mmeberbegin"
            when
            then
            end

            //逻辑处理节点[查询非空间成员]
            rule "debugparam1"
            ruleflow-group "membernot_space_mmeberdebugparam1"
            when
            then
                        update(membernot_space_mmeberdefault);//更新fact中变量值
                        update(membernot_space_mmebershared_page_member_filter);//更新fact中变量值
                        update(membernot_space_mmebershared_page_members);//更新fact中变量值
                        update(membernot_space_mmeberspace_member_filter);//更新fact中变量值
                        update(membernot_space_mmeberspace_members);//更新fact中变量值
                        update(membernot_space_mmeberuser_page);//更新fact中变量值
            end

            //逻辑处理节点[准备空间成员查询过滤器参数]
            rule "prepareparam1"
            ruleflow-group "membernot_space_mmeberprepareparam1"
            when
            then
                            membernot_space_mmeberspace_member_filter.set("n_space_id_eq",membernot_space_mmeberdefault.get("space_id"));
                            membernot_space_mmebershared_page_member_filter.set("n_owner_subtype_eq","SHARED");
                            membernot_space_mmebershared_page_member_filter.set("n_owner_id_eq",membernot_space_mmeberdefault.get("shared_page"));
                            membernot_space_mmebershared_page_member_filter.set("size","1000");
                            membernot_space_mmebershared_page_member_filter.set("n_owner_type_eq","PAGE");
                            membernot_space_mmeberspace_member_filter.set("size","1000");
                        update(membernot_space_mmeberdefault);//更新fact中变量值
                        update(membernot_space_mmebershared_page_member_filter);//更新fact中变量值
                        update(membernot_space_mmebershared_page_members);//更新fact中变量值
                        update(membernot_space_mmeberspace_member_filter);//更新fact中变量值
                        update(membernot_space_mmeberspace_members);//更新fact中变量值
                        update(membernot_space_mmeberuser_page);//更新fact中变量值
            end

            //逻辑处理节点[获取空间成员]
            rule "dedataset1"
            ruleflow-group "membernot_space_mmeberdedataset1"
            when
            then
                        update(membernot_space_mmeberdefault);//更新fact中变量值
                        update(membernot_space_mmebershared_page_member_filter);//更新fact中变量值
                        update(membernot_space_mmebershared_page_members);//更新fact中变量值
                        update(membernot_space_mmeberspace_member_filter);//更新fact中变量值
                        update(membernot_space_mmeberspace_members);//更新fact中变量值
                        update(membernot_space_mmeberuser_page);//更新fact中变量值
            end

            //逻辑处理节点[获取已添加的共享页面成员]
            rule "dedataset3"
            ruleflow-group "membernot_space_mmeberdedataset3"
            when
            then
                        update(membernot_space_mmeberdefault);//更新fact中变量值
                        update(membernot_space_mmebershared_page_member_filter);//更新fact中变量值
                        update(membernot_space_mmebershared_page_members);//更新fact中变量值
                        update(membernot_space_mmeberspace_member_filter);//更新fact中变量值
                        update(membernot_space_mmeberspace_members);//更新fact中变量值
                        update(membernot_space_mmeberuser_page);//更新fact中变量值
            end

            //逻辑处理节点[填充user过滤器ni参数]
            rule "rawsfcode1"
            ruleflow-group "membernot_space_mmeberrawsfcode1"
            when
            then
                        update(membernot_space_mmeberdefault);//更新fact中变量值
                        update(membernot_space_mmebershared_page_member_filter);//更新fact中变量值
                        update(membernot_space_mmebershared_page_members);//更新fact中变量值
                        update(membernot_space_mmeberspace_member_filter);//更新fact中变量值
                        update(membernot_space_mmeberspace_members);//更新fact中变量值
                        update(membernot_space_mmeberuser_page);//更新fact中变量值
            end

            //逻辑处理节点[获取用户]
            rule "dedataset2"
            ruleflow-group "membernot_space_mmeberdedataset2"
            when
            then
                        update(membernot_space_mmeberdefault);//更新fact中变量值
                        update(membernot_space_mmebershared_page_member_filter);//更新fact中变量值
                        update(membernot_space_mmebershared_page_members);//更新fact中变量值
                        update(membernot_space_mmeberspace_member_filter);//更新fact中变量值
                        update(membernot_space_mmeberspace_members);//更新fact中变量值
                        update(membernot_space_mmeberuser_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "membernot_space_mmeberend1"
            when
            then
                        update(membernot_space_mmeberdefault);//更新fact中变量值
                        update(membernot_space_mmebershared_page_member_filter);//更新fact中变量值
                        update(membernot_space_mmebershared_page_members);//更新fact中变量值
                        update(membernot_space_mmeberspace_member_filter);//更新fact中变量值
                        update(membernot_space_mmeberspace_members);//更新fact中变量值
                        update(membernot_space_mmeberuser_page);//更新fact中变量值
            end