package cn.ibizlab.plm.base.logic.memberlogic.resource_member;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.member memberresource_memberdefault;
                global cn.ibizlab.plm.core.base.domain.addon_resource memberresource_memberaddon_resource;
                global cn.ibizlab.plm.core.base.domain.member memberresource_membermember_list;
                global cn.ibizlab.plm.core.base.domain.member memberresource_membermember_page;
                    global cn.ibizlab.plm.core.base.service.Iaddon_resourceService addon_resourceservice;
        global cn.ibizlab.plm.core.base.service.ImemberService iBzSysMemberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "memberresource_memberbegin"
            when
            then
            end

            //逻辑处理节点[设置全局资源组件标识]
            rule "prepareparam1"
            ruleflow-group "memberresource_memberprepareparam1"
            when
            then
                            memberresource_memberaddon_resource.set("id",memberresource_memberdefault.get("addon_resource"));
                        update(memberresource_memberdefault);//更新fact中变量值
                        update(memberresource_memberaddon_resource);//更新fact中变量值
                        update(memberresource_membermember_list);//更新fact中变量值
                        update(memberresource_membermember_page);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "memberresource_memberbindparam1"
            when
            then
                        update(memberresource_memberdefault);//更新fact中变量值
                        update(memberresource_memberaddon_resource);//更新fact中变量值
                        update(memberresource_membermember_list);//更新fact中变量值
                        update(memberresource_membermember_page);//更新fact中变量值
            end

            //逻辑处理节点[获取资源组件]
            rule "deaction1"
            ruleflow-group "memberresource_memberdeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(addon_resourceservice.get(memberresource_memberaddon_resource.getId()),memberresource_memberaddon_resource);
                        update(memberresource_memberdefault);//更新fact中变量值
                        update(memberresource_memberaddon_resource);//更新fact中变量值
                        update(memberresource_membermember_list);//更新fact中变量值
                        update(memberresource_membermember_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "memberresource_memberend1"
            when
            then
                        update(memberresource_memberdefault);//更新fact中变量值
                        update(memberresource_memberaddon_resource);//更新fact中变量值
                        update(memberresource_membermember_list);//更新fact中变量值
                        update(memberresource_membermember_page);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode1"
            ruleflow-group "memberresource_memberrawsfcode1"
            when
            then
                        update(memberresource_memberdefault);//更新fact中变量值
                        update(memberresource_memberaddon_resource);//更新fact中变量值
                        update(memberresource_membermember_list);//更新fact中变量值
                        update(memberresource_membermember_page);//更新fact中变量值
            end