package cn.ibizlab.plm.projmgmt.logic.releaselogic.after_create;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.release releaseafter_createdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.stage releaseafter_createstage_filter;
                global cn.ibizlab.plm.core.projmgmt.domain.stage releaseafter_createstages;
                    global cn.ibizlab.plm.core.projmgmt.service.IstageService stageservice;
        global cn.ibizlab.plm.core.projmgmt.service.IreleaseService iBzSysReleaseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "releaseafter_createbegin"
            when
            then
            end

            //逻辑处理节点[获取全局发布阶段]
            rule "dedataset1"
            ruleflow-group "releaseafter_creatededataset1"
            when
            then
                        update(releaseafter_createdefault);//更新fact中变量值
                        update(releaseafter_createstage_filter);//更新fact中变量值
                        update(releaseafter_createstages);//更新fact中变量值
            end

            //逻辑处理节点[获取首发布阶段标识]
            rule "rawsqlcall1"
            ruleflow-group "releaseafter_createrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",releaseafter_createdefault.get("id"));
    String strSql="select id as first_stage_id from stage  where  RELEASE_ID is null order by `SEQUENCE` asc limit 1 ";
                        java.util.List<JSONObject> entities=iBzSysReleaseDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    releaseafter_createdefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(releaseafter_createdefault);//更新fact中变量值
                        update(releaseafter_createstage_filter);//更新fact中变量值
                        update(releaseafter_createstages);//更新fact中变量值
            end

            //逻辑处理节点[获取末发布阶段标识]
            rule "rawsqlcall2"
            ruleflow-group "releaseafter_createrawsqlcall2"
            when
            then
    Map param =new HashMap();
        param.put("param0",releaseafter_createdefault.get("id"));
    String strSql="select id as last_stage_id from stage  where  RELEASE_ID is null order by `SEQUENCE` desc limit 1 ";
                        java.util.List<JSONObject> entities=iBzSysReleaseDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    releaseafter_createdefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(releaseafter_createdefault);//更新fact中变量值
                        update(releaseafter_createstage_filter);//更新fact中变量值
                        update(releaseafter_createstages);//更新fact中变量值
            end

            //逻辑处理节点[根据全局预定义阶段生成发布阶段]
            rule "rawsfcode1"
            ruleflow-group "releaseafter_createrawsfcode1"
            when
            then
                        update(releaseafter_createdefault);//更新fact中变量值
                        update(releaseafter_createstage_filter);//更新fact中变量值
                        update(releaseafter_createstages);//更新fact中变量值
            end

            //逻辑处理节点[同步默认首阶段至初始阶段]
            rule "rawsqlcall3"
            ruleflow-group "releaseafter_createrawsqlcall3"
            when
            then
    Map param =new HashMap();
        param.put("param0",releaseafter_createdefault.get("id"));
    String strSql="update `project_release` t1, `stage` t2  set t1.`status` = t2.`id` where t1.`id` = #{et.param0} and t1.`id` = t2.`RELEASE_ID` and t2.`is_current` = 1";
                        iBzSysReleaseDefaultService.execute(strSql,param);//SQL调用
                        update(releaseafter_createdefault);//更新fact中变量值
                        update(releaseafter_createstage_filter);//更新fact中变量值
                        update(releaseafter_createstages);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "releaseafter_createend1"
            when
            then
                        update(releaseafter_createdefault);//更新fact中变量值
                        update(releaseafter_createstage_filter);//更新fact中变量值
                        update(releaseafter_createstages);//更新fact中变量值
            end