package cn.ibizlab.plm.projmgmt.logic.releaselogic.del_relation;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.release releasedel_relationdefault;
                global cn.ibizlab.plm.core.base.domain.relation releasedel_relationforward_relation_obj;
                global cn.ibizlab.plm.core.base.domain.relation releasedel_relationreverse_relation_obj;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.projmgmt.service.IreleaseService iBzSysReleaseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "releasedel_relationbegin"
            when
            then
            end

            //逻辑处理节点[填充正反关联对象的主要关联属性]
            rule "prepareparam1"
            ruleflow-group "releasedel_relationprepareparam1"
            when
            then
                            releasedel_relationforward_relation_obj.set("principalid",releasedel_relationdefault.get("principal_id"));
                            releasedel_relationreverse_relation_obj.set("targetid",releasedel_relationdefault.get("principal_id"));
                            releasedel_relationreverse_relation_obj.set("principalid",releasedel_relationdefault.get("id"));
                            releasedel_relationforward_relation_obj.set("targetid",releasedel_relationdefault.get("id"));
                        update(releasedel_relationdefault);//更新fact中变量值
                        update(releasedel_relationforward_relation_obj);//更新fact中变量值
                        update(releasedel_relationreverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[拼接关联对象的主键]
            rule "rawsfcode1"
            ruleflow-group "releasedel_relationrawsfcode1"
            when
            then
                        update(releasedel_relationdefault);//更新fact中变量值
                        update(releasedel_relationforward_relation_obj);//更新fact中变量值
                        update(releasedel_relationreverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[删除正向关联]
            rule "deaction2"
            ruleflow-group "releasedel_relationdeaction2"
            when
            then
                        relationservice.remove(releasedel_relationforward_relation_obj.getId());
                        update(releasedel_relationdefault);//更新fact中变量值
                        update(releasedel_relationforward_relation_obj);//更新fact中变量值
                        update(releasedel_relationreverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[删除反向关联]
            rule "deaction3"
            ruleflow-group "releasedel_relationdeaction3"
            when
            then
                        relationservice.remove(releasedel_relationreverse_relation_obj.getId());
                        update(releasedel_relationdefault);//更新fact中变量值
                        update(releasedel_relationforward_relation_obj);//更新fact中变量值
                        update(releasedel_relationreverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "releasedel_relationend1"
            when
            then
                        update(releasedel_relationdefault);//更新fact中变量值
                        update(releasedel_relationforward_relation_obj);//更新fact中变量值
                        update(releasedel_relationreverse_relation_obj);//更新fact中变量值
            end