package cn.ibizlab.plm.projmgmt.logic.releaselogic.fill_categories_name;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.release releasefill_categories_namedefault;
        global cn.ibizlab.plm.core.projmgmt.service.IreleaseService iBzSysReleaseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "releasefill_categories_namebegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "releasefill_categories_nameend1"
            when
            then
                        update(releasefill_categories_namedefault);//更新fact中变量值
            end

            //逻辑处理节点[类别转换]
            rule "prepareparam1"
            ruleflow-group "releasefill_categories_nameprepareparam1"
            when
            then
                            releasefill_categories_namedefault.set("categoriesname",releasefill_categories_namedefault.get("categories"));
                        update(releasefill_categories_namedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "releasefill_categories_nameend2"
            when
            then
                        update(releasefill_categories_namedefault);//更新fact中变量值
            end