package cn.ibizlab.plm.testmgmt.logic.review_contentlogic.change_review_state;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content review_contentchange_review_statedefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea review_contentchange_review_stateidea;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case review_contentchange_review_statetest_case;
                    global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService test_caseservice;
                    global cn.ibizlab.plm.core.prodmgmt.service.IideaService ideaservice;
        global cn.ibizlab.plm.core.testmgmt.service.Ireview_contentService iBzSysReview_contentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "review_contentchange_review_statebegin"
            when
            then
            end

            //逻辑处理节点[设置评审状态为通过]
            rule "prepareparam2"
            ruleflow-group "review_contentchange_review_stateprepareparam2"
            when
            then
                            review_contentchange_review_statetest_case.set("reviewresultstate","3");
                        update(review_contentchange_review_statedefault);//更新fact中变量值
                        update(review_contentchange_review_stateidea);//更新fact中变量值
                        update(review_contentchange_review_statetest_case);//更新fact中变量值
            end

            //逻辑处理节点[更新测试用例]
            rule "deaction1"
            ruleflow-group "review_contentchange_review_statedeaction1"
            when
            then
                        test_caseservice.update(review_contentchange_review_statetest_case);
                        update(review_contentchange_review_statedefault);//更新fact中变量值
                        update(review_contentchange_review_stateidea);//更新fact中变量值
                        update(review_contentchange_review_statetest_case);//更新fact中变量值
            end

            //逻辑处理节点[获取测试用例id]
            rule "prepareparam1"
            ruleflow-group "review_contentchange_review_stateprepareparam1"
            when
            then
                            review_contentchange_review_statetest_case.set("id",review_contentchange_review_statedefault.get("targetid"));
                        update(review_contentchange_review_statedefault);//更新fact中变量值
                        update(review_contentchange_review_stateidea);//更新fact中变量值
                        update(review_contentchange_review_statetest_case);//更新fact中变量值
            end

            //逻辑处理节点[设置评审状态为拒绝]
            rule "prepareparam3"
            ruleflow-group "review_contentchange_review_stateprepareparam3"
            when
            then
                            review_contentchange_review_statetest_case.set("reviewresultstate","4");
                        update(review_contentchange_review_statedefault);//更新fact中变量值
                        update(review_contentchange_review_stateidea);//更新fact中变量值
                        update(review_contentchange_review_statetest_case);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "review_contentchange_review_stateend1"
            when
            then
                        update(review_contentchange_review_statedefault);//更新fact中变量值
                        update(review_contentchange_review_stateidea);//更新fact中变量值
                        update(review_contentchange_review_statetest_case);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "review_contentchange_review_statedebugparam1"
            when
            then
                        update(review_contentchange_review_statedefault);//更新fact中变量值
                        update(review_contentchange_review_stateidea);//更新fact中变量值
                        update(review_contentchange_review_statetest_case);//更新fact中变量值
            end

            //逻辑处理节点[设置评审状态为通过]
            rule "prepareparam5"
            ruleflow-group "review_contentchange_review_stateprepareparam5"
            when
            then
                            review_contentchange_review_stateidea.set("reviewresultstate","3");
                        update(review_contentchange_review_statedefault);//更新fact中变量值
                        update(review_contentchange_review_stateidea);//更新fact中变量值
                        update(review_contentchange_review_statetest_case);//更新fact中变量值
            end

            //逻辑处理节点[获取产品需求id]
            rule "prepareparam4"
            ruleflow-group "review_contentchange_review_stateprepareparam4"
            when
            then
                            review_contentchange_review_stateidea.set("id",review_contentchange_review_statedefault.get("targetid"));
                        update(review_contentchange_review_statedefault);//更新fact中变量值
                        update(review_contentchange_review_stateidea);//更新fact中变量值
                        update(review_contentchange_review_statetest_case);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction2"
            ruleflow-group "review_contentchange_review_statedeaction2"
            when
            then
                        ideaservice.update(review_contentchange_review_stateidea);
                        update(review_contentchange_review_statedefault);//更新fact中变量值
                        update(review_contentchange_review_stateidea);//更新fact中变量值
                        update(review_contentchange_review_statetest_case);//更新fact中变量值
            end

            //逻辑处理节点[设置评审状态为拒绝]
            rule "prepareparam6"
            ruleflow-group "review_contentchange_review_stateprepareparam6"
            when
            then
                            review_contentchange_review_stateidea.set("reviewresultstate","4");
                        update(review_contentchange_review_statedefault);//更新fact中变量值
                        update(review_contentchange_review_stateidea);//更新fact中变量值
                        update(review_contentchange_review_statetest_case);//更新fact中变量值
            end