package cn.ibizlab.plm.testmgmt.logic.review_contentlogic.create_review_data;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content review_contentcreate_review_datadefault;
                global java.util.Map review_contentcreate_review_datafor_temp_obj;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content review_contentcreate_review_datareview_content_obj;
                global java.util.Map review_contentcreate_review_dataselecteddata;
                    global cn.ibizlab.plm.core.testmgmt.service.Ireview_contentService review_contentservice;
        global cn.ibizlab.plm.core.testmgmt.service.Ireview_contentService iBzSysReview_contentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "review_contentcreate_review_databegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "review_contentcreate_review_databindparam1"
            when
            then
                        update(review_contentcreate_review_datadefault);//更新fact中变量值
                        update(review_contentcreate_review_datafor_temp_obj);//更新fact中变量值
                        update(review_contentcreate_review_datareview_content_obj);//更新fact中变量值
                        update(review_contentcreate_review_dataselecteddata);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "review_contentcreate_review_dataloopsubcall1"
            when
            then
                        update(review_contentcreate_review_datadefault);//更新fact中变量值
                        update(review_contentcreate_review_datafor_temp_obj);//更新fact中变量值
                        update(review_contentcreate_review_datareview_content_obj);//更新fact中变量值
                        update(review_contentcreate_review_dataselecteddata);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "review_contentcreate_review_datarenewparam1"
            when
            then
                        update(review_contentcreate_review_datadefault);//更新fact中变量值
                        update(review_contentcreate_review_datafor_temp_obj);//更新fact中变量值
                        update(review_contentcreate_review_datareview_content_obj);//更新fact中变量值
                        update(review_contentcreate_review_dataselecteddata);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "review_contentcreate_review_dataprepareparam1"
            when
            then
                        update(review_contentcreate_review_datadefault);//更新fact中变量值
                        update(review_contentcreate_review_datafor_temp_obj);//更新fact中变量值
                        update(review_contentcreate_review_datareview_content_obj);//更新fact中变量值
                        update(review_contentcreate_review_dataselecteddata);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "review_contentcreate_review_dataend1"
            when
            then
                        update(review_contentcreate_review_datadefault);//更新fact中变量值
                        update(review_contentcreate_review_datafor_temp_obj);//更新fact中变量值
                        update(review_contentcreate_review_datareview_content_obj);//更新fact中变量值
                        update(review_contentcreate_review_dataselecteddata);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "review_contentcreate_review_datadebugparam1"
            when
            then
                        update(review_contentcreate_review_datadefault);//更新fact中变量值
                        update(review_contentcreate_review_datafor_temp_obj);//更新fact中变量值
                        update(review_contentcreate_review_datareview_content_obj);//更新fact中变量值
                        update(review_contentcreate_review_dataselecteddata);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "review_contentcreate_review_datadeaction1"
            when
            then
                        review_contentservice.create(review_contentcreate_review_datareview_content_obj);
                        update(review_contentcreate_review_datadefault);//更新fact中变量值
                        update(review_contentcreate_review_datafor_temp_obj);//更新fact中变量值
                        update(review_contentcreate_review_datareview_content_obj);//更新fact中变量值
                        update(review_contentcreate_review_dataselecteddata);//更新fact中变量值
            end