package cn.ibizlab.plm.testmgmt.logic.review_contentlogic.review_content_total;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content review_contentreview_content_totaldefault;
                global java.util.Map review_contentreview_content_totalresult;
        global cn.ibizlab.plm.core.testmgmt.service.Ireview_contentService iBzSysReview_contentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "review_contentreview_content_totalbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "review_contentreview_content_totalend1"
            when
            then
                        update(review_contentreview_content_totaldefault);//更新fact中变量值
                        update(review_contentreview_content_totalresult);//更新fact中变量值
            end

            //逻辑处理节点[查询评审结果总条数与已评审条数]
            rule "rawsqlcall1"
            ruleflow-group "review_contentreview_content_totalrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",review_contentreview_content_totaldefault.get("id"));
        param.put("param1",review_contentreview_content_totaldefault.get("id"));
    String strSql="SELECT     query1.count1 AS total,     query2.count2 AS total_already,     (CONVERT(query2.count2, DECIMAL) / query1.count1 * 100) AS schedule FROM     (SELECT COUNT(1) AS count1      FROM review rv               LEFT JOIN relation re ON re.PRINCIPAL_ID = rv.ID AND re.PRINCIPAL_TYPE = 'REVIEW'      WHERE rv.ID = #{et.param0}) AS query1,      (SELECT COUNT(*) AS count2      FROM review rv               INNER JOIN relation re ON re.PRINCIPAL_ID = rv.ID AND re.PRINCIPAL_TYPE = 'REVIEW'               INNER JOIN review_content_extend rc ON re.ID = rc.ID AND rc.review_result = 'pass'      WHERE rv.ID = #{et.param1}) AS query2;";
                        java.util.List<JSONObject> entities=iBzSysReview_contentDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                review_contentreview_content_totalresult.putAll(entity);
                            }
                        update(review_contentreview_content_totaldefault);//更新fact中变量值
                        update(review_contentreview_content_totalresult);//更新fact中变量值
            end