package cn.ibizlab.plm.testmgmt.logic.review_contentlogic.submit_review;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content review_contentsubmit_reviewdefault;
                global cn.ibizlab.plm.core.base.domain.relation review_contentsubmit_reviewfor_reltion;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea review_contentsubmit_reviewidea;
                global cn.ibizlab.plm.core.base.domain.relation review_contentsubmit_reviewrelation_page;
                global cn.ibizlab.plm.core.base.domain.relation review_contentsubmit_reviewreltion_filter;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content review_contentsubmit_reviewreview_content;
                global cn.ibizlab.plm.core.testmgmt.domain.review review_contentsubmit_reviewreview_detail;
                global java.util.Map review_contentsubmit_reviewreviewer_list;
                global java.util.Map review_contentsubmit_reviewreviewer_temp;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage review_contentsubmit_reviewstage;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage review_contentsubmit_reviewstages;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case review_contentsubmit_reviewtest_case;
                    global cn.ibizlab.plm.core.testmgmt.service.IreviewService reviewservice;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
                    global cn.ibizlab.plm.core.prodmgmt.service.IideaService ideaservice;
                    global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService test_caseservice;
        global cn.ibizlab.plm.core.testmgmt.service.Ireview_contentService iBzSysReview_contentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "review_contentsubmit_reviewbegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "review_contentsubmit_reviewbindparam1"
            when
            then
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[获取评审详情]
            rule "deaction4"
            ruleflow-group "review_contentsubmit_reviewdeaction4"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(reviewservice.get(review_contentsubmit_reviewreview_detail.getId()),review_contentsubmit_reviewreview_detail);
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam2"
            ruleflow-group "review_contentsubmit_reviewdebugparam2"
            when
            then
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[设置提交时间]
            rule "rawsfcode1"
            ruleflow-group "review_contentsubmit_reviewrawsfcode1"
            when
            then
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[通知第一评审人]
            rule "denotify1"
            ruleflow-group "review_contentsubmit_reviewdenotify1"
            when
            then
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall2"
            ruleflow-group "review_contentsubmit_reviewloopsubcall2"
            when
            then
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[设置提交人、状态]
            rule "prepareparam1"
            ruleflow-group "review_contentsubmit_reviewprepareparam1"
            when
            then
                                review_contentsubmit_reviewreview_detail.set("submittername",curuser.getSessionParams().get("srfpersonname"));
                                review_contentsubmit_reviewreview_detail.set("submitterid",curuser.getSessionParams().get("srfpersonid"));
                            review_contentsubmit_reviewreview_detail.set("state","20");
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[设置阶段的状态]
            rule "prepareparam2"
            ruleflow-group "review_contentsubmit_reviewprepareparam2"
            when
            then
                            review_contentsubmit_reviewstages.set("",review_contentsubmit_reviewreview_detail.get("stage"));
                            review_contentsubmit_reviewstage.set("",review_contentsubmit_reviewstages.get("0"));
                            review_contentsubmit_reviewstage.set("stagestate","20");
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[设置关系过滤器参数]
            rule "prepareparam3"
            ruleflow-group "review_contentsubmit_reviewprepareparam3"
            when
            then
                            review_contentsubmit_reviewreltion_filter.set("n_principal_id_eq",review_contentsubmit_reviewdefault.get("principalid"));
                            review_contentsubmit_reviewreltion_filter.set("n_principal_type_eq","REVIEW");
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[更新评审]
            rule "deaction1"
            ruleflow-group "review_contentsubmit_reviewdeaction1"
            when
            then
                        reviewservice.update(review_contentsubmit_reviewreview_detail);
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[获取关系数据集]
            rule "dedataset1"
            ruleflow-group "review_contentsubmit_reviewdedataset1"
            when
            then
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[获取评审id]
            rule "prepareparam6"
            ruleflow-group "review_contentsubmit_reviewprepareparam6"
            when
            then
                            review_contentsubmit_reviewreview_detail.set("id",review_contentsubmit_reviewdefault.get("principalid"));
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "review_contentsubmit_reviewend1"
            when
            then
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "review_contentsubmit_reviewloopsubcall1"
            when
            then
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[评审内容为空]
            rule "throwexception1"
            ruleflow-group "review_contentsubmit_reviewthrowexception1"
            when
            then
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "review_contentsubmit_reviewdebugparam1"
            when
            then
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[获取需求id]
            rule "prepareparam7"
            ruleflow-group "review_contentsubmit_reviewprepareparam7"
            when
            then
                            review_contentsubmit_reviewidea.set("id",review_contentsubmit_reviewfor_reltion.get("targetid"));
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[获取测试用例id]
            rule "prepareparam4"
            ruleflow-group "review_contentsubmit_reviewprepareparam4"
            when
            then
                            review_contentsubmit_reviewtest_case.set("id",review_contentsubmit_reviewfor_reltion.get("targetid"));
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[获取产品需求详情]
            rule "deaction5"
            ruleflow-group "review_contentsubmit_reviewdeaction5"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(ideaservice.get(review_contentsubmit_reviewidea.getId()),review_contentsubmit_reviewidea);
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[获取测试用例详情]
            rule "deaction2"
            ruleflow-group "review_contentsubmit_reviewdeaction2"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(test_caseservice.get(review_contentsubmit_reviewtest_case.getId()),review_contentsubmit_reviewtest_case);
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[设置产品需求评审状态]
            rule "prepareparam8"
            ruleflow-group "review_contentsubmit_reviewprepareparam8"
            when
            then
                            review_contentsubmit_reviewidea.set("reviewresultstate","2");
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[设置测试用例评审状态]
            rule "prepareparam5"
            ruleflow-group "review_contentsubmit_reviewprepareparam5"
            when
            then
                            review_contentsubmit_reviewtest_case.set("reviewresultstate","2");
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[更新产品需求]
            rule "deaction6"
            ruleflow-group "review_contentsubmit_reviewdeaction6"
            when
            then
                        ideaservice.update(review_contentsubmit_reviewidea);
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[更新测试用例]
            rule "deaction3"
            ruleflow-group "review_contentsubmit_reviewdeaction3"
            when
            then
                        test_caseservice.update(review_contentsubmit_reviewtest_case);
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[重置参数]
            rule "resetparam2"
            ruleflow-group "review_contentsubmit_reviewresetparam2"
            when
            then
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam9"
            ruleflow-group "review_contentsubmit_reviewprepareparam9"
            when
            then
                            review_contentsubmit_reviewreview_detail.set("reviewer",review_contentsubmit_reviewreviewer_temp.get("reviewer"));
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[重置测试用例参数]
            rule "resetparam1"
            ruleflow-group "review_contentsubmit_reviewresetparam1"
            when
            then
                        update(review_contentsubmit_reviewdefault);//更新fact中变量值
                        update(review_contentsubmit_reviewfor_reltion);//更新fact中变量值
                        update(review_contentsubmit_reviewidea);//更新fact中变量值
                        update(review_contentsubmit_reviewrelation_page);//更新fact中变量值
                        update(review_contentsubmit_reviewreltion_filter);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_content);//更新fact中变量值
                        update(review_contentsubmit_reviewreview_detail);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_list);//更新fact中变量值
                        update(review_contentsubmit_reviewreviewer_temp);//更新fact中变量值
                        update(review_contentsubmit_reviewstage);//更新fact中变量值
                        update(review_contentsubmit_reviewstages);//更新fact中变量值
                        update(review_contentsubmit_reviewtest_case);//更新fact中变量值
            end