package cn.ibizlab.plm.prodmgmt.logic.idealogic.archive;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideaarchivedefault;
                global java.util.Map ideaarchiveid;
                global java.util.Map ideaarchiveids;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideaarchivetemp_obj;
                    global cn.ibizlab.plm.core.prodmgmt.service.IideaService ideaservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IideaService iBzSysIdeaDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ideaarchivebegin"
            when
            then
            end

            //逻辑处理节点[设置需求的归档属性值]
            rule "prepareparam1"
            ruleflow-group "ideaarchiveprepareparam1"
            when
            then
                            ideaarchivedefault.set("isarchived","1");
                        update(ideaarchivedefault);//更新fact中变量值
                        update(ideaarchiveid);//更新fact中变量值
                        update(ideaarchiveids);//更新fact中变量值
                        update(ideaarchivetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[修改需求的归档属性]
            rule "deaction1"
            ruleflow-group "ideaarchivedeaction1"
            when
            then
                        ideaservice.update(ideaarchivedefault);
                        update(ideaarchivedefault);//更新fact中变量值
                        update(ideaarchiveid);//更新fact中变量值
                        update(ideaarchiveids);//更新fact中变量值
                        update(ideaarchivetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ideaarchiveend1"
            when
            then
                        update(ideaarchivedefault);//更新fact中变量值
                        update(ideaarchiveid);//更新fact中变量值
                        update(ideaarchiveids);//更新fact中变量值
                        update(ideaarchivetemp_obj);//更新fact中变量值
            end