package cn.ibizlab.plm.prodmgmt.logic.idealogic.get_customer_score;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideaget_customer_scoredefault;
                global cn.ibizlab.plm.core.base.domain.relation ideaget_customer_scorefilter;
                global cn.ibizlab.plm.core.base.domain.relation ideaget_customer_scorerelation_page;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideaget_customer_scoreresult;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IideaService iBzSysIdeaDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ideaget_customer_scorebegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ideaget_customer_scoreend1"
            when
            then
                        update(ideaget_customer_scoredefault);//更新fact中变量值
                        update(ideaget_customer_scorefilter);//更新fact中变量值
                        update(ideaget_customer_scorerelation_page);//更新fact中变量值
                        update(ideaget_customer_scoreresult);//更新fact中变量值
            end

            //逻辑处理节点[设置过滤器]
            rule "prepareparam1"
            ruleflow-group "ideaget_customer_scoreprepareparam1"
            when
            then
                            ideaget_customer_scorefilter.set("n_principal_id_eq",ideaget_customer_scoredefault.get("id"));
                            ideaget_customer_scorefilter.set("n_target_type_eq","customer");
                        update(ideaget_customer_scoredefault);//更新fact中变量值
                        update(ideaget_customer_scorefilter);//更新fact中变量值
                        update(ideaget_customer_scorerelation_page);//更新fact中变量值
                        update(ideaget_customer_scoreresult);//更新fact中变量值
            end

            //逻辑处理节点[获取需求关联的客户]
            rule "dedataset1"
            ruleflow-group "ideaget_customer_scorededataset1"
            when
            then
                        update(ideaget_customer_scoredefault);//更新fact中变量值
                        update(ideaget_customer_scorefilter);//更新fact中变量值
                        update(ideaget_customer_scorerelation_page);//更新fact中变量值
                        update(ideaget_customer_scoreresult);//更新fact中变量值
            end

            //逻辑处理节点[计算分数]
            rule "rawsfcode1"
            ruleflow-group "ideaget_customer_scorerawsfcode1"
            when
            then
                        update(ideaget_customer_scoredefault);//更新fact中变量值
                        update(ideaget_customer_scorefilter);//更新fact中变量值
                        update(ideaget_customer_scorerelation_page);//更新fact中变量值
                        update(ideaget_customer_scoreresult);//更新fact中变量值
            end