package cn.ibizlab.plm.prodmgmt.logic.idealogic.idea_category;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideaidea_categorydefault;
                global cn.ibizlab.plm.core.base.domain.category ideaidea_categorycategory;
                    global cn.ibizlab.plm.core.base.service.IcategoryService categoryservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IideaService iBzSysIdeaDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ideaidea_categorybegin"
            when
            then
            end

            //逻辑处理节点[设置category_id]
            rule "prepareparam1"
            ruleflow-group "ideaidea_categoryprepareparam1"
            when
            then
                            ideaidea_categorycategory.set("id",ideaidea_categorydefault.get("categoryid"));
                        update(ideaidea_categorydefault);//更新fact中变量值
                        update(ideaidea_categorycategory);//更新fact中变量值
            end

            //逻辑处理节点[获取category]
            rule "deaction1"
            ruleflow-group "ideaidea_categorydeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(categoryservice.get(ideaidea_categorycategory.getId()),ideaidea_categorycategory);
                        update(ideaidea_categorydefault);//更新fact中变量值
                        update(ideaidea_categorycategory);//更新fact中变量值
            end

            //逻辑处理节点[设置category_name]
            rule "prepareparam2"
            ruleflow-group "ideaidea_categoryprepareparam2"
            when
            then
                            ideaidea_categorydefault.set("categoryname",ideaidea_categorycategory.get("name"));
                        update(ideaidea_categorydefault);//更新fact中变量值
                        update(ideaidea_categorycategory);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ideaidea_categoryend1"
            when
            then
                        update(ideaidea_categorydefault);//更新fact中变量值
                        update(ideaidea_categorycategory);//更新fact中变量值
            end