package cn.ibizlab.plm.prodmgmt.logic.idealogic.plan_track_data;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideaplan_track_datadefault;
                global java.util.Map ideaplan_track_database_filter;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideaplan_track_dataidea;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideaplan_track_datapage_ideas;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case ideaplan_track_datare_page_case;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideaplan_track_datare_page_idea;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item ideaplan_track_datare_page_item;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket ideaplan_track_datare_page_ticket;
                global java.util.Map ideaplan_track_dataresult;
                    global cn.ibizlab.plm.core.prodmgmt.service.IideaService ideaservice;
                    global cn.ibizlab.plm.core.prodmgmt.service.IticketService ticketservice;
                    global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService test_caseservice;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IideaService iBzSysIdeaDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ideaplan_track_databegin"
            when
            then
            end

            //逻辑处理节点[获取所有需求]
            rule "dedataset1"
            ruleflow-group "ideaplan_track_datadedataset1"
            when
            then
                        update(ideaplan_track_datadefault);//更新fact中变量值
                        update(ideaplan_track_database_filter);//更新fact中变量值
                        update(ideaplan_track_dataidea);//更新fact中变量值
                        update(ideaplan_track_datapage_ideas);//更新fact中变量值
                        update(ideaplan_track_datare_page_case);//更新fact中变量值
                        update(ideaplan_track_datare_page_idea);//更新fact中变量值
                        update(ideaplan_track_datare_page_item);//更新fact中变量值
                        update(ideaplan_track_datare_page_ticket);//更新fact中变量值
                        update(ideaplan_track_dataresult);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ideaplan_track_dataend1"
            when
            then
                        update(ideaplan_track_datadefault);//更新fact中变量值
                        update(ideaplan_track_database_filter);//更新fact中变量值
                        update(ideaplan_track_dataidea);//更新fact中变量值
                        update(ideaplan_track_datapage_ideas);//更新fact中变量值
                        update(ideaplan_track_datare_page_case);//更新fact中变量值
                        update(ideaplan_track_datare_page_idea);//更新fact中变量值
                        update(ideaplan_track_datare_page_item);//更新fact中变量值
                        update(ideaplan_track_datare_page_ticket);//更新fact中变量值
                        update(ideaplan_track_dataresult);//更新fact中变量值
            end

            //逻辑处理节点[循环所有的需求]
            rule "loopsubcall1"
            ruleflow-group "ideaplan_track_dataloopsubcall1"
            when
            then
                        update(ideaplan_track_datadefault);//更新fact中变量值
                        update(ideaplan_track_database_filter);//更新fact中变量值
                        update(ideaplan_track_dataidea);//更新fact中变量值
                        update(ideaplan_track_datapage_ideas);//更新fact中变量值
                        update(ideaplan_track_datare_page_case);//更新fact中变量值
                        update(ideaplan_track_datare_page_idea);//更新fact中变量值
                        update(ideaplan_track_datare_page_item);//更新fact中变量值
                        update(ideaplan_track_datare_page_ticket);//更新fact中变量值
                        update(ideaplan_track_dataresult);//更新fact中变量值
            end

            //逻辑处理节点[设置基础过滤器]
            rule "prepareparam2"
            ruleflow-group "ideaplan_track_dataprepareparam2"
            when
            then
                            ideaplan_track_database_filter.set("principal_id",ideaplan_track_dataidea.get("id"));
                        update(ideaplan_track_datadefault);//更新fact中变量值
                        update(ideaplan_track_database_filter);//更新fact中变量值
                        update(ideaplan_track_dataidea);//更新fact中变量值
                        update(ideaplan_track_datapage_ideas);//更新fact中变量值
                        update(ideaplan_track_datare_page_case);//更新fact中变量值
                        update(ideaplan_track_datare_page_idea);//更新fact中变量值
                        update(ideaplan_track_datare_page_item);//更新fact中变量值
                        update(ideaplan_track_datare_page_ticket);//更新fact中变量值
                        update(ideaplan_track_dataresult);//更新fact中变量值
            end

            //逻辑处理节点[获取关联需求]
            rule "dedataset2"
            ruleflow-group "ideaplan_track_datadedataset2"
            when
            then
                        update(ideaplan_track_datadefault);//更新fact中变量值
                        update(ideaplan_track_database_filter);//更新fact中变量值
                        update(ideaplan_track_dataidea);//更新fact中变量值
                        update(ideaplan_track_datapage_ideas);//更新fact中变量值
                        update(ideaplan_track_datare_page_case);//更新fact中变量值
                        update(ideaplan_track_datare_page_idea);//更新fact中变量值
                        update(ideaplan_track_datare_page_item);//更新fact中变量值
                        update(ideaplan_track_datare_page_ticket);//更新fact中变量值
                        update(ideaplan_track_dataresult);//更新fact中变量值
            end

            //逻辑处理节点[获取关联工单]
            rule "dedataset4"
            ruleflow-group "ideaplan_track_datadedataset4"
            when
            then
                        update(ideaplan_track_datadefault);//更新fact中变量值
                        update(ideaplan_track_database_filter);//更新fact中变量值
                        update(ideaplan_track_dataidea);//更新fact中变量值
                        update(ideaplan_track_datapage_ideas);//更新fact中变量值
                        update(ideaplan_track_datare_page_case);//更新fact中变量值
                        update(ideaplan_track_datare_page_idea);//更新fact中变量值
                        update(ideaplan_track_datare_page_item);//更新fact中变量值
                        update(ideaplan_track_datare_page_ticket);//更新fact中变量值
                        update(ideaplan_track_dataresult);//更新fact中变量值
            end

            //逻辑处理节点[获取关联测试用例]
            rule "dedataset5"
            ruleflow-group "ideaplan_track_datadedataset5"
            when
            then
                        update(ideaplan_track_datadefault);//更新fact中变量值
                        update(ideaplan_track_database_filter);//更新fact中变量值
                        update(ideaplan_track_dataidea);//更新fact中变量值
                        update(ideaplan_track_datapage_ideas);//更新fact中变量值
                        update(ideaplan_track_datare_page_case);//更新fact中变量值
                        update(ideaplan_track_datare_page_idea);//更新fact中变量值
                        update(ideaplan_track_datare_page_item);//更新fact中变量值
                        update(ideaplan_track_datare_page_ticket);//更新fact中变量值
                        update(ideaplan_track_dataresult);//更新fact中变量值
            end

            //逻辑处理节点[组装数据]
            rule "prepareparam1"
            ruleflow-group "ideaplan_track_dataprepareparam1"
            when
            then
                            ideaplan_track_dataidea.set("re_idea",ideaplan_track_datare_page_idea.get(""));
                            ideaplan_track_dataidea.set("idea_sum",ideaplan_track_datare_page_idea.get("size"));
                            ideaplan_track_dataidea.set("work_item_sum",ideaplan_track_datare_page_item.get("size"));
                            ideaplan_track_dataidea.set("ticket_sum",ideaplan_track_datare_page_ticket.get("size"));
                            ideaplan_track_dataidea.set("test_case_sum",ideaplan_track_datare_page_case.get("size"));
                            ideaplan_track_dataidea.set("re_item",ideaplan_track_datare_page_item.get(""));
                            ideaplan_track_dataidea.set("re_case",ideaplan_track_datare_page_case.get(""));
                            ideaplan_track_dataidea.set("re_ticket",ideaplan_track_datare_page_ticket.get(""));
                        update(ideaplan_track_datadefault);//更新fact中变量值
                        update(ideaplan_track_database_filter);//更新fact中变量值
                        update(ideaplan_track_dataidea);//更新fact中变量值
                        update(ideaplan_track_datapage_ideas);//更新fact中变量值
                        update(ideaplan_track_datare_page_case);//更新fact中变量值
                        update(ideaplan_track_datare_page_idea);//更新fact中变量值
                        update(ideaplan_track_datare_page_item);//更新fact中变量值
                        update(ideaplan_track_datare_page_ticket);//更新fact中变量值
                        update(ideaplan_track_dataresult);//更新fact中变量值
            end

            //逻辑处理节点[附加到数组参数]
            rule "appendparam1"
            ruleflow-group "ideaplan_track_dataappendparam1"
            when
            then
                        update(ideaplan_track_datadefault);//更新fact中变量值
                        update(ideaplan_track_database_filter);//更新fact中变量值
                        update(ideaplan_track_dataidea);//更新fact中变量值
                        update(ideaplan_track_datapage_ideas);//更新fact中变量值
                        update(ideaplan_track_datare_page_case);//更新fact中变量值
                        update(ideaplan_track_datare_page_idea);//更新fact中变量值
                        update(ideaplan_track_datare_page_item);//更新fact中变量值
                        update(ideaplan_track_datare_page_ticket);//更新fact中变量值
                        update(ideaplan_track_dataresult);//更新fact中变量值
            end

            //逻辑处理节点[获取关联工作项]
            rule "dedataset3"
            ruleflow-group "ideaplan_track_datadedataset3"
            when
            then
                        update(ideaplan_track_datadefault);//更新fact中变量值
                        update(ideaplan_track_database_filter);//更新fact中变量值
                        update(ideaplan_track_dataidea);//更新fact中变量值
                        update(ideaplan_track_datapage_ideas);//更新fact中变量值
                        update(ideaplan_track_datare_page_case);//更新fact中变量值
                        update(ideaplan_track_datare_page_idea);//更新fact中变量值
                        update(ideaplan_track_datare_page_item);//更新fact中变量值
                        update(ideaplan_track_datare_page_ticket);//更新fact中变量值
                        update(ideaplan_track_dataresult);//更新fact中变量值
            end