package cn.ibizlab.plm.prodmgmt.logic.idealogic.set_change_type;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideaset_change_typedefault;
                global java.util.Map ideaset_change_typebaseline_filter;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideaset_change_typefor_obj;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideaset_change_typepage_results;
                global cn.ibizlab.plm.core.base.domain.version ideaset_change_typeversion_filter;
                global cn.ibizlab.plm.core.base.domain.version ideaset_change_typeversion_pages_results;
                    global cn.ibizlab.plm.core.prodmgmt.service.IideaService ideaservice;
                    global cn.ibizlab.plm.core.base.service.IversionService versionservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IideaService iBzSysIdeaDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ideaset_change_typebegin"
            when
            then
            end

            //逻辑处理节点[设置基线过滤器]
            rule "prepareparam4"
            ruleflow-group "ideaset_change_typeprepareparam4"
            when
            then
                            ideaset_change_typebaseline_filter.set("baseline",ideaset_change_typedefault.get("baseline"));
                        update(ideaset_change_typedefault);//更新fact中变量值
                        update(ideaset_change_typebaseline_filter);//更新fact中变量值
                        update(ideaset_change_typefor_obj);//更新fact中变量值
                        update(ideaset_change_typepage_results);//更新fact中变量值
                        update(ideaset_change_typeversion_filter);//更新fact中变量值
                        update(ideaset_change_typeversion_pages_results);//更新fact中变量值
            end

            //逻辑处理节点[查询基线需求分页数据]
            rule "dedataset3"
            ruleflow-group "ideaset_change_typededataset3"
            when
            then
                        update(ideaset_change_typedefault);//更新fact中变量值
                        update(ideaset_change_typebaseline_filter);//更新fact中变量值
                        update(ideaset_change_typefor_obj);//更新fact中变量值
                        update(ideaset_change_typepage_results);//更新fact中变量值
                        update(ideaset_change_typeversion_filter);//更新fact中变量值
                        update(ideaset_change_typeversion_pages_results);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "ideaset_change_typedebugparam1"
            when
            then
                        update(ideaset_change_typedefault);//更新fact中变量值
                        update(ideaset_change_typebaseline_filter);//更新fact中变量值
                        update(ideaset_change_typefor_obj);//更新fact中变量值
                        update(ideaset_change_typepage_results);//更新fact中变量值
                        update(ideaset_change_typeversion_filter);//更新fact中变量值
                        update(ideaset_change_typeversion_pages_results);//更新fact中变量值
            end

            //逻辑处理节点[查询需求分页数据]
            rule "dedataset1"
            ruleflow-group "ideaset_change_typededataset1"
            when
            then
                        update(ideaset_change_typedefault);//更新fact中变量值
                        update(ideaset_change_typebaseline_filter);//更新fact中变量值
                        update(ideaset_change_typefor_obj);//更新fact中变量值
                        update(ideaset_change_typepage_results);//更新fact中变量值
                        update(ideaset_change_typeversion_filter);//更新fact中变量值
                        update(ideaset_change_typeversion_pages_results);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "ideaset_change_typeloopsubcall1"
            when
            then
                        update(ideaset_change_typedefault);//更新fact中变量值
                        update(ideaset_change_typebaseline_filter);//更新fact中变量值
                        update(ideaset_change_typefor_obj);//更新fact中变量值
                        update(ideaset_change_typepage_results);//更新fact中变量值
                        update(ideaset_change_typeversion_filter);//更新fact中变量值
                        update(ideaset_change_typeversion_pages_results);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam2"
            ruleflow-group "ideaset_change_typedebugparam2"
            when
            then
                        update(ideaset_change_typedefault);//更新fact中变量值
                        update(ideaset_change_typebaseline_filter);//更新fact中变量值
                        update(ideaset_change_typefor_obj);//更新fact中变量值
                        update(ideaset_change_typepage_results);//更新fact中变量值
                        update(ideaset_change_typeversion_filter);//更新fact中变量值
                        update(ideaset_change_typeversion_pages_results);//更新fact中变量值
            end

            //逻辑处理节点[获取评审需求]
            rule "rawsqlcall1"
            ruleflow-group "ideaset_change_typerawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",ideaset_change_typedefault.get("review"));
        param.put("param1",ideaset_change_typedefault.get("n_test_library_id_eq"));
    String strSql="	SELECT 		*  	FROM 		idea t1  	WHERE 		NOT EXISTS ( 		SELECT 			*  		FROM 			relation t2 			JOIN review_content_extend t3 ON t3.id = t2.id 			JOIN review t4 ON t4.id = t2.PRINCIPAL_ID  		WHERE 			t2.TARGET_ID = t1.id  			AND t4.id = #{et.param0}  		)  		AND t1.product_id = #{et.param1}  AND t1.IS_DELETED = 0 	ORDER BY 	t1.IDENTIFIER;";
                        java.util.List<JSONObject> entities=iBzSysIdeaDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    ideaset_change_typepage_results.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(ideaset_change_typedefault);//更新fact中变量值
                        update(ideaset_change_typebaseline_filter);//更新fact中变量值
                        update(ideaset_change_typefor_obj);//更新fact中变量值
                        update(ideaset_change_typepage_results);//更新fact中变量值
                        update(ideaset_change_typeversion_filter);//更新fact中变量值
                        update(ideaset_change_typeversion_pages_results);//更新fact中变量值
            end

            //逻辑处理节点[设置版本过滤器]
            rule "prepareparam1"
            ruleflow-group "ideaset_change_typeprepareparam1"
            when
            then
                            ideaset_change_typeversion_filter.set("n_owner_id_eq",ideaset_change_typefor_obj.get("id"));
                            ideaset_change_typeversion_filter.set("size","2");
                        update(ideaset_change_typedefault);//更新fact中变量值
                        update(ideaset_change_typebaseline_filter);//更新fact中变量值
                        update(ideaset_change_typefor_obj);//更新fact中变量值
                        update(ideaset_change_typepage_results);//更新fact中变量值
                        update(ideaset_change_typeversion_filter);//更新fact中变量值
                        update(ideaset_change_typeversion_pages_results);//更新fact中变量值
            end

            //逻辑处理节点[查询符合条件的版本]
            rule "dedataset2"
            ruleflow-group "ideaset_change_typededataset2"
            when
            then
                        update(ideaset_change_typedefault);//更新fact中变量值
                        update(ideaset_change_typebaseline_filter);//更新fact中变量值
                        update(ideaset_change_typefor_obj);//更新fact中变量值
                        update(ideaset_change_typepage_results);//更新fact中变量值
                        update(ideaset_change_typeversion_filter);//更新fact中变量值
                        update(ideaset_change_typeversion_pages_results);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam3"
            ruleflow-group "ideaset_change_typedebugparam3"
            when
            then
                        update(ideaset_change_typedefault);//更新fact中变量值
                        update(ideaset_change_typebaseline_filter);//更新fact中变量值
                        update(ideaset_change_typefor_obj);//更新fact中变量值
                        update(ideaset_change_typepage_results);//更新fact中变量值
                        update(ideaset_change_typeversion_filter);//更新fact中变量值
                        update(ideaset_change_typeversion_pages_results);//更新fact中变量值
            end

            //逻辑处理节点[设置变更类型为新增]
            rule "prepareparam2"
            ruleflow-group "ideaset_change_typeprepareparam2"
            when
            then
                            ideaset_change_typefor_obj.set("change_type","0");
                        update(ideaset_change_typedefault);//更新fact中变量值
                        update(ideaset_change_typebaseline_filter);//更新fact中变量值
                        update(ideaset_change_typefor_obj);//更新fact中变量值
                        update(ideaset_change_typepage_results);//更新fact中变量值
                        update(ideaset_change_typeversion_filter);//更新fact中变量值
                        update(ideaset_change_typeversion_pages_results);//更新fact中变量值
            end

            //逻辑处理节点[设置变更类型为修改]
            rule "prepareparam3"
            ruleflow-group "ideaset_change_typeprepareparam3"
            when
            then
                            ideaset_change_typefor_obj.set("change_type","1");
                        update(ideaset_change_typedefault);//更新fact中变量值
                        update(ideaset_change_typebaseline_filter);//更新fact中变量值
                        update(ideaset_change_typefor_obj);//更新fact中变量值
                        update(ideaset_change_typepage_results);//更新fact中变量值
                        update(ideaset_change_typeversion_filter);//更新fact中变量值
                        update(ideaset_change_typeversion_pages_results);//更新fact中变量值
            end

            //逻辑处理节点[设置from-to都为最新版]
            rule "rawsfcode1"
            ruleflow-group "ideaset_change_typerawsfcode1"
            when
            then
                        update(ideaset_change_typedefault);//更新fact中变量值
                        update(ideaset_change_typebaseline_filter);//更新fact中变量值
                        update(ideaset_change_typefor_obj);//更新fact中变量值
                        update(ideaset_change_typepage_results);//更新fact中变量值
                        update(ideaset_change_typeversion_filter);//更新fact中变量值
                        update(ideaset_change_typeversion_pages_results);//更新fact中变量值
            end

            //逻辑处理节点[设置改变版本信息]
            rule "rawsfcode2"
            ruleflow-group "ideaset_change_typerawsfcode2"
            when
            then
                        update(ideaset_change_typedefault);//更新fact中变量值
                        update(ideaset_change_typebaseline_filter);//更新fact中变量值
                        update(ideaset_change_typefor_obj);//更新fact中变量值
                        update(ideaset_change_typepage_results);//更新fact中变量值
                        update(ideaset_change_typeversion_filter);//更新fact中变量值
                        update(ideaset_change_typeversion_pages_results);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ideaset_change_typeend1"
            when
            then
                        update(ideaset_change_typedefault);//更新fact中变量值
                        update(ideaset_change_typebaseline_filter);//更新fact中变量值
                        update(ideaset_change_typefor_obj);//更新fact中变量值
                        update(ideaset_change_typepage_results);//更新fact中变量值
                        update(ideaset_change_typeversion_filter);//更新fact中变量值
                        update(ideaset_change_typeversion_pages_results);//更新fact中变量值
            end