package cn.ibizlab.plm.base.logic.categorylogic.sort;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.category categorysortdefault;
                global cn.ibizlab.plm.core.base.domain.category categorysortfilter;
                global cn.ibizlab.plm.core.base.domain.category categorysortpage;
                    global cn.ibizlab.plm.core.base.service.IcategoryService categoryservice;
        global cn.ibizlab.plm.core.base.service.IcategoryService iBzSysCategoryDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "categorysortbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "categorysortprepareparam1"
            when
            then
                            categorysortfilter.set("n_owner_type_eq",categorysortdefault.get("ownertype"));
                            categorysortfilter.set("sort","sequence,desc");
                            categorysortfilter.set("n_owner_subtype_eq",categorysortdefault.get("ownersubtype"));
                            categorysortfilter.set("n_section_id_eq",categorysortdefault.get("sectionid"));
                            categorysortfilter.set("n_owner_id_eq",categorysortdefault.get("ownerid"));
                        update(categorysortdefault);//更新fact中变量值
                        update(categorysortfilter);//更新fact中变量值
                        update(categorysortpage);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "categorysortdedataset1"
            when
            then
                        update(categorysortdefault);//更新fact中变量值
                        update(categorysortfilter);//更新fact中变量值
                        update(categorysortpage);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "categorysortdebugparam1"
            when
            then
                        update(categorysortdefault);//更新fact中变量值
                        update(categorysortfilter);//更新fact中变量值
                        update(categorysortpage);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode1"
            ruleflow-group "categorysortrawsfcode1"
            when
            then
                        update(categorysortdefault);//更新fact中变量值
                        update(categorysortfilter);//更新fact中变量值
                        update(categorysortpage);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "categorysortend1"
            when
            then
                        update(categorysortdefault);//更新fact中变量值
                        update(categorysortfilter);//更新fact中变量值
                        update(categorysortpage);//更新fact中变量值
            end