package cn.ibizlab.plm.ai.logic.ai_kb_documentlogic.fill_kb_chunk;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document ai_kb_documentfill_kb_chunkdefault;
        global cn.ibizlab.plm.core.ai.service.Iai_kb_documentService iBzSysAi_kb_documentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_kb_documentfill_kb_chunkbegin"
            when
            then
            end

            //逻辑处理节点[变更填充数据]
            rule "debugparam_01"
            ruleflow-group "ai_kb_documentfill_kb_chunkdebugparam_01"
            when
            then
                        update(ai_kb_documentfill_kb_chunkdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_kb_documentfill_kb_chunkend_01"
            when
            then
                        update(ai_kb_documentfill_kb_chunkdefault);//更新fact中变量值
            end