package cn.ibizlab.plm.ai.logic.ai_kb_documentlogic.generate_doc_scheduled_task;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document ai_kb_documentgenerate_doc_scheduled_taskdefault;
        global cn.ibizlab.plm.core.ai.service.Iai_kb_documentService iBzSysAi_kb_documentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_kb_documentgenerate_doc_scheduled_taskbegin"
            when
            then
            end