package cn.ibizlab.plm.ai.logic.ai_kb_documentlogic.parse;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document ai_kb_documentparsedefault;
                global cn.ibizlab.plm.core.ai.domain.ai_agent_context ai_kb_documentparseagent_context;
                global java.util.Map ai_kb_documentparselastreturn;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document ai_kb_documentparsemasked_data;
                    global cn.ibizlab.plm.core.ai.service.Iai_kb_documentService ai_kb_documentservice;
        global cn.ibizlab.plm.core.ai.service.Iai_kb_documentService iBzSysAi_kb_documentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_kb_documentparsebegin"
            when
            then
            end

            //逻辑处理节点[获取数据]
            rule "deaction_01"
            ruleflow-group "ai_kb_documentparsedeaction_01"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(ai_kb_documentservice.get(ai_kb_documentparsedefault.getId()),ai_kb_documentparsedefault);
                        update(ai_kb_documentparsedefault);//更新fact中变量值
                        update(ai_kb_documentparseagent_context);//更新fact中变量值
                        update(ai_kb_documentparselastreturn);//更新fact中变量值
                        update(ai_kb_documentparsemasked_data);//更新fact中变量值
            end

            //逻辑处理节点[获取文件内容]
            rule "rawsfcode_01"
            ruleflow-group "ai_kb_documentparserawsfcode_01"
            when
            then
                        update(ai_kb_documentparsedefault);//更新fact中变量值
                        update(ai_kb_documentparseagent_context);//更新fact中变量值
                        update(ai_kb_documentparselastreturn);//更新fact中变量值
                        update(ai_kb_documentparsemasked_data);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam_01"
            ruleflow-group "ai_kb_documentparsedebugparam_01"
            when
            then
                        update(ai_kb_documentparsedefault);//更新fact中变量值
                        update(ai_kb_documentparseagent_context);//更新fact中变量值
                        update(ai_kb_documentparselastreturn);//更新fact中变量值
                        update(ai_kb_documentparsemasked_data);//更新fact中变量值
            end

            //逻辑处理节点[提取元数据]
            rule "deaction_03"
            ruleflow-group "ai_kb_documentparsedeaction_03"
            when
            then
                        ai_kb_documentservice.extract_meta_data(ai_kb_documentparsedefault);
                        update(ai_kb_documentparsedefault);//更新fact中变量值
                        update(ai_kb_documentparseagent_context);//更新fact中变量值
                        update(ai_kb_documentparselastreturn);//更新fact中变量值
                        update(ai_kb_documentparsemasked_data);//更新fact中变量值
            end

            //逻辑处理节点[实体打印]
            rule "rawsfcode_03"
            ruleflow-group "ai_kb_documentparserawsfcode_03"
            when
            then
                        update(ai_kb_documentparsedefault);//更新fact中变量值
                        update(ai_kb_documentparseagent_context);//更新fact中变量值
                        update(ai_kb_documentparselastreturn);//更新fact中变量值
                        update(ai_kb_documentparsemasked_data);//更新fact中变量值
            end

            //逻辑处理节点[正则解析文档内容]
            rule "rawsfcode_02"
            ruleflow-group "ai_kb_documentparserawsfcode_02"
            when
            then
                        update(ai_kb_documentparsedefault);//更新fact中变量值
                        update(ai_kb_documentparseagent_context);//更新fact中变量值
                        update(ai_kb_documentparselastreturn);//更新fact中变量值
                        update(ai_kb_documentparsemasked_data);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "ai_kb_documentparseprepareparam_01"
            when
            then
                            ai_kb_documentparsemasked_data.set("metadata",ai_kb_documentparsedefault.get("metadata"));
                        update(ai_kb_documentparsedefault);//更新fact中变量值
                        update(ai_kb_documentparseagent_context);//更新fact中变量值
                        update(ai_kb_documentparselastreturn);//更新fact中变量值
                        update(ai_kb_documentparsemasked_data);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam_02"
            ruleflow-group "ai_kb_documentparsedebugparam_02"
            when
            then
                        update(ai_kb_documentparsedefault);//更新fact中变量值
                        update(ai_kb_documentparseagent_context);//更新fact中变量值
                        update(ai_kb_documentparselastreturn);//更新fact中变量值
                        update(ai_kb_documentparsemasked_data);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction_02"
            ruleflow-group "ai_kb_documentparsedeaction_02"
            when
            then
                        ai_kb_documentservice.update(ai_kb_documentparsemasked_data);
                        update(ai_kb_documentparsedefault);//更新fact中变量值
                        update(ai_kb_documentparseagent_context);//更新fact中变量值
                        update(ai_kb_documentparselastreturn);//更新fact中变量值
                        update(ai_kb_documentparsemasked_data);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_kb_documentparseend_01"
            when
            then
                        update(ai_kb_documentparsedefault);//更新fact中变量值
                        update(ai_kb_documentparseagent_context);//更新fact中变量值
                        update(ai_kb_documentparselastreturn);//更新fact中变量值
                        update(ai_kb_documentparsemasked_data);//更新fact中变量值
            end