package cn.ibizlab.plm.ai.logic.ai_kb_documentlogic.references;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document ai_kb_documentreferencesdefault;
                global java.util.Map ai_kb_documentreferencesreferences;
        global cn.ibizlab.plm.core.ai.service.Iai_kb_documentService iBzSysAi_kb_documentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_kb_documentreferencesbegin"
            when
            then
            end

            //逻辑处理节点[提取references]
            rule "rawsfcode_01"
            ruleflow-group "ai_kb_documentreferencesrawsfcode_01"
            when
            then
                        update(ai_kb_documentreferencesdefault);//更新fact中变量值
                        update(ai_kb_documentreferencesreferences);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_kb_documentreferencesend_01"
            when
            then
                        update(ai_kb_documentreferencesdefault);//更新fact中变量值
                        update(ai_kb_documentreferencesreferences);//更新fact中变量值
            end