package cn.ibizlab.plm.ai.logic.ai_kb_documentlogic.remove_doc_scheduled;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document ai_kb_documentremove_doc_scheduleddefault;
                global cn.ibizlab.plm.core.base.domain.extend_schedule ai_kb_documentremove_doc_scheduledextend_schedule;
                global cn.ibizlab.plm.core.base.domain.extend_schedule ai_kb_documentremove_doc_scheduledextend_schedule_filter;
                global cn.ibizlab.plm.core.base.domain.extend_schedule ai_kb_documentremove_doc_scheduledextend_schedule_pages;
                    global cn.ibizlab.plm.core.base.service.Iextend_scheduleService extend_scheduleservice;
        global cn.ibizlab.plm.core.ai.service.Iai_kb_documentService iBzSysAi_kb_documentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_kb_documentremove_doc_scheduledbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "ai_kb_documentremove_doc_scheduledprepareparam_01"
            when
            then
                            ai_kb_documentremove_doc_scheduledextend_schedule_filter.set("size","1000");
                            ai_kb_documentremove_doc_scheduledextend_schedule_filter.set("n_principal_id_eq",ai_kb_documentremove_doc_scheduleddefault.get("id"));
                        update(ai_kb_documentremove_doc_scheduleddefault);//更新fact中变量值
                        update(ai_kb_documentremove_doc_scheduledextend_schedule);//更新fact中变量值
                        update(ai_kb_documentremove_doc_scheduledextend_schedule_filter);//更新fact中变量值
                        update(ai_kb_documentremove_doc_scheduledextend_schedule_pages);//更新fact中变量值
            end

            //逻辑处理节点[过滤文档对应计划]
            rule "dedataset_01"
            ruleflow-group "ai_kb_documentremove_doc_scheduleddedataset_01"
            when
            then
                        update(ai_kb_documentremove_doc_scheduleddefault);//更新fact中变量值
                        update(ai_kb_documentremove_doc_scheduledextend_schedule);//更新fact中变量值
                        update(ai_kb_documentremove_doc_scheduledextend_schedule_filter);//更新fact中变量值
                        update(ai_kb_documentremove_doc_scheduledextend_schedule_pages);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall_01"
            ruleflow-group "ai_kb_documentremove_doc_scheduledloopsubcall_01"
            when
            then
                        update(ai_kb_documentremove_doc_scheduleddefault);//更新fact中变量值
                        update(ai_kb_documentremove_doc_scheduledextend_schedule);//更新fact中变量值
                        update(ai_kb_documentremove_doc_scheduledextend_schedule_filter);//更新fact中变量值
                        update(ai_kb_documentremove_doc_scheduledextend_schedule_pages);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_kb_documentremove_doc_scheduledend_01"
            when
            then
                        update(ai_kb_documentremove_doc_scheduleddefault);//更新fact中变量值
                        update(ai_kb_documentremove_doc_scheduledextend_schedule);//更新fact中变量值
                        update(ai_kb_documentremove_doc_scheduledextend_schedule_filter);//更新fact中变量值
                        update(ai_kb_documentremove_doc_scheduledextend_schedule_pages);//更新fact中变量值
            end

            //逻辑处理节点[删除文档执行计划]
            rule "deaction_01"
            ruleflow-group "ai_kb_documentremove_doc_scheduleddeaction_01"
            when
            then
                        extend_scheduleservice.remove(ai_kb_documentremove_doc_scheduledextend_schedule.getId());
                        update(ai_kb_documentremove_doc_scheduleddefault);//更新fact中变量值
                        update(ai_kb_documentremove_doc_scheduledextend_schedule);//更新fact中变量值
                        update(ai_kb_documentremove_doc_scheduledextend_schedule_filter);//更新fact中变量值
                        update(ai_kb_documentremove_doc_scheduledextend_schedule_pages);//更新fact中变量值
            end