package cn.ibizlab.plm.ai.logic.ai_kb_documentlogic.reparse;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document ai_kb_documentreparsedefault;
                    global cn.ibizlab.plm.core.ai.service.Iai_kb_documentService ai_kb_documentservice;
        global cn.ibizlab.plm.core.ai.service.Iai_kb_documentService iBzSysAi_kb_documentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_kb_documentreparsebegin"
            when
            then
            end

            //逻辑处理节点[置空parsed_content]
            rule "prepareparam_01"
            ruleflow-group "ai_kb_documentreparseprepareparam_01"
            when
            then
                                ai_kb_documentreparsedefault.set("parsedcontent",null);
                        update(ai_kb_documentreparsedefault);//更新fact中变量值
            end

            //逻辑处理节点[更新doc数据]
            rule "deaction_02"
            ruleflow-group "ai_kb_documentreparsedeaction_02"
            when
            then
                        ai_kb_documentservice.update(ai_kb_documentreparsedefault);
                        update(ai_kb_documentreparsedefault);//更新fact中变量值
            end

            //逻辑处理节点[异步解析文档数据]
            rule "deaction_01"
            ruleflow-group "ai_kb_documentreparsedeaction_01"
            when
            then
                        ai_kb_documentservice.async_parse(ai_kb_documentreparsedefault);
                        update(ai_kb_documentreparsedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_kb_documentreparseend_01"
            when
            then
                        update(ai_kb_documentreparsedefault);//更新fact中变量值
            end