package cn.ibizlab.plm.ai.logic.ai_kb_documentlogic.unparsed;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document ai_kb_documentunparseddefault;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document ai_kb_documentunparseddoc;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document ai_kb_documentunparsedpage;
                    global cn.ibizlab.plm.core.ai.service.Iai_kb_documentService ai_kb_documentservice;
        global cn.ibizlab.plm.core.ai.service.Iai_kb_documentService iBzSysAi_kb_documentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_kb_documentunparsedbegin"
            when
            then
            end

            //逻辑处理节点[查询未切片]
            rule "dedataquery_01"
            ruleflow-group "ai_kb_documentunparseddedataquery_01"
            when
            then
                        update(ai_kb_documentunparseddefault);//更新fact中变量值
                        update(ai_kb_documentunparseddoc);//更新fact中变量值
                        update(ai_kb_documentunparsedpage);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall_01"
            ruleflow-group "ai_kb_documentunparsedloopsubcall_01"
            when
            then
                        update(ai_kb_documentunparseddefault);//更新fact中变量值
                        update(ai_kb_documentunparseddoc);//更新fact中变量值
                        update(ai_kb_documentunparsedpage);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_kb_documentunparsedend_01"
            when
            then
                        update(ai_kb_documentunparseddefault);//更新fact中变量值
                        update(ai_kb_documentunparseddoc);//更新fact中变量值
                        update(ai_kb_documentunparsedpage);//更新fact中变量值
            end

            //逻辑处理节点[置空查询parsing_config]
            rule "prepareparam_01"
            ruleflow-group "ai_kb_documentunparsedprepareparam_01"
            when
            then
                                ai_kb_documentunparseddoc.set("parserconfig",null);
                        update(ai_kb_documentunparseddefault);//更新fact中变量值
                        update(ai_kb_documentunparseddoc);//更新fact中变量值
                        update(ai_kb_documentunparsedpage);//更新fact中变量值
            end