package cn.ibizlab.plm.ai.logic.ai_kb_document_wizardlogic.fill_kb_chunk;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_document_wizard ai_kb_document_wizardfill_kb_chunkdefault;
                global cn.ibizlab.plm.core.ai.domain.ai_knowledge_base ai_kb_document_wizardfill_kb_chunkkb;
                    global cn.ibizlab.plm.core.ai.service.Iai_knowledge_baseService ai_knowledge_baseservice;
        global cn.ibizlab.plm.core.ai.service.Iai_kb_document_wizardService iBzSysAi_kb_document_wizardDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_kb_document_wizardfill_kb_chunkbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_kb_document_wizardfill_kb_chunkend_01"
            when
            then
                        update(ai_kb_document_wizardfill_kb_chunkdefault);//更新fact中变量值
                        update(ai_kb_document_wizardfill_kb_chunkkb);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "ai_kb_document_wizardfill_kb_chunkprepareparam_01"
            when
            then
                            ai_kb_document_wizardfill_kb_chunkkb.set("id",ai_kb_document_wizardfill_kb_chunkdefault.get("kbid"));
                        update(ai_kb_document_wizardfill_kb_chunkdefault);//更新fact中变量值
                        update(ai_kb_document_wizardfill_kb_chunkkb);//更新fact中变量值
            end

            //逻辑处理节点[查询知识库切片策略]
            rule "deaction_01"
            ruleflow-group "ai_kb_document_wizardfill_kb_chunkdeaction_01"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(ai_knowledge_baseservice.get(ai_kb_document_wizardfill_kb_chunkkb.getId()),ai_kb_document_wizardfill_kb_chunkkb);
                        update(ai_kb_document_wizardfill_kb_chunkdefault);//更新fact中变量值
                        update(ai_kb_document_wizardfill_kb_chunkkb);//更新fact中变量值
            end

            //逻辑处理节点[填充知识库参数]
            rule "prepareparam_02"
            ruleflow-group "ai_kb_document_wizardfill_kb_chunkprepareparam_02"
            when
            then
                            ai_kb_document_wizardfill_kb_chunkdefault.set("parserconfig",ai_kb_document_wizardfill_kb_chunkkb.get("parserconfig"));
                            ai_kb_document_wizardfill_kb_chunkdefault.set("chunkmethod",ai_kb_document_wizardfill_kb_chunkkb.get("chunkmethod"));
                        update(ai_kb_document_wizardfill_kb_chunkdefault);//更新fact中变量值
                        update(ai_kb_document_wizardfill_kb_chunkkb);//更新fact中变量值
            end