package cn.ibizlab.plm.wiki.logic.baseline_pagelogic.baseline_comparison;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.baseline_page baseline_pagebaseline_comparisondefault;
                global cn.ibizlab.plm.core.wiki.domain.baseline_page baseline_pagebaseline_comparisoncomparison_filter;
                global cn.ibizlab.plm.core.wiki.domain.baseline_page baseline_pagebaseline_comparisoncomparison_page;
                global cn.ibizlab.plm.core.wiki.domain.baseline_page baseline_pagebaseline_comparisoncontent;
                global cn.ibizlab.plm.core.wiki.domain.baseline_page baseline_pagebaseline_comparisonfor_temp_obj;
                global cn.ibizlab.plm.core.wiki.domain.baseline_page baseline_pagebaseline_comparisonpage;
                global cn.ibizlab.plm.core.wiki.domain.article_page baseline_pagebaseline_comparisonpage_filter;
                global cn.ibizlab.plm.core.wiki.domain.article_page baseline_pagebaseline_comparisonpage_for_temp;
                global cn.ibizlab.plm.core.wiki.domain.article_page baseline_pagebaseline_comparisonpage_ids;
                global cn.ibizlab.plm.core.wiki.domain.article_page baseline_pagebaseline_comparisonpage_page;
                global cn.ibizlab.plm.core.wiki.domain.article_page baseline_pagebaseline_comparisonpage_versions;
                global cn.ibizlab.plm.core.base.domain.version baseline_pagebaseline_comparisonversion_filter;
                global cn.ibizlab.plm.core.base.domain.version baseline_pagebaseline_comparisonversion_for_temp;
                global cn.ibizlab.plm.core.base.domain.version baseline_pagebaseline_comparisonversion_page;
                    global cn.ibizlab.plm.core.wiki.service.Ibaseline_pageService baseline_pageservice;
                    global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService article_pageservice;
                    global cn.ibizlab.plm.core.base.service.IversionService versionservice;
        global cn.ibizlab.plm.core.wiki.service.Ibaseline_pageService iBzSysBaseline_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "baseline_pagebaseline_comparisonbegin"
            when
            then
            end

            //逻辑处理节点[设置关联查询过滤器的分页参数]
            rule "prepareparam2"
            ruleflow-group "baseline_pagebaseline_comparisonprepareparam2"
            when
            then
                            baseline_pagebaseline_comparisondefault.set("size","500");
                            baseline_pagebaseline_comparisoncomparison_filter.set("size","500");
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[获取当前基线下页面]
            rule "dedataset1"
            ruleflow-group "baseline_pagebaseline_comparisondedataset1"
            when
            then
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "baseline_pagebaseline_comparisonloopsubcall1"
            when
            then
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[附加到数组参数]
            rule "appendparam2"
            ruleflow-group "baseline_pagebaseline_comparisonappendparam2"
            when
            then
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[提取关联对象中的主键标识]
            rule "rawsfcode1"
            ruleflow-group "baseline_pagebaseline_comparisonrawsfcode1"
            when
            then
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[填充页面过滤器参数]
            rule "prepareparam3"
            ruleflow-group "baseline_pagebaseline_comparisonprepareparam3"
            when
            then
                            baseline_pagebaseline_comparisonpage_filter.set("n_id_in",baseline_pagebaseline_comparisonpage_ids.get("ids"));
                            baseline_pagebaseline_comparisonpage_filter.set("size","500");
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[填充对比基线关联查询过滤器需要的baseline参数]
            rule "prepareparam1"
            ruleflow-group "baseline_pagebaseline_comparisonprepareparam1"
            when
            then
                            baseline_pagebaseline_comparisoncomparison_filter.set("baseline",baseline_pagebaseline_comparisondefault.get("comparison_baseline"));
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[获取对比基线下的页面]
            rule "dedataset2"
            ruleflow-group "baseline_pagebaseline_comparisondedataset2"
            when
            then
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[获取最新版本页面]
            rule "dedataset3"
            ruleflow-group "baseline_pagebaseline_comparisondedataset3"
            when
            then
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall2"
            ruleflow-group "baseline_pagebaseline_comparisonloopsubcall2"
            when
            then
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[附加到数组参数]
            rule "appendparam3"
            ruleflow-group "baseline_pagebaseline_comparisonappendparam3"
            when
            then
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall3"
            ruleflow-group "baseline_pagebaseline_comparisonloopsubcall3"
            when
            then
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[填充最新版本页面附加属性]
            rule "prepareparam7"
            ruleflow-group "baseline_pagebaseline_comparisonprepareparam7"
            when
            then
                            baseline_pagebaseline_comparisonpage_for_temp.set("target_version_id",baseline_pagebaseline_comparisonpage_for_temp.get("curversionid"));
                            baseline_pagebaseline_comparisonpage_for_temp.set("target_id",baseline_pagebaseline_comparisonpage_for_temp.get("id"));
                            baseline_pagebaseline_comparisonpage_for_temp.set("principal_id",baseline_pagebaseline_comparisondefault.get("comparison_baseline"));
                            baseline_pagebaseline_comparisonpage_for_temp.set("is_latest","1");
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[提取关联对象中的版本标识]
            rule "rawsfcode2"
            ruleflow-group "baseline_pagebaseline_comparisonrawsfcode2"
            when
            then
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[填充版本查询过滤器参数]
            rule "prepareparam5"
            ruleflow-group "baseline_pagebaseline_comparisonprepareparam5"
            when
            then
                            baseline_pagebaseline_comparisonversion_filter.set("n_id_in",baseline_pagebaseline_comparisonpage_versions.get("version_id_in"));
                            baseline_pagebaseline_comparisonversion_filter.set("size","500");
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[将处理好的列表对象绑定至分页结果对象]
            rule "bindparam1"
            ruleflow-group "baseline_pagebaseline_comparisonbindparam1"
            when
            then
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[获取版本结果集]
            rule "dedataset4"
            ruleflow-group "baseline_pagebaseline_comparisondedataset4"
            when
            then
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "baseline_pagebaseline_comparisonend1"
            when
            then
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall4"
            ruleflow-group "baseline_pagebaseline_comparisonloopsubcall4"
            when
            then
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall5"
            ruleflow-group "baseline_pagebaseline_comparisonloopsubcall5"
            when
            then
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[填充关联目标版本对象]
            rule "prepareparam6"
            ruleflow-group "baseline_pagebaseline_comparisonprepareparam6"
            when
            then
                            baseline_pagebaseline_comparisonpage_for_temp.set("target_version",baseline_pagebaseline_comparisonversion_for_temp.get(""));
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end

            //逻辑处理节点[附加到数组参数]
            rule "appendparam4"
            ruleflow-group "baseline_pagebaseline_comparisonappendparam4"
            when
            then
                        update(baseline_pagebaseline_comparisondefault);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncomparison_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisoncontent);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonfor_temp_obj);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_ids);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_page);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonpage_versions);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_filter);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_for_temp);//更新fact中变量值
                        update(baseline_pagebaseline_comparisonversion_page);//更新fact中变量值
            end