package cn.ibizlab.plm.wiki.logic.baseline_pagelogic.shift_out_baseline;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.baseline_page baseline_pageshift_out_baselinedefault;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.wiki.service.Ibaseline_pageService iBzSysBaseline_pageDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "baseline_pageshift_out_baselinebegin"
            when
            then
            end

            //逻辑处理节点[删除基线-页面关联数据]
            rule "deaction1"
            ruleflow-group "baseline_pageshift_out_baselinedeaction1"
            when
            then
                        relationservice.remove(baseline_pageshift_out_baselinedefault.getId());
                        update(baseline_pageshift_out_baselinedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "baseline_pageshift_out_baselineend1"
            when
            then
                        update(baseline_pageshift_out_baselinedefault);//更新fact中变量值
            end