package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.archive;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemarchivedefault;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemarchivefor_temp_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemarchivework_item_filter;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemarchivework_item_page;
                    global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemarchivebegin"
            when
            then
            end

            //逻辑处理节点[设置归档状态]
            rule "prepareparam2"
            ruleflow-group "work_itemarchiveprepareparam2"
            when
            then
                            work_itemarchivedefault.set("isarchived","1");
                        update(work_itemarchivedefault);//更新fact中变量值
                        update(work_itemarchivefor_temp_obj);//更新fact中变量值
                        update(work_itemarchivework_item_filter);//更新fact中变量值
                        update(work_itemarchivework_item_page);//更新fact中变量值
            end

            //逻辑处理节点[更新归档状态]
            rule "deaction1"
            ruleflow-group "work_itemarchivedeaction1"
            when
            then
                        work_itemservice.update(work_itemarchivedefault);
                        update(work_itemarchivedefault);//更新fact中变量值
                        update(work_itemarchivefor_temp_obj);//更新fact中变量值
                        update(work_itemarchivework_item_filter);//更新fact中变量值
                        update(work_itemarchivework_item_page);//更新fact中变量值
            end

            //逻辑处理节点[设置工作项过滤器参数]
            rule "prepareparam1"
            ruleflow-group "work_itemarchiveprepareparam1"
            when
            then
                            work_itemarchivework_item_filter.set("n_pid_eq",work_itemarchivedefault.get("id"));
                        update(work_itemarchivedefault);//更新fact中变量值
                        update(work_itemarchivefor_temp_obj);//更新fact中变量值
                        update(work_itemarchivework_item_filter);//更新fact中变量值
                        update(work_itemarchivework_item_page);//更新fact中变量值
            end

            //逻辑处理节点[查询下级工作项]
            rule "dedataset1"
            ruleflow-group "work_itemarchivededataset1"
            when
            then
                        update(work_itemarchivedefault);//更新fact中变量值
                        update(work_itemarchivefor_temp_obj);//更新fact中变量值
                        update(work_itemarchivework_item_filter);//更新fact中变量值
                        update(work_itemarchivework_item_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemarchiveloopsubcall1"
            when
            then
                        update(work_itemarchivedefault);//更新fact中变量值
                        update(work_itemarchivefor_temp_obj);//更新fact中变量值
                        update(work_itemarchivework_item_filter);//更新fact中变量值
                        update(work_itemarchivework_item_page);//更新fact中变量值
            end

            //逻辑处理节点[递归调用]
            rule "delogic1"
            ruleflow-group "work_itemarchivedelogic1"
            when
            then
                        update(work_itemarchivedefault);//更新fact中变量值
                        update(work_itemarchivefor_temp_obj);//更新fact中变量值
                        update(work_itemarchivework_item_filter);//更新fact中变量值
                        update(work_itemarchivework_item_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemarchiveend1"
            when
            then
                        update(work_itemarchivedefault);//更新fact中变量值
                        update(work_itemarchivefor_temp_obj);//更新fact中变量值
                        update(work_itemarchivework_item_filter);//更新fact中变量值
                        update(work_itemarchivework_item_page);//更新fact中变量值
            end