package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.change_time;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemchange_timedefault;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemchange_timefor_temp_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemchange_timesrfactionparam;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemchange_timebegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "work_itemchange_timebindparam1"
            when
            then
                        update(work_itemchange_timedefault);//更新fact中变量值
                        update(work_itemchange_timefor_temp_obj);//更新fact中变量值
                        update(work_itemchange_timesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[修改时间]
            rule "deaction1"
            ruleflow-group "work_itemchange_timedeaction1"
            when
            then
                        work_itemservice.update(work_itemchange_timedefault);
                        update(work_itemchange_timedefault);//更新fact中变量值
                        update(work_itemchange_timefor_temp_obj);//更新fact中变量值
                        update(work_itemchange_timesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemchange_timeloopsubcall1"
            when
            then
                        update(work_itemchange_timedefault);//更新fact中变量值
                        update(work_itemchange_timefor_temp_obj);//更新fact中变量值
                        update(work_itemchange_timesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[设置时间参数]
            rule "prepareparam2"
            ruleflow-group "work_itemchange_timeprepareparam2"
            when
            then
                            work_itemchange_timedefault.set("endat",work_itemchange_timefor_temp_obj.get("endat"));
                            work_itemchange_timedefault.set("startat",work_itemchange_timefor_temp_obj.get("startat"));
                        update(work_itemchange_timedefault);//更新fact中变量值
                        update(work_itemchange_timefor_temp_obj);//更新fact中变量值
                        update(work_itemchange_timesrfactionparam);//更新fact中变量值
            end