package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.change_parent;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemchange_parentdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemchange_parentfor_temp_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemchange_parentparent_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemchange_parentsrfactionparam;
                    global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemchange_parentbegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "work_itemchange_parentbindparam1"
            when
            then
                        update(work_itemchange_parentdefault);//更新fact中变量值
                        update(work_itemchange_parentfor_temp_obj);//更新fact中变量值
                        update(work_itemchange_parentparent_obj);//更新fact中变量值
                        update(work_itemchange_parentsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemchange_parentloopsubcall1"
            when
            then
                        update(work_itemchange_parentdefault);//更新fact中变量值
                        update(work_itemchange_parentfor_temp_obj);//更新fact中变量值
                        update(work_itemchange_parentparent_obj);//更新fact中变量值
                        update(work_itemchange_parentsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[填充pid]
            rule "prepareparam1"
            ruleflow-group "work_itemchange_parentprepareparam1"
            when
            then
                            work_itemchange_parentdefault.set("pid",work_itemchange_parentfor_temp_obj.get("id"));
                        update(work_itemchange_parentdefault);//更新fact中变量值
                        update(work_itemchange_parentfor_temp_obj);//更新fact中变量值
                        update(work_itemchange_parentparent_obj);//更新fact中变量值
                        update(work_itemchange_parentsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[变更父工作项]
            rule "deaction1"
            ruleflow-group "work_itemchange_parentdeaction1"
            when
            then
                        work_itemservice.update(work_itemchange_parentdefault);
                        update(work_itemchange_parentdefault);//更新fact中变量值
                        update(work_itemchange_parentfor_temp_obj);//更新fact中变量值
                        update(work_itemchange_parentparent_obj);//更新fact中变量值
                        update(work_itemchange_parentsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemchange_parentend1"
            when
            then
                        update(work_itemchange_parentdefault);//更新fact中变量值
                        update(work_itemchange_parentfor_temp_obj);//更新fact中变量值
                        update(work_itemchange_parentparent_obj);//更新fact中变量值
                        update(work_itemchange_parentsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[父工作项id为top_id]
            rule "prepareparam3"
            ruleflow-group "work_itemchange_parentprepareparam3"
            when
            then
                            work_itemchange_parentdefault.set("topid",work_itemchange_parentfor_temp_obj.get("id"));
                        update(work_itemchange_parentdefault);//更新fact中变量值
                        update(work_itemchange_parentfor_temp_obj);//更新fact中变量值
                        update(work_itemchange_parentparent_obj);//更新fact中变量值
                        update(work_itemchange_parentsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[继承父工作项的top_id]
            rule "prepareparam2"
            ruleflow-group "work_itemchange_parentprepareparam2"
            when
            then
                            work_itemchange_parentdefault.set("topid",work_itemchange_parentfor_temp_obj.get("topid"));
                        update(work_itemchange_parentdefault);//更新fact中变量值
                        update(work_itemchange_parentfor_temp_obj);//更新fact中变量值
                        update(work_itemchange_parentparent_obj);//更新fact中变量值
                        update(work_itemchange_parentsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[变更顶级工作项]
            rule "delogic1"
            ruleflow-group "work_itemchange_parentdelogic1"
            when
            then
                        update(work_itemchange_parentdefault);//更新fact中变量值
                        update(work_itemchange_parentfor_temp_obj);//更新fact中变量值
                        update(work_itemchange_parentparent_obj);//更新fact中变量值
                        update(work_itemchange_parentsrfactionparam);//更新fact中变量值
            end