package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.change_assignee;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemchange_assigneedefault;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemchange_assigneefor_temp_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemchange_assigneesrfactionparam;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemchange_assigneebegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "work_itemchange_assigneebindparam1"
            when
            then
                        update(work_itemchange_assigneedefault);//更新fact中变量值
                        update(work_itemchange_assigneefor_temp_obj);//更新fact中变量值
                        update(work_itemchange_assigneesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[分配负责人]
            rule "deaction1"
            ruleflow-group "work_itemchange_assigneedeaction1"
            when
            then
                        work_itemservice.update(work_itemchange_assigneedefault);
                        update(work_itemchange_assigneedefault);//更新fact中变量值
                        update(work_itemchange_assigneefor_temp_obj);//更新fact中变量值
                        update(work_itemchange_assigneesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemchange_assigneeloopsubcall1"
            when
            then
                        update(work_itemchange_assigneedefault);//更新fact中变量值
                        update(work_itemchange_assigneefor_temp_obj);//更新fact中变量值
                        update(work_itemchange_assigneesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "work_itemchange_assigneeprepareparam2"
            when
            then
                            work_itemchange_assigneedefault.set("assigneeid",work_itemchange_assigneefor_temp_obj.get("assigneeid"));
                            work_itemchange_assigneedefault.set("assigneename",work_itemchange_assigneefor_temp_obj.get("assigneename"));
                        update(work_itemchange_assigneedefault);//更新fact中变量值
                        update(work_itemchange_assigneefor_temp_obj);//更新fact中变量值
                        update(work_itemchange_assigneesrfactionparam);//更新fact中变量值
            end