package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.child_del_relation;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemchild_del_relationdefault;
                    global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemchild_del_relationbegin"
            when
            then
            end

            //逻辑处理节点[把子工作项的父标识和顶级标识置空]
            rule "prepareparam1"
            ruleflow-group "work_itemchild_del_relationprepareparam1"
            when
            then
                                work_itemchild_del_relationdefault.set("pid",null);
                                work_itemchild_del_relationdefault.set("topid",null);
                        update(work_itemchild_del_relationdefault);//更新fact中变量值
            end

            //逻辑处理节点[变更顶级工作项]
            rule "delogic1"
            ruleflow-group "work_itemchild_del_relationdelogic1"
            when
            then
                        update(work_itemchild_del_relationdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemchild_del_relationend1"
            when
            then
                        update(work_itemchild_del_relationdefault);//更新fact中变量值
            end