package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.choose_child;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemchoose_childdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemchoose_childfor_temp_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemchoose_childparent_work_item;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemchoose_childsrfactionparam;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemchoose_childupdate_obj;
                    global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemchoose_childbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "work_itemchoose_childprepareparam2"
            when
            then
                            work_itemchoose_childparent_work_item.set("id",work_itemchoose_childdefault.get("pid"));
                        update(work_itemchoose_childdefault);//更新fact中变量值
                        update(work_itemchoose_childfor_temp_obj);//更新fact中变量值
                        update(work_itemchoose_childparent_work_item);//更新fact中变量值
                        update(work_itemchoose_childsrfactionparam);//更新fact中变量值
                        update(work_itemchoose_childupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[获取父工作项内容]
            rule "deaction2"
            ruleflow-group "work_itemchoose_childdeaction2"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(work_itemservice.get(work_itemchoose_childparent_work_item.getId()),work_itemchoose_childparent_work_item);
                        update(work_itemchoose_childdefault);//更新fact中变量值
                        update(work_itemchoose_childfor_temp_obj);//更新fact中变量值
                        update(work_itemchoose_childparent_work_item);//更新fact中变量值
                        update(work_itemchoose_childsrfactionparam);//更新fact中变量值
                        update(work_itemchoose_childupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "work_itemchoose_childbindparam1"
            when
            then
                        update(work_itemchoose_childdefault);//更新fact中变量值
                        update(work_itemchoose_childfor_temp_obj);//更新fact中变量值
                        update(work_itemchoose_childparent_work_item);//更新fact中变量值
                        update(work_itemchoose_childsrfactionparam);//更新fact中变量值
                        update(work_itemchoose_childupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemchoose_childloopsubcall1"
            when
            then
                        update(work_itemchoose_childdefault);//更新fact中变量值
                        update(work_itemchoose_childfor_temp_obj);//更新fact中变量值
                        update(work_itemchoose_childparent_work_item);//更新fact中变量值
                        update(work_itemchoose_childsrfactionparam);//更新fact中变量值
                        update(work_itemchoose_childupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "work_itemchoose_childrenewparam1"
            when
            then
                        update(work_itemchoose_childdefault);//更新fact中变量值
                        update(work_itemchoose_childfor_temp_obj);//更新fact中变量值
                        update(work_itemchoose_childparent_work_item);//更新fact中变量值
                        update(work_itemchoose_childsrfactionparam);//更新fact中变量值
                        update(work_itemchoose_childupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "work_itemchoose_childprepareparam1"
            when
            then
                            work_itemchoose_childupdate_obj.set("pid",work_itemchoose_childparent_work_item.get("id"));
                            work_itemchoose_childupdate_obj.set("id",work_itemchoose_childfor_temp_obj.get("owner_id"));
                        update(work_itemchoose_childdefault);//更新fact中变量值
                        update(work_itemchoose_childfor_temp_obj);//更新fact中变量值
                        update(work_itemchoose_childparent_work_item);//更新fact中变量值
                        update(work_itemchoose_childsrfactionparam);//更新fact中变量值
                        update(work_itemchoose_childupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "work_itemchoose_childdebugparam1"
            when
            then
                        update(work_itemchoose_childdefault);//更新fact中变量值
                        update(work_itemchoose_childfor_temp_obj);//更新fact中变量值
                        update(work_itemchoose_childparent_work_item);//更新fact中变量值
                        update(work_itemchoose_childsrfactionparam);//更新fact中变量值
                        update(work_itemchoose_childupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[变更父工作项]
            rule "deaction1"
            ruleflow-group "work_itemchoose_childdeaction1"
            when
            then
                        work_itemservice.update(work_itemchoose_childupdate_obj);
                        update(work_itemchoose_childdefault);//更新fact中变量值
                        update(work_itemchoose_childfor_temp_obj);//更新fact中变量值
                        update(work_itemchoose_childparent_work_item);//更新fact中变量值
                        update(work_itemchoose_childsrfactionparam);//更新fact中变量值
                        update(work_itemchoose_childupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[父工作项标识为子工作项的顶级标识]
            rule "prepareparam3"
            ruleflow-group "work_itemchoose_childprepareparam3"
            when
            then
                            work_itemchoose_childfor_temp_obj.set("topid",work_itemchoose_childparent_work_item.get("id"));
                        update(work_itemchoose_childdefault);//更新fact中变量值
                        update(work_itemchoose_childfor_temp_obj);//更新fact中变量值
                        update(work_itemchoose_childparent_work_item);//更新fact中变量值
                        update(work_itemchoose_childsrfactionparam);//更新fact中变量值
                        update(work_itemchoose_childupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[继承父工作项的顶级标识]
            rule "prepareparam4"
            ruleflow-group "work_itemchoose_childprepareparam4"
            when
            then
                            work_itemchoose_childfor_temp_obj.set("topid",work_itemchoose_childparent_work_item.get("topid"));
                        update(work_itemchoose_childdefault);//更新fact中变量值
                        update(work_itemchoose_childfor_temp_obj);//更新fact中变量值
                        update(work_itemchoose_childparent_work_item);//更新fact中变量值
                        update(work_itemchoose_childsrfactionparam);//更新fact中变量值
                        update(work_itemchoose_childupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[变更顶级工作项]
            rule "delogic1"
            ruleflow-group "work_itemchoose_childdelogic1"
            when
            then
                        update(work_itemchoose_childdefault);//更新fact中变量值
                        update(work_itemchoose_childfor_temp_obj);//更新fact中变量值
                        update(work_itemchoose_childparent_work_item);//更新fact中变量值
                        update(work_itemchoose_childsrfactionparam);//更新fact中变量值
                        update(work_itemchoose_childupdate_obj);//更新fact中变量值
            end