package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.copy_child_work_item;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemcopy_child_work_itemdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemcopy_child_work_itemafter_copy_parent;
                global cn.ibizlab.plm.core.base.domain.attachment work_itemcopy_child_work_itemattachment;
                global cn.ibizlab.plm.core.base.domain.attachment work_itemcopy_child_work_itemattachments;
                global cn.ibizlab.plm.core.base.domain.attention work_itemcopy_child_work_itemattention;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemcopy_child_work_itembefore_copy_parent;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemcopy_child_work_itemchild_page;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemcopy_child_work_itemfor_temp_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemcopy_child_work_itemnew_child;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemcopy_child_work_itemquery_child_filter;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemcopy_child_work_itemrecursion;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
                    global cn.ibizlab.plm.core.base.service.IattentionService attentionservice;
                    global cn.ibizlab.plm.core.base.service.IattachmentService attachmentservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemcopy_child_work_itembegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "work_itemcopy_child_work_itemprepareparam1"
            when
            then
                            work_itemcopy_child_work_itembefore_copy_parent.set("id",work_itemcopy_child_work_itemdefault.get("old_parent_id"));
                            work_itemcopy_child_work_itemquery_child_filter.set("n_pid_eq",work_itemcopy_child_work_itemdefault.get("old_parent_id"));
                            work_itemcopy_child_work_itemafter_copy_parent.set("id",work_itemcopy_child_work_itemdefault.get("new_parent_id"));
                        update(work_itemcopy_child_work_itemdefault);//更新fact中变量值
                        update(work_itemcopy_child_work_itemafter_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachment);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachments);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattention);//更新fact中变量值
                        update(work_itemcopy_child_work_itembefore_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemcopy_child_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemcopy_child_work_itemnew_child);//更新fact中变量值
                        update(work_itemcopy_child_work_itemquery_child_filter);//更新fact中变量值
                        update(work_itemcopy_child_work_itemrecursion);//更新fact中变量值
            end

            //逻辑处理节点[查询所有子工作项]
            rule "dedataset1"
            ruleflow-group "work_itemcopy_child_work_itemdedataset1"
            when
            then
                        update(work_itemcopy_child_work_itemdefault);//更新fact中变量值
                        update(work_itemcopy_child_work_itemafter_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachment);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachments);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattention);//更新fact中变量值
                        update(work_itemcopy_child_work_itembefore_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemcopy_child_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemcopy_child_work_itemnew_child);//更新fact中变量值
                        update(work_itemcopy_child_work_itemquery_child_filter);//更新fact中变量值
                        update(work_itemcopy_child_work_itemrecursion);//更新fact中变量值
            end

            //逻辑处理节点[获取复制前的父工作项]
            rule "deaction1"
            ruleflow-group "work_itemcopy_child_work_itemdeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(work_itemservice.get(work_itemcopy_child_work_itembefore_copy_parent.getId()),work_itemcopy_child_work_itembefore_copy_parent);
                        update(work_itemcopy_child_work_itemdefault);//更新fact中变量值
                        update(work_itemcopy_child_work_itemafter_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachment);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachments);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattention);//更新fact中变量值
                        update(work_itemcopy_child_work_itembefore_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemcopy_child_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemcopy_child_work_itemnew_child);//更新fact中变量值
                        update(work_itemcopy_child_work_itemquery_child_filter);//更新fact中变量值
                        update(work_itemcopy_child_work_itemrecursion);//更新fact中变量值
            end

            //逻辑处理节点[获取复制后的父工作项]
            rule "deaction2"
            ruleflow-group "work_itemcopy_child_work_itemdeaction2"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(work_itemservice.get(work_itemcopy_child_work_itemafter_copy_parent.getId()),work_itemcopy_child_work_itemafter_copy_parent);
                        update(work_itemcopy_child_work_itemdefault);//更新fact中变量值
                        update(work_itemcopy_child_work_itemafter_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachment);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachments);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattention);//更新fact中变量值
                        update(work_itemcopy_child_work_itembefore_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemcopy_child_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemcopy_child_work_itemnew_child);//更新fact中变量值
                        update(work_itemcopy_child_work_itemquery_child_filter);//更新fact中变量值
                        update(work_itemcopy_child_work_itemrecursion);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemcopy_child_work_itemloopsubcall1"
            when
            then
                        update(work_itemcopy_child_work_itemdefault);//更新fact中变量值
                        update(work_itemcopy_child_work_itemafter_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachment);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachments);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattention);//更新fact中变量值
                        update(work_itemcopy_child_work_itembefore_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemcopy_child_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemcopy_child_work_itemnew_child);//更新fact中变量值
                        update(work_itemcopy_child_work_itemquery_child_filter);//更新fact中变量值
                        update(work_itemcopy_child_work_itemrecursion);//更新fact中变量值
            end

            //逻辑处理节点[重置参数]
            rule "resetparam1"
            ruleflow-group "work_itemcopy_child_work_itemresetparam1"
            when
            then
                        update(work_itemcopy_child_work_itemdefault);//更新fact中变量值
                        update(work_itemcopy_child_work_itemafter_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachment);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachments);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattention);//更新fact中变量值
                        update(work_itemcopy_child_work_itembefore_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemcopy_child_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemcopy_child_work_itemnew_child);//更新fact中变量值
                        update(work_itemcopy_child_work_itemquery_child_filter);//更新fact中变量值
                        update(work_itemcopy_child_work_itemrecursion);//更新fact中变量值
            end

            //逻辑处理节点[重置参数]
            rule "resetparam2"
            ruleflow-group "work_itemcopy_child_work_itemresetparam2"
            when
            then
                        update(work_itemcopy_child_work_itemdefault);//更新fact中变量值
                        update(work_itemcopy_child_work_itemafter_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachment);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachments);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattention);//更新fact中变量值
                        update(work_itemcopy_child_work_itembefore_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemcopy_child_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemcopy_child_work_itemnew_child);//更新fact中变量值
                        update(work_itemcopy_child_work_itemquery_child_filter);//更新fact中变量值
                        update(work_itemcopy_child_work_itemrecursion);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam3"
            ruleflow-group "work_itemcopy_child_work_itemprepareparam3"
            when
            then
                            work_itemcopy_child_work_itemnew_child.set("topid",work_itemcopy_child_work_itemafter_copy_parent.get("id"));
                        update(work_itemcopy_child_work_itemdefault);//更新fact中变量值
                        update(work_itemcopy_child_work_itemafter_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachment);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachments);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattention);//更新fact中变量值
                        update(work_itemcopy_child_work_itembefore_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemcopy_child_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemcopy_child_work_itemnew_child);//更新fact中变量值
                        update(work_itemcopy_child_work_itemquery_child_filter);//更新fact中变量值
                        update(work_itemcopy_child_work_itemrecursion);//更新fact中变量值
            end

            //逻辑处理节点[新建子工作项]
            rule "deaction3"
            ruleflow-group "work_itemcopy_child_work_itemdeaction3"
            when
            then
                        work_itemservice.create(work_itemcopy_child_work_itemnew_child);
                        update(work_itemcopy_child_work_itemdefault);//更新fact中变量值
                        update(work_itemcopy_child_work_itemafter_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachment);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachments);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattention);//更新fact中变量值
                        update(work_itemcopy_child_work_itembefore_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemcopy_child_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemcopy_child_work_itemnew_child);//更新fact中变量值
                        update(work_itemcopy_child_work_itemquery_child_filter);//更新fact中变量值
                        update(work_itemcopy_child_work_itemrecursion);//更新fact中变量值
            end

            //逻辑处理节点[填充新子工作项的属性]
            rule "prepareparam2"
            ruleflow-group "work_itemcopy_child_work_itemprepareparam2"
            when
            then
                            work_itemcopy_child_work_itemnew_child.set("projectid",work_itemcopy_child_work_itemafter_copy_parent.get("projectid"));
                            work_itemcopy_child_work_itemnew_child.set("description",work_itemcopy_child_work_itemfor_temp_obj.get("description"));
                            work_itemcopy_child_work_itemattachments.set("",work_itemcopy_child_work_itemfor_temp_obj.get("attachments"));
                            work_itemcopy_child_work_itemnew_child.set("workitemtypeid",work_itemcopy_child_work_itemfor_temp_obj.get("workitemtypeid"));
                            work_itemcopy_child_work_itemnew_child.set("title",work_itemcopy_child_work_itemfor_temp_obj.get("title"));
                            work_itemcopy_child_work_itemnew_child.set("priority",work_itemcopy_child_work_itemfor_temp_obj.get("priority"));
                            work_itemcopy_child_work_itemnew_child.set("startat",work_itemcopy_child_work_itemfor_temp_obj.get("startat"));
                            work_itemcopy_child_work_itemnew_child.set("endat",work_itemcopy_child_work_itemfor_temp_obj.get("endat"));
                            work_itemcopy_child_work_itemnew_child.set("state",work_itemcopy_child_work_itemfor_temp_obj.get("state"));
                            work_itemcopy_child_work_itemnew_child.set("pid",work_itemcopy_child_work_itemafter_copy_parent.get("id"));
                        update(work_itemcopy_child_work_itemdefault);//更新fact中变量值
                        update(work_itemcopy_child_work_itemafter_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachment);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachments);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattention);//更新fact中变量值
                        update(work_itemcopy_child_work_itembefore_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemcopy_child_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemcopy_child_work_itemnew_child);//更新fact中变量值
                        update(work_itemcopy_child_work_itemquery_child_filter);//更新fact中变量值
                        update(work_itemcopy_child_work_itemrecursion);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam4"
            ruleflow-group "work_itemcopy_child_work_itemprepareparam4"
            when
            then
                            work_itemcopy_child_work_itemnew_child.set("topid",work_itemcopy_child_work_itemafter_copy_parent.get("topid"));
                        update(work_itemcopy_child_work_itemdefault);//更新fact中变量值
                        update(work_itemcopy_child_work_itemafter_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachment);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachments);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattention);//更新fact中变量值
                        update(work_itemcopy_child_work_itembefore_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemcopy_child_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemcopy_child_work_itemnew_child);//更新fact中变量值
                        update(work_itemcopy_child_work_itemquery_child_filter);//更新fact中变量值
                        update(work_itemcopy_child_work_itemrecursion);//更新fact中变量值
            end

            //逻辑处理节点[重置参数]
            rule "resetparam3"
            ruleflow-group "work_itemcopy_child_work_itemresetparam3"
            when
            then
                        update(work_itemcopy_child_work_itemdefault);//更新fact中变量值
                        update(work_itemcopy_child_work_itemafter_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachment);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachments);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattention);//更新fact中变量值
                        update(work_itemcopy_child_work_itembefore_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemcopy_child_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemcopy_child_work_itemnew_child);//更新fact中变量值
                        update(work_itemcopy_child_work_itemquery_child_filter);//更新fact中变量值
                        update(work_itemcopy_child_work_itemrecursion);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam6"
            ruleflow-group "work_itemcopy_child_work_itemprepareparam6"
            when
            then
                            work_itemcopy_child_work_itemrecursion.set("old_parent_id",work_itemcopy_child_work_itemfor_temp_obj.get("id"));
                                work_itemcopy_child_work_itemattention.set("name",curuser.getSessionParams().get("srfpersonname"));
                            work_itemcopy_child_work_itemattention.set("userid",work_itemcopy_child_work_itemnew_child.get("createman"));
                            work_itemcopy_child_work_itemattention.set("ownersubtype","WORK_ITEM");
                            work_itemcopy_child_work_itemattention.set("ownertype","WORK_ITEM");
                            work_itemcopy_child_work_itemattention.set("type","40");
                            work_itemcopy_child_work_itemattention.set("ownerid",work_itemcopy_child_work_itemnew_child.get("id"));
                            work_itemcopy_child_work_itemrecursion.set("new_parent_id",work_itemcopy_child_work_itemnew_child.get("id"));
                        update(work_itemcopy_child_work_itemdefault);//更新fact中变量值
                        update(work_itemcopy_child_work_itemafter_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachment);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachments);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattention);//更新fact中变量值
                        update(work_itemcopy_child_work_itembefore_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemcopy_child_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemcopy_child_work_itemnew_child);//更新fact中变量值
                        update(work_itemcopy_child_work_itemquery_child_filter);//更新fact中变量值
                        update(work_itemcopy_child_work_itemrecursion);//更新fact中变量值
            end

            //逻辑处理节点[创建默认关注人]
            rule "deaction5"
            ruleflow-group "work_itemcopy_child_work_itemdeaction5"
            when
            then
                        attentionservice.save(work_itemcopy_child_work_itemattention);
                        update(work_itemcopy_child_work_itemdefault);//更新fact中变量值
                        update(work_itemcopy_child_work_itemafter_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachment);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachments);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattention);//更新fact中变量值
                        update(work_itemcopy_child_work_itembefore_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemcopy_child_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemcopy_child_work_itemnew_child);//更新fact中变量值
                        update(work_itemcopy_child_work_itemquery_child_filter);//更新fact中变量值
                        update(work_itemcopy_child_work_itemrecursion);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall2"
            ruleflow-group "work_itemcopy_child_work_itemloopsubcall2"
            when
            then
                        update(work_itemcopy_child_work_itemdefault);//更新fact中变量值
                        update(work_itemcopy_child_work_itemafter_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachment);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachments);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattention);//更新fact中变量值
                        update(work_itemcopy_child_work_itembefore_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemcopy_child_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemcopy_child_work_itemnew_child);//更新fact中变量值
                        update(work_itemcopy_child_work_itemquery_child_filter);//更新fact中变量值
                        update(work_itemcopy_child_work_itemrecursion);//更新fact中变量值
            end

            //逻辑处理节点[准备附件参数]
            rule "prepareparam5"
            ruleflow-group "work_itemcopy_child_work_itemprepareparam5"
            when
            then
                                work_itemcopy_child_work_itemattachment.set("id",null);
                            work_itemcopy_child_work_itemattachment.set("ownerid",work_itemcopy_child_work_itemnew_child.get("id"));
                            work_itemcopy_child_work_itemattachment.set("ownertype","WORK_ITEM");
                        update(work_itemcopy_child_work_itemdefault);//更新fact中变量值
                        update(work_itemcopy_child_work_itemafter_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachment);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachments);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattention);//更新fact中变量值
                        update(work_itemcopy_child_work_itembefore_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemcopy_child_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemcopy_child_work_itemnew_child);//更新fact中变量值
                        update(work_itemcopy_child_work_itemquery_child_filter);//更新fact中变量值
                        update(work_itemcopy_child_work_itemrecursion);//更新fact中变量值
            end

            //逻辑处理节点[创建附件]
            rule "deaction4"
            ruleflow-group "work_itemcopy_child_work_itemdeaction4"
            when
            then
                        attachmentservice.create(work_itemcopy_child_work_itemattachment);
                        update(work_itemcopy_child_work_itemdefault);//更新fact中变量值
                        update(work_itemcopy_child_work_itemafter_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachment);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachments);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattention);//更新fact中变量值
                        update(work_itemcopy_child_work_itembefore_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemcopy_child_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemcopy_child_work_itemnew_child);//更新fact中变量值
                        update(work_itemcopy_child_work_itemquery_child_filter);//更新fact中变量值
                        update(work_itemcopy_child_work_itemrecursion);//更新fact中变量值
            end

            //逻辑处理节点[递归调用]
            rule "delogic1"
            ruleflow-group "work_itemcopy_child_work_itemdelogic1"
            when
            then
                        update(work_itemcopy_child_work_itemdefault);//更新fact中变量值
                        update(work_itemcopy_child_work_itemafter_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachment);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattachments);//更新fact中变量值
                        update(work_itemcopy_child_work_itemattention);//更新fact中变量值
                        update(work_itemcopy_child_work_itembefore_copy_parent);//更新fact中变量值
                        update(work_itemcopy_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemcopy_child_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemcopy_child_work_itemnew_child);//更新fact中变量值
                        update(work_itemcopy_child_work_itemquery_child_filter);//更新fact中变量值
                        update(work_itemcopy_child_work_itemrecursion);//更新fact中变量值
            end