package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.delete;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemdeletedefault;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemdeletefor_temp_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemdeletework_item_filter;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemdeletework_item_page;
                    global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemdeletebegin"
            when
            then
            end

            //逻辑处理节点[更新删除状态]
            rule "deaction1"
            ruleflow-group "work_itemdeletedeaction1"
            when
            then
                        work_itemservice.update(work_itemdeletedefault);
                        update(work_itemdeletedefault);//更新fact中变量值
                        update(work_itemdeletefor_temp_obj);//更新fact中变量值
                        update(work_itemdeletework_item_filter);//更新fact中变量值
                        update(work_itemdeletework_item_page);//更新fact中变量值
            end

            //逻辑处理节点[删除最近访问]
            rule "rawsqlcall1"
            ruleflow-group "work_itemdeleterawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",work_itemdeletedefault.get("id"));
    String strSql="update recent set IS_DELETED=1 where owner_id=#{et.param0} and owner_subtype='work_item'";
                        iBzSysWork_itemDefaultService.execute(strSql,param);//SQL调用
                        update(work_itemdeletedefault);//更新fact中变量值
                        update(work_itemdeletefor_temp_obj);//更新fact中变量值
                        update(work_itemdeletework_item_filter);//更新fact中变量值
                        update(work_itemdeletework_item_page);//更新fact中变量值
            end

            //逻辑处理节点[设置工作项过滤器参数]
            rule "prepareparam1"
            ruleflow-group "work_itemdeleteprepareparam1"
            when
            then
                            work_itemdeletework_item_filter.set("n_pid_eq",work_itemdeletedefault.get("id"));
                        update(work_itemdeletedefault);//更新fact中变量值
                        update(work_itemdeletefor_temp_obj);//更新fact中变量值
                        update(work_itemdeletework_item_filter);//更新fact中变量值
                        update(work_itemdeletework_item_page);//更新fact中变量值
            end

            //逻辑处理节点[查询下级工作项]
            rule "dedataset1"
            ruleflow-group "work_itemdeletededataset1"
            when
            then
                        update(work_itemdeletedefault);//更新fact中变量值
                        update(work_itemdeletefor_temp_obj);//更新fact中变量值
                        update(work_itemdeletework_item_filter);//更新fact中变量值
                        update(work_itemdeletework_item_page);//更新fact中变量值
            end

            //逻辑处理节点[设置删除状态]
            rule "prepareparam2"
            ruleflow-group "work_itemdeleteprepareparam2"
            when
            then
                            work_itemdeletedefault.set("isdeleted","1");
                        update(work_itemdeletedefault);//更新fact中变量值
                        update(work_itemdeletefor_temp_obj);//更新fact中变量值
                        update(work_itemdeletework_item_filter);//更新fact中变量值
                        update(work_itemdeletework_item_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemdeleteloopsubcall1"
            when
            then
                        update(work_itemdeletedefault);//更新fact中变量值
                        update(work_itemdeletefor_temp_obj);//更新fact中变量值
                        update(work_itemdeletework_item_filter);//更新fact中变量值
                        update(work_itemdeletework_item_page);//更新fact中变量值
            end

            //逻辑处理节点[递归调用]
            rule "delogic1"
            ruleflow-group "work_itemdeletedelogic1"
            when
            then
                        update(work_itemdeletedefault);//更新fact中变量值
                        update(work_itemdeletefor_temp_obj);//更新fact中变量值
                        update(work_itemdeletework_item_filter);//更新fact中变量值
                        update(work_itemdeletework_item_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemdeleteend1"
            when
            then
                        update(work_itemdeletedefault);//更新fact中变量值
                        update(work_itemdeletefor_temp_obj);//更新fact中变量值
                        update(work_itemdeletework_item_filter);//更新fact中变量值
                        update(work_itemdeletework_item_page);//更新fact中变量值
            end