package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.edlin_update;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemedlin_updatedefault;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemedlin_updateedlin_obj;
                    global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemedlin_updatebegin"
            when
            then
            end

            //逻辑处理节点[指定行编辑属性组]
            rule "prepareparam1"
            ruleflow-group "work_itemedlin_updateprepareparam1"
            when
            then
                            work_itemedlin_updateedlin_obj.set("title",work_itemedlin_updatedefault.get("title"));
                            work_itemedlin_updateedlin_obj.set("state",work_itemedlin_updatedefault.get("state"));
                            work_itemedlin_updateedlin_obj.set("assigneename",work_itemedlin_updatedefault.get("assigneename"));
                            work_itemedlin_updateedlin_obj.set("assigneeid",work_itemedlin_updatedefault.get("assigneeid"));
                            work_itemedlin_updateedlin_obj.set("startat",work_itemedlin_updatedefault.get("startat"));
                            work_itemedlin_updateedlin_obj.set("endat",work_itemedlin_updatedefault.get("endat"));
                            work_itemedlin_updateedlin_obj.set("priority",work_itemedlin_updatedefault.get("priority"));
                        update(work_itemedlin_updatedefault);//更新fact中变量值
                        update(work_itemedlin_updateedlin_obj);//更新fact中变量值
            end

            //逻辑处理节点[更新]
            rule "deaction1"
            ruleflow-group "work_itemedlin_updatedeaction1"
            when
            then
                        work_itemservice.update(work_itemedlin_updateedlin_obj);
                        update(work_itemedlin_updatedefault);//更新fact中变量值
                        update(work_itemedlin_updateedlin_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemedlin_updateend1"
            when
            then
                        update(work_itemedlin_updatedefault);//更新fact中变量值
                        update(work_itemedlin_updateedlin_obj);//更新fact中变量值
            end