package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.fill_type;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemfill_typedefault;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemfill_typeparent;
                    global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemfill_typebegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "work_itemfill_typeprepareparam1"
            when
            then
                            work_itemfill_typeparent.set("id",work_itemfill_typedefault.get("pid"));
                        update(work_itemfill_typedefault);//更新fact中变量值
                        update(work_itemfill_typeparent);//更新fact中变量值
            end

            //逻辑处理节点[获取父工作项]
            rule "deaction1"
            ruleflow-group "work_itemfill_typedeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(work_itemservice.get(work_itemfill_typeparent.getId()),work_itemfill_typeparent);
                        update(work_itemfill_typedefault);//更新fact中变量值
                        update(work_itemfill_typeparent);//更新fact中变量值
            end

            //逻辑处理节点[子工作项类型设置为特性]
            rule "prepareparam2"
            ruleflow-group "work_itemfill_typeprepareparam2"
            when
            then
                            work_itemfill_typedefault.set("workitemtypeid","scrum_feature");
                        update(work_itemfill_typedefault);//更新fact中变量值
                        update(work_itemfill_typeparent);//更新fact中变量值
            end

            //逻辑处理节点[子工作项类型设置为用户故事]
            rule "prepareparam3"
            ruleflow-group "work_itemfill_typeprepareparam3"
            when
            then
                            work_itemfill_typedefault.set("workitemtypeid","scrum_story");
                        update(work_itemfill_typedefault);//更新fact中变量值
                        update(work_itemfill_typeparent);//更新fact中变量值
            end

            //逻辑处理节点[子工作项类型设置为用户故事]
            rule "prepareparam4"
            ruleflow-group "work_itemfill_typeprepareparam4"
            when
            then
                            work_itemfill_typedefault.set("workitemtypeid","scrum_story");
                        update(work_itemfill_typedefault);//更新fact中变量值
                        update(work_itemfill_typeparent);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemfill_typeend1"
            when
            then
                        update(work_itemfill_typedefault);//更新fact中变量值
                        update(work_itemfill_typeparent);//更新fact中变量值
            end