package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.get_workload_schedule;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemget_workload_scheduledefault;
        global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemget_workload_schedulebegin"
            when
            then
            end

            //逻辑处理节点[查询实际工时]
            rule "rawsqlcall1"
            ruleflow-group "work_itemget_workload_schedulerawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",work_itemget_workload_scheduledefault.get("id"));
    String strSql="select sum(DURATION) as `ACTUAL_WORKLOAD` from workload where OWNER_TYPE = 'actual_workload' and PRINCIPAL_TYPE = 'WORK_ITEM' and PRINCIPAL_ID = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysWork_itemDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    work_itemget_workload_scheduledefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(work_itemget_workload_scheduledefault);//更新fact中变量值
            end

            //逻辑处理节点[计算工时进度：（实际工时 / (实际工时+剩余工时)）]
            rule "rawsfcode1"
            ruleflow-group "work_itemget_workload_schedulerawsfcode1"
            when
            then
                        update(work_itemget_workload_scheduledefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemget_workload_scheduleend1"
            when
            then
                        update(work_itemget_workload_scheduledefault);//更新fact中变量值
            end