package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.get_project_member;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemget_project_memberdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.project_member work_itemget_project_memberfilter;
                global java.util.Map work_itemget_project_memberfor_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.project_member work_itemget_project_membermembers;
                global cn.ibizlab.plm.core.projmgmt.domain.project work_itemget_project_memberproject_info;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemget_project_memberticket;
                global java.util.Map work_itemget_project_memberuser;
                global java.util.Map work_itemget_project_memberviewctx;
                global java.util.Map work_itemget_project_memberwebctx;
                    global cn.ibizlab.plm.core.projmgmt.service.Iproject_memberService project_memberservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemget_project_memberbegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam3"
            ruleflow-group "work_itemget_project_memberdebugparam3"
            when
            then
                        update(work_itemget_project_memberdefault);//更新fact中变量值
                        update(work_itemget_project_memberfilter);//更新fact中变量值
                        update(work_itemget_project_memberfor_obj);//更新fact中变量值
                        update(work_itemget_project_membermembers);//更新fact中变量值
                        update(work_itemget_project_memberproject_info);//更新fact中变量值
                        update(work_itemget_project_memberticket);//更新fact中变量值
                        update(work_itemget_project_memberuser);//更新fact中变量值
                        update(work_itemget_project_memberviewctx);//更新fact中变量值
                        update(work_itemget_project_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[获取项目id]
            rule "prepareparam2"
            ruleflow-group "work_itemget_project_memberprepareparam2"
            when
            then
                            work_itemget_project_memberproject_info.set("id",work_itemget_project_memberdefault.get("projectid"));
                            work_itemget_project_memberfilter.set("n_project_id_eq",work_itemget_project_memberdefault.get("projectid"));
                                work_itemget_project_memberfilter.set("n_user_id_eq",curuser.getSessionParams().get("srfpersonid"));
                        update(work_itemget_project_memberdefault);//更新fact中变量值
                        update(work_itemget_project_memberfilter);//更新fact中变量值
                        update(work_itemget_project_memberfor_obj);//更新fact中变量值
                        update(work_itemget_project_membermembers);//更新fact中变量值
                        update(work_itemget_project_memberproject_info);//更新fact中变量值
                        update(work_itemget_project_memberticket);//更新fact中变量值
                        update(work_itemget_project_memberuser);//更新fact中变量值
                        update(work_itemget_project_memberviewctx);//更新fact中变量值
                        update(work_itemget_project_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam6"
            ruleflow-group "work_itemget_project_memberdebugparam6"
            when
            then
                        update(work_itemget_project_memberdefault);//更新fact中变量值
                        update(work_itemget_project_memberfilter);//更新fact中变量值
                        update(work_itemget_project_memberfor_obj);//更新fact中变量值
                        update(work_itemget_project_membermembers);//更新fact中变量值
                        update(work_itemget_project_memberproject_info);//更新fact中变量值
                        update(work_itemget_project_memberticket);//更新fact中变量值
                        update(work_itemget_project_memberuser);//更新fact中变量值
                        update(work_itemget_project_memberviewctx);//更新fact中变量值
                        update(work_itemget_project_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset3"
            ruleflow-group "work_itemget_project_memberdedataset3"
            when
            then
                        update(work_itemget_project_memberdefault);//更新fact中变量值
                        update(work_itemget_project_memberfilter);//更新fact中变量值
                        update(work_itemget_project_memberfor_obj);//更新fact中变量值
                        update(work_itemget_project_membermembers);//更新fact中变量值
                        update(work_itemget_project_memberproject_info);//更新fact中变量值
                        update(work_itemget_project_memberticket);//更新fact中变量值
                        update(work_itemget_project_memberuser);//更新fact中变量值
                        update(work_itemget_project_memberviewctx);//更新fact中变量值
                        update(work_itemget_project_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall3"
            ruleflow-group "work_itemget_project_memberloopsubcall3"
            when
            then
                        update(work_itemget_project_memberdefault);//更新fact中变量值
                        update(work_itemget_project_memberfilter);//更新fact中变量值
                        update(work_itemget_project_memberfor_obj);//更新fact中变量值
                        update(work_itemget_project_membermembers);//更新fact中变量值
                        update(work_itemget_project_memberproject_info);//更新fact中变量值
                        update(work_itemget_project_memberticket);//更新fact中变量值
                        update(work_itemget_project_memberuser);//更新fact中变量值
                        update(work_itemget_project_memberviewctx);//更新fact中变量值
                        update(work_itemget_project_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[只读]
            rule "prepareparam10"
            ruleflow-group "work_itemget_project_memberprepareparam10"
            when
            then
                            work_itemget_project_memberuser.set("readonly","true");
                        update(work_itemget_project_memberdefault);//更新fact中变量值
                        update(work_itemget_project_memberfilter);//更新fact中变量值
                        update(work_itemget_project_memberfor_obj);//更新fact中变量值
                        update(work_itemget_project_membermembers);//更新fact中变量值
                        update(work_itemget_project_memberproject_info);//更新fact中变量值
                        update(work_itemget_project_memberticket);//更新fact中变量值
                        update(work_itemget_project_memberuser);//更新fact中变量值
                        update(work_itemget_project_memberviewctx);//更新fact中变量值
                        update(work_itemget_project_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[只读]
            rule "prepareparam8"
            ruleflow-group "work_itemget_project_memberprepareparam8"
            when
            then
                            work_itemget_project_memberuser.set("readonly","true");
                        update(work_itemget_project_memberdefault);//更新fact中变量值
                        update(work_itemget_project_memberfilter);//更新fact中变量值
                        update(work_itemget_project_memberfor_obj);//更新fact中变量值
                        update(work_itemget_project_membermembers);//更新fact中变量值
                        update(work_itemget_project_memberproject_info);//更新fact中变量值
                        update(work_itemget_project_memberticket);//更新fact中变量值
                        update(work_itemget_project_memberuser);//更新fact中变量值
                        update(work_itemget_project_memberviewctx);//更新fact中变量值
                        update(work_itemget_project_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[非只读]
            rule "prepareparam9"
            ruleflow-group "work_itemget_project_memberprepareparam9"
            when
            then
                            work_itemget_project_memberuser.set("readonly","false");
                        update(work_itemget_project_memberdefault);//更新fact中变量值
                        update(work_itemget_project_memberfilter);//更新fact中变量值
                        update(work_itemget_project_memberfor_obj);//更新fact中变量值
                        update(work_itemget_project_membermembers);//更新fact中变量值
                        update(work_itemget_project_memberproject_info);//更新fact中变量值
                        update(work_itemget_project_memberticket);//更新fact中变量值
                        update(work_itemget_project_memberuser);//更新fact中变量值
                        update(work_itemget_project_memberviewctx);//更新fact中变量值
                        update(work_itemget_project_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end6"
            ruleflow-group "work_itemget_project_memberend6"
            when
            then
                        update(work_itemget_project_memberdefault);//更新fact中变量值
                        update(work_itemget_project_memberfilter);//更新fact中变量值
                        update(work_itemget_project_memberfor_obj);//更新fact中变量值
                        update(work_itemget_project_membermembers);//更新fact中变量值
                        update(work_itemget_project_memberproject_info);//更新fact中变量值
                        update(work_itemget_project_memberticket);//更新fact中变量值
                        update(work_itemget_project_memberuser);//更新fact中变量值
                        update(work_itemget_project_memberviewctx);//更新fact中变量值
                        update(work_itemget_project_memberwebctx);//更新fact中变量值
            end