package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.get_with_additional;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemget_with_additionaldefault;
                global cn.ibizlab.plm.core.base.domain.baseline work_itemget_with_additionalbaseline;
                global cn.ibizlab.plm.core.base.domain.relation work_itemget_with_additionalrelation;
                global cn.ibizlab.plm.core.base.domain.relation work_itemget_with_additionalrelation_filter;
                global cn.ibizlab.plm.core.base.domain.relation work_itemget_with_additionalrelation_page;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
                    global cn.ibizlab.plm.core.base.service.IbaselineService baselineservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemget_with_additionalbegin"
            when
            then
            end

            //逻辑处理节点[获取工作项]
            rule "deaction1"
            ruleflow-group "work_itemget_with_additionaldeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(work_itemservice.get(work_itemget_with_additionaldefault.getId()),work_itemget_with_additionaldefault);
                        update(work_itemget_with_additionaldefault);//更新fact中变量值
                        update(work_itemget_with_additionalbaseline);//更新fact中变量值
                        update(work_itemget_with_additionalrelation);//更新fact中变量值
                        update(work_itemget_with_additionalrelation_filter);//更新fact中变量值
                        update(work_itemget_with_additionalrelation_page);//更新fact中变量值
            end

            //逻辑处理节点[准备关联过滤器参数]
            rule "prepareparam1"
            ruleflow-group "work_itemget_with_additionalprepareparam1"
            when
            then
                            work_itemget_with_additionalrelation_filter.set("n_target_type_eq","work_item");
                            work_itemget_with_additionalrelation_filter.set("n_principal_type_eq","baseline");
                            work_itemget_with_additionalrelation_filter.set("n_target_id_eq",work_itemget_with_additionaldefault.get("id"));
                            work_itemget_with_additionalrelation_filter.set("sort","create_time,desc");
                            work_itemget_with_additionalrelation_filter.set("targetversionid",work_itemget_with_additionaldefault.get("curversionid"));
                        update(work_itemget_with_additionaldefault);//更新fact中变量值
                        update(work_itemget_with_additionalbaseline);//更新fact中变量值
                        update(work_itemget_with_additionalrelation);//更新fact中变量值
                        update(work_itemget_with_additionalrelation_filter);//更新fact中变量值
                        update(work_itemget_with_additionalrelation_page);//更新fact中变量值
            end

            //逻辑处理节点[获取此工作项引入的基线]
            rule "dedataset1"
            ruleflow-group "work_itemget_with_additionaldedataset1"
            when
            then
                        update(work_itemget_with_additionaldefault);//更新fact中变量值
                        update(work_itemget_with_additionalbaseline);//更新fact中变量值
                        update(work_itemget_with_additionalrelation);//更新fact中变量值
                        update(work_itemget_with_additionalrelation_filter);//更新fact中变量值
                        update(work_itemget_with_additionalrelation_page);//更新fact中变量值
            end

            //逻辑处理节点[绑定最近移入的基线]
            rule "bindparam1"
            ruleflow-group "work_itemget_with_additionalbindparam1"
            when
            then
                        update(work_itemget_with_additionaldefault);//更新fact中变量值
                        update(work_itemget_with_additionalbaseline);//更新fact中变量值
                        update(work_itemget_with_additionalrelation);//更新fact中变量值
                        update(work_itemget_with_additionalrelation_filter);//更新fact中变量值
                        update(work_itemget_with_additionalrelation_page);//更新fact中变量值
            end

            //逻辑处理节点[填充基线标识]
            rule "prepareparam2"
            ruleflow-group "work_itemget_with_additionalprepareparam2"
            when
            then
                            work_itemget_with_additionalbaseline.set("id",work_itemget_with_additionalrelation.get("principalid"));
                        update(work_itemget_with_additionaldefault);//更新fact中变量值
                        update(work_itemget_with_additionalbaseline);//更新fact中变量值
                        update(work_itemget_with_additionalrelation);//更新fact中变量值
                        update(work_itemget_with_additionalrelation_filter);//更新fact中变量值
                        update(work_itemget_with_additionalrelation_page);//更新fact中变量值
            end

            //逻辑处理节点[获取基线]
            rule "deaction2"
            ruleflow-group "work_itemget_with_additionaldeaction2"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(baselineservice.get(work_itemget_with_additionalbaseline.getId()),work_itemget_with_additionalbaseline);
                        update(work_itemget_with_additionaldefault);//更新fact中变量值
                        update(work_itemget_with_additionalbaseline);//更新fact中变量值
                        update(work_itemget_with_additionalrelation);//更新fact中变量值
                        update(work_itemget_with_additionalrelation_filter);//更新fact中变量值
                        update(work_itemget_with_additionalrelation_page);//更新fact中变量值
            end

            //逻辑处理节点[将基线名称填充至工作项对象中]
            rule "prepareparam3"
            ruleflow-group "work_itemget_with_additionalprepareparam3"
            when
            then
                            work_itemget_with_additionaldefault.set("baseline_name",work_itemget_with_additionalbaseline.get("name"));
                        update(work_itemget_with_additionaldefault);//更新fact中变量值
                        update(work_itemget_with_additionalbaseline);//更新fact中变量值
                        update(work_itemget_with_additionalrelation);//更新fact中变量值
                        update(work_itemget_with_additionalrelation_filter);//更新fact中变量值
                        update(work_itemget_with_additionalrelation_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemget_with_additionalend1"
            when
            then
                        update(work_itemget_with_additionaldefault);//更新fact中变量值
                        update(work_itemget_with_additionalbaseline);//更新fact中变量值
                        update(work_itemget_with_additionalrelation);//更新fact中变量值
                        update(work_itemget_with_additionalrelation_filter);//更新fact中变量值
                        update(work_itemget_with_additionalrelation_page);//更新fact中变量值
            end