package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.init_work_item_info;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_iteminit_work_item_infodefault;
                global java.util.Map work_iteminit_work_item_infoctx;
                global cn.ibizlab.plm.core.testmgmt.domain.Test_plan work_iteminit_work_item_infotest_plan;
                    global cn.ibizlab.plm.core.testmgmt.service.ITest_planService test_planservice;
        global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_iteminit_work_item_infobegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "work_iteminit_work_item_infoprepareparam1"
            when
            then
                            work_iteminit_work_item_infotest_plan.set("id",work_iteminit_work_item_infodefault.get("testplanid"));
                        update(work_iteminit_work_item_infodefault);//更新fact中变量值
                        update(work_iteminit_work_item_infoctx);//更新fact中变量值
                        update(work_iteminit_work_item_infotest_plan);//更新fact中变量值
            end

            //逻辑处理节点[获取test_plan关联项目]
            rule "deaction1"
            ruleflow-group "work_iteminit_work_item_infodeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(test_planservice.get(work_iteminit_work_item_infotest_plan.getId()),work_iteminit_work_item_infotest_plan);
                        update(work_iteminit_work_item_infodefault);//更新fact中变量值
                        update(work_iteminit_work_item_infoctx);//更新fact中变量值
                        update(work_iteminit_work_item_infotest_plan);//更新fact中变量值
            end

            //逻辑处理节点[赋值projectid]
            rule "prepareparam2"
            ruleflow-group "work_iteminit_work_item_infoprepareparam2"
            when
            then
                            work_iteminit_work_item_infodefault.set("projectid",work_iteminit_work_item_infotest_plan.get("projectid"));
                                work_iteminit_work_item_infodefault.set("id",null);
                            work_iteminit_work_item_infodefault.set("projectname",work_iteminit_work_item_infotest_plan.get("projectname"));
                        update(work_iteminit_work_item_infodefault);//更新fact中变量值
                        update(work_iteminit_work_item_infoctx);//更新fact中变量值
                        update(work_iteminit_work_item_infotest_plan);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_iteminit_work_item_infoend1"
            when
            then
                        update(work_iteminit_work_item_infodefault);//更新fact中变量值
                        update(work_iteminit_work_item_infoctx);//更新fact中变量值
                        update(work_iteminit_work_item_infotest_plan);//更新fact中变量值
            end