package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.line_update;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemline_updatedefault;
                    global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemline_updatebegin"
            when
            then
            end

            //逻辑处理节点[更新]
            rule "deaction1"
            ruleflow-group "work_itemline_updatedeaction1"
            when
            then
                        work_itemservice.update(work_itemline_updatedefault);
                        update(work_itemline_updatedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemline_updateend1"
            when
            then
                        update(work_itemline_updatedefault);//更新fact中变量值
            end