package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.move_child_work_item;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemmove_child_work_itemdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemmove_child_work_itemchild_page;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemmove_child_work_itemfilter;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemmove_child_work_itemfor_temp_obj;
                    global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemmove_child_work_itembegin"
            when
            then
            end

            //逻辑处理节点[设置过滤参数]
            rule "prepareparam1"
            ruleflow-group "work_itemmove_child_work_itemprepareparam1"
            when
            then
                            work_itemmove_child_work_itemfilter.set("n_pid_eq",work_itemmove_child_work_itemdefault.get("id"));
                        update(work_itemmove_child_work_itemdefault);//更新fact中变量值
                        update(work_itemmove_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemmove_child_work_itemfilter);//更新fact中变量值
                        update(work_itemmove_child_work_itemfor_temp_obj);//更新fact中变量值
            end

            //逻辑处理节点[子工作项继承父工作项的顶级标识]
            rule "prepareparam3"
            ruleflow-group "work_itemmove_child_work_itemprepareparam3"
            when
            then
                            work_itemmove_child_work_itemfor_temp_obj.set("topid",work_itemmove_child_work_itemdefault.get("topid"));
                        update(work_itemmove_child_work_itemdefault);//更新fact中变量值
                        update(work_itemmove_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemmove_child_work_itemfilter);//更新fact中变量值
                        update(work_itemmove_child_work_itemfor_temp_obj);//更新fact中变量值
            end

            //逻辑处理节点[获取所有子工作项]
            rule "dedataset1"
            ruleflow-group "work_itemmove_child_work_itemdedataset1"
            when
            then
                        update(work_itemmove_child_work_itemdefault);//更新fact中变量值
                        update(work_itemmove_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemmove_child_work_itemfilter);//更新fact中变量值
                        update(work_itemmove_child_work_itemfor_temp_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemmove_child_work_itemloopsubcall1"
            when
            then
                        update(work_itemmove_child_work_itemdefault);//更新fact中变量值
                        update(work_itemmove_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemmove_child_work_itemfilter);//更新fact中变量值
                        update(work_itemmove_child_work_itemfor_temp_obj);//更新fact中变量值
            end

            //逻辑处理节点[子工作项项目继承父工作项的项目标识]
            rule "prepareparam2"
            ruleflow-group "work_itemmove_child_work_itemprepareparam2"
            when
            then
                            work_itemmove_child_work_itemfor_temp_obj.set("projectid",work_itemmove_child_work_itemdefault.get("projectid"));
                        update(work_itemmove_child_work_itemdefault);//更新fact中变量值
                        update(work_itemmove_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemmove_child_work_itemfilter);//更新fact中变量值
                        update(work_itemmove_child_work_itemfor_temp_obj);//更新fact中变量值
            end

            //逻辑处理节点[更新子工作项]
            rule "deaction1"
            ruleflow-group "work_itemmove_child_work_itemdeaction1"
            when
            then
                        work_itemservice.update(work_itemmove_child_work_itemfor_temp_obj);
                        update(work_itemmove_child_work_itemdefault);//更新fact中变量值
                        update(work_itemmove_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemmove_child_work_itemfilter);//更新fact中变量值
                        update(work_itemmove_child_work_itemfor_temp_obj);//更新fact中变量值
            end

            //逻辑处理节点[递归调用]
            rule "delogic1"
            ruleflow-group "work_itemmove_child_work_itemdelogic1"
            when
            then
                        update(work_itemmove_child_work_itemdefault);//更新fact中变量值
                        update(work_itemmove_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemmove_child_work_itemfilter);//更新fact中变量值
                        update(work_itemmove_child_work_itemfor_temp_obj);//更新fact中变量值
            end

            //逻辑处理节点[将父标识当做顶级标识]
            rule "prepareparam4"
            ruleflow-group "work_itemmove_child_work_itemprepareparam4"
            when
            then
                            work_itemmove_child_work_itemfor_temp_obj.set("topid",work_itemmove_child_work_itemdefault.get("id"));
                        update(work_itemmove_child_work_itemdefault);//更新fact中变量值
                        update(work_itemmove_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemmove_child_work_itemfilter);//更新fact中变量值
                        update(work_itemmove_child_work_itemfor_temp_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemmove_child_work_itemend1"
            when
            then
                        update(work_itemmove_child_work_itemdefault);//更新fact中变量值
                        update(work_itemmove_child_work_itemchild_page);//更新fact中变量值
                        update(work_itemmove_child_work_itemfilter);//更新fact中变量值
                        update(work_itemmove_child_work_itemfor_temp_obj);//更新fact中变量值
            end