package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.plan_work_item;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemplan_work_itemdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemplan_work_itemfor_temp_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemplan_work_itemsrfactionparam;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemplan_work_itemupdate_obj;
                    global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemplan_work_itembegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "work_itemplan_work_itemdebugparam1"
            when
            then
                        update(work_itemplan_work_itemdefault);//更新fact中变量值
                        update(work_itemplan_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemplan_work_itemsrfactionparam);//更新fact中变量值
                        update(work_itemplan_work_itemupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "work_itemplan_work_itembindparam1"
            when
            then
                        update(work_itemplan_work_itemdefault);//更新fact中变量值
                        update(work_itemplan_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemplan_work_itemsrfactionparam);//更新fact中变量值
                        update(work_itemplan_work_itemupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemplan_work_itemloopsubcall1"
            when
            then
                        update(work_itemplan_work_itemdefault);//更新fact中变量值
                        update(work_itemplan_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemplan_work_itemsrfactionparam);//更新fact中变量值
                        update(work_itemplan_work_itemupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "work_itemplan_work_itemrenewparam1"
            when
            then
                        update(work_itemplan_work_itemdefault);//更新fact中变量值
                        update(work_itemplan_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemplan_work_itemsrfactionparam);//更新fact中变量值
                        update(work_itemplan_work_itemupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "work_itemplan_work_itemprepareparam1"
            when
            then
                            work_itemplan_work_itemupdate_obj.set("id",work_itemplan_work_itemfor_temp_obj.get("id"));
                            work_itemplan_work_itemupdate_obj.set("releaseid",work_itemplan_work_itemdefault.get("releaseid"));
                        update(work_itemplan_work_itemdefault);//更新fact中变量值
                        update(work_itemplan_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemplan_work_itemsrfactionparam);//更新fact中变量值
                        update(work_itemplan_work_itemupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "work_itemplan_work_itemdeaction1"
            when
            then
                        work_itemservice.update(work_itemplan_work_itemupdate_obj);
                        update(work_itemplan_work_itemdefault);//更新fact中变量值
                        update(work_itemplan_work_itemfor_temp_obj);//更新fact中变量值
                        update(work_itemplan_work_itemsrfactionparam);//更新fact中变量值
                        update(work_itemplan_work_itemupdate_obj);//更新fact中变量值
            end