package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.recover;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrecoverdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrecoverfor_temp_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrecoverp_work_item;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrecoverwork_item_filter;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrecoverwork_item_page;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemrecoverbegin"
            when
            then
            end

            //逻辑处理节点[设置删除状态]
            rule "prepareparam2"
            ruleflow-group "work_itemrecoverprepareparam2"
            when
            then
                            work_itemrecoverdefault.set("isdeleted","0");
                        update(work_itemrecoverdefault);//更新fact中变量值
                        update(work_itemrecoverfor_temp_obj);//更新fact中变量值
                        update(work_itemrecoverp_work_item);//更新fact中变量值
                        update(work_itemrecoverwork_item_filter);//更新fact中变量值
                        update(work_itemrecoverwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[更新删除状态]
            rule "deaction1"
            ruleflow-group "work_itemrecoverdeaction1"
            when
            then
                        work_itemservice.update(work_itemrecoverdefault);
                        update(work_itemrecoverdefault);//更新fact中变量值
                        update(work_itemrecoverfor_temp_obj);//更新fact中变量值
                        update(work_itemrecoverp_work_item);//更新fact中变量值
                        update(work_itemrecoverwork_item_filter);//更新fact中变量值
                        update(work_itemrecoverwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[设置父工作项非叶子节点]
            rule "prepareparam3"
            ruleflow-group "work_itemrecoverprepareparam3"
            when
            then
                            work_itemrecoverp_work_item.set("id",work_itemrecoverdefault.get("pid"));
                            work_itemrecoverp_work_item.set("isleaf","0");
                        update(work_itemrecoverdefault);//更新fact中变量值
                        update(work_itemrecoverfor_temp_obj);//更新fact中变量值
                        update(work_itemrecoverp_work_item);//更新fact中变量值
                        update(work_itemrecoverwork_item_filter);//更新fact中变量值
                        update(work_itemrecoverwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[更新父工作项非叶子节点]
            rule "deaction2"
            ruleflow-group "work_itemrecoverdeaction2"
            when
            then
                        work_itemservice.update(work_itemrecoverp_work_item);
                        update(work_itemrecoverdefault);//更新fact中变量值
                        update(work_itemrecoverfor_temp_obj);//更新fact中变量值
                        update(work_itemrecoverp_work_item);//更新fact中变量值
                        update(work_itemrecoverwork_item_filter);//更新fact中变量值
                        update(work_itemrecoverwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[恢复最近访问]
            rule "rawsqlcall1"
            ruleflow-group "work_itemrecoverrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",work_itemrecoverdefault.get("id"));
    String strSql="update recent set IS_DELETED=0 where owner_id=#{et.param0} and owner_subtype='work_item'";
                        iBzSysWork_itemDefaultService.execute(strSql,param);//SQL调用
                        update(work_itemrecoverdefault);//更新fact中变量值
                        update(work_itemrecoverfor_temp_obj);//更新fact中变量值
                        update(work_itemrecoverp_work_item);//更新fact中变量值
                        update(work_itemrecoverwork_item_filter);//更新fact中变量值
                        update(work_itemrecoverwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[设置工作项过滤器参数]
            rule "prepareparam1"
            ruleflow-group "work_itemrecoverprepareparam1"
            when
            then
                            work_itemrecoverwork_item_filter.set("n_pid_eq",work_itemrecoverdefault.get("id"));
                        update(work_itemrecoverdefault);//更新fact中变量值
                        update(work_itemrecoverfor_temp_obj);//更新fact中变量值
                        update(work_itemrecoverp_work_item);//更新fact中变量值
                        update(work_itemrecoverwork_item_filter);//更新fact中变量值
                        update(work_itemrecoverwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[查询下级工作项]
            rule "dedataset1"
            ruleflow-group "work_itemrecoverdedataset1"
            when
            then
                        update(work_itemrecoverdefault);//更新fact中变量值
                        update(work_itemrecoverfor_temp_obj);//更新fact中变量值
                        update(work_itemrecoverp_work_item);//更新fact中变量值
                        update(work_itemrecoverwork_item_filter);//更新fact中变量值
                        update(work_itemrecoverwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemrecoverloopsubcall1"
            when
            then
                        update(work_itemrecoverdefault);//更新fact中变量值
                        update(work_itemrecoverfor_temp_obj);//更新fact中变量值
                        update(work_itemrecoverp_work_item);//更新fact中变量值
                        update(work_itemrecoverwork_item_filter);//更新fact中变量值
                        update(work_itemrecoverwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[递归调用]
            rule "delogic1"
            ruleflow-group "work_itemrecoverdelogic1"
            when
            then
                        update(work_itemrecoverdefault);//更新fact中变量值
                        update(work_itemrecoverfor_temp_obj);//更新fact中变量值
                        update(work_itemrecoverp_work_item);//更新fact中变量值
                        update(work_itemrecoverwork_item_filter);//更新fact中变量值
                        update(work_itemrecoverwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemrecoverend1"
            when
            then
                        update(work_itemrecoverdefault);//更新fact中变量值
                        update(work_itemrecoverfor_temp_obj);//更新fact中变量值
                        update(work_itemrecoverp_work_item);//更新fact中变量值
                        update(work_itemrecoverwork_item_filter);//更新fact中变量值
                        update(work_itemrecoverwork_item_page);//更新fact中变量值
            end