package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.remaining_updateform;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemremaining_updateformdefault;
        global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemremaining_updateformbegin"
            when
            then
            end

            //逻辑处理节点[计算工时进度]
            rule "rawsfcode1"
            ruleflow-group "work_itemremaining_updateformrawsfcode1"
            when
            then
                        update(work_itemremaining_updateformdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemremaining_updateformend1"
            when
            then
                        update(work_itemremaining_updateformdefault);//更新fact中变量值
            end