package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.requirement_tree_grid;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrequirement_tree_griddefault;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrequirement_tree_gridchild_filter;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrequirement_tree_gridchild_page;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrequirement_tree_gridchild_temp_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrequirement_tree_gridfor_temp;
                global cn.ibizlab.plm.core.ebsx.domain.SysEmployee work_itemrequirement_tree_gridlist_searchconds;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrequirement_tree_gridpage;
                global java.util.Map work_itemrequirement_tree_gridpage_total;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrequirement_tree_gridresult_list;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrequirement_tree_gridwork_item;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemrequirement_tree_gridbegin"
            when
            then
            end

            //逻辑处理节点[无查询条件默认查询未归档的工作项]
            rule "prepareparam4"
            ruleflow-group "work_itemrequirement_tree_gridprepareparam4"
            when
            then
                            work_itemrequirement_tree_griddefault.set("n_is_archived_eq","0");
                        update(work_itemrequirement_tree_griddefault);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_filter);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_page);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_temp_obj);//更新fact中变量值
                        update(work_itemrequirement_tree_gridfor_temp);//更新fact中变量值
                        update(work_itemrequirement_tree_gridlist_searchconds);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage_total);//更新fact中变量值
                        update(work_itemrequirement_tree_gridresult_list);//更新fact中变量值
                        update(work_itemrequirement_tree_gridwork_item);//更新fact中变量值
            end

            //逻辑处理节点[获取查询条件conds]
            rule "rawsfcode2"
            ruleflow-group "work_itemrequirement_tree_gridrawsfcode2"
            when
            then
                        update(work_itemrequirement_tree_griddefault);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_filter);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_page);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_temp_obj);//更新fact中变量值
                        update(work_itemrequirement_tree_gridfor_temp);//更新fact中变量值
                        update(work_itemrequirement_tree_gridlist_searchconds);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage_total);//更新fact中变量值
                        update(work_itemrequirement_tree_gridresult_list);//更新fact中变量值
                        update(work_itemrequirement_tree_gridwork_item);//更新fact中变量值
            end

            //逻辑处理节点[需求类型工作项]
            rule "prepareparam3"
            ruleflow-group "work_itemrequirement_tree_gridprepareparam3"
            when
            then
                            work_itemrequirement_tree_griddefault.set("n_work_item_type_group_eq","requirement");
                        update(work_itemrequirement_tree_griddefault);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_filter);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_page);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_temp_obj);//更新fact中变量值
                        update(work_itemrequirement_tree_gridfor_temp);//更新fact中变量值
                        update(work_itemrequirement_tree_gridlist_searchconds);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage_total);//更新fact中变量值
                        update(work_itemrequirement_tree_gridresult_list);//更新fact中变量值
                        update(work_itemrequirement_tree_gridwork_item);//更新fact中变量值
            end

            //逻辑处理节点[平铺数据集合]
            rule "dedataset2"
            ruleflow-group "work_itemrequirement_tree_griddedataset2"
            when
            then
                        update(work_itemrequirement_tree_griddefault);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_filter);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_page);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_temp_obj);//更新fact中变量值
                        update(work_itemrequirement_tree_gridfor_temp);//更新fact中变量值
                        update(work_itemrequirement_tree_gridlist_searchconds);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage_total);//更新fact中变量值
                        update(work_itemrequirement_tree_gridresult_list);//更新fact中变量值
                        update(work_itemrequirement_tree_gridwork_item);//更新fact中变量值
            end

            //逻辑处理节点[获取顶级工作项]
            rule "dedataset1"
            ruleflow-group "work_itemrequirement_tree_griddedataset1"
            when
            then
                        update(work_itemrequirement_tree_griddefault);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_filter);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_page);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_temp_obj);//更新fact中变量值
                        update(work_itemrequirement_tree_gridfor_temp);//更新fact中变量值
                        update(work_itemrequirement_tree_gridlist_searchconds);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage_total);//更新fact中变量值
                        update(work_itemrequirement_tree_gridresult_list);//更新fact中变量值
                        update(work_itemrequirement_tree_gridwork_item);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemrequirement_tree_gridloopsubcall1"
            when
            then
                        update(work_itemrequirement_tree_griddefault);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_filter);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_page);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_temp_obj);//更新fact中变量值
                        update(work_itemrequirement_tree_gridfor_temp);//更新fact中变量值
                        update(work_itemrequirement_tree_gridlist_searchconds);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage_total);//更新fact中变量值
                        update(work_itemrequirement_tree_gridresult_list);//更新fact中变量值
                        update(work_itemrequirement_tree_gridwork_item);//更新fact中变量值
            end

            //逻辑处理节点[拼接top_ids]
            rule "rawsfcode1"
            ruleflow-group "work_itemrequirement_tree_gridrawsfcode1"
            when
            then
                        update(work_itemrequirement_tree_griddefault);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_filter);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_page);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_temp_obj);//更新fact中变量值
                        update(work_itemrequirement_tree_gridfor_temp);//更新fact中变量值
                        update(work_itemrequirement_tree_gridlist_searchconds);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage_total);//更新fact中变量值
                        update(work_itemrequirement_tree_gridresult_list);//更新fact中变量值
                        update(work_itemrequirement_tree_gridwork_item);//更新fact中变量值
            end

            //逻辑处理节点[附加到数组参数]
            rule "appendparam1"
            ruleflow-group "work_itemrequirement_tree_gridappendparam1"
            when
            then
                        update(work_itemrequirement_tree_griddefault);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_filter);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_page);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_temp_obj);//更新fact中变量值
                        update(work_itemrequirement_tree_gridfor_temp);//更新fact中变量值
                        update(work_itemrequirement_tree_gridlist_searchconds);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage_total);//更新fact中变量值
                        update(work_itemrequirement_tree_gridresult_list);//更新fact中变量值
                        update(work_itemrequirement_tree_gridwork_item);//更新fact中变量值
            end

            //逻辑处理节点[top_ids放入过滤器]
            rule "prepareparam1"
            ruleflow-group "work_itemrequirement_tree_gridprepareparam1"
            when
            then
                            work_itemrequirement_tree_gridchild_filter.set("n_top_id_in",work_itemrequirement_tree_gridwork_item.get("top_ids"));
                            work_itemrequirement_tree_gridchild_filter.set("size","1000");
                            work_itemrequirement_tree_gridchild_filter.set("n_work_item_type_group_eq","requirement");
                        update(work_itemrequirement_tree_griddefault);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_filter);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_page);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_temp_obj);//更新fact中变量值
                        update(work_itemrequirement_tree_gridfor_temp);//更新fact中变量值
                        update(work_itemrequirement_tree_gridlist_searchconds);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage_total);//更新fact中变量值
                        update(work_itemrequirement_tree_gridresult_list);//更新fact中变量值
                        update(work_itemrequirement_tree_gridwork_item);//更新fact中变量值
            end

            //逻辑处理节点[顶级工作项下的所有子工作项]
            rule "dedataset3"
            ruleflow-group "work_itemrequirement_tree_griddedataset3"
            when
            then
                        update(work_itemrequirement_tree_griddefault);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_filter);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_page);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_temp_obj);//更新fact中变量值
                        update(work_itemrequirement_tree_gridfor_temp);//更新fact中变量值
                        update(work_itemrequirement_tree_gridlist_searchconds);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage_total);//更新fact中变量值
                        update(work_itemrequirement_tree_gridresult_list);//更新fact中变量值
                        update(work_itemrequirement_tree_gridwork_item);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall2"
            ruleflow-group "work_itemrequirement_tree_gridloopsubcall2"
            when
            then
                        update(work_itemrequirement_tree_griddefault);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_filter);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_page);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_temp_obj);//更新fact中变量值
                        update(work_itemrequirement_tree_gridfor_temp);//更新fact中变量值
                        update(work_itemrequirement_tree_gridlist_searchconds);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage_total);//更新fact中变量值
                        update(work_itemrequirement_tree_gridresult_list);//更新fact中变量值
                        update(work_itemrequirement_tree_gridwork_item);//更新fact中变量值
            end

            //逻辑处理节点[附加到数组参数]
            rule "appendparam2"
            ruleflow-group "work_itemrequirement_tree_gridappendparam2"
            when
            then
                        update(work_itemrequirement_tree_griddefault);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_filter);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_page);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_temp_obj);//更新fact中变量值
                        update(work_itemrequirement_tree_gridfor_temp);//更新fact中变量值
                        update(work_itemrequirement_tree_gridlist_searchconds);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage_total);//更新fact中变量值
                        update(work_itemrequirement_tree_gridresult_list);//更新fact中变量值
                        update(work_itemrequirement_tree_gridwork_item);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "work_itemrequirement_tree_gridbindparam1"
            when
            then
                        update(work_itemrequirement_tree_griddefault);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_filter);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_page);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_temp_obj);//更新fact中变量值
                        update(work_itemrequirement_tree_gridfor_temp);//更新fact中变量值
                        update(work_itemrequirement_tree_gridlist_searchconds);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage_total);//更新fact中变量值
                        update(work_itemrequirement_tree_gridresult_list);//更新fact中变量值
                        update(work_itemrequirement_tree_gridwork_item);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemrequirement_tree_gridend1"
            when
            then
                        update(work_itemrequirement_tree_griddefault);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_filter);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_page);//更新fact中变量值
                        update(work_itemrequirement_tree_gridchild_temp_obj);//更新fact中变量值
                        update(work_itemrequirement_tree_gridfor_temp);//更新fact中变量值
                        update(work_itemrequirement_tree_gridlist_searchconds);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage);//更新fact中变量值
                        update(work_itemrequirement_tree_gridpage_total);//更新fact中变量值
                        update(work_itemrequirement_tree_gridresult_list);//更新fact中变量值
                        update(work_itemrequirement_tree_gridwork_item);//更新fact中变量值
            end