package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.restore_version;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemrestore_versiondefault;
                global cn.ibizlab.plm.core.base.domain.version work_itemrestore_versionversion;
                    global cn.ibizlab.plm.core.base.service.IversionService versionservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemrestore_versionbegin"
            when
            then
            end

            //逻辑处理节点[提取版本]
            rule "prepareparam"
            ruleflow-group "work_itemrestore_versionprepareparam"
            when
            then
                            work_itemrestore_versionversion.set("id",work_itemrestore_versiondefault.get("srfversionid"));
                            work_itemrestore_versionversion.set("ownertype","WORK_ITEM");
                            work_itemrestore_versionversion.set("ownerid",work_itemrestore_versiondefault.get("id"));
                        update(work_itemrestore_versiondefault);//更新fact中变量值
                        update(work_itemrestore_versionversion);//更新fact中变量值
            end

            //逻辑处理节点[恢复版本]
            rule "deaction"
            ruleflow-group "work_itemrestore_versiondeaction"
            when
            then
                        versionservice.restore(work_itemrestore_versionversion);
                        update(work_itemrestore_versiondefault);//更新fact中变量值
                        update(work_itemrestore_versionversion);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemrestore_versionend1"
            when
            then
                        update(work_itemrestore_versiondefault);//更新fact中变量值
                        update(work_itemrestore_versionversion);//更新fact中变量值
            end