package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.set_sequence;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemset_sequencedefault;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemset_sequencebegin"
            when
            then
            end

            //逻辑处理节点[设置初始排序值]
            rule "prepareparam1"
            ruleflow-group "work_itemset_sequenceprepareparam1"
            when
            then
                            work_itemset_sequencedefault.set("sequence",work_itemset_sequencedefault.get("identifier"));
                        update(work_itemset_sequencedefault);//更新fact中变量值
            end

            //逻辑处理节点[处理初始排序值]
            rule "rawsfcode1"
            ruleflow-group "work_itemset_sequencerawsfcode1"
            when
            then
                        update(work_itemset_sequencedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemset_sequenceend1"
            when
            then
                        update(work_itemset_sequencedefault);//更新fact中变量值
            end