package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.shift_out_release;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemshift_out_releasedefault;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemshift_out_releaseupdate_obj;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemshift_out_releasebegin"
            when
            then
            end

            //逻辑处理节点[置空发布标识]
            rule "prepareparam1"
            ruleflow-group "work_itemshift_out_releaseprepareparam1"
            when
            then
                            work_itemshift_out_releaseupdate_obj.set("id",work_itemshift_out_releasedefault.get("id"));
                                work_itemshift_out_releaseupdate_obj.set("releaseid",null);
                        update(work_itemshift_out_releasedefault);//更新fact中变量值
                        update(work_itemshift_out_releaseupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[更新工作项]
            rule "deaction1"
            ruleflow-group "work_itemshift_out_releasedeaction1"
            when
            then
                        work_itemservice.update(work_itemshift_out_releaseupdate_obj);
                        update(work_itemshift_out_releasedefault);//更新fact中变量值
                        update(work_itemshift_out_releaseupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemshift_out_releaseend1"
            when
            then
                        update(work_itemshift_out_releasedefault);//更新fact中变量值
                        update(work_itemshift_out_releaseupdate_obj);//更新fact中变量值
            end