package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.shift_in_baseline;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemshift_in_baselinedefault;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemshift_in_baselinefor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.relation work_itemshift_in_baselinerelation;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemshift_in_baselinesrfactionparam;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemshift_in_baselinebegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "work_itemshift_in_baselinebindparam1"
            when
            then
                        update(work_itemshift_in_baselinedefault);//更新fact中变量值
                        update(work_itemshift_in_baselinefor_temp_obj);//更新fact中变量值
                        update(work_itemshift_in_baselinerelation);//更新fact中变量值
                        update(work_itemshift_in_baselinesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemshift_in_baselineloopsubcall1"
            when
            then
                        update(work_itemshift_in_baselinedefault);//更新fact中变量值
                        update(work_itemshift_in_baselinefor_temp_obj);//更新fact中变量值
                        update(work_itemshift_in_baselinerelation);//更新fact中变量值
                        update(work_itemshift_in_baselinesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[重置参数]
            rule "resetparam1"
            ruleflow-group "work_itemshift_in_baselineresetparam1"
            when
            then
                        update(work_itemshift_in_baselinedefault);//更新fact中变量值
                        update(work_itemshift_in_baselinefor_temp_obj);//更新fact中变量值
                        update(work_itemshift_in_baselinerelation);//更新fact中变量值
                        update(work_itemshift_in_baselinesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[填充关联属性]
            rule "prepareparam1"
            ruleflow-group "work_itemshift_in_baselineprepareparam1"
            when
            then
                            work_itemshift_in_baselinerelation.set("principalid",work_itemshift_in_baselinedefault.get("baseline_id"));
                            work_itemshift_in_baselinerelation.set("targetversionid",work_itemshift_in_baselinefor_temp_obj.get("chooseversionid"));
                            work_itemshift_in_baselinerelation.set("targetid",work_itemshift_in_baselinefor_temp_obj.get("id"));
                            work_itemshift_in_baselinerelation.set("targettype","work_item");
                            work_itemshift_in_baselinerelation.set("principaltype","baseline");
                        update(work_itemshift_in_baselinedefault);//更新fact中变量值
                        update(work_itemshift_in_baselinefor_temp_obj);//更新fact中变量值
                        update(work_itemshift_in_baselinerelation);//更新fact中变量值
                        update(work_itemshift_in_baselinesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[建立基线-工作项关联数据]
            rule "deaction1"
            ruleflow-group "work_itemshift_in_baselinedeaction1"
            when
            then
                        relationservice.save(work_itemshift_in_baselinerelation);
                        update(work_itemshift_in_baselinedefault);//更新fact中变量值
                        update(work_itemshift_in_baselinefor_temp_obj);//更新fact中变量值
                        update(work_itemshift_in_baselinerelation);//更新fact中变量值
                        update(work_itemshift_in_baselinesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemshift_in_baselineend1"
            when
            then
                        update(work_itemshift_in_baselinedefault);//更新fact中变量值
                        update(work_itemshift_in_baselinefor_temp_obj);//更新fact中变量值
                        update(work_itemshift_in_baselinerelation);//更新fact中变量值
                        update(work_itemshift_in_baselinesrfactionparam);//更新fact中变量值
            end