package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.shift_out_sprint;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemshift_out_sprintdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemshift_out_sprintupdate_obj;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemshift_out_sprintbegin"
            when
            then
            end

            //逻辑处理节点[置空迭代标识]
            rule "prepareparam1"
            ruleflow-group "work_itemshift_out_sprintprepareparam1"
            when
            then
                            work_itemshift_out_sprintupdate_obj.set("id",work_itemshift_out_sprintdefault.get("id"));
                                work_itemshift_out_sprintupdate_obj.set("sprintid",null);
                        update(work_itemshift_out_sprintdefault);//更新fact中变量值
                        update(work_itemshift_out_sprintupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[更新工作项]
            rule "deaction1"
            ruleflow-group "work_itemshift_out_sprintdeaction1"
            when
            then
                        work_itemservice.update(work_itemshift_out_sprintupdate_obj);
                        update(work_itemshift_out_sprintdefault);//更新fact中变量值
                        update(work_itemshift_out_sprintupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemshift_out_sprintend1"
            when
            then
                        update(work_itemshift_out_sprintdefault);//更新fact中变量值
                        update(work_itemshift_out_sprintupdate_obj);//更新fact中变量值
            end