package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.shift_in_kanban;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemshift_in_kanbandefault;
                global cn.ibizlab.plm.core.projmgmt.domain.Entry work_itemshift_in_kanbanentry;
                global cn.ibizlab.plm.core.projmgmt.domain.Entry work_itemshift_in_kanbanentry_filter;
                global cn.ibizlab.plm.core.projmgmt.domain.Entry work_itemshift_in_kanbanentry_page;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemshift_in_kanbanfor_temp_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemshift_in_kanbansrfactionparam;
                    global cn.ibizlab.plm.core.projmgmt.service.IEntryService entryservice;
                    global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemshift_in_kanbanbegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "work_itemshift_in_kanbanbindparam1"
            when
            then
                        update(work_itemshift_in_kanbandefault);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry_filter);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry_page);//更新fact中变量值
                        update(work_itemshift_in_kanbanfor_temp_obj);//更新fact中变量值
                        update(work_itemshift_in_kanbansrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam2"
            ruleflow-group "work_itemshift_in_kanbanbindparam2"
            when
            then
                        update(work_itemshift_in_kanbandefault);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry_filter);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry_page);//更新fact中变量值
                        update(work_itemshift_in_kanbanfor_temp_obj);//更新fact中变量值
                        update(work_itemshift_in_kanbansrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[填充看板栏标识]
            rule "prepareparam3"
            ruleflow-group "work_itemshift_in_kanbanprepareparam3"
            when
            then
                            work_itemshift_in_kanbandefault.set("entryid",work_itemshift_in_kanbanentry.get("id"));
                        update(work_itemshift_in_kanbandefault);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry_filter);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry_page);//更新fact中变量值
                        update(work_itemshift_in_kanbanfor_temp_obj);//更新fact中变量值
                        update(work_itemshift_in_kanbansrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "work_itemshift_in_kanbandedataset1"
            when
            then
                        update(work_itemshift_in_kanbandefault);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry_filter);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry_page);//更新fact中变量值
                        update(work_itemshift_in_kanbanfor_temp_obj);//更新fact中变量值
                        update(work_itemshift_in_kanbansrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemshift_in_kanbanloopsubcall1"
            when
            then
                        update(work_itemshift_in_kanbandefault);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry_filter);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry_page);//更新fact中变量值
                        update(work_itemshift_in_kanbanfor_temp_obj);//更新fact中变量值
                        update(work_itemshift_in_kanbansrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "work_itemshift_in_kanbanprepareparam2"
            when
            then
                            work_itemshift_in_kanbandefault.set("boardid",work_itemshift_in_kanbanfor_temp_obj.get("target_board_id"));
                            work_itemshift_in_kanbanentry_filter.set("sort","showorder,asc");
                            work_itemshift_in_kanbanentry_filter.set("n_board_id_eq",work_itemshift_in_kanbanfor_temp_obj.get("target_board_id"));
                        update(work_itemshift_in_kanbandefault);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry_filter);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry_page);//更新fact中变量值
                        update(work_itemshift_in_kanbanfor_temp_obj);//更新fact中变量值
                        update(work_itemshift_in_kanbansrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[移入看板]
            rule "deaction1"
            ruleflow-group "work_itemshift_in_kanbandeaction1"
            when
            then
                        work_itemservice.update(work_itemshift_in_kanbandefault);
                        update(work_itemshift_in_kanbandefault);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry_filter);//更新fact中变量值
                        update(work_itemshift_in_kanbanentry_page);//更新fact中变量值
                        update(work_itemshift_in_kanbanfor_temp_obj);//更新fact中变量值
                        update(work_itemshift_in_kanbansrfactionparam);//更新fact中变量值
            end