package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.shift_in_version;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemshift_in_versiondefault;
                global cn.ibizlab.plm.core.projmgmt.domain.release work_itemshift_in_versionfor_temp_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.release work_itemshift_in_versionsrfactionparam;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemshift_in_versionbegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "work_itemshift_in_versionbindparam1"
            when
            then
                        update(work_itemshift_in_versiondefault);//更新fact中变量值
                        update(work_itemshift_in_versionfor_temp_obj);//更新fact中变量值
                        update(work_itemshift_in_versionsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemshift_in_versionloopsubcall1"
            when
            then
                        update(work_itemshift_in_versiondefault);//更新fact中变量值
                        update(work_itemshift_in_versionfor_temp_obj);//更新fact中变量值
                        update(work_itemshift_in_versionsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[填充发布标识]
            rule "prepareparam1"
            ruleflow-group "work_itemshift_in_versionprepareparam1"
            when
            then
                            work_itemshift_in_versiondefault.set("releaseid",work_itemshift_in_versionfor_temp_obj.get("id"));
                        update(work_itemshift_in_versiondefault);//更新fact中变量值
                        update(work_itemshift_in_versionfor_temp_obj);//更新fact中变量值
                        update(work_itemshift_in_versionsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[更新工作项的发布标识]
            rule "deaction1"
            ruleflow-group "work_itemshift_in_versiondeaction1"
            when
            then
                        work_itemservice.update(work_itemshift_in_versiondefault);
                        update(work_itemshift_in_versiondefault);//更新fact中变量值
                        update(work_itemshift_in_versionfor_temp_obj);//更新fact中变量值
                        update(work_itemshift_in_versionsrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemshift_in_versionend1"
            when
            then
                        update(work_itemshift_in_versiondefault);//更新fact中变量值
                        update(work_itemshift_in_versionfor_temp_obj);//更新fact中变量值
                        update(work_itemshift_in_versionsrfactionparam);//更新fact中变量值
            end