package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.shift_out_baseline;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemshift_out_baselinedefault;
                global cn.ibizlab.plm.core.base.domain.relation work_itemshift_out_baselinerelation;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemshift_out_baselinebegin"
            when
            then
            end

            //逻辑处理节点[填充关联属性]
            rule "prepareparam1"
            ruleflow-group "work_itemshift_out_baselineprepareparam1"
            when
            then
                            work_itemshift_out_baselinerelation.set("principalid",work_itemshift_out_baselinedefault.get("baseline_id"));
                            work_itemshift_out_baselinerelation.set("targetid",work_itemshift_out_baselinedefault.get("id"));
                            work_itemshift_out_baselinerelation.set("targettype","work_item");
                            work_itemshift_out_baselinerelation.set("principaltype","baseline");
                        update(work_itemshift_out_baselinedefault);//更新fact中变量值
                        update(work_itemshift_out_baselinerelation);//更新fact中变量值
            end

            //逻辑处理节点[获取关联对象主键]
            rule "rawsfcode1"
            ruleflow-group "work_itemshift_out_baselinerawsfcode1"
            when
            then
                        update(work_itemshift_out_baselinedefault);//更新fact中变量值
                        update(work_itemshift_out_baselinerelation);//更新fact中变量值
            end

            //逻辑处理节点[删除基线-工作项关联数据]
            rule "deaction1"
            ruleflow-group "work_itemshift_out_baselinedeaction1"
            when
            then
                        relationservice.remove(work_itemshift_out_baselinerelation.getId());
                        update(work_itemshift_out_baselinedefault);//更新fact中变量值
                        update(work_itemshift_out_baselinerelation);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemshift_out_baselineend1"
            when
            then
                        update(work_itemshift_out_baselinedefault);//更新fact中变量值
                        update(work_itemshift_out_baselinerelation);//更新fact中变量值
            end