package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.shift_in_sprint;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemshift_in_sprintdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.Sprint work_itemshift_in_sprintsrfactionparam;
                global cn.ibizlab.plm.core.projmgmt.domain.Sprint work_itemshift_in_sprinttemp_obj;
                    global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemshift_in_sprintbegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "work_itemshift_in_sprintbindparam1"
            when
            then
                        update(work_itemshift_in_sprintdefault);//更新fact中变量值
                        update(work_itemshift_in_sprintsrfactionparam);//更新fact中变量值
                        update(work_itemshift_in_sprinttemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemshift_in_sprintloopsubcall1"
            when
            then
                        update(work_itemshift_in_sprintdefault);//更新fact中变量值
                        update(work_itemshift_in_sprintsrfactionparam);//更新fact中变量值
                        update(work_itemshift_in_sprinttemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[填充sprint_id]
            rule "prepareparam1"
            ruleflow-group "work_itemshift_in_sprintprepareparam1"
            when
            then
                            work_itemshift_in_sprintdefault.set("sprintid",work_itemshift_in_sprinttemp_obj.get("id"));
                        update(work_itemshift_in_sprintdefault);//更新fact中变量值
                        update(work_itemshift_in_sprintsrfactionparam);//更新fact中变量值
                        update(work_itemshift_in_sprinttemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[移入迭代]
            rule "deaction1"
            ruleflow-group "work_itemshift_in_sprintdeaction1"
            when
            then
                        work_itemservice.update(work_itemshift_in_sprintdefault);
                        update(work_itemshift_in_sprintdefault);//更新fact中变量值
                        update(work_itemshift_in_sprintsrfactionparam);//更新fact中变量值
                        update(work_itemshift_in_sprinttemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemshift_in_sprintend1"
            when
            then
                        update(work_itemshift_in_sprintdefault);//更新fact中变量值
                        update(work_itemshift_in_sprintsrfactionparam);//更新fact中变量值
                        update(work_itemshift_in_sprinttemp_obj);//更新fact中变量值
            end