package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.sprint_contribution;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemsprint_contributiondefault;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemsprint_contributionfor_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemsprint_contributionresult_list;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemsprint_contributionwork_item_page;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemsprint_contributionbegin"
            when
            then
            end

            //逻辑处理节点[准备工作项查询过滤器参数]
            rule "prepareparam1"
            ruleflow-group "work_itemsprint_contributionprepareparam1"
            when
            then
                            work_itemsprint_contributiondefault.set("size","10000");
                            work_itemsprint_contributiondefault.set("n_project_id_eq",work_itemsprint_contributiondefault.get("project"));
                            work_itemsprint_contributiondefault.set("n_sprint_id_eq",work_itemsprint_contributiondefault.get("sprint"));
                            work_itemsprint_contributiondefault.set("n_is_deleted_eq","0");
                        update(work_itemsprint_contributiondefault);//更新fact中变量值
                        update(work_itemsprint_contributionfor_obj);//更新fact中变量值
                        update(work_itemsprint_contributionresult_list);//更新fact中变量值
                        update(work_itemsprint_contributionwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[查询此迭代下的工作项]
            rule "dedataset1"
            ruleflow-group "work_itemsprint_contributiondedataset1"
            when
            then
                        update(work_itemsprint_contributiondefault);//更新fact中变量值
                        update(work_itemsprint_contributionfor_obj);//更新fact中变量值
                        update(work_itemsprint_contributionresult_list);//更新fact中变量值
                        update(work_itemsprint_contributionwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemsprint_contributionloopsubcall1"
            when
            then
                        update(work_itemsprint_contributiondefault);//更新fact中变量值
                        update(work_itemsprint_contributionfor_obj);//更新fact中变量值
                        update(work_itemsprint_contributionresult_list);//更新fact中变量值
                        update(work_itemsprint_contributionwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[计算统计数字]
            rule "rawsfcode1"
            ruleflow-group "work_itemsprint_contributionrawsfcode1"
            when
            then
                        update(work_itemsprint_contributiondefault);//更新fact中变量值
                        update(work_itemsprint_contributionfor_obj);//更新fact中变量值
                        update(work_itemsprint_contributionresult_list);//更新fact中变量值
                        update(work_itemsprint_contributionwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[绑定工作项分页查询结果]
            rule "bindparam1"
            ruleflow-group "work_itemsprint_contributionbindparam1"
            when
            then
                        update(work_itemsprint_contributiondefault);//更新fact中变量值
                        update(work_itemsprint_contributionfor_obj);//更新fact中变量值
                        update(work_itemsprint_contributionresult_list);//更新fact中变量值
                        update(work_itemsprint_contributionwork_item_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemsprint_contributionend1"
            when
            then
                        update(work_itemsprint_contributiondefault);//更新fact中变量值
                        update(work_itemsprint_contributionfor_obj);//更新fact中变量值
                        update(work_itemsprint_contributionresult_list);//更新fact中变量值
                        update(work_itemsprint_contributionwork_item_page);//更新fact中变量值
            end