package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.top_work_item;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemtop_work_itemdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.Work_item work_itemtop_work_itemparent_item;
                    global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.IWork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemtop_work_itembegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "work_itemtop_work_itemprepareparam1"
            when
            then
                            work_itemtop_work_itemparent_item.set("id",work_itemtop_work_itemdefault.get("pid"));
                        update(work_itemtop_work_itemdefault);//更新fact中变量值
                        update(work_itemtop_work_itemparent_item);//更新fact中变量值
            end

            //逻辑处理节点[获取父工作项的顶级工作项]
            rule "deaction1"
            ruleflow-group "work_itemtop_work_itemdeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(work_itemservice.get(work_itemtop_work_itemparent_item.getId()),work_itemtop_work_itemparent_item);
                        update(work_itemtop_work_itemdefault);//更新fact中变量值
                        update(work_itemtop_work_itemparent_item);//更新fact中变量值
            end

            //逻辑处理节点[父工作项就是子工作项的顶级]
            rule "prepareparam3"
            ruleflow-group "work_itemtop_work_itemprepareparam3"
            when
            then
                            work_itemtop_work_itemdefault.set("topid",work_itemtop_work_itemparent_item.get("id"));
                        update(work_itemtop_work_itemdefault);//更新fact中变量值
                        update(work_itemtop_work_itemparent_item);//更新fact中变量值
            end

            //逻辑处理节点[继承父工作项的顶级标识]
            rule "prepareparam2"
            ruleflow-group "work_itemtop_work_itemprepareparam2"
            when
            then
                            work_itemtop_work_itemdefault.set("topid",work_itemtop_work_itemparent_item.get("topid"));
                        update(work_itemtop_work_itemdefault);//更新fact中变量值
                        update(work_itemtop_work_itemparent_item);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemtop_work_itemend1"
            when
            then
                        update(work_itemtop_work_itemdefault);//更新fact中变量值
                        update(work_itemtop_work_itemparent_item);//更新fact中变量值
            end