package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.tree_tile_grid_query;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemtree_tile_grid_querydefault;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemtree_tile_grid_querychild_filter;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemtree_tile_grid_querychild_page;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemtree_tile_grid_querychild_temp_obj;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemtree_tile_grid_queryfor_temp;
                global cn.ibizlab.plm.core.ebsx.domain.SysEmployee work_itemtree_tile_grid_querylist_searchconds;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemtree_tile_grid_querypage;
                global java.util.Map work_itemtree_tile_grid_querypage_total;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemtree_tile_grid_queryresult_list;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemtree_tile_grid_querywork_item;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemtree_tile_grid_querybegin"
            when
            then
            end

            //逻辑处理节点[无查询条件默认查询未归档的工作项]
            rule "prepareparam4"
            ruleflow-group "work_itemtree_tile_grid_queryprepareparam4"
            when
            then
                            work_itemtree_tile_grid_querydefault.set("n_is_archived_eq","0");
                        update(work_itemtree_tile_grid_querydefault);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_filter);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_page);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_temp_obj);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryfor_temp);//更新fact中变量值
                        update(work_itemtree_tile_grid_querylist_searchconds);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage_total);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryresult_list);//更新fact中变量值
                        update(work_itemtree_tile_grid_querywork_item);//更新fact中变量值
            end

            //逻辑处理节点[设置默认值（test）]
            rule "prepareparam5"
            ruleflow-group "work_itemtree_tile_grid_queryprepareparam5"
            when
            then
                            work_itemtree_tile_grid_querydefault.set("n_project_id_eq","cc1ca882-84ed-cf02-b1a7-b6a2d2569a23");
                        update(work_itemtree_tile_grid_querydefault);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_filter);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_page);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_temp_obj);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryfor_temp);//更新fact中变量值
                        update(work_itemtree_tile_grid_querylist_searchconds);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage_total);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryresult_list);//更新fact中变量值
                        update(work_itemtree_tile_grid_querywork_item);//更新fact中变量值
            end

            //逻辑处理节点[平铺数据集合]
            rule "dedataset2"
            ruleflow-group "work_itemtree_tile_grid_querydedataset2"
            when
            then
                        update(work_itemtree_tile_grid_querydefault);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_filter);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_page);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_temp_obj);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryfor_temp);//更新fact中变量值
                        update(work_itemtree_tile_grid_querylist_searchconds);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage_total);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryresult_list);//更新fact中变量值
                        update(work_itemtree_tile_grid_querywork_item);//更新fact中变量值
            end

            //逻辑处理节点[获取查询条件conds]
            rule "rawsfcode2"
            ruleflow-group "work_itemtree_tile_grid_queryrawsfcode2"
            when
            then
                        update(work_itemtree_tile_grid_querydefault);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_filter);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_page);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_temp_obj);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryfor_temp);//更新fact中变量值
                        update(work_itemtree_tile_grid_querylist_searchconds);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage_total);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryresult_list);//更新fact中变量值
                        update(work_itemtree_tile_grid_querywork_item);//更新fact中变量值
            end

            //逻辑处理节点[需求类型工作项]
            rule "prepareparam3"
            ruleflow-group "work_itemtree_tile_grid_queryprepareparam3"
            when
            then
                            work_itemtree_tile_grid_querydefault.set("n_work_item_type_group_eq","requirement");
                            work_itemtree_tile_grid_querydefault.set("n_project_id_eq","cc1ca882-84ed-cf02-b1a7-b6a2d2569a23");
                        update(work_itemtree_tile_grid_querydefault);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_filter);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_page);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_temp_obj);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryfor_temp);//更新fact中变量值
                        update(work_itemtree_tile_grid_querylist_searchconds);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage_total);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryresult_list);//更新fact中变量值
                        update(work_itemtree_tile_grid_querywork_item);//更新fact中变量值
            end

            //逻辑处理节点[获取顶级工作项]
            rule "dedataset1"
            ruleflow-group "work_itemtree_tile_grid_querydedataset1"
            when
            then
                        update(work_itemtree_tile_grid_querydefault);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_filter);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_page);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_temp_obj);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryfor_temp);//更新fact中变量值
                        update(work_itemtree_tile_grid_querylist_searchconds);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage_total);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryresult_list);//更新fact中变量值
                        update(work_itemtree_tile_grid_querywork_item);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "work_itemtree_tile_grid_queryloopsubcall1"
            when
            then
                        update(work_itemtree_tile_grid_querydefault);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_filter);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_page);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_temp_obj);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryfor_temp);//更新fact中变量值
                        update(work_itemtree_tile_grid_querylist_searchconds);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage_total);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryresult_list);//更新fact中变量值
                        update(work_itemtree_tile_grid_querywork_item);//更新fact中变量值
            end

            //逻辑处理节点[拼接top_ids]
            rule "rawsfcode1"
            ruleflow-group "work_itemtree_tile_grid_queryrawsfcode1"
            when
            then
                        update(work_itemtree_tile_grid_querydefault);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_filter);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_page);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_temp_obj);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryfor_temp);//更新fact中变量值
                        update(work_itemtree_tile_grid_querylist_searchconds);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage_total);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryresult_list);//更新fact中变量值
                        update(work_itemtree_tile_grid_querywork_item);//更新fact中变量值
            end

            //逻辑处理节点[附加到数组参数]
            rule "appendparam1"
            ruleflow-group "work_itemtree_tile_grid_queryappendparam1"
            when
            then
                        update(work_itemtree_tile_grid_querydefault);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_filter);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_page);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_temp_obj);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryfor_temp);//更新fact中变量值
                        update(work_itemtree_tile_grid_querylist_searchconds);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage_total);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryresult_list);//更新fact中变量值
                        update(work_itemtree_tile_grid_querywork_item);//更新fact中变量值
            end

            //逻辑处理节点[top_ids放入过滤器]
            rule "prepareparam1"
            ruleflow-group "work_itemtree_tile_grid_queryprepareparam1"
            when
            then
                            work_itemtree_tile_grid_querychild_filter.set("n_top_id_in",work_itemtree_tile_grid_querywork_item.get("top_ids"));
                            work_itemtree_tile_grid_querychild_filter.set("n_project_id_eq","cc1ca882-84ed-cf02-b1a7-b6a2d2569a23");
                            work_itemtree_tile_grid_querychild_filter.set("size","1000");
                            work_itemtree_tile_grid_querychild_filter.set("n_work_item_type_group_eq","requirement");
                        update(work_itemtree_tile_grid_querydefault);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_filter);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_page);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_temp_obj);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryfor_temp);//更新fact中变量值
                        update(work_itemtree_tile_grid_querylist_searchconds);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage_total);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryresult_list);//更新fact中变量值
                        update(work_itemtree_tile_grid_querywork_item);//更新fact中变量值
            end

            //逻辑处理节点[顶级工作项下的所有子工作项]
            rule "dedataset3"
            ruleflow-group "work_itemtree_tile_grid_querydedataset3"
            when
            then
                        update(work_itemtree_tile_grid_querydefault);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_filter);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_page);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_temp_obj);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryfor_temp);//更新fact中变量值
                        update(work_itemtree_tile_grid_querylist_searchconds);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage_total);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryresult_list);//更新fact中变量值
                        update(work_itemtree_tile_grid_querywork_item);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall2"
            ruleflow-group "work_itemtree_tile_grid_queryloopsubcall2"
            when
            then
                        update(work_itemtree_tile_grid_querydefault);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_filter);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_page);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_temp_obj);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryfor_temp);//更新fact中变量值
                        update(work_itemtree_tile_grid_querylist_searchconds);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage_total);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryresult_list);//更新fact中变量值
                        update(work_itemtree_tile_grid_querywork_item);//更新fact中变量值
            end

            //逻辑处理节点[附加到数组参数]
            rule "appendparam2"
            ruleflow-group "work_itemtree_tile_grid_queryappendparam2"
            when
            then
                        update(work_itemtree_tile_grid_querydefault);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_filter);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_page);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_temp_obj);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryfor_temp);//更新fact中变量值
                        update(work_itemtree_tile_grid_querylist_searchconds);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage_total);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryresult_list);//更新fact中变量值
                        update(work_itemtree_tile_grid_querywork_item);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "work_itemtree_tile_grid_querybindparam1"
            when
            then
                        update(work_itemtree_tile_grid_querydefault);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_filter);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_page);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_temp_obj);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryfor_temp);//更新fact中变量值
                        update(work_itemtree_tile_grid_querylist_searchconds);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage_total);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryresult_list);//更新fact中变量值
                        update(work_itemtree_tile_grid_querywork_item);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemtree_tile_grid_queryend1"
            when
            then
                        update(work_itemtree_tile_grid_querydefault);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_filter);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_page);//更新fact中变量值
                        update(work_itemtree_tile_grid_querychild_temp_obj);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryfor_temp);//更新fact中变量值
                        update(work_itemtree_tile_grid_querylist_searchconds);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage);//更新fact中变量值
                        update(work_itemtree_tile_grid_querypage_total);//更新fact中变量值
                        update(work_itemtree_tile_grid_queryresult_list);//更新fact中变量值
                        update(work_itemtree_tile_grid_querywork_item);//更新fact中变量值
            end