package cn.ibizlab.plm.projmgmt.logic.work_itemlogic.work_item_test_plan_project;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item work_itemwork_item_test_plan_projectdefault;
                global java.util.Map work_itemwork_item_test_plan_projectctx;
                global cn.ibizlab.plm.core.testmgmt.domain.test_plan work_itemwork_item_test_plan_projecttest_plan;
                    global cn.ibizlab.plm.core.testmgmt.service.Itest_planService test_planservice;
        global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService iBzSysWork_itemDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "work_itemwork_item_test_plan_projectbegin"
            when
            then
            end

            //逻辑处理节点[绑定测试计划id]
            rule "prepareparam1"
            ruleflow-group "work_itemwork_item_test_plan_projectprepareparam1"
            when
            then
                            work_itemwork_item_test_plan_projecttest_plan.set("id",work_itemwork_item_test_plan_projectdefault.get("testplanid"));
                        update(work_itemwork_item_test_plan_projectdefault);//更新fact中变量值
                        update(work_itemwork_item_test_plan_projectctx);//更新fact中变量值
                        update(work_itemwork_item_test_plan_projecttest_plan);//更新fact中变量值
            end

            //逻辑处理节点[获取test_plan关联项目]
            rule "deaction1"
            ruleflow-group "work_itemwork_item_test_plan_projectdeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(test_planservice.get(work_itemwork_item_test_plan_projecttest_plan.getId()),work_itemwork_item_test_plan_projecttest_plan);
                        update(work_itemwork_item_test_plan_projectdefault);//更新fact中变量值
                        update(work_itemwork_item_test_plan_projectctx);//更新fact中变量值
                        update(work_itemwork_item_test_plan_projecttest_plan);//更新fact中变量值
            end

            //逻辑处理节点[赋值projectid]
            rule "prepareparam2"
            ruleflow-group "work_itemwork_item_test_plan_projectprepareparam2"
            when
            then
                            work_itemwork_item_test_plan_projectdefault.set("projectid",work_itemwork_item_test_plan_projecttest_plan.get("projectid"));
                                work_itemwork_item_test_plan_projectdefault.set("id",null);
                            work_itemwork_item_test_plan_projectdefault.set("projectname",work_itemwork_item_test_plan_projecttest_plan.get("projectname"));
                        update(work_itemwork_item_test_plan_projectdefault);//更新fact中变量值
                        update(work_itemwork_item_test_plan_projectctx);//更新fact中变量值
                        update(work_itemwork_item_test_plan_projecttest_plan);//更新fact中变量值
            end

            //逻辑处理节点[设置默认缺陷类型]
            rule "rawsfcode1"
            ruleflow-group "work_itemwork_item_test_plan_projectrawsfcode1"
            when
            then
                        update(work_itemwork_item_test_plan_projectdefault);//更新fact中变量值
                        update(work_itemwork_item_test_plan_projectctx);//更新fact中变量值
                        update(work_itemwork_item_test_plan_projecttest_plan);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "work_itemwork_item_test_plan_projectend1"
            when
            then
                        update(work_itemwork_item_test_plan_projectdefault);//更新fact中变量值
                        update(work_itemwork_item_test_plan_projectctx);//更新fact中变量值
                        update(work_itemwork_item_test_plan_projecttest_plan);//更新fact中变量值
            end

            //逻辑处理节点[设置默认缺陷类型名称]
            rule "prepareparam3"
            ruleflow-group "work_itemwork_item_test_plan_projectprepareparam3"
            when
            then
                            work_itemwork_item_test_plan_projectdefault.set("workitemtypename","缺陷");
                        update(work_itemwork_item_test_plan_projectdefault);//更新fact中变量值
                        update(work_itemwork_item_test_plan_projectctx);//更新fact中变量值
                        update(work_itemwork_item_test_plan_projecttest_plan);//更新fact中变量值
            end