package cn.ibizlab.plm.insight.logic.insight_reportlogic.create_bi_report;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.insight.domain.insight_report insight_reportcreate_bi_reportdefault;
                global cn.ibizlab.plm.core.extension.domain.PSSysBIReport insight_reportcreate_bi_reportbireport;
                    global cn.ibizlab.plm.core.extension.service.IPSSysBIReportService pssysbireportservice;
        global cn.ibizlab.plm.core.insight.service.Iinsight_reportService iBzSysInsight_reportDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "insight_reportcreate_bi_reportbegin"
            when
            then
            end

            //逻辑处理节点[从模板初始化模型]
            rule "rawsfcode1"
            ruleflow-group "insight_reportcreate_bi_reportrawsfcode1"
            when
            then
                        update(insight_reportcreate_bi_reportdefault);//更新fact中变量值
                        update(insight_reportcreate_bi_reportbireport);//更新fact中变量值
            end

            //逻辑处理节点[构造智能报表默认参数]
            rule "prepareparam1"
            ruleflow-group "insight_reportcreate_bi_reportprepareparam1"
            when
            then
                            insight_reportcreate_bi_reportbireport.set("validflag","1");
                            insight_reportcreate_bi_reportbireport.set("pssysbischemeid","BIScheme");
                            insight_reportcreate_bi_reportbireport.set("pssysbicubeid","BIScheme.work_item");
                            insight_reportcreate_bi_reportbireport.set("pssysbireportname",insight_reportcreate_bi_reportdefault.get("name"));
                        update(insight_reportcreate_bi_reportdefault);//更新fact中变量值
                        update(insight_reportcreate_bi_reportbireport);//更新fact中变量值
            end

            //逻辑处理节点[建立bi报表扩展模型]
            rule "deaction1"
            ruleflow-group "insight_reportcreate_bi_reportdeaction1"
            when
            then
                        pssysbireportservice.create(insight_reportcreate_bi_reportbireport);
                        update(insight_reportcreate_bi_reportdefault);//更新fact中变量值
                        update(insight_reportcreate_bi_reportbireport);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "insight_reportcreate_bi_reportend1"
            when
            then
                        update(insight_reportcreate_bi_reportdefault);//更新fact中变量值
                        update(insight_reportcreate_bi_reportbireport);//更新fact中变量值
            end

            //逻辑处理节点[回写id]
            rule "prepareparam2"
            ruleflow-group "insight_reportcreate_bi_reportprepareparam2"
            when
            then
                            insight_reportcreate_bi_reportdefault.set("id",insight_reportcreate_bi_reportbireport.get("pssysbireportid"));
                        update(insight_reportcreate_bi_reportdefault);//更新fact中变量值
                        update(insight_reportcreate_bi_reportbireport);//更新fact中变量值
            end