package cn.ibizlab.plm.insight.logic.insight_reportlogic.delete_categories;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.insight.domain.insight_report insight_reportdelete_categoriesdefault;
        global cn.ibizlab.plm.core.insight.service.Iinsight_reportService iBzSysInsight_reportDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "insight_reportdelete_categoriesbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "insight_reportdelete_categoriesend1"
            when
            then
                        update(insight_reportdelete_categoriesdefault);//更新fact中变量值
            end

            //逻辑处理节点[直接sql调用当类别删除时修改发布的类别属性]
            rule "rawsqlcall1"
            ruleflow-group "insight_reportdelete_categoriesrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",insight_reportdelete_categoriesdefault.get("id"));
        param.put("param1",insight_reportdelete_categoriesdefault.get("id"));
    String strSql="UPDATE insight_report SET categories = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', categories, ','), CONCAT(',', #{et.param0}, ','), ',')) WHERE FIND_IN_SET(#{et.param1}, categories) > 0 ;";
                        iBzSysInsight_reportDefaultService.execute(strSql,param);//SQL调用
                        update(insight_reportdelete_categoriesdefault);//更新fact中变量值
            end