package cn.ibizlab.plm.insight.logic.insight_reportlogic.remove_bi_report;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.insight.domain.insight_report insight_reportremove_bi_reportdefault;
                global cn.ibizlab.plm.core.extension.domain.PSSysBIReport insight_reportremove_bi_reportbi_report;
                    global cn.ibizlab.plm.core.extension.service.IPSSysBIReportService pssysbireportservice;
        global cn.ibizlab.plm.core.insight.service.Iinsight_reportService iBzSysInsight_reportDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "insight_reportremove_bi_reportbegin"
            when
            then
            end

            //逻辑处理节点[设置id]
            rule "prepareparam1"
            ruleflow-group "insight_reportremove_bi_reportprepareparam1"
            when
            then
                            insight_reportremove_bi_reportbi_report.set("pssysbireportid",insight_reportremove_bi_reportdefault.get("id"));
                        update(insight_reportremove_bi_reportdefault);//更新fact中变量值
                        update(insight_reportremove_bi_reportbi_report);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "insight_reportremove_bi_reportend1"
            when
            then
                        update(insight_reportremove_bi_reportdefault);//更新fact中变量值
                        update(insight_reportremove_bi_reportbi_report);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "insight_reportremove_bi_reportdeaction1"
            when
            then
                        pssysbireportservice.remove(insight_reportremove_bi_reportbi_report.getPssysbireportid());
                        update(insight_reportremove_bi_reportdefault);//更新fact中变量值
                        update(insight_reportremove_bi_reportbi_report);//更新fact中变量值
            end