package cn.ibizlab.plm.insight.logic.insight_reportlogic.use_cur_template;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.insight.domain.insight_report insight_reportuse_cur_templatedefault;
                global cn.ibizlab.plm.core.insight.domain.insight_report insight_reportuse_cur_templatenew_report;
                global cn.ibizlab.plm.core.insight.domain.insight_report insight_reportuse_cur_templatereport;
                    global cn.ibizlab.plm.core.insight.service.Iinsight_reportService insight_reportservice;
        global cn.ibizlab.plm.core.insight.service.Iinsight_reportService iBzSysInsight_reportDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "insight_reportuse_cur_templatebegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "insight_reportuse_cur_templateend1"
            when
            then
                        update(insight_reportuse_cur_templatedefault);//更新fact中变量值
                        update(insight_reportuse_cur_templatenew_report);//更新fact中变量值
                        update(insight_reportuse_cur_templatereport);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "insight_reportuse_cur_templateprepareparam1"
            when
            then
                            insight_reportuse_cur_templatenew_report.set("name",insight_reportuse_cur_templatedefault.get("name"));
                            insight_reportuse_cur_templatenew_report.set("ctrlid",insight_reportuse_cur_templatedefault.get("ctrlid"));
                            insight_reportuse_cur_templatenew_report.set("charttype",insight_reportuse_cur_templatedefault.get("charttype"));
                            insight_reportuse_cur_templatenew_report.set("group",insight_reportuse_cur_templatedefault.get("group"));
                            insight_reportuse_cur_templatenew_report.set("groupdata",insight_reportuse_cur_templatedefault.get("groupdata"));
                            insight_reportuse_cur_templatenew_report.set("desc",insight_reportuse_cur_templatedefault.get("desc"));
                            insight_reportuse_cur_templatenew_report.set("templatemodel",insight_reportuse_cur_templatedefault.get("templatemodel"));
                            insight_reportuse_cur_templatenew_report.set("viewid",insight_reportuse_cur_templatedefault.get("insight_view_id"));
                        update(insight_reportuse_cur_templatedefault);//更新fact中变量值
                        update(insight_reportuse_cur_templatenew_report);//更新fact中变量值
                        update(insight_reportuse_cur_templatereport);//更新fact中变量值
            end

            //逻辑处理节点[创建看板]
            rule "deaction2"
            ruleflow-group "insight_reportuse_cur_templatedeaction2"
            when
            then
                        insight_reportservice.create(insight_reportuse_cur_templatenew_report);
                        update(insight_reportuse_cur_templatedefault);//更新fact中变量值
                        update(insight_reportuse_cur_templatenew_report);//更新fact中变量值
                        update(insight_reportuse_cur_templatereport);//更新fact中变量值
            end

            //逻辑处理节点[生成报表]
            rule "rawsfcode1"
            ruleflow-group "insight_reportuse_cur_templaterawsfcode1"
            when
            then
                        update(insight_reportuse_cur_templatedefault);//更新fact中变量值
                        update(insight_reportuse_cur_templatenew_report);//更新fact中变量值
                        update(insight_reportuse_cur_templatereport);//更新fact中变量值
            end