package cn.ibizlab.plm.testmgmt.logic.library_memberlogic.before_create;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Library_member library_memberbefore_createdefault;
        global cn.ibizlab.plm.core.testmgmt.service.ILibrary_memberService iBzSysLibrary_memberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "library_memberbefore_createbegin"
            when
            then
            end

            //逻辑处理节点[重置id]
            rule "prepareparam1"
            ruleflow-group "library_memberbefore_createprepareparam1"
            when
            then
                                library_memberbefore_createdefault.set("id",null);
                        update(library_memberbefore_createdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "library_memberbefore_createend1"
            when
            then
                        update(library_memberbefore_createdefault);//更新fact中变量值
            end