package cn.ibizlab.plm.testmgmt.logic.library_memberlogic.notify_by_id;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Library_member library_membernotify_by_iddefault;
                    global cn.ibizlab.plm.core.testmgmt.service.ILibrary_memberService library_memberservice;
        global cn.ibizlab.plm.core.testmgmt.service.ILibrary_memberService iBzSysLibrary_memberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "library_membernotify_by_idbegin"
            when
            then
            end

            //逻辑处理节点[获取数据]
            rule "deaction1"
            ruleflow-group "library_membernotify_by_iddeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(library_memberservice.get(library_membernotify_by_iddefault.getId()),library_membernotify_by_iddefault);
                        update(library_membernotify_by_iddefault);//更新fact中变量值
            end

            //逻辑处理节点[绑定当前操作人]
            rule "prepareparam1"
            ruleflow-group "library_membernotify_by_idprepareparam1"
            when
            then
                                library_membernotify_by_iddefault.set("updateman",curuser.getSessionParams().get("srfpersonid"));
                        update(library_membernotify_by_iddefault);//更新fact中变量值
            end

            //逻辑处理节点[填充当前操作时间]
            rule "rawsfcode1"
            ruleflow-group "library_membernotify_by_idrawsfcode1"
            when
            then
                        update(library_membernotify_by_iddefault);//更新fact中变量值
            end

            //逻辑处理节点[移除测试库成员通知]
            rule "denotify1"
            ruleflow-group "library_membernotify_by_iddenotify1"
            when
            then
                        update(library_membernotify_by_iddefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "library_membernotify_by_idend1"
            when
            then
                        update(library_membernotify_by_iddefault);//更新fact中变量值
            end