package cn.ibizlab.plm.testmgmt.logic.library_memberlogic.remove_library_member_notify;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.library_member library_memberremove_library_member_notifydefault;
                    global cn.ibizlab.plm.core.testmgmt.service.Ilibrary_memberService library_memberservice;
        global cn.ibizlab.plm.core.testmgmt.service.Ilibrary_memberService iBzSysLibrary_memberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "library_memberremove_library_member_notifybegin"
            when
            then
            end

            //逻辑处理节点[获取数据]
            rule "deaction1"
            ruleflow-group "library_memberremove_library_member_notifydeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(library_memberservice.get(library_memberremove_library_member_notifydefault.getId()),library_memberremove_library_member_notifydefault);
                        update(library_memberremove_library_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[绑定当前操作人]
            rule "prepareparam1"
            ruleflow-group "library_memberremove_library_member_notifyprepareparam1"
            when
            then
                                library_memberremove_library_member_notifydefault.set("updateman",curuser.getSessionParams().get("srfpersonid"));
                        update(library_memberremove_library_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[填充当前操作时间]
            rule "rawsfcode1"
            ruleflow-group "library_memberremove_library_member_notifyrawsfcode1"
            when
            then
                        update(library_memberremove_library_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[移除测试库成员通知]
            rule "denotify1"
            ruleflow-group "library_memberremove_library_member_notifydenotify1"
            when
            then
                        update(library_memberremove_library_member_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "library_memberremove_library_member_notifyend1"
            when
            then
                        update(library_memberremove_library_member_notifydefault);//更新fact中变量值
            end