package cn.ibizlab.plm.prodmgmt.logic.ticket_typelogic.exclude_exist_type;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket_type ticket_typeexclude_exist_typedefault;
        global cn.ibizlab.plm.core.prodmgmt.service.Iticket_typeService iBzSysTicket_typeDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ticket_typeexclude_exist_typebegin"
            when
            then
            end

            //逻辑处理节点[排除已存在的工单类型]
            rule "rawsqlcall1"
            ruleflow-group "ticket_typeexclude_exist_typerawsqlcall1"
            when
            then
                        Map param = null;
                        String strSql="";
                        iBzSysTicket_typeDefaultService.execute(strSql,param);//SQL调用
                        update(ticket_typeexclude_exist_typedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ticket_typeexclude_exist_typeend1"
            when
            then
                        update(ticket_typeexclude_exist_typedefault);//更新fact中变量值
            end