package cn.ibizlab.plm.prodmgmt.logic.ticket_typelogic.get_con_ticket;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket_type ticket_typeget_con_ticketdefault;
        global cn.ibizlab.plm.core.prodmgmt.service.Iticket_typeService iBzSysTicket_typeDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ticket_typeget_con_ticketbegin"
            when
            then
            end

            //逻辑处理节点[查询所关联的工单数量]
            rule "rawsqlcall1"
            ruleflow-group "ticket_typeget_con_ticketrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",ticket_typeget_con_ticketdefault.get("id"));
    String strSql="select count(1) as ticket_num from ticket  where  type = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysTicket_typeDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    ticket_typeget_con_ticketdefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(ticket_typeget_con_ticketdefault);//更新fact中变量值
            end

            //逻辑处理节点[填充工单提示默认值]
            rule "prepareparam1"
            ruleflow-group "ticket_typeget_con_ticketprepareparam1"
            when
            then
                            ticket_typeget_con_ticketdefault.set("remind","工单类型删除后不可恢复，后续不可再新建此类型的工单。");
                            ticket_typeget_con_ticketdefault.set("disabled","0");
                        update(ticket_typeget_con_ticketdefault);//更新fact中变量值
            end

            //逻辑处理节点[添加工单数量提醒内容]
            rule "rawsfcode1"
            ruleflow-group "ticket_typeget_con_ticketrawsfcode1"
            when
            then
                        update(ticket_typeget_con_ticketdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ticket_typeget_con_ticketend1"
            when
            then
                        update(ticket_typeget_con_ticketdefault);//更新fact中变量值
            end