package cn.ibizlab.plm.base.logic.sectionlogic.delete_section;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.Section sectiondelete_sectiondefault;
                global cn.ibizlab.plm.core.base.domain.Category sectiondelete_sectioncategory_filter;
                global cn.ibizlab.plm.core.base.domain.Category sectiondelete_sectioncategory_page;
                global cn.ibizlab.plm.core.base.domain.Section sectiondelete_sectionfilter;
                global cn.ibizlab.plm.core.base.domain.Category sectiondelete_sectionfor_temp_obj;
                    global cn.ibizlab.plm.core.base.service.ISectionService sectionservice;
                    global cn.ibizlab.plm.core.base.service.ICategoryService categoryservice;
        global cn.ibizlab.plm.core.base.service.ISectionService iBzSysSectionDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "sectiondelete_sectionbegin"
            when
            then
            end

            //逻辑处理节点[删除类别]
            rule "deaction2"
            ruleflow-group "sectiondelete_sectiondeaction2"
            when
            then
                        sectionservice.remove(sectiondelete_sectiondefault.getId());
                        update(sectiondelete_sectiondefault);//更新fact中变量值
                        update(sectiondelete_sectioncategory_filter);//更新fact中变量值
                        update(sectiondelete_sectioncategory_page);//更新fact中变量值
                        update(sectiondelete_sectionfilter);//更新fact中变量值
                        update(sectiondelete_sectionfor_temp_obj);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "sectiondelete_sectiondebugparam1"
            when
            then
                        update(sectiondelete_sectiondefault);//更新fact中变量值
                        update(sectiondelete_sectioncategory_filter);//更新fact中变量值
                        update(sectiondelete_sectioncategory_page);//更新fact中变量值
                        update(sectiondelete_sectionfilter);//更新fact中变量值
                        update(sectiondelete_sectionfor_temp_obj);//更新fact中变量值
            end

            //逻辑处理节点[设置过滤器参数]
            rule "prepareparam1"
            ruleflow-group "sectiondelete_sectionprepareparam1"
            when
            then
                            sectiondelete_sectioncategory_filter.set("n_section_id_eq",sectiondelete_sectiondefault.get("id"));
                        update(sectiondelete_sectiondefault);//更新fact中变量值
                        update(sectiondelete_sectioncategory_filter);//更新fact中变量值
                        update(sectiondelete_sectioncategory_page);//更新fact中变量值
                        update(sectiondelete_sectionfilter);//更新fact中变量值
                        update(sectiondelete_sectionfor_temp_obj);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "sectiondelete_sectiondedataset1"
            when
            then
                        update(sectiondelete_sectiondefault);//更新fact中变量值
                        update(sectiondelete_sectioncategory_filter);//更新fact中变量值
                        update(sectiondelete_sectioncategory_page);//更新fact中变量值
                        update(sectiondelete_sectionfilter);//更新fact中变量值
                        update(sectiondelete_sectionfor_temp_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "sectiondelete_sectionloopsubcall1"
            when
            then
                        update(sectiondelete_sectiondefault);//更新fact中变量值
                        update(sectiondelete_sectioncategory_filter);//更新fact中变量值
                        update(sectiondelete_sectioncategory_page);//更新fact中变量值
                        update(sectiondelete_sectionfilter);//更新fact中变量值
                        update(sectiondelete_sectionfor_temp_obj);//更新fact中变量值
            end

            //逻辑处理节点[删除子数据]
            rule "deaction1"
            ruleflow-group "sectiondelete_sectiondeaction1"
            when
            then
                        categoryservice.remove(sectiondelete_sectionfor_temp_obj.getId());
                        update(sectiondelete_sectiondefault);//更新fact中变量值
                        update(sectiondelete_sectioncategory_filter);//更新fact中变量值
                        update(sectiondelete_sectioncategory_page);//更新fact中变量值
                        update(sectiondelete_sectionfilter);//更新fact中变量值
                        update(sectiondelete_sectionfor_temp_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环调用]
            rule "delogic1"
            ruleflow-group "sectiondelete_sectiondelogic1"
            when
            then
                        update(sectiondelete_sectiondefault);//更新fact中变量值
                        update(sectiondelete_sectioncategory_filter);//更新fact中变量值
                        update(sectiondelete_sectioncategory_page);//更新fact中变量值
                        update(sectiondelete_sectionfilter);//更新fact中变量值
                        update(sectiondelete_sectionfor_temp_obj);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam2"
            ruleflow-group "sectiondelete_sectiondebugparam2"
            when
            then
                        update(sectiondelete_sectiondefault);//更新fact中变量值
                        update(sectiondelete_sectioncategory_filter);//更新fact中变量值
                        update(sectiondelete_sectioncategory_page);//更新fact中变量值
                        update(sectiondelete_sectionfilter);//更新fact中变量值
                        update(sectiondelete_sectionfor_temp_obj);//更新fact中变量值
            end

            //逻辑处理节点[修改需求信息]
            rule "rawsqlcall1"
            ruleflow-group "sectiondelete_sectionrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",sectiondelete_sectiondefault.get("id"));
    String strSql="UPDATE idea t  INNER JOIN category t21 ON t.category_id = t21.ID  INNER JOIN section t31 on t21.SECTION_ID = t31.id SET t.category_id = NULL WHERE (t21.SECTION_ID = #{et.param0} )";
                        iBzSysSectionDefaultService.execute(strSql,param);//SQL调用
                        update(sectiondelete_sectiondefault);//更新fact中变量值
                        update(sectiondelete_sectioncategory_filter);//更新fact中变量值
                        update(sectiondelete_sectioncategory_page);//更新fact中变量值
                        update(sectiondelete_sectionfilter);//更新fact中变量值
                        update(sectiondelete_sectionfor_temp_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "sectiondelete_sectionend1"
            when
            then
                        update(sectiondelete_sectiondefault);//更新fact中变量值
                        update(sectiondelete_sectioncategory_filter);//更新fact中变量值
                        update(sectiondelete_sectioncategory_page);//更新fact中变量值
                        update(sectiondelete_sectionfilter);//更新fact中变量值
                        update(sectiondelete_sectionfor_temp_obj);//更新fact中变量值
            end