# 起始格式化间隔
tabWidth: 2
# 使用单引号
singleQuote: true
# jsx 中使用单引号
jsxSingleQuote: true
# 对象中的 key 是否需要引号。as-needed: 只有在必须时才要
quoteProps: as-needed
# 每行结尾是否需要分号
trailingComma: all
# 括号中参数前后补充空格
bracketSpacing: true
# 箭头函数，参数是否添加括号
arrowParens: avoid
# jsx 元素最后末尾的 > ，换行放置
bracketSameLine: false
# 设置换行符
endOfLine: 'lf'