root: true
extends:
  [
    'stylelint-config-standard',
    'stylelint-config-standard-scss',
    'stylelint-config-recess-order',
    'stylelint-config-prettier',
    'stylelint-scss',
  ]
rules:
  annotation-no-unknown: null
  color-no-invalid-hex: true
  function-name-case: null # 强制样式方法名称小写或大写
  no-duplicate-selectors: null
  scss/dollar-variable-pattern: null
  scss/at-function-pattern: null
  scss/dollar-variable-empty-line-before: null # 变量声明之间不可以有空白行
