package cn.ibizlab.plm.testmgmt.logic.review_wizardlogic.fix_nested_data;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.review_wizard review_wizardfix_nested_datadefault;
        global cn.ibizlab.plm.core.testmgmt.service.Ireview_wizardService iBzSysReview_wizardDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "review_wizardfix_nested_databegin"
            when
            then
            end

            //逻辑处理节点[直接sql调用]
            rule "rawsqlcall1"
            ruleflow-group "review_wizardfix_nested_datarawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",review_wizardfix_nested_datadefault.get("id"));
    String strSql="update attention set OWNER_TYPE = 'REVIEW' where OWNER_TYPE ='REVIEW_WIZARD' AND OWNER_ID = #{et.param0} ";
                        iBzSysReview_wizardDefaultService.execute(strSql,param);//SQL调用
                        update(review_wizardfix_nested_datadefault);//更新fact中变量值
            end