package cn.ibizlab.plm.extension.logic.psdelogiclogic.test_template_flow;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.extension.domain.PSDELogic psdelogictest_template_flowdefault;
                    global cn.ibizlab.plm.core.base.service.Itemplate_flowService template_flowservice;
        global cn.ibizlab.plm.core.extension.service.IPSDELogicService iBzSysPsdelogicDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "psdelogictest_template_flowbegin"
            when
            then
            end

            //逻辑处理节点[测试模板规则]
            rule "delogic1"
            ruleflow-group "psdelogictest_template_flowdelogic1"
            when
            then
                        update(psdelogictest_template_flowdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "psdelogictest_template_flowend1"
            when
            then
                        update(psdelogictest_template_flowdefault);//更新fact中变量值
            end