package cn.ibizlab.plm.testmgmt.logic.test_caselogic.case_move_plan;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case test_casecase_move_plandefault;
                global cn.ibizlab.plm.core.testmgmt.domain.run test_casecase_move_planruninfo;
                global cn.ibizlab.plm.core.base.domain.attachment test_casecase_move_planattachment;
                global cn.ibizlab.plm.core.base.domain.attachment test_casecase_move_planattachments;
                global cn.ibizlab.plm.core.base.domain.attention test_casecase_move_planattention_info;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case test_casecase_move_planfor_temp_obj;
                global java.util.Map test_casecase_move_planid;
                global java.util.Map test_casecase_move_planids;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case test_casecase_move_plansrfactionparam;
                global cn.ibizlab.plm.core.base.domain.attachment test_casecase_move_plantemp_att_obj;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case test_casecase_move_plantemp_obj;
                    global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService test_caseservice;
                    global cn.ibizlab.plm.core.testmgmt.service.IrunService runservice;
                    global cn.ibizlab.plm.core.base.service.IattentionService attentionservice;
        global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService iBzSysTest_caseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_casecase_move_planbegin"
            when
            then
            end

            //逻辑处理节点[获取表单数据]
            rule "bindparam1"
            ruleflow-group "test_casecase_move_planbindparam1"
            when
            then
                        update(test_casecase_move_plandefault);//更新fact中变量值
                        update(test_casecase_move_planruninfo);//更新fact中变量值
                        update(test_casecase_move_planattachment);//更新fact中变量值
                        update(test_casecase_move_planattachments);//更新fact中变量值
                        update(test_casecase_move_planattention_info);//更新fact中变量值
                        update(test_casecase_move_planfor_temp_obj);//更新fact中变量值
                        update(test_casecase_move_planid);//更新fact中变量值
                        update(test_casecase_move_planids);//更新fact中变量值
                        update(test_casecase_move_plansrfactionparam);//更新fact中变量值
                        update(test_casecase_move_plantemp_att_obj);//更新fact中变量值
                        update(test_casecase_move_plantemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[绑定id参数]
            rule "bindparam2"
            ruleflow-group "test_casecase_move_planbindparam2"
            when
            then
                        update(test_casecase_move_plandefault);//更新fact中变量值
                        update(test_casecase_move_planruninfo);//更新fact中变量值
                        update(test_casecase_move_planattachment);//更新fact中变量值
                        update(test_casecase_move_planattachments);//更新fact中变量值
                        update(test_casecase_move_planattention_info);//更新fact中变量值
                        update(test_casecase_move_planfor_temp_obj);//更新fact中变量值
                        update(test_casecase_move_planid);//更新fact中变量值
                        update(test_casecase_move_planids);//更新fact中变量值
                        update(test_casecase_move_plansrfactionparam);//更新fact中变量值
                        update(test_casecase_move_plantemp_att_obj);//更新fact中变量值
                        update(test_casecase_move_plantemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "test_casecase_move_planloopsubcall1"
            when
            then
                        update(test_casecase_move_plandefault);//更新fact中变量值
                        update(test_casecase_move_planruninfo);//更新fact中变量值
                        update(test_casecase_move_planattachment);//更新fact中变量值
                        update(test_casecase_move_planattachments);//更新fact中变量值
                        update(test_casecase_move_planattention_info);//更新fact中变量值
                        update(test_casecase_move_planfor_temp_obj);//更新fact中变量值
                        update(test_casecase_move_planid);//更新fact中变量值
                        update(test_casecase_move_planids);//更新fact中变量值
                        update(test_casecase_move_plansrfactionparam);//更新fact中变量值
                        update(test_casecase_move_plantemp_att_obj);//更新fact中变量值
                        update(test_casecase_move_plantemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "test_casecase_move_planrenewparam1"
            when
            then
                        update(test_casecase_move_plandefault);//更新fact中变量值
                        update(test_casecase_move_planruninfo);//更新fact中变量值
                        update(test_casecase_move_planattachment);//更新fact中变量值
                        update(test_casecase_move_planattachments);//更新fact中变量值
                        update(test_casecase_move_planattention_info);//更新fact中变量值
                        update(test_casecase_move_planfor_temp_obj);//更新fact中变量值
                        update(test_casecase_move_planid);//更新fact中变量值
                        update(test_casecase_move_planids);//更新fact中变量值
                        update(test_casecase_move_plansrfactionparam);//更新fact中变量值
                        update(test_casecase_move_plantemp_att_obj);//更新fact中变量值
                        update(test_casecase_move_plantemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[获取数据]
            rule "deaction2"
            ruleflow-group "test_casecase_move_plandeaction2"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(test_caseservice.get(test_casecase_move_planid.getId()),test_casecase_move_planid);
                        update(test_casecase_move_plandefault);//更新fact中变量值
                        update(test_casecase_move_planruninfo);//更新fact中变量值
                        update(test_casecase_move_planattachment);//更新fact中变量值
                        update(test_casecase_move_planattachments);//更新fact中变量值
                        update(test_casecase_move_planattention_info);//更新fact中变量值
                        update(test_casecase_move_planfor_temp_obj);//更新fact中变量值
                        update(test_casecase_move_planid);//更新fact中变量值
                        update(test_casecase_move_planids);//更新fact中变量值
                        update(test_casecase_move_plansrfactionparam);//更新fact中变量值
                        update(test_casecase_move_plantemp_att_obj);//更新fact中变量值
                        update(test_casecase_move_plantemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[设置执行用例信息（附件置空）]
            rule "prepareparam1"
            ruleflow-group "test_casecase_move_planprepareparam1"
            when
            then
                            test_casecase_move_planruninfo.set("",test_casecase_move_plantemp_obj.get(""));
                                test_casecase_move_planruninfo.set("attentions",null);
                                test_casecase_move_planruninfo.set("executedat",null);
                            test_casecase_move_planattachments.set("",test_casecase_move_plantemp_obj.get("attachments"));
                                test_casecase_move_planruninfo.set("attachments",null);
                                test_casecase_move_planruninfo.set("id",null);
                            test_casecase_move_planruninfo.set("caseid",test_casecase_move_plantemp_obj.get("id"));
                            test_casecase_move_planruninfo.set("planid",test_casecase_move_planfor_temp_obj.get("test_plan"));
                        update(test_casecase_move_plandefault);//更新fact中变量值
                        update(test_casecase_move_planruninfo);//更新fact中变量值
                        update(test_casecase_move_planattachment);//更新fact中变量值
                        update(test_casecase_move_planattachments);//更新fact中变量值
                        update(test_casecase_move_planattention_info);//更新fact中变量值
                        update(test_casecase_move_planfor_temp_obj);//更新fact中变量值
                        update(test_casecase_move_planid);//更新fact中变量值
                        update(test_casecase_move_planids);//更新fact中变量值
                        update(test_casecase_move_plansrfactionparam);//更新fact中变量值
                        update(test_casecase_move_plantemp_att_obj);//更新fact中变量值
                        update(test_casecase_move_plantemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[重置关注信息]
            rule "resetparam1"
            ruleflow-group "test_casecase_move_planresetparam1"
            when
            then
                        update(test_casecase_move_plandefault);//更新fact中变量值
                        update(test_casecase_move_planruninfo);//更新fact中变量值
                        update(test_casecase_move_planattachment);//更新fact中变量值
                        update(test_casecase_move_planattachments);//更新fact中变量值
                        update(test_casecase_move_planattention_info);//更新fact中变量值
                        update(test_casecase_move_planfor_temp_obj);//更新fact中变量值
                        update(test_casecase_move_planid);//更新fact中变量值
                        update(test_casecase_move_planids);//更新fact中变量值
                        update(test_casecase_move_plansrfactionparam);//更新fact中变量值
                        update(test_casecase_move_plantemp_att_obj);//更新fact中变量值
                        update(test_casecase_move_plantemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[创建执行用例]
            rule "deaction1"
            ruleflow-group "test_casecase_move_plandeaction1"
            when
            then
                        runservice.save(test_casecase_move_planruninfo);
                        update(test_casecase_move_plandefault);//更新fact中变量值
                        update(test_casecase_move_planruninfo);//更新fact中变量值
                        update(test_casecase_move_planattachment);//更新fact中变量值
                        update(test_casecase_move_planattachments);//更新fact中变量值
                        update(test_casecase_move_planattention_info);//更新fact中变量值
                        update(test_casecase_move_planfor_temp_obj);//更新fact中变量值
                        update(test_casecase_move_planid);//更新fact中变量值
                        update(test_casecase_move_planids);//更新fact中变量值
                        update(test_casecase_move_plansrfactionparam);//更新fact中变量值
                        update(test_casecase_move_plantemp_att_obj);//更新fact中变量值
                        update(test_casecase_move_plantemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "test_casecase_move_planend2"
            when
            then
                        update(test_casecase_move_plandefault);//更新fact中变量值
                        update(test_casecase_move_planruninfo);//更新fact中变量值
                        update(test_casecase_move_planattachment);//更新fact中变量值
                        update(test_casecase_move_planattachments);//更新fact中变量值
                        update(test_casecase_move_planattention_info);//更新fact中变量值
                        update(test_casecase_move_planfor_temp_obj);//更新fact中变量值
                        update(test_casecase_move_planid);//更新fact中变量值
                        update(test_casecase_move_planids);//更新fact中变量值
                        update(test_casecase_move_plansrfactionparam);//更新fact中变量值
                        update(test_casecase_move_plantemp_att_obj);//更新fact中变量值
                        update(test_casecase_move_plantemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[关注信息]
            rule "prepareparam2"
            ruleflow-group "test_casecase_move_planprepareparam2"
            when
            then
                            test_casecase_move_planattention_info.set("userid",test_casecase_move_plantemp_obj.get("createman"));
                                test_casecase_move_planattention_info.set("name",curuser.getSessionParams().get("srfpersonname"));
                            test_casecase_move_planattention_info.set("ownerid",test_casecase_move_planruninfo.get("id"));
                            test_casecase_move_planattention_info.set("ownertype","RUN");
                            test_casecase_move_planattention_info.set("ownersubtype","RUN");
                            test_casecase_move_planattention_info.set("type","40");
                        update(test_casecase_move_plandefault);//更新fact中变量值
                        update(test_casecase_move_planruninfo);//更新fact中变量值
                        update(test_casecase_move_planattachment);//更新fact中变量值
                        update(test_casecase_move_planattachments);//更新fact中变量值
                        update(test_casecase_move_planattention_info);//更新fact中变量值
                        update(test_casecase_move_planfor_temp_obj);//更新fact中变量值
                        update(test_casecase_move_planid);//更新fact中变量值
                        update(test_casecase_move_planids);//更新fact中变量值
                        update(test_casecase_move_plansrfactionparam);//更新fact中变量值
                        update(test_casecase_move_plantemp_att_obj);//更新fact中变量值
                        update(test_casecase_move_plantemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[保存关注信息]
            rule "deaction3"
            ruleflow-group "test_casecase_move_plandeaction3"
            when
            then
                        attentionservice.save(test_casecase_move_planattention_info);
                        update(test_casecase_move_plandefault);//更新fact中变量值
                        update(test_casecase_move_planruninfo);//更新fact中变量值
                        update(test_casecase_move_planattachment);//更新fact中变量值
                        update(test_casecase_move_planattachments);//更新fact中变量值
                        update(test_casecase_move_planattention_info);//更新fact中变量值
                        update(test_casecase_move_planfor_temp_obj);//更新fact中变量值
                        update(test_casecase_move_planid);//更新fact中变量值
                        update(test_casecase_move_planids);//更新fact中变量值
                        update(test_casecase_move_plansrfactionparam);//更新fact中变量值
                        update(test_casecase_move_plantemp_att_obj);//更新fact中变量值
                        update(test_casecase_move_plantemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_casecase_move_planend1"
            when
            then
                        update(test_casecase_move_plandefault);//更新fact中变量值
                        update(test_casecase_move_planruninfo);//更新fact中变量值
                        update(test_casecase_move_planattachment);//更新fact中变量值
                        update(test_casecase_move_planattachments);//更新fact中变量值
                        update(test_casecase_move_planattention_info);//更新fact中变量值
                        update(test_casecase_move_planfor_temp_obj);//更新fact中变量值
                        update(test_casecase_move_planid);//更新fact中变量值
                        update(test_casecase_move_planids);//更新fact中变量值
                        update(test_casecase_move_plansrfactionparam);//更新fact中变量值
                        update(test_casecase_move_plantemp_att_obj);//更新fact中变量值
                        update(test_casecase_move_plantemp_obj);//更新fact中变量值
            end