package cn.ibizlab.plm.testmgmt.logic.test_caselogic.create_recent;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Test_case test_casecreate_recentdefault;
                global cn.ibizlab.plm.core.base.domain.Recent test_casecreate_recentrecent;
                    global cn.ibizlab.plm.core.base.service.IRecentService recentservice;
        global cn.ibizlab.plm.core.testmgmt.service.ITest_caseService iBzSysTest_caseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_casecreate_recentbegin"
            when
            then
            end

            //逻辑处理节点[准备最近访问参数]
            rule "prepareparam1"
            ruleflow-group "test_casecreate_recentprepareparam1"
            when
            then
                            test_casecreate_recentrecent.set("ownerid",test_casecreate_recentdefault.get("id"));
                            test_casecreate_recentrecent.set("recentparentidentifier",test_casecreate_recentdefault.get("libraryidentifier"));
                            test_casecreate_recentrecent.set("recentparentname",test_casecreate_recentdefault.get("testlibraryname"));
                            test_casecreate_recentrecent.set("recentparent",test_casecreate_recentdefault.get("testlibraryid"));
                                test_casecreate_recentrecent.set("createman",curuser.getSessionParams().get("srfpersonid"));
                            test_casecreate_recentrecent.set("identifier",test_casecreate_recentdefault.get("identifier"));
                            test_casecreate_recentrecent.set("type","2");
                            test_casecreate_recentrecent.set("name",test_casecreate_recentdefault.get("title"));
                            test_casecreate_recentrecent.set("ownertype","library");
                            test_casecreate_recentrecent.set("ownersubtype","test_case");
                        update(test_casecreate_recentdefault);//更新fact中变量值
                        update(test_casecreate_recentrecent);//更新fact中变量值
            end

            //逻辑处理节点[保存最近访问]
            rule "deaction1"
            ruleflow-group "test_casecreate_recentdeaction1"
            when
            then
                        recentservice.save(test_casecreate_recentrecent);
                        update(test_casecreate_recentdefault);//更新fact中变量值
                        update(test_casecreate_recentrecent);//更新fact中变量值
            end

            //逻辑处理节点[更新登记工时中的业务信息]
            rule "rawsqlcall1"
            ruleflow-group "test_casecreate_recentrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",test_casecreate_recentdefault.get("identifier"));
        param.put("param1",test_casecreate_recentdefault.get("testlibraryid"));
        param.put("param2",test_casecreate_recentdefault.get("libraryidentifier"));
        param.put("param3",test_casecreate_recentdefault.get("testlibraryname"));
        param.put("param4",test_casecreate_recentdefault.get("title"));
        param.put("param5",test_casecreate_recentdefault.get("id"));
    String strSql="UPDATE `WORKLOAD` SET IDENTIFIER = #{et.param0}, RECENT_PARENT = #{et.param1}, RECENT_PARENT_IDENTIFIER = #{et.param2}, RECENT_PARENT_NAME = #{et.param3}, `NAME` = #{et.param4} WHERE PRINCIPAL_ID = #{et.param5} and PRINCIPAL_TYPE = 'TEST_CASE'";
                        iBzSysTest_caseDefaultService.execute(strSql,param);//SQL调用
                        update(test_casecreate_recentdefault);//更新fact中变量值
                        update(test_casecreate_recentrecent);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_casecreate_recentend1"
            when
            then
                        update(test_casecreate_recentdefault);//更新fact中变量值
                        update(test_casecreate_recentrecent);//更新fact中变量值
            end