package cn.ibizlab.plm.testmgmt.logic.test_caselogic.del_relation;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Test_case test_casedel_relationdefault;
                global cn.ibizlab.plm.core.base.domain.Relation test_casedel_relationrelationobj;
                global cn.ibizlab.plm.core.base.domain.Relation test_casedel_relationrelationobj2;
                    global cn.ibizlab.plm.core.base.service.IRelationService relationservice;
        global cn.ibizlab.plm.core.testmgmt.service.ITest_caseService iBzSysTest_caseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_casedel_relationbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "test_casedel_relationprepareparam1"
            when
            then
                            test_casedel_relationrelationobj.set("principalid",test_casedel_relationdefault.get("principal_id"));
                            test_casedel_relationrelationobj2.set("targetid",test_casedel_relationdefault.get("principal_id"));
                            test_casedel_relationrelationobj2.set("principalid",test_casedel_relationdefault.get("id"));
                            test_casedel_relationrelationobj.set("targetid",test_casedel_relationdefault.get("id"));
                        update(test_casedel_relationdefault);//更新fact中变量值
                        update(test_casedel_relationrelationobj);//更新fact中变量值
                        update(test_casedel_relationrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[拼接关联对象的主键]
            rule "rawsfcode1"
            ruleflow-group "test_casedel_relationrawsfcode1"
            when
            then
                        update(test_casedel_relationdefault);//更新fact中变量值
                        update(test_casedel_relationrelationobj);//更新fact中变量值
                        update(test_casedel_relationrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[删除正向关联]
            rule "deaction2"
            ruleflow-group "test_casedel_relationdeaction2"
            when
            then
                        relationservice.remove(test_casedel_relationrelationobj.getId());
                        update(test_casedel_relationdefault);//更新fact中变量值
                        update(test_casedel_relationrelationobj);//更新fact中变量值
                        update(test_casedel_relationrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[删除反向关联]
            rule "deaction3"
            ruleflow-group "test_casedel_relationdeaction3"
            when
            then
                        relationservice.remove(test_casedel_relationrelationobj2.getId());
                        update(test_casedel_relationdefault);//更新fact中变量值
                        update(test_casedel_relationrelationobj);//更新fact中变量值
                        update(test_casedel_relationrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_casedel_relationend1"
            when
            then
                        update(test_casedel_relationdefault);//更新fact中变量值
                        update(test_casedel_relationrelationobj);//更新fact中变量值
                        update(test_casedel_relationrelationobj2);//更新fact中变量值
            end