package cn.ibizlab.plm.testmgmt.logic.test_caselogic.delete;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Test_case test_casedeletedefault;
                global cn.ibizlab.plm.core.testmgmt.domain.Run test_casedeletefiter;
                global cn.ibizlab.plm.core.testmgmt.domain.Run test_casedeleterun_info;
                global cn.ibizlab.plm.core.testmgmt.domain.Run test_casedeleterun_list;
                global cn.ibizlab.plm.core.testmgmt.domain.Run test_casedeletetemp_obj;
                global cn.ibizlab.plm.core.testmgmt.domain.Test_plan test_casedeletetest_plan_info;
                    global cn.ibizlab.plm.core.testmgmt.service.ITest_caseService test_caseservice;
                    global cn.ibizlab.plm.core.testmgmt.service.IRunService runservice;
                    global cn.ibizlab.plm.core.testmgmt.service.ITest_planService test_planservice;
        global cn.ibizlab.plm.core.testmgmt.service.ITest_caseService iBzSysTest_caseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_casedeletebegin"
            when
            then
            end

            //逻辑处理节点[设置过滤器参数case_id]
            rule "prepareparam3"
            ruleflow-group "test_casedeleteprepareparam3"
            when
            then
                            test_casedeletefiter.set("n_case_id_eq",test_casedeletedefault.get("id"));
                        update(test_casedeletedefault);//更新fact中变量值
                        update(test_casedeletefiter);//更新fact中变量值
                        update(test_casedeleterun_info);//更新fact中变量值
                        update(test_casedeleterun_list);//更新fact中变量值
                        update(test_casedeletetemp_obj);//更新fact中变量值
                        update(test_casedeletetest_plan_info);//更新fact中变量值
            end

            //逻辑处理节点[设置删除状态]
            rule "prepareparam1"
            ruleflow-group "test_casedeleteprepareparam1"
            when
            then
                            test_casedeletedefault.set("isdeleted","1");
                            test_casedeleterun_info.set("caseid",test_casedeletedefault.get("id"));
                        update(test_casedeletedefault);//更新fact中变量值
                        update(test_casedeletefiter);//更新fact中变量值
                        update(test_casedeleterun_info);//更新fact中变量值
                        update(test_casedeleterun_list);//更新fact中变量值
                        update(test_casedeletetemp_obj);//更新fact中变量值
                        update(test_casedeletetest_plan_info);//更新fact中变量值
            end

            //逻辑处理节点[更新删除状态]
            rule "deaction1"
            ruleflow-group "test_casedeletedeaction1"
            when
            then
                        test_caseservice.update(test_casedeletedefault);
                        update(test_casedeletedefault);//更新fact中变量值
                        update(test_casedeletefiter);//更新fact中变量值
                        update(test_casedeleterun_info);//更新fact中变量值
                        update(test_casedeleterun_list);//更新fact中变量值
                        update(test_casedeletetemp_obj);//更新fact中变量值
                        update(test_casedeletetest_plan_info);//更新fact中变量值
            end

            //逻辑处理节点[删除最近访问]
            rule "rawsqlcall1"
            ruleflow-group "test_casedeleterawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",test_casedeletedefault.get("id"));
    String strSql="update recent set IS_DELETED=1 where owner_id=#{et.param0} and owner_subtype='test_case'";
                        iBzSysTest_caseDefaultService.execute(strSql,param);//SQL调用
                        update(test_casedeletedefault);//更新fact中变量值
                        update(test_casedeletefiter);//更新fact中变量值
                        update(test_casedeleterun_info);//更新fact中变量值
                        update(test_casedeleterun_list);//更新fact中变量值
                        update(test_casedeletetemp_obj);//更新fact中变量值
                        update(test_casedeletetest_plan_info);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "test_casedeleteend2"
            when
            then
                        update(test_casedeletedefault);//更新fact中变量值
                        update(test_casedeletefiter);//更新fact中变量值
                        update(test_casedeleterun_info);//更新fact中变量值
                        update(test_casedeleterun_list);//更新fact中变量值
                        update(test_casedeletetemp_obj);//更新fact中变量值
                        update(test_casedeletetest_plan_info);//更新fact中变量值
            end

            //逻辑处理节点[查询执行用例信息]
            rule "dedataquery1"
            ruleflow-group "test_casedeletededataquery1"
            when
            then
                        update(test_casedeletedefault);//更新fact中变量值
                        update(test_casedeletefiter);//更新fact中变量值
                        update(test_casedeleterun_info);//更新fact中变量值
                        update(test_casedeleterun_list);//更新fact中变量值
                        update(test_casedeletetemp_obj);//更新fact中变量值
                        update(test_casedeletetest_plan_info);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "test_casedeleteloopsubcall1"
            when
            then
                        update(test_casedeletedefault);//更新fact中变量值
                        update(test_casedeletefiter);//更新fact中变量值
                        update(test_casedeleterun_info);//更新fact中变量值
                        update(test_casedeleterun_list);//更新fact中变量值
                        update(test_casedeletetemp_obj);//更新fact中变量值
                        update(test_casedeletetest_plan_info);//更新fact中变量值
            end

            //逻辑处理节点[获取测试计划id]
            rule "prepareparam2"
            ruleflow-group "test_casedeleteprepareparam2"
            when
            then
                            test_casedeletetest_plan_info.set("id",test_casedeletetemp_obj.get("planid"));
                        update(test_casedeletedefault);//更新fact中变量值
                        update(test_casedeletefiter);//更新fact中变量值
                        update(test_casedeleterun_info);//更新fact中变量值
                        update(test_casedeleterun_list);//更新fact中变量值
                        update(test_casedeletetemp_obj);//更新fact中变量值
                        update(test_casedeletetest_plan_info);//更新fact中变量值
            end

            //逻辑处理节点[查询测试计划]
            rule "deaction2"
            ruleflow-group "test_casedeletedeaction2"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(test_planservice.get(test_casedeletetest_plan_info.getId()),test_casedeletetest_plan_info);
                        update(test_casedeletedefault);//更新fact中变量值
                        update(test_casedeletefiter);//更新fact中变量值
                        update(test_casedeleterun_info);//更新fact中变量值
                        update(test_casedeleterun_list);//更新fact中变量值
                        update(test_casedeletetemp_obj);//更新fact中变量值
                        update(test_casedeletetest_plan_info);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_casedeleteend1"
            when
            then
                        update(test_casedeletedefault);//更新fact中变量值
                        update(test_casedeletefiter);//更新fact中变量值
                        update(test_casedeleterun_info);//更新fact中变量值
                        update(test_casedeleterun_list);//更新fact中变量值
                        update(test_casedeletetemp_obj);//更新fact中变量值
                        update(test_casedeletetest_plan_info);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction3"
            ruleflow-group "test_casedeletedeaction3"
            when
            then
                        runservice.remove(test_casedeletetemp_obj.getId());
                        update(test_casedeletedefault);//更新fact中变量值
                        update(test_casedeletefiter);//更新fact中变量值
                        update(test_casedeleterun_info);//更新fact中变量值
                        update(test_casedeleterun_list);//更新fact中变量值
                        update(test_casedeletetemp_obj);//更新fact中变量值
                        update(test_casedeletetest_plan_info);//更新fact中变量值
            end