package cn.ibizlab.plm.testmgmt.logic.test_caselogic.fill_latest_executed;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case test_casefill_latest_executeddefault;
        global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService iBzSysTest_caseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_casefill_latest_executedbegin"
            when
            then
            end

            //逻辑处理节点[填充最近执行]
            rule "rawsfcode1"
            ruleflow-group "test_casefill_latest_executedrawsfcode1"
            when
            then
                        update(test_casefill_latest_executeddefault);//更新fact中变量值
            end