package cn.ibizlab.plm.testmgmt.logic.test_caselogic.get_actual_workload;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Test_case test_caseget_actual_workloaddefault;
        global cn.ibizlab.plm.core.testmgmt.service.ITest_caseService iBzSysTest_caseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_caseget_actual_workloadbegin"
            when
            then
            end

            //逻辑处理节点[获取已登记的工时]
            rule "rawsqlcall1"
            ruleflow-group "test_caseget_actual_workloadrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",test_caseget_actual_workloaddefault.get("id"));
    String strSql="select sum(DURATION) as `ACTUAL_WORKLOAD` from workload where  PRINCIPAL_TYPE = 'TEST_CASE' and PRINCIPAL_ID = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysTest_caseDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    test_caseget_actual_workloaddefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(test_caseget_actual_workloaddefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_caseget_actual_workloadend1"
            when
            then
                        update(test_caseget_actual_workloaddefault);//更新fact中变量值
            end