package cn.ibizlab.plm.testmgmt.logic.test_caselogic.get_library_member;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case test_caseget_library_memberdefault;
                global cn.ibizlab.plm.core.testmgmt.domain.library_member test_caseget_library_memberfilter;
                global java.util.Map test_caseget_library_memberfor_obj;
                global cn.ibizlab.plm.core.testmgmt.domain.library test_caseget_library_memberlibrary_info;
                global cn.ibizlab.plm.core.testmgmt.domain.library_member test_caseget_library_membermembers;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case test_caseget_library_memberticket;
                global java.util.Map test_caseget_library_memberuser;
                global java.util.Map test_caseget_library_memberviewctx;
                global java.util.Map test_caseget_library_memberwebctx;
                    global cn.ibizlab.plm.core.testmgmt.service.Ilibrary_memberService library_memberservice;
        global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService iBzSysTest_caseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_caseget_library_memberbegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam3"
            ruleflow-group "test_caseget_library_memberdebugparam3"
            when
            then
                        update(test_caseget_library_memberdefault);//更新fact中变量值
                        update(test_caseget_library_memberfilter);//更新fact中变量值
                        update(test_caseget_library_memberfor_obj);//更新fact中变量值
                        update(test_caseget_library_memberlibrary_info);//更新fact中变量值
                        update(test_caseget_library_membermembers);//更新fact中变量值
                        update(test_caseget_library_memberticket);//更新fact中变量值
                        update(test_caseget_library_memberuser);//更新fact中变量值
                        update(test_caseget_library_memberviewctx);//更新fact中变量值
                        update(test_caseget_library_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[获取产品id]
            rule "prepareparam2"
            ruleflow-group "test_caseget_library_memberprepareparam2"
            when
            then
                            test_caseget_library_memberlibrary_info.set("id",test_caseget_library_memberdefault.get("testlibraryid"));
                            test_caseget_library_memberfilter.set("n_library_id_eq",test_caseget_library_memberdefault.get("testlibraryid"));
                                test_caseget_library_memberfilter.set("n_user_id_eq",curuser.getSessionParams().get("srfpersonid"));
                        update(test_caseget_library_memberdefault);//更新fact中变量值
                        update(test_caseget_library_memberfilter);//更新fact中变量值
                        update(test_caseget_library_memberfor_obj);//更新fact中变量值
                        update(test_caseget_library_memberlibrary_info);//更新fact中变量值
                        update(test_caseget_library_membermembers);//更新fact中变量值
                        update(test_caseget_library_memberticket);//更新fact中变量值
                        update(test_caseget_library_memberuser);//更新fact中变量值
                        update(test_caseget_library_memberviewctx);//更新fact中变量值
                        update(test_caseget_library_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam6"
            ruleflow-group "test_caseget_library_memberdebugparam6"
            when
            then
                        update(test_caseget_library_memberdefault);//更新fact中变量值
                        update(test_caseget_library_memberfilter);//更新fact中变量值
                        update(test_caseget_library_memberfor_obj);//更新fact中变量值
                        update(test_caseget_library_memberlibrary_info);//更新fact中变量值
                        update(test_caseget_library_membermembers);//更新fact中变量值
                        update(test_caseget_library_memberticket);//更新fact中变量值
                        update(test_caseget_library_memberuser);//更新fact中变量值
                        update(test_caseget_library_memberviewctx);//更新fact中变量值
                        update(test_caseget_library_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset3"
            ruleflow-group "test_caseget_library_memberdedataset3"
            when
            then
                        update(test_caseget_library_memberdefault);//更新fact中变量值
                        update(test_caseget_library_memberfilter);//更新fact中变量值
                        update(test_caseget_library_memberfor_obj);//更新fact中变量值
                        update(test_caseget_library_memberlibrary_info);//更新fact中变量值
                        update(test_caseget_library_membermembers);//更新fact中变量值
                        update(test_caseget_library_memberticket);//更新fact中变量值
                        update(test_caseget_library_memberuser);//更新fact中变量值
                        update(test_caseget_library_memberviewctx);//更新fact中变量值
                        update(test_caseget_library_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall3"
            ruleflow-group "test_caseget_library_memberloopsubcall3"
            when
            then
                        update(test_caseget_library_memberdefault);//更新fact中变量值
                        update(test_caseget_library_memberfilter);//更新fact中变量值
                        update(test_caseget_library_memberfor_obj);//更新fact中变量值
                        update(test_caseget_library_memberlibrary_info);//更新fact中变量值
                        update(test_caseget_library_membermembers);//更新fact中变量值
                        update(test_caseget_library_memberticket);//更新fact中变量值
                        update(test_caseget_library_memberuser);//更新fact中变量值
                        update(test_caseget_library_memberviewctx);//更新fact中变量值
                        update(test_caseget_library_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[只读]
            rule "prepareparam10"
            ruleflow-group "test_caseget_library_memberprepareparam10"
            when
            then
                            test_caseget_library_memberuser.set("readonly","true");
                        update(test_caseget_library_memberdefault);//更新fact中变量值
                        update(test_caseget_library_memberfilter);//更新fact中变量值
                        update(test_caseget_library_memberfor_obj);//更新fact中变量值
                        update(test_caseget_library_memberlibrary_info);//更新fact中变量值
                        update(test_caseget_library_membermembers);//更新fact中变量值
                        update(test_caseget_library_memberticket);//更新fact中变量值
                        update(test_caseget_library_memberuser);//更新fact中变量值
                        update(test_caseget_library_memberviewctx);//更新fact中变量值
                        update(test_caseget_library_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[只读]
            rule "prepareparam8"
            ruleflow-group "test_caseget_library_memberprepareparam8"
            when
            then
                            test_caseget_library_memberuser.set("readonly","true");
                        update(test_caseget_library_memberdefault);//更新fact中变量值
                        update(test_caseget_library_memberfilter);//更新fact中变量值
                        update(test_caseget_library_memberfor_obj);//更新fact中变量值
                        update(test_caseget_library_memberlibrary_info);//更新fact中变量值
                        update(test_caseget_library_membermembers);//更新fact中变量值
                        update(test_caseget_library_memberticket);//更新fact中变量值
                        update(test_caseget_library_memberuser);//更新fact中变量值
                        update(test_caseget_library_memberviewctx);//更新fact中变量值
                        update(test_caseget_library_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[非只读]
            rule "prepareparam9"
            ruleflow-group "test_caseget_library_memberprepareparam9"
            when
            then
                            test_caseget_library_memberuser.set("readonly","false");
                        update(test_caseget_library_memberdefault);//更新fact中变量值
                        update(test_caseget_library_memberfilter);//更新fact中变量值
                        update(test_caseget_library_memberfor_obj);//更新fact中变量值
                        update(test_caseget_library_memberlibrary_info);//更新fact中变量值
                        update(test_caseget_library_membermembers);//更新fact中变量值
                        update(test_caseget_library_memberticket);//更新fact中变量值
                        update(test_caseget_library_memberuser);//更新fact中变量值
                        update(test_caseget_library_memberviewctx);//更新fact中变量值
                        update(test_caseget_library_memberwebctx);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end6"
            ruleflow-group "test_caseget_library_memberend6"
            when
            then
                        update(test_caseget_library_memberdefault);//更新fact中变量值
                        update(test_caseget_library_memberfilter);//更新fact中变量值
                        update(test_caseget_library_memberfor_obj);//更新fact中变量值
                        update(test_caseget_library_memberlibrary_info);//更新fact中变量值
                        update(test_caseget_library_membermembers);//更新fact中变量值
                        update(test_caseget_library_memberticket);//更新fact中变量值
                        update(test_caseget_library_memberuser);//更新fact中变量值
                        update(test_caseget_library_memberviewctx);//更新fact中变量值
                        update(test_caseget_library_memberwebctx);//更新fact中变量值
            end