package cn.ibizlab.plm.testmgmt.logic.test_caselogic.library_get_suite;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Test_case test_caselibrary_get_suitedefault;
        global cn.ibizlab.plm.core.testmgmt.service.ITest_caseService iBzSysTest_caseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_caselibrary_get_suitebegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_caselibrary_get_suiteend1"
            when
            then
                        update(test_caselibrary_get_suitedefault);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "test_caselibrary_get_suitedebugparam1"
            when
            then
                        update(test_caselibrary_get_suitedefault);//更新fact中变量值
            end