package cn.ibizlab.plm.testmgmt.logic.test_caselogic.newest_run;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Test_case test_casenewest_rundefault;
                    global cn.ibizlab.plm.core.testmgmt.service.ITest_caseService test_caseservice;
        global cn.ibizlab.plm.core.testmgmt.service.ITest_caseService iBzSysTest_caseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_casenewest_runbegin"
            when
            then
            end

            //逻辑处理节点[获取测试用例]
            rule "deaction1"
            ruleflow-group "test_casenewest_rundeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(test_caseservice.get(test_casenewest_rundefault.getId()),test_casenewest_rundefault);
                        update(test_casenewest_rundefault);//更新fact中变量值
            end

            //逻辑处理节点[获取最近执行信息]
            rule "rawsqlcall1"
            ruleflow-group "test_casenewest_runrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",test_casenewest_rundefault.get("id"));
    String strSql="select t2.name as test_plan_name,t.EXECUTOR_NAME,t.EXECUTED_AT,t.`STATUS` as run_status from run t,test_plan t2 where  t.CASE_ID=#{et.param0} and t.`STATUS` is not null and t.PLAN_ID=t2.id  order by EXECUTED_AT desc LIMIT 1";
                        java.util.List<JSONObject> entities=iBzSysTest_caseDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    test_casenewest_rundefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(test_casenewest_rundefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_casenewest_runend1"
            when
            then
                        update(test_casenewest_rundefault);//更新fact中变量值
            end