package cn.ibizlab.plm.testmgmt.logic.test_caselogic.plan_compar_ative_analysis;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Test_case test_caseplan_compar_ative_analysisdefault;
                global java.util.Map test_caseplan_compar_ative_analysisresult;
        global cn.ibizlab.plm.core.testmgmt.service.ITest_caseService iBzSysTest_caseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_caseplan_compar_ative_analysisbegin"
            when
            then
            end

            //逻辑处理节点[直接sql调用]
            rule "rawsqlcall1"
            ruleflow-group "test_caseplan_compar_ative_analysisrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",test_caseplan_compar_ative_analysisdefault.get("n_test_library_id_eq"));
    String strSql="SELECT     tp.ID AS filter_type,     tp.Name AS TestPlanName,     COUNT(r.ID) AS TotalRuns, -- 执行用例数量     COALESCE(SUM(CASE WHEN r.status IS NOT NULL THEN 1 ELSE 0 END), 0) AS ExecutedRuns, -- 已执行用例数量     COALESCE(SUM(CASE WHEN r.status = '10' THEN 1 ELSE 0 END), 0) AS PassedRuns, -- 通过的用例数量     -- 测试执行率：已执行用例数量 / 执行用例数量（     CONCAT(COALESCE(ROUND(SUM(CASE WHEN r.status IS NOT NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(r.ID), 0), 2), 0.00), '%') AS ExecutionRate,     -- 测试通过率：通过的用例数量 / 已执行用例数量     CONCAT(COALESCE(ROUND(SUM(CASE WHEN r.status = '10' THEN 1 ELSE 0 END) * 100.0 / NULLIF(SUM(CASE WHEN r.status IS NOT NULL THEN 1 ELSE 0 END), 0), 2), 0.00), '%') AS PassRate FROM     test_plan tp         LEFT JOIN run r ON tp.ID = r.plan_id         LEFT JOIN test_case tc ON r.case_id = tc.ID WHERE         tc.TEST_LIBRARY_ID = #{et.param0} GROUP BY     tp.ID ORDER BY     tp.ID;";
                        java.util.List<JSONObject> entities=iBzSysTest_caseDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                test_caseplan_compar_ative_analysisresult.putAll(entity);
                            }
                        update(test_caseplan_compar_ative_analysisdefault);//更新fact中变量值
                        update(test_caseplan_compar_ative_analysisresult);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_caseplan_compar_ative_analysisend1"
            when
            then
                        update(test_caseplan_compar_ative_analysisdefault);//更新fact中变量值
                        update(test_caseplan_compar_ative_analysisresult);//更新fact中变量值
            end