package cn.ibizlab.plm.testmgmt.logic.test_caselogic.recover;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Test_case test_caserecoverdefault;
                    global cn.ibizlab.plm.core.testmgmt.service.ITest_caseService test_caseservice;
        global cn.ibizlab.plm.core.testmgmt.service.ITest_caseService iBzSysTest_caseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_caserecoverbegin"
            when
            then
            end

            //逻辑处理节点[设置删除状态]
            rule "prepareparam1"
            ruleflow-group "test_caserecoverprepareparam1"
            when
            then
                            test_caserecoverdefault.set("isdeleted","0");
                        update(test_caserecoverdefault);//更新fact中变量值
            end

            //逻辑处理节点[更新删除状态]
            rule "deaction1"
            ruleflow-group "test_caserecoverdeaction1"
            when
            then
                        test_caseservice.update(test_caserecoverdefault);
                        update(test_caserecoverdefault);//更新fact中变量值
            end

            //逻辑处理节点[恢复最近访问]
            rule "rawsqlcall1"
            ruleflow-group "test_caserecoverrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",test_caserecoverdefault.get("id"));
    String strSql="update recent set IS_DELETED=0 where owner_id=#{et.param0} and owner_subtype='test_case'";
                        iBzSysTest_caseDefaultService.execute(strSql,param);//SQL调用
                        update(test_caserecoverdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_caserecoverend1"
            when
            then
                        update(test_caserecoverdefault);//更新fact中变量值
            end