package cn.ibizlab.plm.testmgmt.logic.test_caselogic.set_maintenance;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Test_case test_caseset_maintenancedefault;
                global cn.ibizlab.plm.core.testmgmt.domain.Test_case test_caseset_maintenancefor_temp_obj;
                global cn.ibizlab.plm.core.testmgmt.domain.Test_case test_caseset_maintenancesrfactionparam;
                    global cn.ibizlab.plm.core.testmgmt.service.ITest_caseService test_caseservice;
        global cn.ibizlab.plm.core.testmgmt.service.ITest_caseService iBzSysTest_caseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_caseset_maintenancebegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "test_caseset_maintenancedebugparam1"
            when
            then
                        update(test_caseset_maintenancedefault);//更新fact中变量值
                        update(test_caseset_maintenancefor_temp_obj);//更新fact中变量值
                        update(test_caseset_maintenancesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "test_caseset_maintenancebindparam1"
            when
            then
                        update(test_caseset_maintenancedefault);//更新fact中变量值
                        update(test_caseset_maintenancefor_temp_obj);//更新fact中变量值
                        update(test_caseset_maintenancesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "test_caseset_maintenanceloopsubcall1"
            when
            then
                        update(test_caseset_maintenancedefault);//更新fact中变量值
                        update(test_caseset_maintenancefor_temp_obj);//更新fact中变量值
                        update(test_caseset_maintenancesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "test_caseset_maintenanceprepareparam2"
            when
            then
                            test_caseset_maintenancedefault.set("maintenanceid",test_caseset_maintenancefor_temp_obj.get("maintenanceid"));
                            test_caseset_maintenancedefault.set("maintenancename",test_caseset_maintenancefor_temp_obj.get("maintenancename"));
                        update(test_caseset_maintenancedefault);//更新fact中变量值
                        update(test_caseset_maintenancefor_temp_obj);//更新fact中变量值
                        update(test_caseset_maintenancesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[变更状态]
            rule "deaction1"
            ruleflow-group "test_caseset_maintenancedeaction1"
            when
            then
                        test_caseservice.update(test_caseset_maintenancedefault);
                        update(test_caseset_maintenancedefault);//更新fact中变量值
                        update(test_caseset_maintenancefor_temp_obj);//更新fact中变量值
                        update(test_caseset_maintenancesrfactionparam);//更新fact中变量值
            end