package cn.ibizlab.plm.testmgmt.logic.test_caselogic.set_state;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case test_caseset_statedefault;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case test_caseset_statefor_temp_obj;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case test_caseset_statesrfactionparam;
                    global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService test_caseservice;
        global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService iBzSysTest_caseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_caseset_statebegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "test_caseset_statebindparam1"
            when
            then
                        update(test_caseset_statedefault);//更新fact中变量值
                        update(test_caseset_statefor_temp_obj);//更新fact中变量值
                        update(test_caseset_statesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[变更状态]
            rule "deaction1"
            ruleflow-group "test_caseset_statedeaction1"
            when
            then
                        test_caseservice.update(test_caseset_statedefault);
                        update(test_caseset_statedefault);//更新fact中变量值
                        update(test_caseset_statefor_temp_obj);//更新fact中变量值
                        update(test_caseset_statesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "test_caseset_stateloopsubcall1"
            when
            then
                        update(test_caseset_statedefault);//更新fact中变量值
                        update(test_caseset_statefor_temp_obj);//更新fact中变量值
                        update(test_caseset_statesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[设置用例状态参数]
            rule "prepareparam2"
            ruleflow-group "test_caseset_stateprepareparam2"
            when
            then
                            test_caseset_statedefault.set("state",test_caseset_statefor_temp_obj.get("state"));
                        update(test_caseset_statedefault);//更新fact中变量值
                        update(test_caseset_statefor_temp_obj);//更新fact中变量值
                        update(test_caseset_statesrfactionparam);//更新fact中变量值
            end