package cn.ibizlab.plm.prodmgmt.logic.product_memberlogic.change_role;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_member product_memberchange_roledefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_member product_memberchange_rolefor_temp_obj;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_member product_memberchange_rolesrfactionparam;
                    global cn.ibizlab.plm.core.prodmgmt.service.Iproduct_memberService product_memberservice;
        global cn.ibizlab.plm.core.prodmgmt.service.Iproduct_memberService iBzSysProduct_memberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "product_memberchange_rolebegin"
            when
            then
            end

            //逻辑处理节点[获取传递的参数]
            rule "bindparam1"
            ruleflow-group "product_memberchange_rolebindparam1"
            when
            then
                        update(product_memberchange_roledefault);//更新fact中变量值
                        update(product_memberchange_rolefor_temp_obj);//更新fact中变量值
                        update(product_memberchange_rolesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环id列表进行操作]
            rule "loopsubcall1"
            ruleflow-group "product_memberchange_roleloopsubcall1"
            when
            then
                        update(product_memberchange_roledefault);//更新fact中变量值
                        update(product_memberchange_rolefor_temp_obj);//更新fact中变量值
                        update(product_memberchange_rolesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[获取传递的状态]
            rule "prepareparam2"
            ruleflow-group "product_memberchange_roleprepareparam2"
            when
            then
                            product_memberchange_roledefault.set("roleid",product_memberchange_rolefor_temp_obj.get("roleid"));
                        update(product_memberchange_roledefault);//更新fact中变量值
                        update(product_memberchange_rolefor_temp_obj);//更新fact中变量值
                        update(product_memberchange_rolesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[变更状态]
            rule "deaction1"
            ruleflow-group "product_memberchange_roledeaction1"
            when
            then
                        product_memberservice.update(product_memberchange_roledefault);
                        update(product_memberchange_roledefault);//更新fact中变量值
                        update(product_memberchange_rolefor_temp_obj);//更新fact中变量值
                        update(product_memberchange_rolesrfactionparam);//更新fact中变量值
            end