package cn.ibizlab.plm.prodmgmt.logic.product_memberlogic.mob_create_product_member;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_member product_membermob_create_product_memberdefault;
                global cn.ibizlab.plm.core.base.domain.user product_membermob_create_product_memberfor_temp_obj;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_member product_membermob_create_product_membermember_obj;
                global cn.ibizlab.plm.core.base.domain.user product_membermob_create_product_memberselectdata;
                    global cn.ibizlab.plm.core.prodmgmt.service.Iproduct_memberService product_memberservice;
        global cn.ibizlab.plm.core.prodmgmt.service.Iproduct_memberService iBzSysProduct_memberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "product_membermob_create_product_memberbegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "product_membermob_create_product_memberbindparam1"
            when
            then
                        update(product_membermob_create_product_memberdefault);//更新fact中变量值
                        update(product_membermob_create_product_memberfor_temp_obj);//更新fact中变量值
                        update(product_membermob_create_product_membermember_obj);//更新fact中变量值
                        update(product_membermob_create_product_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "product_membermob_create_product_memberloopsubcall1"
            when
            then
                        update(product_membermob_create_product_memberdefault);//更新fact中变量值
                        update(product_membermob_create_product_memberfor_temp_obj);//更新fact中变量值
                        update(product_membermob_create_product_membermember_obj);//更新fact中变量值
                        update(product_membermob_create_product_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "product_membermob_create_product_memberrenewparam1"
            when
            then
                        update(product_membermob_create_product_memberdefault);//更新fact中变量值
                        update(product_membermob_create_product_memberfor_temp_obj);//更新fact中变量值
                        update(product_membermob_create_product_membermember_obj);//更新fact中变量值
                        update(product_membermob_create_product_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[填充产品成员属性]
            rule "prepareparam1"
            ruleflow-group "product_membermob_create_product_memberprepareparam1"
            when
            then
                            product_membermob_create_product_membermember_obj.set("userid",product_membermob_create_product_memberfor_temp_obj.get("userid"));
                            product_membermob_create_product_membermember_obj.set("name",product_membermob_create_product_memberfor_temp_obj.get("displayname"));
                            product_membermob_create_product_membermember_obj.set("productid",product_membermob_create_product_memberdefault.get("productid"));
                        update(product_membermob_create_product_memberdefault);//更新fact中变量值
                        update(product_membermob_create_product_memberfor_temp_obj);//更新fact中变量值
                        update(product_membermob_create_product_membermember_obj);//更新fact中变量值
                        update(product_membermob_create_product_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "product_membermob_create_product_memberprepareparam2"
            when
            then
                            product_membermob_create_product_membermember_obj.set("userid",product_membermob_create_product_memberfor_temp_obj.get("id"));
                        update(product_membermob_create_product_memberdefault);//更新fact中变量值
                        update(product_membermob_create_product_memberfor_temp_obj);//更新fact中变量值
                        update(product_membermob_create_product_membermember_obj);//更新fact中变量值
                        update(product_membermob_create_product_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[建立产品成员]
            rule "deaction1"
            ruleflow-group "product_membermob_create_product_memberdeaction1"
            when
            then
                        product_memberservice.save(product_membermob_create_product_membermember_obj);
                        update(product_membermob_create_product_memberdefault);//更新fact中变量值
                        update(product_membermob_create_product_memberfor_temp_obj);//更新fact中变量值
                        update(product_membermob_create_product_membermember_obj);//更新fact中变量值
                        update(product_membermob_create_product_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "product_membermob_create_product_memberend1"
            when
            then
                        update(product_membermob_create_product_memberdefault);//更新fact中变量值
                        update(product_membermob_create_product_memberfor_temp_obj);//更新fact中变量值
                        update(product_membermob_create_product_membermember_obj);//更新fact中变量值
                        update(product_membermob_create_product_memberselectdata);//更新fact中变量值
            end