package cn.ibizlab.plm.team.logic.discuss_topiclogic.move_discuss_topic;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_topic discuss_topicmove_discuss_topicdefault;
                global cn.ibizlab.plm.core.team.domain.discuss_topic discuss_topicmove_discuss_topicfor_temp_obj;
                global cn.ibizlab.plm.core.team.domain.discuss_topic discuss_topicmove_discuss_topicsrfactionparam;
                global cn.ibizlab.plm.core.team.domain.discuss_topic discuss_topicmove_discuss_topicupdate_obj;
                    global cn.ibizlab.plm.core.team.service.Idiscuss_topicService discuss_topicservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_topicService iBzSysDiscuss_topicDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_topicmove_discuss_topicbegin"
            when
            then
            end

            //逻辑处理节点[绑定话题信息参数]
            rule "bindparam1"
            ruleflow-group "discuss_topicmove_discuss_topicbindparam1"
            when
            then
                        update(discuss_topicmove_discuss_topicdefault);//更新fact中变量值
                        update(discuss_topicmove_discuss_topicfor_temp_obj);//更新fact中变量值
                        update(discuss_topicmove_discuss_topicsrfactionparam);//更新fact中变量值
                        update(discuss_topicmove_discuss_topicupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环处理话题]
            rule "loopsubcall1"
            ruleflow-group "discuss_topicmove_discuss_topicloopsubcall1"
            when
            then
                        update(discuss_topicmove_discuss_topicdefault);//更新fact中变量值
                        update(discuss_topicmove_discuss_topicfor_temp_obj);//更新fact中变量值
                        update(discuss_topicmove_discuss_topicsrfactionparam);//更新fact中变量值
                        update(discuss_topicmove_discuss_topicupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[准备更新话题参数]
            rule "prepareparam1"
            ruleflow-group "discuss_topicmove_discuss_topicprepareparam1"
            when
            then
                            discuss_topicmove_discuss_topicupdate_obj.set("scopetype",discuss_topicmove_discuss_topicfor_temp_obj.get("scopetype"));
                            discuss_topicmove_discuss_topicupdate_obj.set("id",discuss_topicmove_discuss_topicfor_temp_obj.get("id"));
                            discuss_topicmove_discuss_topicupdate_obj.set("scopeid",discuss_topicmove_discuss_topicfor_temp_obj.get("scopeid"));
                            discuss_topicmove_discuss_topicupdate_obj.set("visibility",discuss_topicmove_discuss_topicfor_temp_obj.get("visibility"));
                        update(discuss_topicmove_discuss_topicdefault);//更新fact中变量值
                        update(discuss_topicmove_discuss_topicfor_temp_obj);//更新fact中变量值
                        update(discuss_topicmove_discuss_topicsrfactionparam);//更新fact中变量值
                        update(discuss_topicmove_discuss_topicupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[更新话题属性]
            rule "deaction1"
            ruleflow-group "discuss_topicmove_discuss_topicdeaction1"
            when
            then
                        discuss_topicservice.update(discuss_topicmove_discuss_topicupdate_obj);
                        update(discuss_topicmove_discuss_topicdefault);//更新fact中变量值
                        update(discuss_topicmove_discuss_topicfor_temp_obj);//更新fact中变量值
                        update(discuss_topicmove_discuss_topicsrfactionparam);//更新fact中变量值
                        update(discuss_topicmove_discuss_topicupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_topicmove_discuss_topicend1"
            when
            then
                        update(discuss_topicmove_discuss_topicdefault);//更新fact中变量值
                        update(discuss_topicmove_discuss_topicfor_temp_obj);//更新fact中变量值
                        update(discuss_topicmove_discuss_topicsrfactionparam);//更新fact中变量值
                        update(discuss_topicmove_discuss_topicupdate_obj);//更新fact中变量值
            end