package cn.ibizlab.plm.ai.logic.ai_kb_chunklogic.retrieval_test;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_chunk ai_kb_chunkretrieval_testdefault;
        global cn.ibizlab.plm.core.ai.service.Iai_kb_chunkService iBzSysAi_kb_chunkDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_kb_chunkretrieval_testbegin"
            when
            then
            end