package cn.ibizlab.plm.prodmgmt.logic.customerlogic.delete_categories;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.customer customerdelete_categoriesdefault;
                global java.util.Map customerdelete_categoriesfilter;
                global cn.ibizlab.plm.core.prodmgmt.domain.customer customerdelete_categoriesplan_filter;
                global cn.ibizlab.plm.core.prodmgmt.domain.customer customerdelete_categoriesproduct_plan_pages;
        global cn.ibizlab.plm.core.prodmgmt.service.IcustomerService iBzSysCustomerDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "customerdelete_categoriesbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "customerdelete_categoriesend1"
            when
            then
                        update(customerdelete_categoriesdefault);//更新fact中变量值
                        update(customerdelete_categoriesfilter);//更新fact中变量值
                        update(customerdelete_categoriesplan_filter);//更新fact中变量值
                        update(customerdelete_categoriesproduct_plan_pages);//更新fact中变量值
            end

            //逻辑处理节点[当删除类别时，修改客户的类别属性]
            rule "rawsqlcall1"
            ruleflow-group "customerdelete_categoriesrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",customerdelete_categoriesdefault.get("id"));
        param.put("param1",customerdelete_categoriesdefault.get("id"));
    String strSql="UPDATE customer SET categories = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', categories, ','), CONCAT(',', #{et.param0}, ','), ',')) WHERE FIND_IN_SET(#{et.param1}, categories) > 0 ;";
                        iBzSysCustomerDefaultService.execute(strSql,param);//SQL调用
                        update(customerdelete_categoriesdefault);//更新fact中变量值
                        update(customerdelete_categoriesfilter);//更新fact中变量值
                        update(customerdelete_categoriesplan_filter);//更新fact中变量值
                        update(customerdelete_categoriesproduct_plan_pages);//更新fact中变量值
            end