package cn.ibizlab.plm.prodmgmt.logic.customerlogic.get_idea_customer_info;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.customer customerget_idea_customer_infodefault;
                global cn.ibizlab.plm.core.base.domain.relation customerget_idea_customer_infofilter;
                global cn.ibizlab.plm.core.base.domain.relation customerget_idea_customer_inforelation_page;
                global cn.ibizlab.plm.core.prodmgmt.domain.customer customerget_idea_customer_inforesult;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IcustomerService iBzSysCustomerDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "customerget_idea_customer_infobegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "customerget_idea_customer_infoend1"
            when
            then
                        update(customerget_idea_customer_infodefault);//更新fact中变量值
                        update(customerget_idea_customer_infofilter);//更新fact中变量值
                        update(customerget_idea_customer_inforelation_page);//更新fact中变量值
                        update(customerget_idea_customer_inforesult);//更新fact中变量值
            end

            //逻辑处理节点[设置过滤器]
            rule "prepareparam1"
            ruleflow-group "customerget_idea_customer_infoprepareparam1"
            when
            then
                            customerget_idea_customer_infofilter.set("n_principal_id_eq",customerget_idea_customer_infodefault.get("idea"));
                            customerget_idea_customer_infofilter.set("n_target_type_eq","customer");
                        update(customerget_idea_customer_infodefault);//更新fact中变量值
                        update(customerget_idea_customer_infofilter);//更新fact中变量值
                        update(customerget_idea_customer_inforelation_page);//更新fact中变量值
                        update(customerget_idea_customer_inforesult);//更新fact中变量值
            end

            //逻辑处理节点[获取需求关联的客户]
            rule "dedataset1"
            ruleflow-group "customerget_idea_customer_infodedataset1"
            when
            then
                        update(customerget_idea_customer_infodefault);//更新fact中变量值
                        update(customerget_idea_customer_infofilter);//更新fact中变量值
                        update(customerget_idea_customer_inforelation_page);//更新fact中变量值
                        update(customerget_idea_customer_inforesult);//更新fact中变量值
            end

            //逻辑处理节点[计算分数]
            rule "rawsfcode1"
            ruleflow-group "customerget_idea_customer_inforawsfcode1"
            when
            then
                        update(customerget_idea_customer_infodefault);//更新fact中变量值
                        update(customerget_idea_customer_infofilter);//更新fact中变量值
                        update(customerget_idea_customer_inforelation_page);//更新fact中变量值
                        update(customerget_idea_customer_inforesult);//更新fact中变量值
            end