package cn.ibizlab.plm.prodmgmt.logic.customerlogic.remove_customer_notify;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.customer customerremove_customer_notifydefault;
                    global cn.ibizlab.plm.core.prodmgmt.service.IcustomerService customerservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IcustomerService iBzSysCustomerDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "customerremove_customer_notifybegin"
            when
            then
            end

            //逻辑处理节点[获取客户信息]
            rule "deaction1"
            ruleflow-group "customerremove_customer_notifydeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(customerservice.get(customerremove_customer_notifydefault.getId()),customerremove_customer_notifydefault);
                        update(customerremove_customer_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[获取当前操作人]
            rule "prepareparam1"
            ruleflow-group "customerremove_customer_notifyprepareparam1"
            when
            then
                                customerremove_customer_notifydefault.set("updateman",curuser.getSessionParams().get("srfpersonid"));
                        update(customerremove_customer_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[获取操作时间]
            rule "rawsfcode1"
            ruleflow-group "customerremove_customer_notifyrawsfcode1"
            when
            then
                        update(customerremove_customer_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[删除客户通知]
            rule "denotify1"
            ruleflow-group "customerremove_customer_notifydenotify1"
            when
            then
                        update(customerremove_customer_notifydefault);//更新fact中变量值
            end