package cn.ibizlab.plm.base.logic.login_loglogic.active_chart_datas;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.login_log login_logactive_chart_datasdefault;
        global cn.ibizlab.plm.core.base.service.Ilogin_logService iBzSysLogin_logDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "login_logactive_chart_datasbegin"
            when
            then
            end