package cn.ibizlab.plm.base.logic.login_loglogic.active_members;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.login_log login_logactive_membersdefault;
                global cn.ibizlab.plm.core.base.domain.login_log login_logactive_membersactive_obj;
                global cn.ibizlab.plm.core.base.domain.login_log login_logactive_membersactive_page;
                    global cn.ibizlab.plm.core.base.service.Ilogin_logService login_logservice;
        global cn.ibizlab.plm.core.base.service.Ilogin_logService iBzSysLogin_logDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "login_logactive_membersbegin"
            when
            then
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode1"
            ruleflow-group "login_logactive_membersrawsfcode1"
            when
            then
                        update(login_logactive_membersdefault);//更新fact中变量值
                        update(login_logactive_membersactive_obj);//更新fact中变量值
                        update(login_logactive_membersactive_page);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "login_logactive_membersprepareparam1"
            when
            then
                        update(login_logactive_membersdefault);//更新fact中变量值
                        update(login_logactive_membersactive_obj);//更新fact中变量值
                        update(login_logactive_membersactive_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "login_logactive_membersend1"
            when
            then
                        update(login_logactive_membersdefault);//更新fact中变量值
                        update(login_logactive_membersactive_obj);//更新fact中变量值
                        update(login_logactive_membersactive_page);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "login_logactive_membersdedataset1"
            when
            then
                        update(login_logactive_membersdefault);//更新fact中变量值
                        update(login_logactive_membersactive_obj);//更新fact中变量值
                        update(login_logactive_membersactive_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "login_logactive_membersloopsubcall1"
            when
            then
                        update(login_logactive_membersdefault);//更新fact中变量值
                        update(login_logactive_membersactive_obj);//更新fact中变量值
                        update(login_logactive_membersactive_page);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode2"
            ruleflow-group "login_logactive_membersrawsfcode2"
            when
            then
                        update(login_logactive_membersdefault);//更新fact中变量值
                        update(login_logactive_membersactive_obj);//更新fact中变量值
                        update(login_logactive_membersactive_page);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "login_logactive_membersprepareparam2"
            when
            then
                        update(login_logactive_membersdefault);//更新fact中变量值
                        update(login_logactive_membersactive_obj);//更新fact中变量值
                        update(login_logactive_membersactive_page);//更新fact中变量值
            end