package cn.ibizlab.plm.base.logic.activitylogic.get_activity_obj_detail;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.activity activityget_activity_obj_detaildefault;
                global java.util.Map activityget_activity_obj_detailobject_id;
                global cn.ibizlab.plm.core.base.domain.activity activityget_activity_obj_detaildetail_info;
                global java.util.Map activityget_activity_obj_detailoption_info;
                    global cn.ibizlab.plm.core.prodmgmt.service.IideaService ideaservice;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
                    global cn.ibizlab.plm.core.prodmgmt.service.IticketService ticketservice;
                    global cn.ibizlab.plm.core.prodmgmt.service.IcustomerService customerservice;
                    global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService test_caseservice;
                    global cn.ibizlab.plm.core.testmgmt.service.IrunService runservice;
                    global cn.ibizlab.plm.core.wiki.service.Iarticle_pageService article_pageservice;
        global cn.ibizlab.plm.core.base.service.IactivityService iBzSysActivityDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "activityget_activity_obj_detailbegin"
            when
            then
            end

            //逻辑处理节点[获取详情类详情]
            rule "deaction2"
            ruleflow-group "activityget_activity_obj_detaildeaction2"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(ideaservice.get(activityget_activity_obj_detaildetail_info.getId()),activityget_activity_obj_detaildetail_info);
                        update(activityget_activity_obj_detaildefault);//更新fact中变量值
                        update(activityget_activity_obj_detailobject_id);//更新fact中变量值
                        update(activityget_activity_obj_detaildetail_info);//更新fact中变量值
                        update(activityget_activity_obj_detailoption_info);//更新fact中变量值
            end

            //逻辑处理节点[获取工作项类详情]
            rule "deaction1"
            ruleflow-group "activityget_activity_obj_detaildeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(work_itemservice.get(activityget_activity_obj_detaildetail_info.getId()),activityget_activity_obj_detaildetail_info);
                        update(activityget_activity_obj_detaildefault);//更新fact中变量值
                        update(activityget_activity_obj_detailobject_id);//更新fact中变量值
                        update(activityget_activity_obj_detaildetail_info);//更新fact中变量值
                        update(activityget_activity_obj_detailoption_info);//更新fact中变量值
            end

            //逻辑处理节点[设置选中id]
            rule "prepareparam1"
            ruleflow-group "activityget_activity_obj_detailprepareparam1"
            when
            then
                            activityget_activity_obj_detaildetail_info.set("id",activityget_activity_obj_detaildefault.get("object_id"));
                        update(activityget_activity_obj_detaildefault);//更新fact中变量值
                        update(activityget_activity_obj_detailobject_id);//更新fact中变量值
                        update(activityget_activity_obj_detaildetail_info);//更新fact中变量值
                        update(activityget_activity_obj_detailoption_info);//更新fact中变量值
            end

            //逻辑处理节点[获取工单类详情]
            rule "deaction3"
            ruleflow-group "activityget_activity_obj_detaildeaction3"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(ticketservice.get(activityget_activity_obj_detaildetail_info.getId()),activityget_activity_obj_detaildetail_info);
                        update(activityget_activity_obj_detaildefault);//更新fact中变量值
                        update(activityget_activity_obj_detailobject_id);//更新fact中变量值
                        update(activityget_activity_obj_detaildetail_info);//更新fact中变量值
                        update(activityget_activity_obj_detailoption_info);//更新fact中变量值
            end

            //逻辑处理节点[获取客户类详情]
            rule "deaction4"
            ruleflow-group "activityget_activity_obj_detaildeaction4"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(customerservice.get(activityget_activity_obj_detaildetail_info.getId()),activityget_activity_obj_detaildetail_info);
                        update(activityget_activity_obj_detaildefault);//更新fact中变量值
                        update(activityget_activity_obj_detailobject_id);//更新fact中变量值
                        update(activityget_activity_obj_detaildetail_info);//更新fact中变量值
                        update(activityget_activity_obj_detailoption_info);//更新fact中变量值
            end

            //逻辑处理节点[获取测试用例类需求]
            rule "deaction5"
            ruleflow-group "activityget_activity_obj_detaildeaction5"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(test_caseservice.get(activityget_activity_obj_detaildetail_info.getId()),activityget_activity_obj_detaildetail_info);
                        update(activityget_activity_obj_detaildefault);//更新fact中变量值
                        update(activityget_activity_obj_detailobject_id);//更新fact中变量值
                        update(activityget_activity_obj_detaildetail_info);//更新fact中变量值
                        update(activityget_activity_obj_detailoption_info);//更新fact中变量值
            end

            //逻辑处理节点[设置项目信息]
            rule "prepareparam2"
            ruleflow-group "activityget_activity_obj_detailprepareparam2"
            when
            then
                            activityget_activity_obj_detailoption_info.set("parent_id",activityget_activity_obj_detaildetail_info.get("project_id"));
                            activityget_activity_obj_detailoption_info.set("self_id",activityget_activity_obj_detaildetail_info.get("id"));
                        update(activityget_activity_obj_detaildefault);//更新fact中变量值
                        update(activityget_activity_obj_detailobject_id);//更新fact中变量值
                        update(activityget_activity_obj_detaildetail_info);//更新fact中变量值
                        update(activityget_activity_obj_detailoption_info);//更新fact中变量值
            end

            //逻辑处理节点[设置产品信息]
            rule "prepareparam3"
            ruleflow-group "activityget_activity_obj_detailprepareparam3"
            when
            then
                            activityget_activity_obj_detailoption_info.set("parent_id",activityget_activity_obj_detaildetail_info.get("product_id"));
                            activityget_activity_obj_detailoption_info.set("self_id",activityget_activity_obj_detaildetail_info.get("id"));
                        update(activityget_activity_obj_detaildefault);//更新fact中变量值
                        update(activityget_activity_obj_detailobject_id);//更新fact中变量值
                        update(activityget_activity_obj_detaildetail_info);//更新fact中变量值
                        update(activityget_activity_obj_detailoption_info);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "activityget_activity_obj_detailend1"
            when
            then
                        update(activityget_activity_obj_detaildefault);//更新fact中变量值
                        update(activityget_activity_obj_detailobject_id);//更新fact中变量值
                        update(activityget_activity_obj_detaildetail_info);//更新fact中变量值
                        update(activityget_activity_obj_detailoption_info);//更新fact中变量值
            end

            //逻辑处理节点[设置测试库信息]
            rule "prepareparam4"
            ruleflow-group "activityget_activity_obj_detailprepareparam4"
            when
            then
                            activityget_activity_obj_detailoption_info.set("parent_id",activityget_activity_obj_detaildetail_info.get("test_library_id"));
                            activityget_activity_obj_detailoption_info.set("self_id",activityget_activity_obj_detaildetail_info.get("id"));
                        update(activityget_activity_obj_detaildefault);//更新fact中变量值
                        update(activityget_activity_obj_detailobject_id);//更新fact中变量值
                        update(activityget_activity_obj_detaildetail_info);//更新fact中变量值
                        update(activityget_activity_obj_detailoption_info);//更新fact中变量值
            end

            //逻辑处理节点[获取执行用例类数据]
            rule "deaction6"
            ruleflow-group "activityget_activity_obj_detaildeaction6"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(runservice.get(activityget_activity_obj_detaildetail_info.getId()),activityget_activity_obj_detaildetail_info);
                        update(activityget_activity_obj_detaildefault);//更新fact中变量值
                        update(activityget_activity_obj_detailobject_id);//更新fact中变量值
                        update(activityget_activity_obj_detaildetail_info);//更新fact中变量值
                        update(activityget_activity_obj_detailoption_info);//更新fact中变量值
            end

            //逻辑处理节点[获取页面类数据]
            rule "deaction7"
            ruleflow-group "activityget_activity_obj_detaildeaction7"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(article_pageservice.get(activityget_activity_obj_detaildetail_info.getId()),activityget_activity_obj_detaildetail_info);
                        update(activityget_activity_obj_detaildefault);//更新fact中变量值
                        update(activityget_activity_obj_detailobject_id);//更新fact中变量值
                        update(activityget_activity_obj_detaildetail_info);//更新fact中变量值
                        update(activityget_activity_obj_detailoption_info);//更新fact中变量值
            end

            //逻辑处理节点[设置空间信息]
            rule "prepareparam5"
            ruleflow-group "activityget_activity_obj_detailprepareparam5"
            when
            then
                            activityget_activity_obj_detailoption_info.set("parent_id",activityget_activity_obj_detaildetail_info.get("space_id"));
                            activityget_activity_obj_detailoption_info.set("self_id",activityget_activity_obj_detaildetail_info.get("id"));
                        update(activityget_activity_obj_detaildefault);//更新fact中变量值
                        update(activityget_activity_obj_detailobject_id);//更新fact中变量值
                        update(activityget_activity_obj_detaildetail_info);//更新fact中变量值
                        update(activityget_activity_obj_detailoption_info);//更新fact中变量值
            end