package cn.ibizlab.plm.base.logic.sectionlogic.sort;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.section sectionsortdefault;
                global cn.ibizlab.plm.core.base.domain.section sectionsortfilter;
                global cn.ibizlab.plm.core.base.domain.section sectionsortpage;
                    global cn.ibizlab.plm.core.base.service.IsectionService sectionservice;
        global cn.ibizlab.plm.core.base.service.IsectionService iBzSysSectionDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "sectionsortbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "sectionsortprepareparam1"
            when
            then
                            sectionsortfilter.set("n_owner_type_eq",sectionsortdefault.get("ownertype"));
                            sectionsortfilter.set("sort","sequence,desc");
                            sectionsortfilter.set("n_owner_subtype_eq",sectionsortdefault.get("ownersubtype"));
                            sectionsortfilter.set("n_owner_id_eq",sectionsortdefault.get("ownerid"));
                        update(sectionsortdefault);//更新fact中变量值
                        update(sectionsortfilter);//更新fact中变量值
                        update(sectionsortpage);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "sectionsortdedataset1"
            when
            then
                        update(sectionsortdefault);//更新fact中变量值
                        update(sectionsortfilter);//更新fact中变量值
                        update(sectionsortpage);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode1"
            ruleflow-group "sectionsortrawsfcode1"
            when
            then
                        update(sectionsortdefault);//更新fact中变量值
                        update(sectionsortfilter);//更新fact中变量值
                        update(sectionsortpage);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "sectionsortend1"
            when
            then
                        update(sectionsortdefault);//更新fact中变量值
                        update(sectionsortfilter);//更新fact中变量值
                        update(sectionsortpage);//更新fact中变量值
            end