package cn.ibizlab.plm.base.logic.template_flowlogic.sync_work_item_finish;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item template_flowsync_work_item_finishchild_work_items;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item template_flowsync_work_item_finishdefault;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item template_flowsync_work_item_finishfilter;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item template_flowsync_work_item_finishparent_work_item;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.base.service.Itemplate_flowService iBzSysTemplate_flowDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin_01"
            ruleflow-group "template_flowsync_work_item_finishbegin_01"
            when
            then
                        update(template_flowsync_work_item_finishchild_work_items);//更新fact中变量值
                        update(template_flowsync_work_item_finishdefault);//更新fact中变量值
                        update(template_flowsync_work_item_finishfilter);//更新fact中变量值
                        update(template_flowsync_work_item_finishparent_work_item);//更新fact中变量值
            end

            //逻辑处理节点[设置子工作项过滤条件]
            rule "prepareparam_02"
            ruleflow-group "template_flowsync_work_item_finishprepareparam_02"
            when
            then
                            template_flowsync_work_item_finishfilter.set("n_state_notin","30,40");
                            template_flowsync_work_item_finishfilter.set("n_pid_eq",template_flowsync_work_item_finishdefault.get("pid"));
                        update(template_flowsync_work_item_finishchild_work_items);//更新fact中变量值
                        update(template_flowsync_work_item_finishdefault);//更新fact中变量值
                        update(template_flowsync_work_item_finishfilter);//更新fact中变量值
                        update(template_flowsync_work_item_finishparent_work_item);//更新fact中变量值
            end

            //逻辑处理节点[获取子工作项]
            rule "dedataset_01"
            ruleflow-group "template_flowsync_work_item_finishdedataset_01"
            when
            then
                        update(template_flowsync_work_item_finishchild_work_items);//更新fact中变量值
                        update(template_flowsync_work_item_finishdefault);//更新fact中变量值
                        update(template_flowsync_work_item_finishfilter);//更新fact中变量值
                        update(template_flowsync_work_item_finishparent_work_item);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "template_flowsync_work_item_finishend_01"
            when
            then
                        update(template_flowsync_work_item_finishchild_work_items);//更新fact中变量值
                        update(template_flowsync_work_item_finishdefault);//更新fact中变量值
                        update(template_flowsync_work_item_finishfilter);//更新fact中变量值
                        update(template_flowsync_work_item_finishparent_work_item);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_03"
            ruleflow-group "template_flowsync_work_item_finishprepareparam_03"
            when
            then
                            template_flowsync_work_item_finishparent_work_item.set("id",template_flowsync_work_item_finishdefault.get("pid"));
                            template_flowsync_work_item_finishparent_work_item.set("state",template_flowsync_work_item_finishdefault.get("state"));
                        update(template_flowsync_work_item_finishchild_work_items);//更新fact中变量值
                        update(template_flowsync_work_item_finishdefault);//更新fact中变量值
                        update(template_flowsync_work_item_finishfilter);//更新fact中变量值
                        update(template_flowsync_work_item_finishparent_work_item);//更新fact中变量值
            end

            //逻辑处理节点[更新工作项状态]
            rule "deaction_02"
            ruleflow-group "template_flowsync_work_item_finishdeaction_02"
            when
            then
                        work_itemservice.update(template_flowsync_work_item_finishparent_work_item);
                        update(template_flowsync_work_item_finishchild_work_items);//更新fact中变量值
                        update(template_flowsync_work_item_finishdefault);//更新fact中变量值
                        update(template_flowsync_work_item_finishfilter);//更新fact中变量值
                        update(template_flowsync_work_item_finishparent_work_item);//更新fact中变量值
            end