package cn.ibizlab.plm.testmgmt.logic.test_planlogic.oppriv_logic;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.test_plan test_planoppriv_logicdefault;
                global cn.ibizlab.plm.core.testmgmt.domain.test_plan test_planoppriv_logicoppriv;
        global cn.ibizlab.plm.core.testmgmt.service.Itest_planService iBzSysTest_planDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_planoppriv_logicbegin"
            when
            then
            end

            //逻辑处理节点[不允许修改]
            rule "prepareparam1"
            ruleflow-group "test_planoppriv_logicprepareparam1"
            when
            then
                            test_planoppriv_logicoppriv.set("update","false");
                        update(test_planoppriv_logicdefault);//更新fact中变量值
                        update(test_planoppriv_logicoppriv);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_planoppriv_logicend1"
            when
            then
                        update(test_planoppriv_logicdefault);//更新fact中变量值
                        update(test_planoppriv_logicoppriv);//更新fact中变量值
            end