package cn.ibizlab.plm.testmgmt.logic.test_planlogic.start_test_plan;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.Test_plan test_planstart_test_plandefault;
                    global cn.ibizlab.plm.core.testmgmt.service.ITest_planService test_planservice;
        global cn.ibizlab.plm.core.testmgmt.service.ITest_planService iBzSysTest_planDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_planstart_test_planbegin"
            when
            then
            end

            //逻辑处理节点[设置状态值（in_progress）]
            rule "prepareparam1"
            ruleflow-group "test_planstart_test_planprepareparam1"
            when
            then
                            test_planstart_test_plandefault.set("status","in_progress");
                        update(test_planstart_test_plandefault);//更新fact中变量值
            end

            //逻辑处理节点[更新测试状态]
            rule "deaction1"
            ruleflow-group "test_planstart_test_plandeaction1"
            when
            then
                        test_planservice.update(test_planstart_test_plandefault);
                        update(test_planstart_test_plandefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_planstart_test_planend1"
            when
            then
                        update(test_planstart_test_plandefault);//更新fact中变量值
            end