package cn.ibizlab.plm.team.logic.discuss_postlogic.close;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_post discuss_postclosedefault;
                global cn.ibizlab.plm.core.team.domain.discuss_post discuss_postcloseupdate_obj;
                    global cn.ibizlab.plm.core.team.service.Idiscuss_postService discuss_postservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_postService iBzSysDiscuss_postDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_postclosebegin"
            when
            then
            end

            //逻辑处理节点[设置为关闭状态]
            rule "prepareparam1"
            ruleflow-group "discuss_postcloseprepareparam1"
            when
            then
                            discuss_postcloseupdate_obj.set("id",discuss_postclosedefault.get("id"));
                            discuss_postcloseupdate_obj.set("status","0");
                        update(discuss_postclosedefault);//更新fact中变量值
                        update(discuss_postcloseupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[执行更新]
            rule "deaction1"
            ruleflow-group "discuss_postclosedeaction1"
            when
            then
                        discuss_postservice.update(discuss_postcloseupdate_obj);
                        update(discuss_postclosedefault);//更新fact中变量值
                        update(discuss_postcloseupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_postcloseend1"
            when
            then
                        update(discuss_postclosedefault);//更新fact中变量值
                        update(discuss_postcloseupdate_obj);//更新fact中变量值
            end