package cn.ibizlab.plm.team.logic.discuss_postlogic.fill_addition;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_post discuss_postfill_additiondefault;
        global cn.ibizlab.plm.core.team.service.Idiscuss_postService iBzSysDiscuss_postDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_postfill_additionbegin"
            when
            then
            end

            //逻辑处理节点[创建的讨论数量]
            rule "rawsqlcall1"
            ruleflow-group "discuss_postfill_additionrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",discuss_postfill_additiondefault.get("id"));
    String strSql="select count(1) as discuss_num from discuss_post where create_man = (select create_man from discuss_post where id = #{et.param0})";
                        java.util.List<JSONObject> entities=iBzSysDiscuss_postDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    discuss_postfill_additiondefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(discuss_postfill_additiondefault);//更新fact中变量值
            end

            //逻辑处理节点[创建的回复数量]
            rule "rawsqlcall2"
            ruleflow-group "discuss_postfill_additionrawsqlcall2"
            when
            then
    Map param =new HashMap();
        param.put("param0",discuss_postfill_additiondefault.get("id"));
    String strSql="select count(1) as reply_num from discuss_reply  where create_man = (select create_man from discuss_post where id = #{et.param0})";
                        java.util.List<JSONObject> entities=iBzSysDiscuss_postDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    discuss_postfill_additiondefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(discuss_postfill_additiondefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_postfill_additionend1"
            when
            then
                        update(discuss_postfill_additiondefault);//更新fact中变量值
            end