package cn.ibizlab.plm.team.logic.discuss_postlogic.mob_get_topic_member;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_post discuss_postmob_get_topic_memberdefault;
                global cn.ibizlab.plm.core.team.domain.discuss_member discuss_postmob_get_topic_memberfilter;
                global java.util.Map discuss_postmob_get_topic_memberfor_obj;
                global cn.ibizlab.plm.core.team.domain.discuss_member discuss_postmob_get_topic_membermembers;
                global java.util.Map discuss_postmob_get_topic_memberuser;
                    global cn.ibizlab.plm.core.team.service.Idiscuss_memberService discuss_memberservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_postService iBzSysDiscuss_postDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_postmob_get_topic_memberbegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "discuss_postmob_get_topic_memberdebugparam1"
            when
            then
                        update(discuss_postmob_get_topic_memberdefault);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfilter);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfor_obj);//更新fact中变量值
                        update(discuss_postmob_get_topic_membermembers);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberuser);//更新fact中变量值
            end

            //逻辑处理节点[判断系统管理员身份]
            rule "rawsfcode3"
            ruleflow-group "discuss_postmob_get_topic_memberrawsfcode3"
            when
            then
                        update(discuss_postmob_get_topic_memberdefault);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfilter);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfor_obj);//更新fact中变量值
                        update(discuss_postmob_get_topic_membermembers);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberuser);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "discuss_postmob_get_topic_memberend2"
            when
            then
                        update(discuss_postmob_get_topic_memberdefault);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfilter);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfor_obj);//更新fact中变量值
                        update(discuss_postmob_get_topic_membermembers);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberuser);//更新fact中变量值
            end

            //逻辑处理节点[获取话题id并设置过滤参数]
            rule "prepareparam2"
            ruleflow-group "discuss_postmob_get_topic_memberprepareparam2"
            when
            then
                            discuss_postmob_get_topic_memberfilter.set("n_owner_id_eq",discuss_postmob_get_topic_memberdefault.get("topicid"));
                                discuss_postmob_get_topic_memberfilter.set("n_user_id_eq",curuser.getSessionParams().get("srfpersonid"));
                        update(discuss_postmob_get_topic_memberdefault);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfilter);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfor_obj);//更新fact中变量值
                        update(discuss_postmob_get_topic_membermembers);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberuser);//更新fact中变量值
            end

            //逻辑处理节点[查询当前用户是否为话题成员]
            rule "dedataset3"
            ruleflow-group "discuss_postmob_get_topic_memberdedataset3"
            when
            then
                        update(discuss_postmob_get_topic_memberdefault);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfilter);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfor_obj);//更新fact中变量值
                        update(discuss_postmob_get_topic_membermembers);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberuser);//更新fact中变量值
            end

            //逻辑处理节点[绑定用户数据到for_obj]
            rule "prepareparam5"
            ruleflow-group "discuss_postmob_get_topic_memberprepareparam5"
            when
            then
                            discuss_postmob_get_topic_memberfor_obj.set("",discuss_postmob_get_topic_membermembers.get("0"));
                        update(discuss_postmob_get_topic_memberdefault);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfilter);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfor_obj);//更新fact中变量值
                        update(discuss_postmob_get_topic_membermembers);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberuser);//更新fact中变量值
            end

            //逻辑处理节点[只读权限]
            rule "rawsfcode1"
            ruleflow-group "discuss_postmob_get_topic_memberrawsfcode1"
            when
            then
                        update(discuss_postmob_get_topic_memberdefault);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfilter);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfor_obj);//更新fact中变量值
                        update(discuss_postmob_get_topic_membermembers);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberuser);//更新fact中变量值
            end

            //逻辑处理节点[非只读权限]
            rule "rawsfcode2"
            ruleflow-group "discuss_postmob_get_topic_memberrawsfcode2"
            when
            then
                        update(discuss_postmob_get_topic_memberdefault);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfilter);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfor_obj);//更新fact中变量值
                        update(discuss_postmob_get_topic_membermembers);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberuser);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end6"
            ruleflow-group "discuss_postmob_get_topic_memberend6"
            when
            then
                        update(discuss_postmob_get_topic_memberdefault);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfilter);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfor_obj);//更新fact中变量值
                        update(discuss_postmob_get_topic_membermembers);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberuser);//更新fact中变量值
            end

            //逻辑处理节点[只读权限]
            rule "rawsfcode4"
            ruleflow-group "discuss_postmob_get_topic_memberrawsfcode4"
            when
            then
                        update(discuss_postmob_get_topic_memberdefault);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfilter);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberfor_obj);//更新fact中变量值
                        update(discuss_postmob_get_topic_membermembers);//更新fact中变量值
                        update(discuss_postmob_get_topic_memberuser);//更新fact中变量值
            end