package cn.ibizlab.plm.team.logic.discuss_postlogic.open;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_post discuss_postopendefault;
                global cn.ibizlab.plm.core.team.domain.discuss_post discuss_postopenupdate_obj;
                    global cn.ibizlab.plm.core.team.service.Idiscuss_postService discuss_postservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_postService iBzSysDiscuss_postDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_postopenbegin"
            when
            then
            end

            //逻辑处理节点[设置为进行中状态]
            rule "prepareparam1"
            ruleflow-group "discuss_postopenprepareparam1"
            when
            then
                            discuss_postopenupdate_obj.set("id",discuss_postopendefault.get("id"));
                            discuss_postopenupdate_obj.set("status","1");
                        update(discuss_postopendefault);//更新fact中变量值
                        update(discuss_postopenupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[执行更新]
            rule "deaction1"
            ruleflow-group "discuss_postopendeaction1"
            when
            then
                        discuss_postservice.update(discuss_postopenupdate_obj);
                        update(discuss_postopendefault);//更新fact中变量值
                        update(discuss_postopenupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_postopenend1"
            when
            then
                        update(discuss_postopendefault);//更新fact中变量值
                        update(discuss_postopenupdate_obj);//更新fact中变量值
            end