package cn.ibizlab.plm.testmgmt.logic.review_contentlogic.add_review_content;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content review_contentadd_review_contentdefault;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content review_contentadd_review_contentfor_temp_obj;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content review_contentadd_review_contentforward_relation_obj;
                global cn.ibizlab.plm.core.base.domain.relation review_contentadd_review_contentreverse_relation_obj;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content review_contentadd_review_contentselectdata;
                    global cn.ibizlab.plm.core.testmgmt.service.Ireview_contentService review_contentservice;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.testmgmt.service.Ireview_contentService iBzSysReview_contentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "review_contentadd_review_contentbegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "review_contentadd_review_contentdebugparam1"
            when
            then
                        update(review_contentadd_review_contentdefault);//更新fact中变量值
                        update(review_contentadd_review_contentfor_temp_obj);//更新fact中变量值
                        update(review_contentadd_review_contentforward_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentreverse_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentselectdata);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "review_contentadd_review_contentbindparam1"
            when
            then
                        update(review_contentadd_review_contentdefault);//更新fact中变量值
                        update(review_contentadd_review_contentfor_temp_obj);//更新fact中变量值
                        update(review_contentadd_review_contentforward_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentreverse_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentselectdata);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "review_contentadd_review_contentloopsubcall1"
            when
            then
                        update(review_contentadd_review_contentdefault);//更新fact中变量值
                        update(review_contentadd_review_contentfor_temp_obj);//更新fact中变量值
                        update(review_contentadd_review_contentforward_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentreverse_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentselectdata);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "review_contentadd_review_contentrenewparam1"
            when
            then
                        update(review_contentadd_review_contentdefault);//更新fact中变量值
                        update(review_contentadd_review_contentfor_temp_obj);//更新fact中变量值
                        update(review_contentadd_review_contentforward_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentreverse_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentselectdata);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam2"
            ruleflow-group "review_contentadd_review_contentrenewparam2"
            when
            then
                        update(review_contentadd_review_contentdefault);//更新fact中变量值
                        update(review_contentadd_review_contentfor_temp_obj);//更新fact中变量值
                        update(review_contentadd_review_contentforward_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentreverse_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentselectdata);//更新fact中变量值
            end

            //逻辑处理节点[填充需要的属性值]
            rule "prepareparam1"
            ruleflow-group "review_contentadd_review_contentprepareparam1"
            when
            then
                            review_contentadd_review_contentforward_relation_obj.set("principalid",review_contentadd_review_contentdefault.get("id"));
                            review_contentadd_review_contentforward_relation_obj.set("changetype",review_contentadd_review_contentdefault.get("changetype"));
                            review_contentadd_review_contentforward_relation_obj.set("changeversion",review_contentadd_review_contentfor_temp_obj.get("changeversion"));
                            review_contentadd_review_contentreverse_relation_obj.set("principalid",review_contentadd_review_contentfor_temp_obj.get("id"));
                            review_contentadd_review_contentreverse_relation_obj.set("targetid",review_contentadd_review_contentdefault.get("id"));
                            review_contentadd_review_contentforward_relation_obj.set("principaltype","REVIEW");
                            review_contentadd_review_contentforward_relation_obj.set("targettype","TEST_CASE");
                            review_contentadd_review_contentreverse_relation_obj.set("principaltype","TEST_CASE");
                            review_contentadd_review_contentreverse_relation_obj.set("targettype","REVIEW");
                            review_contentadd_review_contentforward_relation_obj.set("targetid",review_contentadd_review_contentfor_temp_obj.get("id"));
                        update(review_contentadd_review_contentdefault);//更新fact中变量值
                        update(review_contentadd_review_contentfor_temp_obj);//更新fact中变量值
                        update(review_contentadd_review_contentforward_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentreverse_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentselectdata);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "review_contentadd_review_contentend1"
            when
            then
                        update(review_contentadd_review_contentdefault);//更新fact中变量值
                        update(review_contentadd_review_contentfor_temp_obj);//更新fact中变量值
                        update(review_contentadd_review_contentforward_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentreverse_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentselectdata);//更新fact中变量值
            end

            //逻辑处理节点[正向关联数据]
            rule "debugparam3"
            ruleflow-group "review_contentadd_review_contentdebugparam3"
            when
            then
                        update(review_contentadd_review_contentdefault);//更新fact中变量值
                        update(review_contentadd_review_contentfor_temp_obj);//更新fact中变量值
                        update(review_contentadd_review_contentforward_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentreverse_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentselectdata);//更新fact中变量值
            end

            //逻辑处理节点[生成正向关联数据]
            rule "deaction1"
            ruleflow-group "review_contentadd_review_contentdeaction1"
            when
            then
                        review_contentservice.save(review_contentadd_review_contentforward_relation_obj);
                        update(review_contentadd_review_contentdefault);//更新fact中变量值
                        update(review_contentadd_review_contentfor_temp_obj);//更新fact中变量值
                        update(review_contentadd_review_contentforward_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentreverse_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentselectdata);//更新fact中变量值
            end

            //逻辑处理节点[生成反向关联数据]
            rule "deaction2"
            ruleflow-group "review_contentadd_review_contentdeaction2"
            when
            then
                        relationservice.save(review_contentadd_review_contentreverse_relation_obj);
                        update(review_contentadd_review_contentdefault);//更新fact中变量值
                        update(review_contentadd_review_contentfor_temp_obj);//更新fact中变量值
                        update(review_contentadd_review_contentforward_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentreverse_relation_obj);//更新fact中变量值
                        update(review_contentadd_review_contentselectdata);//更新fact中变量值
            end