package cn.ibizlab.plm.testmgmt.logic.review_contentlogic.start_review;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content review_contentstart_reviewdefault;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage review_contentstart_reviewend_stage;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage review_contentstart_reviewfor_stage;
                global cn.ibizlab.plm.core.testmgmt.domain.review review_contentstart_reviewreview_detail;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage review_contentstart_reviewstage_arr;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage review_contentstart_reviewstage_list;
                    global cn.ibizlab.plm.core.testmgmt.service.IreviewService reviewservice;
        global cn.ibizlab.plm.core.testmgmt.service.Ireview_contentService iBzSysReview_contentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "review_contentstart_reviewbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "review_contentstart_reviewend1"
            when
            then
                        update(review_contentstart_reviewdefault);//更新fact中变量值
                        update(review_contentstart_reviewend_stage);//更新fact中变量值
                        update(review_contentstart_reviewfor_stage);//更新fact中变量值
                        update(review_contentstart_reviewreview_detail);//更新fact中变量值
                        update(review_contentstart_reviewstage_arr);//更新fact中变量值
                        update(review_contentstart_reviewstage_list);//更新fact中变量值
            end

            //逻辑处理节点[传入参数]
            rule "debugparam1"
            ruleflow-group "review_contentstart_reviewdebugparam1"
            when
            then
                        update(review_contentstart_reviewdefault);//更新fact中变量值
                        update(review_contentstart_reviewend_stage);//更新fact中变量值
                        update(review_contentstart_reviewfor_stage);//更新fact中变量值
                        update(review_contentstart_reviewreview_detail);//更新fact中变量值
                        update(review_contentstart_reviewstage_arr);//更新fact中变量值
                        update(review_contentstart_reviewstage_list);//更新fact中变量值
            end

            //逻辑处理节点[获取评审详情id]
            rule "prepareparam1"
            ruleflow-group "review_contentstart_reviewprepareparam1"
            when
            then
                            review_contentstart_reviewreview_detail.set("id",review_contentstart_reviewdefault.get("principalid"));
                        update(review_contentstart_reviewdefault);//更新fact中变量值
                        update(review_contentstart_reviewend_stage);//更新fact中变量值
                        update(review_contentstart_reviewfor_stage);//更新fact中变量值
                        update(review_contentstart_reviewreview_detail);//更新fact中变量值
                        update(review_contentstart_reviewstage_arr);//更新fact中变量值
                        update(review_contentstart_reviewstage_list);//更新fact中变量值
            end

            //逻辑处理节点[获取评审详情]
            rule "deaction1"
            ruleflow-group "review_contentstart_reviewdeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(reviewservice.get(review_contentstart_reviewreview_detail.getId()),review_contentstart_reviewreview_detail);
                        update(review_contentstart_reviewdefault);//更新fact中变量值
                        update(review_contentstart_reviewend_stage);//更新fact中变量值
                        update(review_contentstart_reviewfor_stage);//更新fact中变量值
                        update(review_contentstart_reviewreview_detail);//更新fact中变量值
                        update(review_contentstart_reviewstage_arr);//更新fact中变量值
                        update(review_contentstart_reviewstage_list);//更新fact中变量值
            end

            //逻辑处理节点[获取阶段信息]
            rule "prepareparam2"
            ruleflow-group "review_contentstart_reviewprepareparam2"
            when
            then
                            review_contentstart_reviewstage_list.set("",review_contentstart_reviewreview_detail.get("stage"));
                        update(review_contentstart_reviewdefault);//更新fact中变量值
                        update(review_contentstart_reviewend_stage);//更新fact中变量值
                        update(review_contentstart_reviewfor_stage);//更新fact中变量值
                        update(review_contentstart_reviewreview_detail);//更新fact中变量值
                        update(review_contentstart_reviewstage_arr);//更新fact中变量值
                        update(review_contentstart_reviewstage_list);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "review_contentstart_reviewloopsubcall1"
            when
            then
                        update(review_contentstart_reviewdefault);//更新fact中变量值
                        update(review_contentstart_reviewend_stage);//更新fact中变量值
                        update(review_contentstart_reviewfor_stage);//更新fact中变量值
                        update(review_contentstart_reviewreview_detail);//更新fact中变量值
                        update(review_contentstart_reviewstage_arr);//更新fact中变量值
                        update(review_contentstart_reviewstage_list);//更新fact中变量值
            end

            //逻辑处理节点[排序数组参数]
            rule "sortparam1"
            ruleflow-group "review_contentstart_reviewsortparam1"
            when
            then
                        update(review_contentstart_reviewdefault);//更新fact中变量值
                        update(review_contentstart_reviewend_stage);//更新fact中变量值
                        update(review_contentstart_reviewfor_stage);//更新fact中变量值
                        update(review_contentstart_reviewreview_detail);//更新fact中变量值
                        update(review_contentstart_reviewstage_arr);//更新fact中变量值
                        update(review_contentstart_reviewstage_list);//更新fact中变量值
            end

            //逻辑处理节点[绑定阶段数据]
            rule "prepareparam5"
            ruleflow-group "review_contentstart_reviewprepareparam5"
            when
            then
                            review_contentstart_reviewreview_detail.set("stage",review_contentstart_reviewstage_arr.get(""));
                        update(review_contentstart_reviewdefault);//更新fact中变量值
                        update(review_contentstart_reviewend_stage);//更新fact中变量值
                        update(review_contentstart_reviewfor_stage);//更新fact中变量值
                        update(review_contentstart_reviewreview_detail);//更新fact中变量值
                        update(review_contentstart_reviewstage_arr);//更新fact中变量值
                        update(review_contentstart_reviewstage_list);//更新fact中变量值
            end

            //逻辑处理节点[最后评审详情]
            rule "debugparam3"
            ruleflow-group "review_contentstart_reviewdebugparam3"
            when
            then
                        update(review_contentstart_reviewdefault);//更新fact中变量值
                        update(review_contentstart_reviewend_stage);//更新fact中变量值
                        update(review_contentstart_reviewfor_stage);//更新fact中变量值
                        update(review_contentstart_reviewreview_detail);//更新fact中变量值
                        update(review_contentstart_reviewstage_arr);//更新fact中变量值
                        update(review_contentstart_reviewstage_list);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction2"
            ruleflow-group "review_contentstart_reviewdeaction2"
            when
            then
                        reviewservice.save(review_contentstart_reviewreview_detail);
                        update(review_contentstart_reviewdefault);//更新fact中变量值
                        update(review_contentstart_reviewend_stage);//更新fact中变量值
                        update(review_contentstart_reviewfor_stage);//更新fact中变量值
                        update(review_contentstart_reviewreview_detail);//更新fact中变量值
                        update(review_contentstart_reviewstage_arr);//更新fact中变量值
                        update(review_contentstart_reviewstage_list);//更新fact中变量值
            end

            //逻辑处理节点[当前阶段数据]
            rule "debugparam2"
            ruleflow-group "review_contentstart_reviewdebugparam2"
            when
            then
                        update(review_contentstart_reviewdefault);//更新fact中变量值
                        update(review_contentstart_reviewend_stage);//更新fact中变量值
                        update(review_contentstart_reviewfor_stage);//更新fact中变量值
                        update(review_contentstart_reviewreview_detail);//更新fact中变量值
                        update(review_contentstart_reviewstage_arr);//更新fact中变量值
                        update(review_contentstart_reviewstage_list);//更新fact中变量值
            end

            //逻辑处理节点[设置阶段完成]
            rule "prepareparam3"
            ruleflow-group "review_contentstart_reviewprepareparam3"
            when
            then
                            review_contentstart_reviewfor_stage.set("stagestate","20");
                        update(review_contentstart_reviewdefault);//更新fact中变量值
                        update(review_contentstart_reviewend_stage);//更新fact中变量值
                        update(review_contentstart_reviewfor_stage);//更新fact中变量值
                        update(review_contentstart_reviewreview_detail);//更新fact中变量值
                        update(review_contentstart_reviewstage_arr);//更新fact中变量值
                        update(review_contentstart_reviewstage_list);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam4"
            ruleflow-group "review_contentstart_reviewprepareparam4"
            when
            then
                            review_contentstart_reviewstage_arr.set("",review_contentstart_reviewfor_stage.get(""));
                        update(review_contentstart_reviewdefault);//更新fact中变量值
                        update(review_contentstart_reviewend_stage);//更新fact中变量值
                        update(review_contentstart_reviewfor_stage);//更新fact中变量值
                        update(review_contentstart_reviewreview_detail);//更新fact中变量值
                        update(review_contentstart_reviewstage_arr);//更新fact中变量值
                        update(review_contentstart_reviewstage_list);//更新fact中变量值
            end