package cn.ibizlab.plm.prodmgmt.logic.customerlogic.add_categories;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.customer customeradd_categoriesdefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.customer customeradd_categoriesfor_temp_obj;
                global cn.ibizlab.plm.core.prodmgmt.domain.customer customeradd_categoriessrfactionparam;
                    global cn.ibizlab.plm.core.prodmgmt.service.IcustomerService customerservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IcustomerService iBzSysCustomerDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "customeradd_categoriesbegin"
            when
            then
            end

            //逻辑处理节点[获取选择类别信息参数]
            rule "bindparam1"
            ruleflow-group "customeradd_categoriesbindparam1"
            when
            then
                        update(customeradd_categoriesdefault);//更新fact中变量值
                        update(customeradd_categoriesfor_temp_obj);//更新fact中变量值
                        update(customeradd_categoriessrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[设置类别路径]
            rule "prepareparam2"
            ruleflow-group "customeradd_categoriesprepareparam2"
            when
            then
                            customeradd_categoriesdefault.set("categories",customeradd_categoriesfor_temp_obj.get("categories"));
                        update(customeradd_categoriesdefault);//更新fact中变量值
                        update(customeradd_categoriesfor_temp_obj);//更新fact中变量值
                        update(customeradd_categoriessrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[变更客户属性]
            rule "deaction1"
            ruleflow-group "customeradd_categoriesdeaction1"
            when
            then
                        customerservice.update(customeradd_categoriesdefault);
                        update(customeradd_categoriesdefault);//更新fact中变量值
                        update(customeradd_categoriesfor_temp_obj);//更新fact中变量值
                        update(customeradd_categoriessrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "customeradd_categoriesloopsubcall1"
            when
            then
                        update(customeradd_categoriesdefault);//更新fact中变量值
                        update(customeradd_categoriesfor_temp_obj);//更新fact中变量值
                        update(customeradd_categoriessrfactionparam);//更新fact中变量值
            end