package cn.ibizlab.plm.prodmgmt.logic.customerlogic.add_categorys;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.Customer customeradd_categorysdefault;
                global java.util.Map customeradd_categorysid;
                global java.util.Map customeradd_categorysids;
                global cn.ibizlab.plm.core.prodmgmt.domain.Customer customeradd_categorystemp_obj;
                    global cn.ibizlab.plm.core.prodmgmt.service.ICustomerService customerservice;
        global cn.ibizlab.plm.core.prodmgmt.service.ICustomerService iBzSysCustomerDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "customeradd_categorysbegin"
            when
            then
            end

            //逻辑处理节点[拆分选中主键]
            rule "rawsfcode1"
            ruleflow-group "customeradd_categorysrawsfcode1"
            when
            then
                        update(customeradd_categorysdefault);//更新fact中变量值
                        update(customeradd_categorysid);//更新fact中变量值
                        update(customeradd_categorysids);//更新fact中变量值
                        update(customeradd_categorystemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "customeradd_categorysloopsubcall1"
            when
            then
                        update(customeradd_categorysdefault);//更新fact中变量值
                        update(customeradd_categorysid);//更新fact中变量值
                        update(customeradd_categorysids);//更新fact中变量值
                        update(customeradd_categorystemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "customeradd_categorysrenewparam1"
            when
            then
                        update(customeradd_categorysdefault);//更新fact中变量值
                        update(customeradd_categorysid);//更新fact中变量值
                        update(customeradd_categorysids);//更新fact中变量值
                        update(customeradd_categorystemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction2"
            ruleflow-group "customeradd_categorysdeaction2"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(customerservice.get(customeradd_categorysid.getId()),customeradd_categorysid);
                        update(customeradd_categorysdefault);//更新fact中变量值
                        update(customeradd_categorysid);//更新fact中变量值
                        update(customeradd_categorysids);//更新fact中变量值
                        update(customeradd_categorystemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "customeradd_categorysprepareparam1"
            when
            then
                            customeradd_categorystemp_obj.set("categorys",customeradd_categorysdefault.get("categorys"));
                        update(customeradd_categorysdefault);//更新fact中变量值
                        update(customeradd_categorysid);//更新fact中变量值
                        update(customeradd_categorysids);//更新fact中变量值
                        update(customeradd_categorystemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[update]
            rule "deaction1"
            ruleflow-group "customeradd_categorysdeaction1"
            when
            then
                        customerservice.update(customeradd_categorystemp_obj);
                        update(customeradd_categorysdefault);//更新fact中变量值
                        update(customeradd_categorysid);//更新fact中变量值
                        update(customeradd_categorysids);//更新fact中变量值
                        update(customeradd_categorystemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "customeradd_categorysend1"
            when
            then
                        update(customeradd_categorysdefault);//更新fact中变量值
                        update(customeradd_categorysid);//更新fact中变量值
                        update(customeradd_categorysids);//更新fact中变量值
                        update(customeradd_categorystemp_obj);//更新fact中变量值
            end