package cn.ibizlab.plm.prodmgmt.logic.customerlogic.customer_choose_ticket;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.customer customercustomer_choose_ticketdefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket customercustomer_choose_ticketfor_ticket;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket customercustomer_choose_ticketsrfactionparam;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket customercustomer_choose_ticketupdate_obj;
                    global cn.ibizlab.plm.core.prodmgmt.service.IticketService ticketservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IcustomerService iBzSysCustomerDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "customercustomer_choose_ticketbegin"
            when
            then
            end

            //逻辑处理节点[获取选中工单数据]
            rule "prepareparam1"
            ruleflow-group "customercustomer_choose_ticketprepareparam1"
            when
            then
                            customercustomer_choose_ticketsrfactionparam.set("",customercustomer_choose_ticketdefault.get("srfactionparam"));
                        update(customercustomer_choose_ticketdefault);//更新fact中变量值
                        update(customercustomer_choose_ticketfor_ticket);//更新fact中变量值
                        update(customercustomer_choose_ticketsrfactionparam);//更新fact中变量值
                        update(customercustomer_choose_ticketupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "customercustomer_choose_ticketloopsubcall1"
            when
            then
                        update(customercustomer_choose_ticketdefault);//更新fact中变量值
                        update(customercustomer_choose_ticketfor_ticket);//更新fact中变量值
                        update(customercustomer_choose_ticketsrfactionparam);//更新fact中变量值
                        update(customercustomer_choose_ticketupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[重新建立工单更新参数]
            rule "renewparam1"
            ruleflow-group "customercustomer_choose_ticketrenewparam1"
            when
            then
                        update(customercustomer_choose_ticketdefault);//更新fact中变量值
                        update(customercustomer_choose_ticketfor_ticket);//更新fact中变量值
                        update(customercustomer_choose_ticketsrfactionparam);//更新fact中变量值
                        update(customercustomer_choose_ticketupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[填充工单更新属性]
            rule "prepareparam2"
            ruleflow-group "customercustomer_choose_ticketprepareparam2"
            when
            then
                            customercustomer_choose_ticketupdate_obj.set("id",customercustomer_choose_ticketfor_ticket.get("owner_id"));
                            customercustomer_choose_ticketupdate_obj.set("customerid",customercustomer_choose_ticketdefault.get("customer_id"));
                        update(customercustomer_choose_ticketdefault);//更新fact中变量值
                        update(customercustomer_choose_ticketfor_ticket);//更新fact中变量值
                        update(customercustomer_choose_ticketsrfactionparam);//更新fact中变量值
                        update(customercustomer_choose_ticketupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[更新工单信息]
            rule "deaction1"
            ruleflow-group "customercustomer_choose_ticketdeaction1"
            when
            then
                        ticketservice.update(customercustomer_choose_ticketupdate_obj);
                        update(customercustomer_choose_ticketdefault);//更新fact中变量值
                        update(customercustomer_choose_ticketfor_ticket);//更新fact中变量值
                        update(customercustomer_choose_ticketsrfactionparam);//更新fact中变量值
                        update(customercustomer_choose_ticketupdate_obj);//更新fact中变量值
            end