package cn.ibizlab.plm.prodmgmt.logic.customerlogic.del_relation;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.Customer customerdel_relationdefault;
                global cn.ibizlab.plm.core.base.domain.Relation customerdel_relationrelationobj;
                global cn.ibizlab.plm.core.base.domain.Relation customerdel_relationrelationobj2;
                    global cn.ibizlab.plm.core.base.service.IRelationService relationservice;
        global cn.ibizlab.plm.core.prodmgmt.service.ICustomerService iBzSysCustomerDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "customerdel_relationbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "customerdel_relationprepareparam1"
            when
            then
                            customerdel_relationrelationobj.set("principalid",customerdel_relationdefault.get("principal_id"));
                            customerdel_relationrelationobj2.set("targetid",customerdel_relationdefault.get("principal_id"));
                            customerdel_relationrelationobj2.set("principalid",customerdel_relationdefault.get("id"));
                            customerdel_relationrelationobj.set("targetid",customerdel_relationdefault.get("id"));
                        update(customerdel_relationdefault);//更新fact中变量值
                        update(customerdel_relationrelationobj);//更新fact中变量值
                        update(customerdel_relationrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[拼接关联对象的主键]
            rule "rawsfcode1"
            ruleflow-group "customerdel_relationrawsfcode1"
            when
            then
                        update(customerdel_relationdefault);//更新fact中变量值
                        update(customerdel_relationrelationobj);//更新fact中变量值
                        update(customerdel_relationrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[删除正向关联]
            rule "deaction2"
            ruleflow-group "customerdel_relationdeaction2"
            when
            then
                        relationservice.remove(customerdel_relationrelationobj.getId());
                        update(customerdel_relationdefault);//更新fact中变量值
                        update(customerdel_relationrelationobj);//更新fact中变量值
                        update(customerdel_relationrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[删除反向关联]
            rule "deaction3"
            ruleflow-group "customerdel_relationdeaction3"
            when
            then
                        relationservice.remove(customerdel_relationrelationobj2.getId());
                        update(customerdel_relationdefault);//更新fact中变量值
                        update(customerdel_relationrelationobj);//更新fact中变量值
                        update(customerdel_relationrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "customerdel_relationend1"
            when
            then
                        update(customerdel_relationdefault);//更新fact中变量值
                        update(customerdel_relationrelationobj);//更新fact中变量值
                        update(customerdel_relationrelationobj2);//更新fact中变量值
            end