package cn.ibizlab.plm.prodmgmt.logic.customerlogic.nothing;
        global cn.ibizlab.plm.core.prodmgmt.service.ICustomerService iBzSysCustomerDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin1"
            ruleflow-group "customernothingbegin1"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "customernothingend1"
            when
            then
            end