package cn.ibizlab.plm.prodmgmt.logic.customerlogic.notify_by_id;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.Customer customernotify_by_iddefault;
                    global cn.ibizlab.plm.core.prodmgmt.service.ICustomerService customerservice;
        global cn.ibizlab.plm.core.prodmgmt.service.ICustomerService iBzSysCustomerDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "customernotify_by_idbegin"
            when
            then
            end

            //逻辑处理节点[获取客户信息]
            rule "deaction1"
            ruleflow-group "customernotify_by_iddeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(customerservice.get(customernotify_by_iddefault.getId()),customernotify_by_iddefault);
                        update(customernotify_by_iddefault);//更新fact中变量值
            end

            //逻辑处理节点[获取当前操作人]
            rule "prepareparam1"
            ruleflow-group "customernotify_by_idprepareparam1"
            when
            then
                                customernotify_by_iddefault.set("updateman",curuser.getSessionParams().get("srfpersonid"));
                        update(customernotify_by_iddefault);//更新fact中变量值
            end

            //逻辑处理节点[获取操作时间]
            rule "rawsfcode1"
            ruleflow-group "customernotify_by_idrawsfcode1"
            when
            then
                        update(customernotify_by_iddefault);//更新fact中变量值
            end

            //逻辑处理节点[实体通知]
            rule "denotify1"
            ruleflow-group "customernotify_by_iddenotify1"
            when
            then
                        update(customernotify_by_iddefault);//更新fact中变量值
            end