package cn.ibizlab.plm.prodmgmt.logic.customerlogic.others_relation_idea;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.Customer customerothers_relation_ideadefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.Customer customerothers_relation_ideafor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.Relation customerothers_relation_idearelationobj;
                global cn.ibizlab.plm.core.base.domain.Relation customerothers_relation_idearelationobj2;
                global cn.ibizlab.plm.core.prodmgmt.domain.Customer customerothers_relation_ideaselectdata;
                    global cn.ibizlab.plm.core.base.service.IRelationService relationservice;
        global cn.ibizlab.plm.core.prodmgmt.service.ICustomerService iBzSysCustomerDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "customerothers_relation_ideabegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "customerothers_relation_ideabindparam1"
            when
            then
                        update(customerothers_relation_ideadefault);//更新fact中变量值
                        update(customerothers_relation_ideafor_temp_obj);//更新fact中变量值
                        update(customerothers_relation_idearelationobj);//更新fact中变量值
                        update(customerothers_relation_idearelationobj2);//更新fact中变量值
                        update(customerothers_relation_ideaselectdata);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "customerothers_relation_idealoopsubcall1"
            when
            then
                        update(customerothers_relation_ideadefault);//更新fact中变量值
                        update(customerothers_relation_ideafor_temp_obj);//更新fact中变量值
                        update(customerothers_relation_idearelationobj);//更新fact中变量值
                        update(customerothers_relation_idearelationobj2);//更新fact中变量值
                        update(customerothers_relation_ideaselectdata);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "customerothers_relation_idearenewparam1"
            when
            then
                        update(customerothers_relation_ideadefault);//更新fact中变量值
                        update(customerothers_relation_ideafor_temp_obj);//更新fact中变量值
                        update(customerothers_relation_idearelationobj);//更新fact中变量值
                        update(customerothers_relation_idearelationobj2);//更新fact中变量值
                        update(customerothers_relation_ideaselectdata);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam2"
            ruleflow-group "customerothers_relation_idearenewparam2"
            when
            then
                        update(customerothers_relation_ideadefault);//更新fact中变量值
                        update(customerothers_relation_ideafor_temp_obj);//更新fact中变量值
                        update(customerothers_relation_idearelationobj);//更新fact中变量值
                        update(customerothers_relation_idearelationobj2);//更新fact中变量值
                        update(customerothers_relation_ideaselectdata);//更新fact中变量值
            end

            //逻辑处理节点[填充需要的属性值]
            rule "prepareparam1"
            ruleflow-group "customerothers_relation_ideaprepareparam1"
            when
            then
                            customerothers_relation_idearelationobj.set("principalid",customerothers_relation_ideadefault.get("principal_id"));
                            customerothers_relation_idearelationobj2.set("principalid",customerothers_relation_ideafor_temp_obj.get("id"));
                            customerothers_relation_idearelationobj2.set("targetid",customerothers_relation_ideadefault.get("principal_id"));
                            customerothers_relation_idearelationobj2.set("principaltype",customerothers_relation_ideadefault.get("target_type"));
                            customerothers_relation_idearelationobj2.set("targettype",customerothers_relation_ideadefault.get("principal_type"));
                            customerothers_relation_idearelationobj.set("principaltype",customerothers_relation_ideadefault.get("principal_type"));
                            customerothers_relation_idearelationobj.set("targettype",customerothers_relation_ideadefault.get("target_type"));
                            customerothers_relation_idearelationobj.set("targetid",customerothers_relation_ideafor_temp_obj.get("id"));
                        update(customerothers_relation_ideadefault);//更新fact中变量值
                        update(customerothers_relation_ideafor_temp_obj);//更新fact中变量值
                        update(customerothers_relation_idearelationobj);//更新fact中变量值
                        update(customerothers_relation_idearelationobj2);//更新fact中变量值
                        update(customerothers_relation_ideaselectdata);//更新fact中变量值
            end

            //逻辑处理节点[拼接关系对象的主键（正反）]
            rule "rawsfcode2"
            ruleflow-group "customerothers_relation_idearawsfcode2"
            when
            then
                        update(customerothers_relation_ideadefault);//更新fact中变量值
                        update(customerothers_relation_ideafor_temp_obj);//更新fact中变量值
                        update(customerothers_relation_idearelationobj);//更新fact中变量值
                        update(customerothers_relation_idearelationobj2);//更新fact中变量值
                        update(customerothers_relation_ideaselectdata);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "customerothers_relation_ideaend1"
            when
            then
                        update(customerothers_relation_ideadefault);//更新fact中变量值
                        update(customerothers_relation_ideafor_temp_obj);//更新fact中变量值
                        update(customerothers_relation_idearelationobj);//更新fact中变量值
                        update(customerothers_relation_idearelationobj2);//更新fact中变量值
                        update(customerothers_relation_ideaselectdata);//更新fact中变量值
            end

            //逻辑处理节点[生成正向关联数据]
            rule "deaction1"
            ruleflow-group "customerothers_relation_ideadeaction1"
            when
            then
                        relationservice.create(customerothers_relation_idearelationobj);
                        update(customerothers_relation_ideadefault);//更新fact中变量值
                        update(customerothers_relation_ideafor_temp_obj);//更新fact中变量值
                        update(customerothers_relation_idearelationobj);//更新fact中变量值
                        update(customerothers_relation_idearelationobj2);//更新fact中变量值
                        update(customerothers_relation_ideaselectdata);//更新fact中变量值
            end

            //逻辑处理节点[生成反向关联数据]
            rule "deaction2"
            ruleflow-group "customerothers_relation_ideadeaction2"
            when
            then
                        relationservice.create(customerothers_relation_idearelationobj2);
                        update(customerothers_relation_ideadefault);//更新fact中变量值
                        update(customerothers_relation_ideafor_temp_obj);//更新fact中变量值
                        update(customerothers_relation_idearelationobj);//更新fact中变量值
                        update(customerothers_relation_idearelationobj2);//更新fact中变量值
                        update(customerothers_relation_ideaselectdata);//更新fact中变量值
            end