package cn.ibizlab.plm.prodmgmt.logic.customerlogic.product_customer_re_counters;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.Customer customerproduct_customer_re_countersdefault;
        global cn.ibizlab.plm.core.prodmgmt.service.ICustomerService iBzSysCustomerDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "customerproduct_customer_re_countersbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "customerproduct_customer_re_countersend1"
            when
            then
                        update(customerproduct_customer_re_countersdefault);//更新fact中变量值
            end

            //逻辑处理节点[客户关联工单]
            rule "rawsqlcall1"
            ruleflow-group "customerproduct_customer_re_countersrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",customerproduct_customer_re_countersdefault.get("id"));
    String strSql="SELECT 	COUNT( t2.id ) as customer_re_ticket FROM 	customer t, 	ticket t2  WHERE 	t.id = #{et.param0}  	AND t.id = t2.CUSTOMER_ID  	AND t2.IS_DELETED = 0  	AND t2.IS_ARCHIVED = 0";
                        java.util.List<JSONObject> entities=iBzSysCustomerDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    customerproduct_customer_re_countersdefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(customerproduct_customer_re_countersdefault);//更新fact中变量值
            end