package cn.ibizlab.plm.base.logic.memberlogic.choose_resource_member;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.member memberchoose_resource_memberdefault;
                global cn.ibizlab.plm.core.base.domain.member memberchoose_resource_memberfor_member;
                global cn.ibizlab.plm.core.base.domain.user memberchoose_resource_memberfor_user_obj;
                global cn.ibizlab.plm.core.base.domain.member memberchoose_resource_membergroup_page;
                global cn.ibizlab.plm.core.base.domain.user memberchoose_resource_memberuser_filter;
                global cn.ibizlab.plm.core.base.domain.user memberchoose_resource_memberuser_page;
                    global cn.ibizlab.plm.core.base.service.ImemberService memberservice;
                    global cn.ibizlab.plm.core.base.service.IuserService userservice;
        global cn.ibizlab.plm.core.base.service.ImemberService iBzSysMemberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "memberchoose_resource_memberbegin"
            when
            then
            end

            //逻辑处理节点[分页参数]
            rule "rawsfcode2"
            ruleflow-group "memberchoose_resource_memberrawsfcode2"
            when
            then
                        update(memberchoose_resource_memberdefault);//更新fact中变量值
                        update(memberchoose_resource_memberfor_member);//更新fact中变量值
                        update(memberchoose_resource_memberfor_user_obj);//更新fact中变量值
                        update(memberchoose_resource_membergroup_page);//更新fact中变量值
                        update(memberchoose_resource_memberuser_filter);//更新fact中变量值
                        update(memberchoose_resource_memberuser_page);//更新fact中变量值
            end

            //逻辑处理节点[准备团队成员过滤器参数]
            rule "prepareparam3"
            ruleflow-group "memberchoose_resource_memberprepareparam3"
            when
            then
                            memberchoose_resource_memberdefault.set("n_owner_id_eq",memberchoose_resource_memberdefault.get("user_group"));
                            memberchoose_resource_memberuser_filter.set("size","100");
                            memberchoose_resource_memberdefault.set("n_owner_type_eq","GROUP");
                        update(memberchoose_resource_memberdefault);//更新fact中变量值
                        update(memberchoose_resource_memberfor_member);//更新fact中变量值
                        update(memberchoose_resource_memberfor_user_obj);//更新fact中变量值
                        update(memberchoose_resource_membergroup_page);//更新fact中变量值
                        update(memberchoose_resource_memberuser_filter);//更新fact中变量值
                        update(memberchoose_resource_memberuser_page);//更新fact中变量值
            end

            //逻辑处理节点[准备部门成员过滤器参数]
            rule "prepareparam2"
            ruleflow-group "memberchoose_resource_memberprepareparam2"
            when
            then
                            memberchoose_resource_memberuser_filter.set("n_department_id_eq",memberchoose_resource_memberdefault.get("n_department_id_eq"));
                            memberchoose_resource_memberuser_filter.set("n_status_eq","1");
                            memberchoose_resource_memberuser_filter.set("n_display_name_like",memberchoose_resource_memberdefault.get("n_name_like"));
                        update(memberchoose_resource_memberdefault);//更新fact中变量值
                        update(memberchoose_resource_memberfor_member);//更新fact中变量值
                        update(memberchoose_resource_memberfor_user_obj);//更新fact中变量值
                        update(memberchoose_resource_membergroup_page);//更新fact中变量值
                        update(memberchoose_resource_memberuser_filter);//更新fact中变量值
                        update(memberchoose_resource_memberuser_page);//更新fact中变量值
            end

            //逻辑处理节点[获取团队成员]
            rule "dedataset3"
            ruleflow-group "memberchoose_resource_memberdedataset3"
            when
            then
                        update(memberchoose_resource_memberdefault);//更新fact中变量值
                        update(memberchoose_resource_memberfor_member);//更新fact中变量值
                        update(memberchoose_resource_memberfor_user_obj);//更新fact中变量值
                        update(memberchoose_resource_membergroup_page);//更新fact中变量值
                        update(memberchoose_resource_memberuser_filter);//更新fact中变量值
                        update(memberchoose_resource_memberuser_page);//更新fact中变量值
            end

            //逻辑处理节点[获取部门成员]
            rule "dedataset2"
            ruleflow-group "memberchoose_resource_memberdedataset2"
            when
            then
                        update(memberchoose_resource_memberdefault);//更新fact中变量值
                        update(memberchoose_resource_memberfor_member);//更新fact中变量值
                        update(memberchoose_resource_memberfor_user_obj);//更新fact中变量值
                        update(memberchoose_resource_membergroup_page);//更新fact中变量值
                        update(memberchoose_resource_memberuser_filter);//更新fact中变量值
                        update(memberchoose_resource_memberuser_page);//更新fact中变量值
            end

            //逻辑处理节点[根据团队成员的用户标识查询user]
            rule "rawsfcode3"
            ruleflow-group "memberchoose_resource_memberrawsfcode3"
            when
            then
                        update(memberchoose_resource_memberdefault);//更新fact中变量值
                        update(memberchoose_resource_memberfor_member);//更新fact中变量值
                        update(memberchoose_resource_memberfor_user_obj);//更新fact中变量值
                        update(memberchoose_resource_membergroup_page);//更新fact中变量值
                        update(memberchoose_resource_memberuser_filter);//更新fact中变量值
                        update(memberchoose_resource_memberuser_page);//更新fact中变量值
            end

            //逻辑处理节点[获取部门成员]
            rule "dedataset4"
            ruleflow-group "memberchoose_resource_memberdedataset4"
            when
            then
                        update(memberchoose_resource_memberdefault);//更新fact中变量值
                        update(memberchoose_resource_memberfor_member);//更新fact中变量值
                        update(memberchoose_resource_memberfor_user_obj);//更新fact中变量值
                        update(memberchoose_resource_membergroup_page);//更新fact中变量值
                        update(memberchoose_resource_memberuser_filter);//更新fact中变量值
                        update(memberchoose_resource_memberuser_page);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "memberchoose_resource_memberloopsubcall1"
            when
            then
                        update(memberchoose_resource_memberdefault);//更新fact中变量值
                        update(memberchoose_resource_memberfor_member);//更新fact中变量值
                        update(memberchoose_resource_memberfor_user_obj);//更新fact中变量值
                        update(memberchoose_resource_membergroup_page);//更新fact中变量值
                        update(memberchoose_resource_memberuser_filter);//更新fact中变量值
                        update(memberchoose_resource_memberuser_page);//更新fact中变量值
            end

            //逻辑处理节点[填充用户标识]
            rule "prepareparam4"
            ruleflow-group "memberchoose_resource_memberprepareparam4"
            when
            then
                            memberchoose_resource_memberfor_user_obj.set("name",memberchoose_resource_memberfor_user_obj.get("displayname"));
                            memberchoose_resource_memberfor_user_obj.set("userid",memberchoose_resource_memberfor_user_obj.get("id"));
                        update(memberchoose_resource_memberdefault);//更新fact中变量值
                        update(memberchoose_resource_memberfor_member);//更新fact中变量值
                        update(memberchoose_resource_memberfor_user_obj);//更新fact中变量值
                        update(memberchoose_resource_membergroup_page);//更新fact中变量值
                        update(memberchoose_resource_memberuser_filter);//更新fact中变量值
                        update(memberchoose_resource_memberuser_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "memberchoose_resource_memberend2"
            when
            then
                        update(memberchoose_resource_memberdefault);//更新fact中变量值
                        update(memberchoose_resource_memberfor_member);//更新fact中变量值
                        update(memberchoose_resource_memberfor_user_obj);//更新fact中变量值
                        update(memberchoose_resource_membergroup_page);//更新fact中变量值
                        update(memberchoose_resource_memberuser_filter);//更新fact中变量值
                        update(memberchoose_resource_memberuser_page);//更新fact中变量值
            end