package cn.ibizlab.plm.base.logic.memberlogic.cur_portfolio_resource;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.member membercur_portfolio_resourcedefault;
                global cn.ibizlab.plm.core.base.domain.addon_resource membercur_portfolio_resourceaddon_resource;
                global cn.ibizlab.plm.core.base.domain.addon_resource membercur_portfolio_resourceaddon_resource_filter;
                global cn.ibizlab.plm.core.base.domain.addon_resource membercur_portfolio_resourceaddon_resource_page;
                global cn.ibizlab.plm.core.base.domain.member membercur_portfolio_resourcemember_page;
                    global cn.ibizlab.plm.core.base.service.Iaddon_resourceService addon_resourceservice;
        global cn.ibizlab.plm.core.base.service.ImemberService iBzSysMemberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "membercur_portfolio_resourcebegin"
            when
            then
            end

            //逻辑处理节点[设置资源组件查询过滤器参数]
            rule "prepareparam1"
            ruleflow-group "membercur_portfolio_resourceprepareparam1"
            when
            then
                            membercur_portfolio_resourceaddon_resource_filter.set("n_owner_id_eq",membercur_portfolio_resourcedefault.get("portfolio_id"));
                            membercur_portfolio_resourceaddon_resource_filter.set("n_owner_type_eq","portfolio");
                            membercur_portfolio_resourceaddon_resource_filter.set("n_addon_type_eq","resource");
                        update(membercur_portfolio_resourcedefault);//更新fact中变量值
                        update(membercur_portfolio_resourceaddon_resource);//更新fact中变量值
                        update(membercur_portfolio_resourceaddon_resource_filter);//更新fact中变量值
                        update(membercur_portfolio_resourceaddon_resource_page);//更新fact中变量值
                        update(membercur_portfolio_resourcemember_page);//更新fact中变量值
            end

            //逻辑处理节点[获取当前项目集下的资源组件]
            rule "dedataset1"
            ruleflow-group "membercur_portfolio_resourcededataset1"
            when
            then
                        update(membercur_portfolio_resourcedefault);//更新fact中变量值
                        update(membercur_portfolio_resourceaddon_resource);//更新fact中变量值
                        update(membercur_portfolio_resourceaddon_resource_filter);//更新fact中变量值
                        update(membercur_portfolio_resourceaddon_resource_page);//更新fact中变量值
                        update(membercur_portfolio_resourcemember_page);//更新fact中变量值
            end

            //逻辑处理节点[绑定资源组件]
            rule "bindparam2"
            ruleflow-group "membercur_portfolio_resourcebindparam2"
            when
            then
                        update(membercur_portfolio_resourcedefault);//更新fact中变量值
                        update(membercur_portfolio_resourceaddon_resource);//更新fact中变量值
                        update(membercur_portfolio_resourceaddon_resource_filter);//更新fact中变量值
                        update(membercur_portfolio_resourceaddon_resource_page);//更新fact中变量值
                        update(membercur_portfolio_resourcemember_page);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "membercur_portfolio_resourcebindparam1"
            when
            then
                        update(membercur_portfolio_resourcedefault);//更新fact中变量值
                        update(membercur_portfolio_resourceaddon_resource);//更新fact中变量值
                        update(membercur_portfolio_resourceaddon_resource_filter);//更新fact中变量值
                        update(membercur_portfolio_resourceaddon_resource_page);//更新fact中变量值
                        update(membercur_portfolio_resourcemember_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "membercur_portfolio_resourceend1"
            when
            then
                        update(membercur_portfolio_resourcedefault);//更新fact中变量值
                        update(membercur_portfolio_resourceaddon_resource);//更新fact中变量值
                        update(membercur_portfolio_resourceaddon_resource_filter);//更新fact中变量值
                        update(membercur_portfolio_resourceaddon_resource_page);//更新fact中变量值
                        update(membercur_portfolio_resourcemember_page);//更新fact中变量值
            end