package cn.ibizlab.plm.base.logic.deliverablelogic.get_mob_delivery_detail;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.deliverable deliverableget_mob_delivery_detaildefault;
                global cn.ibizlab.plm.core.base.domain.deliverable deliverableget_mob_delivery_detaildelivery;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item deliverableget_mob_delivery_detailwork_item;
                    global cn.ibizlab.plm.core.base.service.IattachmentService attachmentservice;
                    global cn.ibizlab.plm.core.projmgmt.service.Iwork_itemService work_itemservice;
        global cn.ibizlab.plm.core.base.service.IdeliverableService iBzSysDeliverableDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "deliverableget_mob_delivery_detailbegin"
            when
            then
            end

            //逻辑处理节点[交付物default]
            rule "debugparam1"
            ruleflow-group "deliverableget_mob_delivery_detaildebugparam1"
            when
            then
                        update(deliverableget_mob_delivery_detaildefault);//更新fact中变量值
                        update(deliverableget_mob_delivery_detaildelivery);//更新fact中变量值
                        update(deliverableget_mob_delivery_detailwork_item);//更新fact中变量值
            end

            //逻辑处理节点[获取交付物信息]
            rule "deaction1"
            ruleflow-group "deliverableget_mob_delivery_detaildeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(attachmentservice.get(deliverableget_mob_delivery_detaildefault.getId()),deliverableget_mob_delivery_detaildefault);
                        update(deliverableget_mob_delivery_detaildefault);//更新fact中变量值
                        update(deliverableget_mob_delivery_detaildelivery);//更新fact中变量值
                        update(deliverableget_mob_delivery_detailwork_item);//更新fact中变量值
            end

            //逻辑处理节点[设置工作项信息]
            rule "prepareparam3"
            ruleflow-group "deliverableget_mob_delivery_detailprepareparam3"
            when
            then
                            deliverableget_mob_delivery_detailwork_item.set("id",deliverableget_mob_delivery_detaildefault.get("ownerid"));
                        update(deliverableget_mob_delivery_detaildefault);//更新fact中变量值
                        update(deliverableget_mob_delivery_detaildelivery);//更新fact中变量值
                        update(deliverableget_mob_delivery_detailwork_item);//更新fact中变量值
            end

            //逻辑处理节点[获取工作项信息]
            rule "deaction2"
            ruleflow-group "deliverableget_mob_delivery_detaildeaction2"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(work_itemservice.get(deliverableget_mob_delivery_detailwork_item.getId()),deliverableget_mob_delivery_detailwork_item);
                        update(deliverableget_mob_delivery_detaildefault);//更新fact中变量值
                        update(deliverableget_mob_delivery_detaildelivery);//更新fact中变量值
                        update(deliverableget_mob_delivery_detailwork_item);//更新fact中变量值
            end

            //逻辑处理节点[设置交付物工作项参数]
            rule "prepareparam2"
            ruleflow-group "deliverableget_mob_delivery_detailprepareparam2"
            when
            then
                            deliverableget_mob_delivery_detaildefault.set("workitemtitle",deliverableget_mob_delivery_detailwork_item.get("title"));
                            deliverableget_mob_delivery_detaildefault.set("workitemidentifier",deliverableget_mob_delivery_detailwork_item.get("identifier"));
                        update(deliverableget_mob_delivery_detaildefault);//更新fact中变量值
                        update(deliverableget_mob_delivery_detaildelivery);//更新fact中变量值
                        update(deliverableget_mob_delivery_detailwork_item);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "deliverableget_mob_delivery_detailend1"
            when
            then
                        update(deliverableget_mob_delivery_detaildefault);//更新fact中变量值
                        update(deliverableget_mob_delivery_detaildelivery);//更新fact中变量值
                        update(deliverableget_mob_delivery_detailwork_item);//更新fact中变量值
            end