package cn.ibizlab.plm.base.logic.search_attachmentlogic.cur_project;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.search_attachment search_attachmentcur_projectdefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.customer search_attachmentcur_projectcustomer;
                global cn.ibizlab.plm.core.base.domain.search_attachment search_attachmentcur_projectfor_temp_obj;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea search_attachmentcur_projectidea;
                global cn.ibizlab.plm.core.wiki.domain.article_page search_attachmentcur_projectpage;
                global cn.ibizlab.plm.core.base.domain.search_attachment search_attachmentcur_projectresult_page;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case search_attachmentcur_projecttest_case;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket search_attachmentcur_projectticket;
                global cn.ibizlab.plm.core.projmgmt.domain.work_item search_attachmentcur_projectwork_item;
                    global cn.ibizlab.plm.core.base.service.Isearch_attachmentService search_attachmentservice;
        global cn.ibizlab.plm.core.base.service.Isearch_attachmentService iBzSysSearch_attachmentDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "search_attachmentcur_projectbegin"
            when
            then
            end

            //逻辑处理节点[当前项目下的全部附件]
            rule "dedataset1"
            ruleflow-group "search_attachmentcur_projectdedataset1"
            when
            then
                        update(search_attachmentcur_projectdefault);//更新fact中变量值
                        update(search_attachmentcur_projectcustomer);//更新fact中变量值
                        update(search_attachmentcur_projectfor_temp_obj);//更新fact中变量值
                        update(search_attachmentcur_projectidea);//更新fact中变量值
                        update(search_attachmentcur_projectpage);//更新fact中变量值
                        update(search_attachmentcur_projectresult_page);//更新fact中变量值
                        update(search_attachmentcur_projecttest_case);//更新fact中变量值
                        update(search_attachmentcur_projectticket);//更新fact中变量值
                        update(search_attachmentcur_projectwork_item);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "search_attachmentcur_projectloopsubcall1"
            when
            then
                        update(search_attachmentcur_projectdefault);//更新fact中变量值
                        update(search_attachmentcur_projectcustomer);//更新fact中变量值
                        update(search_attachmentcur_projectfor_temp_obj);//更新fact中变量值
                        update(search_attachmentcur_projectidea);//更新fact中变量值
                        update(search_attachmentcur_projectpage);//更新fact中变量值
                        update(search_attachmentcur_projectresult_page);//更新fact中变量值
                        update(search_attachmentcur_projecttest_case);//更新fact中变量值
                        update(search_attachmentcur_projectticket);//更新fact中变量值
                        update(search_attachmentcur_projectwork_item);//更新fact中变量值
            end

            //逻辑处理节点[绑定工作项参数]
            rule "bindparam1"
            ruleflow-group "search_attachmentcur_projectbindparam1"
            when
            then
                        update(search_attachmentcur_projectdefault);//更新fact中变量值
                        update(search_attachmentcur_projectcustomer);//更新fact中变量值
                        update(search_attachmentcur_projectfor_temp_obj);//更新fact中变量值
                        update(search_attachmentcur_projectidea);//更新fact中变量值
                        update(search_attachmentcur_projectpage);//更新fact中变量值
                        update(search_attachmentcur_projectresult_page);//更新fact中变量值
                        update(search_attachmentcur_projecttest_case);//更新fact中变量值
                        update(search_attachmentcur_projectticket);//更新fact中变量值
                        update(search_attachmentcur_projectwork_item);//更新fact中变量值
            end

            //逻辑处理节点[填充工作项展示属性]
            rule "prepareparam1"
            ruleflow-group "search_attachmentcur_projectprepareparam1"
            when
            then
                            search_attachmentcur_projectfor_temp_obj.set("owneridentifier",search_attachmentcur_projectwork_item.get("identifier"));
                            search_attachmentcur_projectfor_temp_obj.set("ownerparentid",search_attachmentcur_projectwork_item.get("projectid"));
                            search_attachmentcur_projectfor_temp_obj.set("ownerparentname",search_attachmentcur_projectwork_item.get("projectname"));
                            search_attachmentcur_projectfor_temp_obj.set("ownertitle",search_attachmentcur_projectwork_item.get("title"));
                        update(search_attachmentcur_projectdefault);//更新fact中变量值
                        update(search_attachmentcur_projectcustomer);//更新fact中变量值
                        update(search_attachmentcur_projectfor_temp_obj);//更新fact中变量值
                        update(search_attachmentcur_projectidea);//更新fact中变量值
                        update(search_attachmentcur_projectpage);//更新fact中变量值
                        update(search_attachmentcur_projectresult_page);//更新fact中变量值
                        update(search_attachmentcur_projecttest_case);//更新fact中变量值
                        update(search_attachmentcur_projectticket);//更新fact中变量值
                        update(search_attachmentcur_projectwork_item);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "search_attachmentcur_projectend1"
            when
            then
                        update(search_attachmentcur_projectdefault);//更新fact中变量值
                        update(search_attachmentcur_projectcustomer);//更新fact中变量值
                        update(search_attachmentcur_projectfor_temp_obj);//更新fact中变量值
                        update(search_attachmentcur_projectidea);//更新fact中变量值
                        update(search_attachmentcur_projectpage);//更新fact中变量值
                        update(search_attachmentcur_projectresult_page);//更新fact中变量值
                        update(search_attachmentcur_projecttest_case);//更新fact中变量值
                        update(search_attachmentcur_projectticket);//更新fact中变量值
                        update(search_attachmentcur_projectwork_item);//更新fact中变量值
            end