package cn.ibizlab.plm.base.logic.workloadlogic.duration_updateform;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.Workload workloadduration_updateformdefault;
        global cn.ibizlab.plm.core.base.service.IWorkloadService iBzSysWorkloadDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "workloadduration_updateformbegin"
            when
            then
            end

            //逻辑处理节点[计算剩余工时和工时进度]
            rule "rawsfcode1"
            ruleflow-group "workloadduration_updateformrawsfcode1"
            when
            then
                        update(workloadduration_updateformdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "workloadduration_updateformend1"
            when
            then
                        update(workloadduration_updateformdefault);//更新fact中变量值
            end