package cn.ibizlab.plm.base.logic.workloadlogic.member_dimension;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.workload workloadmember_dimensiondefault;
                global cn.ibizlab.plm.core.base.domain.workload workloadmember_dimensionpage;
                    global cn.ibizlab.plm.core.base.service.IworkloadService workloadservice;
        global cn.ibizlab.plm.core.base.service.IworkloadService iBzSysWorkloadDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "workloadmember_dimensionbegin"
            when
            then
            end

            //逻辑处理节点[重置分页参数]
            rule "prepareparam1"
            ruleflow-group "workloadmember_dimensionprepareparam1"
            when
            then
                            workloadmember_dimensiondefault.set("size","10000");
                        update(workloadmember_dimensiondefault);//更新fact中变量值
                        update(workloadmember_dimensionpage);//更新fact中变量值
            end

            //逻辑处理节点[查询工时日历]
            rule "dedataset1"
            ruleflow-group "workloadmember_dimensiondedataset1"
            when
            then
                        update(workloadmember_dimensiondefault);//更新fact中变量值
                        update(workloadmember_dimensionpage);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "workloadmember_dimensionend1"
            when
            then
                        update(workloadmember_dimensiondefault);//更新fact中变量值
                        update(workloadmember_dimensionpage);//更新fact中变量值
            end