package cn.ibizlab.plm.base.logic.workloadlogic.test_case_dimension;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.Workload workloadtest_case_dimensiondefault;
                global cn.ibizlab.plm.core.base.domain.Workload workloadtest_case_dimensionpage;
                    global cn.ibizlab.plm.core.base.service.IWorkloadService workloadservice;
        global cn.ibizlab.plm.core.base.service.IWorkloadService iBzSysWorkloadDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "workloadtest_case_dimensionbegin"
            when
            then
            end

            //逻辑处理节点[重置分页参数]
            rule "prepareparam1"
            ruleflow-group "workloadtest_case_dimensionprepareparam1"
            when
            then
                            workloadtest_case_dimensiondefault.set("size","1000");
                        update(workloadtest_case_dimensiondefault);//更新fact中变量值
                        update(workloadtest_case_dimensionpage);//更新fact中变量值
            end

            //逻辑处理节点[查询我登记的测试用例工时]
            rule "dedataset1"
            ruleflow-group "workloadtest_case_dimensiondedataset1"
            when
            then
                        update(workloadtest_case_dimensiondefault);//更新fact中变量值
                        update(workloadtest_case_dimensionpage);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "workloadtest_case_dimensionend1"
            when
            then
                        update(workloadtest_case_dimensiondefault);//更新fact中变量值
                        update(workloadtest_case_dimensionpage);//更新fact中变量值
            end