package cn.ibizlab.plm.prodmgmt.logic.baseline_idealogic.shift_out_baseline;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.baseline_idea baseline_ideashift_out_baselinedefault;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.prodmgmt.service.Ibaseline_ideaService iBzSysBaseline_ideaDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "baseline_ideashift_out_baselinebegin"
            when
            then
            end

            //逻辑处理节点[删除基线-需求关联数据]
            rule "deaction1"
            ruleflow-group "baseline_ideashift_out_baselinedeaction1"
            when
            then
                        relationservice.remove(baseline_ideashift_out_baselinedefault.getId());
                        update(baseline_ideashift_out_baselinedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "baseline_ideashift_out_baselineend1"
            when
            then
                        update(baseline_ideashift_out_baselinedefault);//更新fact中变量值
            end