server {
  listen       80;
  server_name  localhost;

  location /plmmob/ {
    alias  /dist/;
    index  index.html index.htm;
  }

  location /api/ {
    proxy_pass http://gateway.ibizcloud.cn:20086/;
    proxy_set_header  Host              $host;
    proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Host  $host;
    proxy_set_header  X-Real-IP         $remote_addr;
  }

  error_page   500 502 503 504  /50x.html;

  location = /50x.html {
    root   html;
  }
}
