package cn.ibizlab.plm.base.logic.categorylogic.delete_child_category;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.Category categorydelete_child_categorydefault;
                global cn.ibizlab.plm.core.base.domain.Category categorydelete_child_categorycategory_page;
                global cn.ibizlab.plm.core.base.domain.Category categorydelete_child_categoryfilter;
                global cn.ibizlab.plm.core.base.domain.Category categorydelete_child_categoryfor_temp_obj;
                global java.util.Map categorydelete_child_categoryparent_category;
                global cn.ibizlab.plm.core.base.domain.Section categorydelete_child_categoryparent_section;
                    global cn.ibizlab.plm.core.base.service.ICategoryService categoryservice;
                    global cn.ibizlab.plm.core.base.service.ISectionService sectionservice;
        global cn.ibizlab.plm.core.base.service.ICategoryService iBzSysCategoryDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "categorydelete_child_categorybegin"
            when
            then
            end

            //逻辑处理节点[删除类别]
            rule "deaction2"
            ruleflow-group "categorydelete_child_categorydeaction2"
            when
            then
                        categoryservice.remove(categorydelete_child_categorydefault.getId());
                        update(categorydelete_child_categorydefault);//更新fact中变量值
                        update(categorydelete_child_categorycategory_page);//更新fact中变量值
                        update(categorydelete_child_categoryfilter);//更新fact中变量值
                        update(categorydelete_child_categoryfor_temp_obj);//更新fact中变量值
                        update(categorydelete_child_categoryparent_category);//更新fact中变量值
                        update(categorydelete_child_categoryparent_section);//更新fact中变量值
            end

            //逻辑处理节点[输出默认参数]
            rule "debugparam1"
            ruleflow-group "categorydelete_child_categorydebugparam1"
            when
            then
                        update(categorydelete_child_categorydefault);//更新fact中变量值
                        update(categorydelete_child_categorycategory_page);//更新fact中变量值
                        update(categorydelete_child_categoryfilter);//更新fact中变量值
                        update(categorydelete_child_categoryfor_temp_obj);//更新fact中变量值
                        update(categorydelete_child_categoryparent_category);//更新fact中变量值
                        update(categorydelete_child_categoryparent_section);//更新fact中变量值
            end

            //逻辑处理节点[设置过滤器参数]
            rule "prepareparam1"
            ruleflow-group "categorydelete_child_categoryprepareparam1"
            when
            then
                            categorydelete_child_categoryfilter.set("n_pid_eq",categorydelete_child_categorydefault.get("id"));
                        update(categorydelete_child_categorydefault);//更新fact中变量值
                        update(categorydelete_child_categorycategory_page);//更新fact中变量值
                        update(categorydelete_child_categoryfilter);//更新fact中变量值
                        update(categorydelete_child_categoryfor_temp_obj);//更新fact中变量值
                        update(categorydelete_child_categoryparent_category);//更新fact中变量值
                        update(categorydelete_child_categoryparent_section);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "categorydelete_child_categorydedataset1"
            when
            then
                        update(categorydelete_child_categorydefault);//更新fact中变量值
                        update(categorydelete_child_categorycategory_page);//更新fact中变量值
                        update(categorydelete_child_categoryfilter);//更新fact中变量值
                        update(categorydelete_child_categoryfor_temp_obj);//更新fact中变量值
                        update(categorydelete_child_categoryparent_category);//更新fact中变量值
                        update(categorydelete_child_categoryparent_section);//更新fact中变量值
            end

            //逻辑处理节点[结束前的默认参数]
            rule "debugparam2"
            ruleflow-group "categorydelete_child_categorydebugparam2"
            when
            then
                        update(categorydelete_child_categorydefault);//更新fact中变量值
                        update(categorydelete_child_categorycategory_page);//更新fact中变量值
                        update(categorydelete_child_categoryfilter);//更新fact中变量值
                        update(categorydelete_child_categoryfor_temp_obj);//更新fact中变量值
                        update(categorydelete_child_categoryparent_category);//更新fact中变量值
                        update(categorydelete_child_categoryparent_section);//更新fact中变量值
            end

            //逻辑处理节点[上级的是否叶子节点变更]
            rule "prepareparam2"
            ruleflow-group "categorydelete_child_categoryprepareparam2"
            when
            then
                            categorydelete_child_categoryparent_category.set("id",categorydelete_child_categorydefault.get("pid"));
                            categorydelete_child_categoryfilter.set("n_section_id_eq",categorydelete_child_categorydefault.get("sectionid"));
                            categorydelete_child_categoryparent_category.set("is_leaf","1");
                        update(categorydelete_child_categorydefault);//更新fact中变量值
                        update(categorydelete_child_categorycategory_page);//更新fact中变量值
                        update(categorydelete_child_categoryfilter);//更新fact中变量值
                        update(categorydelete_child_categoryfor_temp_obj);//更新fact中变量值
                        update(categorydelete_child_categoryparent_category);//更新fact中变量值
                        update(categorydelete_child_categoryparent_section);//更新fact中变量值
            end

            //逻辑处理节点[变更上级节点]
            rule "deaction3"
            ruleflow-group "categorydelete_child_categorydeaction3"
            when
            then
                        categoryservice.update(categorydelete_child_categoryparent_category);
                        update(categorydelete_child_categorydefault);//更新fact中变量值
                        update(categorydelete_child_categorycategory_page);//更新fact中变量值
                        update(categorydelete_child_categoryfilter);//更新fact中变量值
                        update(categorydelete_child_categoryfor_temp_obj);//更新fact中变量值
                        update(categorydelete_child_categoryparent_category);//更新fact中变量值
                        update(categorydelete_child_categoryparent_section);//更新fact中变量值
            end

            //逻辑处理节点[修改需求信息]
            rule "rawsqlcall1"
            ruleflow-group "categorydelete_child_categoryrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",categorydelete_child_categorydefault.get("id"));
        param.put("param1",categorydelete_child_categorydefault.get("id"));
    String strSql="UPDATE idea t  INNER JOIN category t21 ON t.category_id = t21.ID  SET t.category_id = NULL WHERE (t.category_id = #{et.param0} OR t21.categories LIKE CONCAT('%',#{et.param1},'%'))";
                        iBzSysCategoryDefaultService.execute(strSql,param);//SQL调用
                        update(categorydelete_child_categorydefault);//更新fact中变量值
                        update(categorydelete_child_categorycategory_page);//更新fact中变量值
                        update(categorydelete_child_categoryfilter);//更新fact中变量值
                        update(categorydelete_child_categoryfor_temp_obj);//更新fact中变量值
                        update(categorydelete_child_categoryparent_category);//更新fact中变量值
                        update(categorydelete_child_categoryparent_section);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "categorydelete_child_categoryloopsubcall1"
            when
            then
                        update(categorydelete_child_categorydefault);//更新fact中变量值
                        update(categorydelete_child_categorycategory_page);//更新fact中变量值
                        update(categorydelete_child_categoryfilter);//更新fact中变量值
                        update(categorydelete_child_categoryfor_temp_obj);//更新fact中变量值
                        update(categorydelete_child_categoryparent_category);//更新fact中变量值
                        update(categorydelete_child_categoryparent_section);//更新fact中变量值
            end

            //逻辑处理节点[循环调用]
            rule "delogic1"
            ruleflow-group "categorydelete_child_categorydelogic1"
            when
            then
                        update(categorydelete_child_categorydefault);//更新fact中变量值
                        update(categorydelete_child_categorycategory_page);//更新fact中变量值
                        update(categorydelete_child_categoryfilter);//更新fact中变量值
                        update(categorydelete_child_categoryfor_temp_obj);//更新fact中变量值
                        update(categorydelete_child_categoryparent_category);//更新fact中变量值
                        update(categorydelete_child_categoryparent_section);//更新fact中变量值
            end

            //逻辑处理节点[上级的是否叶子节点变更]
            rule "prepareparam3"
            ruleflow-group "categorydelete_child_categoryprepareparam3"
            when
            then
                            categorydelete_child_categoryparent_section.set("id",categorydelete_child_categorydefault.get("sectionid"));
                            categorydelete_child_categoryfilter.set("n_section_id_eq",categorydelete_child_categorydefault.get("sectionid"));
                            categorydelete_child_categoryparent_section.set("isleaf","1");
                        update(categorydelete_child_categorydefault);//更新fact中变量值
                        update(categorydelete_child_categorycategory_page);//更新fact中变量值
                        update(categorydelete_child_categoryfilter);//更新fact中变量值
                        update(categorydelete_child_categoryfor_temp_obj);//更新fact中变量值
                        update(categorydelete_child_categoryparent_category);//更新fact中变量值
                        update(categorydelete_child_categoryparent_section);//更新fact中变量值
            end

            //逻辑处理节点[模块下模块]
            rule "dedataset3"
            ruleflow-group "categorydelete_child_categorydedataset3"
            when
            then
                        update(categorydelete_child_categorydefault);//更新fact中变量值
                        update(categorydelete_child_categorycategory_page);//更新fact中变量值
                        update(categorydelete_child_categoryfilter);//更新fact中变量值
                        update(categorydelete_child_categoryfor_temp_obj);//更新fact中变量值
                        update(categorydelete_child_categoryparent_category);//更新fact中变量值
                        update(categorydelete_child_categoryparent_section);//更新fact中变量值
            end

            //逻辑处理节点[子产品下模块]
            rule "dedataset2"
            ruleflow-group "categorydelete_child_categorydedataset2"
            when
            then
                        update(categorydelete_child_categorydefault);//更新fact中变量值
                        update(categorydelete_child_categorycategory_page);//更新fact中变量值
                        update(categorydelete_child_categoryfilter);//更新fact中变量值
                        update(categorydelete_child_categoryfor_temp_obj);//更新fact中变量值
                        update(categorydelete_child_categoryparent_category);//更新fact中变量值
                        update(categorydelete_child_categoryparent_section);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "categorydelete_child_categoryend2"
            when
            then
                        update(categorydelete_child_categorydefault);//更新fact中变量值
                        update(categorydelete_child_categorycategory_page);//更新fact中变量值
                        update(categorydelete_child_categoryfilter);//更新fact中变量值
                        update(categorydelete_child_categoryfor_temp_obj);//更新fact中变量值
                        update(categorydelete_child_categoryparent_category);//更新fact中变量值
                        update(categorydelete_child_categoryparent_section);//更新fact中变量值
            end

            //逻辑处理节点[变更上级节点]
            rule "deaction4"
            ruleflow-group "categorydelete_child_categorydeaction4"
            when
            then
                        sectionservice.update(categorydelete_child_categoryparent_section);
                        update(categorydelete_child_categorydefault);//更新fact中变量值
                        update(categorydelete_child_categorycategory_page);//更新fact中变量值
                        update(categorydelete_child_categoryfilter);//更新fact中变量值
                        update(categorydelete_child_categoryfor_temp_obj);//更新fact中变量值
                        update(categorydelete_child_categoryparent_category);//更新fact中变量值
                        update(categorydelete_child_categoryparent_section);//更新fact中变量值
            end