package cn.ibizlab.plm.base.logic.categorylogic.move_out_section;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.Category categorymove_out_sectiondefault;
        global cn.ibizlab.plm.core.base.service.ICategoryService iBzSysCategoryDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "categorymove_out_sectionbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "categorymove_out_sectionend1"
            when
            then
                        update(categorymove_out_sectiondefault);//更新fact中变量值
            end