package cn.ibizlab.plm.base.logic.categorylogic.set_section;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.Category categoryset_sectiondefault;
                global cn.ibizlab.plm.core.base.domain.Category categoryset_sectionnew_category;
        global cn.ibizlab.plm.core.base.service.ICategoryService iBzSysCategoryDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "categoryset_sectionbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "categoryset_sectionprepareparam1"
            when
            then
                            categoryset_sectionnew_category.set("sectionid",categoryset_sectiondefault.get("sectionid"));
                            categoryset_sectionnew_category.set("last_section_id",categoryset_sectiondefault.get("last.section_id"));
                        update(categoryset_sectiondefault);//更新fact中变量值
                        update(categoryset_sectionnew_category);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "categoryset_sectiondebugparam1"
            when
            then
                        update(categoryset_sectiondefault);//更新fact中变量值
                        update(categoryset_sectionnew_category);//更新fact中变量值
            end