package cn.ibizlab.plm.testmgmt.logic.reviewlogic.program_test_case;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.review reviewprogram_test_casedefault;
                global cn.ibizlab.plm.core.testmgmt.domain.review reviewprogram_test_casefor_temp_obj;
                global cn.ibizlab.plm.core.testmgmt.domain.review reviewprogram_test_caseforward_relation_obj;
                global cn.ibizlab.plm.core.testmgmt.domain.review reviewprogram_test_casereverse_relation_obj;
                global cn.ibizlab.plm.core.testmgmt.domain.review reviewprogram_test_caseselectdata;
                    global cn.ibizlab.plm.core.testmgmt.service.Ireview_contentService review_contentservice;
        global cn.ibizlab.plm.core.testmgmt.service.IreviewService iBzSysReviewDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "reviewprogram_test_casebegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "reviewprogram_test_casedebugparam1"
            when
            then
                        update(reviewprogram_test_casedefault);//更新fact中变量值
                        update(reviewprogram_test_casefor_temp_obj);//更新fact中变量值
                        update(reviewprogram_test_caseforward_relation_obj);//更新fact中变量值
                        update(reviewprogram_test_casereverse_relation_obj);//更新fact中变量值
                        update(reviewprogram_test_caseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "reviewprogram_test_casebindparam1"
            when
            then
                        update(reviewprogram_test_casedefault);//更新fact中变量值
                        update(reviewprogram_test_casefor_temp_obj);//更新fact中变量值
                        update(reviewprogram_test_caseforward_relation_obj);//更新fact中变量值
                        update(reviewprogram_test_casereverse_relation_obj);//更新fact中变量值
                        update(reviewprogram_test_caseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "reviewprogram_test_caseloopsubcall1"
            when
            then
                        update(reviewprogram_test_casedefault);//更新fact中变量值
                        update(reviewprogram_test_casefor_temp_obj);//更新fact中变量值
                        update(reviewprogram_test_caseforward_relation_obj);//更新fact中变量值
                        update(reviewprogram_test_casereverse_relation_obj);//更新fact中变量值
                        update(reviewprogram_test_caseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "reviewprogram_test_caserenewparam1"
            when
            then
                        update(reviewprogram_test_casedefault);//更新fact中变量值
                        update(reviewprogram_test_casefor_temp_obj);//更新fact中变量值
                        update(reviewprogram_test_caseforward_relation_obj);//更新fact中变量值
                        update(reviewprogram_test_casereverse_relation_obj);//更新fact中变量值
                        update(reviewprogram_test_caseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam2"
            ruleflow-group "reviewprogram_test_caserenewparam2"
            when
            then
                        update(reviewprogram_test_casedefault);//更新fact中变量值
                        update(reviewprogram_test_casefor_temp_obj);//更新fact中变量值
                        update(reviewprogram_test_caseforward_relation_obj);//更新fact中变量值
                        update(reviewprogram_test_casereverse_relation_obj);//更新fact中变量值
                        update(reviewprogram_test_caseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[填充需要的属性值]
            rule "prepareparam1"
            ruleflow-group "reviewprogram_test_caseprepareparam1"
            when
            then
                            reviewprogram_test_caseforward_relation_obj.set("principal_id",reviewprogram_test_casedefault.get("principal_id"));
                            reviewprogram_test_casereverse_relation_obj.set("principal_id",reviewprogram_test_casefor_temp_obj.get("owner_id"));
                            reviewprogram_test_casereverse_relation_obj.set("target_id",reviewprogram_test_casedefault.get("principal_id"));
                            reviewprogram_test_casereverse_relation_obj.set("principal_type",reviewprogram_test_casedefault.get("target_type"));
                            reviewprogram_test_casereverse_relation_obj.set("target_type",reviewprogram_test_casedefault.get("principal_type"));
                            reviewprogram_test_caseforward_relation_obj.set("principal_type",reviewprogram_test_casedefault.get("principal_type"));
                            reviewprogram_test_caseforward_relation_obj.set("target_type",reviewprogram_test_casedefault.get("target_type"));
                            reviewprogram_test_caseforward_relation_obj.set("target_id",reviewprogram_test_casefor_temp_obj.get("owner_id"));
                        update(reviewprogram_test_casedefault);//更新fact中变量值
                        update(reviewprogram_test_casefor_temp_obj);//更新fact中变量值
                        update(reviewprogram_test_caseforward_relation_obj);//更新fact中变量值
                        update(reviewprogram_test_casereverse_relation_obj);//更新fact中变量值
                        update(reviewprogram_test_caseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "reviewprogram_test_caseend1"
            when
            then
                        update(reviewprogram_test_casedefault);//更新fact中变量值
                        update(reviewprogram_test_casefor_temp_obj);//更新fact中变量值
                        update(reviewprogram_test_caseforward_relation_obj);//更新fact中变量值
                        update(reviewprogram_test_casereverse_relation_obj);//更新fact中变量值
                        update(reviewprogram_test_caseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[生成正向关联数据]
            rule "deaction1"
            ruleflow-group "reviewprogram_test_casedeaction1"
            when
            then
                        review_contentservice.save(reviewprogram_test_caseforward_relation_obj);
                        update(reviewprogram_test_casedefault);//更新fact中变量值
                        update(reviewprogram_test_casefor_temp_obj);//更新fact中变量值
                        update(reviewprogram_test_caseforward_relation_obj);//更新fact中变量值
                        update(reviewprogram_test_casereverse_relation_obj);//更新fact中变量值
                        update(reviewprogram_test_caseselectdata);//更新fact中变量值
            end

            //逻辑处理节点[生成反向关联数据]
            rule "deaction2"
            ruleflow-group "reviewprogram_test_casedeaction2"
            when
            then
                        review_contentservice.save(reviewprogram_test_casereverse_relation_obj);
                        update(reviewprogram_test_casedefault);//更新fact中变量值
                        update(reviewprogram_test_casefor_temp_obj);//更新fact中变量值
                        update(reviewprogram_test_caseforward_relation_obj);//更新fact中变量值
                        update(reviewprogram_test_casereverse_relation_obj);//更新fact中变量值
                        update(reviewprogram_test_caseselectdata);//更新fact中变量值
            end