package cn.ibizlab.plm.testmgmt.logic.reviewlogic.repeal_review;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.review reviewrepeal_reviewdefault;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content reviewrepeal_reviewcontent_filter;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content reviewrepeal_reviewfor_content;
                global cn.ibizlab.plm.core.testmgmt.domain.review_result reviewrepeal_reviewresult;
                global cn.ibizlab.plm.core.testmgmt.domain.review_result reviewrepeal_reviewresults;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content reviewrepeal_reviewreview_content;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage reviewrepeal_reviewstage;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage reviewrepeal_reviewstages;
                    global cn.ibizlab.plm.core.testmgmt.service.Ireview_contentService review_contentservice;
                    global cn.ibizlab.plm.core.testmgmt.service.IreviewService reviewservice;
                    global cn.ibizlab.plm.core.testmgmt.service.Ireview_resultService review_resultservice;
        global cn.ibizlab.plm.core.testmgmt.service.IreviewService iBzSysReviewDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "reviewrepeal_reviewbegin"
            when
            then
            end

            //逻辑处理节点[绑定阶段]
            rule "prepareparam2"
            ruleflow-group "reviewrepeal_reviewprepareparam2"
            when
            then
                            reviewrepeal_reviewstages.set("",reviewrepeal_reviewdefault.get("stage"));
                            reviewrepeal_reviewcontent_filter.set("n_principal_id_eq",reviewrepeal_reviewdefault.get("id"));
                            reviewrepeal_reviewcontent_filter.set("n_principal_type_eq","REVIEW");
                        update(reviewrepeal_reviewdefault);//更新fact中变量值
                        update(reviewrepeal_reviewcontent_filter);//更新fact中变量值
                        update(reviewrepeal_reviewfor_content);//更新fact中变量值
                        update(reviewrepeal_reviewresult);//更新fact中变量值
                        update(reviewrepeal_reviewresults);//更新fact中变量值
                        update(reviewrepeal_reviewreview_content);//更新fact中变量值
                        update(reviewrepeal_reviewstage);//更新fact中变量值
                        update(reviewrepeal_reviewstages);//更新fact中变量值
            end

            //逻辑处理节点[获取评审内容]
            rule "dedataset1"
            ruleflow-group "reviewrepeal_reviewdedataset1"
            when
            then
                        update(reviewrepeal_reviewdefault);//更新fact中变量值
                        update(reviewrepeal_reviewcontent_filter);//更新fact中变量值
                        update(reviewrepeal_reviewfor_content);//更新fact中变量值
                        update(reviewrepeal_reviewresult);//更新fact中变量值
                        update(reviewrepeal_reviewresults);//更新fact中变量值
                        update(reviewrepeal_reviewreview_content);//更新fact中变量值
                        update(reviewrepeal_reviewstage);//更新fact中变量值
                        update(reviewrepeal_reviewstages);//更新fact中变量值
            end

            //逻辑处理节点[循环阶段数据]
            rule "loopsubcall1"
            ruleflow-group "reviewrepeal_reviewloopsubcall1"
            when
            then
                        update(reviewrepeal_reviewdefault);//更新fact中变量值
                        update(reviewrepeal_reviewcontent_filter);//更新fact中变量值
                        update(reviewrepeal_reviewfor_content);//更新fact中变量值
                        update(reviewrepeal_reviewresult);//更新fact中变量值
                        update(reviewrepeal_reviewresults);//更新fact中变量值
                        update(reviewrepeal_reviewreview_content);//更新fact中变量值
                        update(reviewrepeal_reviewstage);//更新fact中变量值
                        update(reviewrepeal_reviewstages);//更新fact中变量值
            end

            //逻辑处理节点[清空提交人、状态、时间]
            rule "prepareparam1"
            ruleflow-group "reviewrepeal_reviewprepareparam1"
            when
            then
                                reviewrepeal_reviewdefault.set("submittername",null);
                                reviewrepeal_reviewdefault.set("submittedat",null);
                                reviewrepeal_reviewdefault.set("submitterid",null);
                            reviewrepeal_reviewdefault.set("state","50");
                        update(reviewrepeal_reviewdefault);//更新fact中变量值
                        update(reviewrepeal_reviewcontent_filter);//更新fact中变量值
                        update(reviewrepeal_reviewfor_content);//更新fact中变量值
                        update(reviewrepeal_reviewresult);//更新fact中变量值
                        update(reviewrepeal_reviewresults);//更新fact中变量值
                        update(reviewrepeal_reviewreview_content);//更新fact中变量值
                        update(reviewrepeal_reviewstage);//更新fact中变量值
                        update(reviewrepeal_reviewstages);//更新fact中变量值
            end

            //逻辑处理节点[设置阶段为未开始]
            rule "prepareparam3"
            ruleflow-group "reviewrepeal_reviewprepareparam3"
            when
            then
                            reviewrepeal_reviewstage.set("stagestate","10");
                        update(reviewrepeal_reviewdefault);//更新fact中变量值
                        update(reviewrepeal_reviewcontent_filter);//更新fact中变量值
                        update(reviewrepeal_reviewfor_content);//更新fact中变量值
                        update(reviewrepeal_reviewresult);//更新fact中变量值
                        update(reviewrepeal_reviewresults);//更新fact中变量值
                        update(reviewrepeal_reviewreview_content);//更新fact中变量值
                        update(reviewrepeal_reviewstage);//更新fact中变量值
                        update(reviewrepeal_reviewstages);//更新fact中变量值
            end

            //逻辑处理节点[更新评审]
            rule "deaction1"
            ruleflow-group "reviewrepeal_reviewdeaction1"
            when
            then
                        reviewservice.update(reviewrepeal_reviewdefault);
                        update(reviewrepeal_reviewdefault);//更新fact中变量值
                        update(reviewrepeal_reviewcontent_filter);//更新fact中变量值
                        update(reviewrepeal_reviewfor_content);//更新fact中变量值
                        update(reviewrepeal_reviewresult);//更新fact中变量值
                        update(reviewrepeal_reviewresults);//更新fact中变量值
                        update(reviewrepeal_reviewreview_content);//更新fact中变量值
                        update(reviewrepeal_reviewstage);//更新fact中变量值
                        update(reviewrepeal_reviewstages);//更新fact中变量值
            end

            //逻辑处理节点[循环评审内容]
            rule "loopsubcall2"
            ruleflow-group "reviewrepeal_reviewloopsubcall2"
            when
            then
                        update(reviewrepeal_reviewdefault);//更新fact中变量值
                        update(reviewrepeal_reviewcontent_filter);//更新fact中变量值
                        update(reviewrepeal_reviewfor_content);//更新fact中变量值
                        update(reviewrepeal_reviewresult);//更新fact中变量值
                        update(reviewrepeal_reviewresults);//更新fact中变量值
                        update(reviewrepeal_reviewreview_content);//更新fact中变量值
                        update(reviewrepeal_reviewstage);//更新fact中变量值
                        update(reviewrepeal_reviewstages);//更新fact中变量值
            end

            //逻辑处理节点[获取评审阶段结果]
            rule "prepareparam4"
            ruleflow-group "reviewrepeal_reviewprepareparam4"
            when
            then
                            reviewrepeal_reviewresults.set("",reviewrepeal_reviewfor_content.get("stageresults"));
                        update(reviewrepeal_reviewdefault);//更新fact中变量值
                        update(reviewrepeal_reviewcontent_filter);//更新fact中变量值
                        update(reviewrepeal_reviewfor_content);//更新fact中变量值
                        update(reviewrepeal_reviewresult);//更新fact中变量值
                        update(reviewrepeal_reviewresults);//更新fact中变量值
                        update(reviewrepeal_reviewreview_content);//更新fact中变量值
                        update(reviewrepeal_reviewstage);//更新fact中变量值
                        update(reviewrepeal_reviewstages);//更新fact中变量值
            end

            //逻辑处理节点[循环评审结果]
            rule "loopsubcall3"
            ruleflow-group "reviewrepeal_reviewloopsubcall3"
            when
            then
                        update(reviewrepeal_reviewdefault);//更新fact中变量值
                        update(reviewrepeal_reviewcontent_filter);//更新fact中变量值
                        update(reviewrepeal_reviewfor_content);//更新fact中变量值
                        update(reviewrepeal_reviewresult);//更新fact中变量值
                        update(reviewrepeal_reviewresults);//更新fact中变量值
                        update(reviewrepeal_reviewreview_content);//更新fact中变量值
                        update(reviewrepeal_reviewstage);//更新fact中变量值
                        update(reviewrepeal_reviewstages);//更新fact中变量值
            end

            //逻辑处理节点[设置评审状态为为评审]
            rule "prepareparam5"
            ruleflow-group "reviewrepeal_reviewprepareparam5"
            when
            then
                            reviewrepeal_reviewresult.set("resultstate","1");
                        update(reviewrepeal_reviewdefault);//更新fact中变量值
                        update(reviewrepeal_reviewcontent_filter);//更新fact中变量值
                        update(reviewrepeal_reviewfor_content);//更新fact中变量值
                        update(reviewrepeal_reviewresult);//更新fact中变量值
                        update(reviewrepeal_reviewresults);//更新fact中变量值
                        update(reviewrepeal_reviewreview_content);//更新fact中变量值
                        update(reviewrepeal_reviewstage);//更新fact中变量值
                        update(reviewrepeal_reviewstages);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "reviewrepeal_reviewend1"
            when
            then
                        update(reviewrepeal_reviewdefault);//更新fact中变量值
                        update(reviewrepeal_reviewcontent_filter);//更新fact中变量值
                        update(reviewrepeal_reviewfor_content);//更新fact中变量值
                        update(reviewrepeal_reviewresult);//更新fact中变量值
                        update(reviewrepeal_reviewresults);//更新fact中变量值
                        update(reviewrepeal_reviewreview_content);//更新fact中变量值
                        update(reviewrepeal_reviewstage);//更新fact中变量值
                        update(reviewrepeal_reviewstages);//更新fact中变量值
            end

            //逻辑处理节点[更新评审结果]
            rule "deaction2"
            ruleflow-group "reviewrepeal_reviewdeaction2"
            when
            then
                        review_resultservice.update(reviewrepeal_reviewresult);
                        update(reviewrepeal_reviewdefault);//更新fact中变量值
                        update(reviewrepeal_reviewcontent_filter);//更新fact中变量值
                        update(reviewrepeal_reviewfor_content);//更新fact中变量值
                        update(reviewrepeal_reviewresult);//更新fact中变量值
                        update(reviewrepeal_reviewresults);//更新fact中变量值
                        update(reviewrepeal_reviewreview_content);//更新fact中变量值
                        update(reviewrepeal_reviewstage);//更新fact中变量值
                        update(reviewrepeal_reviewstages);//更新fact中变量值
            end