package cn.ibizlab.plm.testmgmt.logic.reviewlogic.submit_review;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.review reviewsubmit_reviewdefault;
                global cn.ibizlab.plm.core.base.domain.relation reviewsubmit_reviewfor_reltion;
                global cn.ibizlab.plm.core.base.domain.relation reviewsubmit_reviewrelation_page;
                global cn.ibizlab.plm.core.base.domain.relation reviewsubmit_reviewreltion_filter;
                global cn.ibizlab.plm.core.testmgmt.domain.review_content reviewsubmit_reviewreview_content;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage reviewsubmit_reviewstage;
                global cn.ibizlab.plm.core.testmgmt.domain.review_stage reviewsubmit_reviewstages;
                global cn.ibizlab.plm.core.testmgmt.domain.test_case reviewsubmit_reviewtest_case;
                    global cn.ibizlab.plm.core.testmgmt.service.IreviewService reviewservice;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
                    global cn.ibizlab.plm.core.testmgmt.service.Itest_caseService test_caseservice;
        global cn.ibizlab.plm.core.testmgmt.service.IreviewService iBzSysReviewDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "reviewsubmit_reviewbegin"
            when
            then
            end

            //逻辑处理节点[设置提交人、状态]
            rule "prepareparam1"
            ruleflow-group "reviewsubmit_reviewprepareparam1"
            when
            then
                                reviewsubmit_reviewdefault.set("submittername",curuser.getSessionParams().get("srfpersonname"));
                                reviewsubmit_reviewdefault.set("submitterid",curuser.getSessionParams().get("srfpersonid"));
                            reviewsubmit_reviewdefault.set("state","20");
                        update(reviewsubmit_reviewdefault);//更新fact中变量值
                        update(reviewsubmit_reviewfor_reltion);//更新fact中变量值
                        update(reviewsubmit_reviewrelation_page);//更新fact中变量值
                        update(reviewsubmit_reviewreltion_filter);//更新fact中变量值
                        update(reviewsubmit_reviewreview_content);//更新fact中变量值
                        update(reviewsubmit_reviewstage);//更新fact中变量值
                        update(reviewsubmit_reviewstages);//更新fact中变量值
                        update(reviewsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[更新评审]
            rule "deaction1"
            ruleflow-group "reviewsubmit_reviewdeaction1"
            when
            then
                        reviewservice.update(reviewsubmit_reviewdefault);
                        update(reviewsubmit_reviewdefault);//更新fact中变量值
                        update(reviewsubmit_reviewfor_reltion);//更新fact中变量值
                        update(reviewsubmit_reviewrelation_page);//更新fact中变量值
                        update(reviewsubmit_reviewreltion_filter);//更新fact中变量值
                        update(reviewsubmit_reviewreview_content);//更新fact中变量值
                        update(reviewsubmit_reviewstage);//更新fact中变量值
                        update(reviewsubmit_reviewstages);//更新fact中变量值
                        update(reviewsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[传入参数]
            rule "debugparam1"
            ruleflow-group "reviewsubmit_reviewdebugparam1"
            when
            then
                        update(reviewsubmit_reviewdefault);//更新fact中变量值
                        update(reviewsubmit_reviewfor_reltion);//更新fact中变量值
                        update(reviewsubmit_reviewrelation_page);//更新fact中变量值
                        update(reviewsubmit_reviewreltion_filter);//更新fact中变量值
                        update(reviewsubmit_reviewreview_content);//更新fact中变量值
                        update(reviewsubmit_reviewstage);//更新fact中变量值
                        update(reviewsubmit_reviewstages);//更新fact中变量值
                        update(reviewsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[设置提交时间]
            rule "rawsfcode1"
            ruleflow-group "reviewsubmit_reviewrawsfcode1"
            when
            then
                        update(reviewsubmit_reviewdefault);//更新fact中变量值
                        update(reviewsubmit_reviewfor_reltion);//更新fact中变量值
                        update(reviewsubmit_reviewrelation_page);//更新fact中变量值
                        update(reviewsubmit_reviewreltion_filter);//更新fact中变量值
                        update(reviewsubmit_reviewreview_content);//更新fact中变量值
                        update(reviewsubmit_reviewstage);//更新fact中变量值
                        update(reviewsubmit_reviewstages);//更新fact中变量值
                        update(reviewsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[设置阶段的状态]
            rule "prepareparam2"
            ruleflow-group "reviewsubmit_reviewprepareparam2"
            when
            then
                            reviewsubmit_reviewstages.set("",reviewsubmit_reviewdefault.get("stage"));
                            reviewsubmit_reviewstage.set("",reviewsubmit_reviewstages.get("0"));
                            reviewsubmit_reviewstage.set("stagestate","20");
                        update(reviewsubmit_reviewdefault);//更新fact中变量值
                        update(reviewsubmit_reviewfor_reltion);//更新fact中变量值
                        update(reviewsubmit_reviewrelation_page);//更新fact中变量值
                        update(reviewsubmit_reviewreltion_filter);//更新fact中变量值
                        update(reviewsubmit_reviewreview_content);//更新fact中变量值
                        update(reviewsubmit_reviewstage);//更新fact中变量值
                        update(reviewsubmit_reviewstages);//更新fact中变量值
                        update(reviewsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[获取关系信息]
            rule "dedataset1"
            ruleflow-group "reviewsubmit_reviewdedataset1"
            when
            then
                        update(reviewsubmit_reviewdefault);//更新fact中变量值
                        update(reviewsubmit_reviewfor_reltion);//更新fact中变量值
                        update(reviewsubmit_reviewrelation_page);//更新fact中变量值
                        update(reviewsubmit_reviewreltion_filter);//更新fact中变量值
                        update(reviewsubmit_reviewreview_content);//更新fact中变量值
                        update(reviewsubmit_reviewstage);//更新fact中变量值
                        update(reviewsubmit_reviewstages);//更新fact中变量值
                        update(reviewsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[设置关系过滤参数]
            rule "prepareparam3"
            ruleflow-group "reviewsubmit_reviewprepareparam3"
            when
            then
                            reviewsubmit_reviewreltion_filter.set("n_principal_id_eq",reviewsubmit_reviewdefault.get("id"));
                            reviewsubmit_reviewreltion_filter.set("n_principal_type_eq","REVIEW");
                        update(reviewsubmit_reviewdefault);//更新fact中变量值
                        update(reviewsubmit_reviewfor_reltion);//更新fact中变量值
                        update(reviewsubmit_reviewrelation_page);//更新fact中变量值
                        update(reviewsubmit_reviewreltion_filter);//更新fact中变量值
                        update(reviewsubmit_reviewreview_content);//更新fact中变量值
                        update(reviewsubmit_reviewstage);//更新fact中变量值
                        update(reviewsubmit_reviewstages);//更新fact中变量值
                        update(reviewsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "reviewsubmit_reviewend1"
            when
            then
                        update(reviewsubmit_reviewdefault);//更新fact中变量值
                        update(reviewsubmit_reviewfor_reltion);//更新fact中变量值
                        update(reviewsubmit_reviewrelation_page);//更新fact中变量值
                        update(reviewsubmit_reviewreltion_filter);//更新fact中变量值
                        update(reviewsubmit_reviewreview_content);//更新fact中变量值
                        update(reviewsubmit_reviewstage);//更新fact中变量值
                        update(reviewsubmit_reviewstages);//更新fact中变量值
                        update(reviewsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "reviewsubmit_reviewloopsubcall1"
            when
            then
                        update(reviewsubmit_reviewdefault);//更新fact中变量值
                        update(reviewsubmit_reviewfor_reltion);//更新fact中变量值
                        update(reviewsubmit_reviewrelation_page);//更新fact中变量值
                        update(reviewsubmit_reviewreltion_filter);//更新fact中变量值
                        update(reviewsubmit_reviewreview_content);//更新fact中变量值
                        update(reviewsubmit_reviewstage);//更新fact中变量值
                        update(reviewsubmit_reviewstages);//更新fact中变量值
                        update(reviewsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[评审内容为空]
            rule "throwexception1"
            ruleflow-group "reviewsubmit_reviewthrowexception1"
            when
            then
                        update(reviewsubmit_reviewdefault);//更新fact中变量值
                        update(reviewsubmit_reviewfor_reltion);//更新fact中变量值
                        update(reviewsubmit_reviewrelation_page);//更新fact中变量值
                        update(reviewsubmit_reviewreltion_filter);//更新fact中变量值
                        update(reviewsubmit_reviewreview_content);//更新fact中变量值
                        update(reviewsubmit_reviewstage);//更新fact中变量值
                        update(reviewsubmit_reviewstages);//更新fact中变量值
                        update(reviewsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[获取测试用例id]
            rule "prepareparam4"
            ruleflow-group "reviewsubmit_reviewprepareparam4"
            when
            then
                            reviewsubmit_reviewtest_case.set("id",reviewsubmit_reviewfor_reltion.get("targetid"));
                        update(reviewsubmit_reviewdefault);//更新fact中变量值
                        update(reviewsubmit_reviewfor_reltion);//更新fact中变量值
                        update(reviewsubmit_reviewrelation_page);//更新fact中变量值
                        update(reviewsubmit_reviewreltion_filter);//更新fact中变量值
                        update(reviewsubmit_reviewreview_content);//更新fact中变量值
                        update(reviewsubmit_reviewstage);//更新fact中变量值
                        update(reviewsubmit_reviewstages);//更新fact中变量值
                        update(reviewsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[获取测试用例详情]
            rule "deaction2"
            ruleflow-group "reviewsubmit_reviewdeaction2"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(test_caseservice.get(reviewsubmit_reviewtest_case.getId()),reviewsubmit_reviewtest_case);
                        update(reviewsubmit_reviewdefault);//更新fact中变量值
                        update(reviewsubmit_reviewfor_reltion);//更新fact中变量值
                        update(reviewsubmit_reviewrelation_page);//更新fact中变量值
                        update(reviewsubmit_reviewreltion_filter);//更新fact中变量值
                        update(reviewsubmit_reviewreview_content);//更新fact中变量值
                        update(reviewsubmit_reviewstage);//更新fact中变量值
                        update(reviewsubmit_reviewstages);//更新fact中变量值
                        update(reviewsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[设置测试用例评审状态]
            rule "prepareparam5"
            ruleflow-group "reviewsubmit_reviewprepareparam5"
            when
            then
                            reviewsubmit_reviewtest_case.set("reviewresultstate","2");
                        update(reviewsubmit_reviewdefault);//更新fact中变量值
                        update(reviewsubmit_reviewfor_reltion);//更新fact中变量值
                        update(reviewsubmit_reviewrelation_page);//更新fact中变量值
                        update(reviewsubmit_reviewreltion_filter);//更新fact中变量值
                        update(reviewsubmit_reviewreview_content);//更新fact中变量值
                        update(reviewsubmit_reviewstage);//更新fact中变量值
                        update(reviewsubmit_reviewstages);//更新fact中变量值
                        update(reviewsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[更新测试用例]
            rule "deaction3"
            ruleflow-group "reviewsubmit_reviewdeaction3"
            when
            then
                        test_caseservice.update(reviewsubmit_reviewtest_case);
                        update(reviewsubmit_reviewdefault);//更新fact中变量值
                        update(reviewsubmit_reviewfor_reltion);//更新fact中变量值
                        update(reviewsubmit_reviewrelation_page);//更新fact中变量值
                        update(reviewsubmit_reviewreltion_filter);//更新fact中变量值
                        update(reviewsubmit_reviewreview_content);//更新fact中变量值
                        update(reviewsubmit_reviewstage);//更新fact中变量值
                        update(reviewsubmit_reviewstages);//更新fact中变量值
                        update(reviewsubmit_reviewtest_case);//更新fact中变量值
            end

            //逻辑处理节点[重置测试用例参数]
            rule "resetparam1"
            ruleflow-group "reviewsubmit_reviewresetparam1"
            when
            then
                        update(reviewsubmit_reviewdefault);//更新fact中变量值
                        update(reviewsubmit_reviewfor_reltion);//更新fact中变量值
                        update(reviewsubmit_reviewrelation_page);//更新fact中变量值
                        update(reviewsubmit_reviewreltion_filter);//更新fact中变量值
                        update(reviewsubmit_reviewreview_content);//更新fact中变量值
                        update(reviewsubmit_reviewstage);//更新fact中变量值
                        update(reviewsubmit_reviewstages);//更新fact中变量值
                        update(reviewsubmit_reviewtest_case);//更新fact中变量值
            end