package cn.ibizlab.plm.testmgmt.logic.baseline_test_caselogic.shift_out_baseline;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.baseline_test_case baseline_test_caseshift_out_baselinedefault;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.testmgmt.service.Ibaseline_test_caseService iBzSysBaseline_test_caseDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "baseline_test_caseshift_out_baselinebegin"
            when
            then
            end

            //逻辑处理节点[删除基线-用例关联数据]
            rule "deaction1"
            ruleflow-group "baseline_test_caseshift_out_baselinedeaction1"
            when
            then
                        relationservice.remove(baseline_test_caseshift_out_baselinedefault.getId());
                        update(baseline_test_caseshift_out_baselinedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "baseline_test_caseshift_out_baselineend1"
            when
            then
                        update(baseline_test_caseshift_out_baselinedefault);//更新fact中变量值
            end