package cn.ibizlab.plm.base.logic.versionlogic.fix_commit;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.version versionfix_commitdefault;
                global cn.ibizlab.plm.core.base.domain.version versionfix_commitfilter;
                global cn.ibizlab.plm.core.base.domain.version versionfix_commitversions;
                    global cn.ibizlab.plm.core.base.service.IversionService versionservice;
        global cn.ibizlab.plm.core.base.service.IversionService iBzSysVersionDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "versionfix_commitbegin"
            when
            then
            end

            //逻辑处理节点[抛出异常]
            rule "throwexception1"
            ruleflow-group "versionfix_committhrowexception1"
            when
            then
                        update(versionfix_commitdefault);//更新fact中变量值
                        update(versionfix_commitfilter);//更新fact中变量值
                        update(versionfix_commitversions);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "versionfix_commitend1"
            when
            then
                        update(versionfix_commitdefault);//更新fact中变量值
                        update(versionfix_commitfilter);//更新fact中变量值
                        update(versionfix_commitversions);//更新fact中变量值
            end

            //逻辑处理节点[初始化版本]
            rule "prepareparam1"
            ruleflow-group "versionfix_commitprepareparam1"
            when
            then
                            versionfix_commitdefault.set("identifier","1");
                            versionfix_commitdefault.set("manual","1");
                            versionfix_commitdefault.set("name","v1");
                        update(versionfix_commitdefault);//更新fact中变量值
                        update(versionfix_commitfilter);//更新fact中变量值
                        update(versionfix_commitversions);//更新fact中变量值
            end

            //逻辑处理节点[建立初始版本数据]
            rule "deaction1"
            ruleflow-group "versionfix_commitdeaction1"
            when
            then
                        versionservice.create(versionfix_commitdefault);
                        update(versionfix_commitdefault);//更新fact中变量值
                        update(versionfix_commitfilter);//更新fact中变量值
                        update(versionfix_commitversions);//更新fact中变量值
            end