package cn.ibizlab.plm.prodmgmt.logic.ticketlogic.activate;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket ticketactivatedefault;
                    global cn.ibizlab.plm.core.prodmgmt.service.IticketService ticketservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IticketService iBzSysTicketDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ticketactivatebegin"
            when
            then
            end

            //逻辑处理节点[设置是否归档状态]
            rule "prepareparam1"
            ruleflow-group "ticketactivateprepareparam1"
            when
            then
                            ticketactivatedefault.set("isarchived","0");
                        update(ticketactivatedefault);//更新fact中变量值
            end

            //逻辑处理节点[更新是否归档状态]
            rule "deaction1"
            ruleflow-group "ticketactivatedeaction1"
            when
            then
                        ticketservice.update(ticketactivatedefault);
                        update(ticketactivatedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ticketactivateend1"
            when
            then
                        update(ticketactivatedefault);//更新fact中变量值
            end