package cn.ibizlab.plm.prodmgmt.logic.ticketlogic.get_archived_info;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket ticketget_archived_infodefault;
                global cn.ibizlab.plm.core.base.domain.activity ticketget_archived_infoactivity_info;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket ticketget_archived_infoget_infos;
                    global cn.ibizlab.plm.core.prodmgmt.service.IticketService ticketservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IticketService iBzSysTicketDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ticketget_archived_infobegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ticketget_archived_infoend1"
            when
            then
                        update(ticketget_archived_infodefault);//更新fact中变量值
                        update(ticketget_archived_infoactivity_info);//更新fact中变量值
                        update(ticketget_archived_infoget_infos);//更新fact中变量值
            end

            //逻辑处理节点[获取详情]
            rule "deaction1"
            ruleflow-group "ticketget_archived_infodeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(ticketservice.get(ticketget_archived_infodefault.getId()),ticketget_archived_infodefault);
                        update(ticketget_archived_infodefault);//更新fact中变量值
                        update(ticketget_archived_infoactivity_info);//更新fact中变量值
                        update(ticketget_archived_infoget_infos);//更新fact中变量值
            end

            //逻辑处理节点[获取的详情信息]
            rule "debugparam2"
            ruleflow-group "ticketget_archived_infodebugparam2"
            when
            then
                        update(ticketget_archived_infodefault);//更新fact中变量值
                        update(ticketget_archived_infoactivity_info);//更新fact中变量值
                        update(ticketget_archived_infoget_infos);//更新fact中变量值
            end

            //逻辑处理节点[查询最新的一条归档信息]
            rule "rawsqlcall1"
            ruleflow-group "ticketget_archived_inforawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",ticketget_archived_infodefault.get("id"));
    String strSql="SELECT * FROM activitiy WHERE OBJECTID = #{et.param0} AND AUDITTYPE = 'archive' ORDER BY CREATE_TIME DESC LIMIT 1;";
                        java.util.List<JSONObject> entities=iBzSysTicketDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    ticketget_archived_infoactivity_info.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(ticketget_archived_infodefault);//更新fact中变量值
                        update(ticketget_archived_infoactivity_info);//更新fact中变量值
                        update(ticketget_archived_infoget_infos);//更新fact中变量值
            end

            //逻辑处理节点[拼接输出信息]
            rule "rawsfcode1"
            ruleflow-group "ticketget_archived_inforawsfcode1"
            when
            then
                        update(ticketget_archived_infodefault);//更新fact中变量值
                        update(ticketget_archived_infoactivity_info);//更新fact中变量值
                        update(ticketget_archived_infoget_infos);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "ticketget_archived_infoend2"
            when
            then
                        update(ticketget_archived_infodefault);//更新fact中变量值
                        update(ticketget_archived_infoactivity_info);//更新fact中变量值
                        update(ticketget_archived_infoget_infos);//更新fact中变量值
            end