package cn.ibizlab.plm.prodmgmt.logic.ticketlogic.get_ticket_state_pie;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket ticketget_ticket_state_piedefault;
        global cn.ibizlab.plm.core.prodmgmt.service.IticketService iBzSysTicketDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ticketget_ticket_state_piebegin"
            when
            then
            end

            //逻辑处理节点[饼图]
            rule "debugparam1"
            ruleflow-group "ticketget_ticket_state_piedebugparam1"
            when
            then
                        update(ticketget_ticket_state_piedefault);//更新fact中变量值
            end