package cn.ibizlab.plm.prodmgmt.logic.ticketlogic.mob_ticket_attention;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket ticketmob_ticket_attentiondefault;
                global cn.ibizlab.plm.core.base.domain.attention ticketmob_ticket_attentionattention;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_member ticketmob_ticket_attentionfor_obj;
                global cn.ibizlab.plm.core.prodmgmt.domain.product_member ticketmob_ticket_attentionsrfactionparam;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket ticketmob_ticket_attentionticket;
                    global cn.ibizlab.plm.core.base.service.IattentionService attentionservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IticketService iBzSysTicketDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ticketmob_ticket_attentionbegin"
            when
            then
            end

            //逻辑处理节点[获取列表]
            rule "bindparam1"
            ruleflow-group "ticketmob_ticket_attentionbindparam1"
            when
            then
                        update(ticketmob_ticket_attentiondefault);//更新fact中变量值
                        update(ticketmob_ticket_attentionattention);//更新fact中变量值
                        update(ticketmob_ticket_attentionfor_obj);//更新fact中变量值
                        update(ticketmob_ticket_attentionsrfactionparam);//更新fact中变量值
                        update(ticketmob_ticket_attentionticket);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "ticketmob_ticket_attentionloopsubcall1"
            when
            then
                        update(ticketmob_ticket_attentiondefault);//更新fact中变量值
                        update(ticketmob_ticket_attentionattention);//更新fact中变量值
                        update(ticketmob_ticket_attentionfor_obj);//更新fact中变量值
                        update(ticketmob_ticket_attentionsrfactionparam);//更新fact中变量值
                        update(ticketmob_ticket_attentionticket);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ticketmob_ticket_attentionend1"
            when
            then
                        update(ticketmob_ticket_attentiondefault);//更新fact中变量值
                        update(ticketmob_ticket_attentionattention);//更新fact中变量值
                        update(ticketmob_ticket_attentionfor_obj);//更新fact中变量值
                        update(ticketmob_ticket_attentionsrfactionparam);//更新fact中变量值
                        update(ticketmob_ticket_attentionticket);//更新fact中变量值
            end

            //逻辑处理节点[设置参数]
            rule "prepareparam1"
            ruleflow-group "ticketmob_ticket_attentionprepareparam1"
            when
            then
                            ticketmob_ticket_attentionattention.set("ownerid",ticketmob_ticket_attentiondefault.get("id"));
                            ticketmob_ticket_attentionattention.set("ownersubtype","TICKET");
                            ticketmob_ticket_attentionattention.set("ownertype","TICKET");
                            ticketmob_ticket_attentionattention.set("type","40");
                            ticketmob_ticket_attentionattention.set("userid",ticketmob_ticket_attentionfor_obj.get("userid"));
                            ticketmob_ticket_attentionattention.set("name",ticketmob_ticket_attentionfor_obj.get("name"));
                        update(ticketmob_ticket_attentiondefault);//更新fact中变量值
                        update(ticketmob_ticket_attentionattention);//更新fact中变量值
                        update(ticketmob_ticket_attentionfor_obj);//更新fact中变量值
                        update(ticketmob_ticket_attentionsrfactionparam);//更新fact中变量值
                        update(ticketmob_ticket_attentionticket);//更新fact中变量值
            end

            //逻辑处理节点[创建关注人]
            rule "deaction1"
            ruleflow-group "ticketmob_ticket_attentiondeaction1"
            when
            then
                        attentionservice.create(ticketmob_ticket_attentionattention);
                        update(ticketmob_ticket_attentiondefault);//更新fact中变量值
                        update(ticketmob_ticket_attentionattention);//更新fact中变量值
                        update(ticketmob_ticket_attentionfor_obj);//更新fact中变量值
                        update(ticketmob_ticket_attentionsrfactionparam);//更新fact中变量值
                        update(ticketmob_ticket_attentionticket);//更新fact中变量值
            end