package cn.ibizlab.plm.prodmgmt.logic.ticketlogic.recover;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.ticket ticketrecoverdefault;
                    global cn.ibizlab.plm.core.prodmgmt.service.IticketService ticketservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IticketService iBzSysTicketDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ticketrecoverbegin"
            when
            then
            end

            //逻辑处理节点[更新删除标识]
            rule "prepareparam1"
            ruleflow-group "ticketrecoverprepareparam1"
            when
            then
                            ticketrecoverdefault.set("isdeleted","0");
                        update(ticketrecoverdefault);//更新fact中变量值
            end

            //逻辑处理节点[执行更新操作]
            rule "deaction1"
            ruleflow-group "ticketrecoverdeaction1"
            when
            then
                        ticketservice.update(ticketrecoverdefault);
                        update(ticketrecoverdefault);//更新fact中变量值
            end

            //逻辑处理节点[恢复最近访问]
            rule "rawsqlcall1"
            ruleflow-group "ticketrecoverrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",ticketrecoverdefault.get("id"));
    String strSql="update recent set IS_DELETED=0 where owner_id=#{et.param0} and owner_subtype='ticket'";
                        iBzSysTicketDefaultService.execute(strSql,param);//SQL调用
                        update(ticketrecoverdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ticketrecoverend1"
            when
            then
                        update(ticketrecoverdefault);//更新fact中变量值
            end