package cn.ibizlab.plm.ai.logic.ai_kb_graph_entitylogic.graph_info;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_graph_entity ai_kb_graph_entitygraph_infodefault;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_graph_entity ai_kb_graph_entitygraph_infoentity;
                global cn.ibizlab.plm.core.ai.domain.ai_kb_graph_relation ai_kb_graph_entitygraph_inforelation;
                    global cn.ibizlab.plm.core.ai.service.Iai_kb_graph_entityService ai_kb_graph_entityservice;
                    global cn.ibizlab.plm.core.ai.service.Iai_kb_graph_relationService ai_kb_graph_relationservice;
        global cn.ibizlab.plm.core.ai.service.Iai_kb_graph_entityService iBzSysAi_kb_graph_entityDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_kb_graph_entitygraph_infobegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "ai_kb_graph_entitygraph_infoprepareparam_01"
            when
            then
                            ai_kb_graph_entitygraph_infoentity.set("id",ai_kb_graph_entitygraph_infodefault.get("ai_kb_graph_entity"));
                        update(ai_kb_graph_entitygraph_infodefault);//更新fact中变量值
                        update(ai_kb_graph_entitygraph_infoentity);//更新fact中变量值
                        update(ai_kb_graph_entitygraph_inforelation);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction_01"
            ruleflow-group "ai_kb_graph_entitygraph_infodeaction_01"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(ai_kb_graph_entityservice.get(ai_kb_graph_entitygraph_infoentity.getId()),ai_kb_graph_entitygraph_infoentity);
                        update(ai_kb_graph_entitygraph_infodefault);//更新fact中变量值
                        update(ai_kb_graph_entitygraph_infoentity);//更新fact中变量值
                        update(ai_kb_graph_entitygraph_inforelation);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_03"
            ruleflow-group "ai_kb_graph_entitygraph_infoprepareparam_03"
            when
            then
                            ai_kb_graph_entitygraph_infoentity.set("current_selected",ai_kb_graph_entitygraph_infodefault.get("current_selected"));
                        update(ai_kb_graph_entitygraph_infodefault);//更新fact中变量值
                        update(ai_kb_graph_entitygraph_infoentity);//更新fact中变量值
                        update(ai_kb_graph_entitygraph_inforelation);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_kb_graph_entitygraph_infoend_01"
            when
            then
                        update(ai_kb_graph_entitygraph_infodefault);//更新fact中变量值
                        update(ai_kb_graph_entitygraph_infoentity);//更新fact中变量值
                        update(ai_kb_graph_entitygraph_inforelation);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_02"
            ruleflow-group "ai_kb_graph_entitygraph_infoprepareparam_02"
            when
            then
                            ai_kb_graph_entitygraph_inforelation.set("id",ai_kb_graph_entitygraph_infodefault.get("ai_kb_graph_relation"));
                        update(ai_kb_graph_entitygraph_infodefault);//更新fact中变量值
                        update(ai_kb_graph_entitygraph_infoentity);//更新fact中变量值
                        update(ai_kb_graph_entitygraph_inforelation);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction_02"
            ruleflow-group "ai_kb_graph_entitygraph_infodeaction_02"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(ai_kb_graph_relationservice.get(ai_kb_graph_entitygraph_inforelation.getId()),ai_kb_graph_entitygraph_inforelation);
                        update(ai_kb_graph_entitygraph_infodefault);//更新fact中变量值
                        update(ai_kb_graph_entitygraph_infoentity);//更新fact中变量值
                        update(ai_kb_graph_entitygraph_inforelation);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_04"
            ruleflow-group "ai_kb_graph_entitygraph_infoprepareparam_04"
            when
            then
                            ai_kb_graph_entitygraph_inforelation.set("current_selected",ai_kb_graph_entitygraph_infodefault.get("current_selected"));
                        update(ai_kb_graph_entitygraph_infodefault);//更新fact中变量值
                        update(ai_kb_graph_entitygraph_infoentity);//更新fact中变量值
                        update(ai_kb_graph_entitygraph_inforelation);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_02"
            ruleflow-group "ai_kb_graph_entitygraph_infoend_02"
            when
            then
                        update(ai_kb_graph_entitygraph_infodefault);//更新fact中变量值
                        update(ai_kb_graph_entitygraph_infoentity);//更新fact中变量值
                        update(ai_kb_graph_entitygraph_inforelation);//更新fact中变量值
            end