package cn.ibizlab.plm.testmgmt.logic.test_suitelogic.sort;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.testmgmt.domain.test_suite test_suitesortdefault;
                global cn.ibizlab.plm.core.testmgmt.domain.test_suite test_suitesortfilter;
                global cn.ibizlab.plm.core.testmgmt.domain.test_suite test_suitesortpage;
                    global cn.ibizlab.plm.core.testmgmt.service.Itest_suiteService test_suiteservice;
        global cn.ibizlab.plm.core.testmgmt.service.Itest_suiteService iBzSysTest_suiteDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "test_suitesortbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "test_suitesortprepareparam1"
            when
            then
                            test_suitesortfilter.set("sort","sequence,desc");
                            test_suitesortfilter.set("n_library_id_eq",test_suitesortdefault.get("owner_id"));
                        update(test_suitesortdefault);//更新fact中变量值
                        update(test_suitesortfilter);//更新fact中变量值
                        update(test_suitesortpage);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "test_suitesortdedataset1"
            when
            then
                        update(test_suitesortdefault);//更新fact中变量值
                        update(test_suitesortfilter);//更新fact中变量值
                        update(test_suitesortpage);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode1"
            ruleflow-group "test_suitesortrawsfcode1"
            when
            then
                        update(test_suitesortdefault);//更新fact中变量值
                        update(test_suitesortfilter);//更新fact中变量值
                        update(test_suitesortpage);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "test_suitesortend1"
            when
            then
                        update(test_suitesortdefault);//更新fact中变量值
                        update(test_suitesortfilter);//更新fact中变量值
                        update(test_suitesortpage);//更新fact中变量值
            end