package cn.ibizlab.plm.prodmgmt.logic.idealogic.activate;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.Idea ideaactivatedefault;
                global java.util.Map ideaactivateid;
                global java.util.Map ideaactivateids;
                global cn.ibizlab.plm.core.prodmgmt.domain.Idea ideaactivatetemp_obj;
                    global cn.ibizlab.plm.core.prodmgmt.service.IIdeaService ideaservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IIdeaService iBzSysIdeaDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ideaactivatebegin"
            when
            then
            end

            //逻辑处理节点[拆分选中主键]
            rule "rawsfcode1"
            ruleflow-group "ideaactivaterawsfcode1"
            when
            then
                        update(ideaactivatedefault);//更新fact中变量值
                        update(ideaactivateid);//更新fact中变量值
                        update(ideaactivateids);//更新fact中变量值
                        update(ideaactivatetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "ideaactivateloopsubcall1"
            when
            then
                        update(ideaactivatedefault);//更新fact中变量值
                        update(ideaactivateid);//更新fact中变量值
                        update(ideaactivateids);//更新fact中变量值
                        update(ideaactivatetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "ideaactivaterenewparam1"
            when
            then
                        update(ideaactivatedefault);//更新fact中变量值
                        update(ideaactivateid);//更新fact中变量值
                        update(ideaactivateids);//更新fact中变量值
                        update(ideaactivatetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[设置激活状态]
            rule "prepareparam1"
            ruleflow-group "ideaactivateprepareparam1"
            when
            then
                            ideaactivatedefault.set("isarchived","0");
                        update(ideaactivatedefault);//更新fact中变量值
                        update(ideaactivateid);//更新fact中变量值
                        update(ideaactivateids);//更新fact中变量值
                        update(ideaactivatetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[修改需求激活状态]
            rule "deaction1"
            ruleflow-group "ideaactivatedeaction1"
            when
            then
                        ideaservice.update(ideaactivatedefault);
                        update(ideaactivatedefault);//更新fact中变量值
                        update(ideaactivateid);//更新fact中变量值
                        update(ideaactivateids);//更新fact中变量值
                        update(ideaactivatetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ideaactivateend1"
            when
            then
                        update(ideaactivatedefault);//更新fact中变量值
                        update(ideaactivateid);//更新fact中变量值
                        update(ideaactivateids);//更新fact中变量值
                        update(ideaactivatetemp_obj);//更新fact中变量值
            end