package cn.ibizlab.plm.prodmgmt.logic.idealogic.change_state;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideachange_statedefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideachange_statefor_temp_obj;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideachange_statesrfactionparam;
                    global cn.ibizlab.plm.core.prodmgmt.service.IideaService ideaservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IideaService iBzSysIdeaDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ideachange_statebegin"
            when
            then
            end

            //逻辑处理节点[获取传递的参数]
            rule "bindparam1"
            ruleflow-group "ideachange_statebindparam1"
            when
            then
                        update(ideachange_statedefault);//更新fact中变量值
                        update(ideachange_statefor_temp_obj);//更新fact中变量值
                        update(ideachange_statesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[循环id列表进行操作]
            rule "loopsubcall1"
            ruleflow-group "ideachange_stateloopsubcall1"
            when
            then
                        update(ideachange_statedefault);//更新fact中变量值
                        update(ideachange_statefor_temp_obj);//更新fact中变量值
                        update(ideachange_statesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[获取传递的状态]
            rule "prepareparam2"
            ruleflow-group "ideachange_stateprepareparam2"
            when
            then
                            ideachange_statedefault.set("state",ideachange_statefor_temp_obj.get("state"));
                        update(ideachange_statedefault);//更新fact中变量值
                        update(ideachange_statefor_temp_obj);//更新fact中变量值
                        update(ideachange_statesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[变更状态]
            rule "deaction1"
            ruleflow-group "ideachange_statedeaction1"
            when
            then
                        ideaservice.update(ideachange_statedefault);
                        update(ideachange_statedefault);//更新fact中变量值
                        update(ideachange_statefor_temp_obj);//更新fact中变量值
                        update(ideachange_statesrfactionparam);//更新fact中变量值
            end