package cn.ibizlab.plm.prodmgmt.logic.idealogic.choose_case_template;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideachoose_case_templatedefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea_template ideachoose_case_templatechoosed_data;
                global java.util.Map ideachoose_case_templatefor_obj;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea_template ideachoose_case_templatesrfactionparam;
                    global cn.ibizlab.plm.core.prodmgmt.service.Iidea_templateService idea_templateservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IideaService iBzSysIdeaDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ideachoose_case_templatebegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ideachoose_case_templateend1"
            when
            then
                        update(ideachoose_case_templatedefault);//更新fact中变量值
                        update(ideachoose_case_templatechoosed_data);//更新fact中变量值
                        update(ideachoose_case_templatefor_obj);//更新fact中变量值
                        update(ideachoose_case_templatesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[获取选中数据id]
            rule "prepareparam1"
            ruleflow-group "ideachoose_case_templateprepareparam1"
            when
            then
                            ideachoose_case_templatechoosed_data.set("id",ideachoose_case_templatedefault.get("choosed_data"));
                        update(ideachoose_case_templatedefault);//更新fact中变量值
                        update(ideachoose_case_templatechoosed_data);//更新fact中变量值
                        update(ideachoose_case_templatefor_obj);//更新fact中变量值
                        update(ideachoose_case_templatesrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[获取选中模板详情]
            rule "deaction1"
            ruleflow-group "ideachoose_case_templatedeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(idea_templateservice.get(ideachoose_case_templatechoosed_data.getId()),ideachoose_case_templatechoosed_data);
                        update(ideachoose_case_templatedefault);//更新fact中变量值
                        update(ideachoose_case_templatechoosed_data);//更新fact中变量值
                        update(ideachoose_case_templatefor_obj);//更新fact中变量值
                        update(ideachoose_case_templatesrfactionparam);//更新fact中变量值
            end