package cn.ibizlab.plm.prodmgmt.logic.idealogic.del_relation;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.Idea ideadel_relationdefault;
                global cn.ibizlab.plm.core.base.domain.Relation ideadel_relationforward_relation_obj;
                global cn.ibizlab.plm.core.base.domain.Relation ideadel_relationreverse_relation_obj;
                    global cn.ibizlab.plm.core.base.service.IRelationService relationservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IIdeaService iBzSysIdeaDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ideadel_relationbegin"
            when
            then
            end

            //逻辑处理节点[填充正反关联对象的主要关联属性]
            rule "prepareparam1"
            ruleflow-group "ideadel_relationprepareparam1"
            when
            then
                            ideadel_relationforward_relation_obj.set("principalid",ideadel_relationdefault.get("principal_id"));
                            ideadel_relationreverse_relation_obj.set("targetid",ideadel_relationdefault.get("principal_id"));
                            ideadel_relationreverse_relation_obj.set("principalid",ideadel_relationdefault.get("id"));
                            ideadel_relationforward_relation_obj.set("targetid",ideadel_relationdefault.get("id"));
                        update(ideadel_relationdefault);//更新fact中变量值
                        update(ideadel_relationforward_relation_obj);//更新fact中变量值
                        update(ideadel_relationreverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[拼接关联对象的主键]
            rule "rawsfcode1"
            ruleflow-group "ideadel_relationrawsfcode1"
            when
            then
                        update(ideadel_relationdefault);//更新fact中变量值
                        update(ideadel_relationforward_relation_obj);//更新fact中变量值
                        update(ideadel_relationreverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[删除正向关联]
            rule "deaction2"
            ruleflow-group "ideadel_relationdeaction2"
            when
            then
                        relationservice.remove(ideadel_relationforward_relation_obj.getId());
                        update(ideadel_relationdefault);//更新fact中变量值
                        update(ideadel_relationforward_relation_obj);//更新fact中变量值
                        update(ideadel_relationreverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[删除反向关联]
            rule "deaction3"
            ruleflow-group "ideadel_relationdeaction3"
            when
            then
                        relationservice.remove(ideadel_relationreverse_relation_obj.getId());
                        update(ideadel_relationdefault);//更新fact中变量值
                        update(ideadel_relationforward_relation_obj);//更新fact中变量值
                        update(ideadel_relationreverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ideadel_relationend1"
            when
            then
                        update(ideadel_relationdefault);//更新fact中变量值
                        update(ideadel_relationforward_relation_obj);//更新fact中变量值
                        update(ideadel_relationreverse_relation_obj);//更新fact中变量值
            end