package cn.ibizlab.plm.prodmgmt.logic.idealogic.del_relation;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.Idea ideadel_relationdefault;
                global cn.ibizlab.plm.core.base.domain.Relation ideadel_relationrelationobj;
                global cn.ibizlab.plm.core.base.domain.Relation ideadel_relationrelationobj2;
                    global cn.ibizlab.plm.core.base.service.IRelationService relationservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IIdeaService iBzSysIdeaDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ideadel_relationbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "ideadel_relationprepareparam1"
            when
            then
                            ideadel_relationrelationobj.set("principalid",ideadel_relationdefault.get("principal_id"));
                            ideadel_relationrelationobj2.set("targetid",ideadel_relationdefault.get("principal_id"));
                            ideadel_relationrelationobj2.set("principalid",ideadel_relationdefault.get("id"));
                            ideadel_relationrelationobj.set("targetid",ideadel_relationdefault.get("id"));
                        update(ideadel_relationdefault);//更新fact中变量值
                        update(ideadel_relationrelationobj);//更新fact中变量值
                        update(ideadel_relationrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[拼接关联对象的主键]
            rule "rawsfcode1"
            ruleflow-group "ideadel_relationrawsfcode1"
            when
            then
                        update(ideadel_relationdefault);//更新fact中变量值
                        update(ideadel_relationrelationobj);//更新fact中变量值
                        update(ideadel_relationrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[删除正向关联]
            rule "deaction2"
            ruleflow-group "ideadel_relationdeaction2"
            when
            then
                        relationservice.remove(ideadel_relationrelationobj.getId());
                        update(ideadel_relationdefault);//更新fact中变量值
                        update(ideadel_relationrelationobj);//更新fact中变量值
                        update(ideadel_relationrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[删除反向关联]
            rule "deaction3"
            ruleflow-group "ideadel_relationdeaction3"
            when
            then
                        relationservice.remove(ideadel_relationrelationobj2.getId());
                        update(ideadel_relationdefault);//更新fact中变量值
                        update(ideadel_relationrelationobj);//更新fact中变量值
                        update(ideadel_relationrelationobj2);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ideadel_relationend1"
            when
            then
                        update(ideadel_relationdefault);//更新fact中变量值
                        update(ideadel_relationrelationobj);//更新fact中变量值
                        update(ideadel_relationrelationobj2);//更新fact中变量值
            end