package cn.ibizlab.plm.prodmgmt.logic.idealogic.delete;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideadeletedefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideadeletefor_temp_obj;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideadeleteidea_filter;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideadeleteidea_page;
                    global cn.ibizlab.plm.core.prodmgmt.service.IideaService ideaservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IideaService iBzSysIdeaDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ideadeletebegin"
            when
            then
            end

            //逻辑处理节点[设置删除状态]
            rule "prepareparam2"
            ruleflow-group "ideadeleteprepareparam2"
            when
            then
                            ideadeletedefault.set("isdeleted","1");
                        update(ideadeletedefault);//更新fact中变量值
                        update(ideadeletefor_temp_obj);//更新fact中变量值
                        update(ideadeleteidea_filter);//更新fact中变量值
                        update(ideadeleteidea_page);//更新fact中变量值
            end

            //逻辑处理节点[更新删除状态]
            rule "deaction1"
            ruleflow-group "ideadeletedeaction1"
            when
            then
                        ideaservice.update(ideadeletedefault);
                        update(ideadeletedefault);//更新fact中变量值
                        update(ideadeletefor_temp_obj);//更新fact中变量值
                        update(ideadeleteidea_filter);//更新fact中变量值
                        update(ideadeleteidea_page);//更新fact中变量值
            end

            //逻辑处理节点[删除最近访问（逻辑）]
            rule "rawsqlcall1"
            ruleflow-group "ideadeleterawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",ideadeletedefault.get("id"));
    String strSql="update recent set IS_DELETED=1 where owner_id=#{et.param0} and owner_subtype='idea'";
                        iBzSysIdeaDefaultService.execute(strSql,param);//SQL调用
                        update(ideadeletedefault);//更新fact中变量值
                        update(ideadeletefor_temp_obj);//更新fact中变量值
                        update(ideadeleteidea_filter);//更新fact中变量值
                        update(ideadeleteidea_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ideadeleteend1"
            when
            then
                        update(ideadeletedefault);//更新fact中变量值
                        update(ideadeletefor_temp_obj);//更新fact中变量值
                        update(ideadeleteidea_filter);//更新fact中变量值
                        update(ideadeleteidea_page);//更新fact中变量值
            end