package cn.ibizlab.plm.prodmgmt.logic.idealogic.idea_re_section;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.Idea ideaidea_re_sectiondefault;
                global cn.ibizlab.plm.core.base.domain.Category ideaidea_re_sectioncategory;
                global cn.ibizlab.plm.core.base.domain.Section ideaidea_re_sectionsection;
                    global cn.ibizlab.plm.core.base.service.ICategoryService categoryservice;
                    global cn.ibizlab.plm.core.base.service.ISectionService sectionservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IIdeaService iBzSysIdeaDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ideaidea_re_sectionbegin"
            when
            then
            end

            //逻辑处理节点[获取模块id]
            rule "prepareparam1"
            ruleflow-group "ideaidea_re_sectionprepareparam1"
            when
            then
                            ideaidea_re_sectioncategory.set("id",ideaidea_re_sectiondefault.get("suite"));
                        update(ideaidea_re_sectiondefault);//更新fact中变量值
                        update(ideaidea_re_sectioncategory);//更新fact中变量值
                        update(ideaidea_re_sectionsection);//更新fact中变量值
            end

            //逻辑处理节点[根据模块id查询模块信息]
            rule "deaction1"
            ruleflow-group "ideaidea_re_sectiondeaction1"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(categoryservice.get(ideaidea_re_sectioncategory.getId()),ideaidea_re_sectioncategory);
                        update(ideaidea_re_sectiondefault);//更新fact中变量值
                        update(ideaidea_re_sectioncategory);//更新fact中变量值
                        update(ideaidea_re_sectionsection);//更新fact中变量值
            end

            //逻辑处理节点[获取模块信息内的子产品id]
            rule "prepareparam2"
            ruleflow-group "ideaidea_re_sectionprepareparam2"
            when
            then
                            ideaidea_re_sectionsection.set("id",ideaidea_re_sectioncategory.get("sectionid"));
                        update(ideaidea_re_sectiondefault);//更新fact中变量值
                        update(ideaidea_re_sectioncategory);//更新fact中变量值
                        update(ideaidea_re_sectionsection);//更新fact中变量值
            end

            //逻辑处理节点[根据子产品id查询子产品信息]
            rule "deaction2"
            ruleflow-group "ideaidea_re_sectiondeaction2"
            when
            then
                            cn.ibizlab.plm.util.helper.CachedBeanCopier.copy(sectionservice.get(ideaidea_re_sectionsection.getId()),ideaidea_re_sectionsection);
                        update(ideaidea_re_sectiondefault);//更新fact中变量值
                        update(ideaidea_re_sectioncategory);//更新fact中变量值
                        update(ideaidea_re_sectionsection);//更新fact中变量值
            end

            //逻辑处理节点[获取子产品名称给需求]
            rule "prepareparam3"
            ruleflow-group "ideaidea_re_sectionprepareparam3"
            when
            then
                            ideaidea_re_sectiondefault.set("sectionname",ideaidea_re_sectionsection.get("name"));
                        update(ideaidea_re_sectiondefault);//更新fact中变量值
                        update(ideaidea_re_sectioncategory);//更新fact中变量值
                        update(ideaidea_re_sectionsection);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end2"
            ruleflow-group "ideaidea_re_sectionend2"
            when
            then
                        update(ideaidea_re_sectiondefault);//更新fact中变量值
                        update(ideaidea_re_sectioncategory);//更新fact中变量值
                        update(ideaidea_re_sectionsection);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ideaidea_re_sectionend1"
            when
            then
                        update(ideaidea_re_sectiondefault);//更新fact中变量值
                        update(ideaidea_re_sectioncategory);//更新fact中变量值
                        update(ideaidea_re_sectionsection);//更新fact中变量值
            end