package cn.ibizlab.plm.prodmgmt.logic.idealogic.idea_archive;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.Idea ideaidea_archivedefault;
                global java.util.Map ideaidea_archiveid;
                global java.util.Map ideaidea_archiveids;
                global cn.ibizlab.plm.core.prodmgmt.domain.Idea ideaidea_archivetemp_obj;
                    global cn.ibizlab.plm.core.prodmgmt.service.IIdeaService ideaservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IIdeaService iBzSysIdeaDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ideaidea_archivebegin"
            when
            then
            end

            //逻辑处理节点[拆分选中主键]
            rule "rawsfcode1"
            ruleflow-group "ideaidea_archiverawsfcode1"
            when
            then
                        update(ideaidea_archivedefault);//更新fact中变量值
                        update(ideaidea_archiveid);//更新fact中变量值
                        update(ideaidea_archiveids);//更新fact中变量值
                        update(ideaidea_archivetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "ideaidea_archiveloopsubcall1"
            when
            then
                        update(ideaidea_archivedefault);//更新fact中变量值
                        update(ideaidea_archiveid);//更新fact中变量值
                        update(ideaidea_archiveids);//更新fact中变量值
                        update(ideaidea_archivetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "ideaidea_archiverenewparam1"
            when
            then
                        update(ideaidea_archivedefault);//更新fact中变量值
                        update(ideaidea_archiveid);//更新fact中变量值
                        update(ideaidea_archiveids);//更新fact中变量值
                        update(ideaidea_archivetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "ideaidea_archiveprepareparam1"
            when
            then
                            ideaidea_archivedefault.set("isarchived","1");
                        update(ideaidea_archivedefault);//更新fact中变量值
                        update(ideaidea_archiveid);//更新fact中变量值
                        update(ideaidea_archiveids);//更新fact中变量值
                        update(ideaidea_archivetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[update]
            rule "deaction1"
            ruleflow-group "ideaidea_archivedeaction1"
            when
            then
                        ideaservice.update(ideaidea_archivedefault);
                        update(ideaidea_archivedefault);//更新fact中变量值
                        update(ideaidea_archiveid);//更新fact中变量值
                        update(ideaidea_archiveids);//更新fact中变量值
                        update(ideaidea_archivetemp_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ideaidea_archiveend1"
            when
            then
                        update(ideaidea_archivedefault);//更新fact中变量值
                        update(ideaidea_archiveid);//更新fact中变量值
                        update(ideaidea_archiveids);//更新fact中变量值
                        update(ideaidea_archivetemp_obj);//更新fact中变量值
            end