package cn.ibizlab.plm.prodmgmt.logic.idealogic.plan_delete_idea;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideaplan_delete_ideadefault;
                global cn.ibizlab.plm.core.base.domain.relation ideaplan_delete_ideaforward_relation_obj;
                global cn.ibizlab.plm.core.base.domain.relation ideaplan_delete_ideareverse_relation_obj;
                    global cn.ibizlab.plm.core.base.service.IrelationService relationservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IideaService iBzSysIdeaDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ideaplan_delete_ideabegin"
            when
            then
            end

            //逻辑处理节点[填充正反关联对象的主要关联属性]
            rule "prepareparam1"
            ruleflow-group "ideaplan_delete_ideaprepareparam1"
            when
            then
                            ideaplan_delete_ideaforward_relation_obj.set("principalid",ideaplan_delete_ideadefault.get("principal_id"));
                            ideaplan_delete_ideareverse_relation_obj.set("targetid",ideaplan_delete_ideadefault.get("principal_id"));
                            ideaplan_delete_ideareverse_relation_obj.set("principalid",ideaplan_delete_ideadefault.get("id"));
                            ideaplan_delete_ideaforward_relation_obj.set("targetid",ideaplan_delete_ideadefault.get("id"));
                        update(ideaplan_delete_ideadefault);//更新fact中变量值
                        update(ideaplan_delete_ideaforward_relation_obj);//更新fact中变量值
                        update(ideaplan_delete_ideareverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[拼接正反关联对象的主键]
            rule "rawsfcode1"
            ruleflow-group "ideaplan_delete_idearawsfcode1"
            when
            then
                        update(ideaplan_delete_ideadefault);//更新fact中变量值
                        update(ideaplan_delete_ideaforward_relation_obj);//更新fact中变量值
                        update(ideaplan_delete_ideareverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[删除正向关联]
            rule "deaction2"
            ruleflow-group "ideaplan_delete_ideadeaction2"
            when
            then
                        relationservice.remove(ideaplan_delete_ideaforward_relation_obj.getId());
                        update(ideaplan_delete_ideadefault);//更新fact中变量值
                        update(ideaplan_delete_ideaforward_relation_obj);//更新fact中变量值
                        update(ideaplan_delete_ideareverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[删除反向关联]
            rule "deaction3"
            ruleflow-group "ideaplan_delete_ideadeaction3"
            when
            then
                        relationservice.remove(ideaplan_delete_ideareverse_relation_obj.getId());
                        update(ideaplan_delete_ideadefault);//更新fact中变量值
                        update(ideaplan_delete_ideaforward_relation_obj);//更新fact中变量值
                        update(ideaplan_delete_ideareverse_relation_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ideaplan_delete_ideaend1"
            when
            then
                        update(ideaplan_delete_ideadefault);//更新fact中变量值
                        update(ideaplan_delete_ideaforward_relation_obj);//更新fact中变量值
                        update(ideaplan_delete_ideareverse_relation_obj);//更新fact中变量值
            end