package cn.ibizlab.plm.prodmgmt.logic.idealogic.product_idea_re_counters;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.idea ideaproduct_idea_re_countersdefault;
        global cn.ibizlab.plm.core.prodmgmt.service.IideaService iBzSysIdeaDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ideaproduct_idea_re_countersbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ideaproduct_idea_re_countersend1"
            when
            then
                        update(ideaproduct_idea_re_countersdefault);//更新fact中变量值
            end

            //逻辑处理节点[需求关联客户]
            rule "rawsqlcall1"
            ruleflow-group "ideaproduct_idea_re_countersrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",ideaproduct_idea_re_countersdefault.get("id"));
    String strSql="-- 需求关联客户 SELECT 	count( t.id ) AS idea_re_customer  FROM 	customer t  WHERE 	EXISTS ( 	SELECT 		*  	FROM 		`RELATION` t11  	WHERE 		t.`ID` = t11.`TARGET_ID`  		AND ( 			t11.`TARGET_TYPE` = 'customer'  			AND t11.`PRINCIPAL_TYPE` = 'idea'  			AND t11.`PRINCIPAL_ID` = #{et.param0} ) ) 			AND t.`is_archived` = 0";
                        java.util.List<JSONObject> entities=iBzSysIdeaDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    ideaproduct_idea_re_countersdefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(ideaproduct_idea_re_countersdefault);//更新fact中变量值
            end

            //逻辑处理节点[需求关联需求]
            rule "rawsqlcall2"
            ruleflow-group "ideaproduct_idea_re_countersrawsqlcall2"
            when
            then
    Map param =new HashMap();
        param.put("param0",ideaproduct_idea_re_countersdefault.get("id"));
    String strSql="-- 需求 SELECT 	count( t.id ) AS idea_re_idea  FROM 	idea t  WHERE 	EXISTS ( 	SELECT 		*  	FROM 		`RELATION` t11  	WHERE 		t.`ID` = t11.`TARGET_ID`  		AND ( t11.`PRINCIPAL_ID` = #{et.param0} AND t11.`TARGET_TYPE` = 'idea' AND t11.`PRINCIPAL_TYPE` = 'idea' )  	)  AND t.IS_DELETED = 0 	";
                        java.util.List<JSONObject> entities=iBzSysIdeaDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    ideaproduct_idea_re_countersdefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(ideaproduct_idea_re_countersdefault);//更新fact中变量值
            end

            //逻辑处理节点[需求关联工单]
            rule "rawsqlcall3"
            ruleflow-group "ideaproduct_idea_re_countersrawsqlcall3"
            when
            then
    Map param =new HashMap();
        param.put("param0",ideaproduct_idea_re_countersdefault.get("id"));
    String strSql="-- 工单 SELECT 	count( t.id ) AS idea_re_ticket  FROM 	ticket t  WHERE 	EXISTS ( 	SELECT 		*  	FROM 		`RELATION` t11  	WHERE 		t.`ID` = t11.`TARGET_ID`  		AND ( t11.`PRINCIPAL_ID` = #{et.param0} AND t11.`TARGET_TYPE` = 'ticket' AND t11.`PRINCIPAL_TYPE` = 'idea' )  	)  	AND t.`IS_DELETED` = 0";
                        java.util.List<JSONObject> entities=iBzSysIdeaDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    ideaproduct_idea_re_countersdefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(ideaproduct_idea_re_countersdefault);//更新fact中变量值
            end

            //逻辑处理节点[需求关联工作项]
            rule "rawsqlcall4"
            ruleflow-group "ideaproduct_idea_re_countersrawsqlcall4"
            when
            then
    Map param =new HashMap();
        param.put("param0",ideaproduct_idea_re_countersdefault.get("id"));
    String strSql="-- 工作项 SELECT 	count( t.id ) AS idea_re_work_item  FROM 	work_item t  WHERE 	EXISTS ( 	SELECT 		*  	FROM 		`RELATION` t11  	WHERE 		t.`ID` = t11.`TARGET_ID`  		AND ( t11.`PRINCIPAL_ID` = #{et.param0} AND t11.`TARGET_TYPE` = 'work_item' AND t11.`PRINCIPAL_TYPE` = 'idea' )  	)  	AND t.`IS_DELETED` = 0";
                        java.util.List<JSONObject> entities=iBzSysIdeaDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    ideaproduct_idea_re_countersdefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(ideaproduct_idea_re_countersdefault);//更新fact中变量值
            end

            //逻辑处理节点[需求关联测试用例]
            rule "rawsqlcall5"
            ruleflow-group "ideaproduct_idea_re_countersrawsqlcall5"
            when
            then
    Map param =new HashMap();
        param.put("param0",ideaproduct_idea_re_countersdefault.get("id"));
    String strSql="-- 测试用例 SELECT 	count( t.id ) AS idea_re_test_case FROM 	test_case t  WHERE 	EXISTS ( 	SELECT 		*  	FROM 		`RELATION` t11  	WHERE 		t.`ID` = t11.`TARGET_ID`  		AND ( t11.`PRINCIPAL_ID` = #{et.param0} AND t11.`TARGET_TYPE` = 'test_case' AND t11.`PRINCIPAL_TYPE` = 'idea' )  	)  	AND t.`IS_DELETED` = 0";
                        java.util.List<JSONObject> entities=iBzSysIdeaDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    ideaproduct_idea_re_countersdefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(ideaproduct_idea_re_countersdefault);//更新fact中变量值
            end