package cn.ibizlab.plm.prodmgmt.logic.idealogic.recover;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.prodmgmt.domain.Idea idearecoverdefault;
                global cn.ibizlab.plm.core.prodmgmt.domain.Idea idearecoverfor_temp_obj;
                global cn.ibizlab.plm.core.prodmgmt.domain.Idea idearecoveridea_filter;
                global cn.ibizlab.plm.core.prodmgmt.domain.Idea idearecoveridea_page;
                    global cn.ibizlab.plm.core.prodmgmt.service.IIdeaService ideaservice;
        global cn.ibizlab.plm.core.prodmgmt.service.IIdeaService iBzSysIdeaDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "idearecoverbegin"
            when
            then
            end

            //逻辑处理节点[设置删除状态]
            rule "prepareparam2"
            ruleflow-group "idearecoverprepareparam2"
            when
            then
                            idearecoverdefault.set("isdeleted","0");
                        update(idearecoverdefault);//更新fact中变量值
                        update(idearecoverfor_temp_obj);//更新fact中变量值
                        update(idearecoveridea_filter);//更新fact中变量值
                        update(idearecoveridea_page);//更新fact中变量值
            end

            //逻辑处理节点[更新删除状态]
            rule "deaction1"
            ruleflow-group "idearecoverdeaction1"
            when
            then
                        ideaservice.update(idearecoverdefault);
                        update(idearecoverdefault);//更新fact中变量值
                        update(idearecoverfor_temp_obj);//更新fact中变量值
                        update(idearecoveridea_filter);//更新fact中变量值
                        update(idearecoveridea_page);//更新fact中变量值
            end

            //逻辑处理节点[恢复最近访问]
            rule "rawsqlcall1"
            ruleflow-group "idearecoverrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",idearecoverdefault.get("id"));
    String strSql="update recent set IS_DELETED=0 where owner_id=#{et.param0} and owner_subtype='idea'";
                        iBzSysIdeaDefaultService.execute(strSql,param);//SQL调用
                        update(idearecoverdefault);//更新fact中变量值
                        update(idearecoverfor_temp_obj);//更新fact中变量值
                        update(idearecoveridea_filter);//更新fact中变量值
                        update(idearecoveridea_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "idearecoverend1"
            when
            then
                        update(idearecoverdefault);//更新fact中变量值
                        update(idearecoverfor_temp_obj);//更新fact中变量值
                        update(idearecoveridea_filter);//更新fact中变量值
                        update(idearecoveridea_page);//更新fact中变量值
            end