package cn.ibizlab.plm.team.logic.discuss_memberlogic.mob_create_topic_member;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.team.domain.discuss_member discuss_membermob_create_topic_memberdefault;
                global cn.ibizlab.plm.core.base.domain.user discuss_membermob_create_topic_memberfor_temp_obj;
                global cn.ibizlab.plm.core.team.domain.discuss_member discuss_membermob_create_topic_membermember_obj;
                global cn.ibizlab.plm.core.base.domain.user discuss_membermob_create_topic_memberselectdata;
                    global cn.ibizlab.plm.core.team.service.Idiscuss_memberService discuss_memberservice;
        global cn.ibizlab.plm.core.team.service.Idiscuss_memberService iBzSysDiscuss_memberDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_membermob_create_topic_memberbegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "discuss_membermob_create_topic_memberbindparam1"
            when
            then
                        update(discuss_membermob_create_topic_memberdefault);//更新fact中变量值
                        update(discuss_membermob_create_topic_memberfor_temp_obj);//更新fact中变量值
                        update(discuss_membermob_create_topic_membermember_obj);//更新fact中变量值
                        update(discuss_membermob_create_topic_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "discuss_membermob_create_topic_memberloopsubcall1"
            when
            then
                        update(discuss_membermob_create_topic_memberdefault);//更新fact中变量值
                        update(discuss_membermob_create_topic_memberfor_temp_obj);//更新fact中变量值
                        update(discuss_membermob_create_topic_membermember_obj);//更新fact中变量值
                        update(discuss_membermob_create_topic_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "discuss_membermob_create_topic_memberrenewparam1"
            when
            then
                        update(discuss_membermob_create_topic_memberdefault);//更新fact中变量值
                        update(discuss_membermob_create_topic_memberfor_temp_obj);//更新fact中变量值
                        update(discuss_membermob_create_topic_membermember_obj);//更新fact中变量值
                        update(discuss_membermob_create_topic_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[填充话题成员属性]
            rule "prepareparam1"
            ruleflow-group "discuss_membermob_create_topic_memberprepareparam1"
            when
            then
                            discuss_membermob_create_topic_membermember_obj.set("userid",discuss_membermob_create_topic_memberfor_temp_obj.get("userid"));
                            discuss_membermob_create_topic_membermember_obj.set("name",discuss_membermob_create_topic_memberfor_temp_obj.get("displayname"));
                            discuss_membermob_create_topic_membermember_obj.set("ownerid",discuss_membermob_create_topic_memberdefault.get("ownerid"));
                        update(discuss_membermob_create_topic_memberdefault);//更新fact中变量值
                        update(discuss_membermob_create_topic_memberfor_temp_obj);//更新fact中变量值
                        update(discuss_membermob_create_topic_membermember_obj);//更新fact中变量值
                        update(discuss_membermob_create_topic_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "discuss_membermob_create_topic_memberprepareparam2"
            when
            then
                            discuss_membermob_create_topic_membermember_obj.set("userid",discuss_membermob_create_topic_memberfor_temp_obj.get("id"));
                        update(discuss_membermob_create_topic_memberdefault);//更新fact中变量值
                        update(discuss_membermob_create_topic_memberfor_temp_obj);//更新fact中变量值
                        update(discuss_membermob_create_topic_membermember_obj);//更新fact中变量值
                        update(discuss_membermob_create_topic_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[建立话题成员]
            rule "deaction1"
            ruleflow-group "discuss_membermob_create_topic_memberdeaction1"
            when
            then
                        discuss_memberservice.create(discuss_membermob_create_topic_membermember_obj);
                        update(discuss_membermob_create_topic_memberdefault);//更新fact中变量值
                        update(discuss_membermob_create_topic_memberfor_temp_obj);//更新fact中变量值
                        update(discuss_membermob_create_topic_membermember_obj);//更新fact中变量值
                        update(discuss_membermob_create_topic_memberselectdata);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "discuss_membermob_create_topic_memberend1"
            when
            then
                        update(discuss_membermob_create_topic_memberdefault);//更新fact中变量值
                        update(discuss_membermob_create_topic_memberfor_temp_obj);//更新fact中变量值
                        update(discuss_membermob_create_topic_membermember_obj);//更新fact中变量值
                        update(discuss_membermob_create_topic_memberselectdata);//更新fact中变量值
            end