package cn.ibizlab.plm.base.logic.attentionlogic.un_attention;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.base.domain.attention attentionun_attentiondefault;
                    global cn.ibizlab.plm.core.base.service.IattentionService attentionservice;
        global cn.ibizlab.plm.core.base.service.IattentionService iBzSysAttentionDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attentionun_attentionbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "attentionun_attentionend1"
            when
            then
                        update(attentionun_attentiondefault);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "attentionun_attentiondebugparam1"
            when
            then
                        update(attentionun_attentiondefault);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "attentionun_attentiondeaction1"
            when
            then
                        attentionservice.remove(attentionun_attentiondefault.getId());
                        update(attentionun_attentiondefault);//更新fact中变量值
            end