global cn.ibizlab.plm.core.extension.service.IPSDEFieldService  psdefieldService;
global cn.ibizlab.plm.core.extension.domain.PSDEField et;

    no-loop

    rule "psdefieldapply"
    ruleflow-group "5b457698d99df93edf02f7b0abdbcbc1"
    when
    then
    cn.ibizlab.plm.core.extension.domain.PSDEField actionLogicDE =new cn.ibizlab.plm.core.extension.domain.PSDEField();
    et.copyTo(actionLogicDE,true);
    psdefieldService.apply(actionLogicDE);
    end