global cn.ibizlab.plm.core.extension.service.IPSDEFieldService  psdefieldService;
global cn.ibizlab.plm.core.extension.domain.PSDEField et;

    no-loop

    rule "psdefieldapply"
    ruleflow-group "d027ece0e3d3d047844f1941cd049f68"
    when
    then
    cn.ibizlab.plm.core.extension.domain.PSDEField actionLogicDE =new cn.ibizlab.plm.core.extension.domain.PSDEField();
    et.copyTo(actionLogicDE,true);
    psdefieldService.apply(actionLogicDE);
    end