package cn.ibizlab.plm.wiki.logic.spacelogic.activate;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.Space spaceactivatedefault;
                global cn.ibizlab.plm.core.wiki.domain.Space spaceactivateupdate_obj;
                    global cn.ibizlab.plm.core.wiki.service.ISpaceService spaceservice;
        global cn.ibizlab.plm.core.wiki.service.ISpaceService iBzSysSpaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "spaceactivatebegin"
            when
            then
            end

            //逻辑处理节点[设置归档状态]
            rule "prepareparam1"
            ruleflow-group "spaceactivateprepareparam1"
            when
            then
                            spaceactivateupdate_obj.set("isarchived","0");
                            spaceactivateupdate_obj.set("id",spaceactivatedefault.get("id"));
                        update(spaceactivatedefault);//更新fact中变量值
                        update(spaceactivateupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[激活]
            rule "deaction1"
            ruleflow-group "spaceactivatedeaction1"
            when
            then
                        spaceservice.update(spaceactivateupdate_obj);
                        update(spaceactivatedefault);//更新fact中变量值
                        update(spaceactivateupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "spaceactivateend1"
            when
            then
                        update(spaceactivatedefault);//更新fact中变量值
                        update(spaceactivateupdate_obj);//更新fact中变量值
            end