package cn.ibizlab.plm.wiki.logic.spacelogic.archive;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.Space spacearchivedefault;
                global cn.ibizlab.plm.core.wiki.domain.Space spacearchiveupdate_obj;
                    global cn.ibizlab.plm.core.wiki.service.ISpaceService spaceservice;
        global cn.ibizlab.plm.core.wiki.service.ISpaceService iBzSysSpaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "spacearchivebegin"
            when
            then
            end

            //逻辑处理节点[设置已归档状态]
            rule "prepareparam1"
            ruleflow-group "spacearchiveprepareparam1"
            when
            then
                            spacearchiveupdate_obj.set("isarchived","1");
                            spacearchiveupdate_obj.set("id",spacearchivedefault.get("id"));
                        update(spacearchivedefault);//更新fact中变量值
                        update(spacearchiveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[归档]
            rule "deaction1"
            ruleflow-group "spacearchivedeaction1"
            when
            then
                        spaceservice.update(spacearchiveupdate_obj);
                        update(spacearchivedefault);//更新fact中变量值
                        update(spacearchiveupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "spacearchiveend1"
            when
            then
                        update(spacearchivedefault);//更新fact中变量值
                        update(spacearchiveupdate_obj);//更新fact中变量值
            end