package cn.ibizlab.plm.wiki.logic.spacelogic.auto_create_members;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.space spaceauto_create_membersdefault;
                global cn.ibizlab.plm.core.base.domain.member spaceauto_create_membersmember;
                global cn.ibizlab.plm.core.base.domain.member spaceauto_create_membersmember_obj;
                global cn.ibizlab.plm.core.base.domain.member spaceauto_create_membersmember_page;
                global cn.ibizlab.plm.core.wiki.domain.space_member spaceauto_create_membersspace_member;
                    global cn.ibizlab.plm.core.wiki.service.Ispace_memberService space_memberservice;
                    global cn.ibizlab.plm.core.base.service.ImemberService memberservice;
        global cn.ibizlab.plm.core.wiki.service.IspaceService iBzSysSpaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "spaceauto_create_membersbegin"
            when
            then
            end

            //逻辑处理节点[准备生成用户数据]
            rule "prepareparam3"
            ruleflow-group "spaceauto_create_membersprepareparam3"
            when
            then
                            spaceauto_create_membersspace_member.set("spaceid",spaceauto_create_membersdefault.get("id"));
                                spaceauto_create_membersspace_member.set("userid",curuser.getSessionParams().get("srfpersonid"));
                                spaceauto_create_membersspace_member.set("name",curuser.getSessionParams().get("srfpersonname"));
                        update(spaceauto_create_membersdefault);//更新fact中变量值
                        update(spaceauto_create_membersmember);//更新fact中变量值
                        update(spaceauto_create_membersmember_obj);//更新fact中变量值
                        update(spaceauto_create_membersmember_page);//更新fact中变量值
                        update(spaceauto_create_membersspace_member);//更新fact中变量值
            end

            //逻辑处理节点[准备查询参数]
            rule "prepareparam2"
            ruleflow-group "spaceauto_create_membersprepareparam2"
            when
            then
                            spaceauto_create_membersmember.set("n_owner_id_eq",spaceauto_create_membersdefault.get("scopeid"));
                            spaceauto_create_membersmember.set("n_owner_type_eq","GROUP");
                        update(spaceauto_create_membersdefault);//更新fact中变量值
                        update(spaceauto_create_membersmember);//更新fact中变量值
                        update(spaceauto_create_membersmember_obj);//更新fact中变量值
                        update(spaceauto_create_membersmember_page);//更新fact中变量值
                        update(spaceauto_create_membersspace_member);//更新fact中变量值
            end

            //逻辑处理节点[生成用户数据]
            rule "deaction2"
            ruleflow-group "spaceauto_create_membersdeaction2"
            when
            then
                        space_memberservice.create(spaceauto_create_membersspace_member);
                        update(spaceauto_create_membersdefault);//更新fact中变量值
                        update(spaceauto_create_membersmember);//更新fact中变量值
                        update(spaceauto_create_membersmember_obj);//更新fact中变量值
                        update(spaceauto_create_membersmember_page);//更新fact中变量值
                        update(spaceauto_create_membersspace_member);//更新fact中变量值
            end

            //逻辑处理节点[查询用户数据]
            rule "dedataset1"
            ruleflow-group "spaceauto_create_membersdedataset1"
            when
            then
                        update(spaceauto_create_membersdefault);//更新fact中变量值
                        update(spaceauto_create_membersmember);//更新fact中变量值
                        update(spaceauto_create_membersmember_obj);//更新fact中变量值
                        update(spaceauto_create_membersmember_page);//更新fact中变量值
                        update(spaceauto_create_membersspace_member);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "spaceauto_create_membersloopsubcall1"
            when
            then
                        update(spaceauto_create_membersdefault);//更新fact中变量值
                        update(spaceauto_create_membersmember);//更新fact中变量值
                        update(spaceauto_create_membersmember_obj);//更新fact中变量值
                        update(spaceauto_create_membersmember_page);//更新fact中变量值
                        update(spaceauto_create_membersspace_member);//更新fact中变量值
            end

            //逻辑处理节点[重置参数]
            rule "resetparam1"
            ruleflow-group "spaceauto_create_membersresetparam1"
            when
            then
                        update(spaceauto_create_membersdefault);//更新fact中变量值
                        update(spaceauto_create_membersmember);//更新fact中变量值
                        update(spaceauto_create_membersmember_obj);//更新fact中变量值
                        update(spaceauto_create_membersmember_page);//更新fact中变量值
                        update(spaceauto_create_membersspace_member);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam4"
            ruleflow-group "spaceauto_create_membersprepareparam4"
            when
            then
                            spaceauto_create_membersspace_member.set("spaceid",spaceauto_create_membersdefault.get("id"));
                            spaceauto_create_membersspace_member.set("name",spaceauto_create_membersmember_obj.get("name"));
                            spaceauto_create_membersspace_member.set("userid",spaceauto_create_membersmember_obj.get("userid"));
                            spaceauto_create_membersspace_member.set("roleid",spaceauto_create_membersmember_obj.get("roleid"));
                        update(spaceauto_create_membersdefault);//更新fact中变量值
                        update(spaceauto_create_membersmember);//更新fact中变量值
                        update(spaceauto_create_membersmember_obj);//更新fact中变量值
                        update(spaceauto_create_membersmember_page);//更新fact中变量值
                        update(spaceauto_create_membersspace_member);//更新fact中变量值
            end

            //逻辑处理节点[生成用户数据]
            rule "deaction3"
            ruleflow-group "spaceauto_create_membersdeaction3"
            when
            then
                        space_memberservice.create(spaceauto_create_membersspace_member);
                        update(spaceauto_create_membersdefault);//更新fact中变量值
                        update(spaceauto_create_membersmember);//更新fact中变量值
                        update(spaceauto_create_membersmember_obj);//更新fact中变量值
                        update(spaceauto_create_membersmember_page);//更新fact中变量值
                        update(spaceauto_create_membersspace_member);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "spaceauto_create_membersend1"
            when
            then
                        update(spaceauto_create_membersdefault);//更新fact中变量值
                        update(spaceauto_create_membersmember);//更新fact中变量值
                        update(spaceauto_create_membersmember_obj);//更新fact中变量值
                        update(spaceauto_create_membersmember_page);//更新fact中变量值
                        update(spaceauto_create_membersspace_member);//更新fact中变量值
            end