package cn.ibizlab.plm.wiki.logic.spacelogic.before_create;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.Space spacebefore_createdefault;
                global cn.ibizlab.plm.core.wiki.domain.Space_member spacebefore_createmember;
                global cn.ibizlab.plm.core.wiki.domain.Space_member spacebefore_createmembers;
        global cn.ibizlab.plm.core.wiki.service.ISpaceService iBzSysSpaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "spacebefore_createbegin"
            when
            then
            end

            //逻辑处理节点[绑定members]
            rule "bindparam1"
            ruleflow-group "spacebefore_createbindparam1"
            when
            then
                        update(spacebefore_createdefault);//更新fact中变量值
                        update(spacebefore_createmember);//更新fact中变量值
                        update(spacebefore_createmembers);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "spacebefore_createend1"
            when
            then
                        update(spacebefore_createdefault);//更新fact中变量值
                        update(spacebefore_createmember);//更新fact中变量值
                        update(spacebefore_createmembers);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "spacebefore_createloopsubcall1"
            when
            then
                        update(spacebefore_createdefault);//更新fact中变量值
                        update(spacebefore_createmember);//更新fact中变量值
                        update(spacebefore_createmembers);//更新fact中变量值
            end

            //逻辑处理节点[重置id]
            rule "prepareparam1"
            ruleflow-group "spacebefore_createprepareparam1"
            when
            then
                                spacebefore_createmember.set("id",null);
                        update(spacebefore_createdefault);//更新fact中变量值
                        update(spacebefore_createmember);//更新fact中变量值
                        update(spacebefore_createmembers);//更新fact中变量值
            end