package cn.ibizlab.plm.wiki.logic.spacelogic.change_admin_role;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.space spacechange_admin_roledefault;
                global cn.ibizlab.plm.core.base.domain.user spacechange_admin_rolefor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.user spacechange_admin_roleselectdata;
                global cn.ibizlab.plm.core.wiki.domain.space_member spacechange_admin_roleupdate_member_info;
                    global cn.ibizlab.plm.core.wiki.service.Ispace_memberService space_memberservice;
        global cn.ibizlab.plm.core.wiki.service.IspaceService iBzSysSpaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "spacechange_admin_rolebegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "spacechange_admin_rolebindparam1"
            when
            then
                        update(spacechange_admin_roledefault);//更新fact中变量值
                        update(spacechange_admin_rolefor_temp_obj);//更新fact中变量值
                        update(spacechange_admin_roleselectdata);//更新fact中变量值
                        update(spacechange_admin_roleupdate_member_info);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "spacechange_admin_roleloopsubcall1"
            when
            then
                        update(spacechange_admin_roledefault);//更新fact中变量值
                        update(spacechange_admin_rolefor_temp_obj);//更新fact中变量值
                        update(spacechange_admin_roleselectdata);//更新fact中变量值
                        update(spacechange_admin_roleupdate_member_info);//更新fact中变量值
            end

            //逻辑处理节点[重新建立更新成员信息参数]
            rule "renewparam4"
            ruleflow-group "spacechange_admin_rolerenewparam4"
            when
            then
                        update(spacechange_admin_roledefault);//更新fact中变量值
                        update(spacechange_admin_rolefor_temp_obj);//更新fact中变量值
                        update(spacechange_admin_roleselectdata);//更新fact中变量值
                        update(spacechange_admin_roleupdate_member_info);//更新fact中变量值
            end

            //逻辑处理节点[准备更新管理员身份]
            rule "prepareparam2"
            ruleflow-group "spacechange_admin_roleprepareparam2"
            when
            then
                            spacechange_admin_roleupdate_member_info.set("userid",spacechange_admin_rolefor_temp_obj.get("id"));
                            spacechange_admin_roleupdate_member_info.set("roleid","admin");
                            spacechange_admin_roleupdate_member_info.set("spaceid",spacechange_admin_roledefault.get("id"));
                        update(spacechange_admin_roledefault);//更新fact中变量值
                        update(spacechange_admin_rolefor_temp_obj);//更新fact中变量值
                        update(spacechange_admin_roleselectdata);//更新fact中变量值
                        update(spacechange_admin_roleupdate_member_info);//更新fact中变量值
            end

            //逻辑处理节点[更新管理员身份]
            rule "deaction1"
            ruleflow-group "spacechange_admin_roledeaction1"
            when
            then
                        space_memberservice.save(spacechange_admin_roleupdate_member_info);
                        update(spacechange_admin_roledefault);//更新fact中变量值
                        update(spacechange_admin_rolefor_temp_obj);//更新fact中变量值
                        update(spacechange_admin_roleselectdata);//更新fact中变量值
                        update(spacechange_admin_roleupdate_member_info);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "spacechange_admin_roleend1"
            when
            then
                        update(spacechange_admin_roledefault);//更新fact中变量值
                        update(spacechange_admin_rolefor_temp_obj);//更新fact中变量值
                        update(spacechange_admin_roleselectdata);//更新fact中变量值
                        update(spacechange_admin_roleupdate_member_info);//更新fact中变量值
            end