package cn.ibizlab.plm.wiki.logic.spacelogic.create_default_addon;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.space spacecreate_default_addondefault;
                global cn.ibizlab.plm.core.base.domain.addon spacecreate_default_addonaddon_filter;
                global cn.ibizlab.plm.core.base.domain.addon spacecreate_default_addonaddon_page;
                global cn.ibizlab.plm.core.base.domain.addon spacecreate_default_addonfor_temp_obj;
                global cn.ibizlab.plm.core.base.domain.addon spacecreate_default_addonnew_addon;
                    global cn.ibizlab.plm.core.base.service.IaddonService addonservice;
        global cn.ibizlab.plm.core.wiki.service.IspaceService iBzSysSpaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "spacecreate_default_addonbegin"
            when
            then
            end

            //逻辑处理节点[准备空间组件过滤参数]
            rule "prepareparam1"
            ruleflow-group "spacecreate_default_addonprepareparam1"
            when
            then
                            spacecreate_default_addonaddon_filter.set("n_owner_type_eq","space");
                            spacecreate_default_addonaddon_filter.set("n_owner_id_isnull","1");
                        update(spacecreate_default_addondefault);//更新fact中变量值
                        update(spacecreate_default_addonaddon_filter);//更新fact中变量值
                        update(spacecreate_default_addonaddon_page);//更新fact中变量值
                        update(spacecreate_default_addonfor_temp_obj);//更新fact中变量值
                        update(spacecreate_default_addonnew_addon);//更新fact中变量值
            end

            //逻辑处理节点[获取空间默认组件配置]
            rule "dedataset1"
            ruleflow-group "spacecreate_default_addondedataset1"
            when
            then
                        update(spacecreate_default_addondefault);//更新fact中变量值
                        update(spacecreate_default_addonaddon_filter);//更新fact中变量值
                        update(spacecreate_default_addonaddon_page);//更新fact中变量值
                        update(spacecreate_default_addonfor_temp_obj);//更新fact中变量值
                        update(spacecreate_default_addonnew_addon);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "spacecreate_default_addonloopsubcall1"
            when
            then
                        update(spacecreate_default_addondefault);//更新fact中变量值
                        update(spacecreate_default_addonaddon_filter);//更新fact中变量值
                        update(spacecreate_default_addonaddon_page);//更新fact中变量值
                        update(spacecreate_default_addonfor_temp_obj);//更新fact中变量值
                        update(spacecreate_default_addonnew_addon);//更新fact中变量值
            end

            //逻辑处理节点[组件填充数据属性]
            rule "prepareparam2"
            ruleflow-group "spacecreate_default_addonprepareparam2"
            when
            then
                            spacecreate_default_addonnew_addon.set("isenabled",spacecreate_default_addonfor_temp_obj.get("isenabled"));
                            spacecreate_default_addonnew_addon.set("ownersubtype",spacecreate_default_addonfor_temp_obj.get("ownersubtype"));
                            spacecreate_default_addonnew_addon.set("ownerid",spacecreate_default_addondefault.get("id"));
                            spacecreate_default_addonnew_addon.set("ownertype",spacecreate_default_addonfor_temp_obj.get("ownertype"));
                            spacecreate_default_addonnew_addon.set("addontype",spacecreate_default_addonfor_temp_obj.get("addontype"));
                            spacecreate_default_addonnew_addon.set("description",spacecreate_default_addonfor_temp_obj.get("description"));
                            spacecreate_default_addonnew_addon.set("name",spacecreate_default_addonfor_temp_obj.get("name"));
                            spacecreate_default_addonnew_addon.set("ordervalue",spacecreate_default_addonfor_temp_obj.get("ordervalue"));
                        update(spacecreate_default_addondefault);//更新fact中变量值
                        update(spacecreate_default_addonaddon_filter);//更新fact中变量值
                        update(spacecreate_default_addonaddon_page);//更新fact中变量值
                        update(spacecreate_default_addonfor_temp_obj);//更新fact中变量值
                        update(spacecreate_default_addonnew_addon);//更新fact中变量值
            end

            //逻辑处理节点[生成空间组件信息]
            rule "deaction1"
            ruleflow-group "spacecreate_default_addondeaction1"
            when
            then
                        addonservice.create(spacecreate_default_addonnew_addon);
                        update(spacecreate_default_addondefault);//更新fact中变量值
                        update(spacecreate_default_addonaddon_filter);//更新fact中变量值
                        update(spacecreate_default_addonaddon_page);//更新fact中变量值
                        update(spacecreate_default_addonfor_temp_obj);//更新fact中变量值
                        update(spacecreate_default_addonnew_addon);//更新fact中变量值
            end