package cn.ibizlab.plm.wiki.logic.spacelogic.delete;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.Space spacedeletedefault;
                global cn.ibizlab.plm.core.wiki.domain.Space spacedeleteupdate_obj;
                    global cn.ibizlab.plm.core.wiki.service.ISpaceService spaceservice;
        global cn.ibizlab.plm.core.wiki.service.ISpaceService iBzSysSpaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "spacedeletebegin"
            when
            then
            end

            //逻辑处理节点[设置删除状态]
            rule "prepareparam1"
            ruleflow-group "spacedeleteprepareparam1"
            when
            then
                            spacedeleteupdate_obj.set("isdeleted","1");
                            spacedeleteupdate_obj.set("id",spacedeletedefault.get("id"));
                        update(spacedeletedefault);//更新fact中变量值
                        update(spacedeleteupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[删除]
            rule "deaction1"
            ruleflow-group "spacedeletedeaction1"
            when
            then
                        spaceservice.update(spacedeleteupdate_obj);
                        update(spacedeletedefault);//更新fact中变量值
                        update(spacedeleteupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[删除最近访问]
            rule "rawsqlcall1"
            ruleflow-group "spacedeleterawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",spacedeletedefault.get("id"));
    String strSql="update recent set IS_DELETED=1 where owner_id=#{et.param0} and owner_subtype='space'";
                        iBzSysSpaceDefaultService.execute(strSql,param);//SQL调用
                        update(spacedeletedefault);//更新fact中变量值
                        update(spacedeleteupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "spacedeleteend1"
            when
            then
                        update(spacedeletedefault);//更新fact中变量值
                        update(spacedeleteupdate_obj);//更新fact中变量值
            end