package cn.ibizlab.plm.wiki.logic.spacelogic.move_out_category;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.Space spacemove_out_categorydefault;
                global cn.ibizlab.plm.core.wiki.domain.Space spacemove_out_categoryfor_temp_obj;
                global cn.ibizlab.plm.core.wiki.domain.Space spacemove_out_categorysrfactionparam;
                    global cn.ibizlab.plm.core.wiki.service.ISpaceService spaceservice;
        global cn.ibizlab.plm.core.wiki.service.ISpaceService iBzSysSpaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "spacemove_out_categorybegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "spacemove_out_categorydebugparam1"
            when
            then
                        update(spacemove_out_categorydefault);//更新fact中变量值
                        update(spacemove_out_categoryfor_temp_obj);//更新fact中变量值
                        update(spacemove_out_categorysrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "spacemove_out_categoryprepareparam1"
            when
            then
                                spacemove_out_categorydefault.set("categoryid",null);
                                spacemove_out_categorydefault.set("categoryname",null);
                                spacemove_out_categorydefault.set("categories",null);
                        update(spacemove_out_categorydefault);//更新fact中变量值
                        update(spacemove_out_categoryfor_temp_obj);//更新fact中变量值
                        update(spacemove_out_categorysrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "spacemove_out_categorydeaction1"
            when
            then
                        spaceservice.update(spacemove_out_categorydefault);
                        update(spacemove_out_categorydefault);//更新fact中变量值
                        update(spacemove_out_categoryfor_temp_obj);//更新fact中变量值
                        update(spacemove_out_categorysrfactionparam);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "spacemove_out_categoryend1"
            when
            then
                        update(spacemove_out_categorydefault);//更新fact中变量值
                        update(spacemove_out_categoryfor_temp_obj);//更新fact中变量值
                        update(spacemove_out_categorysrfactionparam);//更新fact中变量值
            end