package cn.ibizlab.plm.wiki.logic.spacelogic.recover;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.Space spacerecoverdefault;
                global cn.ibizlab.plm.core.wiki.domain.Space spacerecoverupdate_obj;
                    global cn.ibizlab.plm.core.wiki.service.ISpaceService spaceservice;
        global cn.ibizlab.plm.core.wiki.service.ISpaceService iBzSysSpaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "spacerecoverbegin"
            when
            then
            end

            //逻辑处理节点[设置删除状态]
            rule "prepareparam1"
            ruleflow-group "spacerecoverprepareparam1"
            when
            then
                            spacerecoverupdate_obj.set("isdeleted","0");
                            spacerecoverupdate_obj.set("id",spacerecoverdefault.get("id"));
                        update(spacerecoverdefault);//更新fact中变量值
                        update(spacerecoverupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[恢复]
            rule "deaction1"
            ruleflow-group "spacerecoverdeaction1"
            when
            then
                        spaceservice.update(spacerecoverupdate_obj);
                        update(spacerecoverdefault);//更新fact中变量值
                        update(spacerecoverupdate_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "spacerecoverend1"
            when
            then
                        update(spacerecoverdefault);//更新fact中变量值
                        update(spacerecoverupdate_obj);//更新fact中变量值
            end