package cn.ibizlab.plm.wiki.logic.spacelogic.un_favorite;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.plm.util.errors.BadRequestAlertException;
                global cn.ibizlab.plm.core.wiki.domain.Space spaceun_favoritedefault;
                global cn.ibizlab.plm.core.wiki.domain.Space spaceun_favoriteupdateobj;
        global cn.ibizlab.plm.core.wiki.service.ISpaceService iBzSysSpaceDefaultService;
        global cn.ibizlab.plm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "spaceun_favoritebegin"
            when
            then
            end

            //逻辑处理节点[删除收藏数据]
            rule "rawsqlcall1"
            ruleflow-group "spaceun_favoriterawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",curuser.getSessionParams().get("srfuserid"));
        param.put("param1",spaceun_favoritedefault.get("owner_id"));
    String strSql="delete from `favorite` where create_man = #{et.param0} and owner_id = #{et.param1}";
                        iBzSysSpaceDefaultService.execute(strSql,param);//SQL调用
                        update(spaceun_favoritedefault);//更新fact中变量值
                        update(spaceun_favoriteupdateobj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "spaceun_favoriteend1"
            when
            then
                        update(spaceun_favoritedefault);//更新fact中变量值
                        update(spaceun_favoriteupdateobj);//更新fact中变量值
            end